### ISSUE TITLE
Restart Loop, Docker-Compose Curseforge

### ISSUE THREAD

**Issue by Bupher** [itzg/docker-minecraft-server#1005]
Just as stated in the title, when I bring up the container, and watch docker PS, it just says restarting and continually restarts.

The compose file is shown below, I have tried two different 1.16 modpacks with no discernable change. Any help would be appreciated.

[docker-compose.txt](https://github.com/itzg/docker-minecraft-server/files/7011643/docker-compose.txt)
![image](https://user-images.githubusercontent.com/17689133/130007004-e9d2ceb8-9b56-4e8d-9f26-7ee3192e1b18.png)
![image](https://user-images.githubusercontent.com/17689133/130007061-daf842f9-8b4d-4382-9730-8628709180da.png)

**Comment by itzg** [comment]
I don’t what’s going on with the `cpus` or if you have enough memory. Please provide the container logs.

**Comment by Bupher** [comment]
My bad, first problem was me not having modpack.zip in the data folder. Second problem was "http://ftb.forgecdn.net/" could not be resolved, when when using the FTB_LEGACYJAVAFIXER option. Third problem was that my modpack.zip for the pack I was trying to use does not work. Moving the modpack, commenting out javafixer, and switching modpack fixed my problems.

**Comment by itzg** [comment]
Glad it worked in the end. Good to close the issue?

**Comment by Bupher** [comment]
Sure, the FTB_LEGACYJAVAFIXER problem still exists, but I do not need it atm.
