### ISSUE TITLE
GENERIC_PACK unzip chokes with large zips

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#1017]
The unzip action seems to choke if the zip is too volumous, causing 'bad zipfile offset' errors on unzip.
Suggest using `jar xvf file.zip` instead of the `unzip` utility.

**Comment by ChipWolf** [comment]
```
minecraft@minecraft-forge-squirtle-prod-5dff7469b8-8lj9c:/tmp$ curl -fsSL -o /tmp/generic_pack.zip "${GENERIC_PACK}" curl: (18) transfer closed with 3210594 bytes remaining to read
```

Looks like a Content-Length issue after some further investigation

**Comment by ChipWolf** [comment]
Adding `--ignore-content-length` to the curl command works for us

```
minecraft@minecraft-forge-squirtle-prod-5dff7469b8-8lj9c:/tmp$ curl -fsSL -o /tmp/generic_pack.zip "${GENERIC_PACK}"
curl: (18) transfer closed with 3210594 bytes remaining to read
minecraft@minecraft-forge-squirtle-prod-5dff7469b8-8lj9c:/tmp$ curl -fsSL --ignore-content-length -o /tmp/generic_pack.zip "${GENERIC_PACK}"
minecraft@minecraft-forge-squirtle-prod-5dff7469b8-8lj9c:/tmp$
```

**Comment by itzg** [comment]
I need to add error checking at

https://github.com/itzg/docker-minecraft-server/blob/0ae15c2b3c9c0500933283e55c4cbb6b2bd4a930/start-finalSetupModpack#L157

**Comment by itzg** [comment]
> Adding `--ignore-content-length` to the curl command works for us

I would offer to include that option in the generic pack handling, but seems like a risky option to use unconditionally. Will you be able to fix the server serving up that file?

**Comment by ChipWolf** [comment]
> 
> 
> > Adding `--ignore-content-length` to the curl command works for us
> 
> I would offer to include that option in the generic pack handling, but seems like a risky option to use unconditionally. Will you be able to fix the server serving up that file?

Agree!
It's a CDN provider in our case, I've sent them a support request.

**Comment by itzg** [comment]
Pushed image with error handling on that curl call.

**Comment by ChipWolf** [comment]
LGTM
