### ISSUE TITLE
Need specific version of 1.12.2 forge

### ISSUE THREAD

**Issue by drakosoldier298** [itzg/docker-minecraft-server#1019]
i use portaijner to run my docker instance and was wondering how i would go about grabbing a specific version of forge i need 1.12.2 - 14.23.5.2854 but the latest is 1.12.2 - 14.23.5.2855 and idk if its possibel to specify exact forge versions

**Comment by itzg** [comment]
`FORGEVERSION` https://github.com/itzg/docker-minecraft-server#running-a-forge-server
