### ISSUE TITLE
EULA=TRUE accept problem in QNAP cointainer station > docker

### ISSUE THREAD

**Issue by ddominq** [itzg/docker-minecraft-server#1021]
in Environment:

AUTOPAUSE_KNOCK_INTERFACE eth0
AUTOPAUSE_PERIOD 10
AUTOPAUSE_TIMEOUT_EST 3600
AUTOPAUSE_TIMEOUT_INIT 600
AUTOPAUSE_TIMEOUT_KN 120

ELUA TRUE

ENABLE_AUTOPAUSE false
ENABLE_RCON true
GID 1000
JAVA_HOME /opt/java/openjdk
JAVA_VERSION jdk-16.0.1+9
LANG en_US.UTF-8
LANGUAGE en_US:en
LC_ALL en_US.UTF-8
MEMORY 1G
ONLINE_MODE TRUE
PATH /opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RCON_PASSWORD minecraft
RCON_PORT 25575
SERVER_NAME Dedicated Server
SERVER_PORT 25565
TYPE SPIGOT
UID 1000
VERSION LATEST

start effect
[init] Please accept the Minecraft EULA at
[init]   https://account.mojang.com/documents/minecraft_eula
[init] by adding the following immediately after 'docker run':
[init]   -e EULA=TRUE

**Comment by itzg** [comment]
You have a typo

```
ELUA TRUE
```

Should be `EULA`

**Comment by ddominq** [comment]
I typed it in Environment as I showed in the first post, it doesn't do anything.
My son found a good solution. Just put a file named elua.txt in the _data directory (inside your compilation hash) 
In the TXT file write only elua=true. It works!

By the way. Thank you very much for your great work.

Now since I have uploaded the world here from a backup it remains for me to solve a few minor issues like;
"Unknown loot table called minecraft:entities/reference/extra/ender dragon"
or
"UUID of added entity already exists: EntityArmorStand['Armor Stand'/177, l='ServerLevel[world]', x=16562064.50, y=1000.00, z=-22242911.50]"

**Comment by itzg** [comment]
That's a good work around. 

Can you provide a screenshot of your QNAP config screen with the EULA variable? I'm still curious what is not working there.

**Comment by ddominq** [comment]
![Screenshot 2021-08-30 at 14 28 01](https://user-images.githubusercontent.com/50619298/131339467-cfb85f87-4c53-44db-9bed-6eca2bd05b35.png)
Of course.
I just noticed that the 1G memory value has been erased. It appeared in the final server.
The problem is that the parameters entered at the beginning are uneditable in QNAP. I came up with the idea of changing the limit with the slider at the top.

**Comment by itzg** [comment]
You have spelled EULA wrong. Look at the red underlined item.

**Comment by itzg** [comment]
...and the container memory limit is completely separate from the JVM heap limit set with MEMORY. Both are for you to adjust.

**Comment by ddominq** [comment]
> You have spelled EULA wrong. Look at the red underlined item.

I create new serwer with EULA and it's start out of the box! 👍

**Comment by ddominq** [comment]
> ...and the container memory limit is completely separate from the JVM heap limit set with MEMORY. Both are for you to adjust.
Is it optimal to set 2GB each for max 10 players? Is it better to have more on VM than for Minecraft? If so, by how much?

**Comment by itzg** [comment]
The container (it's a process not a VM) memory should be higher than JVM heap memory. There's no exact formula but start with 25%-50% more.

**Comment by ddominq** [comment]
> The container (it's a process not a VM) memory should be higher than JVM heap memory. There's no exact formula but start with 25%-50% more.
Thank you very much! With a setting of 3GB for process and 2GB for Minecraft. It runs much more efficiently, and can use over 90% of the CPU at startup! Revelation.
