### ISSUE TITLE
Can't find Curseforge modpack

### ISSUE THREAD

**Issue by camielverdult** [itzg/docker-minecraft-server#1023]
Hi all,

I am trying to run [this](https://www.curseforge.com/minecraft/modpacks/better-minecraft-modpack-new) modpack with the following command: 

```bash
docker run -d -v /path/on/host:/data -e TYPE=CURSEFORGE \
    -e CF_SERVER_MOD=better-mc.zip \
    -e VERSION=1.16.5 \
    -p 25569:25565 -e EULA=TRUE --name better-mc itzg/minecraft-server:java8
```

The container starts and stops immediately with the following output:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1000          4096 Aug 30 19:52 /data'
[init] Resolved version given 1.16.5 into 1.16.5
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] FTB server modpack /data/better-mc.zip not found.
```

Can anyone point me out what I am doing wrong here? I also tried the fabric version of the same modpack, updated type to fabric to point to the installer file but it gave me a `java.IllegalAccessError`, even when using the java8 branch

**Comment by itzg** [comment]
For `-v /path/on/host:/data` make sure that left hand path is a real path on your host. In that directory make sure you have the modpack file `better-mc.zip`.

**Comment by gammaliel** [comment]
I've been trying to use a modpack the same way as @camielverdult and I'm unable to make it work, I keep getting the same errors.

I used:
`docker run -d -v ~/data -e TYPE=CURSEFORGE -e CF_SERVER_MOD=SIMPLE-SERVER-FILES-1.8.0.zip -e VERSION=1.16.5 -p 25569:25565 -e EULA=TRUE --name mc itzg/minecraft-server:java8`

Where **data** would be a folder inside my host's HOME containing the zip file. Is there something else that should be done? Is there a way to run a modpack without downloading the zip file manually?

**Comment by itzg** [comment]
@camielverdult did you change `/path/on/host` to be a real path on your host with the `better-mc.zip` file in it? Can you provide an `ls` of that real directory?
