### ISSUE TITLE
Setup Plugin

### ISSUE THREAD

**Issue by domesticwarlord86** [itzg/docker-minecraft-server#1029]
I'm wondering if you might be able to help me out here. I'm running a standard server from your docker. No mod packs or anything. I want to be able to use [https://github.com/GeyserMC/Geyser/wiki/Setup](Geyser) so I can have Bedrock clients connect to the same server as my Java clients. 
The problem is I don't really know how to get the server to read the plugin folder. I mounted a Plugins folder inside the container and tossed the .jar in there, but the server didn't see to do anything with it. Have any ideas?

If it helps, here's the yml I'm using to create the docker container, with all the ENV variables in it.
https://pastebin.com/2YpUuA4W

**Comment by itzg** [comment]
A standard/vanilla server from Mojang does not support plugis or mods. Choose an appropriate [server type](https://github.com/itzg/docker-minecraft-server#server-types).

BTW, the mount `'/:/SERVER'` looks very dangerous to me. You're giving the container access to your entire host filesystem .

**Comment by 9Mad-Max5** [comment]
> A standard/vanilla server from Mojang does not support plugins or mods. Choose an appropriate [server type](https://github.com/itzg/docker-minecraft-server#server-types).
> 
> BTW, the mount `'/:/SERVER'` looks very dangerous to me. You're giving the container access to your entire host filesystem .

Yesterday I ran in to a similiar issue with TYPE=Paper
The Container has been started but the plungins from the mount point /plugins didn't get collected.
If i place the manually in the /data/plugins directory they had the wrong owner privileges so I manually need to change it to 1000:1000.

**Comment by itzg** [comment]
@9Mad-Max5 please open a new issue
