### ISSUE TITLE
ERROR: failed to download 

### ISSUE THREAD

**Issue by mogadanez** [itzg/docker-minecraft-server#103]
```
docker run -d -it -v /path/mc:/data \
    -e TYPE=SPIGOT -e VERSION=1.8 \
        -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server

```

logs:

```
usermod: no changes
Switching to user 'minecraft'
Checking version information.
Checking type information.
Downloading Spigot
ERROR: failed to download from https://ci.mcadmin.net/job/Spigot/2/artifact/spigot-1.8.jar due to (error code was 4)
```

same for BUKKIT( with different path )

**Comment by itzg** [comment]
With a quick check from my phone I can see their SSL cert has some issues. I'll research it some more and see if I need/should relax the SSL checking.

**Comment by voruti** [comment]
Still not working, but different error:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Mar 13 22:20 /data'
[init] Resolved version given 1.8 into 1.8
[init] Resolving type given SPIGOT
[init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.8.jar ...

ERROR: failed to download from https://cdn.getbukkit.org/spigot/spigot-1.8.jar
       Visit https://getbukkit.org/download/spigot to lookup the
       exact version, such as 1.4.6-R0.4-SNAPSHOT or 1.8-R0.1-SNAPSHOT-LATEST
```

**Comment by itzg** [comment]
Some of their older versions are not intuitive at all. If you click through the "1.8" entry, it takes you [to this page](https://getbukkit.org/get/WAH0jXqYA2s3Gzzg3toWHG1R3lHNCNZY) where the specific, cryptic version is shown. Worst still, it's case sensitive, so I had to grab the version lower down with lowercase "-latest":

![image](https://user-images.githubusercontent.com/988985/111051617-043c2a00-841a-11eb-9f8c-c8748bdaf658.png)

**Comment by voruti** [comment]
I can confirm this is working with `VERSION=1.8-R0.1-SNAPSHOT-latest`.
How can this be documented? (e. g. if someone else wants to setup a Spigot server for Minecraft < 1.11)
Maybe somewhere at https://github.com/itzg/docker-minecraft-server#Versions ?

**Comment by itzg** [comment]
I tried to spell that out in the error message:

```
       Visit https://getbukkit.org/download/spigot to lookup the
       exact version, such as 1.4.6-R0.4-SNAPSHOT or 1.8-R0.1-SNAPSHOT-LATEST
```

however, I noticed I need to fix the example in the message from `1.8-R0.1-SNAPSHOT-LATEST` to `1.8-R0.1-SNAPSHOT-latest`

**Comment by itzg** [comment]
I updated [the README section](https://github.com/itzg/docker-minecraft-server#running-a-bukkitspigot-server) and further explained the filename quirk in the error message.

**Comment by voruti** [comment]
> I tried to spell that out in the error message:

Oops, yes that makes sense. I completely overlooked that and just recognized there was some error, not reading the error message.

Looks fine to me.
