### ISSUE TITLE
Minecraft docker image stop prematurely

### ISSUE THREAD

**Issue by jedo-tm** [itzg/docker-minecraft-server#1040]
### Discussed in https://github.com/itzg/docker-minecraft-server/discussions/1038

<div type='discussions-op-text'>

<sup>Originally posted by **jedo-tm** September 11, 2021</sup>
Hi, 

Recently my docker images stops prematurely. I have tried to investigate different causes but is unsuccessful. I am running it on a kubuntu 20.04 LTS.

- It happens with both vanilla and forge servers
- It happens with and without autopause enabled.
- I have tried to increase memory (    -e MEMORY=10G )   
- I have tried to remove and re-create  container.
- I have deleted and re-downloaded image. 

In the most recent  crash :

- I had started the docker container
-  attached to the docker and left. 
- After 5 idle hours I tried to connect minecraft client but was not successfull
- I looked at terminal where I had run $docker attach mcimage 
- I could exit with ctrl p ctrl q, but could not stop or start the container again

```
[Autopause loop] No client reconnected - stopping
[12:17:21] [RCON Listener #1/INFO] [minecraft/MinecraftServer]: Rcon connection from: /127.0.0.1
[12:17:21] [RCON Client #6/INFO] [minecraft/DedicatedServer]: [Rcon: Saved the world]
[2021-09-11T12:17:21+0200] [Autopause] Pausing Java process
read escape sequence
$ docker attach mcimage

You cannot attach to a stopped container, start it first

$docker start mcimage; docker attach mcimage

Error response from daemon: driver failed programming external connectivity on endpoint mcimage (c8d56783d606cde4af32ee08a442f901f24e2aa2b838c927bafccf90720b267d): Error starting userland proxy: listen tcp 0.0.0.0:3555: bind: address already in use
Error: failed to start containers: mcimage
You cannot attach to a stopped container, start it first_
$docker stop mcimage
mcimage
$docker start mcimage; docker attach mcimage
_Error response from daemon: driver failed programming external connectivity on endpoint mcimage (c8b3104c686f18b41f6b33be39bd7dee43b7fc2578426f1e641f67e5d788900f): Error starting userland proxy: listen tcp 0.0.0.0:3555: bind: address already in use
Error: failed to start containers: mcimage
You cannot attach to a stopped container, start it first
```
If  I log into a different docker image, I can see that the processes running are a mixture of root and minecraft user processes running and this "picture" is general for all my containers

```
 $ docker exec -it mcimage2

root@fa21d4b2d7f3:/data# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND\n
minecra+       1  0.1  0.0 705272  3488 pts/0    Ssl+ 17:22   0:00 mc-server-runner --stop-duration 60s java -Xms4G -Xmx4G -jar minecraft_server.1.17.1.jar
minecra+      36  0.0  0.0   7328  3784 pts/0    S+   17:22   0:00 /bin/bash /autopause/autopause-daemon.sh
minecra+      66  408 10.4 10258468 3423352 pts/0 Sl+ 17:22   2:59 java -Xms4G -Xmx4G -jar minecraft_server.1.17.1.jar
root          94  0.0  0.0   4884  2220 ?        Ss   17:22   0:00 /usr/sbin/knockd -c /tmp/knockd-config.cfg -d -i eth0
root         215  0.1  0.0   7460  4068 pts/1    Ss   17:22   0:00 bash
minecra+     234  0.0  0.0   5476   520 pts/0    S+   17:22   0:00 sleep 10
root         235  0.0  0.0   9116  3476 pts/1    R+   17:23   0:00 ps aux*root@fa21d4b2d7f3:/data#** 
```
Does anyone have ideas how to solve this or further troubleshoot the problem?

</div>

**Comment by itzg** [comment]
@jedo-tm you opened a discussion and an issue. Can you pick one to avoid the noise and confusion?

**Comment by jedo-tm** [comment]
Hi @itzg 
 
I realized that an issue might be more appropriate when looking at how people have used issues and discussions - I cant figure out how to close the discussion - I think it might be something that only the moderator can do?? Sorry I am not that used to posting in github forum. By the way thank you so much for bringing this docker image, I think it is fantastic.

**Comment by itzg** [comment]
Oh yeah, I can't see how to close the discussion either. Ok, we'll continue here in the issue 😀

@Oekn5w do you have any suggestions to debug?

**Comment by Oekn5w** [comment]
@jedo-tm  The port seems to be used by something else, although 3555 is not near the range used in the image (I know you can rebind it to whatever). Are you using that port for the container?

Searching for the error ( [for example here](https://stackoverflow.com/questions/39508018/docker-driver-failed-programming-external-connectivity-on-endpoint-webserver) ) suggests to check the running containers (`docker ps`), clearing up docker stuff (`docker prune`), restarting the docker service and checking what is binding the port (`ss -tulpn`).

From the description above, I kind of doubt, that this is something specifically tied to the image.
Despite that, can you provide the docker-compose file or docker run command?

**Comment by jedo-tm** [comment]
@Oekn5w @itzg 

I think I now can confirm that it has nothing to do with the docker image . I had the same problem on multiple constainers with the same image ( well the java version used was different for some of the images). The container which has been run for the longest time (~ 3month) is tied to a port which had not been used by other programs as far as i know. This container started to crash . 

A few days ago, I suspected that my docker installation was the real issue. The docker installation was a snap installed from the linux distributions (kubuntu) software center 'discover'. I completely deleted that installation and instead added Dockers own ubuntu APT source as descibed [here] (https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04). and for the last four days I have had no restarts The plot below shows the number of log files per day for one of the containers. Log files could of course also be due to other issues but it sort of gives an indication of when the problem start, which seems to 27th of august 

![logfiles](https://user-images.githubusercontent.com/33766127/134080403-e6101974-9a0b-42ed-ae06-39fc3cd0b71b.png)

When running

`journalctl -u snapd|grep docker`

I see many entries like the ones below. I don't know what they mean, but there seems to be a change around ~ 27th of august which coincide with my problem . So far my conclusion is that the snap for docker in ubuntu caused the problem  - maybe an update was pushed? My problem seems to have been resolved by using Dockers APT source.

```
Aug 25 21:47:49 asus snapd[1244537]: storehelpers.go:551: cannot refresh: snap has no updates available: "core18", "docker", "snapd"
Aug 26 01:17:49 asus snapd[1244537]: storehelpers.go:551: cannot refresh: snap has no updates available: "core18", "docker", "snapd"
Aug 26 07:02:49 asus snapd[1244537]: storehelpers.go:551: cannot refresh: snap has no updates available: "core18", "docker", "snapd"
Aug 26 14:57:49 asus snapd[1244537]: storehelpers.go:551: cannot refresh: snap has no updates available: "core18", "docker", "snapd"Aug 26 19:02:49 asus snapd[1244537]: storehelpers.go:551: cannot refresh: snap has no updates available: "core18", "docker", "snapd"
Aug 27 02:12:49 asus snapd[1244537]: storehelpers.go:551: cannot refresh: snap has no updates available: "core18", "docker", "snapd"
Aug 27 08:17:49 asus snapd[1244537]: storehelpers.go:551: cannot refresh: snap has no updates available: "core18", "docker", "snapd"
Aug 27 15:08:13 asus snapd[1244537]: taskrunner.go:271: [change 11 "Setup snap \"docker\" (1125) security profiles" task] failed: cannot update mount namespace of snap "docker": cannot update preserved namespace of snap "docker": cannot update snap namespace: cannot create symlink in "/etc/docker": existing file in the way
Aug 27 15:08:15 asus snapd[1244537]: handlers.go:511: Reported install problem for "docker" as d718d3d8-0737-11ec-a5d4-fa163e102db1 OOPSID
Aug 27 22:47:58 asus snapd[1003]: taskrunner.go:271: [change 12 "Run post-refresh hook of \"docker\" snap if present" task] failed: run hook "post-refresh":
Aug 27 22:47:58 asus snapd[1003]: cannot update snap namespace: cannot create symlink in "/etc/docker": existing file in the way
Aug 27 22:48:01 asus snapd[1003]: handlers.go:511: Reported install problem for "docker" as 116ecebc-0778-11ec-a5f9-fa163e102db1 OOPSID
Aug 28 03:12:59 asus snapd[1003]: taskrunner.go:271: [change 13 "Setup snap \"docker\" (1125) security profiles" task] failed: cannot update mount namespace of snap "docker": cannot update preserved namespace of snap "docker": cannot update snap namespace: cannot create symlink in "/etc/docker": existing file in the way
Aug 28 03:13:00 asus snapd[1003]: handlers.go:511: Reported install problem for "docker" as already-reported
Aug 28 06:58:02 asus snapd[1003]: taskrunner.go:271: [change 14 "Setup snap \"docker\" (1125) security profiles" task] failed: cannot update mount namespace of snap "docker": cannot update preserved namespace of snap "docker": cannot update snap namespace: cannot create symlink in "/etc/docker": existing file in the way
Aug 28 06:58:03 asus snapd[1003]: handlers.go:511: Reported install problem for "docker" as already-reported
Aug 28 13:42:59 asus snapd[1003]: taskrunner.go:271: [change 15 "Setup snap \"docker\" (1125) security profiles" task] failed: cannot update mount namespace of snap "docker": cannot update preserved namespace of snap "docker": cannot update snap namespace: cannot create
```

I appreciate your interest in trying to solve the problem

For what it is worth  - here is my docker run file:

```
docker run -d \
    -v /path:/data \
    -e TZ=Europe/Copenhagen \
    -it -p 3555:25565 \
    -e EULA=TRUE \
    -e MEMORY=4G \
    -e AUTOPAUSE_TIMEOUT_EST=60 \
    -e AUTOPAUSE_TIMEOUT_INIT=60 \
    -e ENABLE_AUTOPAUSE=TRUE \
    -e DEBUG=TRUE \
    -e DEBUG_EXEC=TRUE \
    -e DEBUG_MEMORY=TRUE \
    --restart always -it \
    --name nameofserver  itzg/minecraft-server
```
And the "code" for making the plot data file which counts the number of logfiles in the minecraft server
```
ls logs| grep -o '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' | xargs -n1 | sort | uniq -c | awk '{print $2,$1}'  > data.text
```

And from GNUplot
```
gnuplot> set datafile separator " "
gnuplot> set xdata time
gnuplot> set format x "%Y-%m-%d"
gnuplot> set timefmt "%Y-%m-%d"
gnuplot> set ylabel "#logfiles"
gnuplot> plot 'dat.txt' u 1:2 w l

```

**Comment by itzg** [comment]
Thanks for the follow up information. 

Good to close the issue?

**Comment by jedo-tm** [comment]
Ok  :)
