### ISSUE TITLE
ATM6 Startup Script not working correctly due do missing "ping" Command

### ISSUE THREAD

**Issue by NightHammer1000** [itzg/docker-minecraft-server#1041]
Heya.

The ATM6 Startup Script does a check if the Server is Online at startup by pinging 1.1.1.1 and 8.8.8.8
These checks fail due to the missing ping command.

It does not impact the Startup Script itself, but it triggers my Log Watchdog on each restart.

**Comment by itzg** [comment]
ping is now included in the latest image, so it's ready to test

**Comment by NightHammer1000** [comment]
Message is gone.
Great! 
Thanks!
