### ISSUE TITLE
/plugins structure not working properly

### ISSUE THREAD

**Issue by 9Mad-Max5** [itzg/docker-minecraft-server#1044]
Im using TYPE: PAPER in the docker-compose.
As described in the docs I mounted the /plugins folder.
Inserted there my GeyserMC.jar and Floodgate.jar.
But those have not been used in any way.
As well, I noticed the owner of the plugins folder is not 1000:1000 minecraft it is root.

From the host system, I'm manually copied the files to /data/plugins.
But unfortunately, then I ran in to the owner issue again as, the files are owned by root instead of minecraft.
So I manually need to change the ownership.

Greats

**Comment by itzg** [comment]
Can you also provide the container logs?

**Comment by itzg** [comment]
It found the mods, but both are invalid id you look at your logs 

```
[22:45:53] [Server thread/ERROR]: Could not load 'plugins/floodgate-spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
```

```
[22:45:53] [Server thread/ERROR]: Could not load 'plugins/Geyser-Spigot.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
```

This is something you need to fix. It's not a problem with the image.

**Comment by 9Mad-Max5** [comment]
Hi,

I got your point, but the root cause seems to be, for me, this line:
`Caused by: java.io.FileNotFoundException: plugins/floodgate-spigot.jar (Permission denied)`

As it hadn't the correct owner group, the parsing has failed.
After I changed manually the ownership, everything worked.
This printout was possible after I moved the file manually to /data/plugins.

If I understood the documentation correctly usually the files from the folder /plugins should be imported automatically.
But this didn't worked either.

**Comment by itzg** [comment]
Yes, `/plugins` gets synchronized to `/data/plugins` but if you have permission problems on your host side there's only so much the image fix. 

You haven't yet provided your compose file. I can't help make without that.

Have you tried moving away the data path to let the container set it up properly?

**Comment by 9Mad-Max5** [comment]
No it is the permission inside the container not on the host site.
The container needs to align the permissions inside from it.
`services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server-java
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      UID: $PUID
      GID: $PGID
      TZ: $TZ
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: MC Mad-Max
      DEFAULT_PLAYER_PERMISSION_LEVEL: "member" # Options: visitor, member, operator
      MEMORY: 6G
      LEVEL_NAME: The Gloriuos World
      VIEW_DISTANCE: "8"
      TICK_DISTANCE: "4"
      MAX_THREADS: "8"
      #DISABLE_HEALTHCHECK: "true"
    ports:
      - 19132:19132/udp
      - 25565:25565
    volumes:
      - $DOCKERDIR/Minecraft-Server-Java/data:/data
    stdin_open: true
    tty: true`

**Comment by itzg** [comment]
Thanks, that helps.

- Can you provide output from `ls -ld $DOCKERDIR/Minecraft-Server-Java/data` from the host side?
- Can you provide `ls -l $DOCKERDIR/Minecraft-Server-Java/data/plugins`?
- I don't see a `volumes` entry for `/plugins`. If you were trying that before, can you do the same `ls -l` for that host path?

**Comment by 9Mad-Max5** [comment]
Ah sorry for the missing volume at plugins.
I removed it as it didn't worked out and thought maybe this is part of the issue..

```
[/share/Container/Minecraft-Server-Java] # ls -ld data
drwxrwxr-x 8 Michael 1000 4096 2021-09-14 21:42 data/
[/share/Container/Minecraft-Server-Java] # ls -ld data/plugins
drwxr-xr-x 5 Michael 1000 4096 2021-09-14 00:53 data/plugins/
[/share/Container/Minecraft-Server-Java] # ls -l plugins
total 0
[/share/Container/Minecraft-Server-Java] #

```
