### ISSUE TITLE
Autopause with Geyser

### ISSUE THREAD

**Issue by kjburr** [itzg/docker-minecraft-server#1046]
I have a small feature request to add Geyser(https://github.com/GeyserMC/Geyser) functionality with autopause.  Currently if you connect from a bedrock client on a paused server it does not detect the bedrock client at all.  The server also pauses if your connected and playing on the server ie not detecting the bedrock client.

I've tried diving into this myself and went as far as editing the knockd-config.cfg and adding the extra port but that hadn't made a difference.  Maybe it's something that can be added later on.  Thank you

**Comment by itzg** [comment]
When you tried the config change did you account for 19132 being UDP with

```
sequence = 19132:udp 
```

and removing the `tcpflags`?

**Comment by kjburr** [comment]
Yea I did actually.  My config looks like this

[unpauseMCServer-server]
 sequence = 25565,19132:udp
 seq_timeout = 1
 command = /usr/sbin/gosu minecraft:minecraft /autopause/resume.sh
 tcpflags = syn
 
 Sorry I should've mentioned I was trying to allow both 25565 and 19132 to have autopause as I'm running Geyser as a plugin.  Would removing the tcpflags still be required in this case?  Thanks again

**Comment by itzg** [comment]
Since that is the sequence of port knocks you'll instead want to try a whole separate section like

```
[unpauseMCServer-bedrock]
 sequence = 19132:udp 
 command = /usr/sbin/gosu minecraft:minecraft /autopause/resume.sh
```

**Comment by kjburr** [comment]
That worked! The only other thing I'm unsure if it's intended but RCON constantly tries to save when it tries to pause.  If the bedrock client is minimized to the background the server will finally pause kicking the client.  This isn't an issue for the java side I'm guessing because of the differences between how the tcp/udp protocols work.

 [01:46:02 INFO]: kjburr joined the game
[01:46:02 INFO]: kjburr[/172.20.0.1:0] logged in with entity id 3363 at ([world]181.53487, 83.00181, -319.29227)
[Autopause loop] No client connected since startup / knocked - stopping
[01:46:27 INFO]: Thread RCON Client /127.0.0.1 started
[01:46:27 INFO]: [Rcon: Saved the game]
[01:46:27 INFO]: Thread RCON Client /127.0.0.1 shutting down
[2021-09-16T01:46:27+00:00] [Autopause] Pausing Java process
[Autopause loop] Server was knocked - waiting for clients or timeout

I did have the timeout set low for testing purposes, probably wouldn't be an issue if it was set high enough.  But a save-all consistently might be an issue?  I could just disable rcon entirely but hey it's a feature I had it enabled lol.

**Comment by itzg** [comment]
Excellent. I'm trying to think if rcon even needs to be included as a knock-able port. 

@Oekn5w , I can see its inclusion being good for human initiated rcon, but the backup initiated does seem to unnecessarily wake up the server. What are you latest thought?

**Comment by itzg** [comment]
I went ahead and added the bedrock knock section to the latest images.

**Comment by kjburr** [comment]
Thank you!  Would the server trying to pause even though a client is connected be fine?  From the above stacktrace the server attempts to pause and then the client knocks.  I'm guessing that's cancelling out the pause and looping around?  It does this constantly but allows the bedrock client to stay connected and wake the server.

**Comment by Oekn5w** [comment]
Unfortunately I don't have access to the bedrock client, but this is an interesting read.

Regarding rcon @itzg : I have included it  for the interaction from external, if you don't want that, you wouldn't bind the port to external. I figured it is better that way, than having it timeout or something with a strange error because the process is stopped. rcon commands don't connect a client, so the server should pause pretty quickly again. Internal rcon command call to the loopback interface, not the external one, so they won't trigger knockd.

Regarding reknocking @kjburr : The bedrock connections are not checked for in here: 
https://github.com/itzg/docker-minecraft-server/blob/bdeab5bb9c166857eadf1ea0abdb50c16a738c41/files/autopause/autopause-fcns.sh#L25 
So it'll pause the server, with it being immediately reknocked. @itzg I think we should add another env like `SERVER_PORT_BEDROCK_CLIENTS` and implement that in the config file and that line.
@kjburr Can you exec the `netstat -tn` command in the container with the bedrock client connected?

**Comment by itzg** [comment]
> Regarding rcon @itzg : I have included it for the interaction from external, if you don't want that, you wouldn't bind the port to external. I figured it is better that way, than having it timeout or something with a strange error because the process is stopped. rcon commands don't connect a client, so the server should pause pretty quickly again. Internal rcon command call to the loopback interface, not the external one, so they won't trigger knockd.

There are two ways of setting up the backup container where one uses inter-container networking. In that case it won't be over loopback, but like said the server will quickly see no connections remaining and re-pause.

Hmm, Bedrock might be tricky to support since it uses UDP, so therefore netstat may or may not reveal active "connections".

**Comment by kjburr** [comment]
Just in case it helps I did run netstat -tn with bedrock connected and got the following

# netstat -tn
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 172.20.0.3:48136        146.59.205.175:443      ESTABLISHED
tcp        0      0 172.20.0.3:36016        85.214.21.103:443       ESTABLISHED
tcp        0      0 172.20.0.3:34404        172.67.216.193:443      TIME_WAIT
tcp        0      0 172.20.0.3:37322        104.24.31.82:443        TIME_WAIT
tcp        0      0 172.20.0.3:56132        172.67.151.184:443      ESTABLISHED
tcp        0      0 172.20.0.3:35962        85.214.21.103:443       ESTABLISHED
tcp        0      0 172.20.0.3:50894        104.27.196.95:443       TIME_WAIT
tcp        0      0 172.20.0.3:36492        104.21.21.184:443       ESTABLISHED
tcp        0      0 172.20.0.3:36018        85.214.21.103:443       ESTABLISHED
tcp        0      0 172.20.0.3:52110        185.199.111.133:443     ESTABLISHED
tcp        0      0 172.20.0.3:37302        104.26.15.192:443       ESTABLISHED
tcp        0      0 127.0.0.1:49254         127.0.0.1:25565         TIME_WAIT

**Comment by Oekn5w** [comment]
Hmm, is there a way to check for those connections by knockd? Write the uptime on each knock (to an ENV). Compare the last written value in the deamon file function when checking for connections. Short timeout of maybe 5 seconds for client connected detection.

**Comment by itzg** [comment]
I was just thinking, rather than using TCP and/or UDP activity to infer users still connected to the server it would be more robust and portable to use the included https://github.com/itzg/mc-monitor. I could even add a command line flag to output only player count to make it easy to script.

**Comment by Oekn5w** [comment]
Sounds good if the monitor also picks up the bedrock clients in Geyser. What is your idea of a batchable interaction? `--porcelain --playercount` (analogue to git) with immediate timeout maybe?

**Comment by itzg** [comment]
Added command line option in 

https://github.com/itzg/mc-monitor/releases/tag/0.10.0
