### ISSUE TITLE
Impossible to select specific snapshot

### ISSUE THREAD

**Issue by meekah7** [itzg/docker-minecraft-server#1055]
Using the Version configuration parameter it is only possible to select specific full releases. I'm not sure whether this is possible but it would be nice to be able to also select specific snapshot versions because now with Minecraft's new 1.18 world generation snapshots the maps are not cross-version compatible.

**Comment by itzg** [comment]
Can you provide examples of what you tried and logs from those not working?

**Comment by meekah7** [comment]
Sorry, there seems to have been some miscommunication on our end. Seems like our map data corrupted because we opened the map in 1.17.1

**Comment by itzg** [comment]
Thanks for following up.
