### ISSUE TITLE
Fabric Server With Synology Docker. 

### ISSUE THREAD

**Issue by NLGaming92** [itzg/docker-minecraft-server#1057]
Hello, is it possible to run a fabric Server with docker for Synology. I know you can change the version from Vanille to Fabric, but when I want to start my server he will crash always, Am I overlooking something or is it not possible.

**Comment by itzg** [comment]
That's possible. Can you provide the container logs?

**Comment by NLGaming92** [comment]
> That's possible. Can you provide the container logs?

Hello, i just found it. I must place the installer jar and Accept the eula, now it's working fine.
