### ISSUE TITLE
Spiget plugins ignored

### ISSUE THREAD

**Issue by ghost** [itzg/docker-minecraft-server#1058]
![image](https://user-images.githubusercontent.com/36360774/134774307-34c34c87-a9a1-4735-a4a5-a82266fb1394.png)
![image](https://user-images.githubusercontent.com/36360774/134774312-5af6bb32-bb96-4c59-b5a2-5bbb52c0c92d.png)
The PLUGINS env is ignored too

**Comment by itzg** [comment]
I'm not sure why you think this is an issue with this docker image.

**Comment by martinlacorrona** [comment]
As you see there, the plugin PaTzCore need LuckPerms... then you need to install LuckPerms in the folder.

And it's not Spiget, is **Spigot**.
