### ISSUE TITLE
Simulation Distance variable -e flag

### ISSUE THREAD

**Issue by finndo77** [itzg/docker-minecraft-server#1065]
I have not been able to set the simulation distance in server.properties via
-e SIMULATION_DISTANCE=
or
-e CFG_SIMULATION_DISTANCE=

is this something that you need to add?  it is a parity add from bedrock, it is called TICK_DISTANCE on the minecraft-bedrock-server documentation.

this was added to java in snapshot 21w38a
https://www.minecraft.net/en-us/article/minecraft-snapshot-21w38a

this is the startup script i am using if needed, everything is working except simulation distance (I put each entry on a separate line, because it was hard to read in the narrow columns on github)
```
#! /bin/bash
echo "starting up Snapshot server"

docker run -d
-e INIT_MEMORY=1G
-e MAX_MEMORY=4G
-e PVP=TRUE
-e SPAWN_PROTECTION=30
-e ENABLE_COMMAND_BLOCK=false
-e VIEW_DISTANCE=7
-e SIMULATION_DISTANCE=3
-e NETWORK_COMPRESSION_THRESHOLD=256
-e USE_AIKAR_FLAGS=true
-e LEVEL=snapshot2
-e DIFFICULTY=hard
-e SEED="-2446887223678575115"
-e EULA=TRUE
-e MAX_WORLD_SIZE=90000
-e PLAYER_IDLE_TIMEOUT=180
-e FORCE_GAMEMODE=TRUE
-e SERVER_NAME=snapshot2
-e VERSION=snapshot
-p 45578:25565
-e ENABLE_AUTOPAUSE=FALSE
-v /mnt/minecraft-1/snapshot2:/data
-v /etc/timezone:/etc/timezone:ro
--name mc-snapshot2
itzg/minecraft-server:java16 
exit
```

**Comment by itzg** [comment]
I know they added that in the latest snapshot and I can see it in the client settings, but I'm not yet finding a definitive confirmation of the server property. Can you point me to that?

**Comment by anaxios** [comment]
https://www.minecraft.net/en-us/article/minecraft-snapshot-21w38a
"A new simulation-distance property in dedicated server properties."

I see "simulation-distance=10" in my server.properties using 21w39a.

**Comment by itzg** [comment]
Thanks! For some reason my eyes had skipped over that part of the article.

**Comment by itzg** [comment]
The latest image now maps that server property.

**Comment by anaxios** [comment]
Looks like it's working for me. I tried changing it a couple times with OVERRIDE_SERVER_PROPERTIES set to true and it works. Thanks for all the work you've put into this project!
