### ISSUE TITLE
Support storing mod/plugin download links in a text file

### ISSUE THREAD

**Issue by cadenkriese** [itzg/docker-minecraft-server#1072]
To separate this from the docker-compose file would be nice so the input could be more human-readable and modifiable for source control purposes.

**Comment by hle0** [comment]
It could maybe be implemented as a volume in docker-compose, and then an environment variable with the location of the file? Keep in mind that there's also `env_file` in docker-compose already. I'd be happy to implement this in a PR.

**Comment by steve-thousand** [comment]
To clarify, it looks like this may only work for local mods files, correct? It looks like specifying a remote mods file over http is not supported.

**Comment by itzg** [comment]
@steve-thousand its actually the opposite. It only works for lists of URLs for now.

**Comment by itzg** [comment]
...oh now I understand the question. Yes the file must be local, but contents are URLs. It could actually be easy to add remote file also. Please open an enhancement issue for that.
