### ISSUE TITLE
multiarch-latest fails to run

### ISSUE THREAD

**Issue by hansnull** [itzg/docker-minecraft-server#1074]
Hi,

2021.20.0-multiarch-latest is running fine, after update the server does not run anymore:
`Downloading minecraft_server.[0.003s][error][cds]_Unable_to_map_CDS_archive_--_os::vm_allocation_granularity()_expected:_4096_actual:_65536`
Any ideas what is going on?

Best regards,
hansnull

**Comment by itzg** [comment]
I'm not sure what that error means at all. From some of the keywords I'm guessing it related to the memory conditions of the docker host. 

BTW, please switch to one of the `java*` image tags since those "multiarch" ones are deprecated.
