### ISSUE TITLE
How to add data packs to this Docker container

### ISSUE THREAD

**Issue by ajeetraina** [itzg/docker-minecraft-server#1097]
### Describe the problem

I am able to run Minecraft following https://collabnix.com/running-minecraft-server-in-2-minutes-using-docker/ and able to connect from the client by running the below CLI:

```
sudo docker run -d -p 25565:25565 -e EULA=true -e ONLINE_MODE =false -e DIFFICULTY=hard -e OPS=collabnix  -e MAX_PLAYERS=50 -e MOTD="welcome to Collabnix" -v /tmp/minecraft_data:/data --name mc itzg/minecraft-server
```

But any idea how can I connect the data packs.  I want to add cutclean, treecapitator etc datapacks. Will just moving those tar.gz to the /data directory works.

**Comment by itzg** [comment]
Since you have the data directory host mounted, then you'll install it into the `datapacks` directory of the `world` directory in your host's `/tmp/minecraft_data` directory.
