### ISSUE TITLE
Container stops while generating world

### ISSUE THREAD

**Issue by Hugo54x** [itzg/docker-minecraft-server#1103]
In docker logs the mc worker is stopping the server after a certain time. Is there a way to stop this behavior? My server is a little bit on the slow side of generating the world.

**Comment by itzg** [comment]
You can configure the health check to use more retries with `--health-retries` or disable the health check (at least for initial world gen) as described here:

https://github.com/itzg/docker-minecraft-server#healthcheck

**Comment by Hugo54x** [comment]
Thanks, this worked
