### ISSUE TITLE
Server stop's everynight at a certian time

### ISSUE THREAD

**Issue by mediacowboy** [itzg/docker-minecraft-server#1111]
### Describe the problem

I have been running the docker container for 2 weeks now and every night at 11:00 pm minecraft kicks everyone out and the minecraft server reboot's and comes back up. Some times is does this okay other time's it complains of a corrupt jar. I know how to fix the corrupt jar but not sure what would cause the Minecraft server to restart every night at 11p.

This happens even with or without players in the server.

Any help would be appreciated.

### Container definition

  mc2:
    image: itzg/minecraft-server
    container_name: mc_spigot #spigot
    ports:
      - 25565:25565
      - 8123:8123
      - 19132:19132/udp
    environment:
      EULA: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MOTD: "Please read the rules in the discord server"
      TYPE: SPIGOT
      SPIGET_RESOURCES: 34315,3836
      SPIGOT_DOWNLOAD_URL: 
      MAX_MEMORY: 3G
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ${USERDIR}/docker/spigot-data:/data
      - ${USERDIR}/docker/spigot-data/plugins:/plugins
      - /etc/timezone:/etc/timezone:ro

**Comment by itzg** [comment]
This is something specific to  your environment. Container logs would have helped provide some ideas.

**Comment by mediacowboy** [comment]
Okay. I will check that tonight and report back.

**Comment by mediacowboy** [comment]
I figured out the issue. Had nothing to do with the container. Thank you for pointing me in the right direction.
