### ISSUE TITLE
Forge 1.16.5 crashes

### ISSUE THREAD

**Issue by simon12mm** [itzg/docker-minecraft-server#1114]
### Describe the problem

I'm very new with Dockers and Containers, when i try to run this docker, after a while, it stops with the following message 
"2021-11-11T14:08:22.410Z WARN mc-server-runner sub-process failed {"exitCode": 1}"

### Container definition

docker run -d -it -p 25565:25565 -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.16.5 -e FORGEVERSION=36.2.8 -e DIFFICULTY=easy -e DEBUG_EXEC=TRUE itzg/minecraft-server

### Container logs

  Patching net/minecraft/client/renderer/model/ModelBakery$BlockStateDefinitionException 1/1

[init] Finding installed server jar...

[init] Using server forge-1.16.5-36.2.8.jar

[init] Creating server.properties in /data/server.properties

[init] Disabling whitelist

[init] Setting whitelist to 'false' in /data/server.properties

[init] Setting white-list to 'false' in /data/server.properties

[init] Adding server-name with 'Dedicated Server' in /data/server.properties

[init] Setting server-port to '25565' in /data/server.properties

[init] Setting motd to 'A Forge Minecraft Server powered by Docker' in /data/server.properties

[init] Setting enable-rcon to 'true' in /data/server.properties

[init] Setting rcon.password to 'minecraft' in /data/server.properties

[init] Setting rcon.port to '25575' in /data/server.properties

[init] Setting level-name to 'world' in /data/server.properties

[init] Setting online-mode to 'true' in /data/server.properties

[init] Setting difficulty to 'easy' in /data/server.properties

[init] Checking for JSON files.

[init] Setting initial memory to 1G and max to 1G

[init] Starting the Minecraft server...

at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)

at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Nov 11 14:07 /data'

[init] Resolved version given 1.16.5 into 1.16.5

[init] Resolving type given FORGE

[init] **********************************************************************

[init] WARNING: The image tag itzg/minecraft-server:java8 is recommended

[init]          since some mods require Java 8

[init]          Exception traces reporting ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader

[init]          can be fixed with java8

[init] **********************************************************************

[init] Checking Forge version information.

[init] server.properties already created, skipping

[init] Checking for JSON files.

[init] Setting initial memory to 1G and max to 1G

[init] Starting the Minecraft server...

at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)

at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Nov 11 14:07 /data'

[init] Resolved version given 1.16.5 into 1.16.5

[init] Resolving type given FORGE

[init] **********************************************************************

[init] WARNING: The image tag itzg/minecraft-server:java8 is recommended

[init]          since some mods require Java 8

[init]          Exception traces reporting ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader

[init]          can be fixed with java8

[init] **********************************************************************

[init] Checking Forge version information.

[init] server.properties already created, skipping

[init] Checking for JSON files.

[init] Setting initial memory to 1G and max to 1G

[init] Starting the Minecraft server...

at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)

at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Nov 11 14:07 /data'

[init] Resolved version given 1.16.5 into 1.16.5

[init] Resolving type given FORGE

[init] **********************************************************************

[init] WARNING: The image tag itzg/minecraft-server:java8 is recommended

[init]          since some mods require Java 8

[init]          Exception traces reporting ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader

[init]          can be fixed with java8

[init] **********************************************************************

[init] Checking Forge version information.

[init] server.properties already created, skipping

[init] Checking for JSON files.

[init] Setting initial memory to 1G and max to 1G

[init] Starting the Minecraft server...

at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)

at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Nov 11 14:07 /data'

[init] Resolved version given 1.16.5 into 1.16.5

[init] Resolving type given FORGE

[init] **********************************************************************

[init] WARNING: The image tag itzg/minecraft-server:java8 is recommended

[init]          since some mods require Java 8

[init]          Exception traces reporting ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader

[init]          can be fixed with java8

[init] **********************************************************************

[init] Checking Forge version information.

[init] server.properties already created, skipping

[init] Checking for JSON files.

[init] Setting initial memory to 1G and max to 1G

[init] Starting the Minecraft server...

at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:41)

at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)

**Comment by itzg** [comment]
Try using the `itzg/minecraft-server:java8` image since Forge is usually sensitive to Java versions.

**Comment by simon12mm** [comment]
thanks, it works now
