### ISSUE TITLE
can't run mediaval minecraft curseforge server

### ISSUE THREAD

**Issue by Daddie2** [itzg/docker-minecraft-server#1115]
i'm trying to start a mediaval minecraft but if i use USE_MODPACK_START_SCRIPT=false don't pull the modpack server, if don't use it i have the make sure is a ftb server error

**Comment by itzg** [comment]
What modpack exactly are you trying and I'll see if I can find any workarounds?

**Comment by Daddie2** [comment]
https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-modpack
I use this and didn't work 
version: "2"
 services:
  minecraft-server:
     image: itzg/minecraft-server:java8
     container_name: minecraft1
     network_mode: host
     environment:
      - PUID=1000
      - PGID=1000
      - EULA=TRUE
      - VERSION=1.16.5
      - TYPE=CURSEFORGE
      - CF_SERVER_MOD=https://media.forgecdn.net/files/3518/284/Medieval+Minecraft+Server+Pack+%5bFORGE%5d+v37.zip
      - MEMORY=4G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - ALLOW_FLIGHT=TRUE
     ports:
       - 25565:25565
     volumes:
       - /srv/dev-disk-by-uuid-f56a2030-b0f5-4e5b-9d30-18fe84f81052/mi/Minecraft:/data
     restart: unless-stopped

**Comment by Xskullibur** [comment]
I also had the same issue, are there any solutions or workarounds yet?

**Comment by steve-thousand** [comment]
I ran into a similar issue when trying to use `USE_MODPACK_START_SCRIPT` which is that it looks like the modpack cannot be a web URL when using `USE_MODPACK_START_SCRIPT=false`. It seems that `USE_MODPACK_START_SCRIPT=false` limits the container to only local modpacks

**Comment by itzg** [comment]
A workaround for really misbehaving modpacks is to use `TYPE=FORGE` and the `GENERIC_PACK` variable; however, for the time being `GENERIC_PACK`  only supports remote files via http.

**Comment by plsworkpls** [comment]
so I tried to use the workaround and the server started, but i wasnt able to join. I think the server didnt import the mods right?
version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:${IMAGE_TAG:-latest}
    ports:
      - 25565:25565
    volumes:
      - ./medievaldata:/data
      - ./modpacks:/modpacks:ro
    environment:
      EULA: "true"
      TYPE: FORGE
      GNERIC_PACKS: https://media.forgecdn.net/files/3797/938/Medieval+Minecraft+Server+Pack+%5bFORGE%5d+v11.zip
    restart: unless-stopped

volumes:
  data: {}

![image](https://user-images.githubusercontent.com/59932387/170119323-1e7dc257-eb55-4c5a-bfd7-a4db77814f92.png)

Starting curseforgeserver_mc_1 ... done
Attaching to curseforgeserver_mc_1
mc_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 9 1000 1000 4096 May 24 11:46 /data'
mc_1  | [init] Resolved version given LATEST into 1.18.2 and major version 1.18
mc_1  | [init] Resolving type given FORGE
mc_1  | [init] Checking Forge version information.
mc_1  | [init] server.properties already created, skipping
mc_1  | [init] Checking for JSON files.
mc_1  | [init] Setting initial memory to 1G and max to 1G
mc_1  | [init] Using Forge supplied run.sh script...
mc_1  | 2022-05-24 17:40:53,030 main WARN Advanced terminal features are not available in this environment
mc_1  | [17:40:53] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 40.1.0, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
mc_1  | [17:40:53] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.3 by Eclipse Adoptium
mc_1  | [17:40:53] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/data/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=SERVER
mc_1  | [17:40:56] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
mc_1  | [17:41:04] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 40.1.0, for MC 1.18.2 with MCP 20220404.173914
mc_1  | [17:41:04] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v40.1.0 Initialized
mc_1  | [17:41:05] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
mc_1  | [17:41:06] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 40.1.0 Target: null
mc_1  | [17:41:07] [main/INFO] [mojang/YggdrasilAuthenticationService]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
mc_1  | [17:41:09] [main/WARN] [minecraft/VanillaPackResources]: Assets URL 'union:/data/libraries/net/minecraft/server/1.18.2-20220404.173914/server-1.18.2-20220404.173914-srg.jar%2339!/assets/.mcassetsroot' uses unexpected schema
mc_1  | [17:41:09] [main/WARN] [minecraft/VanillaPackResources]: Assets URL 'union:/data/libraries/net/minecraft/server/1.18.2-20220404.173914/server-1.18.2-20220404.173914-srg.jar%2339!/data/.mcassetsroot' uses unexpected schema
mc_1  | [17:41:13] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
mc_1  | [17:41:13] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
mc_1  | [17:41:13] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
mc_1  | [17:41:13] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
mc_1  | [17:41:13] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
mc_1  | [17:41:15] [Worker-Main-11/INFO] [minecraft/RecipeManager]: Loaded 7 recipes
mc_1  | [17:41:17] [Worker-Main-11/INFO] [minecraft/AdvancementList]: Loaded 1141 advancements
mc_1  | [17:41:19] [Server thread/INFO] [minecraft/DedicatedServer]: Starting minecraft server version 1.18.2
mc_1  | [17:41:19] [Server thread/INFO] [minecraft/DedicatedServer]: Loading properties
mc_1  | [17:41:19] [Server thread/INFO] [minecraft/DedicatedServer]: Default game type: SURVIVAL
mc_1  | [17:41:19] [Server thread/INFO] [minecraft/MinecraftServer]: Generating keypair
mc_1  | [17:41:19] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565
mc_1  | [17:41:19] [Server thread/INFO] [minecraft/ServerConnectionListener]: Using epoll channel type
mc_1  | [17:41:20] [Server thread/INFO] [minecraft/DedicatedServer]: Preparing level "world"
mc_1  | [17:41:20] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing start region for dimension minecraft:overworld
mc_1  | [17:41:22] [Worker-Main-13/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:22] [Worker-Main-13/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:22] [Worker-Main-9/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:22] [Worker-Main-8/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:23] [Worker-Main-10/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:23] [Worker-Main-9/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:23] [Worker-Main-13/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:24] [Worker-Main-12/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:24] [Worker-Main-14/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:25] [Worker-Main-13/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:25] [Worker-Main-9/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:26] [Worker-Main-8/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 0%
mc_1  | [17:41:26] [Worker-Main-10/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 1%
mc_1  | [17:41:27] [Worker-Main-8/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 1%
mc_1  | [17:41:27] [Worker-Main-9/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 1%
mc_1  | [17:41:28] [Worker-Main-13/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 6%
mc_1  | [17:41:28] [Worker-Main-10/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 15%
mc_1  | [17:41:29] [Worker-Main-12/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 23%
mc_1  | [17:41:29] [Worker-Main-13/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 52%
mc_1  | [17:41:30] [Worker-Main-10/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 69%
mc_1  | [17:41:30] [Worker-Main-10/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 69%
mc_1  | [17:41:31] [Worker-Main-8/INFO] [minecraft/LoggerChunkProgressListener]: Preparing spawn area: 95%
mc_1  | [17:41:31] [Server thread/INFO] [minecraft/LoggerChunkProgressListener]: Time elapsed: 10680 ms
mc_1  | [17:41:31] [Server thread/INFO] [minecraft/DedicatedServer]: Done (11.254s)! For help, type "help"
mc_1  | [17:41:31] [Server thread/INFO] [minecraft/DedicatedServer]: Starting remote control listener
happythepills@compaq-mc:~/curseforgeserver$
mc_1  | [17:41:31] [Server thread/INFO] [minecraft/RconThread]: RCON running on 0.0.0.0:25575
mc_1  | [17:41:31] [Server thread/INFO] [ne.mi.se.pe.PermissionAPI/]: Successfully initialized permission handler forge:default_handler
^CGracefully stopping... (press Ctrl+C again to force)
Stopping curseforgeserver_mc_1 ...
