### ISSUE TITLE
Airplane 1.16:  Unsupported Java detected (61.0). Only up to Java 16 is supported.

### ISSUE THREAD

**Issue by mhbates** [itzg/docker-minecraft-server#1125]
### Describe the problem

Server isn't starting up with the latest image. Not sure if it's related to Airplane or just Minecraft itself.

### Container definition

```
docker run -d \
--cpus="4.0" \
--name minecraft \
-p 25565:25565 \
-p 8123:8123 \
-v /xxx:/data \
-e EULA=TRUE \
-e SERVER_NAME=xxx \
-e DIFFICULTY=hard \
-e FORCE_GAMEMODE=true \
-e GENERATE_STRUCTURES=true \
-e ANNOUNCE_PLAYER_ACHIEVEMENTS=true \
-e TZ=xxx \
-e MEMORY=4G \
-e TYPE=AIRPLANE \
-e USE_AIKAR_FLAGS=true \
-e VERSION=1.16 \
-e FORCE_REDOWNLOAD=false \
-e ENABLE_AUTOPAUSE=true \
-e AUTOPAUSE_TIMEOUT_EST=300 \
-e AUTOPAUSE_TIMEOUT_INIT=15 \
-e AUTOPAUSE_TIMEOUT_KN=30 \
--restart=always \
itzg/minecraft-server
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 12 1000 1000 4096 Oct  4 19:23 /data'
[init] Resolved version given 1.16 into 1.16
[init] Autopause functionality enabled
[init] Resolving type given AIRPLANE
[init] Using Airplane-1.16 branch
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Using Aikar's flags
[init] Setting initial memory to 4G and max to 4G
[init] Starting the Minecraft server...
Unsupported Java detected (61.0). Only up to Java 16 is supported.
2021-11-17T07:27:37.504-0800	INFO	mc-server-runner	Done
```

**Comment by mhbates** [comment]
Rolling back to image 2021.22.0 fixes it.

**Comment by samirelanduk** [comment]
Getting the same error using `1.18-pre3` and `1.18-pre2`, which are the two pre-releases since MC changed the version of Java they used. Reverting to the 2021.22.0 image didn't fix it for me, but reverting to `1.18-pre1` did. I think without a fix versions >= `1.18-pre2`, including the final version 1.18, won't run using this container.

**Comment by itzg** [comment]
@mhbates 

> Unsupported Java detected (61.0). Only up to Java 16 is supported.

`latest` is now Java 17. Use `itzg/minecraft-server:java16` or [one of the other image-java versions prior to 17](https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version).

@samirelanduk make sure you re-pull `itzg/minecraft-server` (or use `itzg/minecraft-server:java17`). Both worked fine for me just now with `VERSION=SNAPSHOT`.

**Comment by samirelanduk** [comment]
Pulling in the latest image did fix this - thanks a lot.

**Comment by mhbates** [comment]
@itzg Thanks, I guess Airplane 1.16.5 is still on Java 16 then. I'll stick with that image for now.
