### ISSUE TITLE
Add a table to the Readme showing which Minecraft version work with which Java version

### ISSUE THREAD

**Issue by maeries** [itzg/docker-minecraft-server#1130]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I Just spend an hour figuring our why Minecraft Server 1.10 through 1.14 do not work, but newer versions do. I fixed it by setting the docker tag to `java8`. To save the time for others I imagine it would be a good idea to put a table into the readme that shows which java version I have to use if I want to use a specific minecraft version

**Comment by itzg** [comment]
Good idea. It might have to be an incremental, community effort since I'm not totally sure all of the combinations.

**Comment by itzg** [comment]
I have clarified the compatibility note in https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version since I did find it odd that versions before 1.10 were fine with Java 17, but 1.10 and 1.11 were not.
