### ISSUE TITLE
Unbound variable in start-utils when trying to load 1.18-pre8

### ISSUE THREAD

**Issue by anaxios** [itzg/docker-minecraft-server#1132]
### Describe the problem

Spun up a vanilla testing server using "SNAPSHOT" for the version and java 17 and the container fails with 

`/start-utils: line 127: pre8: unbound variable`

Wish I knew enough to fix it myself.

### Container definition

version: "3"

services:
  mc:
    image: "itzg/minecraft-server:java17"
    ports:
      - 25525:25565
      - 25526:25526/udp
    environment:
      #TYPE: "FABRIC"
      #SPIGET_RESOURCES: "9089"
      EULA: "TRUE"
      MEMORY: "4G"
      VERSION: "SNAPSHOT"
      ENABLE_RCON: "true"
      RCON_PORT: "25575"
      RCON_PASSWORD: "minecraft"
      SERVER_PORT: "25565"
      ONLINE_MODE: "false"
      SERVER_NAME: "testing"
      #ENABLE_ROLLING_LOGS: "true"
      MOTD: "Testing server."
      VIEW_DISTANCE: "10"
      SIMULATION_DISTANCE: "15"
      MAX_PLAYERS: "10"
      DIFFICULTY: "hard"
      MODE: "survival"
      FORCE_GAMEMODE: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      #RESOURCE_PACK: "https://github.com/anaxios/MC-resource-pack/raw/main/Vanilla_Additions_2.1.zip=1"
      PVP: "true"
      #LEVEL_TYPE: "flat"
      BROADCAST_CONSOLE_TO_OPS: "true"
      ALLOW_FLIGHT: "true"
      LEVEL: "world"
      SPAWN_PROTECTION: "0"
      OPS: ""
      OVERRIDE_SERVER_PROPERTIES: "true"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      WHITELIST: ""
      USE_AIKAR_FLAGS: "true"
      EXEC_DIRECTLY: "true"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: "300"
      AUTOPAUSE_TIMEOUT_KN: "120"
      AUTOPAUSE_TIMEOUT_INIT: "600"
      AUTOPAUSE_PERIOD: "10"
      AUTOPAUSE_KNOCK_INTERFACE: "eth0"
      MAX_TICK_TIME: "-1"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./data:/data

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
Thanks for reporting this! Looking into it right now.

**Comment by itzg** [comment]
Build is on the way https://github.com/itzg/docker-minecraft-server/actions/runs/1501303292

**Comment by itzg** [comment]
And it's pushed

**Comment by Nincodedo** [comment]
I was also having this issue. Fix works for me! Thank you for the quick update!

**Comment by anaxios** [comment]
Works beautifully! Thank you!
