### ISSUE TITLE
Waterfall Server?

### ISSUE THREAD

**Issue by Skyfay** [itzg/docker-minecraft-server#1187]
### Enhancement Type

New server type

### Describe the enhancement

It would be cool if you could do a bungeecord or a waterfall server.
https://papermc.io/downloads#Waterfall
https://github.com/PaperMC/Waterfall

**Comment by itzg** [comment]
Like this 😉

https://github.com/itzg/docker-bungeecord

**Comment by Skyfay** [comment]
> Like this? 😉
> 
> https://github.com/itzg/docker-bungeecord

Oh, Yes 😅

**Comment by ThomasTomanec** [comment]
Hello, I would really need it for Waterfall.

**Comment by Skyfay** [comment]
> Hello, I would really need it for Waterfall.

Here -> https://github.com/itzg/docker-bungeecord

**Comment by ThomasTomanec** [comment]
And there, in the docker-compose file, do I just need to set TYPE: WATERFALL
in the environment to have Waterfall?


po 22. 4. 2024 v 12:08 odesílatel Manu ***@***.***> napsal:

**Comment by ThomasTomanec** [comment]
My docker-compose.yml:


version: "3"

services:

  minecraft:

    image: marctv/minecraft-papermc-server:latest

    restart: always

    container_name: "mcserver"

    environment:

      MEMORYSIZE: „4G"

      PAPERMC_FLAGS: ""

    volumes:

      - /root/mc-docker:/data

    stdin_open: true

    tty: true

  bungeecord:

    image: itzg/bungeecord

    environment:

      TYPE: WATERFALL

      ENABLE_RCON: "true"

      DEBUG: "false"

    ports:

      - 25565:25577

    volumes:

      - ./config.yml:/config/config.yml

po 22. 4. 2024 v 12:15 odesílatel Tomáš Tomanec ***@***.***>
napsal:

**Comment by itzg** [comment]
Just want to check that you understand Waterfall is a proxy and not a Minecraft server type?

marctv/minecraft-papermc-server is not my image, but you can switch to my image that supports Paper and add a Waterfall proxy container like this example

https://github.com/itzg/docker-bungeecord/blob/master/docs/docker-compose-waterfall.yml
