### ISSUE TITLE
docker-paper-compose.yml needs Version commented out

### ISSUE THREAD

**Issue by woeisme** [itzg/docker-minecraft-server#1194]
### Describe the problem

attempting to run the example file throws java exception 

### Container definition

version: '3.8'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.9.4
      # needed for Paper versions before 1.14
      CONSOLE: "false"
    ports:
      - 25565:25565
    volumes:
      - mc-paper:/data

volumes:
  mc-paper:

### Container logs

java exception, no logs captured.

**Comment by itzg** [comment]
That example is very old -- it needs `image: itzg/minecraft-server:java8-multiarch` now. In any case, I'm going to delete the example file since it's trivial to create a Paper container.

**Comment by woeisme** [comment]
is `image: itzg/minecraft-server:java8-multiarch` necessary now? 
It seemed to be able to get running with `image: itzg/minecraft-server` 
logs show ` System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12) Host: Linux 5.13.0-21-generic (amd64)
paper | Loading libraries, please wait...
`
The example file was still useful for those of us not necessarily familiar with docker-compose syntax

**Comment by woeisme** [comment]
Re-running with java8-multiarch added to the compose file yields
`
BLANKED:~/docker-minecraft-server$ docker-compose -f docker-compose-paper.yml up
Pulling mc (itzg/minecraft-server:java8-multiarch)...
java8-multiarch: Pulling from itzg/minecraft-server
7b1a6ab2e44d: Already exists
5c122ee837fa: Pull complete
2d17ed067016: Pull complete
89aa7ee48d2c: Pull complete
4649aa3da7c5: Pull complete
9d5f4ed50352: Pull complete
3665697ad897: Pull complete
c79cba075b32: Pull complete
5a06c19f9e1d: Pull complete
139fe14e77a8: Pull complete
0faddcc7416f: Pull complete
904827597385: Pull complete
74db104c39b4: Pull complete
cd00dcc99eeb: Pull complete
a4f5bba154ab: Pull complete
b3c5c6bd6c1b: Pull complete
2f4be888cae3: Pull complete
1ba78607b429: Pull complete
bfddd5d0728c: Pull complete
e4a35e8eca33: Pull complete
748e7d842daa: Pull complete
1e547184d11e: Pull complete
Digest: sha256:fb9c0944bc8cf27e6efc72ab401502f0006ff41aeafbc60fe5363169f61045ce
Status: Downloaded newer image for itzg/minecraft-server:java8-multiarch
Recreating paper ... done
Attaching to paper
paper | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 998 560 Dec 13 01:32 /data'
paper | [init] Resolved version given LATEST into 1.18.1
paper | [init] Autopause functionality enabled
paper | [init] Resolving type given PAPER
paper | [init] Removing old PaperMC versions ...
paper | [init] Downloading PaperMC 1.18.1 (build 71) ...
paper | [init] Getting plugins via Spiget
paper | [init] Downloading resource 60383 ...
paper | [init] resource '60383' not downloaded because installed version '6.1.1' already up to date ('6.1.1')
paper | [init] server.properties already created, skipping
paper | [init] Warning: The server.properties for the server doesn't have the Server Watchdog (effectively) disabled.
paper | [init] Warning (cont): Autopause functionality resuming the process might trigger the Watchdog and restart the server completely.
paper | [init] Warning (cont): Set the max-tick-time property to a high value (or disable the Watchdog with value -1 for versions 1.8.1+).
paper | [init] Checking for JSON files.
paper | [init] Setting initial memory to 4G and max to 4G
paper | [init] Starting the Minecraft server...
paper | Minecraft 1.18 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/
paper | 2021-12-13T02:48:34.288Z        WARN    mc-server-runner        sub-process failed      {"exitCode": 1}
paper | 2021-12-13T02:48:34.288Z        INFO    mc-server-runner        Done
paper exited with code 1
BLANKED:~/docker-minecraft-server$ docker-compose -f docker-compose-paper.yml up
`

**Comment by itzg** [comment]
> is `image: itzg/minecraft-server:java8-multiarch` necessary now? 

It is if you're running Paper versions prior to 1.18. The file I removed was specifying 1.9.4, so Java 8 was required:

https://github.com/itzg/docker-minecraft-server/blob/66a17c8d589e7ebee60a2a789024e0522f039d26/examples/docker-compose-paper.yml#L9

> It seemed to be able to get running with `image: itzg/minecraft-server` logs show `System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.1+12) Host: Linux 5.13.0-21-generic (amd64) paper | Loading libraries, please wait...` 

That contradicts your original problem statement:

![image](https://user-images.githubusercontent.com/988985/145745309-06deae3a-3d82-4f19-a0d7-f4fbb3f5b7c6.png)

> The example file was still useful for those of us not necessarily familiar with docker-compose syntax

There's a whole directory full of examples:

https://github.com/itzg/docker-minecraft-server/tree/master/examples

**Comment by woeisme** [comment]
>It is if you're running Paper versions prior to 1.18. The file I removed was specifying 1.9.4, so Java 8 was required:
Ah now I understand better, thank you. 

> That contradicts your original problem statement:

Allow me to clarify, I was able to run it successfully _after_ commenting out the version line. 

>There's a whole directory full of examples:
True, however I had a doozy of a time getting my file to work and that examples list is buried where less users will see it. 

I'd be happy to submit my docker-compose-paper.yml file for inclusion in the examples directory, as I think many of us would benefit and there are many pitfalls to YAML syntax for those of us not familiar or this being the first use of docker.

**Comment by woeisme** [comment]
pull request created https://github.com/itzg/docker-minecraft-server/pull/1198
