### ISSUE TITLE
multiarch-latest Java 17

### ISSUE THREAD

**Issue by BC6B** [itzg/docker-minecraft-server#1200]
Looks like multiarch-latest might need a Java 17 upgrade for 1.18+. I get the following on container start:

`java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 60.0`

I verified I have the latest version and also tried pulling a fresh copy.

**Comment by itzg** [comment]
`multiarch-latest` is deprecated: https://github.com/itzg/docker-minecraft-server#deprecated-image-tags

Please switch to `latest`.
