### ISSUE TITLE
cant run a mod pack on 1.16.5

### ISSUE THREAD

**Issue by windetrsfugwq** [itzg/docker-minecraft-server#1207]
### Describe the problem

Docker runs for 3 seconds and then immediately quits
on just on modpacks cursed Forge
command  for me it made a directory called  FeedTheBeast with all the mods and stuff in it

### Container definition

sudo docker run -d -v /var/minecraft/forge:/data     -e TYPE=CURSEFORGE     -e CF_SERVER_MOD=Above+and+Beyond-1.3-Server.zip     -p 25565:25565 -e EULA=TRUE --name forge itzg/minecraft-server 

### Container logs

```
Paste logs here
```

**Comment by windetrsfugwq** [comment]
logs?
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    9 1000     1000          4096 Dec 17 00:51 /data'
 [init] Resolved version given 1.16.5 into 1.16.5
 [init] Resolving type given CURSEFORGE
 [init] Looking for Feed-The-Beast / CurseForge server modpack.
 [init] Unpacking FTB server modpack /data/Above+and+Beyond-1.3-Server.zip ...
 ..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
 [init] Please make sure you are using the server version of the FTB modpack!

**Comment by itzg** [comment]
The modpack must have a different structure than currently supported. This will need further investigation.

**Comment by windetrsfugwq** [comment]
ok thank you

**Comment by StoneLabs** [comment]
It appears this mod pack comes without an install script. I do believe that's what USE_MODPACK_START_SCRIPT=false is for.

Running it like this works:
```
sudo docker run -d -v /var/minecraft/forge:/data 
-e TYPE=CURSEFORGE 
-e CF_SERVER_MOD=Above+and+Beyond-1.3-Server.zip 
-p 25565:25565 
-e EULA=TRUE
-e USE_MODPACK_START_SCRIPT=FALSE  <----- CHANGE
itzg/minecraft-server
```

(well the modpack crashs after start, but that is not a problem on our end)
