### ISSUE TITLE
IBM Semeru OpenJ9 container images are now available with Java 17

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1209]
FYI, IBM Semeru OpenJ9 container images are now available with Java 17 => https://hub.docker.com/_/ibm-semeru-runtimes

__Originally posted by @C0Nd3Mnd in https://github.com/itzg/docker-minecraft-server/issues/1054#issuecomment-996254884__

**Comment by itzg** [comment]
Variant is now ready.

```
> docker run -it --rm --entrypoint java itzg/minecraft-server:java17-openj9 -version
openjdk version "17.0.1" 2021-10-19
IBM Semeru Runtime Open Edition 17.0.1.0 (build 17.0.1+12)
Eclipse OpenJ9 VM 17.0.1.0 (build openj9-0.29.1, JRE 17 Linux amd64-64-Bit Compressed References 20211207_75 (JIT enabled, AOT enabled)
OpenJ9   - 7d055dfcb
OMR      - e30892e2b
JCL      - fc67fbe50a0 based on jdk-17.0.1+12)
```

**Comment by yqs112358** [comment]
So will Semeru OpenJ9 with Java21 will be supported? 🥰 It can observe a considerable reduction in memory usage compared to Temurin on the same server configuration, which will be helpful for small servers with limited memory supply
