### ISSUE TITLE
Downloading spigot fails. Download domain changed?

### ISSUE THREAD

**Issue by Mr-Protocol** [itzg/docker-minecraft-server#1213]
It looks like it's using the wrong URL to download the newest file.

Log:
[init] Resolved version given 1.18.1 into 1.18.1
[init] Resolving type given SPIGOT
[init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.18.1.jar ...

URL from using a browser: https://download.getbukkit.org/spigot/spigot-1.18.1.jar

I'm not sure if this is a simple fix or if someone has a workaround?

**Comment by itzg** [comment]
Re-pull the latest image since that already been fixed.

**Comment by Mr-Protocol** [comment]
Ah, seems like my container didn't auto update. Thanks.

**Comment by itzg** [comment]
Can this be closed?
