### ISSUE TITLE
Pufferfish support

### ISSUE THREAD

**Issue by bram-pkg** [itzg/docker-minecraft-server#1226]
### Enhancement Type

New server type

### Describe the enhancement

Hey,

Since Airplane will not be updating to 1.18, and from early testing Pufferfish seems to be a good replacement.

Would you be open to adding Pufferfish as a server type?

I think a lot of the current Airplane script could be reused.

<https://github.com/pufferfish-gg/Pufferfish>
<https://ci.pufferfish.host/job/Pufferfish-Purpur-1.18/>

**Comment by itzg** [comment]
I'll think about it. Honestly, all the various server types get a bit exhausting. I'm also not sure why the developers don't just contribute back to Paper since it has the same goals.

**Comment by bram-pkg** [comment]
I agree, it's a bit of a pain. First there was Bukkit -> Spigot -> Paper -> Tuinity -> Airplane.

Trying to even explain to someone is already weird.

**Comment by bram-pkg** [comment]
As to contributing back to Paper. They can be quite reluctant to add "foreign" patches.

**Comment by itzg** [comment]
Not for you to answer, but I then wonder why can't the Pufferfish people team up with the Airplane people if the Paper people are not inclusive?

**Comment by bram-pkg** [comment]
Good question 😅 Haven't got a clue.

**Comment by kev626** [comment]
> Not for you to answer, but I then wonder why can't the Pufferfish people team up with the Airplane people if the Paper people are not inclusive?

s/people/person :)

Airplane is just discontinued and Paul (also a singular person) isn't interested in continuing the project in any capacity, so I'm maintaining the patches that were originally in Airplane and adding my own on top of them. Paper's PR process is a bit annoying and I kinda want some autonomy in what I choose to do with my project, I don't want to have patches waiting in review queues or require changes that I may not agree with.

**Comment by itzg** [comment]
Thanks @kev626 for the clarification. I'm still hesitant to personally support more variants especially since I got pulled into drama with one of the others. I would very much appreciate and accept a PR though.

**Comment by bram-pkg** [comment]
Hey Geoff, like you suggested: I've opened a PR to address this issue (#1255) :)
