### ISSUE TITLE
Potential AutoPlug Support

### ISSUE THREAD

**Issue by EpicLPer** [itzg/docker-minecraft-server#1227]
### Enhancement Type

New server type

### Describe the enhancement

I've recently discovered AutoPlug which is a way to easily update and maintain existing server plugins and also update the server itself to the latest version.

https://www.spigotmc.org/resources/autoplug-automatic-plugin-server-java-self-updater.78414/

However this requires the AutoPlug jar to start first and it handling all the rest of the server like updating the server jar etc.  
Would it be feasible to include support for this or should there rather be a whole new Docker container for it since it's technically not a server by itself? Of course only a suggestion :)

Thanks!

**Comment by itzg** [comment]
Great find. Yes, as you were saying I think this should be utilized in a whole new image since it does a lot of the same things as the current image.
