### ISSUE TITLE
Swarm Tutorial seems only to work, when the overlay network name is es

### ISSUE THREAD

**Issue by quorak** [itzg/docker-minecraft-server#123]
hey there,

i followd https://github.com/itzg/dockerfiles/wiki/Swarm-mode-production-grade-Elasticsearch-cluster  .
Everything works like a charm. But when I give the network a different name (but still in overlay mode) it doesn't seem to work.

I get various connection Timeouts

```
Jan 13 12:11:01 node-3.cluster-1 dockerd[28325]: [2017-01-13T12:11:01,649][INFO ][o.e.d.z.ZenDiscovery     ] [ijIX1ba] failed to send join request to master [{CzwnAHl}{CzwnAHlQQoa7Ouj52I-7EQ}{040xLUAPRd2P-ZxhMjVEsQ}{10.0.9.16}{10.0.9.16:9300}], reason [RemoteTransportException[[CzwnAHl][10.0.9.16:9300][internal:discovery/zen/join]]; nested: ConnectTransportException[[ijIX1ba][10.255.0.9:9300] connect_timeout[30s]]; nested: IOException[connection timed out: 10.255.0.9/10.255.0.9:9300]; ]
Jan 13 12:11:34 node-3.cluster-1 dockerd[28325]: [2017-01-13T12:11:34,663][INFO ][o.e.d.z.ZenDiscovery     ] [ijIX1ba] failed to send join request to master [{CzwnAHl}{CzwnAHlQQoa7Ouj52I-7EQ}{040xLUAPRd2P-ZxhMjVEsQ}{10.0.9.16}{10.0.9.16:9300}], reason [RemoteTransportException[[CzwnAHl][10.0.9.16:9300][internal:discovery/zen/join]]; nested: ConnectTransportException[[ijIX1ba][10.255.0.9:9300] connect_timeout[30s]]; nested: IOException[connection timed out: 10.255.0.9/10.255.0.9:9300]; ]
````

Do you have a Idea why? Is it somehow hardcoded?

thanks a lot best

**Comment by itzg** [comment]
Did you also change the `--network` references to "es" in the `service create` commands?

**Comment by itzg** [comment]
@quorak now that swarm mode in Docker 1.13 support compose files, I was able to double check with [this compose file](https://raw.githubusercontent.com/itzg/dockerfiles/master/elasticsearch/docker-compose.yml). I need to update the wiki page, but in the mean time you could try launching with:

```
docker stack deploy -c docker-compose.yml testing
```
