### ISSUE TITLE
java17-openj9	for 1.18.1

### ISSUE THREAD

**Issue by vorburger** [itzg/docker-minecraft-server#1234]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Just an issue to track evenually having a `java17-openj9` (we currently only have `java16-openj9`, note 16 vs 17) for Minecraft 1.18.1 (which requires Java 17 and does not work on Java 18 - apparently).

**Comment by itzg** [comment]
Duplicate of #1209

**Comment by itzg** [comment]
`itzg/minecraft-server:java17-openj9` is now available.

**Comment by MennoGamed** [comment]
Hey,
If i add the docker image to Pterodactyl the console will almost instand crach. 
Below are the logs of the console:

https://mcpaste.com/YCbbORZHygo09JGDxsfiT96B
