### ISSUE TITLE
Forge and Packwiz

### ISSUE THREAD

**Issue by Extensivity** [itzg/docker-minecraft-server#1238]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Allow forge to also implement packwiz, instead of just fabric.

**Comment by Extensivity** [comment]
Just figured out the issue, I thought I could just git clone and point the url to the file instead.

PS: Should add in the readme that it does works with forge and fabric, instead of just fabric.

**Comment by itzg** [comment]
I don't see where it says only Fabric. Or was it the example that implied that?

**Comment by Extensivity** [comment]
Pretty much, plus I was still kinda new to packwiz and was trying to get used to it. Some completely my bad.
