### ISSUE TITLE
Add GraalVM (CE) tag image

### ISSUE THREAD

**Issue by Zifiv** [itzg/docker-minecraft-server#1252]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

It could be interesting to add an image tag that is based on GraalVM.

It appear that this VM is more efficient than the openj9, so it could be usefull for server administrators I think.

**Comment by itzg** [comment]
As far as I know GraalVM requires compilation from source. Please reach out to Mojang and/or a downstream server project, such as PaperMC. It's also non-trivial to apply existing source code to GraalVM since common Java techniques are disallowed, so set your expectations low.

**Comment by beaucoralk** [comment]
Oh ok, I didn't know about this. So only a PaperMC server can be started with the Graal VM right ?

**Comment by beaucoralk** [comment]
Ok thanks 👍. Sorry, didn't know.

**Comment by beaucoralk** [comment]
Apparently GraalVM is working well with PaperMC and FabricMC. I've not tester for mojang vanilla implementation and Forge.

**Comment by itzg** [comment]
Yeah I later found during research that there's a runtime mode for GraalVM. I'm not finding any appealing base images to use though, so I don't think I can do much with this for now. Have you found any published research on performance improvements of Paper/Fabric with GraalVM?

**Comment by Panderine** [comment]
Hi @itzg there are some oficial GraalVM docker images (both amd64 /ARM64 both for CE and EE GraalVM edition). EE edition says to have even more performance than CE edition (source: GraalVM page). https://www.graalvm.org/downloads/

Regarding real data for Minecraft Servers I have none, but I'm using it as the client jvm and performance is very satisfactory for me. I'm using fabric with ton of mods. Will try to find some comparisons.

**Comment by itzg** [comment]
@Panderine I'm not finding official images. Can you send me a specific one?

**Comment by Panderine** [comment]
Sure:
https://github.com/graalvm/container/pkgs/container/graalvm-ce

And here is the oracle container registry:
https://container-registry.oracle.com/ords/f?p=113:1:13646253991039:::1:P1_BUSINESS_AREA:88&cs=3U8tdS9yPgB7mPY6asqSLHZGKNt6lqaeoiZNOBJDZ13YkvkrFy1gkdwLogwdXOQfykKm8VQQSY__AtQgdsV0PkA

**Comment by itzg** [comment]
Thanks! I was looking on Docker Hub.

**Comment by Panderine** [comment]
This could be a great alternativo for ARM64 arch :)

**Comment by itzg** [comment]
> This could be a great alternative for ARM64 arch :)

Could be. I have been developing with Java for over 20 years since 1.0. I have seen several JVMs come and go and am automatically skeptical of anything other than the mainline.

**Comment by Panderine** [comment]
TL:DR version: This one comes from Oracle, It's main sale point is replacing the mainline compiler C1, with the graal one. Started on java 9. Several years later... spin off VM = GraalVM. It's also polyglot so it suppots other languajes besides java.

Major differentiators of GraalVM compared to the base JDK are:

GraalVM Compiler, a JIT compiler for Java
GraalVM Native Image, allowing the ahead-of-time compilation of Java applications
Truffle Language Implementation framework and the GraalVM SDK, to implement additional programming language runtimes
LLVM Runtime and JavaScript Runtime

**Comment by itzg** [comment]
Yes, being developed and supplied by Oracle muddies my purist stance since both Graal and Hotspot are "pure" JVMs 😀 I really need to research GraalVM more for my day to day development.

**Comment by itzg** [comment]
Just wanted to provide an update that it'll be a little harder than planned since their images are Redhat based (Oracle Linux 7/8) whereas the Dockerfile so far assumes Debian for most variants.

**Comment by andrewschott** [comment]
DId you need a hand translating RH-isms into Debian-isms?  I am  rather well versed and comfortable in doing things the RH way (not that Oracle is really all that different)  and have kinda gotten used to a while back converting Deb/*Buntu to RHEL7 images .... back when I had the time to rebuild everything I ran.  Now I just don't have that kind of time for toy containers.

But if you want help shout out, I'll do what I can.

**Comment by itzg** [comment]
That would be great @andrewschott 

The base image is now build arg driven

https://github.com/itzg/docker-minecraft-server/blob/b7f8239235929f058e5846532b212913263c4f64/Dockerfile#L3

and then the package and user setup is auto routed based on the distro 

https://github.com/itzg/docker-minecraft-server/tree/master/build

and then the workflow matrix needs a new entry for it

https://github.com/itzg/docker-minecraft-server/blob/b7f8239235929f058e5846532b212913263c4f64/.github/workflows/build-multiarch.yml#L18

**Comment by itzg** [comment]
Yeah go with the Oracle base image @andrewschott

**Comment by NoaHimesaka1873** [comment]
@itzg Any progress? Also it'd be nice to have Enterprise Edition one primarily focused for OCI user since it's free running on OCI.

**Comment by itzg** [comment]
No progress. It's in the queue. 

This type of feature is a good candidate for someone to fork and maintain downstream.

**Comment by NoaHimesaka1873** [comment]
> No progress. It's in the queue. 
> 
> This type of feature is a good candidate for someone to fork and maintain downstream. 

Then I should try to do this myself :)

**Comment by NoaHimesaka1873** [comment]
@itzg Can you close this since it's now completed?

**Comment by itzg** [comment]
Sure will!

**Comment by NoaHimesaka1873** [comment]
Also one more note: GraalVM EE also works if you build Docker image yourself. I'm running GraalVM EE on my production MC server (of course with vaild license)
![Screenshot_20220718_092402-1](https://user-images.githubusercontent.com/39993457/179430956-fb6ae898-b786-47b9-824f-bda8bdbc021a.png)
