### ISSUE TITLE
Using GENERIC_PACK and REMOVE_OLD_MODS works only once

### ISSUE THREAD

**Issue by panromir** [itzg/docker-minecraft-server#1253]
### Describe the problem

When using docker-compose I noticed that the functionality for extracting all mods from a generic mods zip file works only on the first start, usually I want to be able to restart my container without changing the zip file in any way.
The issue seems to be in the start-setupModPack script.
It creates a file .generic_pack.sum that it compares the checksum of the zip file against ( I assume ) and doesn't extract if if the sum is equal, however it purges the mods folder either way.

### Container definition

version: "3"

services:
  mc:
    image: itzg/minecraft-server
    user: "removed"
    ports:
      - 25566:25565
      - 127.0.0.1:8124:8124
      - 127.0.0.1:25575:25575
    environment:
      EULA: "TRUE"
      DIFFICULTY: hard
      WHITELIST: removed
      OPS: removed
      ALLOW_NETHER: "TRUE"
      GENERATE_STRUCTURES: "TRUE"
      MODE: survival
      MEMORY: 16G
      TYPE: FORGE
      GENERIC_PACK: "/modpacks/bettermc.zip"
      REMOVE_OLD_MODS: "TRUE"
      REMOVE_OLD_MODS_EXCLUDE: "WorldPreGenerator*"
      SERVER_NAME: "Panromirs Better-Minecraft 1.18.1 Server"
    tty: true
    stdin_open: true
    volumes:
      - "/home/removed/docker/better_minecraft:/data:Z"
      - "/home/removed/modpacks/bettermc.zip:/modpacks/bettermc.zip:ro"
    restart: unless-stopped

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
Thanks for reporting this. Yes it does seem the combination of options is not handled properly. It's not the most efficient solution, but I could have it remove the marker file when REMOVE_OLD_MOD. That way it would at least remain self consistent. Would that be acceptable?

**Comment by panromir** [comment]
Hi, thanks for the quick reply!
For me personally, this would solve the issue. 
I can't think of any negative side effects of that behaviour from the top of my head.

**Comment by itzg** [comment]
The latest image now has the fix for this.

**Comment by panromir** [comment]
Fix is working, thank you, cosing this!
