### ISSUE TITLE
Add MODS/MODS_FILE schedule

### ISSUE THREAD

**Issue by Toucan-Sam** [itzg/docker-minecraft-server#1254]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

At the moment, `MODS` and `MODS_FILE` will download a file once and only once. After that, the process will just skip downloading those files again. It would be excellent to add a `MODS_FREQUENCY` variable to check if a file on disk is older than X and if so, redownload.

Snip the file name if *.jar from `MODS_FILE` and check timestamp on disk; If older than MODS_FREQUENCY, download again?

I update containers automatically when updates are pushed, but given the log4j stuff recently it would be ideal to be able to do the same for plugins.

This does already work effectively if using SPIGET, but there seem to be a large number of popular mods that choose not to publish directly on spigot.org. Kinda throws a wrench in that particular set of gears but it is of course up to them to choose where and how they publish. This could be an effective workaround though.

**Comment by itzg** [comment]
I could pretty easily use a `--skip-up-to-date` option on `mc-image-helper get` to ensure the latest copy is downloaded, but skip the download when up to date. Would that probably be sufficient?

**Comment by Toucan-Sam** [comment]
I'm not 100% sure I understand. Words are hard. :)
Thanks for the response though. 10/10 for service.

My use case is that mods like Geyser don't publish via SPIGET, so I'm using the URL of their lastSuccessful build .jar file to download it when the server starts so it's easy to (re)deploy servers via docker-compose.

The servers are set to auto-update (via ouroboros), so if you push an updated image for the branch I'm using (itzg/minecraft-server), it'll pull that and restart. When it does that, it would be great if it would re-download the files in `MODS_FILE` to make sure they're up-to-date.

Easy to check timestamps of files on disks, but less easy to check remote HTTP timestamps so I assume the file has to be redownloaded completely? Which is fine by me. I'd rather it be updated than not.

Obviously if it's possible to skip wasting bandwidth on a file that is already the latest, then that's ideal. If you can do that with a `--skip-up-to-date` option, then by all means. Me not understanding the specific implementation is not a reason not to do it. :)

**Comment by itzg** [comment]
Very good, I think that option will take care of that scenario, so I'll work on that soon. I forgot that some artifacts are provided via Jenkins or similar, where the latest build URL always looks the same.

**Comment by Stealthii** [comment]
@Toucan-Sam another option you could utilize in the meantime is setting `REMOVE_OLD_MODS` to "TRUE". This will clear the mods folder and redownload any on container start/restart.

**Comment by shotah** [comment]
@Toucan-Sam, @Stealthii ,and @itzg Going to be honest, the whole Forge and Fabric with hardcoded versions in their URLs really make this difficult. You will always be downloading the same versions. It would be really nice if they provided Latest tags so they could be auto updated on restart.

**Comment by itzg** [comment]
This will be published with this build https://github.com/itzg/docker-minecraft-server/actions/runs/1803794206

Re-open and let me know if the new behavior still doesn't solve your scenario.

**Comment by itzg** [comment]
Testing so far sounds good

https://github.com/itzg/docker-minecraft-server/discussions/1330#discussioncomment-2124720

**Comment by Toucan-Sam** [comment]
Missed the last email with updates. Apologies. Awesome progress though!

Still keen to write some doco but some personal life getting in the way.

@shotah I've raised issues on some more popular spigot mods about using latest tags and the general consensus is "you shouldn't automate your production services". Which I personally disagree with, but it's their project. Same goes for Fabric and Forge I guess.

In this case I might say, don't use this feature for those particular distros?

**Comment by shotah** [comment]
@Toucan-Sam I've run into the same push back. They don't seem keen on automation. I have been working on using the Forge api. You can follow the PR, it should elevate some of this, and hopefully we can flesh it out to the point it just works. 👍 

[Current ForgeApi - Checkback once latest PR is merged](https://github.com/itzg/docker-minecraft-server#forgeapi-usage-to-use-non-version-specific-projects)
