### ISSUE TITLE
Changing MOTD doesn't work

### ISSUE THREAD

**Issue by owu-1** [itzg/docker-minecraft-server#1261]
### Describe the problem

I ran the latest image with ```-e MOTD="My Server"``` and the MOTD doesn't change. It keeps the default one 

I tried running the java17 image and the MOTD changes properly. That one was updated a day ago so I guess it was before 977d082638347092261e834d7e5dd2f54db0f5f6 when code related to MOTD was changed

### Container definition

```podman run -d -it -p 25565:25565 -e EULA=TRUE -e MOTD="My Server" itzg/minecraft-server```
```podman run -d -it -p 25565:25565 -e EULA=TRUE -e MOTD="My Server" itzg/minecraft-server:java17```

### Container logs

![image](https://user-images.githubusercontent.com/83254308/148636161-bc9699ab-0775-4516-971b-3aa26c6b81fb.png)

![image](https://user-images.githubusercontent.com/83254308/148636199-6e354e67-d592-4097-9bec-fa95345e003a.png)

**Comment by owu-1** [comment]
It seems to be working again. I donno what I did haha sorry

**Comment by itzg** [comment]
It also depends on `OVERRIDE_SERVER_PROPERTIES`

**Comment by Stealthii** [comment]
I also updated to the latest images and the MOTD isn't being set anymore. OVERRIDE_SERVER_PROPERTIES is set to true and MOTD is set to a string value.

Log:
```
minecraft-plscraft-s3-1  | [init] Setting motd to 'A Fabric Minecraft Server powered by Docker' in /data/server.properties
```
MOTD is set to "PlsCraft S3"

**Comment by Stealthii** [comment]
MOTD issue seems to be related to the following change in #1259:
```diff
-  if [ -z "$MOTD" ]; then
+  if ! [ -v "$MOTD" ]; then
```

**Comment by drewburr** [comment]
I'm also running into this issue. Still looking into what might be causing it. Using the latest image version

Here are the env variables from my container:

```text
$ env
SERVER_NAME="Mum's House"
MOTD="Central Station Server"
HOSTNAME=cf5f2792f810
LANGUAGE=en_US:en
JAVA_HOME=/opt/java/openjdk
RCON_PASSWORD=minecraft
AUTOPAUSE_PERIOD=10
RCON_PORT=25575
EULA=TRUE
TYPE=PAPER
VIEW_DISTANCE=12
PWD=/data
AUTOSTOP_PERIOD=10
TZ=America/Chicago
JVM_DD_OPTS=disable.watchdog:true
HOME=/root
LANG=en_US.UTF-8
USE_AIKAR_FLAGS=true
AUTOSTOP_TIMEOUT_EST=3600
ENABLE_AUTOSTOP=false
AUTOPAUSE_TIMEOUT_INIT=60
ENABLE_RCON=true
GID=1000
AUTOPAUSE_TIMEOUT_KN=20
MAX_PLAYERS=50
SHLVL=1
INIT_MEMORY=500M
MAX_TICK_TIME=-1
AUTOPAUSE_KNOCK_INTERFACE=eth0
LC_ALL=en_US.UTF-8
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
OVERRIDE_SERVER_PROPERTIES=true
VERSION=1.18.1
MEMORY=1G
UID=1000
ENABLE_AUTOPAUSE=true
JAVA_VERSION=jdk-17.0.1+12
MAX_MEMORY=2G
AUTOSTOP_TIMEOUT_INIT=1800
AUTOPAUSE_TIMEOUT_EST=120
_=/usr/bin/env
```

**Comment by drewburr** [comment]
Looks like Stealthii is correct on this one. `-v "$MOTD"` is used to check if a environment variable is set, and returns 0 if the value is set. 

```
if ! [ -v "$MOTD" ]; then
  # Set a reasonable default MOTD
```

The above says "if MOTD is set, set a default", and I think we want the opposite here. I've opened #1265 to fix this

**Comment by tomis007** [comment]
Just wanted to mention I'm running into the same issue, and the PR fix looks to be correct

**Comment by itzg** [comment]
> Just wanted to mention I'm running into the same issue, and the PR fix looks to be correct

The fix accidentally worked. I have applied a fix to the fix and published. It's ready to re-test.

**Comment by tomis007** [comment]
That fixed it for me! Thanks for the quick merge
