### ISSUE TITLE
cant write to file in data dir, while data dir has 777 permissions recursively

### ISSUE THREAD

**Issue by pjalsGit** [itzg/docker-minecraft-server#1269]
### Describe the problem

cant write to file in data dir, while data dir has 777 permissions recursively
running `sudo setenforce 0` works

### Container definition

```
echo $UID $GID
 1000 1000

docker run -v /home/me/dockermc/:/data -d -it -p 25565:25565 -e EULA=TRUE itzg/minecraft-server
```

### Container logs

```
chmod: changing permissions of '/data': Permission denied
[init] Changing ownership of /data to 1000 ...
chown: cannot read directory '/data': Permission denied
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx. 2 0 0 4096 Jan  9 17:12 /data'
/start-utils: line 155: /data/eula.txt: Permission denied
[init] ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=1000
```

**Comment by Stealthii** [comment]
Even if the directory is writable, the uid/gid should be set to the owner of that directory, as during bootstrap chmod is run to ensure ownership.

Apply `UID` and `GID` environment variables with the correct values should solve your issue!

**Comment by pjalsGit** [comment]
i checked and my UID and GID are 1000

**Comment by itzg** [comment]
> i checked and my UID and GID are 1000

Your command snippet doesn't show that. Please update with that. Using chmod 777 is not a viable approach. Fix the directory ownership on the host side.

**Comment by pjalsGit** [comment]
updated the issue with info

**Comment by itzg** [comment]
I think @Stealthii meant checking those variables on the docker command. In any case, just make sure that host directory is already owned by uid 1000 and it is normally fine from there. Something is unusual on your system so there's nothing I know to fix in the image.

**Comment by pjalsGit** [comment]
appending `-e UID=1000 -e GID=1000` to the command worked
