### ISSUE TITLE
Support loading Spigot-family world zips on non-Spigot servers

### ISSUE THREAD

**Issue by wlritchi** [itzg/docker-minecraft-server#1290]
### Enhancement Type

Improve an existing feature

### Context
Servers in the Spigot family arrange their world files somewhat differently than other servers; for a world directory `foo/`, instead of locating the nether and end dimensions in `foo/DIM-1/` and `foo/DIM1/`, Spigot locates them in `foo_nether/DIM-1/` and `foo_the_end/DIM1/`. The `start-setupWorld` script is aware of this possibility, and knows to copy these directories for Spigot-family servers.

### Current behaviour
`start-setupWorld` determines whether to create Spigot-style dimensions based on the family of the server about to be launched. When loading a Spigot-style world zip for a standard-style server jar, the script picks only one of the dimensions (at random) and fails to copy the other two.

### Desired behaviour
`start-setupWorld` detects the existence of Spigot-style or standard-style dimensions based on what appears in the world zip, and renames them if needed. In particular, a world zip created using either style of dimensions should be correctly loaded by either style of server.

**Comment by wlritchi** [comment]
I'm prototyping this, but the edge cases make it a little bit ugly. Consider:

1. World files with no nether
2. World files with only a vanilla nether
3. World files with only a Spigot nether
4. World files with both (shouldn't happen, but we should have a defined behaviour in this case)

Vanilla servers will load the vanilla nether in cases 2 and 4, and no nether at all in cases 1 and 3. Spigot servers will load any nether that's provided[1], favouring the Spigot nether in case 4.

I suspect that we probably want to have the same preferences as Spigot regardless of what server type we're actually loading - if the world file contains both, favour the Spigot nether, otherwise do whatever reorganization is necessary to ensure the server finds the dimension correctly.

[1] According to some forum posts anyway, but I haven't yet tested this myself.

**Comment by itzg** [comment]
Thanks. Yes it is indeed one of those cases where listing out the scenarios helps to reason through it.
