### ISSUE TITLE
Animated GIF as ICON env var does not work

### ISSUE THREAD

**Issue by knrdl** [itzg/docker-minecraft-server#1303]
### Describe the problem

Setting ICON=https://example.org/image.gif ends up in creation of these files:
* server-icon-0.png
* server-icon-1.png
* server-icon-2.png
* ... (One image per frame in gif file)

The necessary server-icon.png won't be created. A solution might be to only extract the first frame

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
I'll remove the stale tag since I have this queued up to work.

**Comment by itzg** [comment]
Sorry for taking so long to work on this. Do you have an example gif file with multiple frames that I could use for dev/test?
