### ISSUE TITLE
[FR] generic pack prefix/suffix

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#1315]
It'd be useful to have the option to configure a prefix/suffix for generic pack(s) URLs.

i.e.
```
GENERIC_PACKS_PREFIX=https://cdn.example.org/
GENERIC_PACKS=emea-v9.0.1,mods-v4.3.6
GENERIC_PACKS_SUFFIX=.zip
```

This would be especially useful for our use-case as our pack URLs are [secret](https://github.com/PixelmonToGo/gitops-k8s/blob/bc46b9c8a630030e9728c5bc1a87e635027edfb8/minecraft/minecraft/minecraft-forge-squirtle-helm-values.txt#L6).
Ideally we'd like to use Renovate to bump the pack versions based on server pack releases.

**Comment by ChipWolf** [comment]
The suffix probably isn't totally necessary, thought I should include it for any other edge cases that may crop up.

**Comment by itzg** [comment]
Yeah, I like that idea.

**Comment by itzg** [comment]
The latest image now includes the new variables.

**Comment by ChipWolf** [comment]
@itzg validated in our dev environment, will promote once there's a versioned tag.
Thanks again ⬆️ 5️⃣

**Comment by itzg** [comment]
Now included in image tags `2022.2.0`

**Comment by ChipWolf** [comment]
> Now included in image tags `2022.2.0`

![](https://i.cwlf.uk/6nyP3)

Could you bake an openj9 tag when you have a moment please?

**Comment by itzg** [comment]
This time it actually pushed the images

https://hub.docker.com/layers/itzg/minecraft-server/2022.3.0-java8-openj9/images/sha256-a884a8b246d53899d297fd9bab69ffaf0eab8f177b3b5abafd98d7515eb92dbb?context=explore

**Comment by ChipWolf** [comment]
Rolled into prod & working perfectly
