### ISSUE TITLE
Support ServerStarter yaml configs for modpacks

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1322]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

The structure provided by https://github.com/TeamAOF/ServerStarter applies to some modpacks, such as

- https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5

**Comment by nickavem** [comment]
Is there any way to run AOF5 until this is implemented?

**Comment by itzg** [comment]
If the plugins/mods can be pre-downloaded into a host directory, then could attached to `/plugins` [as described here](https://github.com/itzg/docker-minecraft-server#optional-plugins-mods-and-config-attach-points)

**Comment by itzg** [comment]
Ah yes, this issue can really be closed now with the auto CurseForge support. 

Yes, a PR would be great to add the modpack specific exclude/includes. Or can add to the global excludes for those that are blatantly client only mods...which is already quite a few as you see.
