### ISSUE TITLE
Improve handling of invalid/unknown VERSION

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1323]
### Describe the problem

The "Missing property" step should be when/where the startup to stop and explain.

### Container definition

```
docker run -it --rm -e EULA=TRUE -e VERSION=1.0 itzg/minecraft-server:java8-multiarch
```

### Container logs

```
[init] Resolving type given VANILLA
[init] Downloading minecraft_server.1.0.jar ...
[mc-image-helper] 14:41:17.786 ERROR : Operation failed: Missing property in path $['downloads']['server']
[init] ERROR failed to obtain version manifest from https://launchermeta.mojang.com/v1/packages/edfc56a64dfc6430665d745264732db53b0d1b41/1.0.json (1)
```

**Comment by shotah** [comment]
Is this something we can bake a hard coded value on build? Say when the build runs it grabs this value as a default and bakes it into the image?

**Comment by itzg** [comment]
Mainly I'm just wanting the error message to be more intuitive 😀 I think I'm missing a conditional on the Mojang manifest lookup. Or could be that "null" string behavior jq does.

**Comment by itzg** [comment]
And I should link the discussion that caused me to notice

https://github.com/itzg/docker-minecraft-server/discussions/1319
