### ISSUE TITLE
fresh install, quits without output

### ISSUE THREAD

**Issue by arnolde** [itzg/docker-minecraft-server#1324]
### Describe the problem

I just found this by chance, and since I already had a server with docker running in the cloud, I just ran:
```
docker run -d -p 25565:25565 --name mc itzg/minecraft-server
```
it downloaded all the images and started, but quit immediately with no output.
```
arnolde@mail00:~$ docker ps -a
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS                      PORTS                                                                                              NAMES
d63485fa82d5   itzg/minecraft-server   "/start"                 33 seconds ago   Exited (1) 32 seconds ago        
```
What am I doing wrong? I would expect at least SOMETHING to be printed?
Running Ubuntu 18.04 LTS and Docker version 20.10.7.

regards,
Ethan

**Comment by itzg** [comment]
Your bug reporting is missing the logs that were requested. If you look at the logs it'll tell you the problem.

In any case, [you're missing acceptance of the EULA](https://github.com/itzg/docker-minecraft-server#:~:text=Be%20sure%20to%20always%20include%20%2De%20EULA%3DTRUE%20in%20your%20commands%20and%20container%20definitions%2C%20as%20Mojang/Microsoft%20requires%20EULA%20acceptance.), so add `-e EULA=true`

**Comment by arnolde** [comment]
Sorry for being ignorant... but what logs? I'm used to docker containers logging directly to console, thats why I didnt see any. I'll read the docs some more...
