### ISSUE TITLE
`docker run` gets stuck at `mc-image-helper get ...`

### ISSUE THREAD

**Issue by LucasG04** [itzg/docker-minecraft-server#1331]
### Describe the problem

Hello,
first of all, I am very impressed by the good documentation and the range of the repository.
Unfortunately, when starting the container the process hangs at `mc-image-helper get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json`.

I downloaded the tool and tried the same request (and it was successful):
```sh
$ ./mc-image-helper get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
1.18.1
```

My specs:
Linux raspberrypi 5.10.52-v7l+
armv7 & 4G mem

### Container definition

```sh
docker run -it -p 25565:25565 -e EULA=TRUE -e DEBUG=TRUE itzg/minecraft-server
```

With Minecraft version:
```sh
docker run -it -p 25565:25565 -e EULA=TRUE -e VERSION=1.18.1 -e DEBUG=TRUE itzg/minecraft-server
```

### Container logs

```sh
$ docker run -it -p 25565:25565 -e EULA=TRUE -e DEBUG=TRUE itzg/minecraft-server
+ export HOME=/data
+ HOME=/data
++ id -u
++ id -g
++ ls -lnd /data
+ log 'Running as uid=1000 gid=1000 with /data as '\''drwxrwxr-x 2 1000 1000 4096 Feb  3  2022 /data'\'''
+ echo '[init] Running as uid=1000 gid=1000 with /data as '\''drwxrwxr-x 2 1000 1000 4096 Feb  3  2022 /data'\'''
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Feb  3  2022 /data'
+ '[' '!' -e /data/eula.txt ']'
+ isTrue TRUE
+ local value=true
+ result=
+ case ${value} in
+ result=0
+ return 0
+ writeEula
++ date
+ echo '# Generated via Docker
# Sun 22 Feb 1970 01:56:11 AM UTC
eula=true
'
+ isTrue false
+ local value=false
+ result=
+ case ${value} in
+ result=1
+ return 1
+ isTrue false
+ local value=false
+ result=
+ case ${value} in
+ result=1
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ which java
+ export VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ case "X$VERSION" in
++ get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
++ flags=()
++ local flags
++ isTrue false
++ local value=false
++ result=
++ case ${value} in
++ result=1
++ return 1
++ mc-image-helper get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
```

With Minecraft version:
```sh
$ docker run -it -p 25565:25565 -e EULA=TRUE -e VERSION=1.18.1 -e DEBUG=TRUE itzg/minecraft-server
+ export HOME=/data
+ HOME=/data
++ id -u
++ id -g
++ ls -lnd /data
+ log 'Running as uid=1000 gid=1000 with /data as '\''drwxrwxr-x 2 1000 1000 4096 Feb  3  2022 /data'\'''
+ echo '[init] Running as uid=1000 gid=1000 with /data as '\''drwxrwxr-x 2 1000 1000 4096 Feb  3  2022 /data'\'''
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Feb  3  2022 /data'
+ '[' '!' -e /data/eula.txt ']'
+ isTrue TRUE
+ local value=true
+ result=
+ case ${value} in
+ result=0
+ return 0
+ writeEula
++ date
+ echo '# Generated via Docker
# Mon 23 Feb 1970 02:20:43 PM UTC
eula=true
'
+ isTrue false
+ local value=false
+ result=
+ case ${value} in
+ result=1
+ return 1
+ isTrue false
+ local value=false
+ result=
+ case ${value} in
+ result=1
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ which java
+ export VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ case "X$VERSION" in
+ VANILLA_VERSION=1.18.1
+ export VANILLA_VERSION
+ log 'Resolved version given 1.18.1 into 1.18.1'
+ echo '[init] Resolved version given 1.18.1 into 1.18.1'
[init] Resolved version given 1.18.1 into 1.18.1
+ cd /data
+ export ORIGINAL_TYPE=VANILLA
+ ORIGINAL_TYPE=VANILLA
+ isTrue false
+ local value=false
+ result=
+ case ${value} in
+ result=1
+ return 1
+ isTrue false
+ local value=false
+ result=
+ case ${value} in
+ result=1
+ return 1
+ versionLessThan 1.7
+ mc-image-helper compare-versions 1.18.1 lt 1.7
```

**Comment by itzg** [comment]
Since it only happens within the container and that's the first host lookup, I'm guessing it is a DNS or UDP firewall issue with your docker setup. To see if it is DNS you could add `--dns 1.1.1.1` to the docker run to ensure it is using CloudFlare's. Firewall debugging will vary on your setup. I hope that helps.

**Comment by LucasG04** [comment]
Thank you for the quick reply. I'll take a closer look.

**Comment by LucasG04** [comment]
Unfortunately, the DNS option did not help. I'll take a closer look later. I'll close the issue for now and if I think that there is a problem with the image, I'll open it again.

**Comment by Borrelhapje** [comment]
I'm having the same issue (also raspberry pi), and I noticed some apparent time(zone) issues:
```
root@4419b00bb823:/data# date
Sat 28 Feb 1970 03:34:19 AM UTC
root@4419b00bb823:/data# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=54 time=1021238 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=54 time=1021251 ms
```

The date command on the host reports the correct date and time. Server was started with `docker run -e EULA=TRUE itzg/minecraft-server:java17`. 

What I also tried:
 - mounting /etc/localtime and /etc/timezone
 - --dns 1.1.1.1 as extra argument to docker
 - curl to any server exits with `(28) Timeout was reached`

@LucasG04 Did you ever find a fix?
@itzg Would you mind reopening this?

**Comment by itzg** [comment]
@Borrelhapje you mentioned

> curl to any server exits with (28) Timeout was reached

So, I'm not sure how I'm supposed to fix that.

**Comment by Borrelhapje** [comment]
I meant that curl to any server from within the container fails with that exit code. The same command on the host works fine. I think it has something to do with the wrong time reported, e.g. curl sets the timeout to be somewhere in the near future, which is somewhere in 1970 according to the container.

**Comment by itzg** [comment]
@Borrelhapje I understood what you meant. That sounds like a general issue with Docker since my image doesn't have control over what time is reported from the kernel.

**Comment by Borrelhapje** [comment]
For others encountering these issues: my SD card with the raspberry pi OS install died on reboot. Had to reinstall the whole OS but that did somehow solve these issues.
