### ISSUE TITLE
Support vanilla tweaks resource packs

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1335]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

In addition to datapacks and crafttweaks, also need resource pack support at least via a sharecode.

**Comment by shotah** [comment]
Currently on hold, but PR can be found here: https://github.com/itzg/docker-minecraft-server/pull/1336

**Comment by itzg** [comment]
Merged #1336
