### ISSUE TITLE
Fabric server updates on new installer rather than new loader

### ISSUE THREAD

**Issue by Stealthii** [itzg/docker-minecraft-server#1350]
When using the `TYPE=FABRIC` server, the deploy script for Fabric uses the installer as the version identifier for Fabric updates.

As the installer only changes the method by which we install fabric-loader, with Fabric changes being included in the loader itself, we should use the loader version number to signify current Fabric version.

**Comment by itzg** [comment]
Ok, I see what you mean. I'll get this adjusted.

**Comment by Stealthii** [comment]
@itzg I've raised PR #1351 which not only fixes this but uses the new launcher jar method which leads to cleaner version management similar to Paper or other servers.

If you're interested in the alternative that still uses the installer:
https://github.com/itzg/docker-minecraft-server/compare/master...Stealthii:feature/fabric-update

**Comment by itzg** [comment]
Awesome! I'll review that later today.
