### ISSUE TITLE
exec /start: no such file or directory

### ISSUE THREAD

**Issue by tamara-schmitz** [itzg/docker-minecraft-server#1356]
### Describe the problem

Container fails to start with error
`exec /start: no such file or directory`

Broken version:
docker.io/itzg/minecraft-server  latest      27f375adda33

Platform: amd64

Also tried Tag 2022.3.0-java17 sha256:ea036f60092ca77d92785c7f528073849e6fd127255ed3b359da477ff7e4d6a3

Confirmed working version:     docker.io/itzg/minecraft-server@sha256:40daceaedff07f6d57bb8686b813497231046fcea302c97936fd9b68ed4e72a1

### Container definition

```
podman create --restart always --name mc-server -p 25565:25565 -p 8123:8123 -p 24454:24454/udp \
    -m 8G -e MEMORY="6G" \
    -e JVM_OPTS="-server -XshowSettings:vm" \
    -e EULA="TRUE" -e TYPE="FABRIC" \
    -e VERSION="1.18.1" \
    --label io.containers.autoupdate=registry \
    -v /var/minecraft/$SUBFOLDER:/data \
    docker.io/itzg/minecraft-server
```

### Container logs

podman logs mc-server
```
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
exec /start: no such file or directory
```

**Comment by shotah** [comment]
Were you able to try replacing the ENV Var with an existing folder name and see if that fixes it? 
Example: `-v /var/minecraft/$SUBFOLDER:/data \` -> `-v /var/minecraft/hardcore:/data \`

**Comment by tamara-schmitz** [comment]
> Were you able to try replacing the ENV Var with an existing folder name and see if that fixes it? Just for testing of course. Example: `-v /var/minecraft/$SUBFOLDER:/data \` -> `-v /var/minecraft/hardcore:/data \`

That's a non-issue. Forgot to replace that. But when I run the script, it shows me that it puts a valid path there.

**Comment by tamara-schmitz** [comment]
hmm i cannot replicate this issue on my local machine...

**Comment by tamara-schmitz** [comment]
Wow. Okay. The issue was a dirty cache. I might have cancelled a pull. So purging the cache and pulling again solved this issue.

**Comment by itzg** [comment]
Thanks for following up with more info @tamara-schmitz . That'll help any others that bump into this scenario.
