### ISSUE TITLE
MODS_FILE getting download error

### ISSUE THREAD

**Issue by mech16** [itzg/docker-minecraft-server#1364]
Pretty sure it is probably something simple I am missing but the when I use MODS_FILE I get a download error in my container logs.

[mc-image-helper] 02:41:33.213 ERROR : Operation failed: Failed to download https://www.curseforge.com/minecraft/mc-mods/customized-dungeon-loot/download/3565661/file: status code: 403, reason phrase: Forbidden

If I place the link directly into my web browser it starts the download immediately no waiting for 5 seconds.

If I use the mods folder and drop the jar file into it and do not use MODS_FILE things load nicely.

**Comment by itzg** [comment]
CurseForge URLs require "authorization" via browser cookies. It works in the browser because it redirects to an authenticated instance of the CDN location. I could be wrong about some of the details, but that's the general gist.

**Comment by mech16** [comment]
Sounds simple enough. I guess my next problem will be to find a CDN link for the mods my son would like. 

Is there a link cross referance web page or something similar?

Thank you for all the help.

**Comment by shotah** [comment]
@mech16 I was running into the same issue. You have to Split the file id and do some formatting to make it work. Then you have to track versions and dependencies. I did add a way to by pass all of this.

[ForgeApi Usage](https://github.com/itzg/docker-minecraft-server#forgeapi-usage-to-use-non-version-specific-projects)
