### ISSUE TITLE
PATH Error on startup after pulling the last image

### ISSUE THREAD

**Issue by dwilson1251** [itzg/docker-minecraft-server#1370]
### Describe the problem

Simply pulled the latest version and on statup get the following error in the log; running via Portainer.  It's been working fine for the at least a month when I last checked:

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 7 1000 1000 4096 Feb  9 00:09 /data'
[init] ERROR: PATH should not be explicitly passed into the container
[init]        Remove configuration of that variable.
```

**Comment by dwilson1251** [comment]
Reverted back to tag 2021.23.1 and now it's working again with no errors.

**Comment by itzg** [comment]
I'm guessing you're using a NAS, probably Synology? Please report the issue to that vendor as described here

https://github.com/itzg/docker-minecraft-server/issues/749#issuecomment-1040242143

Or wait for the mentioned issue where I yet again need to work around their flaw.

**Comment by dwilson1251** [comment]
Not using a NAS; ubuntu running docker, leveraging Portainer (v2.11.1) for management.  I removed UID/GID from ENV variables, but they keep get added back in when pulling the latest image.  Same config with the prior version of the image.  Portainer issue?

**Comment by dwilson1251** [comment]
removing the env in red from the other ticket you linked fixed the issue.  Specifically: PATH, JAVA_HOME, JAVA_VERSION, JVM_XX_OPTS, LANG, LANGUAGE, LC_ALL

Appreciate you making this available; have a great rest of your week.
