### ISSUE TITLE
java8 version with FlightRecorder

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#1375]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I'm looking for a java8 image with [FlightRecorder](https://developers.redhat.com/blog/2020/08/25/get-started-with-jdk-flight-recorder-in-openjdk-8u) for continuous profiling, but it doesn't look like the current java8 build has this feature.

I know OpenJDK 8 (version 8u262+) and Azul Zulu 8+ (version 8u212+) include FlightRecorder.

Additionally, it doesn't look like the current alpine build [is supported](https://github.com/docker-library/docs/blob/master/openjdk/README.md#supported-tags-and-respective-dockerfile-links) anymore:

https://github.com/itzg/docker-minecraft-server/blob/f31c57b8979f59dbf034b2c7a82fe1a497bbb27a/.github/workflows/build-multiarch.yml#L42

Sticking to `_/openjdk`; the remaining options are:

* [8u322-jdk-oraclelinux8](https://github.com/docker-library/openjdk/blob/a73c475009d29f67e0dfea5dd3c605da79506df8/8/jdk/oraclelinux8/Dockerfile) (8-jdk-oracle)

* [8u322-jdk-slim-bullseye](https://github.com/docker-library/openjdk/blob/a73c475009d29f67e0dfea5dd3c605da79506df8/8/jdk/slim-bullseye/Dockerfile)  (8-jdk-slim)

**Comment by itzg** [comment]
Per our Discord convo https://github.com/itzg/docker-minecraft-server/issues/1376

**Comment by itzg** [comment]
As for the OP we found that the java8-multiarch variants does have flightrecorder support.

**Comment by ChipWolf** [comment]
In theory, this issue is resolved.
