### ISSUE TITLE
Pin java8-multiarch at Forge compatible version

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1380]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

As reported here https://github.com/MultiMC/Launcher/issues/4470#issuecomment-1025114255 , Forge doesn't work with Java 8 update 321 or newer.

Should pin the java8-multiarch variant to [8u312-b07-jre](https://hub.docker.com/layers/eclipse-temurin/library/eclipse-temurin/8u312-b07-jre/images/sha256-0ff5a316cc79e112f26135f72a6d415c330382ffd8405f5f2ded658553d75e19?context=explore)

**Comment by shotah** [comment]
@itzg this can be closed.
