### ISSUE TITLE
Create a variant for jdk and slim down mainline variants to jre

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1381]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

As a follow up to https://github.com/itzg/docker-minecraft-server/issues/1064, now that image variants are easy to declare I would like to switch the mainline variants (latest, java17, java8-multiarch, etc) to a JRE base image and then add java8-jdk and java17-jdk variants.

**Comment by shotah** [comment]
@itzg this can be closed as well.
