### ISSUE TITLE
Add support for velocity

### ISSUE THREAD

**Issue by misterquestions** [itzg/docker-minecraft-server#1385]
### Enhancement Type

New server type

### Describe the enhancement

Hey there!

Would it be possible to add support for [Velocity proxy](https://velocitypowered.com/)

Thanks in advance.

**Comment by misterquestions** [comment]
Just found [this](https://github.com/itzg/docker-bungeecord), however the docs never mention how to run a proxy with a similar image like this, so would be great to add it for a better visibility :D

**Comment by itzg** [comment]
A reference to the proxy options does seem reasonable for the docs.
