### ISSUE TITLE
RCON CMDS: Missing Export, and Run order could be improved.

### ISSUE THREAD

**Issue by shotah** [itzg/docker-minecraft-server#1398]
### Describe the problem

First connect command is not exported.
Run order is in the case it does client level stuff before stopping maintenance tasks. Aka if pregen'ing chunks its setting teams while chunk pregen is still going before pausing it.

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by shotah** [comment]
Created PR for resolution. <https://github.com/itzg/docker-minecraft-server/pull/1397>

**Comment by itzg** [comment]
Fixed by #1397
