### ISSUE TITLE
Allow delayed start by using env varibles

### ISSUE THREAD

**Issue by misterquestions** [itzg/docker-minecraft-server#1407]
### Enhancement Type

A completely new feature

### Describe the enhancement

Hey there!

It would be really great to have some environment variable that allows the server to start with a given delay in seconds using environment variables.

For example: 

Setting `START_DELAY=5` would make the server hold for 5 seconds and then start.

## Why this would be useful?

Imagine we have a stack with docker-compose, where we expect to run a database and a Redis server, there might exist a situation where the Minecraft server starts faster than the DB and some plugins would complain that they can't access DB.

Having the delay enabled for servers would mitigate this issue seamlessly.

This could also be applied in the [docker-bungeecord](https://github.com/itzg/docker-bungeecord) project as it can be benefited from this as well.

**Comment by shotah** [comment]
This should already be controlled by depends on and the proper health checks on the containers themselves. AKA if the DB has a proper health check it'll let docker know when its "healthy" and it can start minecraft when set in "depends_on".  More information can be found on the docker compose website. https://docs.docker.com/compose/startup-order/

**Comment by misterquestions** [comment]
For MariaDB/MySQL container is marked as "healthy" even when the connection allowance has not been reached yet, this leads to the issue I describe in the request.

**Comment by itzg** [comment]
I agree with @shotah 's suggestion. This is a broader aspect of Docker that is already solved and adding an arbitrary startup delay is a brittle solution. 

The official MariaDB, etc images tend not to provide health checks out of the box, since it is left to define by the end user. So, you'll need to declare the health checks yourself.
