### ISSUE TITLE
Allow user to specify desired UID/GID as environment variables

### ISSUE THREAD

**Issue by d3adb5** [itzg/docker-minecraft-server#1416]
### Enhancement Type

A completely new feature

### Describe the enhancement

Have the Docker entry point accept environment variables such as `UID` and `GID` with which to run the server in the end.

This would be useful in case users want more granular control over filesystem permissions on their servers. While one can specify UID and GID directly through Docker and start the server, the autopausing feature requires the use of knockd, and requires the UID of the process invoking `sudo` to be in the sudoers list. When that isn't the case, autopausing is simply disabled.

The relevant logs from the container when a UID like `996` is specified and autopausing is enabled:

```
sudo: you do not exist in the passwd database
[Autopause loop] Failed to start knockd daemon.
[Autopause loop] Probable cause: Unable to attach to interface "eth0".
[Autopause loop] Available interfaces within the docker container:
[Autopause loop]   eth0 lo
[Autopause loop] Please set the environment variable AUTOPAUSE_KNOCK_INTERFACE to the interface that handles incoming connections.
[Autopause loop] If unsure which interface to choose, run the ifconfig command in the container.
[Autopause loop] Autopause failed to initialize. This log entry will be printed every 30 minutes.
```

**Comment by itzg** [comment]
You already can

https://github.com/itzg/docker-minecraft-server#running-as-alternate-usergroup-id

**Comment by d3adb5** [comment]
I completely missed that. My bad!
