### ISSUE TITLE
Stuck on 100% CPU

### ISSUE THREAD

**Issue by valentinfrlch** [itzg/docker-minecraft-server#1418]
### Describe the problem

Running on Raspberry Pi 4 with 8GB RAM. When I start the the server (latest tag) CPU usage spikes to 100%.  I left it running over night and after 8 hours it still hasn't started. 

### Container definition

```
docker run -d -it -p 25565:25565 -e EULA=TRUE -e MEMORY=4G itzg/minecraft-server
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Mar 10  2022 /data'
```

**Comment by valentinfrlch** [comment]
The java version seems to be the problem: I tried running "java -Xmx1024M -Xms1024M -jar server.jar nogui" directly and got this: 
`Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
	java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
`
I suppose I don't have Java 17 installed...

**Comment by itzg** [comment]
The Minecraft server performs terribly on RaspberryPi. One thing  that is worth trying is TYPE=PAPER since it is more optimized than the vanilla one from Mojang. 

I'm not sure what your experiment really identified, since the default image itself bundles Java 17 unless you're using the java11 or java8 image tags.

**Comment by valentinfrlch** [comment]
Thanks for replying. I tried running a paper server, with the same result unfortunately. I looked into the /data folder inside the container. Is it normal that there's only the eula.txt file?

**Comment by itzg** [comment]
I'm sorry, didn't realize that one line of logs is the only line you're seeing. Can you add `-e DEBUG=true` and provide that output?

**Comment by valentinfrlch** [comment]
Yes sure! I just got an AIRPLANE server working, on another Raspberry Pi (also model 4).

**Comment by valentinfrlch** [comment]
Got some logs here: 
```
+ export HOME=/data
+ HOME=/data
++ id -u
++ id -g
++ ls -lnd /data
+ log 'Running as uid=1000 gid=1000 with /data as '\''drwxrwxr-x 2 1000 1000 4096 Mar 10  2022 /data'\'''
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
[init] 1970-03-12 06:50:35+00:00 Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Mar 10  2022 /data'
+ '[' '!' -e /data/eula.txt ']'
+ isTrue TRUE
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 0
+ writeEula
++ date
+ echo '# Generated via Docker
# Wed 13 May 1970 11:36:27 AM UTC
eula=true
'
+ isTrue false
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
+ isTrue false
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 1
+ [[ -n '' ]]
+ [[ -n '' ]]
+ fixJavaPath
+ which java
+ export VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
+ case "X$VERSION" in
++ get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
++ flags=()
++ local flags
++ isTrue false
++ local oldState
+++ shopt -po xtrace
++ oldState='set -o xtrace'
++ shopt -u -o xtrace
++ return 1
++ mc-image-helper get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
```

**Comment by itzg** [comment]
Thanks, but still a mystery 😀 Can you now add `-e DEBUG_GET=true` since it seems to be spinning in the network operation.

**Comment by valentinfrlch** [comment]
The only line I'm getting is that one: 
```
Error: LinkageError occurred while loading main class net.minecraft.bundler.Main
	java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0```

Very much puzzled about this. I'm going to run "system prune" again and redownload everything again...

**Comment by valentinfrlch** [comment]
Btw: I found this issue which describes the same problem: https://github.com/itzg/docker-minecraft-server/issues/1372#issue-1145090470

**Comment by itzg** [comment]
Thank you, I had already forgotten about the other issue, which does indeed seem to be exactly the same. Let's close out yours and I'll tweak the title of the other for clarification.
