### ISSUE TITLE
README.md: Custom detach sequence

### ISSUE THREAD

**Issue by PatBoud** [itzg/docker-minecraft-server#1425]
### Enhancement Type

Not sure

### Describe the enhancement

In the README.md, "Interactive and Color Console" section, add this information that changes the default "detach" key sequence using the "--detach-keys=..." option.

The command is:
docker attach mc --detach-keys="ctrl-c"

This offer 2 advantages:
- Avoids having to remember the obscure default "CTRL-P, CTRL Q" sequence
- Avoids accidentally stopping the container if pressing "CTRL-C" when trying to exit the console

This way, you can exit the native console with CTRL-C just like RCON.

Thank you!

**Comment by itzg** [comment]
The detach behavior is not specific to this image, so I am hesitant to re-iterate information that is already in https://docs.docker.com/engine/reference/commandline/attach/; however, I can see that briefly mentioning the option exists and linking to there would be very helpful.

**Comment by ChipWolf** [comment]
I think this is entirely out of scope & not worth mentioning in the readme. There's a reason it's a sequence of key combinations and definitely not 'CTRL-C' https://docs.docker.com/engine/reference/commandline/attach/#extended-description

CTRL-C sends SIGKILL to stop the container while attached.
