### ISSUE TITLE
Some JAR SPIGET plugins are being decompressed

### ISSUE THREAD

**Issue by JAHMCR** [itzg/docker-minecraft-server#1426]
### Describe the problem

When trying to download some plugins using SPIGET they are being decompressed instead of just copying to the plugins folder.

It happened with the following plugins:

DeluxeMenus (11734)
LuckPerms (28140)
PlaceholderAPI (6245)
SkinsRestorer (2124)
ViaVersion (19254)
ViaBackwards (27448)

### Container logs

```
Server  | [init] Downloading resource 6245 ...
Server  | [init] Extracting contents of resource 6245 into plugins
Server  | [init] Downloading resource 11734 ...
Server  | [init] Extracting contents of resource 11734 into plugins
Server  | replace /data/plugins/META-INF/MANIFEST.MF? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
Server  | (EOF or read error, treating as "[N]one" ...)
Server  | [init] Downloading resource 27448 ...
Server  | [init] Extracting contents of resource 27448 into plugins
Server  | replace /data/plugins/META-INF/MANIFEST.MF? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
Server  | (EOF or read error, treating as "[N]one" ...)
```

**Comment by itzg** [comment]
Thanks for reporting this!

Introduced by #1413

**Comment by itzg** [comment]
The latest images should now fix this issue.

**Comment by JAHMCR** [comment]
Thank you very much @itzg! Is it already available on Docker website to pull?

**Comment by JAHMCR** [comment]
But now I'm now getting this error, is it related or should I create a different issue?

`[init] Getting plugins via Spiget
[init] Downloading resource 2124 ...
[mc-image-helper] 02:49:10.485 ERROR : 'get' command failed: Unexpected content type 'application/octet-stream', expected any of [application/zip, application/java-archive]
[init] ERROR: failed to download resource '2124' from https://api.spiget.org/v2/resources/2124/download
[init]        Visit https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/14.1.13/SkinsRestorer.jar to pre-download the resource
[init]        instead of using SPIGET_RESOURCES
`

**Comment by itzg** [comment]
You reformatted the output and it hid the instructions it was telling you. As originally formatted:
```
[mc-image-helper] 00:39:33.022 ERROR : 'get' command failed: Unexpected content type 'application/octet-stream', expected any of [application/zip, application/java-archive]
[init] ERROR: failed to download resource '2124' from https://api.spiget.org/v2/resources/2124/download
[init]        Visit https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/14.1.13/SkinsRestorer.jar to pre-download the resource
[init]        instead of using SPIGET_RESOURCES
```

So you need to
> Visit https://github.com/SkinsRestorer/SkinsRestorerX/releases/download/14.1.13/SkinsRestorer.jar to pre-download the resource instead of using SPIGET_RESOURCES

**Comment by JAHMCR** [comment]
Yeah, I did read the instructions, but reported it to you because it was working fine with that specific plugin, the error just occurred to me yesterday. So nothing to do in that case other than manually downloading the resource?

**Comment by itzg** [comment]
I'm now thinking I can combine the old detection logic I had with the new page redirect handling. I'll re-open this and give that a try.

**Comment by JAHMCR** [comment]
Thanks @itzg, I really appreciate it!

Perhaps you can check if the URL Content-Type is different than "text/html" then try to download it, because I've noticed that some plugins like Vault (34315) redirect to a completely external download website (Bukkit) so I guess we must manually download those specific ones due that it's harder to automate them as we don't have the direct download link.

**Comment by itzg** [comment]
Yeah that's along the lines of why I'm thinking. The redirect to HTML was the main thing I wanted to detect there. Also, I later remembered that GitHub resources all report octet-stream since it is a safe "something binary" content type to report.

**Comment by itzg** [comment]
Sorry for the delay. The latest image now reverts back to the prior jar/zip detection. So resource 2124 is working again.

**Comment by JAHMCR** [comment]
Thanks @itzg, it's working perfectly

**Comment by JAHMCR** [comment]
Hey @itzg, it seems like we have a very similar issue, just added a new SPIGET resource ID and it's failing even that's a direct JAR download from Spigot, could you please take a look?

`[init] Downloading resource 88135 ...
[init] Extracting contents of resource 88135 into plugins
[init] ERROR: unsupported archive type: application/java-archive`

**Comment by itzg** [comment]
Just noting that 88135 threw off the logic since the jar contains a jar, `PlugManDummy.jar`. I'll adjust the logic to give plugin.yml a higher precedence.
