### ISSUE TITLE
vanilla tweaks datapacks

### ISSUE THREAD

**Issue by Goten87** [itzg/docker-minecraft-server#1429]
### Describe the problem

when i used the file system of what you have here it did not download the datapack file `vanillatweaks-datapacks.json` needs a type as well
```json
{
    "type": "datapacks",
    "version": "1.18",
    "packs": {
        "survival": [
            "graves",
            "multiplayer sleep",
            "afk display",
            "armor statues",
            "unlock all recipes",
            "fast leaf decay",
            "coordinates hud"
        ],
        "items": ["armored elytra"]
    }
}
```

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
To clarify, can also provide the container config?

cc @shotah

**Comment by shotah** [comment]
Sounds like he caught my documentation bug. When it was just data packs it didn't require a type, so that is how the documentation was. But once we updated it they ALL now require a data type so it knows what it's doing with them.
