### ISSUE TITLE
Selectively override server.properties

### ISSUE THREAD

**Issue by alphafalcon** [itzg/docker-minecraft-server#1443]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

In addition to completely defining the server.properties from env-vars and not touching it at all if it exists a way to selectively override settings would be useful.

I'm running a curseforge modpack, which brings it's own server.properties in the zip.
I'd like to enable rcon to manage things from the console.
I can either start the server to unpack things, edit the server.properties and restart the server or re-create the whole config using env-vars and check on each update that I'm recreating it correctly.

Having a set of single override variables that get evaluated just before the server process is launched could solve this.

**Comment by itzg** [comment]
For non-modpacks, the server properties are already processed in a non-destructive way. Modpacks get unpacked into a sub-directory by default, which is causing the properties file to get completely overwritten. Try setting `CF_BASE_DIR` to "/data" to have it line up with the primary location.

**Comment by alphafalcon** [comment]
okay, I did some source-diving.

I was confused by the MOTD autogenerating, and env-vars being already set in the image.
Got it working for me, thanks for the hints.
