### ISSUE TITLE
Release Docker Images on Github's Container registry 

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [itzg/docker-minecraft-server#1444]
### Enhancement Type

A completely new feature

### Describe the enhancement

I didn't see a previous issue, but apologizes if I missed it. 

I was wondering if it would be a good idea to also have the docker images available via [Github's Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

This is something that I could take on if it is a good idea.

**Comment by itzg** [comment]
It's an interesting idea, but is there a particular problem with the Docker Hub registry?

**Comment by Cyb3r-Jak3** [comment]
The only thing that I can think of is the [rate limit](https://docs.docker.com/docker-hub/download-rate-limit/), but I'm not sure how much of an issue it is to people.

**Comment by itzg** [comment]
From the page you provided, that rate limit is **per end-user** and 200 pulls per 6 hours is a lot considering this image is updated every few days at most. If I applied to their open source program then it's unlimited. [Github Packages are capped at 1 GB per month](https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages), which impacts **all users**.

So, I appreciate the idea, but I only see downsides.

**Comment by Cyb3r-Jak3** [comment]
Ah, I didn't see that. It is odd because I'm pretty sure that I transfer more than 1 GB per month.

I shall close this out.

**Comment by AngellusMortis** [comment]
> GitHub Packages usage is free for public packages.

The limits only apply to private repos. Having a mirror would be nice since I often hit the Docker Hub limit a lot since I have a ton of other things running on a single IP address.

**Comment by itzg** [comment]
Yeah, I'll revive this issue since I have a bunch more experience with GitHub container registry since then.

**Comment by AngellusMortis** [comment]
This also kind applies to all of the other repos as well. Just did not see the point in duplicating it though.

I am actually running into the issue using the proxy Helm chart since it seems to not be accepting my Docker Hub credentials.

**Comment by camalot** [comment]
You can technically publish to both registries. Wouldn't hurt, just in case one is down for some reason.
