### ISSUE TITLE
Support for zip world files locally

### ISSUE THREAD

**Issue by misterquestions** [itzg/docker-minecraft-server#1446]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Hey there.

It would be great if it was possible to use .zip/.tar file mounting to /words, and the image would automatically unzip it and move it into the container.

The current behavior as documented only does that for urls.

**Comment by itzg** [comment]
Good news, the second sub-section clarifies that a directory, zip, or tar file can be referenced 

https://github.com/itzg/docker-minecraft-server#cloning-world-from-a-container-path
