### ISSUE TITLE
Allow ICON to reference a file

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1449]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Right now it can only be a URL

**Comment by vorburger** [comment]
That would be neat! (Although the env. var. is called `SERVER` and not `SERVER_ICON`, [according to this](server-icon.png)?)

**Comment by vorburger** [comment]
In the meantime, one could do (and I do) something like the following in one's `Dockerfile`:

```Dockerfile
COPY servericon.png /data-init/
COPY start-custom /data-init/
...
ENTRYPOINT ["/data-init/start-custom"]
```

where `start-custom` is something like:

```bash
#!/bin/bash
cp /data-init/server-icon.png /data/
/start
```

**Comment by itzg** [comment]
Correction, it's `ICON`

https://github.com/itzg/docker-minecraft-server#server-icon
