### ISSUE TITLE
FTB Architecture Selector

### ISSUE THREAD

**Issue by jtrenaud1s** [itzg/docker-minecraft-server#1457]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Feed The Beast modpacks generally provide x86 as well as ARM64 modpack installers for server software. It'd be nice if there was either some auto-detection or an environment variable we can set in our docker-compose.yml files to specify which one we wish to use. Url scheme for the file is like so:

https://api.modpacks.ch/public/modpack/79/2113/server/arm/linux

**Comment by jtrenaud1s** [comment]
After browsing the code for a moment, I found that this is already implemented, however hadn't actually worked when I ran my docker-compose. I ran `uname -m` on my VM and it responded with aarch64, which is what the installer expects when it downloads and executes, however it didn't actually download that version.

**Comment by itzg** [comment]
Yes, it's already implemented. Can you provide your container logs with DEBUG=true?
