### ISSUE TITLE
Add support for Spigot BungeeCord type

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#146]
https://www.spigotmc.org/wiki/bungeecord/

Reported by `Reviville`

**Comment by Reviville** [comment]
Hey Geoff, could you have another look at that? :3

**Comment by itzg** [comment]
I'm sorry for the delay on this one. I created the issue and then got distracted elsewhere. I should be able to start looking into this.

**Comment by Reviville** [comment]
No hurries. You are doing this in your freetime, i understand that :)
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 27.05.2017, 05:25, Geoff Bourne <notifications@github.com> schrieb:
I'm sorry for the delay on this one. I created the issue and then got distracted elsewhere. I should be able to start looking into this.

**Comment by itzg** [comment]
@Reviville I finally have something for you to try out. For the moment the changes are on a branch and tagged, so please try out the image tag `itzg/minecraft-server:bungee`. [Here is the new docs section](https://github.com/itzg/dockerfiles/blob/mc/bungeecord/minecraft-server/README.md#running-bungeecord). 

Let me know if there's anything that doesn't work or could be a little bit easier to configure.

**Comment by Reviville** [comment]
Well it works but there are some errors left, or in other words optimizations possible.
Tou can find the error in the screenshot at the end.
Apart from that, the image creates a lot of unneccessary data, e.g. banned-ips.json, banned-players.json, 2 server.properties (both not needed, as bungee creates its config.yml), an empty config and mods directory (i know these always exist, so probably not that important) and 2 eula.txt files.
There is no problem for me to remove all those files and directories right after creation, but it would probably make things easier for others, i dont know.
I did not test everything yet, so i don't know how everything works if you add a server to the config etc. I will test this too, if you want.
![image](https://cloud.githubusercontent.com/assets/26972387/26561986/f36a1dd0-44c2-11e7-9965-c42cf98f6f47.png)

**Comment by itzg** [comment]
Thanks! That's exactly the feedback I needed. Yeah, I later realized that BungeeCord is basically a proxy and not a typical minecraft server. Perhaps a separate image is better...the openssl error will most likely go away when using the debian branch of the image, but still is more bulky than all BungeeCord really needs.

**Comment by itzg** [comment]
...yeah, I think I'm going to create a separate image for it, but looks like a `-e` option for offline mode on the minecraft servers would be handy according to

> "Once you have successfully installed BungeeCord, it is time to get it working properly. One of the most essential steps is to set your connected server instances (e.g. Spigot, Bukkit) to run in offline-mode"
 -https://diigo.com/09r4wm

**Comment by itzg** [comment]
...and forgot `-e ONLINE_MODE=false` is already supported by the image :)

**Comment by itzg** [comment]
@Reviville now, give this one a try:

https://hub.docker.com/r/itzg/bungeecord/

**Comment by Reviville** [comment]
It works as expected, good work! I tested everything and adjusted the config.yml as needed.
But 1 more thing and it would for now be perfect... :)
Could you also add uid and gid, so you can execute this as anotheruser, or at least adjust the permission to do so? <3

**Comment by itzg** [comment]
Very good. Yeah, it looks like if I change the internal download location to `/tmp/BungeeCord.jar` (or maybe just `/server`) then the uid/gid form of `docker run ... --user <name|uid>[:<group|gid>]` will probably work.

**Comment by Reviville** [comment]
Would be awesome :)

**Comment by itzg** [comment]
`docker pull` the latest and it should now handle non-root for you. I added a snippet of how I tested at the end of the [repo info](https://hub.docker.com/r/itzg/bungeecord/).

**Comment by Reviville** [comment]
i just meant the old options with "-e" like in the minecraft-image, where you can define -e UID=$uid and -e GID=$gid
that makes it a bit more complecated to be honest o.o

**Comment by itzg** [comment]
It was a little hacky how I did that in the minecraft image, but in the spirit of consistency I'll fix that up to use the -e's.

**Comment by Reviville** [comment]
Appreciate that :)

**Comment by itzg** [comment]
Pushed an image update with `-e UID=$uid -e GID=$gid` usage. Can you double check that for me?

**Comment by Reviville** [comment]
does not seem to work that well :3
![image](https://cloud.githubusercontent.com/assets/26972387/26641473/040897d4-462b-11e7-94a4-b5c06c3673f9.png)

**Comment by itzg** [comment]
I think I was naughty and didn't test with a `GID` set. I can fix this :)

**Comment by itzg** [comment]
OK, now I fixed it **and** tested it ;)

```
> docker run -d --name bungee -e UID=1001 -e GID=1001 bungee
0c8282325b654e2794ba618c18fdcc6d29bae2013031980e1a55a24ace19f33d
> docker logs bungee
Downloading https://ci.md-5.net/job/BungeeCord/lastStableBuild/artifact/bootstrap/target/BungeeCord.jar
Setting initial memory to 512m and max to 512m
02:41:12 [INFO] Using OpenSSL based native cipher.
02:41:12 [INFO] Using native code compressor
02:41:12 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:e26b937:1236
02:41:13 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
02:41:13 [INFO] Epoll is working, utilising it!
02:41:13 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
```

**Comment by Reviville** [comment]
Yo, works for me too :)

**Comment by Reviville** [comment]
I will get back to you when i tested it with every detail possible... i guess im gonna donate again :p

**Comment by itzg** [comment]
Awesome

**Comment by voruti** [comment]
Close the issue?

**Comment by itzg** [comment]
> Close the issue?

Apparently so since I never heard back 😃
