### ISSUE TITLE
Files become read only causing forge server to crash

### ISSUE THREAD

**Issue by suited-1** [itzg/docker-minecraft-server#1465]
for whatever reason everytime i start the server the create mod crashes, running "sudo chmod -R 777 [server file location]" fixes it, its odd

crash report from the server
[crash-2022-04-10_04.45.06-fml.txt](https://github.com/itzg/docker-minecraft-server/files/8458561/crash-2022-04-10_04.45.06-fml.txt)
:

**Comment by CDFN** [comment]
Please fill out issue template

**Comment by suited-1** [comment]
> Please fill out issue template

oh sorry, where can i find that? i just looked but couldnt find it

**Comment by itzg** [comment]
It was a choice when you created the issue. Since you're already here, provide your container configuration (command line, compose file, or similar) and container logs from startup.
