### ISSUE TITLE
Curseforge Server installation - jar-file not found by install.sh

### ISSUE THREAD

**Issue by huettenwirt** [itzg/docker-minecraft-server#1468]
Hi,

I tried to install a curseforge server based on the Create Live 3 modpack and struggled due to install.sh not finding the jar file, which is strange since everything is residing in the same folder, shell script seems correct etc. I also couldn't find any rights issues (running this as user "root" PID 0, GID 1000, which is already more than I like... 

I then installed a pure forge server which worked flawlessly and copied over the modpack files. While this led to a running server including the modpack, the Type=Curseforge route would be nice to work with. 

Any idea, why the script is unable to process the .jar file for the server installation?

Thank you in advance and best regards!

**Comment by itzg** [comment]
Unfortunately there's some modpack structures that aren't detected and handled properly. I am planning on overhauling modpack support and will add this one to the list of test cases. 

In the meantime, your solution is good. `GENERIC_PACK` can be used in a similar way.

**Comment by huettenwirt** [comment]
Hi Geoff, 
thank you for replying on my issue! Highly appreciated. I'm just a Dad not into Minecraft at all, but trying to run a server for my son. He told me I should send you best wishes and a big Thank You for providing this cool, modular approach setting up a Minecraft server ;-)
Cheers!
