### ISSUE TITLE
No longer uses UID=1000 GID=1000 by default

### ISSUE THREAD

**Issue by Frederick888** [itzg/docker-minecraft-server#1469]
### Describe the problem

In 97fe6b1f14f597d6746d90d191f00acbf8b8ef5c, some `ENV` arguments were moved into different scripts, however it seems default `UID` and `GID` were gone after this change.

As a result, now it starts with `UID=0` and empty `GID`, and also changes ownership of data volume at https://github.com/itzg/docker-minecraft-server/blob/8ef3fe199fe30dc2d70eb4c91399c2bf040d567e/scripts/start#L35-L38

### Container logs

```
minecraft-mc-1  | [init] Changing ownership of /data to 0 ...
minecraft-mc-1  | [init] Running as uid=0 gid=1000 with /data as 'drwxrwxr-x 15 0 1000 4096 Mar 12 13:48 /data'
minecraft-mc-1  | [init] Resolved version given 1.18.2 into 1.18.2 and major version 1.18
minecraft-mc-1  | [init] Resolving type given FABRIC
minecraft-mc-1  | [init] Checking Fabric Launcher version information.
minecraft-mc-1  | [init] Checking Fabric Loader version information.
minecraft-mc-1  | [init] server.properties already created, skipping
minecraft-mc-1  | [init] Updating ops
minecraft-mc-1  | [init] FrederickZh already present in ops.json, skipping
minecraft-mc-1  | [init] Checking for JSON files.
minecraft-mc-1  | [init] Setting initial memory to 2G and max to 8G
minecraft-mc-1  | [init] Starting the Minecraft server...
```

**Comment by itzg** [comment]
I'm sorry for introducing this bug and thanks for reporting this. PR testing is going now and will merge+publish immediately after that.

**Comment by itzg** [comment]
Latest images now include the fix for this.

**Comment by Frederick888** [comment]
No need to apologise and thank you for maintaining this project :)
