### ISSUE TITLE
Failed to store chunk [x,y]

### ISSUE THREAD

**Issue by JRitmeester** [itzg/docker-minecraft-server#1470]
### Describe the problem

After replacing an instance of this container and playing for multiple days, I replaced the container with another one using Forge (VERSION=FORGE). Forge appears to work fine in the overworld, but the Nether got reset. Looking at Container Station in my QNAP NAS, I see the output ```[minecraft/IOWorker]: Failed to store chunk [x,y]``` over and over again. Trying to build anything in the Nether usually (*not always*) gets undone when travelling to the overworld and back. Last time, only a part of my Nether build got removed. This made my initial guess, a permission error, kind of questionable. I realise this may not be the right place to post this, but I am not sure where else to post.

The server shows Forge version 40.0.44, and Minecraft is running 1.18.2.

### Container definition

None, used Container Station

### Container logs

[debug.log](https://github.com/itzg/docker-minecraft-server/files/8465161/debug.log)
[latest.log](https://github.com/itzg/docker-minecraft-server/files/8465164/latest.log)

**Comment by itzg** [comment]
Thanks for following up with your findings. Is it ok to close this issue now?

**Comment by JRitmeester** [comment]
Yes, you can close it. Thanks.
