### ISSUE TITLE
server crash after setting MEMORY="4096m" - mc-server-runner	sub-process failed	{"exitCode": -1}

### ISSUE THREAD

**Issue by fstelzner** [itzg/docker-minecraft-server#1493]
First of all… thank you for this awesome docker image and all your work you put in here! This is really appreciated. Hugs and Kisses from my Kids ;-)

When I add the line marked **bold** the server crashed directly after starting up:

`version: '3.3'

services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: XXXXX
      RWA_ADMIN: "TRUE"
      # is referring to the hostname of 'mc' compose service below
      RWA_RCON_HOST: mc
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: XXXXX
    ports:
      - 4326:4326
      - 4327:4327
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      **MEMORY: "4096m"**
    restart: always
    volumes:
      - /Users/XXXXX/minecraft-server/:/data`

**This is the console output with memory allocation:**

`minecraft-server-mc-1   | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 17 1000 1000 544 Oct 20 07:04 /data'
minecraft-server-web-1  | 2021-10-26T11:38:22.661Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [init] Resolved version given LATEST into 1.17.1
minecraft-server-mc-1   | [init] Resolving type given VANILLA
minecraft-server-mc-1   | [init] server.properties already created, skipping
minecraft-server-mc-1   | [init] Checking for JSON files.
minecraft-server-mc-1   | [init] Setting initial memory to 4096m and max to 4096m
minecraft-server-mc-1   | [init] Starting the Minecraft server...
minecraft-server-web-1  | 2021-10-26T11:38:32.780Z RconServer [mc:25575]: Connection failed
minecraft-server-web-1  | 2021-10-26T11:38:42.595Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [11:38:47] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
minecraft-server-mc-1   | [11:38:48] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
minecraft-server-mc-1   | [11:38:48] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
minecraft-server-mc-1   | [11:38:48] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
minecraft-server-mc-1   | [11:38:48] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
minecraft-server-mc-1   | [11:38:48] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
minecraft-server-mc-1   | [11:38:48] [main/INFO]: Reloading ResourceManager: Default
minecraft-server-mc-1   | [11:38:50] [Worker-Main-2/INFO]: Loaded 7 recipes
minecraft-server-mc-1   | [11:38:51] [Worker-Main-2/INFO]: Loaded 1137 advancements
minecraft-server-web-1  | 2021-10-26T11:38:52.634Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [11:38:56] [Server thread/INFO]: Starting minecraft server version 1.17.1
minecraft-server-mc-1   | [11:38:56] [Server thread/INFO]: Loading properties
minecraft-server-mc-1   | [11:38:56] [Server thread/INFO]: Default game type: SURVIVAL
minecraft-server-mc-1   | [11:38:56] [Server thread/INFO]: Generating keypair
minecraft-server-mc-1   | [11:38:58] [Server thread/INFO]: Starting Minecraft server on *:25565
minecraft-server-mc-1   | [11:38:58] [Server thread/INFO]: Using epoll channel type
minecraft-server-mc-1   | [11:38:59] [Server thread/INFO]: Preparing level "world"
minecraft-server-mc-1   | [11:39:00] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
minecraft-server-mc-1   | [11:39:01] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:01] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:01] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:01] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:02] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-web-1  | 2021-10-26T11:39:02.620Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [11:39:02] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:03] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:03] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:04] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:04] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:05] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:05] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:06] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-web-1  | 2021-10-26T11:39:12.685Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:20] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:20] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:21] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:39:21] [Worker-Main-2/INFO]: Preparing spawn area: 6%
minecraft-server-mc-1   | [11:39:22] [Worker-Main-2/INFO]: Preparing spawn area: 80%
minecraft-server-web-1  | 2021-10-26T11:39:22.685Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [11:39:23] [Server thread/INFO]: Time elapsed: 23560 ms
minecraft-server-mc-1   | [11:39:23] [Server thread/INFO]: Done (24.199s)! For help, type "help"
minecraft-server-mc-1   | [11:39:23] [Server thread/INFO]: Starting remote control listener
minecraft-server-mc-1   | [11:39:23] [Server thread/INFO]: Thread RCON Listener started
minecraft-server-mc-1   | [11:39:23] [Server thread/INFO]: RCON running on 0.0.0.0:25575
minecraft-server-mc-1   | [11:39:33] [RCON Listener itzg/mc-server-runner#1/INFO]: Thread RCON Client /172.22.0.2 started
minecraft-server-mc-1   | 2021-10-26T11:39:39.648Z	WARN	mc-server-runner	sub-process failed	{"exitCode": -1}
minecraft-server-mc-1   | 2021-10-26T11:39:39.768Z	INFO	mc-server-runner	Done`

**This is the console output without memory allocation:**
`minecraft-server-mc-1   | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 17 1000 1000 544 Oct 20 07:04 /data'
minecraft-server-web-1  | {"host":null,"websocketUrlSsl":null,"websocketUrl":null,"port":4326}2021-10-26T11:40:46.411Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [init] Resolved version given LATEST into 1.17.1
minecraft-server-mc-1   | [init] Resolving type given VANILLA
minecraft-server-mc-1   | [init] server.properties already created, skipping
minecraft-server-mc-1   | [init] Checking for JSON files.
minecraft-server-mc-1   | [init] Setting initial memory to 1G and max to 1G
minecraft-server-mc-1   | [init] Starting the Minecraft server...
minecraft-server-web-1  | 2021-10-26T11:40:56.370Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [11:40:58] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
minecraft-server-mc-1   | [11:40:59] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
minecraft-server-mc-1   | [11:40:59] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
minecraft-server-mc-1   | [11:40:59] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
minecraft-server-mc-1   | [11:40:59] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
minecraft-server-mc-1   | [11:40:59] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
minecraft-server-mc-1   | [11:40:59] [main/INFO]: Reloading ResourceManager: Default
minecraft-server-mc-1   | [11:41:01] [Worker-Main-2/INFO]: Loaded 7 recipes
minecraft-server-mc-1   | [11:41:01] [Worker-Main-2/INFO]: Loaded 1137 advancements
minecraft-server-mc-1   | [11:41:05] [Server thread/INFO]: Starting minecraft server version 1.17.1
minecraft-server-mc-1   | [11:41:05] [Server thread/INFO]: Loading properties
minecraft-server-mc-1   | [11:41:05] [Server thread/INFO]: Default game type: SURVIVAL
minecraft-server-mc-1   | [11:41:05] [Server thread/INFO]: Generating keypair
minecraft-server-mc-1   | [11:41:06] [Server thread/INFO]: Starting Minecraft server on *:25565
minecraft-server-web-1  | 2021-10-26T11:41:06.383Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [11:41:06] [Server thread/INFO]: Using epoll channel type
minecraft-server-mc-1   | [11:41:06] [Server thread/INFO]: Preparing level "world"
minecraft-server-mc-1   | [11:41:07] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
minecraft-server-mc-1   | [11:41:08] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-web-1  | 2021-10-26T11:41:16.351Z RconServer [mc:25575]: Connection failed
minecraft-server-mc-1   | [11:41:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:20] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:20] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:21] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:21] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:22] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:22] [Worker-Main-2/INFO]: Preparing spawn area: 0%
minecraft-server-mc-1   | [11:41:23] [Worker-Main-2/INFO]: Preparing spawn area: 52%
minecraft-server-mc-1   | [11:41:24] [Server thread/INFO]: Time elapsed: 17516 ms
minecraft-server-mc-1   | [11:41:24] [Server thread/INFO]: Done (17.879s)! For help, type "help"
minecraft-server-mc-1   | [11:41:24] [Server thread/INFO]: Starting remote control listener
minecraft-server-mc-1   | [11:41:24] [Server thread/INFO]: Thread RCON Listener started
minecraft-server-mc-1   | [11:41:24] [Server thread/INFO]: RCON running on 0.0.0.0:25575
minecraft-server-mc-1   | [11:41:26] [RCON Listener itzg/mc-server-runner#1/INFO]: Thread RCON Client /172.22.0.2 started`

**Comment by itzg** [comment]
@jakobbouchard please open a new issue since OP here was resolved. In your case, also include output with `DEBUG_EXEC` set to "true".
