### ISSUE TITLE
Could you please add MultiPaper support?

### ISSUE THREAD

**Issue by akosvr** [itzg/docker-minecraft-server#1498]
### Enhancement Type

New server type

### Describe the enhancement

Multipaper is a great project, and It has it's potential, allows server owners to scale their server.

**Comment by itzg** [comment]
That certainly looks interesting. I'll queue this up.

**Comment by RemainingToast** [comment]
Very good

**Comment by itzg** [comment]
I didn’t realize multipaper is a whole clustered solution. I don’t think it is prudent to layer that into this image. Instead I would suggest people contribute to https://github.com/akiicat/MultiPaper-Container such as dynamic version selection.

**Comment by shotah** [comment]
Will just leave these here:
https://github.com/MultiPaper/MultiPaper
https://multipaper.io/

**Comment by ChipWolf** [comment]
Multipaper works on both this and the bungeecord image with no additional changes other than setting BUNGEE_JAR_URL and PAPER_DOWNLOAD_URL respectively @itzg
