### ISSUE TITLE
Forge is being installed every time the container starts.... I think

### ISSUE THREAD

**Issue by xchoice** [itzg/docker-minecraft-server#1500]
### Describe the problem

Forge is being installed every time the container starts.... I think

Also pack is "Medieval Minecraft [FORGE] - 1.18.2"
https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-new/files

(Which does not seem to work with CURSEFORGE type, complains about me not using the "server" file, also happened with other modpack "Euphoric Hallucinations").

### Container definition

services:
  mc:
    image: itzg/minecraft-server
    container_name: medival
    restart: unless-stopped
    ports:
      - 25566:25566
    volumes:
      - /srv/minecraft/modpacks:/modpacks
      - /srv/minecraft/medival:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      EULA: "TRUE"
      MEMORY: 6G
      VERSION: 1.18.2
      TYPE: FORGE
      JVM_DD_OPTS: -Dfml.readTimeout=360
      OVERRIDE_SERVER_PROPERTIES: "true"
      ONLINE_MODE: "false"

### Container logs

medival | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 3 1000 1000 4096 May  3 01:31 /data'
medival | [init] Resolved version given 1.18.2 into 1.18.2 and major version 1.18
medival | [init] Resolving type given FORGE
medival | [init] Checking Forge version information.
medival | Unknown option: '-s'
medival | Possible solutions: --skip-existing, --skip-up-to-date

**Comment by itzg** [comment]
Oh yeah, that can't be doing good things if that argument is not correct. I'll fix this ASAP.

**Comment by itzg** [comment]
New image is published. Let me know if it's still not behaving correctly.
