### ISSUE TITLE
Bronze block conversion JEI mismatch

### ISSUE THREAD

**Issue by popemichael** [itzg/docker-minecraft-server#1529]
### Describe the problem

When you put the bronze block from FTB Industrial contraptions it turns into ANOTHER bronze block from Create: Alloy and not 9 bronze ingots as JEI indicates. (Direwolf20 pack 1.18 v 1.2.0)

![javaw_nQoJj3IxBg](https://user-images.githubusercontent.com/17892373/169710638-a2886524-f882-44b4-a91b-7d91588b724f.png)

**Comment by itzg** [comment]
How is this an issue with the Docker image?
