### ISSUE TITLE
Fails to start - version lookup failed / 'get' command failed: PKIX path building failed

### ISSUE THREAD

**Issue by dupuik** [itzg/docker-minecraft-server#1532]
### Describe the problem

Started about 3 days ago.  Tried setting dir perms to 777, updated Docker & Docker Compose, tried on different hosts, new install/no data directory, etc.  Container won't start.

### Container definition

networks:
  web:
    external: true

services:
  mc-creative:
    image: itzg/minecraft-server
    container_name: mc-creative
    networks:
      - web
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MODE: "creative"
      ONLINE_MODE: "FALSE"
      ENABLE_AUTOPAUSE: "TRUE"
      MAX_TICK_TIME: "-1"
    restart: unless-stopped
    volumes:
      - ./mc-creative-data:/data

### Container logs

[init] ERROR: version lookup failed:
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 6 1000 1000 4096 May 22 22:42 /data'
[mc-image-helper] 15:56:04.549 ERROR : 'get' command failed: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[init] ERROR: version lookup failed:
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 6 1000 1000 4096 May 22 22:42 /data'
[mc-image-helper] 15:57:06.824 ERROR : 'get' command failed: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[init] ERROR: version lookup failed:

**Comment by dupuik** [comment]
Image up-to-date and spinning up a new container from scratch, vanilla Docker Compose file, local disk - same error -

root@kilohertz:/docker/mc# date
Tue 24 May 2022 05:52:42 PM EDT

root@kilohertz:/docker/mc# docker ps -a|grep mc

root@kilohertz:/docker/mc# ls -al
total 12
drwxr-xr-x 2 dupuik dupuik 4096 May 24 17:52 .
drwxr-xr-x 8 root   root   4096 May 24 17:49 ..
-rw-r--r-- 1 dupuik dupuik  236 May 24 17:50 docker-compose.yml

root@kilohertz:/docker/mc# docker pull itzg/minecraft-server
Using default tag: latest
latest: Pulling from itzg/minecraft-server
Digest: sha256:9f077ec17d55be8f2e355e79b4b6db8010a150a71dfed7325db8278d775325ba
Status: Image is up to date for itzg/minecraft-server:latest
docker.io/itzg/minecraft-server:latest

root@kilohertz:/docker/mc# docker compose up -d
[+] Running 1/1
 ⠿ Container mc  Started                                                                                                                                                                0.4s

root@kilohertz:/docker/mc# docker logs mc
[init] Changing ownership of /data to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 May 24 21:53 /data'
[mc-image-helper] 21:53:05.486 ERROR : 'get' command failed: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[init] ERROR: version lookup failed:

root@kilohertz:/docker/mc# ls -al
total 16
drwxr-xr-x 3 dupuik dupuik 4096 May 24 17:53 .
drwxr-xr-x 8 root   root   4096 May 24 17:49 ..
drwxrwxr-x 2 dupuik dupuik 4096 May 24 17:53 data
-rw-r--r-- 1 dupuik dupuik  236 May 24 17:50 docker-compose.yml

root@kilohertz:/docker/mc# cat docker-compose.yml
networks:
  web:
    external: true

services:
  mc:
    image: itzg/minecraft-server
    container_name: mc
    networks:
      - web
    ports:
      - 25567:25565
    environment:
      EULA: "TRUE"
    volumes:
      - ./data:/data

root@kilohertz:/docker/mc# df -h .
Filesystem                      Size  Used Avail Use% Mounted on
/dev/mapper/kilohertz--vg-root   97G  3.6G   89G   4% /

**Comment by dupuik** [comment]
Fixed! Gaming sites blocked M-F network-wide by OpenDNS / core firewall/router.

**Comment by sbrinkerhoff** [comment]
Thanks @dupuik for posting this.  I had the same issue with similar dns blocking security software and you saved me time!

**Comment by dupuik** [comment]
Glad I could help! I'm not techie or used to Git but figured I'd close out
the ticket with details when I solved my own issue after a couple hours
troubleshooting!

**Comment by logmehditt** [comment]
I had the same issue, after 2 days of troubleshouting I found out my ufw is enabled
Disabling it fixed my issue
here's how to do it:

`$ sudo ufw disable`
