### ISSUE TITLE
"run.sh" not considered as start script

### ISSUE THREAD

**Issue by huettenwirt** [itzg/docker-minecraft-server#1533]
### Describe the problem

After a curseforge installation using the "Create Live 3.0" modpack, the server could be started invoking the "run.sh" script. Unfortunately only variations of server + start + .sh are considered according to the log output. 

It would be great to add `run.sh` as another search string to look for within your script to start the server under linux.

I hope this short descritpion is sufficient to explain my wish.

Best, 
Huettenwirt

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
++ find /data/FeedTheBeast -name ServerStart.sh -o -name serverstart.sh -o -name ServerStartLinux.sh -o -name LaunchServer.sh -o -name server-start.sh -o -name start-server.sh -o -name startserver.sh -o -name StartServer.sh

```

**Comment by itzg** [comment]
That totally makes sense and in fact tracks with a recent PR for FTBA

https://github.com/itzg/docker-minecraft-server/pull/1521
