### ISSUE TITLE
Container unhealthy and unreachable after Restart

### ISSUE THREAD

**Issue by GunterJauch138** [itzg/docker-minecraft-server#1546]
### Describe the problem

Hello i have a problem my friend and i have a minecraft bungeecord server he set it up on his server and changed the config and every thing so i can acces my server in this bungeecord server. And i can acces it, it works just fine but theres one problem if i restart my server once or twice it gets stuck on starting even tho the log says its finished eventualy it goes on to say unhealthy (even tho i it was healthy before the restart) or just stays on starting and i cant acces the server when its in this stage. And when i try to cennect to my server on the bungeecord server it says Exception Connecting:ReadTimeoutException : null and i cant find anything in the logs or on the internet o this specific problem. Then i delete the data folder where everything is stored in from my minecraft server and let the server run the process of creating everything again world, properties, configs etc. and then it works again (healthy) but i dont want to do this over and over so if some could help thx

### Container definition

![Screenshot 2022-06-04 191157](https://user-images.githubusercontent.com/106881414/172018013-fe289af8-7fa4-445d-b0b5-8b6343a66265.png)
![Screenshot 2022-06-04 191215](https://user-images.githubusercontent.com/106881414/172018015-11069f67-ff49-4a25-bf89-3abdb7796cb1.png)

### Container logs

https://pastebin.com/raw/fWLATbZE

**Comment by itzg** [comment]
I can see anything wrong in those logs. You mention a bungeecord server, which is a proxy, but you're showing the SPIGOT logs and config. I'm confused.

**Comment by GunterJauch138** [comment]
The Problem is on my site the BungeeCord server is runing fine no problems i can connect to every server on it except my cause it is in a starting up mode or unhealthy. Every time i start a new world its fine i put my plugins on it still fine but then i create my server lobby and put command blocks down which are working fine so after i restart the server it is unreachable and in a starting / unhealthy mode.

**Comment by GunterJauch138** [comment]
nevermind i figured it out it was a plugin of mine which does not work if you restart the server which i cannot find again on the Internet. I deleted it. It was call SignPlugin and now i use BungeServerSigns
