### ISSUE TITLE
Rootless Docker Runs as 100999

### ISSUE THREAD

**Issue by nate-krichbaum** [itzg/docker-minecraft-server#1554]
### Describe the problem

I think this is the same issue as described here. https://github.com/serverless/serverless-python-requirements/issues/589

I noticed that rootless docker on Ubuntu still runs with 100999 even with environment variables set correctly.

![image](https://user-images.githubusercontent.com/97190258/172654354-e635df02-9ab2-456f-9696-63513d499feb.png)

### Container definition

version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25560:25565
    environment:
      EULA: "TRUE"
      MOTD: "\u00a76What up! We're cool guys looking for other cool guys who want to hang out.\u00a7c Nothing Sexual."
      MEMORY: "4G"
      TYPE: "VANILLA"
      VERSION: "LATEST"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "****"
      ENABLE_AUTOPAUSE: "false"
      AUTOPAUSE_TIMEOUT_EST: 3600
      AUTOPAUSE_TIMEOUT_KN: 120
      AUTOPAUSE_TIMEOUT_INIT: 600
      AUTOPAUSE_PERIOD: 10
      AUTOPAUSE_KNOCK_INTERFACE: "eno1"
      ENABLE_AUTOSTOP: "false"
      SERVER_NAME: "Party Mansion"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "True"
      OPS: "null"
      UID: 1000
      GID: 1000
    volumes:
      - /home/nate/Docker/minecraft:/data
    tty: true
    stdin_open: true
    restart: unless-stopped

**Comment by itzg** [comment]
Can you provide logs?

**Comment by nate-krichbaum** [comment]
chown _R the minecraft directory back to 1000/1000 ownership then deleted and reran the compose.

`mc_1 | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 6 1000 1000 4096 Jun  8 14:04 /data'

mc_1 | [init] Resolved version given LATEST into 1.19 and major version 1.19

mc_1 | [init] Resolving type given VANILLA

mc_1 | [init] server.properties already created, skipping

mc_1 | [init] Updating ops

mc_1 | [init] null already present in ops.json, skipping

mc_1 | [init] Checking for JSON files.

mc_1 | [init] Setting initial memory to 4G and max to 4G

mc_1 | [init] Starting the Minecraft server...

mc_1 | Starting net.minecraft.server.Main

mc_1 | [00:24:15] [ServerMain/INFO]: Building unoptimized datafixer

mc_1 | [00:24:16] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'

mc_1 | [00:24:16] [ServerMain/WARN]: ResourcePack: ignored non-lowercase namespace: .DS_Store in ./world/datapacks/how-many-bees-e2680.zip

mc_1 | [00:24:16] [ServerMain/WARN]: ResourcePack: ignored non-lowercase namespace: .DS_Store in ./world/datapacks/how-many-bees-e2680.zip

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-10/WARN]: Invalid path in datapack: minecraft:tags/functions/.DS_Store, ignoring

mc_1 | [00:24:19] [Worker-Main-11/WARN]: Invalid path in datapack: hmb:functions/.DS_Store, ignoring

mc_1 | [00:24:22] [ServerMain/INFO]: Loaded 7 recipes

mc_1 | [00:24:22] [ServerMain/WARN]: Found validation problem in {minecraft:entities/villager}.pools[0].entries[0]: Unknown loot table called minecraft:entities/reference/villager/villager_head

mc_1 | [00:24:22] [ServerMain/INFO]: Loaded 2197 advancements

mc_1 | [00:24:22] [ServerMain/WARN]: Failed to parse level-type default, defaulting to minecraft:normal

mc_1 | [00:24:22] [Server thread/INFO]: Starting minecraft server version 1.19

mc_1 | [00:24:22] [Server thread/INFO]: Loading properties

mc_1 | [00:24:22] [Server thread/INFO]: Default game type: SURVIVAL

mc_1 | [00:24:22] [Server thread/INFO]: Generating keypair

mc_1 | [00:24:22] [Server thread/INFO]: Starting Minecraft server on *:25565

mc_1 | [00:24:22] [Server thread/INFO]: Using epoll channel type

mc_1 | [00:24:23] [Server thread/INFO]: Preparing level "world"

mc_1 | [00:24:23] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld

mc_1 | [00:24:24] [Worker-Main-6/INFO]: Preparing spawn area: 0%

mc_1 | [00:24:24] [Worker-Main-6/INFO]: Preparing spawn area: 0%

mc_1 | [00:24:24] [Worker-Main-2/INFO]: Preparing spawn area: 0%

mc_1 | [00:24:24] [Worker-Main-3/INFO]: Preparing spawn area: 0%

mc_1 | [00:24:25] [Worker-Main-1/INFO]: Preparing spawn area: 0%

mc_1 | [00:24:25] [Worker-Main-11/INFO]: Preparing spawn area: 0%

mc_1 | [00:24:32] [Worker-Main-4/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-4/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-8/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-6/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-6/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-6/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-6/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-6/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-6/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-1/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-1/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-1/INFO]: Preparing spawn area: 17%

mc_1 | [00:24:32] [Worker-Main-8/INFO]: Preparing spawn area: 26%

mc_1 | [00:24:32] [Worker-Main-3/INFO]: Preparing spawn area: 69%

mc_1 | [00:24:33] [Server thread/INFO]: Time elapsed: 9915 ms

mc_1 | [00:24:33] [Server thread/INFO]: Done (10.113s)! For help, type "help"

mc_1 | [00:24:33] [Server thread/INFO]: Starting remote control listener

mc_1 | [00:24:33] [Server thread/INFO]: Thread RCON Listener started

mc_1 | [00:24:33] [Server thread/INFO]: RCON running on 0.0.0.0:25575`

![image](https://user-images.githubusercontent.com/97190258/172739045-57884a87-09da-4ba3-9cf9-6d8c4a4f948d.png)
still ends up owned by 100999

**Comment by itzg** [comment]
I don't think I can fix that via the image. As you can see from this output, it is running as and reports the ownership of the data directory as user 1000

```
mc_1 | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 6 1000 1000 4096 Jun 8 14:04 /data
```

That output comes from

https://github.com/itzg/docker-minecraft-server/blob/9458005b5bd78b8139e13e66c29a449a12dd6218/scripts/start-configuration#L30

**Comment by itzg** [comment]
For those wandering onto this issue, refer to

https://github.com/itzg/docker-minecraft-server/issues/1934#issuecomment-1407581582

**Comment by valientinx** [comment]
> For those wandering onto this issue, refer to
> 
> [#1934 (comment)](https://github.com/itzg/docker-minecraft-server/issues/1934#issuecomment-1407581582)

Thanks @itzg, I din't see your comment in time so i didn't try the suggested solution, but what worked for me was to use an older docker version, 20.10.12  not 23.0.1
