### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by RealAstolfo** [itzg/docker-minecraft-server#1572]
### Describe the problem

I recently woke up to the minecraft server container taking 80GB of my 128GB server box. plz fix.

### Container definition

version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      MOTD: "Trap Paradise MC Server"
      MEMORY: "16G"
      EULA: "TRUE"
      TYPE: FABRIC
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /megapool/vanilla-minecraft/data:/data

### Container logs

No log outside ordinary.

**Comment by CDFN** [comment]
I highly doubt that's caused by image itself. I would advice attaching profiler and see what's taking up so much space. It's very unlikely that the Minecraft container used up 80GBs considering you've set 16GB limit.

**Comment by itzg** [comment]
Agreed, this is completely beyond my control via the image's software. Ultimately it's just running the Java process, so you need to report this to the Fabric team.

**Comment by RealAstolfo** [comment]
this is something that occurred with the vanilla server as well though

**Comment by RealAstolfo** [comment]
perhaps it is docker itself? but then how would it work?

**Comment by itzg** [comment]
It will have nothing to do with Docker. Ultimately a container is just a Linux process. Do a `ps -ef` and you'll see the process. You'll also see the command line passed to Java. If the command line is not what was expected, then that's something I can fix.

If you hadn't noticed 1.19 just came out. The most logical explanation is that 1.19 has introduced an issue, so I'm not sure why you're trying to blame elsewhere.

**Comment by RealAstolfo** [comment]
i got down to the source of the issue and my confusion. i had been producing multiple services like NAS, which was supported by a ZFS raid filesystem. i store the server itself (which includes the volume the docker container used) on the pool. and it was the only service of all those i host that hits the filesystem so often. ZFS compensates for this by creating a cache in RAM so that common changes can simply overwrite in RAM rather than continuously hit the disks. which also explained why killing the minecraft server caused the memory to be freed. since ZFS detected that it was no longer needed and decided to dump the ending data into the disks. Apologies for the opened issue.
