### ISSUE TITLE
VanillaTweaks share code install causes duplicate data packs?

### ISSUE THREAD

**Issue by bagobones** [itzg/docker-minecraft-server#1578]
### Describe the problem

Built a new server this time with the share code method to load vanillaTweaks datapacks I ended up with more mob heads v2.10.0.zip and more mob heads v2.10.1.zip installed on the server.

I am not sure exactly when this happened as I restarted the docker when doing first setup but I did not manually add any datapacks so I suspect that one was updated.

Should the share method not clean up and replace the datapacks with the latest version?

Not sure if I can replicate as I suspect this was specific to the datapack being updated on vanillatweaks

### Container definition

```
Using portainer this is the env variable section


        "Env": [
            "ENABLE_RCON=true",
            "ENABLE_ROLLING_LOGS=true",
            "ENABLE_WHITELIST=true",
            "EULA=true",
            "GID=1000",
            "MEMORY=4G",
            "RCON_PASSWORD=###############",
            "RCON_PORT=25575",
            "SEED=#################",
            "TYPE=VANILLA",
            "TZ=##################",
            "UID=1000",
            "VERSION=1.19",
            "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=en_US.UTF-8",
            "LANGUAGE=en_US:en",
            "LC_ALL=en_US.UTF-8",
            "JAVA_VERSION=jdk-17.0.3+7",
            "JAVA_HOME=/opt/java/openjdk",
            "VANILLATWEAKS_SHARECODE=BHQg3R",
            "LEVEL=################"
        ]

```

### Container logs

```
Paste logs here
```

**Comment by bagobones** [comment]
```
[init] Resolved version given 1.19 into 1.19 and major version 1.19
[init] Resolving type given VANILLA
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   611    0    76  100   535    571   4022 --:--:-- --:--:-- --:--:--  4593
Archive:  /tmp/vanillatweaks.zip
  inflating: /data/#######/datapacks/nether portal coords v1.1.3.zip  
  inflating: /data/#######/datapacks/durability ping v1.1.3.zip  
  inflating: /data/#######/datapacks/afk display v1.1.3.zip  
  inflating: /data/#######/datapacks/silence mobs v1.1.3.zip  
  inflating: /data/#######/datapacks/more mob heads v2.10.1.zip  
  inflating: /data/#######/datapacks/dragon drops v1.3.3.zip  
  inflating: /data/#######/datapacks/double shulker shells v1.3.3.zip  
  inflating: /data/#######/datapacks/anti enderman grief v1.1.3.zip  
  inflating: /data/#######/datapacks/anti creeper grief v1.1.3.zip  
  inflating: /data/#######/datapacks/player head drops v1.1.3.zip  
  inflating: /data/#######/datapacks/timber v2.1.5.zip  
  inflating: /data/#######/datapacks/back v1.3.3.zip  
  inflating: /data/#######/datapacks/tpa v2.3.3.zip  
  inflating: /data/#######/datapacks/homes v1.5.4.zip  
  inflating: /data/#######/datapacks/spawn v2.3.3.zip  
[init] server.properties already created, skipping
[init] log4j2.xml already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 4G and max to 4G
[init] Starting the Minecraft server...
Starting net.minecraft.server.Main
[14:02:07] [ServerMain/INFO]: Building unoptimized datafixer
[14:02:08] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:02:08] [ServerMain/WARN]: Missing data pack file/afk display v1.1.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/anti creeper grief v1.1.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/anti enderman grief v1.1.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/back v1.3.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/double shulker shells v1.3.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/dragon drops v1.3.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/durability ping v1.1.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/homes v1.5.4.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/nether portal coords v1.1.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/player head drops v1.1.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/silence mobs v1.1.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/spawn v2.3.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/timber v2.1.5.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/tpa v2.3.3.zip
[14:02:08] [ServerMain/WARN]: Missing data pack file/more mob heads v2.10.1.zip
[14:02:10] [ServerMain/INFO]: Loaded 7 recipes
[14:02:10] [ServerMain/INFO]: Loaded 1179 advancements
[14:02:12] [ServerMain/WARN]: Failed to parse level-type default, defaulting to minecraft:normal
[14:02:12] [Server thread/INFO]: Starting minecraft server version 1.19

```

Adding that variable caused ALL datapacks to be removed and for the world to start without them.

Are you sure the share code install happens in the correct order?

**Comment by itzg** [comment]
@shotah can you help look into this?

**Comment by bagobones** [comment]
Also logic and documentation wise I re-read the documentation and it the vanillatweaks remove functions don't say much other than " they work like other mod environment variables" which sort of makes sense if you then go read that whole section which I did after you pointed out the remove variable.

The thing that confuses me is why you would ever want to use the share code to manage the datapacks ETC and NOT have it delete the old ones as having more than one of the same datapack seems to cause problems and that will happen a lot if you JUST have the share code enabled, you will accumulate more and more of the same datapacks as they update.

**Comment by itzg** [comment]
I was reviewing the original problem and am wondering if you could clarify the sequence of events? Did you start with one share code, change it to another and then saw the extra files? Or was it the same share code the whole time but the content backed by the share code upgraded?

**Comment by bagobones** [comment]
It has been a few weeks I didn't notice the duplicate datapack right away.. As far as I recall I added the one share code and did not change it but did pull / rebuild the docker with different settings more than once while tweaking other ENV variables during initial setup over the first few days I had the server up with 1.19.

My personal expectation would be that if you use vanillatweeks share codes the datapacks in that share code would just be kept current between rebuilds and you could add other NONE vanilla tweeks datadpacks that would not be touched in the directory. Not sure exactly how REMOVE_OLD_VANILLATWEAK is supposed to know which datapacks are vanillatweaks ether since the naming of the zip files doesn't contain anything distinct, I wonder if it wouldn't be better to prefix the extracted files with the share code after download or something?

At any rate keeping an eye on it.. I could maybe spin up another server for more testing but as it stands REMOVE_OLD_VANILLATWEAK seemed to remove the datapacks AFTER they had downloaded from the share code thus when the server came up there where no datapacks. I have no way to force a test of the upstream vanilla tweaks site updating a datapack so I will just have to wait and see. currently I do NOT have REMOVE_OLD_VANILLATWEAK enabled since it wiped everything out.

**Comment by itzg** [comment]
I agree with you that a given run of vanilla tweaks download should always clean up previous files no longer needed and at the same time touch nothing else in the datapacks and resourcepacks directories -- in other words, `REMOVE_OLD_VANILLATWEAK` will no longer be needed. A major part of my refactoring will be to have it create and use a manifest file to track files to manage.

Since a sharecode resolves to a data structure that references the packs by name only, such as "unlock all recipes", then it seems quite normal for the version of that pack to progress over time.

Stay tuned...I have most of the new code written and was asking questions to confirm your expectations matched mine.

**Comment by bagobones** [comment]
Sounds good.  This docker has made managing a minecraft server for my friends and family so much easier. Since we mostly stick to vanilla servers and vanilla tweaks this is the icing on the cake for low maintenance.

**Comment by itzg** [comment]
@bagobones the latest image now includes auto-cleanup of the VanillaTweaks installed files. You might need to do some manual cleanup the first startup, but after that it'll track the files it installs.
