### ISSUE TITLE
java11 does not changing ownership of /data to 1000

### ISSUE THREAD

**Issue by thenilsdev** [itzg/docker-minecraft-server#1583]
### Describe the problem

When I mount individual plugin folders to persist across restarts, `java11` does not modify permissions. For me it would not be a solution to make the entire server persistent

---

Works with tag `java8`:
```
[init] Changing ownership of /data to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Jul  3 02:34 /data'
[init] Resolved version given 1.12.2 into 1.12.2 and major version 1.12
[init] Resolving type given PAPER
[init] Removing old PaperMC versions ...
[init] Downloading PaperMC 1.12.2 (build 1620) ...
[init] Copying plugins over...
[init] Copying any configs from /config to /data
[init] server.properties already created, skipping
[init] Replacing env variables in /data that match the prefix CFG_ ...
[init] Checking for JSON files.
[init] Using Aikar's flags
[init] Setting initial memory to 8G and max to 8G
[init] Starting the Minecraft server...
```

Does not work with tag `java11`:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Jul  3 02:56 /data'
[init] Resolved version given 1.16.5 into 1.16.5 and major version 1.16
[init] Resolving type given PAPER
[init] Removing old PaperMC versions ...
[init] Downloading PaperMC 1.16.5 (build 794) ...
[init] Copying plugins over...
[mc-image-helper] 02:56:18.937 INFO  : Copying /plugins/IWBrandingBukkit.jar -> /data/plugins/IWBrandingBukkit.jar
[mc-image-helper] 02:56:18.946 ERROR : Failed to sync and interpolate /plugins into /data/plugins : /data/plugins/IWBrandingBukkit.jar
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Jul  3 02:56 /data'
[init] Resolved version given 1.16.5 into 1.16.5 and major version 1.16
[init] Resolving type given PAPER
[init] Removing old PaperMC versions ...
[init] Downloading PaperMC 1.16.5 (build 794) ...
[init] Copying plugins over...
[mc-image-helper] 02:56:21.346 INFO  : Copying /plugins/IWBrandingBukkit.jar -> /data/plugins/IWBrandingBukkit.jar
[mc-image-helper] 02:56:21.348 ERROR : Failed to sync and interpolate /plugins into /data/plugins : /data/plugins/IWBrandingBukkit.jar
```

---

Following fixes the issue until next deployment:
```
sudo chown -R 1000:1000 /var/lib/docker/volumes/<volume_id>/_data
```

**Comment by itzg** [comment]
Please provide container configs

**Comment by thenilsdev** [comment]
I have summarized the whole thing in a minimal configuration so that you can test it yourself. It seems to work only with alpine

https://github.com/thenilsdev/docker-minecraft-server-issues-1583

| Tag name      | Working |
|---------------|---------|
| java8         | ✔️       |
| java11        | ❌       |
| java11-openj  | ❌       |
| java17        | ❌       |
| java17-alpine | ✔️       |
| java17-openj  | ❌       |

**Comment by itzg** [comment]
Why are you doing this in the Dockerfile rather than just mounting the host directory?

```
COPY /plugins /plugins
```

**Comment by itzg** [comment]
...and volume mounting to a subdirectory. You should be mounting at `/data` otherwise you are certainly inviting complexities with mismatched file ownership. The startup script **only** checks `/data` and not any subdirectories for the ownership of user 1000.

```
    volumes:
      - mc-paper-viaversion:/data/plugins/ViaVersion
```

**Comment by itzg** [comment]
With adjustments to bring the config back to normal, it works fine for me:

https://github.com/thenilsdev/docker-minecraft-server-issues-1583/compare/main...itzg:docker-minecraft-server-issues-1583:works?expand=1

I also included a listing of the files and all have user ID 1000 (minecraft) ownership:
https://github.com/thenilsdev/docker-minecraft-server-issues-1583/compare/main...itzg:docker-minecraft-server-issues-1583:works?expand=1#diff-8fd005186778f5427297d77faccf090d70091cda01a469b6a1a9a994bce5c985

**Comment by thenilsdev** [comment]
> Why are you doing this in the Dockerfile rather than just mounting the host directory?
> 
> 
> 
> ```
> 
> COPY /plugins /plugins
> 
> ```

I tried to make my production setup reproducible, since I copy the plugins into Docker Imagine as well


> ...and why are you volume mounting to a subdirectory? You should be mounting at `/data` otherwise you are certainly inviting complexities with mismatched file ownership. The startup script **only** checks `/data` and not any subdirectories for the ownership of user 1000.
> 
> 
> 
> ```
> 
>     volumes:
> 
>       - mc-paper-viaversion:/data/plugins/ViaVersion
> 
> ```

This way I want to make sure that no data persists that I don't directly mount. I can imagine that this is not the best solution but with alpine it actually works exactly as I would like it to. 

I could create a file with wrong owner rights in /data so that the permission are set, but that doesn't sound like a good solution

**Comment by itzg** [comment]
Your requirements are very unusual since you're trying to mount a volume inside a volume and apparently Alpine accidentally handles it. Sounds like you're stuck with the alpine image variants. 

Also please either shift to Java 8 (for pre MC 1.18) or 17. I will be deprecating Java 11 support soon.
