### ISSUE TITLE
CURSEFORGE fabric modpack does not launch with `USE_MODPACK_START_SCRIPT=FALSE`

### ISSUE THREAD

**Issue by rednetllc** [itzg/docker-minecraft-server#1586]
### Describe the problem

I am attempting to launch a CURSEFORGE type container that is utilizing a fabric-based modpack. The modpack does not include a start script so I used the `USE_MODPACK_START_SCRIPT=FALSE` variable and every time it runs it barfs saying that it cannot find a forge installer. Obviously it will never find one since this is a fabric pack. If I run the pack as a pure FABRIC pack things get funky for other reasons that are not related to this bug report.

The one way to fix the issue was to go and, after failing (1) time with the CURSEFORGE attempt described here, change the `TYPE` value to `FABRIC` and change `CF_SERVER_MOD` to `MODPACK`. With these changes, the server boots up fine and everything is applied and working correctly as expected. If I started a new pack using `Type` = `FABRIC` and pointing to the `MODPACK` zip, the container fails with other error messages unrelated to this bug report.

If it's relevant, I'm running docker on unRaid 6.10.3 using the latest version available.
 
Modpack can be found here: https://www.curseforge.com/minecraft/modpacks/euphoriccuriosity
Modpack direct download here: https://mediafiles.forgecdn.net/files/3847/564/Euphoric+Curiosity+3+Server.zip

### Container definition

```
root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Euphoric_Curiosity' --net='bridge' -e TZ="America/New_York" -e HOST_OS="Unraid" -e HOST_HOSTNAME="unraid-prime" -e HOST_CONTAINERNAME="Euphoric_Curiosity" -e 'TYPE'='CURSEFORGE' -e 'MOTD'='Euphoric Origins by The Modders' -e 'SEED'='206205394' -e 'MODE'='survival' -e 'MEMORY'='6G' -e 'VERSION'='1.18.2' -e 'LEVEL'='Gay_Beach' -e 'ICON'='/modpacks/icon.png' -e 'DIFFICULTY'='normal' -e 'WHITELIST_FILE'='/modpacks/whitelist.json' -e 'USE_AIKAR_FLAGS'='TRUE' -e 'FORCE_GAMEMODE'='TRUE' -e 'ENFORCE_WHITELIST'='TRUE' -e 'ALLOW_FLIGHT'='TRUE' -e 'STOP_SERVER_ANNOUNCE_DELAY'='3000' -e 'SPAWN_PROTECTION'='0' -e 'EULA'='TRUE' -e 'OPS_FILE'='/modpacks/ops.json' -e 'OVERRIDE_ICON'='TRUE' -e 'OVERRIDE_WHITELIST'='TRUE' -e 'CF_BASE_DIR'='/data' -e 'USE_MODPACK_START_SCRIPT'='FALSE' -e 'CF_SERVER_MOD'='/modpacks/Euphoric+Curiosity+3+Server.zip' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.icon='https://maxcdn.icons8.com/Color/PNG/512/Gaming/minecraft_logo-512.png' -p '25565:25565/tcp' -v '/mnt/user/appdata/Euphoric_Curiosity_Minecraft':'/data':'rw' -v '/mnt/user/appdata/modpacks':'/modpacks':'rw' 'itzg/minecraft-server:java17-alpine'
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1--- 1--- 292 Jul  5 19:29 /data'
[init] Resolved version given 1.18.2 into 1.18.2 and major version 1.18
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] Unpacking FTB server modpack /modpacks/Euphoric+Curiosity+3+Server.zip ...
..............................................................................................................
..............................................................................................................
..............................................................................................................
..............................................................................................................
..............................................................................................................
..................................................................................................
[init] ERROR Unable to find forge installer in modpack
[init]             or download using modpack config.
[init]             Make sure you downloaded the server files.
```

**Comment by itzg** [comment]
You're correct that it'll never locate the forge server jar being a Fabric modpack. Your solution is similar to what I would have suggested, but using `GENERIC_PACK`.

**Comment by yairp03** [comment]
Had this problem with [All of Fabric 5](https://www.curseforge.com/minecraft/modpacks/all-of-fabric-5). Can I get an explanation on how exactly to solve it?

**Comment by itzg** [comment]
It will be like this example where GENERIC_PACK is used instead along with TYPE and VERSION.

https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-generic-pack-atm7.yml
