### ISSUE TITLE
Magma version  1.16.5-89287b58 -  Failed to find file: data/server.lzma, is the server corrupt?

### ISSUE THREAD

**Issue by shenniko** [itzg/docker-minecraft-server#1600]
### Describe the problem

on launch get following error

Failed to find file: data/server.lzma, is the server corrupt?
Patching server...   0% [>                                 ] 0/6 (0:00:00 / ?) 

2022-07-15T00:29:38.398Z	WARN	mc-server-runner	Minecraft server process failed	{"exitCode": 255}

### Container definition

  mc:
    image: itzg/minecraft-server:java8
    container_name: Minecraft_Forge_Vault
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "MAGMA"
      VERSION: "1.16.5"
      MEMORY: "10G"
      DEBUG_MEMORY: "true"
      DEBUG_EXEC: "true"
    volumes:
      - ./minecraft-data:/data

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 5 1000 1000 4096 Jul 15 00:12 /data'

[init] Resolved version given 1.16.5 into 1.16.5 and major version 1.16

[init] Resolving type given MAGMA

[init] server.properties already created, skipping

[init] Checking for JSON files.

[init] Memory usage and availability (in MB)

Linux f9d3747dddbb 5.13.0-40-generic #45-Ubuntu SMP Tue Mar 29 14:48:14 UTC 2022 x86_64 GNU/Linux

              total        used        free      shared  buff/cache   available

Mem:          31968         571       25377           1        6019       30944

Swap:         16366           2       16364

[init] Setting initial memory to 10G and max to 10G

[init] Starting the Minecraft server...

+ isTrue false

+ local oldState

++ shopt -po xtrace

+ oldState='set -o xtrace'

+ shopt -u -o xtrace

+ return 1

+ exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -Xmx10G -Xms10G -Dlog4j2.formatMsgNoLookups=true -jar forge-1.16.5-36.2.35-89287b58.jar

    __  ___                           

   /  |/  /___ _____ _____ ___  ____ _

  / /|_/ / __ `/ __ `/ __ `__ \/ __ `/

 / /  / / /_/ / /_/ / / / / / / /_/ / 

/_/  /_/\__,_/\__, /_/ /_/ /_/\__,_/  

             /____/                   

Copyright (c) 2022 MagmaFoundation.

--------------------------------------

Running on Java 1.8.0_212 (IcedTea)

Magma version  1.16.5-89287b58

Bukkit version v1_16_R3

Forge version  1.16.5-36.2.35

--------------------------------------

Checking libraries, please wait...

Libraries JSON version: 1.0

Downloading libraries   0% [>                              ] 0/3 (0:00:00 / ?) 
Downloading libraries  33% [========>                ] 1/3 (0:00:01 / 0:00:02) 
Downloading libraries  66% [================>        ] 2/3 (0:00:01 / 0:00:00) 
Downloading libraries 100% [=========================] 3/3 (0:00:01 / 0:00:00) 
Downloading libraries 100% [=========================] 3/3 (0:00:01 / 0:00:00) 

The libraries are up to date

Failed to find file: data/server.lzma, is the server corrupt?
Patching server...   0% [>                                 ] 0/6 (0:00:00 / ?) 

2022-07-15T00:29:38.398Z	WARN	mc-server-runner	Minecraft server process failed	{"exitCode": 255}

2022-07-15T00:29:38.398Z	INFO	mc-server-runner	Done

**Comment by itzg** [comment]
That is happening after the image executes the server software. You will need to report this issue with Magma.

**Comment by m1lc0lm** [comment]
It seems the script uses the original forge jar. To start the server, you need to run Magma-1.16.5-36.2.35-89287b58-server.jar
