### ISSUE TITLE
Autostop don't work on modpack ATM6

### ISSUE THREAD

**Issue by DewDrop-99** [itzg/docker-minecraft-server#1616]
### Describe the problem

After the server starts the listener for autoserver stop don't appear in console. In other 4 modpack that I have the autostop works perfectly. 

The modpack is All the mods 6

**Comment by itzg** [comment]
Can you provide your container config?

**Comment by DewDrop-99** [comment]
I use it on Unraid so the container config are the following:

![image](https://user-images.githubusercontent.com/49823183/180312246-edd67d00-9f4c-4657-abd8-a0ad0496d0e1.png)

**Comment by DewDrop-99** [comment]
1 week later the issue still persists. 
Maybe it's some mod creating the conflict since I don't have this problem with other modpacks. There is some debugging variable that I can enable to see if I can find the error?

**Comment by itzg** [comment]
If you could pull the latest image there is now `DEBUG_AUTOSTOP` that can be set to `true`. That will output more logs to reveal more of what it is trying. Also note that the default for `AUTOSTOP_TIMEOUT_INIT` is 30 minutes...had to lower that to 30 seconds for my testing.

**Comment by DewDrop-99** [comment]
The debug log is the following:

`+ :
+ isTrue true
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ return 0
+ log 'DEBUG: autostop state = INIT'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ case X$STATE in
+ mc_server_listening
+ mc-monitor status --host localhost --port 25565 --timeout 10s
[init] DEBUG: autostop state = INIT
+ sleep 10`

**Comment by itzg** [comment]
Really need to see all the container logs, but at least the ones through the line that says "Starting Minecraft server on".

**Comment by DewDrop-99** [comment]
Here they are with two server boot's.
The last player left the game at [04:19:42]

The second boot started at [08:38:39]

[Contailerlog.log](https://github.com/itzg/docker-minecraft-server/files/9232068/Contailerlog.log)

**Comment by itzg** [comment]
Thanks. Still a mystery unfortunately since I see the correct message from the server binding on all interfaces:

```
[23:36:32] [Server thread/INFO] [minecraft/DedicatedServer]: Starting Minecraft server on *:25565 
```

and the server ping is going to the same port:

```
+ mc-monitor status --host localhost --port 25565 --timeout 10s                                     "time":{"2022-07-30T22:36:33.208538047Z"}
```

...but it's like the server itself is not responding to the status pings.
