### ISSUE TITLE
Update location of Loli catserver retrieval

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1622]
Looks like this server isn't a thing anymore. The GitHub page, as well as the JAR download seem to be gone.
See <https://github.com/Loli-Server/LoliServer>

__Originally posted by @Scrumplex in https://github.com/itzg/docker-minecraft-server/pull/1483#issuecomment-1192558011__

**Comment by itzg** [comment]
It moved

https://github.com/itzg/docker-minecraft-server/pull/1483#issuecomment-1192905724

**Comment by khankul** [comment]
I believe this issue can be closed now.
