### ISSUE TITLE
New minecraft spigot container with 1.11.2 data will start as a 1.11.2 container, even with new version specified 

### ISSUE THREAD

**Issue by kitzu** [itzg/docker-minecraft-server#163]
When I set up a new container with an empty data directory with `-e TYPE=SPIGOT -e VERSION=1.12 -e BUILD_FROM_SOURCE=true`, it correctly builds a 1.12 spigot server and generates a new map. When I set up a new container and use my old data directory used with spigot 1.11.2 with the same parameters set, it will always start as a spigot 1.11.2 server. Is that intended behavior? If so, how can I update my server to the new version?

**Comment by itzg** [comment]
I double checked the script and it seems to be acting as designed, which is that it'll look for

/data/craftbukkit_server.jar

or

/data/spigot_server.jar

and skip the download/build if that's already there. If you're wanting to "upgrade" or "recycle" a data directory from a prior version, move the existing jar out of the way or remove it. With that, it should either build/download the new version. Alternatively you could transplant the built jar from the newer container into the data directory of the older directory.

Let me know if that doesn't work for you.
