### ISSUE TITLE
Manifest.json Support

### ISSUE THREAD

**Issue by Lite5h4dow** [itzg/docker-minecraft-server#1639]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Exported Client modpacks use Manifest.json to communicate the modfiles that are used as well as forge version and minecraft version
documentation here: https://nodecraft.com/support/games/minecraft/preparing-minecraft-modpacks-manifest-files#h-downloading-server-files-d06c460319

it is reccomended that you use a mod scrubber when doing this manually to avoid client mods that crash servers such as this one: https://github.com/BloodyMods/ServerStarter
however given this also starts the server, might want to ignore it and just state that client side mods may crash the server.

**Comment by itzg** [comment]
Note: https://github.com/itzg/mc-image-helper/pull/195 provides the mc-image-helper option that can be used for this

**Comment by itzg** [comment]
Supported by https://github.com/itzg/docker-minecraft-server#auto-curseforge-management with the variable `CF_MODPACK_MANIFEST`
