### ISSUE TITLE
GraalVM 8 dumping command not found in logs

### ISSUE THREAD

**Issue by nickkeane** [itzg/docker-minecraft-server#1640]
### Describe the problem

When using GraalVM for Java 8 and firing up the server, the docker logs become flooded with this message:

/autopause/autopause-fcns.sh: line 12: ps: command not found

### Container definition

version: "3.9"
services:
  db:
    image: mariadb:10.8-jammy
    container_name: minecraft-bettermcplus-db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: 'REDACTED'
      MYSQL_USER: 'REDACTED'
      MYSQL_PASSWORD: 'REDACTED'
    ports:
      - "8323:3306"
    volumes:
      - ./db/data/10/data:/var/lib/mysql
      - ./db/config:/etc/mysql:ro
      - ./db/scripts/init:/docker-entrypoint-initdb.d:ro
    networks:
      - default
    labels:
      traefik.enable: 'false'

  docs:
    build:
      context: ./docs
    image: minecraft-docs:BetterMCPlus_39.5_1.16.5
    container_name: minecraft-bettermcplus-docs
    restart: always
    ports:
      - "8223:80"
    volumes:
      - ./docs/logs:/opt/logs
    networks:
      - default
      - traefik-proxy
    labels:
      traefik.enable: 'true'
      traefik.http.routers.mca-https.entrypoints: websecure
      traefik.http.routers.mca-https.rule: 'Host(`REDACTED`)'
      traefik.http.routers.mca-https.tls.certresolver: 'letsencrypt'
      traefik.http.routers.mca-https.tls.options: 'modern2020@file'
      traefik.http.routers.mca-https-inet.entrypoints: 'websecure'
      traefik.http.routers.mca-https-inet.rule: 'Host(`REDACTED`)'
      traefik.http.routers.mca-web-https-inet.tls.certresolver: 'internalca'
      traefik.http.routers.mca-web-https-inet.tls.options: 'modern2020@file'
      traefik.http.services.mca.loadbalancer.server.port: 80

  backups:
    image: itzg/mc-backup:latest
    container_name: minecraft-bettermcplus-backups
    restart: always
    environment:
      BACKUP_NAME: 'world'
      INITIAL_DELAY: '30m'
      BACKUP_INTERVAL: '24h'
      PRUNE_BACKUP_DAYS: '30'
      RCON_HOST: 'app'
      RCON_PORT: 25575
      TAR_COMPRESS_METHOD: 'zstd'
    volumes:
      - ./app/data:/data:ro
      - ./backups:/backups
    networks:
      - default
    labels:
      traefik.enable: 'false'

  app:
    image: itzg/minecraft-server:java8-graalvm-ce
    container_name: minecraft-bettermcplus
    restart: always
    stdin_open: true
    tty: true
    depends_on:
      - db
      - docs
      - backups
    environment:
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "1.16.5"
      FORGEVERSION: "36.2.39"
      MEMORY: "4G"
      USE_AIKAR_FLAGS: "true"
      ENABLE_ROLLING_LOGS: "true"
      SYNC_SKIP_NEWER_IN_DESTINATION: "false"
      MODE: "survival"
      FORCE_GAMEMODE: "true"
      PVP: "false"
      RCON_CMDS_STARTUP: |-
        gamerule mobGriefing false
        gamerule spawnRadius 0
      REMOVE_OLD_MODS: "true"
      REMOVE_OLD_MODS_INCLUDE: "*.jar,*.jar.disabled"
      REMOVE_OLD_MODS_DEPTH: 16
      COMPOSE_HTTP_TIMEOUT: 3000
    env_file:
      - ./common.env
    ports:
      - "25565:25565"
      - "25575:25575"
      - "8123:8123"
      - "8423:8423"
      - "8422:8422"
    volumes:
      - ./app/data:/data
      - ./app/mods:/mods
      - ./app/plugins:/plugins
      - ./app/config:/config
    networks:
      - default
    labels:
      traefik.enable: 'false'

networks:
  default:
    driver: bridge
  traefik-proxy:
    external: true

**Comment by itzg** [comment]
@NoaHimesaka1873 , can you help look at this? Is it the `procps` package that's needed?

**Comment by NoaHimesaka1873** [comment]
@itzg Either is fine. `procps` is an alias for `procps-ng` on Oracle Linux.

**Comment by itzg** [comment]
Fixed by #1644
