### ISSUE TITLE
Option to allow use of outdated versions on modrinth

### ISSUE THREAD

**Issue by MattiDragon** [itzg/docker-minecraft-server#1650]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I would like to set up a fabric 1.19.2 (just released) server this image and download mods from modrinth, but most of my mods aren't getting downloaded as they haven't been marked for 1.19.2 support. Most have been marked for 1.19.1 support, but some are only marked for 1.18.2, but still work as the code they touch hasn't changed. 

I would like to have a flag to make the image use a version of the mod for the latest mc version bellow the current one that the project supports. I don't really care if it's opt-in or opt-out as long as it's possible. Also, could you not just silently skip the mods?

I'm, using docker compose btw

**Comment by itzg** [comment]
I think that's beyond my control. I'm using this API call

https://docs.modrinth.com/api-spec/#tag/versions/operation/getProjectVersions

and can only make use of what it responds. This seems like a request to post with Modrinth.

Out of curiosity, what mod is an example that is marked for 1.18.2 but works for 1.19.2?

**Comment by MattiDragon** [comment]
That api allows omitting the minecraft version, allowing you to do the checks yourself. For the 1.18 mod, it's https://modrinth.com/mod/zombify. Apparently it's 1.18.1, but still, it's so basic it probably still works

**Comment by itzg** [comment]
That's an option in the API but how would the code determine if a mod file "probably still works"?

This sounds like a capability Modrinth should provide to mod publishers to designate a given mod file works with multiple Minecraft versions.

**Comment by MattiDragon** [comment]
Mod publishers can set multiple versions, but some forget. My suggestion was to make this image pull the latest (older) version if a matching one isn't found. It would be up to the user to find valid mods. Another option would be the ability to specify version ids to download, but then we wouldn't have auto updates

**Comment by itzg** [comment]
> Another option would be the ability to specify version ids to download, but then we wouldn't have auto updates

This can be done. Software can do deterministic things like this leaving a human to make the fuzzy decision.

**Comment by itzg** [comment]
I need a new stalebot...this is queued up in https://github.com/users/itzg/projects/4/views/1

**Comment by pedrofgodinho** [comment]
Requesting that you consider reopening this issue. 

There are quite a few plugins and mods that support more recent versions than reported. In particular, developers often edit the description page, or leave a comment, saying that the plugin/mod is compatible with the latest version, without updating the files to add that compatibility. 
For instance, there's tons of mods supporting, say, 1.21.1-1.21.8, since 1.21.8 was the last time the author updated the page, even though 1.21.10 would be supported. 

An option to allow out-of-date mods/plugins would be great.

**Comment by itzg** [comment]
@pedrofgodinho specify the version ID such as "Oa9ZDzZq" to bypass the Modrinth API call that needs Minecraft game version. 

https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/modrinth/#usage

Also, contact Modrinth to report this problem with stale metadata.
