### ISSUE TITLE
Research exposing JVM memory/cpu without JMX

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1671]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I seem to remember there was a Java agent could expose JMX metrics via HTTP. There might be mods/plugins that do this; however would be nice to have the option for vanilla.

**Comment by CDFN** [comment]
Making javaagent exposing it would be possible but I'm not sure if running an HTTP server along with Minecraft server would be smart idea.

**Comment by itzg** [comment]
Agreed, I wouldn't want an HTTP server running there. What I meant is that I seem to remember one that ran in-process with a very simple REST API.

**Comment by itzg** [comment]
Found it, this is what I remembered https://jolokia.org/

**Comment by itzg** [comment]
Probably best to use a plugin like https://spark.lucko.me/
