### ISSUE TITLE
Can't launch docker minecraft server

### ISSUE THREAD

**Issue by WhyVent** [itzg/docker-minecraft-server#1681]
### Describe the problem

Can't launch docker minecraft server

### Container logs

[init] Starting the Minecraft server...
Error: Invalid or corrupt jarfile minecraft_server.1.19.2.jar
2022-08-16T13:37:47.462Z	WARN	mc-server-runner	Minecraft server process failed	{"exitCode": 1}
2022-08-16T13:37:47.462Z	INFO	mc-server-runner	Done

**Comment by itzg** [comment]
Try deleting the corrupted file `minecraft_server.1.19.2.jar` and restarting the container to let it redownload.

**Comment by WhyVent** [comment]
Thank you for your answer. I seem to have asked a stupid question.

**Comment by itzg** [comment]
Did that fix it? It wasn't a stupid question at all. 

If it's still happening then please provide the requested info about your container config and full startup logs.

**Comment by sonnleit** [comment]
> Try deleting the corrupted file `minecraft_server.1.19.2.jar` and restarting the container to let it redownload.

Worked for me
