### ISSUE TITLE
Modrinth download doesn't work for no-chat-reports

### ISSUE THREAD

**Issue by dogtopus** [itzg/docker-minecraft-server#1697]
### Describe the problem

After adding `MODRINTH_PROJECTS=no-chat-reports`, the build fails with `Failed to parse version response`. Removing `no-chat-reports` and the build works normally.

### Container definition

```
podman volume create mc-test-data
podman run -e EULA=TRUE -e TYPE=FABRIC -e MODRINTH_PROJECTS=fabric-api,lithium,phosphor,no-chat-reports -v mc-test-data:/data --name mc-test docker.io/itzg/minecraft-server:latest
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x. 9 1000 1000 4096 Aug 28 20:12 /data'

[init] Resolved version given LATEST into 1.19.2 and major version 1.19

[init] Resolving type given FABRIC

[init] Checking Fabric Launcher version information.

[init] Checking Fabric Loader version information.

[mc-image-helper] 20:15:17.512 INFO  : Downloading phosphor-fabric-mc1.19.x-0.8.1.jar

[mc-image-helper] 20:15:17.514 INFO  : Downloading lithium-fabric-mc1.19.2-0.8.3.jar

[mc-image-helper] 20:15:17.593 INFO  : Downloading fabric-api-0.60.0+1.19.2.jar

[mc-image-helper] 20:15:17.657 ERROR : 'modrinth' command failed: Failed to parse version response

Streaming disconnected
```

**Comment by dogtopus** [comment]
Downgrading instance to 1.19.1 made the problem disappear for a while, but it's now back.

Sounds like it might be something on the Modrinth side?

**Comment by itzg** [comment]
Yeah. I haven't had a chance to investigate yet, but there must be something unusual about the metadata for that one specifically. I'll have to see if there's a heuristic to adapt to what they're doing.

**Comment by itzg** [comment]
The latest image is building now. With pulling that feel free to reopen and comment if the issue still isn't fixed. There was a bug on my part missing dependencies marked as "embedded".

**Comment by itzg** [comment]
Build is almost done but looks like I have broken java 8

https://github.com/itzg/docker-minecraft-server/actions/runs/2986036826

**Comment by dogtopus** [comment]
It went further (the file name of the mod is printed), but then it failed with `'modrinth' command failed: HttpClient request failed: 404 Not Found`.

**Comment by itzg** [comment]
Recreated the issue by enabling optional dependencies. That led to finding a typo in one of my request URLs. Fix is on the way.

**Comment by itzg** [comment]
This time it looks like it should be fixed.
