### ISSUE TITLE
move minecraft server to own repository

### ISSUE THREAD

**Issue by TheLeftMoose** [itzg/docker-minecraft-server#170]
I really love your work and would like to contribute. Though it would be easier if minecraft server had it's own repository.

Would that be possible?

Thanks in advance.

**Comment by itzg** [comment]
Thanks. Yeah, that and the elasticsearch directory in the same repo each have a lot of activity/contributions going on independently. I have been wanting to make them repos each, but keep hestitating at considering how to retain contributor designations as such. 

It might be sufficient for me to fork that one repo into a new repo, remove all but the minecraft-server , and shift down a directory. Thoughts or suggestions?

**Comment by theWoodman** [comment]
hmm github help to the rescue... https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

Though that only covers the git migration. Should we consider to migrate the issues as well?

**Comment by theWoodman** [comment]
was just googling further, and there is some different approaches to moving the issues. 

https://github.com/holman/ama/issues/413 refers to this project: https://github.com/google/github-issue-mover. Though I can't seem to find out if you will need to use this tool manually, or if you actually can query the "copy from project", then get a list that is looped across.

**Comment by itzg** [comment]
Good finds @theWoodman ! I'll work on a combo of the two since I had forgotten issues definitely need to migrate.

**Comment by dschaper** [comment]
https://www.zenhub.com/guides/time-saver-features#move-issue-button We use ZenHub for our projects, really easy to move issues to a new repo when a user puts them in the wrong place.

**Comment by TheLeftMoose** [comment]
so, long time no see... and it seems like nothing changed. Would it be possible to have a chat about what the plan could be to move?

I might have some preliminary plan below here:
In terms of keeping the git history with the contributions, it would be the best to fork this repo, move it to a new repo. Then:

1. `git rm` on new repo on all the files and folders that isn't needed anymore

1. `git mv`on new repo on content from /minecraft_server folder to root folder

1. run the github issue mover

1. `git rm` /minecraft server from old repo

**Comment by itzg** [comment]
Yeah, thanks for poking this topic. I really would like to isolate the image into its own repo. Yes, that approach would retain all the contributors which is equally important as retaining the open issues.

**Comment by itzg** [comment]
...so I’ll actively explore this.

**Comment by itzg** [comment]
...oh, I wonder if Docker Hub will let me shift the git reference?

**Comment by itzg** [comment]
Doesn't look promising :( The Docker Hub build settings don't provide an edit option for the associated GitHub repo:

![screenshot from 2018-02-17 18-14-39 png](https://user-images.githubusercontent.com/988985/36346971-4ec76292-1410-11e8-9273-8d0e7d6ad24f.png)

**Comment by itzg** [comment]
Another I might "solve" this is to prune away some of the deprecated images I have in this repo. For example I know use all of the official Elastic images and can deprecated away elasticsearch, logstash, and kibana.

**Comment by TheLeftMoose** [comment]
thanks for look into it, and sorry i didn't notice your comment before... Seems like this convo takes as long as pidgin carrieer...

Anyways, you are not the only one that has this problem, so i have tried to look up on the internet what others are doing. Certainly there is no message direct from Docker Inc; though their github feedback repo is a gold mine... if you dig...
https://github.com/docker/hub-feedback/issues/313#issuecomment-265843090

and:
https://success.docker.com/article/how-do-you-rename-a-docker-hub-repository

Anyways, you can't change provider. Though you can delete a dockerhub repo and create a new automated build with the same name. Though that will make you lose all your metadata, and therefore also the user base as this image is the most pulled. 
So that is a no-go i guess...

Any other top notch docker images being pulled from the same github repo? in that case, move everything other than your minecraft server, and rearrange it as you also discuss in the last post.

**Comment by marxenegls** [comment]
hey @TheLeftMoose could you in the meantime maybe hint a quick and tidy way to pull/fetch the damn minercaft-server directory , i'm almost out nails soon it's gonna be bone i'll be chewing on. got stuck on checkout between --detach and --orphan or a possible three way , i'm not sure who's kinkiest here me itzg or github

**Comment by itzg** [comment]
It's only been two years :), but I finally worked up the nerve to archive the other directories of this repo, shift the minecraft-server files up to the top level, and rename the repo to effectively make it be its own repo.

Github will handle the redirects, but the new repo URL is https://github.com/itzg/docker-minecraft-server.
