### ISSUE TITLE
different start command on version change

### ISSUE THREAD

**Issue by hrolofs** [itzg/docker-minecraft-server#1700]
### Enhancement Type

A completely new feature

### Describe the enhancement

Hello,

im using docker-minecraft-server for my spigot server with docker compose.

from my docker-compose.yml:
i don't use VERSION in the environment.

    image: itzg/minecraft-server
    command: --forceUpgrade --eraseCache
    environment:
      - TYPE=SPIGOT

Everytime when i restart the container the newest version of spigot.jar are downloaded if a newer version available. In the command i use  --forceUpgrade --eraseCache to make sure that in case of a newer version the world data are upgraded. This works fine. :-)

The forceUpgrade is done on every restart of the container  and it takes time and make for some minutes havy load on the server. Is it possible to use a different command in case of a version change of spigot (new version downloaded)? So that the forceUpgrade is only done when the version changed.

in my case:

without version change
command:

with version change
command: --forceUpgrade --eraseCache

Regards, Henry

**Comment by itzg** [comment]
All the `command` arguments are passed as is to the server, so I can't influence that behavior. Please provide full container config so I can provide any specific advice.
