### ISSUE TITLE
Rip out playerdb usage since it breaks a lot

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#1733]
And use Mojang's own API, such as

curl --request GET \
  --url https://api.mojang.com/users/profiles/minecraft/user

**Comment by itzg** [comment]
Should help with 
- #1732

**Comment by Cherry** [comment]
Sorry about the https://playerdb.co issues. This was caused by the username history API being removed as per https://help.minecraft.net/hc/en-us/articles/8969841895693, but we've patched this now.

**Comment by itzg** [comment]
Thanks for the quick follow up and fix. 

I'll leave it as is with playerdb usage for now.

**Comment by Cherry** [comment]
No worries! Feel free to ping me in future if there's ever any issues with playerdb.

**Comment by christ37** [comment]
bonjour je écris car je viens de créer un serveur minecraft avec l'image itzg/minecraft-server est quand je me connecte j'ai un message **

> echec de connexion au serveur vous n'êtes pas sur la liste blanche de ce serveur !

** si on pourrais m'aider sa serais cool .

**Comment by TheDanilAssassin** [comment]
> Sorry about the https://playerdb.co issues. This was caused by the username history API being removed as per https://help.minecraft.net/hc/en-us/articles/8969841895693, but we've patched this now.
> 
> The main benefit you'll get with using PlayerDB over the official Mojang API is caching and speed, since it runs on Cloudflare Workers in 250+ locations.

Hello, an error has visited me. My friend can't log into the server. Does not load playerdb. There is no topic on the minecraft forum.

**Comment by martinflorek** [comment]
Sorry for reviving an old issue, but playerdb.co is down at the moment. All Minecraft username lookups are returning 500, thus servers cannot resolve usernames. cc @Cherry

**Comment by itzg** [comment]
I might have forgotten to document but you can set env var `USER_API_PROVIDER` to "mojang" for now.

**Comment by martinflorek** [comment]
@itzg the api.mojang.com/users/... is failing with 403 forbidden. What kind of auth does it need?

**Comment by itzg** [comment]
It shouldn't need any. I'll have to investigate if their endpoint changed. That code hasn't been utilized in a while.

**Comment by martinflorek** [comment]
Maybe this is the same problem, why playerdb is also failing, if a specific username is not cached on their side...

**Comment by itzg** [comment]
Yeah, I think Mojang is the root cause. The code is using the correct API endpoint according to

https://minecraft.wiki/w/Mojang_API#Query_player's_UUID

**Comment by Cherry** [comment]
We have observed an increase in errors on playerdb but the majority of requests are still succeeding. The cause seems to be `api.mojang.com` randomly throwing 403s, and that number of 403s escalating.
![](https://i.james.pub/file/2025/06/8ac68fb2-6211-4bbd-a3eb-24cfb032c62a.png)

We've deployed a fix to use `api.minecraftservices.com` instead which seems to be a more reliable, and are now seeing a drop in error rates. ![](https://i.james.pub/file/2025/06/9935c201-cc9e-45f0-8664-0b6e8ec655b5.png)

**Comment by krnlks** [comment]
If I understand correctly, then the whitelist cannot be configured anymore inside the compose file? Does that mean that [these instructions in your documentation](https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#whitelist-players) are deprecated?

**Comment by itzg** [comment]
> If I understand correctly, then the whitelist cannot be configured anymore inside the compose file? Does that mean that [these instructions in your documentation](https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#whitelist-players) are deprecated?

You're understanding is incorrect. What is documented is fully supported.
