### ISSUE TITLE
TCP4

### ISSUE THREAD

**Issue by dwhitnall** [itzg/docker-minecraft-server#175]
I've tried to get this running.  It downloads and runs fine but by default it would seem that java is listening to TCP6 and not TCP4.  I know that if you - export _JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true" before running the jar file locally you can get it to listen on TCP4.
Is there a way to do this in the container

**Comment by itzg** [comment]
Yes, that can be done. Which of the images in this repo need to be adjusted?

**Comment by itzg** [comment]
There is now a way to pass generic JVM options to the container:

https://github.com/itzg/docker-minecraft-server#jvm-options
