### ISSUE TITLE
Stop autopause from being awoken by bots

### ISSUE THREAD

**Issue by samit43** [itzg/docker-minecraft-server#1767]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Honestly I don't really know how this would be done but annoying minecraft server scanners and stuff are waking up the server every time they scan the server. Is there any way to prevent this, or at least reduce the quantity/impact of it?

**Comment by itzg** [comment]
I appreciate the concern, but this is impossible within the scope of the container startup scripts. 

Have you noticed the new logging of remote IP address that woke the server? Have you tried any networking based solutions like firewall whitelisting?

**Comment by samit43** [comment]
I have now and I guess I can just manually blacklist them on the router. Thanks for the reply!
