### ISSUE TITLE
Don't override motd in server.properties when not set as env var

### ISSUE THREAD

**Issue by DerEnderKeks** [itzg/docker-minecraft-server#1776]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Because of #1769 I noticed that the `motd` in the `server.properties` is overridden with the default generated motd every time when no custom motd is set with the `MOTD` env var.

I suggest that the motd is only overridden when it was intentionally set with the env var. This might apply to other properties too, but I just noticed this one so far.

**Comment by itzg** [comment]
That seems reasonable. I'll lose the cute "powered by Docker" default though 😉

**Comment by DerEnderKeks** [comment]
You could still use that when the file is generated/the motd wasn't modified manually

**Comment by itzg** [comment]
Very good point.

**Comment by tjsd** [comment]
The newest version overwrites my server.properties file, so I lose the settigns I have with white-list and motd.

**Comment by itzg** [comment]
@tjsd in that case, set `OVERRIDE_SERVER_PROPERTIES` to false.

**Comment by DerEnderKeks** [comment]
Wouldn't it be better if my suggestion was applied to all server properties, so that only the properties for variables that are intentionally set are overridden in the file? Maybe this could be an extra flag, something like `OVERRIDE_UNDEFINED_SERVER_PROPERTIES`, so you can choose which behavior you want.

**Comment by itzg** [comment]
@DerEnderKeks your original suggestions are great and what I'll implement. I was only offering a workaround for @tjsd to fully manage like the old behavior.

**Comment by itzg** [comment]
Feel free to comment or re-open if there are still scenarios not addressed.
