### ISSUE TITLE
Server immediately fails to launch

### ISSUE THREAD

**Issue by omaknight** [itzg/docker-minecraft-server#1786]
When running the following command:
docker run -d -it -e TYPE=FORGE -e VERSION=1.16.5 -e MEMORY=7G -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server

The server began to try and start, and then exited with the following error:
![image](https://user-images.githubusercontent.com/84608909/195989852-eda1b7c4-dc67-409f-bcde-d6e08eb72f97.png)

Any help would be appreciated.

**Comment by itzg** [comment]
Use `itzg/minecraft-server:java8-multiarch`

https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version
