### ISSUE TITLE
Add an environment variable that can edit the javaagent

### ISSUE THREAD

**Issue by KarLYelin** [itzg/docker-minecraft-server#1815]
### Enhancement Type

A completely new feature

### Describe the enhancement

I would like to add a feature that would allow the user to add an environment variable, the effect would be to add a command inside the server JAR file run with a format similar to this: -javaagent="Content set by environment variable"

Translated by DeepL，**Possible problems with grammar**

**Comment by itzg** [comment]
That is already supported

https://github.com/itzg/docker-minecraft-server#jvm-options
