### ISSUE TITLE
README: better explain setting ports

### ISSUE THREAD

**Issue by taggart** [itzg/docker-minecraft-server#1822]
### Enhancement Type

Not sure

### Describe the enhancement

In the [server port part of the README](https://github.com/itzg/docker-minecraft-server#server-port) you explain that probably you don't need to adjust this, and to use the normal docker run `-p` option to adjust things.

I think it might be worth explaining in that part at the top of the README that the first part will be the external port and second part the internal port and is advised to keep the internal the default. It seems like most things (like knockd) are now smart enough to automatically adjust for SERVER_PORT changes, but still better to keep everything inside the container the default where possible.

I also think it might be a good idea to encourage adjustment of the external port. Random attackers will be probing the default port and if they find it then at worst they could trash a poorly configured server and at least they will cause servers with autopause to wake up and add server load. This is a little like not running your ssh daemon on port 22 in order to avoid 99% of the people probing it. It _is_ security-thru-obscurity, but raising the bar a little helps.

I'm not sure of the best way to phrase the above, but maybe you have a better idea.
Thanks

**Comment by itzg** [comment]
There's only so much of standard Docker instructions that can be included in the README and the README is already overwhelming. 

I'll give this one some thought though. While port mapping is one of the most fundamental parts of Docker it seems to be overlooked and misunderstood by way too many people. 

As for external port changes, your suggestion is subjective and does not belong in the documentation.
