### ISSUE TITLE
WARN	mc-server-runner	Minecraft server process failed	{"exitCode": 1}

### ISSUE THREAD

**Issue by xinmans** [itzg/docker-minecraft-server#1839]
### Describe the problem

[init] Resolving type given VANILLA
[init] Setting initial memory to 2G and max to 2G
[init] Starting the Minecraft server...
Error: Invalid or corrupt jarfile minecraft_server.1.19.2.jar
2022-11-23T12:55:14.788Z	WARN	mc-server-runner	Minecraft server process failed	{"exitCode": 1}
2022-11-23T12:55:14.789Z	INFO	mc-server-runner	Done
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 3 1000 1000 4096 Nov 23 12:55 /data'
[init] Resolved version given LATEST into 1.19.2 and major version 1.19
[init] Resolving type given VANILLA

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
Real error is

```
Error: Invalid or corrupt jarfile minecraft_server.1.19.2.jar
```

Set `FORCE_REDOWNLOAD` to "true" temporarily and see if that downloads a valid file.
