### ISSUE TITLE
minecrafter-server can only run on x86_64

### ISSUE THREAD

**Issue by bear454** [itzg/docker-minecraft-server#185]
While most of the dependency stack for your (awesome) minecraft-server image runs fine on armv7l (e.g. Raspberry Pi), your own dependencies are Arch-specific, and this blocks use on other architectures:

```
ADD https://github.com/itzg/restify/releases/download/1.0.4/restify_linux_amd64 /usr/local/bin/restify
ADD https://github.com/itzg/rcon-cli/releases/download/1.3/rcon-cli_linux_amd64 /usr/local/bin/rcon-cli
```

You're building binaries of both restify & rcon-cli for ARM; it would be nice to reference the proper binary here.

**Comment by itzg** [comment]
Good point and good idea. I think the main mental barrier is making effective use of image labels, etc to organize the different architecture types.

**Comment by bear454** [comment]
Maybe this can be accomplished with a Dockerfile ARG ? 
https://docs.docker.com/engine/reference/builder/#arg

If not, I'd be happy to submit a pull with an arm version ;-)

**Comment by itzg** [comment]
Unfortunately Docker Hub’s automated builds don’t seem to accept the arguments to feed into ARG declarations. I think a branch will work fine like I’ve done for the Debian variant. 

A PR would be fantastic. I’ll create a branch for the PR destination...

**Comment by itzg** [comment]
...I created this branch for it

https://github.com/itzg/dockerfiles/tree/mc/arm

**Comment by itzg** [comment]
Hmm, apparently there’s a multi-arch image building available. We’ll have to figure out how to tap into that

https://blog.docker.com/2017/11/multi-arch-all-the-things/

**Comment by bear454** [comment]
Yeah, you can add a manifest, but you still need per-arch dockerfiles ;-)

**Comment by itzg** [comment]
It's not the most ideal solution, but there is now a multiarch tag

```
itzg/minecraft-server:multiarch
```

that will use the appropriate image for the current platform.
