### ISSUE TITLE
Fabric 1.19 doesn't start, unplayable

### ISSUE THREAD

**Issue by Tors-0** [itzg/docker-minecraft-server#1865]
### Describe the problem

just reinstalled my minecraft fabric server to change to a new modpack, just get this error and it doesnt even generate the server files like 'config' 'mods' etc

### Container definition

```
docker run -d -v /home/rae/mc-docker:/data \
-e TYPE=FABRIC \
-p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server:java17-jdk \
-e VERSION=1.19 \
-e MEMORY=6G \
--restart unless-stopped \
-e FABRIC_LOADER_VERSION=0.14.11
```

### Container logs

```
user@server:~$ docker logs mc 
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 3 1000 1000 4096 Dec 18 01:47 /data'
[mc-image-helper] 02:27:47.697 ERROR : 'get' command failed: launchermeta.mojang.com: Temporary failure in name resolution
[init] ERROR: version lookup failed: 
```

**Comment by Tors-0** [comment]
oh and when i visit the website its trying to pull from, i just see 
![image](https://user-images.githubusercontent.com/73916067/208278738-b389f91d-9840-40a9-8879-9f4dcb905df4.png)

**Comment by itzg** [comment]
The log shows you have a DNS issue

```
Temporary failure in name resolution
```

The screenshot also looks like some strange networking issue on your system with invalid HTTPS certificate.
