### ISSUE TITLE
Add Modrinth support for Spigot/Paper plugins

### ISSUE THREAD

**Issue by theo546** [itzg/docker-minecraft-server#1884]
### Enhancement Type

A completely new feature

### Describe the enhancement

As of now, Modrinth now allow the download of plugins for any Bukkit/Spigot/Paper server, which is awesome, and could be integrated like spiget already is.

You can see a page full of plugins from the Modrinth website here: https://modrinth.com/plugins

As a bonus point, what about being able to use both SPIGET_RESOURCES and a new MODRINTH_RESOURCES environnement variable at the same time?

**Comment by itzg** [comment]
Good news: it's already supported 

https://github.com/itzg/docker-minecraft-server#auto-download-mods-from-modrinth

**Comment by theo546** [comment]
> 

Is not only for mods?

**Comment by itzg** [comment]
I think they call them "projects": mods, plugins, whatever. 

Did you try the feature and it didn't work for you?

**Comment by theo546** [comment]
I just tried with the following env variables, it doesn't download anything:

```
      VERSION: "1.19.3"
      TYPE: "PAPER"
      MODRINTH_ALLOWED_VERSION_TYPE: "release"
      MODRINTH_PROJECTS: "coreprotect"
```

**Comment by itzg** [comment]
[This image build](https://github.com/itzg/docker-minecraft-server/actions/runs/3824731972) will include the new Modrinth support

**Comment by theo546** [comment]
Thank you, this is now working as expected!
I did a one-time sponsor payment of 10$, thank you again for your clean and fast work!

**Comment by itzg** [comment]
Awesome and thanks!

**Comment by terafin** [comment]
Nevermind, looks like my error. These are modrinth mods, not plugins :) Nothing to see here, moving along!

**Comment by terafin** [comment]
That said, the documentation implies it works with mods, and this mod for example: `https://modrinth.com/mod/light-overlay` does not seem to load if I put it as the only one.

**Comment by itzg** [comment]
> Sorry for the zombie issue, but I don't seem to see this working...

Don't apologize. Just open a new issue.

**Comment by terafin** [comment]
Doing so now :) Thanks!
