### ISSUE TITLE
Crashing when opening chest in Shipwreck's and When using waystones to get to the end city's 

### ISSUE THREAD

**Issue by Noddley** [itzg/docker-minecraft-server#1887]
### Describe the problem

 I have had A Minecraft docker container running for a while. but when I and my buds were playing we would go to shipwrecks' to get loot and it would crash the docker container I thought that was weird so I increased the ram usage and that seemed to improve the server running abilities but it did not fix the shipwreck glitch so we just never went near them but this evening we were beating the game and we wanted to go get some elytra's so we went through a waystone and the whole docker container crashed I can't find anyone else having this issue please help!

### Container definition

version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "6G"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data

### Container logs

[crash-2023-01-07_18.50.45-server.txt](https://github.com/itzg/docker-minecraft-server/files/10367032/crash-2023-01-07_18.50.45-server.txt)

**Comment by Noddley** [comment]
update everything works fine when there's only one person on but the when someone joins the server crashes in my mind it might be a time to get a ssd?

**Comment by itzg** [comment]
I can't do anything about issues that happen after the container startup. Please report it to Mojang. 

Can also convert this to a discussion if you're just looking for advice from the community.
