### ISSUE TITLE
Java 19

### ISSUE THREAD

**Issue by Szczurs** [itzg/docker-minecraft-server#1898]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Hi there, I was wondering that there is a way to force docker container run minecraft server on java 18 or above. Some servers based on better minecraft 1.19.2 require such java to work properly. Thank you in advance for hints and help

**Comment by itzg** [comment]
That's easy to support, but it would be great if you could point me to such things that require Java 18+.

**Comment by Szczurs** [comment]
I am aware that this is not a common usage, but when I tried to deploy forge modpack https://www.curseforge.com/minecraft/modpacks/better-mc-new it could not start on java below 18. Finally after forcing linux distro to install that java version it works without docker container. 

this is a docker command which launches container with latest java 17 which does not satisfy this modpack
docker run -d -i -t -v /<someCustomPath>:/data -e TYPE=FORGE -e VERSION=1.19.2 -e FORGEVERSION=43.1.57 -e ONLINE_MODE=TRUE -e MEMORY=6G -e SERVER_PORT=25565 -p 25566:25565 -e EULA=TRUE --name mc itzg/minecraft-server 

As I mentioned it works in some way so it is not so much important. Also I am very confused with Java versioning since its licenses have changed.

Thank you in advance for hints and help ;)

**Comment by itzg** [comment]
I am not able to recreate this issue using

```
docker run -it --rm -e EULA=true -e TYPE=AUTO_CURSEFORGE -e CF_PAGE_URL=https://www.curseforge.com/minecraft/modpacks/better-mc-new/files/4167504 -e CF_FORCE_SYNCHRONIZE=true -v bettermc:/data -e MEMORY=4G itzg/minecraft-server
```

and I don't see any mention of a Java 19 requirement on their page.

I'm already providing 13 variants and would like to remove one before adding another. You can always clone this repo and set the base image as a build arg.

**Comment by Szczurs** [comment]
I will try this out. Thanks for help

**Comment by Szczurs** [comment]
After some tweaking I've found some note from modpack dev.

"YOU NEED JAVA 18 TO PLAY 1.19.2 MODPACKS. THIS CAN BE INSTALLED HERE https://adoptium.net/temurin/releases/?version=18 (install and run the .msi)"
If your server still doesn't launch with Java 18, uninstall other Java versions! This can be done by going to Programs and Features, then typing the letter "j" to search for versions of Java.

It is featured in modpack server readme file. Also the client refused to launch properly without new jdk installed on pc. For now server works on host directly using jdk 19. I miss the times where all stuff worked on java 8 with no issue. Btw thanks for issuing this docker image which saved me from numerous nightmares with multiple java version selection on host system. ;)
Thanks for notes and some usefull info. I am aware this project has still much to offer and saves me a lot of pain running numerous servers. ;)

**Comment by itzg** [comment]
Thanks for the follow up! Now I'm good with adding that.

**Comment by itzg** [comment]
Java 19 image is now available https://hub.docker.com/layers/itzg/minecraft-server/java19/images/sha256-b5968b87672e470757a050abafbe0e77d92978d7fb5fb9dc6ffbea242ba2e090?context=explore
