### ISSUE TITLE
Mods folder not seen?

### ISSUE THREAD

**Issue by guymckrone** [itzg/docker-minecraft-server#1937]
Trying to run a Fabric server for Minecraft 1.19.2 but no matter what I try the server only loads in with three mods. Below are the logs when I run, the docker-compose file, the dockerfile, and the mod folder.

Docker-Compose: https://pastebin.com/Gr12n4bq
Dockerfile: https://pastebin.com/17jpnfAs
Logs: https://pastebin.com/d7c3fRi1
Mod Folder: https://filebin.net/srzzb3r0grvu2bhu

**Comment by itzg** [comment]
That's certainly strange.

Can you try a few things:
1. `docker compose pull` to make sure the latest base image there
2. Provide the output of `docker compose run --entrypoint ls mc /mods` to see what the container sees
3. Add `DEBUG: "true"` to see some more details around the "Copying any mods over" step

**Comment by guymckrone** [comment]
I think the command might be off, but for 2, after running 1, I get this: 

Creating minecraft_mc_run ... done

For 3:

https://pastebin.com/LQUEQ9Hg

**Comment by itzg** [comment]
The command is correct. It means the `/mods` attached is empty. You'll need to investigate further on your system.

**Comment by guymckrone** [comment]
I have figured it out, and it was a simple, very dumb mistake. I had it pointed to the wrong location, which I thought I had checked, but i guess I had not. Thanks for your help
