### ISSUE TITLE
ERROR: FTBA Modpack requires 1.19.2 but TYPE=FTBA requires Java8Multiarch

### ISSUE THREAD

**Issue by jaiinus** [itzg/docker-minecraft-server#1948]
### Describe the problem

Was working through https://github.com/itzg/docker-minecraft-server/issues/1492 and believe that there is a bug with FTBA packs that need modern minecraft versions. 

docker run -d -it -e TYPE=FTBA -e FTB_MODPACK_ID=101 -e VERSION=1.19.2 --name DirewolfMC -v /mnt/user/Minecraft/DirewolfMC/:/data  -e EULA=TRUE itzg/minecraft-server:latest

Error from docker logs:

[init] Resolved version given 1.19.2 into 1.19.2
[init] Resolving type given FTBA
[init] Invalid type: 'FTBA'
[init] Must be: VANILLA, FORGE, BUKKIT, SPIGOT, PAPER, FTBA (multiarch-only),
[init]          CURSE_INSTANCE, CURSEFORGE, SPONGEVANILLA,
[init]          CUSTOM, MAGMA, MOHIST, CATSERVER

I have tried minecraft-server:java17-alpine and java8-multiarch (as per the example https://github.com/itzg/docker-minecraft-server#running-a-server-with-a-feed-the-beast-modpack). Alpine 17 gives the same error and java8-multiarch errors out because 1.19.2 requires a modern Java.

In the past I succeeded in running this by using TYPE=FORGE, manually running the install script and copy pasting the files over. However this latest version requires a newer version of forge which broke my prior method so I am trying to do it the way the I believe it's "supposed" to be done with TYPE=FTBA.

### Container definition

docker run -d -it -e TYPE=FTBA -e FTB_MODPACK_ID=101 -e VERSION=1.19.2 --name DirewolfMC -v /mnt/user/Minecraft/DirewolfMC/:/data  -e EULA=TRUE itzg/minecraft-server:latest

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    1 1000     1000           150 Feb  3 11:52 /data'
[init] Resolved version given 1.19.2 into 1.19.2
[init] Resolving type given FTBA
[init] Invalid type: 'FTBA'
[init] Must be: VANILLA, FORGE, BUKKIT, SPIGOT, PAPER, FTBA (multiarch-only),
[init]          CURSE_INSTANCE, CURSEFORGE, SPONGEVANILLA,
[init]          CUSTOM, MAGMA, MOHIST, CATSERVER

**Comment by itzg** [comment]
The image `itzg/minecraft-server:latest` is what you should be using for a Java 17 based on Debian...however it does look like you're running into some of bug where it is rejecting TYPE=FTBA. Silly question, but are you sure this isn't a non-printable character within that value?

**Comment by itzg** [comment]
I am not able to recreate the issue by running:

```
docker run -d -it -e TYPE=FTBA -e FTB_MODPACK_ID=101 -e VERSION=1.19.2 -e EULA=TRUE itzg/minecraft-server
```

Please make sure you have pulled the latest image just in case it is an old bug.

**Comment by jaiinus** [comment]
Your initial guess was correct. I thought I had been updating my image through a GUI system (Unraid OS) but after checking it hadn't pulled a new image in ages. Thank you for the prompt response and I apologize for such a simple mistake.

**Comment by itzg** [comment]
So glad to hear 🎉
