### ISSUE TITLE
Identify the modpack(s) installed and what version

### ISSUE THREAD

**Issue by camalot** [itzg/docker-minecraft-server#1975]
### Enhancement Type

A completely new feature

### Describe the enhancement

I would like it if there was a way (maybe just a text file) to get the current installed version of the modpacks installed.

Take `TYPE: AUTO_CURSEFORGE` for example: 

```yaml
TYPE: AUTO_CURCEFORGE
CF_SLUG: all-the-mods-8
```

Would like if there was an indicator file that identified what version of All The Mods that are installed. 

If this exists somewhere already, please let me know where, because I looked and was unable to locate anything stating that version `1.0.11` was installed, except in the initial startup logs.

Use case: 

I have a discord community and require whitelisting for the MC server, and have to inform them if there are changes to the modpack version. or if the version hasn't updated for some reason. Having this info in a file will allow the discord bot to automatically inform the community what version of the pack is installed. Currently, I have to manually update a file that I have the bot reading info from.

**Comment by itzg** [comment]
That use case seems reasonable. So, there's already the `.curseforge-manifest.json` file which tracks various things including the resolved modpack's file ID (newlines added and `files` stripped down for clarity):

```json
{
  "@type": "me.itzg.helpers.curseforge.CurseForgeManifest",
  "timestamp": "2023-02-24T21:18:48.364886508Z",
  "files": [...],
  "modId": 520914,
  "fileId": 4402331,
  "minecraftVersion": "1.19.2",
  "modLoaderId": "forge-43.2.3",
  "levelName": null
}
```

Admittedly the `fileId` is not immediately helpful. Side note, to clarify something, modpacks don't have explicit declared versions, they just have a naming convention of putting a version in the modpack's file name. So, as a human, looking at 'All the Mods 8-1.0.11.zip', it's obvious that's version 1.0.11. Code could extract that out in this particular case, but I have learned that mod/modpack authors follow very little consistency amongst themselves.

So, I have a few proposals:
1. Add that filename, such as 'All the Mods 8-1.0.11.zip' into the manifest as a field, like `fileName`
2. Enhance `mc-image-helper` to allow for resolving the mod+file IDs from the manifest into the file name
3. Put the file name in some other file, perhaps optionally in a file named from the value in an env var like `CF_STORE_MODPACK_FILENAME`.

I would prefer 1 or 2 and it is sounding like a ready-to-read file fits the need best. So, I'm highly recommending option 1.

**Comment by camalot** [comment]
I don't know how i even missed that file. 

I like the idea of adding the info to that file. puts all the info in the single location.

**Comment by itzg** [comment]
It's a dot/hidden file, so purposely easy to miss 😀

Cool, I'll go with option 1 then.

**Comment by itzg** [comment]
Image is building now.

At first you'll need to set `CF_FORCE_SYNCHRONIZE` to "true" to recreate the manifest file. Otherwise, it'll update as new version is processed.
