### ISSUE TITLE
Setting Gamemode does not work if datadir is empty

### ISSUE THREAD

**Issue by josephshanak** [itzg/docker-minecraft-server#1980]
# Summary

https://github.com/itzg/docker-minecraft-server/blob/705e266f760088b9b775fb98d6a17f362d654161/scripts/start-setupServerProperties#L25-L32

The above code attempts to either add or update a property in `server.properties` depending on whether it is already present.
However this does not work for if you are starting with a blank `datadir` and are attempting to set `gameMode`.

In this case `grep "${prop}" "$SERVER_PROPERTIES"` returns true because `force-gamemode=false` matches the regular expression. However the subsequent call to sed (`sed -i "/^${prop}\s*=/ c ${prop}=${value//\\/\\\\}" "$SERVER_PROPERTIES"`) does nothing since that regular expression does not match any line in the file.

# Example

For example, utilizing https://github.com/itzg/minecraft-server-charts :

```yaml
minecraftServer: 
  whitelist:
  levelType: FLAT
  difficulty: hard
  gameMode: creative  # Default is normally survival

persistence:
  storageClassName: "local-path"
  dataDir:
    enabled: true
    Size: 10Gi

extraEnv:
  DUMP_SERVER_PROPERTIES: true
```

This produces output similar to the following. Note that the output claims that `gamemode` is being set to `creative` but the dumped `server.properties` does not show it.
```log
[init] 2023-02-28 15:46:51+00:00 Enabling whitelist functionality 
[init] 2023-02-28 15:46:51+00:00 DEBUG: Adding white-list with 'true' in /data/server.properties
[init] 2023-02-28 15:46:51+00:00 DEBUG: Adding enforce-whitelist with 'true' in /data/server.properties
...
[init] 2023-02-28 15:46:52+00:00 DEBUG: Adding level-type with 'FLAT' in /data/server.properties
[init] 2023-02-28 15:46:52+00:00 DEBUG: Adding difficulty with 'hard' in /data/server.properties
[init] 2023-02-28 15:46:52+00:00 Setting mode
[init] 2023-02-28 15:46:53+00:00 DEBUG: Setting gamemode to 'creative' in /data/server.properties
[init] 2023-02-28 15:46:53+00:00 DEBUG Dumping server.properties
white-list=true
enforce-whitelist=true
...
level-type=FLAT
difficulty=hard
```

If you inspect the `server.properties` after it has started, the `server.properties` the file now contains `gamemode=survival`.

```
  DUMP_SERVER_PROPERTIES: true

```properties
#Minecraft server properties
#Tue Feb 28 15:47:09 UTC 2023
gamemode=survival
difficulty=hard
white-list=true
enforce-whitelist=true
level-type: flat
```

# Recommendation
* You could initially copy the base file (https://github.com/itzg/docker-minecraft-server/blob/master/files/server.properties) to the datadir to handle this case. This would ensure that `gamemode=` is present in the case.
* You could also change the regular expression to check for `^${prop}=` or `^\s+${prop}=` to avoid the prefix problem.

**Comment by josephshanak** [comment]
In my case I was able to workaround this using an init-container and `overrideServerProperties` similar to

```
initContainers:
  - name: init-serverproperties
    image: busybox
    command:
      [
        "/bin/sh",
        "-c",
        "[ -f ./data/server.properties ] || echo 'gamemode=survival' > /data/server.properties",
      ]
    volumeMounts:
      - name: datadir
        mountPath: /data

minecraftServer:
  - overrideServerProperties: true
```

However, I still think it would be useful to change the property existence check to deal with prefixes.

**Comment by itzg** [comment]
Thanks for reporting and investigating this. Agreed, that grep call needs to be more restrictive, building on your suggestion:

```
grep "^\s*${prop}\s*=" "$SERVER_PROPERTIES"
```

**Comment by Sammcb** [comment]
Just curious, I believe I'm hitting this issue as well. I see that it was marked as stale, was this work captured in a different issue/PR? Thanks so much, really appreciate all the amazing to work you've done!

**Comment by itzg** [comment]
Funny timing since I am at this same moment overhauling the server properties handling in https://github.com/itzg/docker-minecraft-server/pull/2414

**Comment by itzg** [comment]
Please retry this after [this build](https://github.com/itzg/docker-minecraft-server/actions/runs/6442811587) finishes.

**Comment by Sammcb** [comment]
This is working for me now, thank you so much!
