### ISSUE TITLE
unable to access rcon

### ISSUE THREAD

**Issue by Traptonian** [itzg/docker-minecraft-server#1995]
rcon port and password set up but when trying to access i get this
![image](https://user-images.githubusercontent.com/60815502/223291756-1cc7e462-f9c7-49f5-8ead-aff5aa41be60.png)

**Comment by itzg** [comment]
You're trying from a browser? RCON is not a web protocol.

**Comment by Traptonian** [comment]
i was what do i access it from

**Comment by itzg** [comment]
https://github.com/itzg/docker-minecraft-server#interacting-with-the-server

or anything else that communicates using [RCON protocol](https://wiki.vg/RCON).

**Comment by Traptonian** [comment]
ah ok thank you
