### ISSUE TITLE
desync between users and server?

### ISSUE THREAD

**Issue by Traptonian** [itzg/docker-minecraft-server#1998]
### Discussed in https://github.com/itzg/docker-minecraft-server/discussions/1997

<div type='discussions-op-text'>

<sup>Originally posted by **Traptonian** March  8, 2023</sup>
i am using modded, but when im playing with my friend on a server and he opens a door it opens for him but not me? and then when i try to open the door it closes for me but not for him but he still cant get through?</div>

**Comment by itzg** [comment]
This has nothing to do with running containerized. 

Please don't open a discussion and an issue without waiting for some kind of response.
