### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by JAPGamer** [itzg/docker-minecraft-server#2000]
Hey guys,

I have a permissions problem when running docker minecraft servers. I'm working on a minecraft server network with different "gamemodes" and for every gamemode I created a unique image. The Dockerfile of an example image looks like this: 

"FROM itzg/minecraft-server:latest \n" +
                    "COPY --chmod=0777 global /data \n" +
                    "COPY --chmod=0777 mode1 /data \n"

So I basically just copy the template files (global and specific) into the data folder of the image. I tried it out (added a plugins folder to the template and put an example plugin in there) but receive the following message from the plugin (worldedit) that it can't create its config file and other folders. 
`[14:36:07 WARN]: [WorldEdit] Failed to write default config file
2023-03-08 15:36:07 java.io.FileNotFoundException: plugins/WorldEdit/config.yml (No such file or directory)

2023-03-08 16:30:24 [15:30:24 WARN]: Failed to create asset directory
2023-03-08 16:30:24 java.nio.file.AccessDeniedException: /data/plugins/WorldEdit

`. I already tried out giving the folders chmod 777 (as you can see in the dockerfile) 

Can someone please help me?

Thanks so much in advance.

**Comment by itzg** [comment]
Last I tried, you cannot `COPY` content into a declared volume, such as `/data`. Instead, stage the content in one of the special directories the README describes.

**Comment by JAPGamer** [comment]
First thanks for your answer. But what "special directories" are you referring to? 

My ultimate goal is to give the Docker container (server)files as a kind of "template" without it then saving the changes to the template in return. 

My approach for this was creating unique images for every "gamemode" and just copying all files from there into the image. But maybe there is a better approach for this?

**Comment by itzg** [comment]
IMHO, creating a series of docker compose projects for each is better. But I can also see the appeal in an image for each.

This is the section: https://github.com/itzg/docker-minecraft-server#optional-plugins-mods-and-config-attach-points

**Comment by JAPGamer** [comment]
Ohh ok thank you. Is there also an option to copy basically everything from one folder into the "/data" folder. So not only for plugins like in -v ./plugins:/plugins (this is copied into /data/plugins after start if I got that right) but just for all server files?

Thanks in advance

**Comment by sja** [comment]
I added that, but I'm not familar with how to validate the result. Are the results compared to an expected value somewhere or is that more like a smoke test if the values can be rendered at all?
