### ISSUE TITLE
RCon enabled by default with default password

### ISSUE THREAD

**Issue by so7ow** [itzg/docker-minecraft-server#2002]
Is it a great idea to have RCon enabled by default with the default password of 'minecraft'? Someone used that default configuration to join my server and grant themselves server op. Not a huge deal and I've dealt with it now but perhaps a more secure config by default would be a good idea?

**Comment by itzg** [comment]
Did you have the rcon port bound outside the container?

**Comment by so7ow** [comment]
I did, and that was my fault. The guy who did this did so in a friendly way and he said he finds similarly configured servers very frequently.

**Comment by itzg** [comment]
Thanks for the followup. 

I should probably add a note advising about that on the README. 

I was also thinking I can generate a random value by default that the internal tools can still use. It might break other people, so I'll give that some more thought.

**Comment by hockeyduck3** [comment]
Is there a way to disable RCON and leave it off? My friends and I had a scare today where someone joined and took away our server op. It really scared us when I banned him and then he unbanned himself. Luckily I figured out what was going on and shut it down. 

Which part of that is on me cause I didn't know I didn't need to forward port 25575. But it does seem like when I go and change the server.properties file the RCON settings get reset when I restart the server. 

I'm also running my server in a docker container if that helps.

**Comment by so7ow** [comment]
Try stopping the server before you edit the file?

**Comment by itzg** [comment]
@hockeyduck3 yes, take a look at the README and use those variables instead of the properties file.

**Comment by itzg** [comment]
> I was also thinking I can generate a random value by default that the internal tools can still use. It might break other people, so I'll give that some more thought.

Just reconfirmed this won't work at all since the environment variable needs to be available at the container level and not just the startup process.

Would leaving out the `EXPOSE` of 25575 help prevent the inclination to bind that port?

@so7ow @hockeyduck3 what documentation, tutorial, etc led you to believe 25575 should be bound and port forwarded?

**Comment by so7ow** [comment]
> @so7ow @hockeyduck3 what documentation, tutorial, etc led you to believe 25575 should be bound and port forwarded?

Sorry, I don't recall--it was too long ago. I wasn't aware of RCon as a concept and I was just trying to make the sever accessible to friends. Clearly I should have read a little more.

**Comment by hockeyduck3** [comment]
> @so7ow @hockeyduck3 what documentation, tutorial, etc led you to believe 25575 should be bound and port forwarded?

Here's a link to the tutorial I followed. https://drfrankenstein.co.uk/2021/05/03/minecraft-java-server-in-docker-on-a-synology-nas/

In the tutorial the guy didn't say anything about the ports other than: "You will now see the Port Settings screen, you will need to type in the Local Ports to match the Container Ports shown on the right hand side, this will stop the container from being assigned random ports when it is started and make accessing your server easy."

Since the tutorial didn't say anything about what either ports were for, my dumb brain thought I had to forward both in order for my friends to connect. 

I honestly feel so dumb that I didn't notice that only one port needed to be forwarded. But just like @so7ow until yesterday I didn't know RCON was a thing.

**Comment by itzg** [comment]
Thanks, both, for the follow-up info. I think the removal of the pre-exposed port declaration will help quite a bit for future scenarios like this. That updated image is building now.

**Comment by shinysocks** [comment]
I'm having trouble with rcon as well.
Firstly, I agree that it should be disabled by default.
Secondly, when I attempt to disable it in the server.properties file, it keeps re-enabling. All other settings seem to persistent a container restart except for that one???

**Comment by itzg** [comment]
@shinysocks disable it with the environment variable as described in https://github.com/itzg/docker-minecraft-server#rcon

**Comment by shinysocks** [comment]
Thank you! I should have looked harder before asking... I really appreciate your work on this project.

**Comment by camalot** [comment]
> Just reconfirmed this won't work at all since the environment variable needs to be available at the container level and not just the startup process.

@itzg couldn't you generate a random password when building the container? maybe in the build action, or pass as a BUILD-ARG and set the env to the build-arg? 

Yeah, it will absolutely mess with people that are using the default password, but the fix for them would be to set that variable back to the default. so they would have to make the decision to set it to that value, or set to something else, if they want to use it. and really, SHOULD they be using RCON with default password?

Document that the password is RANDOM, and that it **MUST** be set in order to successfully use RCON.

**Comment by itzg** [comment]
Interesting idea @camalot especially with a build arg being invoked. A little scripted step could generate the random value as an output parameter 

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

and then that could be used as build arg value.

**Comment by camalot** [comment]
or you could even use an [existing action](https://github.com/marketplace/actions/get-random-password-and-its-hash) ([another one](https://github.com/marketplace/actions/random-password-generator)) and have it generate the random password

I thought about allowing to print the password to the logs if like `RCON_PRINT_PASSWORD` was set, but honestly, it is best to have them create their own RCON password.

**Comment by itzg** [comment]
Thanks, I wasn't able to find those actions with a quick search. Was thinking the same with printing password, but had also reached the same conclusion.

**Comment by itzg** [comment]
...I do want to remind everyone: **do not expose your rcon port without a custom password**. The solution being discussed will still have to bake a password into the image itself. A bad actor can grab the latest few images and try those passwords on exposed servers.

**Comment by itzg** [comment]
Please see the discussion way above. For seamless, default behavior it needs to be set.

**Comment by camalot** [comment]
Yeah, working out of the box is important, for sure. I was thinking more along the lines of if they don't set the RCON_PASSWORD, then having it not work. just for security reasons. since you cant really check if they have exposed the RCON port outside of the container.

**Comment by itzg** [comment]
> I was thinking more along the lines of if they don't set the RCON_PASSWORD, then having it not work.

I'm confused. The default is not having it set, so therefore rcon would be disabled, but that would compromise the ease of use default behavior I just mentioned. 

In any case, I like the build time random password approach and can implement that soon'ish or can be PR'ed. I just wanted to warn people that it's only slightly more secure.

**Comment by camalot** [comment]
i will try to submit a PR for it if I have some time this week, if you don't get to it first.

**Comment by camalot** [comment]
Am I correct to assume that this test `tests/setuponlytests/defaults/verify.sh` should fail if my generation of the password, and passing as a build-arg, is done properly?

```
mc-image-helper assert propertyEquals --file=server.properties --property=rcon.password --expect=minecraft
```

I am running a `test/` branch, so before I create a PR, I want this test to fail, so I can then figure out the proper way to now do this test, so it passes.

**Comment by camalot** [comment]
![image](https://user-images.githubusercontent.com/171452/229889404-285a186d-fc49-405b-8a0a-3ea322994d25.png)

Perfect! i think this is what I am looking for. Now I just need to get the test to pass and I should have a PR. 

Should I PR directly from the `/test` branch?

**Comment by itzg** [comment]
> Should I PR directly from the `/test` branch?

The one where you're making #2051 changes? If so, then a separate branch would be good.

**Comment by camalot** [comment]
i have a `test/` branch specific to this change

**Comment by itzg** [comment]
In that case, yes PR from there should be good.

**Comment by camalot** [comment]
Interesting. 

I added a `require.sh` to `/tests/setuponly/tests/defaults` to ensure that an env var called `EXPECT_RCON_PASSWORD` (only used during the tests so it knows what to test for), and it passes just fine with that env var. 

When I attempt to use the same env var in `verify.sh`, the value of it there is `""` 

```
Starting Tests in ./defaults
Testing for EXPECT_RCON_PASSWORD value
EXPECT_RCON_PASSWORD=docaeZtdv6PK3WAfGf0z
EXPECT_RCON_PASSWORD=
```

The first EXPECT_RCON_PASSWORD is from the `require.sh`, the second is from within the `verify.sh`. 

I am trying to execute the following:

```
mc-image-helper assert propertyEquals --file=server.properties --property=rcon.password --expect="${EXPECT_RCON_PASSWORD}"
```

which asserts:

```
Expected the property rcon.password in the file server.properties to be '', but was 'docaeZtdv6PK3WAfGf0z'
```


Oh... I think I understand why. `verify.sh` actually runs within the container, and `require.sh` runs on the "runner". So the runner has the environment variables, as set by the action step. And `require.sh` passes. But the env var doesnt actually exist within the container. 

The `require.sh` gives sort of an incorrect verification.

**Comment by camalot** [comment]
Got the tests working. 

My solution:

Like there is a `require.sh`, I added an `environment.sh`. This script is meant to output to a file to "generate" a `.env` file.

In this instance:

``` bash
echo "EXPECT_RCON_PASSWORD=${EXPECT_RCON_PASSWORD}"
```

in `setuponlytests/test.sh`, when the `verify.sh` is executed:

``` bash
  elif [ -f verify.sh ]; then
    # if there is an environment.sh, run it, and push the output to ./.tests.env. then load that as an env-file for the docker run
    env_file=$([ -f environment.sh ] && sh ./environment.sh > ./.tests.env && echo "--env-file=./.tests.env" || echo "")
    [ ! -z "${env_file// }" ] && echo "Using env-file argument: $env_file"
    if ! docker run --rm --entrypoint bash $env_file -v "${PWD}/data":/data -v "${PWD}/verify.sh":/verify "${IMAGE_TO_TEST:-itzg/minecraft-server}" -e /verify; then

# ...

    fi
    # clean up the env file it if exists
    [ -f ./.tests.env ] && rm -rf ./.tests.env
  else
```

**Comment by JorianWoltjer** [comment]
A bit late, but I'll join in here. I am the researcher who originally went around reporting this to servers, including many other weak passwords. I made a (for now private) scanner tool and found around 300 servers with the default "minecraft" password for this image and Rcon open publicly to the internet. 

Let me know if you have any questions

**Comment by itzg** [comment]
Ugh, now that I hear how bad that is, I'm going to figure out a way to make startup-time random password work with the adjacent tools.

**Comment by itzg** [comment]
[Next image build](https://github.com/itzg/docker-minecraft-server/actions/runs/4642543509) will randomize the default RCON password at every startup yet still ensure rcon-cli and mc-backup can access RCON.

**Comment by JorianWoltjer** [comment]
Thanks a lot for fixing this! As this update is pretty recent, there are still a lot of servers that are not updated, also because docker does not do this automatically afaik. 

I have set up my program to report to found servers every 4 hours via `/tellraw` that they are vulnerable with this version, and that they should update to `:latest` to fix it. Thought I would let you all know, and leave your thoughts

**Comment by itzg** [comment]
Thanks @JorianWoltjer that's a novel solution to try get people to remediate their container.
