### ISSUE TITLE
Typo in /scripts/start-setupModpack

### ISSUE THREAD

**Issue by stlouisn** [itzg/docker-minecraft-server#2014]
### Describe the problem

Typo in /scripts/start-setupModpack, line 278

elif isFaily FABRIC; then

should read as

elif isFamily FABRIC; then

### Container definition

```
```

### Container logs

```
/start-setupModpack: line 278: isFaily: command not found
```

**Comment by itzg** [comment]
Thanks so much for reporting this. I'll get this fixed momentarily.
