### ISSUE TITLE
Autopause not working in java8 tag

### ISSUE THREAD

**Issue by Caedis** [itzg/docker-minecraft-server#2017]
Getting an error on startup:

    sudo: unable to execute /usr/local/sbin/knockd: No such file or directory
    [Autopause loop] Failed to start knockd daemon.
    [Autopause loop] Probable cause: Unable to attach to interface "eth0".
    [Autopause loop] Available interfaces within the docker container:
    [Autopause loop]   eth0
    [Autopause loop] Please set the environment variable AUTOPAUSE_KNOCK_INTERFACE to the interface that handles incoming connections.
    [Autopause loop] If unsure which interface to choose, run the ifconfig command in the container.
    [Autopause loop] Autopause failed to initialize. This log entry will be printed every 30 minutes.

Guessing one of the issues is:

https://github.com/itzg/docker-minecraft-server/blob/48414b3e87ccf524f55dd4e22e74826346f167e3/files/autopause/autopause-daemon.sh#L42

Going into the container gives:

    bash-4.4# which knockd
    /usr/local/sbin/knockd
    bash-4.4# which knock
    /usr/local/bin/knock

**Comment by itzg** [comment]
@Metalcape it looks like Alpine support is broken for auto-pause. I'm guessing it's because Alpine uses musl instead of glibc and the binary needs to be built accordingly. Statically linking would probably solve it too. Can you research this some?

**Comment by Metalcape** [comment]
I've looked into it and apparently static linking isn't possible due to certain functions like `getaddrinfo` that still require the glibc binary even when statically linked. For alpine we only support amd64 right? Dealing with musl cross-compilers seems complicated.

**Comment by itzg** [comment]
...in fact, I'm now thinking that either way the knockd installation at

https://github.com/itzg/docker-minecraft-server/blob/f6493892e5fc2fc174993ebf0704560f949eb3b6/Dockerfile#L55-L58

should probably be situated in the `build/*/install-packages.sh` scripts. In which, case altering the alpine installation is quite natural to alter via that mechanism.
