### ISSUE TITLE
Possible enhancement: Git integration

### ISSUE THREAD

**Issue by samara8609** [itzg/docker-minecraft-server#202]
Any thought to integrating in github/gitlab for world backups?  Basically pass in a few variables to reflect the git repo you want snapshots uploaded to, then on scheduled backup run an additional command to upload that backup to git.  On the reverse side adding a variable where you can tell via the docker-compose to pull down the last backup and restore?

**Comment by itzg** [comment]
Yeah, that’s a cool idea. Similarly I have used this recently backup DB snapshots to cloud storage

https://rclone.org/

**Comment by TheLeftMoose** [comment]
As this is docker land, should a backup service run in a separate container with access to the minecraft volume?

**Comment by ryantheleach** [comment]
I've seen one example run a 'side car' backup container that was able to issue commands one by one to minecraft servers, suspending save operations before backup.
