### ISSUE TITLE
Change fabric version

### ISSUE THREAD

**Issue by asw13537** [itzg/docker-minecraft-server#2021]
Just wondering, using the oculus quest and have deployed your image to my server. How do you change the fabric to a compatible version for the oculus.

**Comment by itzg** [comment]
Did you look here yet

https://github.com/itzg/docker-minecraft-server#running-a-fabric-server

**Comment by itzg** [comment]
> I take it I can specify the latest loader with version 1.193

By default it will locate and download the latest loader.

**Comment by itzg** [comment]
...and to clarify, for the Minecraft version such as 1.19.3, you set that via `VERSION` regardless of type.
