### ISSUE TITLE
Knockd is not installed

### ISSUE THREAD

**Issue by jmighion** [itzg/docker-minecraft-server#2026]
### Describe the problem

From https://github.com/itzg/docker-minecraft-server/pull/2025, it looks like the `curl` will need `-L` at least to follow the redirect.
https://github.com/itzg/docker-minecraft-server/blob/master/build/ubuntu/install-packages.sh#L34
https://github.com/itzg/docker-minecraft-server/blob/master/build/alpine/install-packages.sh#L30
https://github.com/itzg/docker-minecraft-server/blob/master/build/ol/install-packages.sh#L43

Without it, the curl saves an empty file.
Example from the build logs:
https://github.com/itzg/docker-minecraft-server/actions/runs/4482650100/jobs/7880955108#step:6:1511

Not sure why the build didn't fail.

Chat in discord about it https://canary.discord.com/channels/660567679458869252/660569755320844308/1087842287834366052

### Container definition

```
podman run --rm -d -p 25566:25565 -v /home/jmighion/minecraft:/data:Z --name pause -e EULA=TRUE -e OPS=GodsSyntaxError -e INIT_MEMORY=1G -e MAX_MEMORY=4G -e WHITELIST=GodsSyntaxError -e ENFORCE_WHITELIST=true -e RCON_PASSWORD=pauser -e ENABLE_AUTOPAUSE=TRUE -e MAX_TICK_TIME=-1 -e AUTOPAUSE_TIMEOUT_EST=60 -e AUTOPAUSE_TIMEOUT_INIT=30 -e AUTOPAUSE_TIMEOUT_KN=30 -e DEBUG_AUTOPAUSE=true -e OVERRIDE_SERVER_PROPERTIES=true --privileged docker.io/itzg/minecraft-server:latest
```

### Container logs

```
...output omitted...
+ sudo /usr/local/sbin/knockd -c /tmp/knockd-config.cfg -d -i eth0 -D
sudo: /usr/local/sbin/knockd: command not found
```

From exec'd inside:
```
podman run --rm -d -p 25566:25565 -v /home/jmighion/minecraft:/data:Z --name pause -e EULA=TRUE -e OPS=GodsSyntaxError -e INIT_MEMORY=1G -e MAX_MEMORY=4G -e WHITELIST=GodsSyntaxError -e ENFORCE_WHITELIST=true -e RCON_PASSWORD=pauser -e ENABLE_AUTOPAUSE=TRUE -e MAX_TICK_TIME=-1 -e AUTOPAUSE_TIMEOUT_EST=60 -e AUTOPAUSE_TIMEOUT_INIT=30 -e AUTOPAUSE_TIMEOUT_KN=30 -e DEBUG_AUTOPAUSE=true -e OVERRIDE_SERVER_PROPERTIES=true --privileged docker.io/itzg/minecraft-server:latest
```

**Comment by itzg** [comment]
Just noting that changing the declaration at the top of package install script would have stopped the build

```
set -euo pipefail
```
