### ISSUE TITLE
Builtin support for Paper Folia

### ISSUE THREAD

**Issue by Frank-Mayer** [itzg/docker-minecraft-server#2042]
### Enhancement Type

New server type

### Describe the enhancement

Would be awesome to support the new Folia (Multithreaded) fork of Paper.
https://github.com/PaperMC/Folia

**Comment by itzg** [comment]
Being what appears to be a fork under the official org, I'm curious if you know why they didn't just enhance the mainline one?

**Comment by TrinityMHT** [comment]
It would be great to see this engine in a docker image. I'm waiting to be added.

**Comment by cfpwastaken** [comment]
It wasn't added to actual Paper because it breaks lots of plugins.

**Comment by itzg** [comment]
Resolved by #2081
