### ISSUE TITLE
Add the possibility to pass `CF_API_KEY` via seperate file

### ISSUE THREAD

**Issue by feathecutie** [itzg/docker-minecraft-server#2048]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I usually like to store my docker configuration (e.g. via docker-compose) in version control on services like GitHub. However, with the new `CF_API_KEY` system, this would require uploading a secret key in plain text, which I'd really like to avoid.

It would be great if it was possible to store the API key in a seperate file that I can exclude from version control and just provide its location in the container's file system (e.g. via a new env var `CF_API_KEY_FILE`), which is then read at runtime.

Another option besides a new env var would be defining a standard path for the file and first checking if a file at that path exists before falling back to `CF_API_KEY`.

If you're willing to accept such a feature, I'd be happy to try and implement it myself. I haven't taken too close of a look at the codebase yet, so I'm not sure if what I'm suggesting is even possible, but I don't see why it wouldn't be.

**Comment by feathecutie** [comment]
Follow up: After doing more research (which I should have done beforehand), I've realized that both docker-compose and the NixOS module system (which I use for docker configuration) allow using `.env`-files instead of directly specifying environment variables, which would most likely solve the problem I described.

I'll leave this issue open because from a security standpoint, it still seems like a sensible idea, but I'd understand if this is seen as unnecessary

**Comment by itzg** [comment]
In fact, I'll use this issue to track a change I wanted to make to those docs to mention and highly recommend the use of the `.env` file.

While you're at it, @camalot , want to add this info into the same block you just updated? The `.env` file might be a way to avoid escaping `$`'s since it probably is not subject to variable substitution.

**Comment by itzg** [comment]
Resolved by #2054
