### ISSUE TITLE
Add webp package

### ISSUE THREAD

**Issue by willis936** [itzg/docker-minecraft-server#2066]
### Enhancement Type

A completely new feature

### Describe the enhancement

Add the webp package to the container for use with dynmap.

**Comment by itzg** [comment]
Seems reasonable, but out of curiosity can you provide any more info such as docs where dynmap lists webp as a requirement? What kind of issue/logs occurs without it?

**Comment by willis936** [comment]
It isn't necessary to run dynmap, but it is to use webp rather than png or jpg.

Here is where that is documented.

https://github.com/webbukkit/dynmap/wiki/Configuration.txt#image-format

**Comment by itzg** [comment]
Just noting that package name on Alpine seems to be `libwebp`

**Comment by itzg** [comment]
...and other platform package names provided [in their Reddit post](https://www.reddit.com/r/Dynmap/comments/ji7h87/support_for_webp_map_image_format_in_31snapshot/).

**Comment by willis936** [comment]
Thanks!

Could this be ported to the java8 branches?

**Comment by itzg** [comment]
All the variants are now built from master. There might be more packages needed for OracleLinux (base for GraalVM). I'll re-open and investigate a bit more.

**Comment by itzg** [comment]
I'm going to have to give up on the graalvm / OracleLinux based images. I can't find `libwebp-tools`, just

```
bash-4.4# dnf search webp
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:05:25 ago on Thu May  4 23:34:08 2023.
============================================= Name & Summary Matched: webp =============================================
libwebp.x86_64 : Library and tools for the WebP graphics format
libwebp.i686 : Library and tools for the WebP graphics format
libwebp.src : Library and tools for the WebP graphics format
libwebp-devel.i686 : Development files for libwebp, a library for the WebP format
libwebp-devel.x86_64 : Development files for libwebp, a library for the WebP format
webp-pixbuf-loader.src : WebP image loader for GTK+ applications
webp-pixbuf-loader.x86_64 : WebP image loader for GTK+ applications
================================================== Name Matched: webp ==================================================
python-webpy.src : A simple web framework for Python
python3-webpy.noarch : A simple web framework for Python
```

**Comment by willis936** [comment]
Ah okay.  The Alpine, Debian, and Ubuntu versions should have it though?

**Comment by itzg** [comment]
Yes.

**Comment by willis936** [comment]
Documenting my mistake for posterity.

I had a hiccup where I was incorrectly running docker pull, which pulls the "latest" tag, then used a docker compose yaml that launched a java8 tag, which used an older cached release of those tags.  By specifying the tag to pull the issue went away.

**Comment by itzg** [comment]
Good to close this then?

**Comment by willis936** [comment]
Yeah.  I think graalvm + webp support is a corner case and not that important.

**Comment by LichLord91** [comment]
Sorry to open a old thread but I'd double check the libwep versions these distros pull directly from their default repos.

Ubuntu Arm official repos has like a 0.6* or something and users of Dynmap were having issues generating webp images, myself included. I compiled to the latest 1.3.0 and it works.

https://github.com/webbukkit/dynmap/issues/3953#issuecomment-1505638671

**Comment by itzg** [comment]
Very interesting. Perhaps there's a more direct, up to date place to pull the binaries?

**Comment by itzg** [comment]
**NOTE**

Webp has been removed from the latest images. It was starting to add 200-300 MBs to the image size and hundreds of extraneous packages. I recommend either using an older image tag or building your own image that adds webp.
