### ISSUE TITLE
Auto-download Modrinth plugins

### ISSUE THREAD

**Issue by andriygm** [itzg/docker-minecraft-server#2075]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Currently, it appears that MODRINTH_PROJECTS only supports mods and not plugins (I've tried using the both the project slug and the ID). It would be convenient to also support plugins in the same way.

**Comment by itzg** [comment]
> Update: it seems that it does support plugins, but https://modrinth.com/plugin/bmarker seems to not want to download. Not sure why this one doesn't download but the other plugin does.

Just curious which server `TYPE` and `VERSION` you're using?

**Comment by andriygm** [comment]
`TYPE` is set to `PAPER` and `VERSION` is unset.
