### ISSUE TITLE
mc-send-to-console bug

### ISSUE THREAD

**Issue by caunt** [itzg/docker-minecraft-server#2090]
### Describe the problem

mc-send-to-console fails with input of special symbols, for example:

**$ docker exec mc mc-send-to-console 'say text1 text2 &acoloredText3'**
_say text1 text2
bash: acoloredText3: command not found_

**$ docker exec mc mc-send-to-console 'say text1 text2 > text3'**
logs: _[Server thread/INFO]: [Not Secure] [Server] text1 text2_

so its just interpreting linux shell operators instead of raw forwarding into server console even though I placed single quotes around

In first example ampersand & symbol splitted the command and "ran it in background". In second example > symbol somehow forwarded output to text3 file

both examples expected to write 3 words into server chat through command "say"

### Container definition

```
docker run -d -it -p 25565:25565 -e EULA=TRUE -e DEBUG=TRUE --name mc itzg/minecraft-server
```

### Container logs
<details>
  <summary>docker.log</summary>

    + export HOME=/data
    + HOME=/data
    ++ id -u
    ++ id -g
    ++ ls -lnd /data
    + log 'Running as uid=1000 gid=1000 with /data as '\''drwxrwxr-x 2 1000 1000 6 Apr 19 13:23 /data'\'''
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:03+00:00 Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 6 Apr 19 13:23 /data'
    + '[' '!' -e /data/eula.txt ']'
    + isTrue TRUE
    + case "${1,,}" in
    + return 0
    + writeEula
    ++ date
    + echo '# Generated via Docker
    # Sun 23 Apr 2023 08:12:03 AM UTC
    eula=true
    '
    + isTrue false
    + case "${1,,}" in
    + return 1
    + isTrue false
    + case "${1,,}" in
    + return 1
    + [[ -n '' ]]
    + [[ -n '' ]]
    + echo password=9027ce881a23fa0e13d9e775
    + fixJavaPath
    + which java
    + export VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
    + VERSIONS_JSON=https://launchermeta.mojang.com/mc/game/version_manifest.json
    + case "X$VERSION" in
    ++ get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
    ++ mc-image-helper get --json-path '$.latest.release' https://launchermeta.mojang.com/mc/game/version_manifest.json
    [mc-image-helper] 08:12:05.094 DEBUG : Getting uri=https://launchermeta.mojang.com/mc/game/version_manifest.json
    [mc-image-helper] 08:12:05.101 DEBUG : Executing GET /mc/game/version_manifest.json with headers=[Accept: application/json]
    [mc-image-helper] 08:12:05.113 DEBUG : Intercepting request uri=https://launchermeta.mojang.com/mc/game/version_manifest.json
    [mc-image-helper] 08:12:05.478 DEBUG : Post-request capturing redirectLocations=[]
    [mc-image-helper] 08:12:05.478 DEBUG : Response: status=200, reason=OK, headers=[Cache-Control: public, max-age=120, Transfer-Encoding: chunked, Content-Type: application/json, Last-Modified: Thu, 20 Apr 2023 14:26:51 GMT, ETag: 0x8DB41AB486DB1BD, X-Cache: TCP_HIT, x-ms-request-id: 1fafa5a9-f01e-0071-55bb-75d991000000, x-ms-version: 2009-09-19, x-ms-lease-status: unlocked, x-ms-blob-type: BlockBlob, X-Azure-Ref-OriginShield: 0LOhEZAAAAACkZuicRui9RLqhTnOX1bkNTU5aMjIxMDYwNjEyMDM1ADJhYmYyZTY2LWJkZWEtNDVjYy05YTAzLTY0YTNiZmM0NzIzZg==, Access-Control-Allow-Origin: *, X-Azure-Ref: 0VehEZAAAAABH4rYlvYwYT5lvtdUeUdtXTU5aMjIxMDYwNjEzMDE5ADJhYmYyZTY2LWJkZWEtNDVjYy05YTAzLTY0YTNiZmM0NzIzZg==, Date: Sun, 23 Apr 2023 08:12:05 GMT]
    + VANILLA_VERSION=1.19.4
    + export VANILLA_VERSION
    ++ get_major_version 1.19.4
    ++ version=1.19.4
    ++ echo 1.19.4
    ++ cut -d. -f 1-2
    + MAJOR_VANILLA_VERSION=1.19
    + export MAJOR_VANILLA_VERSION
    + log 'Resolved version given LATEST into 1.19.4 and major version 1.19'
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:05+00:00 Resolved version given LATEST into 1.19.4 and major version 1.19
    + cd /data
    + export ORIGINAL_TYPE=VANILLA
    + ORIGINAL_TYPE=VANILLA
    + isTrue false
    + case "${1,,}" in
    + return 1
    + isTrue false
    + case "${1,,}" in
    + return 1
    + [[ -n '' ]]
    + [[ -n '' ]]
    + [[ -n '' ]]
    + [[ -n '' ]]
    + [[ -n '' ]]
    + versionLessThan 1.7
    + mc-image-helper compare-versions 1.19.4 lt 1.7
    + return 1
    + log 'Resolving type given VANILLA'
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:06+00:00 Resolving type given VANILLA
    + case "${TYPE^^}" in
    + exec /start-deployVanilla
    + set -o pipefail
    + export SERVER=minecraft_server.1.19.4.jar
    + SERVER=minecraft_server.1.19.4.jar
    + '[' '!' -e minecraft_server.1.19.4.jar ']'
    + debug 'Finding version manifest for 1.19.4'
    + isDebugging
    + isTrue TRUE
    + case "${1,,}" in
    + return 0
    + return 0
    + log 'DEBUG: Finding version manifest for 1.19.4'
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:06+00:00 DEBUG: Finding version manifest for 1.19.4
    ++ get https://launchermeta.mojang.com/mc/game/version_manifest.json
    ++ mc-image-helper get https://launchermeta.mojang.com/mc/game/version_manifest.json
    ++ jq --arg VANILLA_VERSION 1.19.4 --raw-output '[.versions[]|select(.id == $VANILLA_VERSION)][0].url'
    [mc-image-helper] 08:12:07.729 DEBUG : Getting uri=https://launchermeta.mojang.com/mc/game/version_manifest.json
    [mc-image-helper] 08:12:07.737 DEBUG : Executing GET /mc/game/version_manifest.json with headers=[]
    [mc-image-helper] 08:12:07.747 DEBUG : Intercepting request uri=https://launchermeta.mojang.com/mc/game/version_manifest.json
    [mc-image-helper] 08:12:08.084 DEBUG : Post-request capturing redirectLocations=[]
    [mc-image-helper] 08:12:08.084 DEBUG : Response: status=200, reason=OK, headers=[Cache-Control: public, max-age=120, Transfer-Encoding: chunked, Content-Type: application/json, Last-Modified: Thu, 20 Apr 2023 14:26:51 GMT, ETag: 0x8DB41AB486DB1BD, X-Cache: TCP_HIT, x-ms-request-id: 1fafa5a9-f01e-0071-55bb-75d991000000, x-ms-version: 2009-09-19, x-ms-lease-status: unlocked, x-ms-blob-type: BlockBlob, X-Azure-Ref-OriginShield: 0LOhEZAAAAACkZuicRui9RLqhTnOX1bkNTU5aMjIxMDYwNjEyMDM1ADJhYmYyZTY2LWJkZWEtNDVjYy05YTAzLTY0YTNiZmM0NzIzZg==, Access-Control-Allow-Origin: *, X-Azure-Ref: 0WOhEZAAAAADfuVLKxdCiQZwqGpIGsG64TU5aMjIxMDYwNjE0MDI5ADJhYmYyZTY2LWJkZWEtNDVjYy05YTAzLTY0YTNiZmM0NzIzZg==, Date: Sun, 23 Apr 2023 08:12:07 GMT]
    + versionManifestUrl=https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json
    + result=0
    + '[' 0 '!=' 0 ']'
    + '[' https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json = null ']'
    + debug 'Found version manifest at https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json'
    + isDebugging
    + isTrue TRUE
    + case "${1,,}" in
    + return 0
    + return 0
    + log 'DEBUG: Found version manifest at https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json'
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:08+00:00 DEBUG: Found version manifest at https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json
    ++ get --json-path '$.downloads.server.url' https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json
    ++ mc-image-helper get --json-path '$.downloads.server.url' https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json
    [mc-image-helper] 08:12:09.472 DEBUG : Getting uri=https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json
    [mc-image-helper] 08:12:09.479 DEBUG : Executing GET /v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json with headers=[Accept: application/json]
    [mc-image-helper] 08:12:09.490 DEBUG : Intercepting request uri=https://piston-meta.mojang.com/v1/packages/f42c5f3f354ab3fef44088fe61e9c1cdbc25a8cc/1.19.4.json
    [mc-image-helper] 08:12:09.849 DEBUG : Post-request capturing redirectLocations=[]
    [mc-image-helper] 08:12:09.849 DEBUG : Response: status=200, reason=OK, headers=[Cache-Control: public, max-age=1209600, Transfer-Encoding: chunked, Content-Type: application/json, Last-Modified: Thu, 20 Apr 2023 12:03:16 GMT, ETag: 0x8DB4197398B4516, X-Cache: TCP_HIT, x-ms-request-id: 58e3aa4c-201e-000c-608b-73f48a000000, x-ms-version: 2009-09-19, x-ms-lease-status: unlocked, x-ms-blob-type: BlockBlob, Access-Control-Allow-Origin: *, X-Azure-Ref: 0WehEZAAAAABc/Fp0RzaBR4a/Zaf/b4uLTU5aMjIxMDYwNjExMDI3ADJhYmYyZTY2LWJkZWEtNDVjYy05YTAzLTY0YTNiZmM0NzIzZg==, Date: Sun, 23 Apr 2023 08:12:09 GMT]
    + serverDownloadUrl=https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar
    + '[' https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar = null ']'
    + log 'Downloading 1.19.4 server...'
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:09+00:00 Downloading 1.19.4 server...
    + debug 'Downloading server from https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar'
    + isDebugging
    + isTrue TRUE
    + case "${1,,}" in
    + return 0
    + return 0
    + log 'DEBUG: Downloading server from https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar'
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:09+00:00 DEBUG: Downloading server from https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar
    + get -o minecraft_server.1.19.4.jar https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar
    + mc-image-helper get -o minecraft_server.1.19.4.jar https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar
    [mc-image-helper] 08:12:12.245 DEBUG : FILE FETCH: uri=https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar headers=[user-agent: mc-image-helper/1.27.5 (cmd=unspecified), x-fetch-session: 9f26a2aa-49d5-41fa-adb7-ea8bceff4836, host: piston-data.mojang.com, accept: */*]
    [mc-image-helper] 08:12:13.652 DEBUG : Download of https://piston-data.mojang.com/v1/objects/8f3112a1049751cc472ec13e397eade5336ca7ae/server.jar took 2s 246ms at 21155 KB/s
    + result=0
    + '[' 0 '!=' 0 ']'
    + versionLessThan 1.6
    + mc-image-helper compare-versions 1.19.4 lt 1.6
    + return 1
    + [[ -L /data/minecraft_server.jar ]]
    + isDebugging
    + isTrue TRUE
    + case "${1,,}" in
    + return 0
    + return 0
    + ls -l
    total 46408
    -rw-rw-r-- 1 minecraft minecraft       68 Apr 23 08:12 eula.txt
    -rw-rw-r-- 1 minecraft minecraft 47515675 Apr 23 08:12 minecraft_server.1.19.4.jar
    + export FAMILY=VANILLA
    + FAMILY=VANILLA
    + exec /start-setupWorld
    + '[' VANILLA = CURSEFORGE ']'
    + worldDest=/data/world
    + [[ -n '' ]]
    + exec /start-setupVanillaTweaks
    + out_dir=/data/world/datapacks
    + isTrue false
    + case "${1,,}" in
    + return 1
    + [[ -n '' ]]
    + [[ -n '' ]]
    + exec /start-setupForgeApiMods
    + isTrue false
    + case "${1,,}" in
    + return 1
    + '[' '' ']'
    + '[' '' ']'
    + exec /start-setupModpack
    + CURSE_URL_BASE=https://minecraft.curseforge.com/projects
    + isTrue false
    + case "${1,,}" in
    + return 1
    + handlePackwiz
    + [[ -n '' ]]
    + handleModpackListOrFile
    + [[ -n '' ]]
    + [[ -n '' ]]
    + [[ -n '' ]]
    + handleCurseForgeManifest
    + [[ -n '' ]]
    + handleGenericPacks
    + : ''
    + : ''
    + : ''
    + [[ -n '' ]]
    + handleModrinthProjects
    + : ''
    + : true
    + : release
    + [[ -n '' ]]
    + exec /start-setupModconfig
    + isTrue true
    + case "${1,,}" in
    + return 0
    + updateArg=--skip-newer-in-destination
    + isTrue true
    + case "${1,,}" in
    + return 0
    + subcommand=sync-and-interpolate
    + : /plugins
    + : /data/plugins
    + '[' -d /plugins ']'
    + : /mods
    + : /data/mods
    + '[' -d /mods ']'
    + : /config
    + : /data/config
    + '[' -d /config ']'
    + exec /start-setupServerProperties
    [init] 2023-04-23 08:12:14+00:00 Creating server properties in /data/server.properties
    [init] 2023-04-23 08:12:14+00:00 Disabling whitelist functionality
    [init] 2023-04-23 08:12:14+00:00 DEBUG: Adding white-list with 'false' in /data/server.properties
    [init] 2023-04-23 08:12:14+00:00 DEBUG: Adding enable-rcon with 'true' in /data/server.properties
    [init] 2023-04-23 08:12:14+00:00 DEBUG: Adding rcon.password with '*****' in /data/server.properties
    [init] 2023-04-23 08:12:14+00:00 DEBUG: Adding rcon.port with '25575' in /data/server.properties
    [init] 2023-04-23 08:12:15+00:00 DEBUG: Adding motd with 'A Vanilla Minecraft Server powered by Docker' in /data/server.properties
    + versionLessThan 1.7.6
    + mc-image-helper compare-versions 1.19.4 lt 1.7.6
    + return 1
    + opsFile=ops.json
    + whitelistFile=whitelist.json
    + isTrue ''
    + case "${1,,}" in
    + return 1
    + '[' -n '' ']'
    + '[' -n '' ']'
    + isTrue ''
    + case "${1,,}" in
    + return 1
    + '[' -n '' ']'
    + '[' -n '' ']'
    + exec /start-finalExec
    + '[' -n '' ']'
    + canUseRollingLogs=true
    + useFallbackJvmFlag=false
    + versionLessThan 1.7
    + mc-image-helper compare-versions 1.19.4 lt 1.7
    + return 1
    + isFamily VANILLA
    + for f in "${@}"
    + [[ VANILLA == \V\A\N\I\L\L\A ]]
    + return 0
    + versionLessThan 1.12
    + mc-image-helper compare-versions 1.19.4 lt 1.12
    + return 1
    + isFamily VANILLA
    + for f in "${@}"
    + [[ VANILLA == \V\A\N\I\L\L\A ]]
    + return 0
    + versionLessThan 1.17
    + mc-image-helper compare-versions 1.19.4 lt 1.17
    + return 1
    + isType PURPUR
    + for t in "${@}"
    + [[ VANILLA == \P\U\R\P\U\R ]]
    + return 1
    + isType PURPUR
    + for t in "${@}"
    + [[ VANILLA == \P\U\R\P\U\R ]]
    + return 1
    + versionLessThan 1.18.1
    + mc-image-helper compare-versions 1.19.4 lt 1.18.1
    + return 1
    + false
    + isTrue false
    + case "${1,,}" in
    + return 1
    + versionLessThan 1.14
    + mc-image-helper compare-versions 1.19.4 lt 1.14
    + return 1
    + [[ '' = false ]]
    + expandedDOpts=
    + '[' -n '' ']'
    + isTrue ''
    + case "${1,,}" in
    + return 1
    + isTrue ''
    + case "${1,,}" in
    + return 1
    + isTrue ''
    + case "${1,,}" in
    + return 1
    + isTrue ''
    + case "${1,,}" in
    + return 1
    + isTrue ''
    + case "${1,,}" in
    + return 1
    + [[ -n 1G ]]
    + log 'Setting initial memory to 1G and max to 1G'
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:21+00:00 Setting initial memory to 1G and max to 1G
    + [[ -n 1G ]]
    + JVM_OPTS='-Xms1G '
    + [[ -n 1G ]]
    + JVM_OPTS='-Xmx1G -Xms1G '
    + mcServerRunnerArgs=(--stop-duration "${STOP_DURATION:-60}s" --named-pipe "${CONSOLE_IN_NAMED_PIPE:-/tmp/minecraft-console-in}")
    + [[ -n '' ]]
    + [[ VANILLA == \C\U\R\S\E\F\O\R\G\E ]]
    + [[ VANILLA == \C\U\R\S\E\F\O\R\G\E ]]
    + [[ minecraft_server.1.19.4.jar =~ run.sh ]]
    + '[' -f /data/bootstrap.txt ']'
    + log 'Starting the Minecraft server...'
    + local oldState
    ++ shopt -po xtrace
    + oldState='set -o xtrace'
    + shopt -u -o xtrace
    [init] 2023-04-23 08:12:21+00:00 Starting the Minecraft server...
    + finalArgs=($JVM_XX_OPTS $JVM_OPTS $expandedDOpts -jar "$SERVER" "$@" $EXTRA_ARGS)
    + isTrue false
    + case "${1,,}" in
    + return 1
    + isTrue false
    + case "${1,,}" in
    + return 1
    + isTrue false
    + case "${1,,}" in
    + return 1
    + exec mc-server-runner --stop-duration 60s --named-pipe /tmp/minecraft-console-in java -Xmx1G -Xms1G -jar minecraft_server.1.19.4.jar
    Unpacking 1.19.4/server-1.19.4.jar (versions:1.19.4) to versions/1.19.4/server-1.19.4.jar
    Unpacking com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar (libraries:com.github.oshi:oshi-core:6.2.2) to libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
    Unpacking com/google/code/gson/gson/2.10/gson-2.10.jar (libraries:com.google.code.gson:gson:2.10) to libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
    Unpacking com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar (libraries:com.google.guava:failureaccess:1.0.1) to libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
    Unpacking com/google/guava/guava/31.1-jre/guava-31.1-jre.jar (libraries:com.google.guava:guava:31.1-jre) to libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
    Unpacking com/mojang/authlib/3.18.38/authlib-3.18.38.jar (libraries:com.mojang:authlib:3.18.38) to libraries/com/mojang/authlib/3.18.38/authlib-3.18.38.jar
    Unpacking com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar (libraries:com.mojang:brigadier:1.0.18) to libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
    Unpacking com/mojang/datafixerupper/6.0.6/datafixerupper-6.0.6.jar (libraries:com.mojang:datafixerupper:6.0.6) to libraries/com/mojang/datafixerupper/6.0.6/datafixerupper-6.0.6.jar
    Unpacking com/mojang/logging/1.1.1/logging-1.1.1.jar (libraries:com.mojang:logging:1.1.1) to libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
    Unpacking commons-io/commons-io/2.11.0/commons-io-2.11.0.jar (libraries:commons-io:commons-io:2.11.0) to libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
    Unpacking io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar (libraries:io.netty:netty-buffer:4.1.82.Final) to libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
    Unpacking io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar (libraries:io.netty:netty-codec:4.1.82.Final) to libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
    Unpacking io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar (libraries:io.netty:netty-common:4.1.82.Final) to libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
    Unpacking io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar (libraries:io.netty:netty-handler:4.1.82.Final) to libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
    Unpacking io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar (libraries:io.netty:netty-resolver:4.1.82.Final) to libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
    Unpacking io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar (libraries:io.netty:netty-transport:4.1.82.Final) to libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
    Unpacking io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar (libraries:io.netty:netty-transport-classes-epoll:4.1.82.Final) to libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
    Unpacking io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar (libraries:io.netty:netty-transport-native-epoll:4.1.82.Final:linux-x86_64) to libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-x86_64.jar
    Unpacking io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar (libraries:io.netty:netty-transport-native-epoll:4.1.82.Final:linux-aarch_64) to libraries/io/netty/netty-transport-native-epoll/4.1.82.Final/netty-transport-native-epoll-4.1.82.Final-linux-aarch_64.jar
    Unpacking io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar (libraries:io.netty:netty-transport-native-unix-common:4.1.82.Final) to libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
    Unpacking it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar (libraries:it.unimi.dsi:fastutil:8.5.9) to libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
    Unpacking net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar (libraries:net.java.dev.jna:jna:5.12.1) to libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
    Unpacking net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar (libraries:net.java.dev.jna:jna-platform:5.12.1) to libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
    Unpacking net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar (libraries:net.sf.jopt-simple:jopt-simple:5.0.4) to libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
    Unpacking org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar (libraries:org.apache.commons:commons-lang3:3.12.0) to libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
    Unpacking org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar (libraries:org.apache.logging.log4j:log4j-api:2.19.0) to libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
    Unpacking org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar (libraries:org.apache.logging.log4j:log4j-core:2.19.0) to libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
    Unpacking org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar (libraries:org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0) to libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
    Unpacking org/joml/joml/1.10.5/joml-1.10.5.jar (libraries:org.joml:joml:1.10.5) to libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
    Unpacking org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar (libraries:org.slf4j:slf4j-api:2.0.1) to libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
    Starting net.minecraft.server.Main
    [08:12:31] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
    [08:12:33] [ServerMain/INFO]: Loaded 7 recipes
    [08:12:33] [ServerMain/INFO]: Loaded 1179 advancements
    [08:12:34] [Server thread/INFO]: Starting minecraft server version 1.19.4
    [08:12:34] [Server thread/INFO]: Loading properties
    [08:12:34] [Server thread/INFO]: Default game type: SURVIVAL
    [08:12:34] [Server thread/INFO]: Generating keypair
    [08:12:35] [Server thread/INFO]: Starting Minecraft server on *:25565
    [08:12:35] [Server thread/INFO]: Using epoll channel type
    [08:12:35] [Server thread/INFO]: Preparing level "world"
    [08:12:44] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
    [08:12:45] [Worker-Main-7/INFO]: Preparing spawn area: 0%
    [08:13:27] [Worker-Main-1/INFO]: Preparing spawn area: 99%
    [08:13:27] [Server thread/INFO]: Time elapsed: 43647 ms
    [08:13:27] [Server thread/INFO]: Done (52.519s)! For help, type "help"
    [08:13:27] [Server thread/INFO]: Starting remote control listener
    [08:13:27] [Server thread/INFO]: Thread RCON Listener started
    [08:13:27] [Server thread/INFO]: RCON running on 0.0.0.0:25575
    [08:13:45] [Server thread/INFO]: [Not Secure] [Server] text1 text2
</details>

**Comment by itzg** [comment]
Thanks for reporting this. Looked like I missed a layer of quotes.
