### ISSUE TITLE
Autopause function

### ISSUE THREAD

**Issue by woeisme** [itzg/docker-minecraft-server#2115]
I'm using the autopause feature successfully, however I notice in the logs endless wakeups from random access attempts (I'm runnning a user whitelist).  

Endless knock attempts from random IP's are sort of defeating the purpose of the pause, what would be a good way to mitigate this behaviour?

**Comment by itzg** [comment]
You will need to allow/restrict IP addresses at your internet router or some other routing point prior to the container. Any whitelisting within the Minecraft server won't help because...it has to be unpaused to process and block the connections.

**Comment by woeisme** [comment]
That´s unfortunately what I feared, is there a way to do container specific IP firewallling perhaps?

**Comment by woeisme** [comment]
I decided to switch away from docker iptables rules to ufw and opened the minecraft port for just the a single users IP using UFW. 
I'll test for the next few days to see if that cuts down on the random knocking.

**Comment by woeisme** [comment]
For those that would like to use UFW to solve this [please read this](https://github.com/chaifeng/ufw-docker)

I ended up limiting IP access at the router level.

**Comment by indykoning** [comment]
For the people where that may not be an option it might be cool to implement the likes of https://github.com/timvisee/lazymc
Which doesn't boot the server until a client actually tries to connect.
It gets rid of those pesky port scanners starting the server, but keeps the server accessible from any ip

**Comment by itzg** [comment]
Very interesting concept, @indykoning . I could use the https://github.com/itzg/mc-router/tree/master/mcproto bits and tie that into start/stop logic in https://github.com/itzg/mc-server-runner/tree/master ...
