### ISSUE TITLE
Restart should apply new environment variables

### ISSUE THREAD

**Issue by mikeyaworski** [itzg/docker-minecraft-server#2116]
### Enhancement Type

Not sure

### Describe the enhancement

Currently, if I change any of my environment variables within my `docker-compose.yaml` file and then restart the server with

```
docker-compose restart
```

the changed environment variables won't have an effect.

E.g. if I change the `VERSION` or `MEMORY` environment variable, the restarted server will continue to use my previous value.

So I'm forced to delete the image entirely, which feels unnecessary.

```
docker image rm itzg/minecraft-server
docker-compose up -d
```

If this is a bug, then I can provide more detailed information.

**Comment by itzg** [comment]
That's a docker usage problem. Make sure you're saving your compose file and use `docker compose up -d` to apply changes -- don't use restart.

**Comment by mikeyaworski** [comment]
Ah, I see. Thanks!

For future readers:

- `docker-compose restart` will not apply changes
- `docker-compose down && docker-compose up -d` will apply changes
- `docker-compose up -d` will apply changes

The container will not be recreated when you simply restart.

```
$ docker-compose restart
Restarting root_mc_1 ... done

$ docker-compose down && docker-compose up -d
Stopping root_mc_1 ... done
Removing root_mc_1 ... done
Removing network root_default
Creating network "root_default" with the default driver
Creating root_mc_1 ... done

$ docker-compose up -d
Recreating root_mc_1 ... done
```

**Comment by rhullah** [comment]
Also as an FYI: if you have changes in the compose file, you don't have to manually bring it down and then up.  Doing a `docker compose up` alone will know if the compose file has changed and if it needs to recreate the container.

**Comment by itzg** [comment]
They really should have named (or aliased) `up` as `apply`.
