### ISSUE TITLE
Add support for Launcher and Loader versions when using TYPE: MODRINTH

### ISSUE THREAD

**Issue by douglasparker** [itzg/docker-minecraft-server#2131]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Previously when creating a `TYPE: forge`, `TYPE: fabric`, `TYPE: quilt` Minecraft server, you had the ability to override launcher and loader versions using environmental variables.

i.e. `*_LAUNCHER_VERSION` and `*_LOADER_VERSION`, `FORGE_VERSION`, `FORGE_INSTALLER`, `FORGE_INSTALLER_URL`.

From what I understand, these variables do not work when using the new `TYPE: MODRINTH`.

I would like to see support added to `TYPE: MODRINTH` and possibly see these variable names standardized so it is less confusing.

I know backwards compatibility may be an issue, but hopefully anyone using the `latest` tag is watching releases on GitHub and should be informed of any breaking changes.

Just some suggestions that I think will make the project better! Thank you for all of the work you put into this project.

**Comment by itzg** [comment]
I was reviewing this issue and I don't think that it is valid. The types forge, fabric, and quilt are **modloader** types, where it absolutely makes sense to request certain versions of those modloaders (within the requested Minecraft version).

Modrinth is not a mod loader...it's a **modpack** type or a "mod platform" as of https://github.com/itzg/docker-minecraft-server/issues/2141, which was discussed in #2139 . As such, the modpack dictates the modloader type to be used including the specific version. The modpack needs to do that ensure compatibility with the included mods.

Please clarify this issue needs to be re-opened.
