### ISSUE TITLE
Curse-Forge sometimes has DNS-Issues (Retry on DNS-Issues)

### ISSUE THREAD

**Issue by denizkoekden** [itzg/docker-minecraft-server#2133]
### Describe the problem

When starting Auto-Curseforge sometimes while downloading the Files I get the following Error:

`[|[0m[mc-image-helper]11:39:57.262INFO:Downloadedmodfilemods/Adorn-3.8.1+1.19.2-fabric.jar

[|[0m[mc-image-helper]11:39:57.577INFO:Downloadedmodfilemods/DungeonsArise-1.19.2-2.1.54-fabric.jar

[|[0m[mc-image-helper]11:39:57.627INFO:Downloadedmodfilemods/snowyspirit-1.19.2-2.1.7-fabric.jar

[|[0m[mc-image-helper]11:39:57.631INFO:Downloadedmodfilemods/meadow-1.1.1-1.19.jar

[|[0m[mc-image-helper]11:39:57.659INFO:Downloadedmodfilemods/biomemakeover-FABRIC-1.19.2-1.6.2.jar

[|[0m[mc-image-helper]11:39:57.734INFO:Downloadedmodfilemods/DramaticDoors-Fabric-1.19.2-1.4.2_1.jar

[|[0m[mc-image-helper]11:39:57.748INFO:Downloadedmodfilemods/bygonenether-1.19-1.2.2.jar

[|[0m[mc-image-helper]11:39:57.828INFO:Downloadedmodfilemods/the_bumblezone_fabric-6.6.17+1.19.2.jar

[|[0m[mc-image-helper]11:39:57.836INFO:Downloadedmodfilemods/supplementaries-1.19.2-2.2.57-fabric.jar

[|[0m[mc-image-helper]11:39:57.844INFO:Downloadedmodfilemods/repurposed_structures_fabric-6.3.16+1.19.2.jar

[|[0m[mc-image-helper]11:39:57.857INFO:Downloadedmodfilemods/fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar

[|[0m[mc-image-helper]11:39:57.952INFO:Downloadedmodfilemods/cinderscapes-3.0.3.jar

[|[0m[mc-image-helper]11:39:58.206INFO:Downloadedmodfilemods/deeperdarker-fabric-1.1.6-fabric.jar

[|[0m[mc-image-helper]11:39:58.612INFO:Downloadedmodfilemods/Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13.jar

[|[0m[mc-image-helper]11:39:58.724INFO:Downloadedmodfilemods/eden-ring-0.6.4.jar

[|[0m[mc-image-helper]11:39:58.998INFO:Downloadedmodfilemods/paradise-lost-2.0.2-beta+1.19.2.jar

[|[0m[mc-image-helper]11:39:59.024INFO:Downloadedmodfilemods/charmonium-fabric-1.19.2-4.2.1.jar

[|[0m[mc-image-helper]11:39:59.466INFO:Downloadedmodfilemods/better-end-2.1.4.jar

[|[0m[mc-image-helper]11:39:59.852ERROR:'install-curseforge'commandfailed.Versionis1.27.5

[|[0mreactor.core.Exceptions$ReactiveException:java.net.UnknownHostException:Failedtoresolve'mediafilez.forgecdn.net'[A(1)]

[|[0matreactor.core.Exceptions.propagate(Exceptions.java:408)

[|[0matreactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)

[|[0matreactor.core.publisher.Mono.block(Mono.java:1710)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.processModpack(CurseForgeInstaller.java:430)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.resolveModpackFileAndProcess(CurseForgeInstaller.java:316)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.installByRetrievingModpackZip(CurseForgeInstaller.java:197)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.lambda$install$4(CurseForgeInstaller.java:131)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:166)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:130)

[|[0matme.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:187)

[|[0matme.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:24)

[|[0matpicocli.CommandLine.executeUserObject(CommandLine.java:2041)

[|[0matpicocli.CommandLine.access$1500(CommandLine.java:148)

[|[0matpicocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)

[|[0matpicocli.CommandLine$RunLast.handle(CommandLine.java:2453)

[|[0matpicocli.CommandLine$RunLast.handle(CommandLine.java:2415)

[|[0matpicocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)

[|[0matpicocli.CommandLine$RunLast.execute(CommandLine.java:2417)

[|[0matpicocli.CommandLine.execute(CommandLine.java:2170)

[|[0matme.itzg.helpers.McImageHelper.main(McImageHelper.java:131)

[|[0mSuppressed:java.lang.Exception:#blockterminatedwithanerror

[|[0matreactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)

[|[0m...18commonframesomitted

[|[0mCausedby:java.net.UnknownHostException:Failedtoresolve'mediafilez.forgecdn.net'[A(1)]

[|[0matio.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1088)

[|[0matio.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1035)

[|[0matio.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:422)

[|[0matio.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66)

[|[0matio.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:493)

[|[0matio.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)

[|[0matio.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)

[|[0matio.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)

[|[0matio.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)

[|[0matio.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)

[|[0matio.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)

[|[0matio.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)

[|[0matio.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:261)

[|[0matio.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:208)

[|[0matio.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)

[|[0matio.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)

[|[0matio.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

[|[0matio.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)

[|[0matio.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)

[|[0matio.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)

[|[0matio.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

[|[0matio.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

[|[0matio.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

[|[0matjava.base/java.lang.Thread.run(UnknownSource)

[|[0mCausedby:io.netty.resolver.dns.DnsNameResolverTimeoutException:[13211:/127.0.0.11:53]DefaultDnsQuestion(mediafilez.forgecdn.net.INA)query'13211'viaUDPtimedoutafter5000milliseconds(nostacktraceavailable)

[|[0m[init]ERRORfailedtoauto-installCurseForgemodpack
`

So I guess the Script can not resolve mediafilez.forgecdn.net via DNS and sometimes it can. Regardless it would be great if the Script retries it a few times until it works.

### Container definition

```
   environment:
      TYPE: "AUTO_CURSEFORGE"
      OVERRIDE_SERVER_PROPERTIES: "false"
      EULA: "TRUE"
      CF_SLUG: "medieval-mc-fabric"
      CF_FILE_ID: 4434948
      CF_API_KEY: "NOPE"
      GUI: "FALSE"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "8G"
      USE_AIKAR_FLAGS: "true"
      JVM_XX_OPTS: "-XX:+UseG1GC"
      CF_EXCLUDE_INCLUDE_FILE: "My Own URL HERE"
      CF_FORCE_SYNCHRONIZE: "true"
      FORCE_REDOWNLOAD: "true"
```

### Container logs

```
[|[0m[mc-image-helper]11:39:57.262INFO:Downloadedmodfilemods/Adorn-3.8.1+1.19.2-fabric.jar

[|[0m[mc-image-helper]11:39:57.577INFO:Downloadedmodfilemods/DungeonsArise-1.19.2-2.1.54-fabric.jar

[|[0m[mc-image-helper]11:39:57.627INFO:Downloadedmodfilemods/snowyspirit-1.19.2-2.1.7-fabric.jar

[|[0m[mc-image-helper]11:39:57.631INFO:Downloadedmodfilemods/meadow-1.1.1-1.19.jar

[|[0m[mc-image-helper]11:39:57.659INFO:Downloadedmodfilemods/biomemakeover-FABRIC-1.19.2-1.6.2.jar

[|[0m[mc-image-helper]11:39:57.734INFO:Downloadedmodfilemods/DramaticDoors-Fabric-1.19.2-1.4.2_1.jar

[|[0m[mc-image-helper]11:39:57.748INFO:Downloadedmodfilemods/bygonenether-1.19-1.2.2.jar

[|[0m[mc-image-helper]11:39:57.828INFO:Downloadedmodfilemods/the_bumblezone_fabric-6.6.17+1.19.2.jar

[|[0m[mc-image-helper]11:39:57.836INFO:Downloadedmodfilemods/supplementaries-1.19.2-2.2.57-fabric.jar

[|[0m[mc-image-helper]11:39:57.844INFO:Downloadedmodfilemods/repurposed_structures_fabric-6.3.16+1.19.2.jar

[|[0m[mc-image-helper]11:39:57.857INFO:Downloadedmodfilemods/fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar

[|[0m[mc-image-helper]11:39:57.952INFO:Downloadedmodfilemods/cinderscapes-3.0.3.jar

[|[0m[mc-image-helper]11:39:58.206INFO:Downloadedmodfilemods/deeperdarker-fabric-1.1.6-fabric.jar

[|[0m[mc-image-helper]11:39:58.612INFO:Downloadedmodfilemods/Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.0.13.jar

[|[0m[mc-image-helper]11:39:58.724INFO:Downloadedmodfilemods/eden-ring-0.6.4.jar

[|[0m[mc-image-helper]11:39:58.998INFO:Downloadedmodfilemods/paradise-lost-2.0.2-beta+1.19.2.jar

[|[0m[mc-image-helper]11:39:59.024INFO:Downloadedmodfilemods/charmonium-fabric-1.19.2-4.2.1.jar

[|[0m[mc-image-helper]11:39:59.466INFO:Downloadedmodfilemods/better-end-2.1.4.jar

[|[0m[mc-image-helper]11:39:59.852ERROR:'install-curseforge'commandfailed.Versionis1.27.5

[|[0mreactor.core.Exceptions$ReactiveException:java.net.UnknownHostException:Failedtoresolve'mediafilez.forgecdn.net'[A(1)]

[|[0matreactor.core.Exceptions.propagate(Exceptions.java:408)

[|[0matreactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:97)

[|[0matreactor.core.publisher.Mono.block(Mono.java:1710)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.processModpack(CurseForgeInstaller.java:430)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.resolveModpackFileAndProcess(CurseForgeInstaller.java:316)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.installByRetrievingModpackZip(CurseForgeInstaller.java:197)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.lambda$install$4(CurseForgeInstaller.java:131)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:166)

[|[0matme.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:130)

[|[0matme.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:187)

[|[0matme.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:24)

[|[0matpicocli.CommandLine.executeUserObject(CommandLine.java:2041)

[|[0matpicocli.CommandLine.access$1500(CommandLine.java:148)

[|[0matpicocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)

[|[0matpicocli.CommandLine$RunLast.handle(CommandLine.java:2453)

[|[0matpicocli.CommandLine$RunLast.handle(CommandLine.java:2415)

[|[0matpicocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)

[|[0matpicocli.CommandLine$RunLast.execute(CommandLine.java:2417)

[|[0matpicocli.CommandLine.execute(CommandLine.java:2170)

[|[0matme.itzg.helpers.McImageHelper.main(McImageHelper.java:131)

[|[0mSuppressed:java.lang.Exception:#blockterminatedwithanerror

[|[0matreactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)

[|[0m...18commonframesomitted

[|[0mCausedby:java.net.UnknownHostException:Failedtoresolve'mediafilez.forgecdn.net'[A(1)]

[|[0matio.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1088)

[|[0matio.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1035)

[|[0matio.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:422)

[|[0matio.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66)

[|[0matio.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:493)

[|[0matio.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)

[|[0matio.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)

[|[0matio.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)

[|[0matio.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)

[|[0matio.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)

[|[0matio.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)

[|[0matio.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)

[|[0matio.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:261)

[|[0matio.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:208)

[|[0matio.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)

[|[0matio.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)

[|[0matio.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)

[|[0matio.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)

[|[0matio.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)

[|[0matio.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)

[|[0matio.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)

[|[0matio.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

[|[0matio.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

[|[0matjava.base/java.lang.Thread.run(UnknownSource)

[|[0mCausedby:io.netty.resolver.dns.DnsNameResolverTimeoutException:[13211:/127.0.0.11:53]DefaultDnsQuestion(mediafilez.forgecdn.net.INA)query'13211'viaUDPtimedoutafter5000milliseconds(nostacktraceavailable)

[|[0m[init]ERRORfailedtoauto-installCurseForgemodpack```

**Comment by itzg** [comment]
I am not going to implement logic to handle DNS issues. Please fix your system.

**Comment by denizkoekden** [comment]
I tried providing dns to the compose file but sometimes it can resolve the url and sometimes not. What is weird is, that the previous mod-files can be downloaded and only the last not and sometimes it works. So this is weird. I just thought that retrying to resolve/download it more than one time should fix issues like this. DNS is working fine on the host system. It can resolve  mediafilez.forgecdn.net. Maybe you have an Idea what the issue is?

**Comment by itzg** [comment]
It's not super elegant but perhaps try simply restarting the whole host. Seems like I have heard that fixing weird, random network issues. 

BTW some brief context: retrying DNS related operations is not trivial since the JVM prefers to cache lookups, rightly so. Doing a retry logic would involve disabling that caching and degrading performance for all users. 

Perhaps ask around on [the Discord server](https://discord.gg/DXfKpjB).

**Comment by denizkoekden** [comment]
Thanks! 😅
