### ISSUE TITLE
Add support for unpublished CurseForge Profile Modpack Exports

### ISSUE THREAD

**Issue by douglasparker** [itzg/docker-minecraft-server#2136]
### Enhancement Type

A completely new feature

### Describe the enhancement

Maybe I am missing something, but I was unable to get custom profile modpack exports to work.

It seems the only way is to publish a modpack, which in this case I want to avoid the approval workflow and just upload the zip to the server and distribute the zip for clients.

This export doesn't export jar files, it seems to export a `manifest.json` that tells you what to download from CurseForge.

I'd like to see both `CF_MODPACK_ZIP` and `CF_MODPACK_MANIFEST` work for unpublished modpack exports.

More info:
- https://support.curseforge.com/en/support/solutions/articles/9000196904-creating-a-custom-profile
- https://support.curseforge.com/en/support/solutions/articles/9000197912

**Comment by itzg** [comment]
That is already supported. Manifest file alone or zipped up like a published one.

**Comment by douglasparker** [comment]
> That is already supported. Manifest file alone or zipped up like a published one.

I was trying with `TYPE: "CURSEFORGE"` and `CF_SERVER_MOD: "/modpacks/Cobblemon-0.0.1.zip"` and was receiving the following output:

```sh
root@joofy:/docker/minecraft# docker logs cobblemon-forge -f
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 11 1000 1000 4096 May 18 08:03 /data'
[init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] Unpacking FTB server modpack /modpacks/Cobblemon-0.0.1.zip ...
........
[init] ERROR: Modpack missing start script and unable to find Forge jar to generate one
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 11 1000 1000 4096 May 18 08:03 /data'
[init] Resolved version given 1.19.2 into 1.19.2 and major version 1.19
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] Unpacking FTB server modpack /modpacks/Cobblemon-0.0.1.zip ...
........
[init] ERROR: Modpack missing start script and unable to find Forge jar to generate one
```

I also tried using `TYPE: forge` with `GENERIC_PACKS` without success.

Could you please direct me to the correct usage? Thank you so much.

**Comment by itzg** [comment]
You must use <https://github.com/itzg/docker-minecraft-server#auto-curseforge-management>. I do not actively support the old way -- it was a maintenance nightmare.

**Comment by douglasparker** [comment]
> You must use https://github.com/itzg/docker-minecraft-server#auto-curseforge-management. I do not actively support the old way -- it was a maintenance nightmare.

Can you confirm that a published modpack is required for this to work? See edit 2 in my original post.

**Comment by itzg** [comment]
If you want to experiment, use TYPE=AUTO_CURSEFORGE approach, with your manifest, but just give it a fake slug value. Without looking through the code yet, I think it needed that just to just be some stable value to track install state.

**Comment by douglasparker** [comment]
> If you want to experiment, use TYPE=AUTO_CURSEFORGE approach, with your manifest, but just give it a fake slug value. Without looking through the code yet, I think it needed that just to just be some stable value to track install state.

Using a fake slug worked for me! Thank you for recommending that!

I'll keep this issue open so that way you can remove the slug requirement in the future. :)

**Comment by itzg** [comment]
> I'll keep this issue open so that way you can remove the slug requirement in the future. :)

Agreed. It's a little quirky because surprisingly there's no kind of identifier within the manifest that can be used to determine if an update to the same unpublished modpack or a different modpack is being installed. Do you think using the given manifest/zip filename would be a decent slug-substitute?

**Comment by douglasparker** [comment]
> > I'll keep this issue open so that way you can remove the slug requirement in the future. :)
> 
> Agreed. It's a little quirky because surprisingly there's no kind of identifier within the manifest that can be used to determine if an update to the same unpublished modpack or a different modpack is being installed. Do you think using the given manifest/zip filename would be a decent slug-substitute?

I personally think the hash of the manifest / zip might be better and more reliable. 😅

**Comment by itzg** [comment]
I was thinking that too, but it needs to be an identifier that stays the same across versions. Speaking of which, I do have it generate a fileId (i.e. the version) by hashing the mod file references.

**Comment by douglasparker** [comment]
> I was thinking that too, but it needs to be an identifier that stays the same across versions.

Well, in the case of curseforge exports, the zip file always has the version in it- so that is always changing. I believe the manifest inside of the zip is always `manifest.json`.

It might be worth using a random uuid for unpublished exports, especially since you generate a fileId anyways. Unless I am misunderstanding, it sounds like them slug wouldn't have much of a use in this case.

**Comment by jcotton42** [comment]
I'm commenting to indicate my interest in this feature as well. I have some light modifications to a published modpack I want to use on my server, but don't want to upload the modified version to Curse.

**Comment by itzg** [comment]
@jcotton42 in your case you'll set `CF_MODPACK_MANIFEST` (or the zip variant) to the local path of your modified modpack file. Set `CF_SLUG` to the same as the published one.

**Comment by itzg** [comment]
[Docs](https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#unpublished-modpacks) have been updated and [full example](https://github.com/itzg/docker-minecraft-server/tree/master/examples/auto-cf/modpack-manifest) added.

Resolved by https://github.com/itzg/docker-minecraft-server/pull/2582
