### ISSUE TITLE
The README is massive. Consider moving configuration docs to their own files

### ISSUE THREAD

**Issue by benjamin051000** [itzg/docker-minecraft-server#2138]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

The README appears to have detailed information about every configuration possible with this project. While the detailed docs are appreciated, it makes it difficult to at-a-glance understand the high-level features/capabilities of the project.

Would it be better if fine-grain details about configurations were moved to their own separate file, with links provided from the README? I'm just wondering if there's a better way to organize all this information. Thanks.

**Comment by itzg** [comment]
This is already done, 

https://itzg.github.io/docker-minecraft-docs/

but I am thinking through ongoing maintenance and if each image docs should reside in each repo.

**Comment by itzg** [comment]
Now imported to https://docker-minecraft-server.readthedocs.io/
