### ISSUE TITLE
Provide support for installing local Modrinth modpack files

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#2144]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

From an mrpack[mrpack](https://docs.modrinth.com/docs/modpacks/format_definition/#storage) or just the `modrinth.index.json`

**Comment by SirBastol** [comment]
this would be great. since it already pulls the modrinth stuff from the site.. :) but to be able to be local  handy for the modpackt that can't be posted publicly.
