### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by uhthomas** [itzg/docker-minecraft-server#2173]
### Describe the problem

Hey!

The current release is 2023.3.0, released on April 7th. Would it be possible to make a new release for major fixes like https://github.com/itzg/docker-minecraft-server/pull/2106? I was quite confused as the live documentation says this should work, but the latest tagged version doesn't actually include this change.

### Container definition

N/A

### Container logs

N/A

**Comment by itzg** [comment]
Released https://github.com/itzg/docker-minecraft-server/releases/tag/2023.4.0

**Comment by uhthomas** [comment]
> Released https://github.com/itzg/docker-minecraft-server/releases/tag/2023.4.0

Awesome! Thanks

**Comment by itzg** [comment]
I should really get in the habit of at least creating a release per month, so thank you for poking me on releases.
