### ISSUE TITLE
docs(rcon): default password is not "minecraft"

### ISSUE THREAD

**Issue by uhthomas** [itzg/docker-minecraft-server#2180]
### Describe the problem

The documentation states:

>The default password is "minecraft" but change the password before deploying into production by setting RCON_PASSWORD.

It looks like this was changed in https://github.com/itzg/docker-minecraft-server/pull/2071.

### Container definition

N/A

### Container logs

N/A

**Comment by itzg** [comment]
Thanks. A PR would be great.
