### ISSUE TITLE
Cannot Pull Docker Image 2023.4.0

### ISSUE THREAD

**Issue by barrelmaker97** [itzg/docker-minecraft-server#2183]
### Describe the problem

The tag for the latest image, 2023.4.0, does not seem to exist. I see all the other docker tags with the different java versions, as well as latest. However, the tag for just the version and nothing else does not appear to exist on Docker Hub or GitHub Container Registry. Both fail with a manifest unknown error:
```
barrelmaker@pollux:~$ docker pull docker.io/itzg/minecraft-server:2023.4.0
Error response from daemon: manifest for itzg/minecraft-server:2023.4.0 not found: manifest unknown: manifest unknown

barrelmaker@pollux:~$ docker pull ghcr.io/itzg/minecraft-server:2023.4.0
Error response from daemon: manifest unknown
```

Has this tag type been accidentally left off, or is this change intentional?

**Comment by itzg** [comment]
If it's missing, then not intentional. Thanks for letting me know.

**Comment by itzg** [comment]
Latest build now pushes the "primary" tag of 2023.4.1 correctly

https://hub.docker.com/repository/docker/itzg/minecraft-server/tags?page=1&ordering=last_updated&name=2023.4.1

**Comment by barrelmaker97** [comment]
Thank you! Image pulling properly now 👍🏻
