### ISSUE TITLE
docs: typo in building.md (changing image's java base)

### ISSUE THREAD

**Issue by scotus-1** [itzg/docker-minecraft-server#2219]
https://github.com/itzg/docker-minecraft-server/blob/6359b5ce4232c33cd79ccf3fab2a649cff671480/docs/misc/contributing/building.md?plain=1#LL7C31-L7C32

```shell
docker build --build-arg BASE_IMG=ghcr.io/graalvm/graalvm-ce:ol8-java11 -t IMG_PREFIX/minecraft-server:java11-graalvm .
```

The example line given (above) to change the base image for the minecraft-server image has an error as the line contains `BASE_IMG`.
It should be `BASE_IMAGE`, I got caught up on it for around 30 mins and I didn't want anyone else to as well. I tried changing the image to the GraavlVM enterprise edition, so that's why. Thank you!

**Comment by itzg** [comment]
Thanks, that is indeed the wrong variable.
