### ISSUE TITLE
Feature Request: Example in Docs, Vanilla Server Spin-up Walkthrough

### ISSUE THREAD

**Issue by rela-v** [itzg/docker-minecraft-server#2222]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I recently used this project to spin up a Vanilla Minecraft server with the latest updates, and while I must say the tool is performant and quite easy to use, the documentation felt lacking in terms of its inclusion of useful complete examples: from nothing to a server, step by step, making the process exceedingly longer than it needed to be (for my part: I think that even inexperienced users should be able to access and use this great project, and I hope the lack of a complete example wouldn't stop them!). 

I would be happy to write this complete example walkthrough, including some stubs/minimal starting information on setting static IP, port forwarding, and security measures with regards to the actual server setup, and of course some information on how to use docker, how to write an effective configuration.yml, and how to then spin up the server.

I can go ahead and start working on this - in the meantime, feel free to assign me the issue if so desired, and I can submit a PR.

- Rela

**Comment by itzg** [comment]
...regarding static IP, port forwarding, etc it would be great if you added a link from the intro page over to a new page under https://github.com/itzg/docker-minecraft-server/tree/master/docs/misc/deployment
