### ISSUE TITLE
Readthedocs is messed up 

### ISSUE THREAD

**Issue by mraarone** [itzg/docker-minecraft-server#2230]
### Describe the problem

Since this last weekend's cyber attack on AWS, or maybe earlier but likely this weekend, your docs are messed up on RTDs. May way to re-push the documents after you verify this issue by navigating the documents on RTDs.

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
I'm not sure what you mean. The docs are fine

https://docker-minecraft-server.readthedocs.io/
