### ISSUE TITLE
Auto download using -e MODS_FILE causes 'mcopy' to fail since 2023.6.1 update

### ISSUE THREAD

**Issue by Ranoth** [itzg/docker-minecraft-server#2232]
### Describe the problem

Since I updated the image to the latest version, plugins which worked with exactly the same configuration as before I pulled the new version now stop the container from finishing the server startup.
Specifically the latest versions of [World Edit](https://dev.bukkit.org/projects/worldedit) and [No Mob Griefing](https://dev.bukkit.org/projects/no-mob-griefing).

### Container definition

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20"
      # VERSION: "1.19.4"
      MAX_TICK_TIME: "-1"
      MAX_MEMORY: "12G"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
      SPIGET_RESOURCES: "74208"
      MODRINTH_PROJECTS: "chunky"
      MODS_FILE: "/data/mods.txt"
      REMOVE_OLD_MODS: "TRUE"
      REMOVE_OLD_MODS_EXCLUDE: ""
      OPS: "Ranoth"
      WHITELIST: "Ranoth, Aucyus"
    volumes:
      - ./minecraftData:/data
    mem_limit: 12G
    cpus: 12
    tty: true
    stdin_open: true
    restart: unless-stopped

### My mods.txt file
[mods.txt](https://github.com/itzg/docker-minecraft-server/files/11780574/mods.txt)

### Container logs

[runtime-2023-06-18_05h06m56s.log](https://github.com/itzg/docker-minecraft-server/files/11780555/runtime-2023-06-18_05h06m56s.log)
[runtime-2023-06-18_05h08m16s.log](https://github.com/itzg/docker-minecraft-server/files/11780556/runtime-2023-06-18_05h08m16s.log)
[runtime-2023-06-18_05h09m22s.log](https://github.com/itzg/docker-minecraft-server/files/11780557/runtime-2023-06-18_05h09m22s.log)
[runtime-2023-06-18_05h04m10s.log](https://github.com/itzg/docker-minecraft-server/files/11780558/runtime-2023-06-18_05h04m10s.log)
[runtime-2023-06-18_05h06m06s.log](https://github.com/itzg/docker-minecraft-server/files/11780559/runtime-2023-06-18_05h06m06s.log)

**Comment by itzg** [comment]
Thanks for reporting this. I'm looking into it now.

**Comment by guigoruiz1** [comment]
Hello, I am having the same issue with the latest image
