### ISSUE TITLE
PR #2225 Includes Broken Link in Docs Intro Page

### ISSUE THREAD

**Issue by rela-v** [itzg/docker-minecraft-server#2233]
### Describe the problem

First of all, sorry in advance - this is a problem of my own creation. In https://github.com/itzg/docker-minecraft-server/pull/2225, I created a link page in the Deployment index.md which included a link to a tutorial that I created and posted in a dev.to article. 

In a previous iteration of the same PR, I added a note with a link to a page *in the docs* which would've hosted that tutorial. I forgot to take that out and now that note includes a completely broken link.

I'd be happy to fix that, I'll add a PR which changes it so that the note is deleted in its entirety, if that is permissible.

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
No problem at all. Yeah, a PR would be great.

**Comment by itzg** [comment]
...actually, I'm about to make a change to the repo, so I'll fix this while I'm in here.
