### ISSUE TITLE
rcon-cli prefixing all responses with "Using config file: /root/.rcon-cli.env"

### ISSUE THREAD

**Issue by ThomWilhelm** [itzg/docker-minecraft-server#2257]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I've previously written some scripts to process the response of rcon-cli commands such as the following:

**kubectl exec job/minecraft-server -- rcon-cli weather rain**

Previously this command would just return the result of the command eg:

_Set the weather to rain_

However now all rcon-cli commands are now displaying a line displaying the config file being used.

_Using config file: /root/.rcon-cli.env
Set the weather to rain_

I tried to figure out where this line is coming from but no luck, is there any way to disable this? It makes processing responses programmatically quite painful

**Comment by ThomWilhelm** [comment]
OK so it's obviously a line in the itzg/rcon-cli repo, which has actually been there since it's initial commit.

https://github.com/itzg/rcon-cli/blob/803bf2de3617f8c059a0824dd21453f67a91d299/cmd/root.go#L101

Imo this kind message is more of a debugging message, and doesn't belong on every usage of the command. But happy to take direction from the maintainer as everyone has a different opinion here.

**Comment by itzg** [comment]
Agreed, that can be removed. Go's built in logging is crap and they don't have logging levels.

**Comment by ThomWilhelm** [comment]
Really appreciate that change thank you.
