### ISSUE TITLE
Minecraft forge server not running forge

### ISSUE THREAD

**Issue by V3RA8D** [itzg/docker-minecraft-server#227]
My minecraft forge server isn't running forge, it shows up as a normal vanilla server on my sever list.
I have already reinstalled 2ce, I don't know what to do.
Here's a picture of the server when it first starts up, and my server folder.
![serverproblems](https://user-images.githubusercontent.com/41269964/42736899-cbe04506-883b-11e8-9a98-7663612faa4f.PNG)

**Comment by V3RA8D** [comment]
I'm also running windows 7

**Comment by itzg** [comment]
Can you provide the `docker run` command line you’re usingn or at least the environment variables you’re passing?
