### ISSUE TITLE
Minecraft - Question/feature

### ISSUE THREAD

**Issue by tjsd** [itzg/docker-minecraft-server#228]
With the FORGE enabled you can specify the forge version you want to run. Is it possible to point it to a local forge in the data directory instead?
Like I usually manage the forge version myself and just ln the forge to a generic name like minecraft_forge.jar

So if I could do like -e FORGEFILE=minecraft_forge.jar
I could totally manage the forge versions myself. Is that possible to implement? or is there already a way to do this that I just cant see?

**Comment by itzg** [comment]
I had forgotten this feature existed, but yes you can pass a `FORGE_INSTALLER` variable to point at your managed jar. It can either be a path relative to the container's `/data` or an absolute path if you want to manage that via a volume attachment of your choosing. I'd actually recommend the latter where you could do:

```
docker run ... -v myForgeInstallers:/forge -e FORGE_INSTALLER=/forge/minecraft_forge.jar ...
``` 

That and a `FORGE_INSTALLER_URL` option are documented here
https://github.com/itzg/dockerfiles/blob/master/minecraft-server/README.md#running-a-forge-server

**Comment by tjsd** [comment]
The confusion for me here was that you call it installer, so that is for me the jar that actually installs forge. The complete version of forge is called universal. 
I should have just tested it with the symlinked file :)

**Comment by itzg** [comment]
You're 2 for 2 :). You're right that points at the installer and not the final forge jar. I'll plan on adding an option like `FORGEFILE`...or maybe `FORGE_FILE` to be consistent with other variables.

**Comment by itzg** [comment]
I just checked and the forge installer also takes care of downloading jars into the `libraries` directory, so I'm thinking it's more robust to point the start script at a specific installer rather than the final, universal jar file. Here's the jars I found in the `libraries` directory:

```
bash-4.4$ find libraries/ -name '*.jar'
libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
libraries/jline/jline/2.13/jline-2.13.jar
```

**Comment by itzg** [comment]
@tjsd did you feel like this issue is still valid given my comment about forge consisting of more than just the expanded universal jar?
