### ISSUE TITLE
Automatically handle "latest" bukkit url when downloading via PLUGINS

### ISSUE THREAD

**Issue by nmistry** [itzg/docker-minecraft-server#2299]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

WorldEdit latest can be downloaded via the latest link on bukkit's website.    Unfortunately the URL does not redirect properly, leaving the file "latest" in the /plugins directory.   This request is to add support for this (and possibly other urls like it.

Testing was done against the following container image version:
```
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
itzg/minecraft-server   latest    2b05b286719e   2 days ago     840MB
```

Below is the  docker-compose.yaml config excerpt. 

```
      PLUGINS: |
        https://dev.bukkit.org/projects/worldedit/files/latest
```

Running curl against the URL shows the redirect to forgecdn with the correct filename. 

```
curl -v https://dev.bukkit.org/projects/worldedit/files/latest 2>&1 | grep location
< location: https://edge.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar?api-key=267C6CA3
``` 

In the event that you are using `wget` to pull the URLS, adding the parameter `--content-disposition` renames file redirects if specified by the url provider.   In the example of worldedit / bukkit you can see the difference that this parameter makes:

```
➜  /tmp wget https://dev.bukkit.org/projects/worldedit/files/latest
--2023-07-17 22:06:55--  https://dev.bukkit.org/projects/worldedit/files/latest
Resolving dev.bukkit.org (dev.bukkit.org)... 104.19.146.132, 104.19.147.132, 2606:4700::6813:9384, ...
Connecting to dev.bukkit.org (dev.bukkit.org)|104.19.146.132|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://edge.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar?api-key=267C6CA3 [following]
--2023-07-17 22:06:55--  https://edge.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar?api-key=267C6CA3
Resolving edge.forgecdn.net (edge.forgecdn.net)... 34.232.167.69, 107.20.23.99
Connecting to edge.forgecdn.net (edge.forgecdn.net)|34.232.167.69|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://mediafilez.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar [following]
--2023-07-17 22:06:55--  https://mediafilez.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar
Resolving mediafilez.forgecdn.net (mediafilez.forgecdn.net)... 18.165.98.7, 18.165.98.65, 18.165.98.95, ...
Connecting to mediafilez.forgecdn.net (mediafilez.forgecdn.net)|18.165.98.7|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6395168 (6.1M) [application/java-archive]
Saving to: ‘latest’

latest                                     100%[======================================================================================>]   6.10M  --.-KB/s    in 0.05s

2023-07-17 22:06:55 (123 MB/s) - ‘latest’ saved [6395168/6395168]

➜  /tmp wget --content-disposition https://dev.bukkit.org/projects/worldedit/files/latest
--2023-07-17 22:07:09--  https://dev.bukkit.org/projects/worldedit/files/latest
Resolving dev.bukkit.org (dev.bukkit.org)... 104.19.146.132, 104.19.147.132, 2606:4700::6813:9384, ...
Connecting to dev.bukkit.org (dev.bukkit.org)|104.19.146.132|:443... connected.
HTTP request sent, awaiting response... 307 Temporary Redirect
Location: https://edge.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar?api-key=267C6CA3 [following]
--2023-07-17 22:07:09--  https://edge.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar?api-key=267C6CA3
Resolving edge.forgecdn.net (edge.forgecdn.net)... 107.20.23.99, 34.232.167.69
Connecting to edge.forgecdn.net (edge.forgecdn.net)|107.20.23.99|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://mediafilez.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar [following]
--2023-07-17 22:07:09--  https://mediafilez.forgecdn.net/files/4586/220/worldedit-bukkit-7.2.15.jar
Resolving mediafilez.forgecdn.net (mediafilez.forgecdn.net)... 18.165.98.63, 18.165.98.95, 18.165.98.65, ...
Connecting to mediafilez.forgecdn.net (mediafilez.forgecdn.net)|18.165.98.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6395168 (6.1M) [application/java-archive]
Saving to: ‘worldedit-bukkit-7.2.15.jar’

worldedit-bukkit-7.2.15.jar                100%[======================================================================================>]   6.10M  --.-KB/s    in 0.06s

2023-07-17 22:07:09 (99.8 MB/s) - ‘worldedit-bukkit-7.2.15.jar’ saved [6395168/6395168]
```

**Comment by itzg** [comment]
It works fine for https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot by following the redirect and looking at content disposition. I'll have to implement the specific difference you noted with theirs.

**Comment by itzg** [comment]
...so how does `wget` "ask" for content-disposition? I don't see it coming from any of the headers, so all I can presume is that wget is overcoming file providers by assuming the filename in the last URL is like the [`filename` part of an attachment content-disposition](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#directives).

**Comment by itzg** [comment]
I did some initial investigation and to do what wget is doing the implementation will be forced to re-download the requested file every single time even if it already exists locally. It is the `HEAD` request that Forge CDN is not correctly supporting, which is what gives the download logic the ability to resolve the final filename via a content disposition header or the final redirected URL without needing to actually download via a `GET`.

**Comment by itzg** [comment]
...and I'll have to add a heuristic to not use "error" as the filename, which is what the redirected `HEAD` currently provides for worldedit:

```
$ curl -X HEAD -O -fsSL -v https://dev.bukkit.org/projects/worldedit/files/latest 2>&1 | egrep "< HTTP|content
-disposition|location|GET"
* successfully set certificate verify locations:
< HTTP/2 302
< location: /error?aspxerrorpath=/projects/worldedit/files/latest
< HTTP/2 200
```

**Comment by itzg** [comment]
I started to research this again and now get a 403, forbidden both with wget and curl:

```
$ wget https://dev.bukkit.org/projects/worldedit/files/latest
--2023-07-29 00:59:29--  https://dev.bukkit.org/projects/worldedit/files/latest
Resolving dev.bukkit.org (dev.bukkit.org)... 2606:4700::6813:9384, 2606:4700::6813:9284, 104.19.147.132, ...
Connecting to dev.bukkit.org (dev.bukkit.org)|2606:4700::6813:9384|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-29 00:59:29 ERROR 403: Forbidden.
```

**Comment by 53c70r** [comment]
`wget --content-disposition` does the trick.
E.g. `wget --content-disposition https://dev.bukkit.org/projects/worldedit/files/latest`

**Comment by itzg** [comment]
`--content-disposition` doesn't actually make a difference since bukkit.org's file responses do not include the content-disposition header. In the case of errors I reported, it is wget 1.21.1 vs 1.20.3. The latter works as expected.

In any case, it looks like the algorithm will need to fall back to taking the filename from the last redirected URL.

**Comment by 53c70r** [comment]
Maybe the base image could be Ubuntu 22.04 LTS.

**Comment by 53c70r** [comment]
Since this execution is idempotent it should work.
`curl -JOs "$(curl -Lso /dev/null -w %{url_effective} https://dev.bukkit.org/projects/worldedit/files/latest)"`
Just replace the URL with proper variable.

**Comment by itzg** [comment]
I really appreciate the advice on wget and curl 😀, but it is implemented with neither 

https://github.com/itzg/mc-image-helper/blob/master/src/main/java/me/itzg/helpers/sync/MulitCopyCommand.java#L225

There's several features I need to balance there which is why it is not a super trivial change.
