### ISSUE TITLE
User authentication error

### ISSUE THREAD

**Issue by MadayLyncoln** [itzg/docker-minecraft-server#2306]
### Describe the problem

Hello, I'm trying to log in to the docker server on an instance of oracle cloud "ARM64" manage to install the world to leave UP, but when trying to enter the server receives this error message

[07:27:12] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 47.0.45, for MC 1.20.1 with MCP 20230612.114412

[07:28:59] [User Authenticator #1/INFO] [minecraft/ServerLoginPacketListenerImpl]: Disconnecting /####:36830: Failed to verify username!

[07:28:59] [User Authenticator #1/ERROR] [minecraft/ServerLoginPacketListenerImpl]: Username 'test' tried to join with an invalid session

### Container definition

version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
        - 25565:25565
    environment:
        - EULA=TRUE

        - VERSION=1.20.1
        - TYPE=FORGE
        - FORGE_VERSION=47.0.45
        - PUID=1000
        - PGID=1000

    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - /home/ubuntu/minecraft_forge:/data

**Comment by itzg** [comment]
That is being reported by the Minecraft software, not this image. Since you're using a user called "test" perhaps try disabling online mode: https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#online-mode

**Comment by MadayLyncoln** [comment]
I did the configuration you mentioned and now it returns this error 

[15:35:56] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: Disconnecting com.mojang.authlib.GameProfile@20b919ed[id=530fa97a-357f-3c19-94d3-0c5c65c18fe8,name=test,properties={},legacy=false] (/IPHOME:13987): You are not white-listed on this server!

[15:35:56] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@20b919ed[id=530fa97a-357f-3c19-94d3-0c5c65c18fe8,name=test,properties={},legacy=false] (/IPHOME:13987) lost connection: You are not white-listed on this server!


Container definition

    environment:
        - EULA=TRUE
        - VERSION=1.20.1
        - TYPE=FORGE
        - FORGE_VERSION=47.0.45
        - PUID=1000
        - PGID=1000
        - ONLINE_MODE=FALSE

**Comment by itzg** [comment]
I'm not sure if you can combine whitelisting with offline mode. You could also try adding the UUID it reported there in the logs.

**Comment by MadayLyncoln** [comment]
can only access the server with the parameter - ENABLE_WHITELIST=FALSE

**Comment by sag3ll0** [comment]
Hello
if i disable white list 
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/18ae20f7-4595-41bd-b73d-3196521e89c0)
server is starting ok
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/d442be86-7bf5-42f5-b2c2-abab7e31012d)

but users cannot access to server, they is not in whitelist.

when i enabled whitelist with users and start server
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/0e6073d8-58b8-4916-b468-ae131afb6dde)

its start ok, but 
whitelist.json and ops.json is empty
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/e93b131a-64cd-4d08-b363-f3ac9499e1bb)

and users again cannot connect to server.

If i enable white list without users
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/2e1c11b6-eaec-4042-a8b9-c94217e0a649)

after start container i can fill whitelist.json and ops.json by hand and users can connect to server

lookslike filling whitelist.json and ops.json when ONLINE_MODE: "FALSE" is not worked

**Comment by itzg** [comment]
@sag3ll0 can you create a new issue or discussion for your scenario?
