### ISSUE TITLE
whitelist and ops not filling when ONLINE_MODE: "FALSE"

### ISSUE THREAD

**Issue by sag3ll0** [itzg/docker-minecraft-server#2309]
Hello
if i disable white list 
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/18ae20f7-4595-41bd-b73d-3196521e89c0)
server is starting ok
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/d442be86-7bf5-42f5-b2c2-abab7e31012d)

but users cannot access to server, they is not in whitelist.

when i enabled whitelist with users and start server
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/0e6073d8-58b8-4916-b468-ae131afb6dde)

its start ok, but 
whitelist.json and ops.json is empty
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/e93b131a-64cd-4d08-b363-f3ac9499e1bb)

and users again cannot connect to server.

If i enable white list without users
![image](https://github.com/itzg/docker-minecraft-server/assets/18505406/2e1c11b6-eaec-4042-a8b9-c94217e0a649)

after start container i can fill whitelist.json and ops.json by hand and users can connect to server

lookslike filling whitelist.json and ops.json when ONLINE_MODE: "FALSE" is not worked

_Originally posted by @sag3ll0 in https://github.com/itzg/docker-minecraft-server/issues/2306#issuecomment-1657226153_

**Comment by itzg** [comment]
I was about to investigate this further, but just noticed you're not using a comma-delimited list for the whitelist and ops:

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#whitelist-players:~:text=and/or%20UUIDs-,separated%20by%20commas,-via%20the%20WHITELIST

While I do agree it really should support space-delimited also (and I'm starting to add that kind of list support elsewhere), the current code requires a comma-delimited list.

**Comment by itzg** [comment]
This is probably related to #2290 where your configuration is probably logging errors like the following, but proceeds anyway.

```
issue2309-mc-1  | [mc-image-helper] 17:20:37.768 ERROR : 'get' command failed. Version is 1.32.5
issue2309-mc-1  | me.itzg.helpers.get.RequestFailedException: Failed to download https://playerdb.co/api/player/minecraft/03d5540f-306f-34c8-b572-6959433acb74: status code: 400, reason phrase: Bad Request
issue2309-mc-1  |       at me.itzg.helpers.get.GetCommand.processSingleUri(GetCommand.java:442)
```

I probably need to have it skip the playerdb lookup when offline since https://playerdb.co/api/player/minecraft/03d5540f-306f-34c8-b572-6959433acb74 is likely failing since that's an offline UUID.

**Comment by sag3ll0** [comment]
> I probably need to have it skip the playerdb lookup when offline since https://playerdb.co/api/player/minecraft/03d5540f-306f-34c8-b572-6959433acb74 is likely failing since that's an offline UUID.

yes, I also think that with ONLINE_MODE: "FALSE" it is necessary to skip the check and enter users into files, under the responsibility of the server administrator

**Comment by itzg** [comment]
> yes, I also think that with ONLINE_MODE: "FALSE" it is necessary to skip the check and enter users into files, under the responsibility of the server administrator

To make sure I understand, you're proposing that the whitelist/ops logic should leave the files untouched if offline? Even if `WHITELIST` and/or `OPS` is populated?

**Comment by sag3ll0** [comment]
If possible, it is necessary to fill in whitelist files during initial initialization and OVERRIDE_WHITELIST=TRUE (with the ONLINE_MODE=FALSE parameter).json and ops.json by users specified in the appropriate parameters without checking their names on the minecraft server.

**Comment by itzg** [comment]
I'm now confused about your expectations. I think I'll go back to an earlier thought that when it's offline I'll have it insert the UUIDs as-is and not call the playerdb API to resolve those.

**Comment by mohaidoss** [comment]
Hey @itzg could you please explain for me or give me a snippets of the env var to set to enable whitelist/ops with `online_mode:FALSE` ?

I have used this
```
ENV OPS=Mohaidoss
```

But it still doesn't recognise my user.

What about using a file, does the value in UUID matters ? If yes, what should it be then in that case

**Comment by itzg** [comment]
@mohaidoss since offline mode disables the API call to resolve Minecraft username you'll need to set `OPS` to a list of UUIDs like `OPS=00000000-0000-0000-0000-000000000000`

**Comment by nikshepsvn** [comment]
hey @itzg trying to get this running, I have ONLINE_MODE=false and an ops.json file, and its not copying over the file (its empty in data). How would I define my usernames I want to op in this situation?
