### ISSUE TITLE
Autopause + SneakyServer Mod causes frequent client timeouts

### ISSUE THREAD

**Issue by AldsteCarter** [itzg/docker-minecraft-server#2312]
### Describe the problem

I'm running a docker minecraft server with the autopause feature enabled. There is a mod named Sneaky Server which helps with botting and other such security enhancements. I submitted an issue [#9](https://github.com/adryd325/sneaky/issues/9)  on the Sneaky Server page and was referred to submit an issue here. The issue with the client timeouts only occurs with the mod enabled; I can remove the mod and leave autopause enabled and clients have no issues. Any insight on this would be much appreciated. Thanks!

### Container definition

I do not currently have access to my docker-compose file as I am working remote with no ssh access. I could provide this if absolutely necessary.

### Container logs

See related issue.

**Comment by itzg** [comment]
I don't see how this is anything specific to this image and I have commented as such on the issue you linked. I suggest providing the compose file for them to recreate the problem.

**Comment by itzg** [comment]
In general it seems like the mod and feature are not compatible. I recommend not using autopause while using that mod.

**Comment by itzg** [comment]
If you want to debug further, while a player(s) is connected run the following and provide that output:

```
docker exec <container name> mc-monitor --debug status --show-player-count
```

**Comment by adryd325** [comment]
Oh I see the problem, are you pinging the server, if so its the player list anonymisation that breaks it

You'll have to determine the IP mc-monitor connects from and add it to the permanent allowlist in `config/sneakyserver/allowed-ping-ips.csv`

a line like 127.0.0.1,0 should work

**Comment by itzg** [comment]
FWIW here's an example of the ping response it processes:

```
2023-08-01T17:05:28.277Z	DEBUG	mc-monitor/java_status.go:82	pinging
2023-08-01T17:05:28.278Z	DEBUG	mc-monitor/java_status.go:85	ping returned	{"info": {"version":{"name":"Paper 1.20.1","protocol":763},"players":{"max":20,"online":0,"Sample":null},"description":{"text":"A Paper Minecraft Server powered by Docker","bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"","extra":null},"favicon":""}}
0
```

**Comment by adryd325** [comment]
What IP would mc-monitor ping from?
if it's just localhost; adding 
```
127.0.0.1,0
0:0:0:0:0:0:0:1%0,0
```
to config/sneakyserver/allowed-ping-ips.csv should allow pings from the local IP

**Comment by itzg** [comment]
Yes it'll ping over loopback. The suggested change will be for the OP to configure. The image doesn't include any mod specific configuration.

**Comment by adryd325** [comment]
I'll add a default option to allow loopback to ping to prevent issues in the future

**Comment by itzg** [comment]
@AldsteCarter I'll let you close this out if you're happy with all that.

@adryd325 thanks for your follow-up

**Comment by AldsteCarter** [comment]
Thanks for the assistance! That makes sense.
