### ISSUE TITLE
I have a couple critical questions about automation

### ISSUE THREAD

**Issue by KoNekoD** [itzg/docker-minecraft-server#2319]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I have a couple critical questions about automation
How can I use plugins similarly to the world sharing feature.
1. Worlds can be connected as I understand by minting volume by name(/var/mc/saves/serv1/world:/worlds/world). I would like to do the same with the plugins folder, how can this be done?

I want to do this in order to cron to do an automatic dump of the world and data from plugins (there are also over time change (databases, etc.)). 

2. I really like your implementation with image, but it lacks one thing - status monitoring, it seems to be absent. Is there any way to organize it somehow - "the server has been down for 10 minutes" I get a notification in Telegram and Discord and I wake up from sleep and immediately run to start it, or not run =).

**Comment by itzg** [comment]
For item 1 it's not clear if you have read the documentation and found the plugin support to be lacking something specific. Like the world data support you described there are several options for plugins.

For item 2, the image includes health checks and that's the extent of what a container should do to monitor itself. If the container is down how can it itself report that it is done? Instead use something like what the container bundles, but run it **external** to the container being monitored and derive alerts from that: https://github.com/itzg/mc-monitor

**Comment by KoNekoD** [comment]
I found how to connect /plugins, thanks. Do I connect the worlds via WORLD ?

**Comment by KoNekoD** [comment]
Why world volume and plugins volume just copy files?
