### ISSUE TITLE
Minecraft - Features/questions

### ISSUE THREAD

**Issue by tjsd** [itzg/docker-minecraft-server#232]
Hi!
I am sorry for creating a issue here, but I don't know if you have a discord community or anything for questions/comments about use/features of the dockers you maintain.

I have a script running in crontab that restarts my minecraft server at given intervalls.
That is done by issuing console commands to the screen like stop. Then it will automatically restart after a give time in the script.

But if I issue a stop with rcon it just stops and sits there. Got any suggestions on how I could get this functionality with the docker version? :)

For reference I use the following script to start my server, so when stop is issued it just counts down 5 seconds and start the server again:

```
#!/bin/sh
while true
do
java -Xmx8G -d64 -server -jar minecraft_forge.jar nogui
echo "If you want to completely stop the server process now, press Ctrl+C before
the time is up!"
echo "Rebooting in:"
for i in 5 4 3 2 1
do
echo "$i..."
sleep 1
done
echo "Rebooting now!"
done
```

**Comment by tjsd** [comment]
Just to comment on my own case, if I issue a stop the container also stops. 
If you then use --restart always in the docker parameter it will restart.

**Comment by itzg** [comment]
I have recently enhanced the container to handle `docker stop` such that it sends a `stop` command to the minecraft server to shutdown gracefully. The logic then waits for the java process to stop all the way before letting the `docker stop` return. So...you should be able to greatly simply your cron job and issue a `docker restart` or separate `docker stop` then `docker start`.

FYI I have a Gitter channel here https://gitter.im/itzg/dockerfiles but a Discord community is a good idea.
