### ISSUE TITLE
MODRINTH_PROJECT is a confusing a variable name

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#2333]
Apparently the naming/documentation is still confusing. I think I am going to rename the `MODRINTH_PROJECT` (singular) to `MODRINTH_MODPACK`, which **is required** with `MOD_PLATFORM: MODRINTH`. I'll alias the variable so that it doesn't break existing configurations.

_Originally posted by @itzg in https://github.com/itzg/docker-minecraft-server/issues/2139#issuecomment-1676160787_

**Comment by Sandros94** [comment]
Docs still refer to `MODRINTH_PROJECT`.

Also, would it be possible to combine modpacks with single mods?
