### ISSUE TITLE
failed to ping localhost:25565 : read tcp 127.0.0.1:48942->127.0.0.1:25565: read: connection reset by peer

### ISSUE THREAD

**Issue by olivercool103** [itzg/docker-minecraft-server#2354]
### Describe the problem

I cannot connect to my minecraft server, container keeps reporting back this error.

### Container definition

docker run -d -p 25565:25565 --name minecraft -e TYPE=QUILT -e EULA=TRUE -v /home/oliverjelincic/Minecraft/home:/data itzg/minecraft-server

### Container logs

```
Very normal Minecraft server logs
```

**Comment by itzg** [comment]
Please provide container logs as was requested in the issue template.
