### ISSUE TITLE
Modrinth disable Download of Required dependencies

### ISSUE THREAD

**Issue by RevLaw** [itzg/docker-minecraft-server#2356]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Hey, if you want to use mods like **[adorn](https://modrinth.com/mod/adorn/version/5.0.0-fabric)** and **[wthit](https://modrinth.com/mod/wthit/version/quilt-8.3.1)** together on Quilt it is at the moment not working with the auto download feature.

Required dependencies **wthit**: 
-  fabric-api

Required dependencies **Adorn**: 
- (qsl) Quilted Fabric API

If I start the server, qsl and fabric-api trying to register the same Mod ID and then the server stops because that is not possible. 

I know that is an issue on Modrinth/modder side, and they should set the right dependencies for quilt versions. But could you implement an env variable where I can change the behaviour?

[Documentation optional dependencies](https://docker-minecraft-server.readthedocs.io/en/latest/mods-and-plugins/modrinth/#extra-options)

**Comment by itzg** [comment]
Yes that totally makes sense. Really I should transform the option to download optional dependencies into an option that accepts none, required, or optional as the choices.

**Comment by RevLaw** [comment]
Thank you very much. I appreciate your work <3
