### ISSUE TITLE
Support for neoforge

### ISSUE THREAD

**Issue by shayanz23** [itzg/docker-minecraft-server#2362]
Hi, a few months ago a new forge fork was made called neoforged with almost all the forge team moving to it, and I think since it is practically a forge replacement, it should also be supported as server type or at least version of forge. 

Edit: Some mods like https://www.curseforge.com/minecraft/mc-mods/railcraft-reborn are already starting to warn that in the future they will only support neoforge.

**Comment by itzg** [comment]
Why do half the time they call it "neoforged" with a "d" and "neoforge" without? Which is their main identifier or do I have to allow confused users to request it by either name?

https://neoforged.net/

**Comment by shayanz23** [comment]
mb, It's actually neoforged.

**Comment by itzg** [comment]
You're good. I mean on their own website they use both 😀

**Comment by shayanz23** [comment]
Lol no wonder I messed up lol.

**Comment by itzg** [comment]
Thanks @heipiao233 ! Wanted to make sure the correct term was exposed.

**Comment by itzg** [comment]
To poke a bit of fun (and justify why I have been asking)

![image](https://github.com/itzg/docker-minecraft-server/assets/988985/f116d3d3-cf91-4dcb-b99d-ee46f87d02b1)

**Comment by itzg** [comment]
@shayanz23 @heipiao233 where is the neoforge equivalent of https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json ? Their docs only mention their maven repo and their Discord server is not publicly listed.

I **cannot proceed** without this information.

**Comment by itzg** [comment]
Blocked by https://github.com/neoforged/NeoForge/issues/52

**Comment by itzg** [comment]
With clarification in https://github.com/neoforged/NeoForge/issues/52#issuecomment-1742119053 I can now proceed.

**Comment by itzg** [comment]
### Development notes

Selecting NeoForge from modpacks doesn't seem to be supported yet. For example, 

- https://www.curseforge.com/minecraft/modpacks/projekt-arcturus/files/4772539 claims NeoForge as a modloader, but needs version 1.18.2, [which doesn't exist for NeoForge](https://maven.neoforged.net/releases/net/neoforged/forge/maven-metadata.xml). Also, the manifest actually reports just forge:
```json
  "minecraft": {
    "version": "1.18.2",
    "modLoaders": [
      {
        "id": "forge-40.2.4",
        "primary": true
      }
    ]
  },
```
- https://modrinth.com/modpack/nerbvival/version/v5 indicates support for NeoForge, but the manifest calls out only forge and the forge version 47.1.44 does not exist for NeoForge 1.20.1
```json
  "dependencies": {
    "forge": "47.1.44",
    "minecraft": "1.20.1"
  },
```
