### ISSUE TITLE
Container Shows as Unhealthy and Appears to Time Out when using TCPShield Proxy.

### ISSUE THREAD

**Issue by UPSOKen** [itzg/docker-minecraft-server#2365]
### Describe the problem

This may not be a bug as much as me being an idiot.

I use TCPShield for DDoS protection. The TCPShield plugin enforces an only connect via proxy system, so you can only connect via DNS for a domain name I've setup.

However, If the proxy-only connection option is enabled, it says my container is unhealthy (It says healthy as soon as I disable the option). Then I believe the health check times out the container (Which auto restarts) after some time (I continue to experience strange shutdowns/restarts).

How can I correct this? I am not an expert with docker, and I use portainer to manage my containers. I am wondering if I am missing something in the documentation.

### Container definition

```
Using Portainer
```

### Container logs

```
  | failed to ping localhost:25565 : could not connect to Minecraft server: dial tcp 127.0.0.1:25565: connect: connection refused
-- | --
```

**Comment by itzg** [comment]
You can always disable the healthcheck https://docker-minecraft-server.readthedocs.io/en/latest/misc/healthcheck/

**Comment by UPSOKen** [comment]
> You can always disable the healthcheck https://docker-minecraft-server.readthedocs.io/en/latest/misc/healthcheck/

I will consider this, but I was curious if there was some sort of environment variable option to define the IP it should be checking, because I do like the healthcheck option. Thanks for the help, either way!

**Comment by itzg** [comment]
What IP address would it ping then? The "external" TCPshield one? If so, that goes against the point of self-contained, containerized health checks. Perhaps TCPshield has an option to allow loopback as an exception.

**Comment by UPSOKen** [comment]
> 

I suppose you're right - but I figured that the health check was to check if the server was up or not, and the external IP would tell if that was the case, but I suppose that does lend it to a lot of issues. I'll disable Healthcheck for now. TCPShield claims to have some sort of IP whitelist, but so far it has not worked for me. Either way, I appreciate your help!

**Comment by UPSOKen** [comment]
> FYI for broader monitoring, you can always run https://github.com/itzg/mc-monitor as a companion container and point that at the TCPshield endpoint.

Great suggestion! I actually am using uptime kuma and setup a GameDig check for the server, so I've got that handled. Thanks for the help!
