### ISSUE TITLE
ops.json & whitelist.json are created in the wrong directory

### ISSUE THREAD

**Issue by EvilBlood** [itzg/docker-minecraft-server#2373]
### Describe the problem

If you define the whitelist and the ops in the variables. then the files are always created in the main folder. With Curseforge modpacks, however, they must be placed in the correct subfolder. With the server.properties this also works, unfortunately only not with the ops.json and whitelist.json these are created directly in /data.

![image](https://github.com/itzg/docker-minecraft-server/assets/92166/5bee9537-3726-4ecc-923c-39917b453159)

### Container definition

mcs2:
    image: itzg/minecraft-server
    container_name: mcs2
    environment:
      OVERRIDE_SERVER_PROPERTIES: "true"
      EULA: "TRUE"
      TZ: "Europe/Berlin"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: "/downloads/ATMVB/serverfiles-1.0.7.zip"
      INIT_MEMORY: "2G"
      MAX_MEMORY: "8G"
      ENABLE_WHITELIST: "true"
      WHITELIST: "user1, user2, user3"
      OVERRIDE_WHITELIST: "true"
      PLAYER_IDLE_TIMEOUT: "30"
      ENABLE_AUTOPAUSE: "true"
      ENABLE_ROLLING_LOGS: "true"
      MAX_TICK_TIME: "-1"
      VIEW_DISTANCE: "6"
      OPS: "user1"
      MAX_PLAYERS: "5"
      MOTD: "MOTD"
      ALLOW_FLIGHT: "TRUE"
      REMOVE_OLD_MODS: "TRUE"
    tty: true
    stdin_open: true
    networks:
      internal:
    volumes:
      - modpacks:/downloads
      - mcs2_data:/data
    labels:
      com.centurylinklabs.watchtower.enable: "true"

**Comment by itzg** [comment]
I am trying to avoid any further support of the old curseforge type in favor of the new support: https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/ 

...however, I'll take a quick look since I might have caused a regression with a recent change.

**Comment by zinefer** [comment]
I think I'm running into this issue, I can't get into my server despite following the docs for whitelist. I'm not sure where the ops/whitelist files should actually go.

**Comment by itzg** [comment]
> I think I'm running into this issue, I can't get into my server despite following the docs for whitelist. I'm not sure where the ops/whitelist files should actually go.

For now the files will need to be manually created in the expanded modpack subdirectory.
