### ISSUE TITLE
can't set max-tick-time

### ISSUE THREAD

**Issue by YanivYon** [itzg/docker-minecraft-server#2374]
### Describe the problem

synology server crashes
in env i cant set max-tick-time
its always 60000ms

### Container definition

```
Paste run command or compose file here
```

### Container logs

https://pastebin.com/qv9uNsLc

**Comment by itzg** [comment]
Please provide container config and specific snippet pointing out where you confirmed the max tick time was not set in server.properties.

**Comment by YanivYon** [comment]
i am running it via synology docker app
can't really get the launch command
https://prnt.sc/ux_tRAvRO57t
i tried max_tick_time and max-tick-time as ENV
https://prnt.sc/iqxbLBuBH7o7

but that's just a try to fix my constant server crashes
my kids are complaining they can't get to the end of the map or into after end, because server crashes

**Comment by itzg** [comment]
Thanks, that helped. All env vars are case sensitive: it needs to be `MAX_TICK_TIME`, not `max_tick_time`:

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#max-tick-time

**Comment by itzg** [comment]
Unrelated, I'm guessing you may want to use https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options/#enable-aikars-flags rather than manually settings `JVM_XX_OPTS` (but I can only see the first bit there).

**Comment by YanivYon** [comment]
env variables helped
https://pastebin.com/D9w2T5uE

and i set the aikars flags too

server is still crashing once they teleport 
but without the watchdog message
thats the last log entry, after 30 seconds the clients disconnect
[09:28:55] [Server thread/INFO]: [raphim343: Teleported raphim343 to 1000.500000, 79.937500, 1000.500000]

kids are crying
help please

**Comment by itzg** [comment]
I can't help with general Minecraft issues. I only maintain the image that configures the server. Perhaps ask on Minecraft's Discord https://discord.com/invite/minecraft
