### ISSUE TITLE
Minecraft - Add support for custom server software (jar file)

### ISSUE THREAD

**Issue by CatMe0w** [itzg/docker-minecraft-server#238]
I need to run with my own server software, but it seems there is no way.
Also, because of this problem, it is difficult for those people who need to run Thermos or Cauldron server.

**Comment by itzg** [comment]
How would you like to stage the custom jar? Via an attached volume like in the /data mount path? If that, works then I’m thinking the option could be something like

`-e CUSTOM_SERVER=server.jar`

where a path is relative to /data or can be an absolute path.

**Comment by CatMe0w** [comment]
Right.
I think this option can point to a URL like downloading modpacks as an alternative way.

**Comment by Nicholaiii** [comment]
+1 on this, would be nice with a CUSTOM type that could potentially download and expand a zip archive and then via eg CUSTOM_SERVER env var specify which jar to run.

**Comment by itzg** [comment]
Sorry for the huge delay on this one. I have pushed a new image to Docker Hub that now includes `TYPE=CUSTOM` and the new `CUSTOM_SERVER` variable that can either be a URL to download or an existing JAR file.

Documentation section has been added at

https://github.com/itzg/dockerfiles/tree/master/minecraft-server#running-with-a-custom-server-jar

@CatMe0w and/or @Nicholaiii can you let me know if this update works for you?

**Comment by bram-pkg** [comment]
I think this issue is fixed now. @itzg

**Comment by Nicholaiii** [comment]
Oh, I hadn't seen this response, but that's great news
