### ISSUE TITLE
Add TOC in Documentation

### ISSUE THREAD

**Issue by jpgreth** [itzg/docker-minecraft-server#2381]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

It would be very helpful, to add a table of contents in the head of the Documentation.
This would make the docs so much more useable and give them additional structure.

**Comment by itzg** [comment]
There's already the navigation banner at the top and section TOC's within each

<img width="1265" alt="image" src="https://github.com/itzg/docker-minecraft-server/assets/988985/f219abd6-9af0-4dc9-8297-221d0666a981">

I really don't know how to implement what you want in mkdocs without an incredibly tedious, error prone task. Please point me to mkdocs plugins that would help achieve what you're thinking.

**Comment by jpgreth** [comment]
Didn't know about this page. Where can i find it? 
Just came here via google and meant the TOC for the Readme.md
But this page looks much better than the md.

**Comment by jpgreth** [comment]
Ah... found it: https://docker-minecraft-server.readthedocs.io/en/latest/?badge=latest sorry

**Comment by itzg** [comment]
For future reference, all GitHub readme's (markdown in general) provide a TOC drop-down

![image](https://github.com/itzg/docker-minecraft-server/assets/988985/f948c3ba-6fed-492a-80de-8f0233438b35)
