### ISSUE TITLE
Error with Modpack Server ATM9

### ISSUE THREAD

**Issue by kromac17** [itzg/docker-minecraft-server#2403]
### Describe the problem

When trying to run a Minecraft Server with the ATM9 Modpack i get the following error. A similar error i had before was fixed by updating to the newest image, but now i have the newest image and it is downloading some modpacks, as seen in the logs, but at some point it gets this error.

Thanks
Marco

### Container definition

version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25569:25565"
    environment:
      EULA: "true"
      MOD_PLATFORM: AUTO_CURSEFORGE
      CF_API_KEY: "$2a$10$...."
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
      MEMORY: 16G
    volumes:
      - /minecraft/ATM9/data:/data

volumes:
  mc-data: {}

### Container logs

[+] Running 1/0
 ✔ Container atm9-mc-1  Created                                                                                                                                                                             0.0s
Attaching to atm9-mc-1
atm9-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 10 1000 1003 4096 Oct  1 16:24 /data'
atm9-mc-1  | [mc-image-helper] 19:13:42.641 INFO  : Processing modpack 'All the Mods 9-0.1.11' (all-the-mods-9) @ 715572:4776759
atm9-mc-1  | [mc-image-helper] 19:13:43.597 INFO  : Excluding mod file 'Controlling' (controlling) due to configuration
atm9-mc-1  | [mc-image-helper] 19:13:43.741 INFO  : Mod file mods/useful_railroads-forge-1.20.1-1.5.6.56.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:43.741 INFO  : Mod file mods/flickerfix-1.20.1-4.0.1.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:43.746 INFO  : Mod file mods/cupboard-1.20.1-2.0.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:43.748 INFO  : Mod file mods/crashutilities-8.1.4.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:43.757 INFO  : Mod file mods/rsrequestify-1.20.1-2.3.2.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:43.758 INFO  : Mod file mods/ftb-essentials-forge-2001.2.0.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:43.891 INFO  : Mod file mods/baubley-heart-canisters-1.20.1-1.0.3.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:43.898 INFO  : Mod file mods/trashcans-1.0.18b-forge-mc1.20.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:43.903 INFO  : Mod file mods/alltheores-1.20-46.0.2-2.1.1.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.223 INFO  : Mod file mods/sophisticatedbackpacks-1.20.1-3.18.59.909.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.348 INFO  : Excluding mod file 'Entity Culling Fabric/Forge' (entityculling) due to configuration
atm9-mc-1  | [mc-image-helper] 19:13:44.352 INFO  : Mod file mods/BetterAdvancements-1.20.1-0.3.2.161.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.356 INFO  : Mod file mods/MysticalAgriculture-1.20.1-7.0.2.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.357 INFO  : Mod file mods/durabilitytooltip-1.1.5-forge-mc1.20.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.370 INFO  : Mod file mods/IntegratedDynamics-1.20.1-1.19.1.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.370 INFO  : Mod file mods/create-stuff-additions1.20.1_v2.0.4a.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.371 INFO  : Mod file mods/kubejs-forge-2001.6.3-build.52.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.374 INFO  : Mod file mods/AttributeFix-Forge-1.20.1-21.0.2.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.379 INFO  : Mod file mods/multipiston-1.20-1.2.31-ALPHA.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.379 INFO  : Mod file mods/trashslot-forge-1.20-15.1.0.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.388 INFO  : Mod file mods/ToastControl-1.20.1-8.0.3.jar already exists
atm9-mc-1  | [mc-image-helper] 19:13:44.430 ERROR : 'install-curseforge' command failed. Version is 1.35.3
atm9-mc-1  | me.itzg.helpers.errors.GenericException: Failed to parse response body into class me.itzg.helpers.curseforge.model.GetModFileResponse: Cannot deserialize value of type `me.itzg.helpers.curseforge.model.FileStatus` from String "18": not one of the values accepted for Enum class: [11, 12, 13, 14, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
atm9-mc-1  |  at [Source: (reactor.netty.ByteBufMono$ReleasingInputStream); line: 1, column: 194] (through reference chain: me.itzg.helpers.curseforge.model.GetModFileResponse["data"]->me.itzg.helpers.curseforge.model.CurseForgeFile["fileStatus"])
atm9-mc-1  |    at me.itzg.helpers.http.ObjectFetchBuilder.lambda$handleResponse$1(ObjectFetchBuilder.java:89)
atm9-mc-1  |    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
atm9-mc-1  |    at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
atm9-mc-1  |    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
atm9-mc-1  |    at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
atm9-mc-1  |    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
atm9-mc-1  |    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
atm9-mc-1  |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
atm9-mc-1  |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
atm9-mc-1  |    at java.base/java.lang.Thread.run(Unknown Source)
atm9-mc-1  |    Suppressed: java.lang.Exception: #block terminated with an error
atm9-mc-1  |            at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
atm9-mc-1  |            at reactor.core.publisher.Mono.block(Mono.java:1712)
atm9-mc-1  |            at me.itzg.helpers.curseforge.CurseForgeInstaller.processModpack(CurseForgeInstaller.java:540)
atm9-mc-1  |            at me.itzg.helpers.curseforge.CurseForgeInstaller.resolveModpackFileAndProcess(CurseForgeInstaller.java:361)
atm9-mc-1  |            at me.itzg.helpers.curseforge.CurseForgeInstaller.installByRetrievingModpackZip(CurseForgeInstaller.java:229)
atm9-mc-1  |            at me.itzg.helpers.curseforge.CurseForgeInstaller.lambda$install$4(CurseForgeInstaller.java:159)
atm9-mc-1  |            at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:195)
atm9-mc-1  |            at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:158)
atm9-mc-1  |            at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:202)
atm9-mc-1  |            at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:27)
atm9-mc-1  |            at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
atm9-mc-1  |            at picocli.CommandLine.access$1500(CommandLine.java:148)
atm9-mc-1  |            at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
atm9-mc-1  |            at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
atm9-mc-1  |            at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
atm9-mc-1  |            at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
atm9-mc-1  |            at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
atm9-mc-1  |            at picocli.CommandLine.execute(CommandLine.java:2170)
atm9-mc-1  |            at me.itzg.helpers.McImageHelper.main(McImageHelper.java:155)
atm9-mc-1  | Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `me.itzg.helpers.curseforge.model.FileStatus` from String "18": not one of the values accepted for Enum class: [11, 12, 13, 14, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
atm9-mc-1  |  at [Source: (reactor.netty.ByteBufMono$ReleasingInputStream); line: 1, column: 194] (through reference chain: me.itzg.helpers.curseforge.model.GetModFileResponse["data"]->me.itzg.helpers.curseforge.model.CurseForgeFile["fileStatus"])
atm9-mc-1  |    at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
atm9-mc-1  |    at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002)
atm9-mc-1  |    at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:415)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:279)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:258)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
atm9-mc-1  |    at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
atm9-mc-1  |    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
atm9-mc-1  |    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
atm9-mc-1  |    at me.itzg.helpers.http.ObjectFetchBuilder.lambda$handleResponse$1(ObjectFetchBuilder.java:85)
atm9-mc-1  |    ... 9 common frames omitted
atm9-mc-1  | [init] ERROR failed to auto-install CurseForge modpack
atm9-mc-1 exited with code 1

**Comment by itzg** [comment]
Thanks for reporting this. There must be an update to the API that will need to be handled.

**Comment by itzg** [comment]
### Dev note

That FileStatus ordinal is not documented, nor is values 16 or 17: https://docs.curseforge.com/#tocS_FileStatus

**Comment by itzg** [comment]
I am not able to recreate this issue. I suspect the offending mod file had its file status changed since you originally observed the issue. I am going to add a little more information to the error stack trace for future debugging, but otherwise am unable to address the original issue exactly.

**Comment by kromac17** [comment]
Thank you for dealing with my problem so fast, even tough it fixed itself 😂
