### ISSUE TITLE
defaultworldgenerator-port in server.properties

### ISSUE THREAD

**Issue by skupfer** [itzg/docker-minecraft-server#2407]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I am trying to run `Feed the Factory`. Unfortunately the server.zip refuses to work despite all efforts so I resorted to `AUTO_CURSEFORGE` but during the startup it complains about the missing "World Type". I didn't find a way in the docs to declare it by variables.

```
mc_1       | Choose A default world type:
mc_1       |
mc_1       | 1) Factory Flatscape   [f8c04631-f744-11ec-b260-f02f74b094e0]
mc_1       | 2) Default Gen   [12a8e5d1-f988-11ec-ba31-f02f74b094e0]
mc_1       |
mc_1       | Type "/defaultworldgenerator-port <the number for the server's worldtype>
mc_1       | Alternativly add the uuid as the value of "defaultworldgenerator-port" in server.properties
```

Line in server.properties from server.zip: `defaultworldgenerator-port=f8c04631-f744-11ec-b260-f02f74b094e0`

**Comment by itzg** [comment]
When [this build finishes](https://github.com/itzg/docker-minecraft-server/actions/runs/6442811587), there is an option for custom server properties: 

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#custom-server-properties
