### ISSUE TITLE
Modpack on MC Version 1.18.2 crashes

### ISSUE THREAD

**Issue by itanne99** [itzg/docker-minecraft-server#2431]
### Describe the problem

While trying to run a Vault Hunter 3 server using the following image `itzg/minecraft-server:stable` the server crashes with the following log message, which can be found below.

Doing research, it is mentioned that the reason for this message is that a Forge 1.18.2 server requires Java 17 to run properly, but the stable build of this docker image uses Java 17.

### Container definition

ersion: "3.8"

services:
  mc:
    image: itzg/minecraft-server:stable
    ports:
      - "25565:25565"
    # restart: unless-stopped
    environment:
      EULA: "true"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: {{API_KEY}}
      CF_SLUG: vault-hunters-1-18-2
      CF_FILENAME_MATCHER: "Vault Hunters 3rd Edition-3.11.5.zip"
      MOTD: "  4-----   2 Vault Hunters: 1.18.2 V3.11.5   4 -----  r\\n       4------   e vaulthunters.gg    4------"
      MEMORY: 12G # 4G for base server + 2G per player
      CF_EXCLUDE_MODS: reauth, neon-craft-2-mod
      CF_FORCE_INCLUDE_MODS: '230976'
      ALLOW_FLIGHT: "true"
      ENABLE_COMMAND_BLOCK: "true"
      DIFFICULTY: "normal"
    volumes:
      # Need to place non-distributable mods in ./downloads/mods
      # As of Update-10.0.0
      # - Neon Craft 2 v2.2: https://www.curseforge.com/minecraft/mc-mods/neon-craft-2-mod/files/3726051
      - ./downloads:/downloads
      - ./mc-data:/data

volumes:
  mc-data: {}

### Container logs

mc_1  | /data/./run.sh: line 6:   412 Killed                  java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.2-40.2.9/unix_args.txt "$@"
mc_1  | 2023-10-12T14:03:07.120Z        WARN    mc-server-runner        Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error.      {"exitCode": 137}
mc_1  | 2023-10-12T14:03:07.127Z        INFO    mc-server-runner        Done

**Comment by itzg** [comment]
You have made me realize that maybe I should get rid of the "stable" tag if it is going to cause this kind of confusion. "stable" is just a shorthand for the most recent git-tagged "latest" where "latest" is tracking Mojang's latest Java version used. So, stable == latest == Java 17.

Please use `itzg/minecraft-server:java8-multiarch`.

**Comment by itanne99** [comment]
I should have mentioned that I tried to use `Latest` as well and `java17` tags, but that didn't work.

I'll try to use the tag you mentioned and get back to you.

**Comment by itanne99** [comment]
`itzg/minecraft-server:java8-multiarch` did not let the server run at all.

![image](https://github.com/itzg/docker-minecraft-server/assets/20746427/6633c1b7-af71-4338-8661-b2ef12b1127d)


When using `itzg/minecraft-server:latest` this is the error I get... I'll look into seeing if this is an issue with the modpack, but I had it running perfectly a couple months back.

![image](https://github.com/itzg/docker-minecraft-server/assets/20746427/f8145e97-2544-4996-8406-3b2297733d3f)

**Comment by itzg** [comment]
Ah yes, it definitely needs Java 17. I don't know what the original error is since a) it's from the mods, not the container b) I can't see enough from the snippet.
