### ISSUE TITLE
/start-setupRbac: line 16: isTrue: command not found

### ISSUE THREAD

**Issue by atyrode** [itzg/docker-minecraft-server#2435]
https://github.com/itzg/docker-minecraft-server/blob/2ebcc0fe0051fee282f70a9c6ed5f746d59d1c4f/scripts/start-setupRbac#L8-L22

Hello, I feel like that might be a misuse of something on my side but, start-utils is not "imported" in setupRbac before the first isTrue, and since that's a function that's part of start-utils, I consistently get:

```
...
[init] Enabling whitelist functionality
[init] Setting mode
[mc-image-helper] 02:53:06.217 INFO  : Created/updated 16 properties in /data/server.properties
/start-setupRbac: line 16: isTrue: command not found <-----------------
[init] Creating log4j2.xml in /data/log4j2.xml
[init] Using Aikar's flags
...
```

I don't know too much about bash so I'm worried it might not be running the rest of the script?

**Comment by itzg** [comment]
Thanks for reporting this. I had put the import in the wrong spot and apparently hadn't hit those test cases before now.

**Comment by itzg** [comment]
Should be fixed with this image build https://github.com/itzg/docker-minecraft-server/actions/runs/6520298931

**Comment by atyrode** [comment]
@itzg Thanks a lot. Sincerely.

**Comment by itzg** [comment]
And thanks for the sponsorship!
