### ISSUE TITLE
VANILLA server version 1.0, 1.1, 1.2 doesn't work and gives an error

### ISSUE THREAD

**Issue by AblakfosoMolyadek** [itzg/docker-minecraft-server#2447]
### Describe the problem

I tried to run a vanilla server version 1.1, but it gave an error, as it couldn't find to download it.
(I want to change versions every few months till we reach the latest)

From version 1.3 it works fine though.

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```
[init] Changing ownership of /data to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 3 1000 1000 14 Oct 19 16:37 /data'
[init] Resolving type given VANILLA
[init] Resolved version given 1.1 into 1.1
[init] ERROR: there is not a server download for version 1.1

**Comment by itzg** [comment]
That is beyond my control. Following https://launchermeta.mojang.com/mc/game/version_manifest.json you'll find 

- the 1.0 manifest https://piston-meta.mojang.com/v1/packages/75062586b830dd5160f13f1c9130eb365e01f1b9/1.0.json does **not** include a `server` entry in the `downloads`
- the 1.3 manifest https://piston-meta.mojang.com/v1/packages/b384219c6d4879e56b92eea01a0d986e20d55dea/1.3.json does include that entry

**Comment by AblakfosoMolyadek** [comment]
I see.
Is there any way to start a custom server.jar file that I put there manually?
That would also solve this problem.

**Comment by itzg** [comment]
Good idea, https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/server-types/others/#custom
