### ISSUE TITLE
Docker Unhealthy Notification on older versions

### ISSUE THREAD

**Issue by Hetters** [itzg/docker-minecraft-server#2461]
### Describe the problem

Hi!

I'm running a beta 1.7.3 container for minecraft, and it always shows the 'unhealthy' state in portainer. In the live log, I constantly get the following events:

2023-11-03 08:42:02 [INFO] /127.0.0.1:59718 lost connection
java.io.IOException: Bad packet id 254
	at gt.a(SourceFile:135)
	at jl.g(SourceFile:197)
	at jl.c(SourceFile:17)
	at oy.run(SourceFile:84)
2023-11-03 08:42:07 [INFO] /127.0.0.1:47544 lost connection
java.io.IOException: Bad packet id 254
	at gt.a(SourceFile:135)
	at jl.g(SourceFile:197)
	at jl.c(SourceFile:17)
	at oy.run(SourceFile:84)

Have I set this up wrong? I've included my compose file below which includes a custom jar for b1.7.3

### Container definition

```
Paste run command or compose file here
```
version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - "25567:25565"
    environment:
      EULA: "TRUE"
      TYPE: "CUSTOM"
      CUSTOM_SERVER: "b1.7.3.jar"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
This was mostly fixed by #2360; however, can you also set `VERSION` so that the logic knows to disable the health check or just set `DISABLE_HEALTHCHECK` to "true" (see https://docker-minecraft-server.readthedocs.io/en/latest/misc/healthcheck/)
