### ISSUE TITLE
Is it possible to use some kind of placeholder as a level name?

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#2474]
### Discussed in https://github.com/itzg/docker-minecraft-server/discussions/2473

<div type='discussions-op-text'>

<sup>Originally posted by **nmills3** November  9, 2023</sup>
So basically i want to make it so that my level name is based off of the current snapshot version that the server is running. Is there any way to set the level name as something like "world-%VERSION%" or something similar?

My goal is to have the server create a new world for each snapshot version that gets release. that way i can just restart the container and then the new snapshot server will get auto downloaded and a new world will be created. But if i want i could still go back and access the old worlds</div>

**Comment by nmills3** [comment]
Here's a list of possible placeholder options i can think of

- Version
- Server Type (Vanilla, force, fabric, etc)
- Current datetime (useful for a server that generates a new map after every restart but needs to keep the old maps)
- Current date

**Comment by hpf3** [comment]
my request is for the ability to also use the replacements in the motd, including the version of the ftb pack or auto-curseforge pack.

maybe a generic replacer that runs before each of the "misc text" enviroment variables are used?

**Comment by itzg** [comment]
The image now includes support for placeholders where both environment variables and custom date/time format can be processed:

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#placeholders

**Comment by nmills3** [comment]
Can i suggest giving all resolved variables a prefix of some sort. Right now there is potential for conflict because VERSION could either be the initial value of SNAPSHOT or the resolved value of 23w45a. Another option could be making it so that just %VERSION% is the resolved value OR the env variable and %env:VERSION% will always be the unresolved version.

Other than that small nit pick, it's a very nice change and works well. Thanks!

**Comment by itzg** [comment]
Applying a prefix would be quite difficult since all it is doing is resolving environment variables and it's impossible to know where the variables originated. 

With that said, VERSION is certainly a special case that is worth keeping aside the declared version. I'll have it save off `DECLARED_VERSION` prior to any of the resolution steps.

**Comment by nmills3** [comment]
may i also suggest a slight rewording to the docs. Currently they say that the values are replaced with the environment variables, but from my understanding, the environment variable its self for VERSION isn't changed and remains as SNAPSHOT. If i'm correct, maybe changing the working to something like "the environment variable or resolved value." I know it does say it in the paragraph underneath but having it in the sentence under the example might help to make it a little bit more clear

**Comment by itzg** [comment]
VERSION is changed to the resolved value, which is why I added DECLARED_VERSION as discussed. 

I'm a bit confused about what is now being requested; however, maybe it doesn't help that it isn't apparent that change in variable happens during startup.

**Comment by itzg** [comment]
For example,

```
docker run -it --rm -e EULA=true -e MOTD="Running %TYPE% version %VERSION%" -e DUMP_SERVER_PROPERTIES=true -e SETUP_ONLY=true itzg/minecraft-server
```

outputs the server property:
```
motd=Running VANILLA version 1.20.2
```

**Comment by itzg** [comment]
I see the source of confusion now and indeed would like to find a better wording for

<img width="700" alt="image" src="https://github.com/itzg/docker-minecraft-server/assets/988985/fffa13b4-d0ba-4863-8ef0-f252825d4d1a">

What I'm trying to say is that when declaring a server property via an environment variable, like `MOTD`, then placeholders can be used. I am trying to emphasize that someone manually managing `server.properties` will not be able to use placeholders.

Maybe I should use that ☝️ wording 😄

**Comment by itzg** [comment]
How does this newest wording look:

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#placeholders

**Comment by nmills3** [comment]
sorry if i was a bit unclear. I'm refering to this section of the docs

![image](https://github.com/itzg/docker-minecraft-server/assets/26787639/6e712cd6-2bb5-4479-b3bc-85a4f98d311c)

in practice the %VAR% isn't actually replaced with the environment variable var, it's replaced with either the environment variable %VAR% or anything %VAR% has been resolved into.

For a real world example, if i put %VERSION% i'm not going to get the enviroment variable VERSION i'm going to get the value that %VERSION% was resolved to. From running echo $VERSION in the container, i can see that the VERSION env variable doesn't actually get changed into the resolved version, the environment variable remains SNAPSHOT. So haveing the wording of the docs being that you get the enviromnent variable isn't technically correct. 

I know that for VERSION we do have DECLARED_VERSION to get the original value, but that doesn't really change the fact that the environment variable for VERSION is still SNAPSHOT and based off the wording of the docs, that means that currently putting %VERSION% should give me the environment variable and not the resolved value.

maybe something like this would make a bit more sense

![image](https://github.com/itzg/docker-minecraft-server/assets/26787639/b2e0e661-5c57-414b-8151-977b4074a33e)

**Comment by nmills3** [comment]
Also take what i say here with a grain of salt, I am autistic so it's also possible i'm overcomplicating this a bit. Sorry in advance

**Comment by itzg** [comment]
I like your suggested wording and I'll go with that.

**Comment by itzg** [comment]
@nmills3, @hpf3 , I'm going to close this, but let me know if you find any issues with it as you use it and I'll re-open.

**Comment by hpf3** [comment]
the name replacement has been working well for what is available, but, can the ftb version also be available for replacement?
I went looking around and it seems the output of the API call used to get the id in the ftba start-deploy could be re-used to get the version by using .name instead of .id
