### ISSUE TITLE
Can't build Dockerfile  /bin/sh: 1: /build/run.sh: not found

### ISSUE THREAD

**Issue by DerTyp7** [itzg/docker-minecraft-server#2506]
### Describe the problem

I've tried building the Dockerfile myself with this command `docker build -t XXX .`.
I tried almost all possible combinations with `--no-cache` or the docs/build.md.
But it's always crashing with this error message.

I have even tried to clone it directly into my Ubuntu WSL and instantly building it without touching anything.

I'm using the master branch.

Docker Version: 24.0.7
### Container definition

```
docker build --no-cache -t itzg/minecraft-server:latest .
```

### Container logs

```
 => [minecraft] https://github.com/itzg/easy-add/releases/download/0.8.1/easy-add_linux_amd64                        12.2s
 => ERROR [minecraft stage-0  2/19] RUN --mount=target=/build,source=build     REV=1 TARGET=amd64 /build/run.sh inst  0.4s
------
 > [minecraft stage-0  2/19] RUN --mount=target=/build,source=build     REV=1 TARGET=amd64 /build/run.sh install-packages:
0.237 /bin/sh: 1: /build/run.sh: not found
------
failed to solve: process "/bin/sh -c REV=${BUILD_FILES_REV} TARGET=${TARGETARCH}${TARGETVARIANT} /build/run.sh install-packages" did not complete successfully: exit code: 127
```

**Comment by DerTyp7** [comment]
Formatting all relevant files with `dos2unix` worked.

**Comment by itzg** [comment]
You may want to double check your git configuration 

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings
