### ISSUE TITLE
Add error when MEMORY is not set

### ISSUE THREAD

**Issue by askiiart** [itzg/docker-minecraft-server#2555]
### Enhancement Type

Not sure

### Describe the enhancement

Since the `MEMORY` variable is required on newer Minecraft versions, it would be helpful if it threw an error if it isn't set. This was a breaking change, yet I had no idea about it until I searched through GitHub issues to find out why my server was constantly throwing OOM errors.

**Comment by itzg** [comment]
It has defaulted to "1G" this whole time:

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options/#memory-limit

I don't why it should be an error when the user hasn't changed it from the default especially since 1GB is still sufficient baseline for most server types.

If you're getting OOM errors then it's you need to increase it from the default.

**Comment by askiiart** [comment]
> It has defaulted to "1G" this whole time:
> 
> https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options/#memory-limit
> 
> I don't why it should be an error when the user hasn't changed it from the default especially since 1GB is still a sufficient baseline for most server types.
> 
> If you're getting OOM errors then you need to increase it from the default or perhaps your host host doesn't have sufficient free memory to allocate the requested amount. Set `DEBUG_MEMORY` to "true" to see memory usage info at startup:
> 
> https://docker-minecraft-server.readthedocs.io/en/latest/misc/troubleshooting/

Hmm that's interesting, I was running a Spigot server with a few mods. But now that I think about it, having 2 worlds (a creative and survival world) probably increases the memory required by quite a bit. I increased `MEMORY` to "2G" and it works perfectly.

BTW I had ~12GB of RAM in the buffer cache, and even after clearing that I was still getting OOM errors, so the host definitely had enough memory XD

And I'm sorry about the tone in the original post, I just assumed it was a breaking change because it used to work fine, but my guess is that it just broke because the worlds expanded too much.

**Comment by itzg** [comment]
It's all good. I'm glad to hear a simple memory increase resolved it.
