### ISSUE TITLE
Automated Backups

### ISSUE THREAD

**Issue by c2technology** [itzg/docker-minecraft-server#256]
Would there be a way to implement automatic backups?
I know manually the process would be something like:
```
rcon-cli save-off
rcon-cli save-all
tar --create --gzip -vv --directory="/data" --file="/backups/backup_`date '+%Y%m%d'`.tar.gz" "./"
rcon-cli save-on
```
You could always mount a separate volume to the `/backups` folder for handling of the file (offsite, archive, etc)

**Comment by itzg** [comment]
Yeah, that feels like something that I could add to the server running wrapper

https://github.com/itzg/mc-server-runner

**Comment by itzg** [comment]
@rayntheleach, your comment on #202 reminded me to go looking for this issue.

@c2technology , my apologies, I had forgotten about this issue when I finally created a sidecar mechanism for automated backups

https://github.com/itzg/docker-mc-backup

This is now a standard part of my home server recipe for Minecraft servers. It works very nicely in Kubernetes where pods are designed to easily run several containers each; however, this can also be utilized with Docker itself too.

**Comment by itzg** [comment]
Here is the deployment file I use that shows the persistent volume claim declaration needed for the backup container:

https://gist.github.com/itzg/13d60211213489d138a07b785d2697af#file-mc-deployment-yaml

**Comment by onezero1010101** [comment]
@itzg I am attempting to deploy your mc-backup with your minecraft-server, but I am not using Kubernetes, and you indicated that you could do this with Docker itself?  I can't get my docker-compose file to come up for the backup.  Keep getting an error.  Any insight?

`ERROR: readlink /var/lib/docker/overlay2/1: invalid argument`

**Comment by itzg** [comment]
@onezero1010101 , I just added an example over here https://github.com/itzg/docker-mc-backup#docker-compose that approximates what happens with the kubernetes pod setup.

**Comment by itzg** [comment]
I'll close this issue since I believe the original goal was accomplished by https://github.com/itzg/docker-mc-backup

**Comment by onezero1010101** [comment]
@itzg Yea my bad, I had some sort of cache issue in docker itself that was causing my error.  Your side-car is great!

**Comment by Frederick888** [comment]
Sorry for commenting on an old issue. I'm wondering if `save-all flush` should be used instead, or `save-all` is blocking already?

According to https://minecraft.fandom.com/wiki/Commands/save#save-all,

> Saves the server to the data storage device. Causes the server to mark all chunks and player data as needing to be saved. They are saved over time until all are flushed to the data storage device.
> 
> Syntax
>
>   save-all
>    Normal mode.
> 
> save-all flush
>    All the chunks are saved to the data storage device immediately, freezing the server for a short time.

It sounds like `save-all` basically queues the saving jobs up then process them later asynchronously, so in theory if you start backing up files right after issuing `save-all`, the queue may not have been cleared yet and the archive can be inconsistent. Or `rcon-cli save-all` already waits for the queue to be cleared?
