### ISSUE TITLE
Aikar flags memory check will fail if memory is set to empty value

### ISSUE THREAD

**Issue by MelonCode** [itzg/docker-minecraft-server#2567]
### Describe the problem

Hi everyone, just ran into following issue 
[The doc states](https://docker-minecraft-server.readthedocs.io/en/latest/configuration/jvm-options/)

> To let the JVM calculate the heap size from the container declared memory limit, unset MEMORY with an empty value, such as -e MEMORY="". 

While that works great, it would produce error if you try to use it with `USE_AIKAR_FLAGS=true` because of the following line 

https://github.com/itzg/docker-minecraft-server/blob/cbd1e8d86d56d6aa9904b94330bfa4d5bccc615c/scripts/start-finalExec#L142

### Container logs

```
mc-primary-1     | /start-utils: line 160: -1: substring expression < 0
mc-primary-1     | /start-finalExec: line 142: ((: >= 12884901888 : syntax error: operand expected (error token is ">= 12884901888 ")
mc-primary-1     | [init] Using Aikar's flags
mc-primary-1     | [init] Starting the Minecraft server...
mc-primary-1     | WARNING: Using incubator modules: jdk.incubator.vector
mc-primary-1     | Starting org.bukkit.craftbukkit.Main
mc-primary-1     | System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.9+9) Host: Linux 5.10.16.3-microsoft-standard-WSL2 (amd64)
mc-primary-1     | Loading libraries, please wait...
```

**Comment by itzg** [comment]
Thanks for reporting this.

**Comment by MelonCode** [comment]
Glad to help! 

Thanks for your work and for quick fix!
Happy New Year, btw!
