### ISSUE TITLE
"Version is 1.37.7"

### ISSUE THREAD

**Issue by RealBrengineer** [itzg/docker-minecraft-server#2595]
### Describe the problem

I've had this exact same issue with every yaml I've tried, from the vanilla one to the one in the paste.

### Container definition

version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      MODRINTH_PROJECTS: "asguhoserver"
      MEMORY: "5G"
      MAX_MEMORY: "5G"
      DIFFICULTY: "normal"
      MAX_PLAYERS: "8"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: "0"
      VIEW_DISTANCE: "12"
      ONLINE_MADE: "false"
      SIMULATION_DISTANCE: "8"
    volumes:
      - data:/data

volumes:
  data: {}

### Container logs

minecraft-server-mc-1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Jan 15 21:30 /data'
minecraft-server-mc-1  | [init] Resolving type given FABRIC
minecraft-server-mc-1  | [mc-image-helper] 21:30:33.998 ERROR : 'install-fabric-loader' command failed. Version is 1.37.7
minecraft-server-mc-1  | reactor.core.Exceptions$ReactiveException: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: meta.fabricmc.net/188.114.96.4:443
minecraft-server-mc-1  |        at reactor.core.Exceptions.propagate(Exceptions.java:408)
minecraft-server-mc-1  |        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
minecraft-server-mc-1  |        at reactor.core.publisher.Mono.block(Mono.java:1712)
minecraft-server-mc-1  |        at me.itzg.helpers.fabric.FabricLauncherInstaller.installUsingVersions(FabricLauncherInstaller.java:68)
minecraft-server-mc-1  |        at me.itzg.helpers.fabric.InstallFabricLoaderCommand.call(InstallFabricLoaderCommand.java:93)
minecraft-server-mc-1  |        at me.itzg.helpers.fabric.InstallFabricLoaderCommand.call(InstallFabricLoaderCommand.java:15)
minecraft-server-mc-1  |        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
minecraft-server-mc-1  |        at picocli.CommandLine.access$1500(CommandLine.java:148)
minecraft-server-mc-1  |        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
minecraft-server-mc-1  |        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
minecraft-server-mc-1  |        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
minecraft-server-mc-1  |        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
minecraft-server-mc-1  |        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
minecraft-server-mc-1  |        at picocli.CommandLine.execute(CommandLine.java:2170)
minecraft-server-mc-1  |        at me.itzg.helpers.McImageHelper.main(McImageHelper.java:157)
minecraft-server-mc-1  |        Suppressed: java.lang.Exception: #block terminated with an error
minecraft-server-mc-1  |                at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
minecraft-server-mc-1  |                ... 13 common frames omitted
minecraft-server-mc-1  | Caused by: io.netty.channel.AbstractChannel$AnnotatedNoRouteToHostException: null: meta.fabricmc.net/188.114.96.4:443
minecraft-server-mc-1  | Caused by: java.net.NoRouteToHostException: null
minecraft-server-mc-1  |        at io.netty.channel.unix.Errors.newConnectException0(Errors.java:158)
minecraft-server-mc-1  |        at io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
minecraft-server-mc-1  |        at io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
minecraft-server-mc-1  |        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
minecraft-server-mc-1  |        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
minecraft-server-mc-1  |        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
minecraft-server-mc-1  |        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
minecraft-server-mc-1  |        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
minecraft-server-mc-1  |        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
minecraft-server-mc-1  |        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
minecraft-server-mc-1  |        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
minecraft-server-mc-1  |        at java.base/java.lang.Thread.run(Unknown Source)
minecraft-server-mc-1  | [init] ERROR failed to install Fabric launcher given LATEST, LATEST, LATEST

**Comment by itzg** [comment]
Something is wrong with your network and/or docker installation:

```
NoRouteToHostException: null: meta.fabricmc.net/188.114.96.4:443
```

**Comment by RealBrengineer** [comment]
> Something is wrong with your network and/or docker installation:
> 
> ```
> NoRouteToHostException: null: meta.fabricmc.net/188.114.96.4:443
> ```

Ah I got it, I had a fundamental misunderstanding (I think) I reserved an IP for my server on my router and also had my network interface set to have a static IP in /etc/network/interfaces, after changing it back to dhcp everything works seamlessly.
Thank you!

**Comment by dhafindzahin** [comment]
@RealBrengineer 
Can you elaborate more with what you did wrong. I'm also getting the exact same error and my server is also using static IP like you mention. Is the only solution to use dhcp IP? because I want to use static IP.

**Comment by RealBrengineer** [comment]
> @RealBrengineer Can you elaborate more with what you did wrong. I'm also getting the exact same error and my server is also using static IP like you mention. Is the only solution to use dhcp IP? because I want to use static IP.

I'm not really sure what exactly caused the problem, but to get a "static" IP I had reserved an IP on my router for my server (still using dhcp). Additionally I had set up a static IP in my network interface in /etc/network/interfaces, I think this was the cause of the issue because after changing it back to dhcp everything works (and I still have my static IP due to always having the same dhcp address be assigned)

**Comment by itzg** [comment]
I'm wondering if that was just a coincidental fix with the router being restarted. So, @dhafindzahin perhaps restart your router. Otherwise Google for "no route to host" -- it's not a problem unique to this image or docker.
