### ISSUE TITLE
umask as env variable

### ISSUE THREAD

**Issue by Gjermundhp02** [itzg/docker-minecraft-server#2599]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

For a project I'm doing i need more restrictive file permissions in the data directory. (750)

umask is already in the /start file and it would be nice to have it as an environment variable.
```
-umask 0002
+umask "${UMASK:=0002}"
```

**Comment by itzg** [comment]
Great idea. A PR would be glad accepted if you want to submit that.
