### ISSUE TITLE
Autopause freeing memory

### ISSUE THREAD

**Issue by Player505** [itzg/docker-minecraft-server#2641]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I'm not sure if this is even possible as it might be a limitation with java but is there a way to have the auto-pause functionality free up memory when paused? 

This would be useful when running multiple server instances on one box where the sum of the allocated memory for each instance exceeds the amount of memory avalible but only one or two instances aren't paused at a time.

**Comment by itzg** [comment]
That's a reasonable request, but is impossible. It's simply a Linux-process thing -- a paused process still holds on to the memory that it was allocated. If you have swap enabled then the kernel will page out the inactive memory.

Instead take a look at https://docker-minecraft-server.readthedocs.io/en/latest/misc/autopause-autostop/autostop/ or https://docker-minecraft-server.readthedocs.io/en/latest/misc/examples/#lazytainer-stop-minecraft-container-based-on-traffic
