### ISSUE TITLE
Ketting Server Jar's are deprecated and have been rolled out

### ISSUE THREAD

**Issue by C0D3-M4513R** [itzg/docker-minecraft-server#2650]
Ketting server jars are depracticed.
They will be rolled out and unsupported when the Ketting team tests the new kettinglauncher to their statisfaction.

We reserve the right to make releases for other versions as we see fit after 1.20.2 server jars have been discontinued.

Please use the new kettinglauncher for Ketting 1.20.1, 1.20.2, (1.20.3 unsupported, only released as an intermediate step), 1.20.4.

Please note that all arguments can also be set via jvm property flags or environment variables.
That part is just not documented in the Readme, but still considered part of the cli api.
(https://github.com/kettingpowered/kettinglauncher/blob/9e68154b78d554453701769f6573b0cb6b9bcdd0/src/main/java/org/kettingpowered/launcher/Args.java#L70)

https://github.com/kettingpowered/kettinglauncher

Currently you cannot set explicit versions with the kettinglauncher.
This is something I want to add though.
edit: seems like my edit did not go through, but support for this was added in 1.3.0

The new Ketting version string goes like this btw: `MCVersion-ForgeVersion-KettingVersion`
Where `KettingVersion` is also of the form: `x.y.z`

Disclaimer, I am a co-owner and dev of Kettingpowered/Ketting.
@itzg

**Comment by itzg** [comment]
Thanks for letting me know about the change. 

> Currently you cannot set explicit versions with the kettinglauncher.
> This is something I want to add though.
> 
> The new Ketting version string goes like this btw: MCVersion-ForgeVersion-KettingVersion
> Where KettingVersion is also of the form: x.y.z

I'm a bit confused then since I see 

![image](https://github.com/itzg/docker-minecraft-server/assets/988985/e5727282-97cd-414a-8b4e-b181b3f5caef)

Are none of these supported?

Or are all of these required? Can a user give just Minecraft version and the latest is used of the other two? With Forge is it latest or recommended version?

Where is the MCVersion-ForgeVersion-KettingVersion needed as input?

**Comment by C0D3-M4513R** [comment]
all of then are supported as of version 1.3.0.
For the `-minecraftVersion` it is required for the first start.
When the `library` folder is properly initialized, it is not required anymore however.

`-forgeVersion` and `-kettingVersion` are entirely optional. If they are not set, the launcher will just launch the most recent version.

**Comment by C0D3-M4513R** [comment]
Also why exactly are you confused by the footnotes?

**Comment by itzg** [comment]
> Also why exactly are you confused by the footnotes?
> 
> Because they were by the arguments instead of the description?

I wasn't confused by the footnotes. I was confused by the text I quoted from your initial issue description.

**Comment by itzg** [comment]
Hmm, this launcher sounds counterproductive to the automation I have built in https://github.com/itzg/mc-image-helper. I think I would rather work with the maven metadata similar to others I have implemented. 

I also don't like that users don't seem to have an upgrade path if it ignores the given Minecraft version on subsequent startups.

**Comment by C0D3-M4513R** [comment]
> I also don't like that users don't seem to have an upgrade path if it ignores the given Minecraft version on subsequent startups.

It doesn't ignore the minecraft version. It is simply inferred, if it isn't given.
If you manually specify a different minecraft Version, kettinglauncher will make sure to start
that version

**Comment by itzg** [comment]
Specifically I'd prefer to implement it like I do for NeoForge

https://github.com/itzg/mc-image-helper/blob/master/src/main/java/me/itzg/helpers/forge/NeoForgeInstallerResolver.java

**Comment by C0D3-M4513R** [comment]
Miscommunications cleared up in Discussed: https://discord.com/channels/660567679458869252/660569755320844308/1205949288660865094

It seems like one of my edits after releasing kettinglauncher 1.3.0 was not properly saved.
Sorry for the confusion.

**Comment by itzg** [comment]
@C0D3-M4513R why is it prompting for EULA even though I already have a eula.txt file with eula set:

```
WARNING: It appears you have not agreed to the EULA.
Please read the EULA (https://www.minecraft.net/eula) and type 'yes' to continue.
Do you accept? (yes/no): Exception in thread "main" java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)
        at org.kettingpowered.launcher.betterui.BetterUI.checkEula(BetterUI.java:104)
        at org.kettingpowered.launcher.KettingLauncher.init(KettingLauncher.java:131)
        at org.kettingpowered.launcher.Main.main(Main.java:184)

> cat .\eula.txt
eula=true
```

And where are all the files being stored? The current working directory is empty even though it has done the "Loading libs" step.

**Comment by C0D3-M4513R** [comment]
> why

The files are all stored in the directory the kettinglauncher.jar is in.

**Comment by itzg** [comment]
(Posting a note here for posterity)

> The files are all stored in the directory the kettinglauncher.jar is in.

That was the part I wasn't expecting. I was expecting the files in the current working directory.
