### ISSUE TITLE
Auto Pause Not Compatable with `SERVER_PORT` - Still Uses 25565

### ISSUE THREAD

**Issue by harrismcc** [itzg/docker-minecraft-server#2666]
### Describe the problem

When using the auto pause feature and `SERVER_PORT` the container crashes with the debug line:
```
+++ mc-monitor status --host localhost --port 25565 --show-player-count
failed to ping localhost:25565 : could not connect to Minecraft server: dial tcp 127.0.0.1:25565: connect: connection refused++ connections=
```

It seems like mc-monitor is still using the default 25565 port instead of the port set by `SERVER_PORT`

### Container definition

env vars:
```
        EULA=true
        TYPE=MODRINTH
        VERSION=1.20.1
        MODRINTH_LOADER=fabric
        MODRINTH_MODPACK=[redacted]
        MODRINTH_EXCLUDE_FILES=e4mc

        # JVM config
        MEMORY=2G
        # Auto Pause
        ENABLE_AUTOPAUSE=true
        AUTOPAUSE_KNOCK_INTERFACE=eth0
        DEBUG_AUTOPAUSE=true
        AUTOPAUSE_TIMEOUT_EST=15
        AUTOPAUSE_TIMEOUT_INIT=15
```

### Container logs

```
+ isTrue true
+ case "${1,,}" in
+ return 0
+ log 'DEBUG: autopause state = S'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ case X$STATE in
+ rcon_client_exists
++ ps -ax -o comm
++ grep rcon-cli
+ [[ -n '' ]]
+ java_running
++ ps -ax -o stat,comm
++ grep java
++ awk '{ print $1 }'
+ [[ Tl =~ ^S.*$ ]]
+ [[ S == \S ]]
+ sleep 5
+ :
+ isTrue true
+ case "${1,,}" in
+ return 0
+ log 'DEBUG: autopause state = S'
+ local oldState
++ shopt -po xtrace
+ oldState='set -o xtrace'
+ shopt -u -o xtrace
+ case X$STATE in
+ rcon_client_exists
++ ps -ax -o comm
++ grep rcon-cli
+ [[ -n '' ]]
+ java_running
++ ps -ax -o stat,comm
++ grep java
++ awk '{ print $1 }'
+ [[ Sl =~ ^S.*$ ]]
+ java_clients_connected
++ java_clients_connections
++ local connections
++ java_running
+++ ps -ax -o stat,comm
+++ grep java
+++ awk '{ print $1 }'
++ [[ Sl =~ ^S.*$ ]]
+++ mc-monitor status --host localhost --port 25565 --show-player-count
failed to ping localhost:25565 : could not connect to Minecraft server: dial tcp 127.0.0.1:25565: connect: connection refused++ connections=
++ connections=1
++ echo 1
+ ((  1 > 0  ))
+ logAutopause 'Client connected - waiting for disconnect'
+ echo '[Autopause loop] Client connected - waiting for disconnect'
+ STATE=E
+ [[ E == \S ]]
+ sleep 10
```

**Comment by itzg** [comment]
I don't see `SERVER_PORT` in your environment variables. Did you manually change the port in `server.properties` instead? In any case, there's very little reason to change the listening port since the port mapping can resolve host level conflicts.

**Comment by harrismcc** [comment]
Okay, I think I see. I'm using a non-25565 port externally, but I'm mapping it to 25565 internally so it's correct from the containers' perspective. Sorry for the confusing, but I think the behavior is correct.

Any ideas why it would be crashing with that connection issue line? If it's not the port then it's some other issue?

**Comment by itzg** [comment]
What you are showing seems normal before the server is ready, so please provide the full startup logs that includes the line that looks like the following:

```
[21:09:27] [Server thread/INFO]: Starting Minecraft server on *:25566
```

Quickly troubleshooting with the following, I am not able to recreate any issue with using `SERVER_PORT` and auto-pause:

```
docker run -it --rm -e EULA=true -e ENABLE_AUTOPAUSE=true -e SERVER_PORT=25566 -e DEBUG=true itzg/minecraft-server
```

**Comment by itzg** [comment]
Thanks for providing the logs. I see no mention of "could not connect" in those logs.

**Comment by harrismcc** [comment]
It seems to be working now, I'm guessing that `MAX_TICK_TIME` was the real fix here. I'll continue to monitor it over the course of today and if it's still working then I'll close this ticket. Thanks!
