### ISSUE TITLE
 ERROR: could not locate path that contains java

### ISSUE THREAD

**Issue by famsad** [itzg/docker-minecraft-server#2695]
### Describe the problem

Creating new or modifiying old images results in this error: 
{"log":"[init] ERROR: could not locate path that contains java\n","stream":"stdout","time":"2024-03-04T15:51:41.81031473Z"}
{"log":"[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 1 1000 1000 132 Mar  4 14:39 /data'\n","stream":"stdout","time":"2024-03-04T15:51:42.611688654Z"}
{"log":"[init] ERROR: your Docker provider has an annoying flaw where it\n","stream":"stdout","time":"2024-03-04T15:51:42.613631589Z"}
{"log":"[init]        tries to set PATH even though the container establishes\n","stream":"stdout","time":"2024-03-04T15:51:42.614245718Z"}
{"log":"[init]        a very specific value.\n","stream":"stdout","time":"2024-03-04T15:51:42.614890066Z"}

however, running old servers that update themselves have no issues finding java or the PATH variable.
Even when I check the Path variables manually they are the same.
In an old thread there was something about JAVA 19, but the server is configured to use java 17.

Currently I am using Portainer and openSUSE and I cant find the error atm.
It may be an setting Error on my side as I updated Portainer a few weeks back, but as old images run fine and just the newly/modified version are having this problem I am just maybe missing something.

ENV:
EULA=true
DIFFICULTY=normal
MOTD=Bitches get Bitches
SPAWN_PROTECTION=0
ONLINE_MODE=true
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_ALL=en_US.UTF-8
JAVA_HOME=/opt/java/openjdk
UID=1000
GID=1000
MEMORY=10G
VERSION=LATEST
ENABLE_RCON=true
RCON_PORT=25575
ENABLE_AUTOPAUSE=false
AUTOPAUSE_TIMEOUT_EST=3600
AUTOPAUSE_TIMEOUT_KN=120
AUTOPAUSE_TIMEOUT_INIT=600
AUTOPAUSE_PERIOD=10
AUTOPAUSE_KNOCK_INTERFACE=eth0
JAVA_VERSION=jdk-17.0.7+7
SEED=
TYPE=SPIGOT
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SPIGET_RESOURCES=64346,60383,85548,59773,62325,91310,81069,74188

Sorry for the inconvenience! 

### Container definition

version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}

### Container logs

{"log":"[init] ERROR: could not locate path that contains java\n","stream":"stdout","time":"2024-03-04T15:51:41.81031473Z"}
{"log":"[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 1 1000 1000 132 Mar  4 14:39 /data'\n","stream":"stdout","time":"2024-03-04T15:51:42.611688654Z"}
{"log":"[init] ERROR: your Docker provider has an annoying flaw where it\n","stream":"stdout","time":"2024-03-04T15:51:42.613631589Z"}
{"log":"[init]        tries to set PATH even though the container establishes\n","stream":"stdout","time":"2024-03-04T15:51:42.614245718Z"}
{"log":"[init]        a very specific value.\n","stream":"stdout","time":"2024-03-04T15:51:42.614890066Z"}

**Comment by itzg** [comment]
The error states the problem. Remove Portainer's setting of the PATH -- it **must** be the one provided by the image.

**Comment by famsad** [comment]
OK so we tried a few things out.
As it seems this issue persists when trying to start the container directly via ssh and docker and default settings.
so portainer doesnt seem to be the problem here.
Do you have any suggestions what to try ?

**Comment by itzg** [comment]
Can you provide the direct docker command you tried? Also, did you try removing the PATH variable from container declaration?

**Comment by darkweasel77** [comment]
Same problem - but i'm just using docker-compose on ubuntu

**Comment by Supermathie** [comment]
@itzg something is off with the image itself; the `which` command is broken!

this is image ID `sha256:c8d5602ac142f302840664939034f5f49c1515ec9804513385b3e3aee5b157ce`
```
michael@andor:~$ docker run --rm -it --entrypoint /bin/bash itzg/minecraft-server:latest
root@0203bc88cd5a:/data# echo $PATH
/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@0203bc88cd5a:/data# which java
root@0203bc88cd5a:/data# echo $?
1
root@0203bc88cd5a:/data# command -v java
/opt/java/openjdk/bin/java
root@0203bc88cd5a:/data# java --version
[0.012s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.013s][error  ][gc,task  ] Failed to create worker thread
```

(also… java --version doesn't work… that failure to start looks bad ☹)
contrast with an earlier version:

```
michael@andor:~$ docker run --rm -it --entrypoint /bin/bash itzg/minecraft-server:java19
root@31df96ba4081:/data# echo $PATH
/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@31df96ba4081:/data# which java
/opt/java/openjdk/bin/java
root@31df96ba4081:/data# echo $?
0
root@31df96ba4081:/data# command -v java
/opt/java/openjdk/bin/java
root@31df96ba4081:/data# java --version
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment Temurin-19.0.2+7 (build 19.0.2+7)
OpenJDK 64-Bit Server VM Temurin-19.0.2+7 (build 19.0.2+7, mixed mode, sharing)
```

**Comment by itzg** [comment]
FYI `java -version` (single dash) is the backward compatible invocation.

Make sure you are re-pulling the image variants as you're testing. java21-jdk (along with every other variant I tried) resolves fine for me:

```
> docker image inspect itzg/minecraft-server:java21-jdk -f '{{.Id}} {{json .Config.Labels}}'
sha256:43bd4b435c8940b66bce60e202f1485162cf2bb64591acd85f83a04992f1919e {"org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.created":"2024-07-06T17:22:17.884Z","org.opencontainers.image.description":"Docker image that provides a Minecraft Server that will automatically download selected version at startup","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.ref.name":"ubuntu","org.opencontainers.image.revision":"67b790dfed04038178c97a491e75b32e3f5749f0","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.title":"docker-minecraft-server","org.opencontainers.image.url":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java21-jdk"}

> docker run --rm --entrypoint bash itzg/minecraft-server:java21-jdk -c 'which java; java -version'
/opt/java/openjdk/bin/java
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```

**Comment by Supermathie** [comment]
That's the same image as I was testing yesterday (freshly pulled):

```
michael@andor:~$ docker image inspect itzg/minecraft-server:java21-jdk -f '{{.Id}} {{json .Config.Labels}}'
sha256:43bd4b435c8940b66bce60e202f1485162cf2bb64591acd85f83a04992f1919e {"org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.created":"2024-07-06T17:22:17.884Z","org.opencontainers.image.description":"Docker image that provides a Minecraft Server that will automatically download selected version at startup","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.ref.name":"ubuntu","org.opencontainers.image.revision":"67b790dfed04038178c97a491e75b32e3f5749f0","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.title":"docker-minecraft-server","org.opencontainers.image.url":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java21-jdk"}
```

today it's a new version with:

```
michael@andor:~$ docker image inspect itzg/minecraft-server:java21-jdk -f '{{.Id}} {{json .Config.Labels}}'
sha256:9adf763665bbe04c1fca2bc2c6cdff95abf572878043db9d12aabc91de119dd6 {"org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.created":"2024-07-08T19:14:28.749Z","org.opencontainers.image.description":"Docker image that provides a Minecraft Server that will automatically download selected version at startup","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.ref.name":"ubuntu","org.opencontainers.image.revision":"4232a981e8d3f4d772a5800ed00d25e4db5b66e8","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.title":"docker-minecraft-server","org.opencontainers.image.url":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java21-jdk"}

michael@andor:~$ docker run --rm --entrypoint bash itzg/minecraft-server:java21-jdk -c 'which java; java -version'
[0.145s][warning][os,thread] Failed to start thread "GC Thread#0" - pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
[0.146s][error  ][gc,task  ] Failed to create worker thread
```

still no output from `which`

A fresh pull today of java21-alpine still works:
```
michael@andor:~$ docker image inspect itzg/minecraft-server:java21-alpine -f '{{.Id}} {{json .Config.Labels}}'
sha256:3699ee64fb9c8ab73b20a837f9c1414907c00b48f0b1492d0dbaf58822a71e9a {"org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.created":"2024-07-08T19:14:28.025Z","org.opencontainers.image.description":"Docker image that provides a Minecraft Server that will automatically download selected version at startup","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.revision":"4232a981e8d3f4d772a5800ed00d25e4db5b66e8","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.title":"docker-minecraft-server","org.opencontainers.image.url":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java21-alpine"}

michael@andor:~$ docker run --rm --entrypoint bash itzg/minecraft-server:java21-alpine -c 'which java; java -version'
/opt/java/openjdk/bin/java
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+9 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+9 (build 21.0.3+9-LTS, mixed mode, sharing)
```

possibly something about one of my layers is bad, or maybe it's the docker version on this machine (very strange symptoms though) as it's a bit old… will investigate

**Comment by itzg** [comment]
@Supermathie it's likely a difference with your kernel and/or a setting like huge pages looking again at

```
pthread_create failed (EPERM) for attributes: stacksize: 1024k, guardsize: 4k, detached.
```

**Comment by Supermathie** [comment]
Possibly, yeah, though the problem with `which` not working points to a more severe underlying problem to fix first.
