### ISSUE TITLE
Make Java configuration easier

### ISSUE THREAD

**Issue by Morgandri1** [itzg/docker-minecraft-server#2702]
### Enhancement Type

A completely new feature

### Describe the enhancement

Hello!
I'm using railway, and I'd love to be able to set java version using the environment variables. This should be relatively easy, but i'd love feedback on the idea.

**Comment by itzg** [comment]
Please read the documentation:

https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/

Since the Java installation must be part of the base image it is not trivial nor prudent to install almost twenty versions of Java into one image. Can you image how huge the image size would be?

**Comment by itzg** [comment]
...besides in most cases the Java 17 (aka `latest`) will suffice for modern versions of Minecraft. Java 8 suffices for all others.
