### ISSUE TITLE
Memory usage stuck at 1.6G

### ISSUE THREAD

**Issue by JTT-JustTheTip** [itzg/docker-minecraft-server#271]
I have a FTB server with a custom modpack on it, I tried setting new memory settings for it as shown below

INIT_MEMORY: '4G'
MAX_MEMORY: '6G'

But every time I check the portainer stats it's showing 1.6G usage despite being setting the server to initial memory of 4G. I know that it's reading the parameters correctly as when I watch the logs on startup it says it's setting the memory to 4-6G

Any ideas why it's doing this?

**Comment by itzg** [comment]
I picked one at random like [Sky Adventure](https://www.feed-the-beast.com/projects/ftb-sky-adventures) and noticed its start script isn't accepting the `MIN_RAM` setting like before. I published a change to Docker Hub that passes the `-Xms` via their new parameter, but I'm still seeing `docker stats` report less memory usage than the "INIT" value I passed.

Can you see if the latest image makes a difference for you?

**Comment by JTT-JustTheTip** [comment]
Ive pulled the new image and it seems to have the memory utilisation on the container at 4G upon starting which is a good sign. Ill continue to monitor it. 

On a side note ive notice this allot in my logs (both pre and post new image)
`[00:57:30] [Server thread/WARN] [minecraft/MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 4034ms behind, skipping 80 tick(s)
`

**Comment by itzg** [comment]
Thanks for the update, that does sound promising.

I see those logs occasionally in mine, but thought it was because I tend to run on underpowered/overloaded hardware. It could also be just a "normal" thing with these FTB server packs since they include a large number of plugins/mods.

**Comment by itzg** [comment]
@JTT-JustTheTip can you double check what CPU architecture got picked up by the JVM by running:

```
docker run --entrypoint java itzg/minecraft-server -version
```

For example, it reports a 64-Bit server for me:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

**Comment by Zephyr928** [comment]
I'm also having this issue where my server has 15 GB available but is only using 1.3GB.  Is there something I can do to fix this?  Thank you.

**Comment by itzg** [comment]
@Zephyr928 which modpack are you using? Each one can have a slightly different startup script so will need to investigate what it’s doing.

**Comment by ooohawk** [comment]
@itzg i met the same issue, i've got a server with 16gb of memory and i set the initial memory to 12gb. it turns out that the container is only using 1.6gb. While checking the server with htop, i saw 4~5 process that is running with virt showing 14gb(preferred initial memory +2, same when i set the initial memory to 4gb,6gb,10gb) in red color(not sure what does that meant)

**Comment by itzg** [comment]
@ooohawk can you provide the "docker run" or compose file you are using for your container?

**Comment by ooohawk** [comment]
@itzg 
```
docker run -d -e VERSION=1.12.2 -e TYPE=FORGE -e MEMORY=12G -e ICON=https://lemon2ee.icu/pictures/catunderlight.png -e OPS=Crabfunny,Lemon2ee_NEU,bobo210514 -e MAX_PLAYERS=10 -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server
```

**Comment by itzg** [comment]
@ooohawk thanks for providing that. How did you identify that the container was only using 1.6gb when htop reports the expected amount of virt memory usage? Also, when you get a chance can you add `-e DEBUG_EXEC=true` and provide the "mc-server-runner" line that is logged after "Starting the Minecraft server"?

**Comment by ooohawk** [comment]
[mc-logs.txt](https://github.com/itzg/docker-minecraft-server/files/4675059/mc-logs.txt)
<img width="805" alt="htopsh" src="https://user-images.githubusercontent.com/43295730/82774980-e563ab80-9e78-11ea-83be-14ea4559cdad.png">
I used to have a server with 8g of memory and i set the initial memory to 4g. while it was running, it occupied 4.6g/8g which i regard as expected number. But this one only takes somewhere between 1.6~2gb of memory.

**Comment by itzg** [comment]
The startup script invoked Java correctly

```
java -XX:+UseG1GC -Xms6G -Xmx6G -Dlog4j.configurationFile=/data/log4j2.xml -jar forge-1.12.2-14.23.5.2854.jar
```

so I’m not sure what Java is doing then.

**Comment by biodrone** [comment]
I seem to be having a similar issue with this as previously reported, but it seems that the script isn't invoking Java correctly. Please see below for my compose file and a snippet of the Java command as seen from htop. Docker stats agrees with htop, in that there's about 4.7GB of memory usage by the container...

`
version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Valhelsia_SERVER-2.2.10.zip
      VERSION: 1.15.2
      OPS: some,minecraft,users
      WHITELIST: some,minecraft,users
      INIT_MEMORY: 8G
      MAX_MEMORY: 12G
    volumes:
      - "minecraft:/data"
      - "modpacks:/modpacks"
    ports:
      - 25565:25565
      - 25575:25575
volumes:
  minecraft:
  modpacks:
`

![minecraft-java-htop](https://user-images.githubusercontent.com/1135584/96970041-fe958480-150a-11eb-818d-9ceff028dffb.png)

**Comment by biodrone** [comment]
Figured this one out @itzg, the ServerStart.sh seems to be written with 4G as default (for CF, at least) and doesn't get changed when the env vars are updated (via compose, for example).
