### ISSUE TITLE
Spigot server is downloaded on start even when server.jar is present

### ISSUE THREAD

**Issue by crenz** [itzg/docker-minecraft-server#2720]
### Describe the problem

I have a working spigot server with a `server.jar` and `spigot_server-1.20.4.jar` present in the data directory.

Even though `FORCE_REDOWNLOAD` is not set, there is an attempt to download the JAR file each time on server start. Since `getbukkit.org` currently is down, this attempt fails.

As a workaround, I have hosted `spigot_server-1.20.4.jar` on my own server and set `SPIGOT_DOWNLOAD_URL` to it. The suggested fix would be to not re-download the server if `server.jar` is present.

### Container definition

```
docker run -v ./test:/data \
    -e TYPE=SPIGOT -e VERSION=1.20.4 \
    -p 25599:25565 -e EULA=TRUE --name mc itzg/minecraft-server 
```

### Container logs

```
[init] Downloading Spigot from https://download.getbukkit.org/spigot/spigot-1.20.4.jar ...
```

**Comment by cchaz003** [comment]
I'm also experiencing this issue as well. Thanks for the tip on using the `SPIGOT_DOWNLOAD_URL` option!

**Comment by itzg** [comment]
Thanks for reporting this. In #2721 I identified a way to both ensure it tries to get an updated copy of that spigot version or fallback to an existing server file if that fails.

**Comment by crenz** [comment]
That was fast, @itzg! Thanks a lot! I suggest to update the documentation as well to indicate that an attempt for download will be made every time, even if FORCE_REDOWNLOAD is not set.

**Comment by itzg** [comment]
Well, there's a subtle difference between an attempt and an actual download is made every time (see curl's `-z` argument), so I think it will only be more confusing than it helps to make a declaration either way.

In any case, I'm going to put a warning on that page that Spigot/Bukkit should no longer be used and Paper used instead. So this is all a moot point since getbukkit has apparently shut down.

**Comment by crenz** [comment]
Great. Thanks for all the work you are doing with these images!
