### ISSUE TITLE
proxy不起作用

### ISSUE THREAD

**Issue by djdjfjfkeocj** [itzg/docker-minecraft-server#2751]
### Describe the problem

[init] ERROR: failed to obtain version manifest from https://piston-meta.mojang.com/v1/packages/505270a5ebc9b400370bdcbb1769a860d1a45562/1.20.4.json (0)

应该是proxy不起作用，我填写的是http://192.168.1.5:20172，在jellyfin上能够生效，所以应该不是代理的问题。
Translation by chatgpt: "It seems that the proxy is not working. I have entered http://192.168.1.5:20172/, which works on Jellyfin, so it shouldn't be a proxy issue."

### Container definition

![屏幕截图 2024-04-02 160527](https://github.com/itzg/docker-minecraft-server/assets/78682444/ce2bbd72-5213-4d15-89bc-2f91ce669419)
![屏幕截图 2024-04-02 160515](https://github.com/itzg/docker-minecraft-server/assets/78682444/9c8270f7-73d0-42a4-8ee0-4cfbb81fb1e7)

### Container logs

![1](https://github.com/itzg/docker-minecraft-server/assets/78682444/ef590c29-83bf-417b-b426-aa16e0ffb1f7)

**Comment by itzg** [comment]
Can you set the environment variable `DEBUG` to "true" and provide those logs?

**Comment by djdjfjfkeocj** [comment]
> DEBUG



> Can you set the environment variable `DEBUG` to "true" and provide those logs?

![debug](https://github.com/itzg/docker-minecraft-server/assets/78682444/6f44bf8a-45d0-4ed7-8d7a-8d64db9eca19)
![配置](https://github.com/itzg/docker-minecraft-server/assets/78682444/dfdf60f4-2682-4669-a54a-448857634688)

我之前的那个删了，这次简单配置了一下，打开了debug，请看看，谢谢
Translation by chatgpt:   ''I deleted the previous one. This time I made a simple configuration and turned on debug. Please take a look. Thank you.''

**Comment by itzg** [comment]
The proxy does not seem to be fully functional. It seems to have correctly handled https://launchermeta.mojang.com/mc/game/version_manifest.json but then is not handling the URL reported in the logs you posted. 

Please post the logs as text next time since it is difficult to work with screenshot images.

**Comment by djdjfjfkeocj** [comment]
> 代理似乎没有完全发挥作用。它似乎正确处理[了 https://launchermeta.mojang.com/mc/game/version_manifest.json](https://launchermeta.mojang.com/mc/game/version_manifest.json) 但随后没有处理您发布的日志中报告的 URL。
> 
> 下次请将日志作为文本发布，因为很难处理屏幕截图图像。

依旧不行  Still no
