### ISSUE TITLE
Minecraft has moved to Java 21 as the default starting 24w14a

### ISSUE THREAD

**Issue by finndo77** [itzg/docker-minecraft-server#2756]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

requesting move for "latest" to java 21

**Comment by finndo77** [comment]
https://www.minecraft.net/en-us/article/minecraft-snapshot-24w14a

**Comment by finndo77** [comment]
confirmed that version=latest works with image java21

**Comment by itzg** [comment]
Good point. Will do.
