### ISSUE TITLE
Autopause fails to start with permission error

### ISSUE THREAD

**Issue by kman1999** [itzg/docker-minecraft-server#2813]
### Describe the problem

The Autopause functionality fails to start when booting the container. An "operation not permitted" error is encountered with the knockd binary file located in /usr/local/sbin.

Expected behavior: Autopause binary should not encounter any permissions errors when the container runs.

Theory: It doesn't look like the permissions of /usr/local/sbin are configured correctly by the Dockerfile. Chmod is called for many directories / binaries / scripts, but not for /usr/local/sbin. Perhaps this is related to starting the container as a user other than uid 1000.

I am not sure how to fix the permission issue with the binary file.

### Container definition

podman run -d \
-v /data/minecraft/data:/data \
-p 25565:25565 \
--env=EULA=TRUE \
--env=TYPE=VANILLA \
--env=VERSION=LATEST \
--env=UID=2002 \
--env=GID=2002 \
--env=INIT_MEMORY=2G \
--env=MAX_MEMORY=4G \
--env=GUI=FALSE \
--env=ENABLE_ROLLING_LOGS=TRUE \
--env=SPAWN_PROTECTION=400 \
--env=ENABLE_AUTOPAUSE=TRUE \
--env=MAX_TICK_TIME=-1 \
--env=DIFFICULTY=normal \
--env=FORCE_GAMEMODE=TRUE \
--network=isolate-mc \
--restart=never \
--name=mc-server \
docker.io/itzg/minecraft-server:2024.5.0-java21

### Container logs

[init] Running as uid=2002 gid=2002 with /data as 'drwx------ 7 2002 2002 4096 May  4 16:05 /data'
[init] Autopause functionality enabled
[init] Resolving type given VANILLA
sudo: unable to execute /usr/local/sbin/knockd: Operation not permitted
[Autopause loop] Failed to start knockd daemon.
[Autopause loop] Probable cause: Unable to attach to interface "eth0".
[Autopause loop] Available interfaces within the docker container:
[Autopause loop]   eth0
[Autopause loop] Please set the environment variable AUTOPAUSE_KNOCK_INTERFACE to the interface that handles incoming connections.
[Autopause loop] If unsure which interface to choose, run the ifconfig command in the container.
[Autopause loop] Autopause failed to initialize. This log entry will be printed every 30 minutes.
[init] Resolved version given LATEST into 1.20.6
[mc-image-helper] 16:05:57.223 INFO  : The file /data/ops.json already exists, so no changes will be made
[init] log4j2.xml already created, skipping
[init] Setting initial memory to 2G and max to 4G
[init] Starting the Minecraft server...
Starting net.minecraft.server.Main
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
[16:06:02] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[16:06:03] [ServerMain/INFO]: Loaded 1175 recipes
[16:06:03] [ServerMain/INFO]: Loaded 1276 advancements
[16:06:03] [Server thread/INFO]: Starting minecraft server version 1.20.6
[16:06:03] [Server thread/INFO]: Loading properties
[16:06:03] [Server thread/INFO]: Default game type: SURVIVAL
[16:06:03] [Server thread/INFO]: Generating keypair
[16:06:03] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:06:03] [Server thread/INFO]: Using epoll channel type
[16:06:03] [Server thread/INFO]: Preparing level "world"
[16:06:04] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[16:06:04] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:06:04] [Worker-Main-5/INFO]: Preparing spawn area: 0%
[16:06:04] [Server thread/INFO]: Time elapsed: 932 ms
[16:06:04] [Server thread/INFO]: Done (1.449s)! For help, type "help"
[16:06:04] [Server thread/INFO]: Starting remote control listener

**Comment by kman1999** [comment]
I ended up digging far enough into other Autopause issues to find the answer. It seems that you must set --cap-add=CAP_NET_RAW for the container in order for Autopause to work correctly. Reference: https://github.com/itzg/docker-minecraft-server/issues/1276#issuecomment-1481897860

Closing this issue thread - however, this container capability requirement should be noted in the docs/readme for this image.

**Comment by itzg** [comment]
I'm glad you figured it out. It is somewhat mentioned in this section

https://docker-minecraft-server.readthedocs.io/en/latest/misc/autopause-autostop/autopause/#rootless-auto-pause

however, it does seem like it could be called out clearer.
