### ISSUE TITLE
Paused Java in User (Rootless) container does not end up in swap

### ISSUE THREAD

**Issue by Doomsdayrs** [itzg/docker-minecraft-server#2829]
### Describe the problem

When using a container that is run by the root user, the paused java memory ends up in swap.

When using a container that is run by a non-root user, the paused java memory does not end up in swap.

Swapping of the memory usually occurs after an hour or so after being paused.

I do not know how to debug this.

### Container definition

[Unit]
Description=Minecraft Java Server with friends
After=network-online.target

[Container]
Image=docker.io/itzg/minecraft-server:latest
ContainerName=Timur-Friends-Java
PublishPort=2459:25565
AutoUpdate=registry
Volume=/home/brother/Minecraft/Servers/friends-darren-java/:/data/:Z
Environment=EULA=TRUE

# Don't use so much memory
Environment=MEMORY=2G

# Autopause
Environment=SKIP_SUDO=true
Environment=ENABLE_AUTOPAUSE=TRUE
Environment=AUTOPAUSE_KNOCK_INTERFACE=tap0
Environment=AUTOPAUSE_TIMEOUT_EST=900
PodmanArgs=--cap-add=CAP_NET_RAW
Network=slirp4netns:port_handler=slirp4netns

[Service]
MemoryMax=2G
RestartSec=30

[Install]
WantedBy=default.target

### Container logs

N/A ?

**Comment by itzg** [comment]
I'm not sure how to proceed either. For anyone that can help, the Java process is "paused" by sending a STOP signal here

https://github.com/itzg/docker-minecraft-server/blob/e1262effef6a17323b556eb18a9d20fdc62314d0/files/auto/pause.sh#L23

**Comment by Doomsdayrs** [comment]
> I'm not sure how to proceed either. For anyone that can help, the Java process is "paused" by sending a STOP signal here

From what I understand, this is perfectly reasonable and likely is not the issue.

What I speculate is something is occurring, that only happens on non-root accounts, that prevents the JVM memory allocation from being considered inactive, thus leading it to be persistently kept in RAM.

**Comment by Doomsdayrs** [comment]
It seemed to have finally start doing it after a server restart.

Huh.

That still does not fully explain everything, but maybe will help others!
