### ISSUE TITLE
Minecraft server - ops not propagated from -e to ops.json

### ISSUE THREAD

**Issue by KimRagnaSchwerdt** [itzg/docker-minecraft-server#283]
Hello,

started container with -e OPS=myplayer but in ops.json in the server the value myplayer is not visible.

This prevents setting the operators.

**Comment by itzg** [comment]
Can you check if there was previously an `ops.txt.converted` file in `/data`? If that's in the way then the startup script will skip the `OPS` handling here:

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start-minecraftFinalSetup#L3-L6

**Comment by KimRagnaSchwerdt** [comment]
content of opts.txt.converted:
my_majong_user
\n
\n
\n

content of ops.json:
[]

thus i think setting the OPS is ommitted or awk command does not works.

Can you fix this?

**Comment by itzg** [comment]
I have double checked this with a couple recent containers I created and has been working for me. As a work around for the current files, you could delete just the ops.txt.converted and ops.json files and restart the container. That will force the startup script to re-process the OPS setting.

**Comment by itzg** [comment]
Thanks @adeleglise that detail will help me try to recreate and hopefully fix the issue.

**Comment by itzg** [comment]
I am still not able to re-create this issue; however, I now realize that it is expected to require manual updates to the ops after the container is already created. You can either modify the `ops.json` file manually and restart the container or better yet, exec into the container and run `rcon-cli op USER_TO_OP`.

Let me know if those options still don't seem to work.

**Comment by Nautigsam** [comment]
@itzg I met the same issue with ops file not being updated with new ops when it already exists. I think that's technically logical but still, by looking at the entrypoint script I think we could always overwrite it when OPS env variable is set. The same applies to whitelist.

**Comment by itzg** [comment]
I wonder if writing new ops into `ops.txt` will result in the minecraft server simply appending to `ops.json` rather than replacing the previous ops there?

**Comment by itzg** [comment]
...wonder no more. I did a quick experiment and found that it always adds to `ops.json`, which is what I was hoping. The latest image (`sha256:d1944914e1f885980c5bac233a5c6ff414a20d1e204e0bd5c7c49af2fce2b616`) now will always update `ops.txt` with the `OPS` variable on every container start.

@KimRagnaSchwerdt and @Nautigsam can you see if this fixes the ops aspect for you?

If so, I'll do the same for the whitelist file.

**Comment by Nautigsam** [comment]
It works well, ops get added to the file. That's great!

**Comment by itzg** [comment]
The latest image also updates the whitelist on every container startup.
