### ISSUE TITLE
Auto-Curseforge Use Server Pack

### ISSUE THREAD

**Issue by hamcoremusic** [itzg/docker-minecraft-server#2855]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

After fighting with getting Better MC 4 [FORGE] working, I realized that when the auto-curseforge downloader works, it uses the Curseforge manifest to grab mods, however all of the mods are not included in the client manifest. An example would be looking at the [relations](https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4/relations/dependencies), you will see that "Crabber's Delight" is not a listed mod, however in their [own supplied mod index](https://www.modpackindex.com/modpack/64026/better-mc-forge-bmc4) it is. The mod is also present in the [actual server pack](https://www.curseforge.com/minecraft/modpacks/better-mc-forge-bmc4/files/5098158).

To avoid this from happening, I think there should be an option to actually grab the server pack for modpacks on Curseforge. It will also eliminate the steps to exclude certain mods cause developers didn't mark them as client only.

If there is a way to force the server pack already please let me know. I have stared at the documentation way too long now.

**Comment by itzg** [comment]
Server modpacks can be used with

https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/curseforge/

but I no longer provide support for that feature since there is very little standardization across server packs.

You may also want to try this Modrinth example of BMC4

https://github.com/itzg/docker-minecraft-server/blob/master/examples/bmc4/docker-compose.yml

**Comment by hamcoremusic** [comment]
Ah okay I see. I feel like some packs benefit from the deprecated Curseforge implementation. I think BMC4 is a special case for this but next time I will probably use Modrinth. I did try the Modrinth docker compose and it resulted in my clients crashing upon join, IDK if it was a mod incompatibility or I missed some "Mods to Download".

Thank you for your insight!

**Comment by itzg** [comment]
> Ah okay I see. I feel like some packs benefit from the deprecated Curseforge implementation.

As you see, it's still an option 😀
