### ISSUE TITLE
Nas session.lock error

### ISSUE THREAD

**Issue by Simy-cup** [itzg/docker-minecraft-server#2866]
### Describe the problem

I got a problem with the session.lock. I run my server on my synology Nas and when i try to upload my world into the world folder im getting an AccessDeniedException error with the session lock. The session lock should have the promissions to write and read.

### Container definition

PATH 
/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

JAVA_HOME
/opt/java/openjdk

JAVA_VERSION
jdk-21.0.2+13

TYPE
PAPER

EULA
TRUE

UID 
1000
GID
1000

MEMORY
4G

### Container logs

2024/06/01 00:13:43 | stdout | [mc-image-helper] 22:13:43.113 INFO  : Resolved paper to version 1.20.6 build 129
2024/06/01 00:13:40 | stdout | [init] Resolving type given PAPER
2024/06/01 00:13:40 | stdout | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 12 1000 1000 4096 May 31 22:04 /data'
2024/06/01 00:13:35 | stdout | [m2024-05-31T22:13:35.764Z INFO mc-server-runner Done
2024/06/01 00:13:35 | stdout | at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
2024/06/01 00:13:35 | stdout | at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
2024/06/01 00:13:35 | stdout | at org.bukkit.craftbukkit.Main.main(Main.java:328) ~[paper-1.20.6.jar:1.20.6-129-0513374]
2024/06/01 00:13:35 | stdout | at net.minecraft.server.Main.main(Main.java:197) ~[paper-1.20.6.jar:1.20.6-129-0513374]
2024/06/01 00:13:35 | stdout | at net.minecraft.world.level.storage.LevelStorageSource.validateAndCreateAccess(LevelStorageSource.java:428) ~[paper-1.20.6.jar:1.20.6-129-0513374]
2024/06/01 00:13:35 | stdout | at net.minecraft.world.level.storage.LevelStorageSource$LevelStorageAccess.<init>(LevelStorageSource.java:522) ~[paper-1.20.6.jar:1.20.6-129-0513374]
2024/06/01 00:13:35 | stdout | at net.minecraft.util.DirectoryLock.create(DirectoryLock.java:23) ~[paper-1.20.6.jar:1.20.6-129-0513374]
2024/06/01 00:13:35 | stdout | at java.base/java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]
2024/06/01 00:13:35 | stdout | at java.base/java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]
2024/06/01 00:13:35 | stdout | at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source) ~[?:?]
2024/06/01 00:13:35 | stdout | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
2024/06/01 00:13:35 | stdout | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
2024/06/01 00:13:35 | stdout | at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
**2024/06/01 00:13:35 | stdout | java.nio.file.AccessDeniedException: ./world/session.lock**
2024/06/01 00:13:35 | stdout | [31;1m[22:13:35 ERROR]: Failed to start the minecraft server
2024/06/01 00:13:34 | stdout | [22:13:34 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
2024/06/01 00:13:26 | stdout | Loading libraries, please wait...
2024/06/01 00:13:26 | stdout | System Info: Java 21 (OpenJDK 64-Bit Server VM 21.0.3+9-LTS) Host: Linux 4.4.302+ (amd64)
2024/06/01 00:13:26 | stdout | Starting org.bukkit.craftbukkit.Main
2024/06/01 00:13:25 | stdout | [init] Starting the Minecraft server...
2024/06/01 00:13:23 | stdout | [init] Setting initial memory to 4G and max to 4G
2024/06/01 00:13:18 | stdout | [mc-image-helper] 22:13:18.346 INFO  : Created/updated 1 property in /data/server.properties
2024/06/01 00:13:13 | stdout | [mc-image-helper] 22:13:13.846 INFO  : Resolved paper to version 1.20.6 build 129
2024/06/01 00:13:11 | stdout | [init] Resolving type given PAPER
2024/06/01 00:13:11 | stdout | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 12 1000 1000 4096 May 31 22:04 /data'
2024/06/01 00:10:28 | stdout | [mc-image-helper] 22:10:28.733 INFO  : Created/updated 1 property in /data/server.properties
2024/06/01 00:10:24 | stdout | [mc-image-helper] 22:10:24.091 INFO  : Resolved paper to version 1.20.6 build 129
2024/06/01 00:10:21 | stdout | [init] Resolving type given PAPER

</body>
</html>

**Comment by itzg** [comment]
You need to ensure it and the world directory are writable by uid 1000.

**Comment by Simy-cup** [comment]
I know what i did wrong.. ( I feel stupid) In the Synology Nas you have to go in the File Manager in the Folder, where all your docker containers are and right click. Then on property. Go to the permissions tab and scroll down to EVERYONE. Change the Promission to READ and WRITE. Deafult is only Read.

articel
https://kb.synology.com/en-nz/DSM/tutorial/Docker_container_cant_access_the_folder_or_file

Thanks anyway
