### ISSUE TITLE
Autocurseforge server not starting. me.itzg.helpers.errors.GenericException: no mods found with slug=mcjw

### ISSUE THREAD

**Issue by vaitamozhetnet** [itzg/docker-minecraft-server#2879]
### Describe the problem

I created a modpack on CF but it doesnt want to work.

### Container definition

services:
  minecraft:
    image: itzg/minecraft-server
    stdin_open: true
    tty: true
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_API_KEY: "$$2a$$10$$9nozKmFiMrhTzo8aRrpuqOrHveGim48QckBjEklRMhLjV8.6mBvWu"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/mcjw/files/5401331"
      VERSION: "1.19.2"
      UID: "1026"
      GID: "100"

### Container logs

2024/06/07 20:11:31 | stdout | at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
2024/06/07 20:11:31 | stdout | at picocli.CommandLine.execute(CommandLine.java:2174)
2024/06/07 20:11:31 | stdout | at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
2024/06/07 20:11:31 | stdout | at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
2024/06/07 20:11:31 | stdout | at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
2024/06/07 20:11:31 | stdout | at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
2024/06/07 20:11:31 | stdout | at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
2024/06/07 20:11:31 | stdout | at picocli.CommandLine.access$1500(CommandLine.java:148)
2024/06/07 20:11:31 | stdout | at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
2024/06/07 20:11:31 | stdout | at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:29)
2024/06/07 20:11:31 | stdout | at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:213)
2024/06/07 20:11:31 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:175)
2024/06/07 20:11:31 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:213)
2024/06/07 20:11:31 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.lambda$install$3(CurseForgeInstaller.java:176)
2024/06/07 20:11:31 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.installByRetrievingModpackZip(CurseForgeInstaller.java:255)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.Mono.block(Mono.java:1712)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
2024/06/07 20:11:31 | stdout | Suppressed: java.lang.Exception: #block terminated with an error
2024/06/07 20:11:31 | stdout | at java.base/java.lang.Thread.run(Unknown Source)
2024/06/07 20:11:31 | stdout | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024/06/07 20:11:31 | stdout | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024/06/07 20:11:31 | stdout | at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2024/06/07 20:11:31 | stdout | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2024/06/07 20:11:31 | stdout | at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
2024/06/07 20:11:31 | stdout | at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
2024/06/07 20:11:31 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
2024/06/07 20:11:31 | stdout | at me.itzg.helpers.curseforge.CurseForgeApiClient.lambda$searchMod$2(CurseForgeApiClient.java:123)
2024/06/07 20:11:31 | stdout | me.itzg.helpers.errors.GenericException: No mods found with slug=mcjw
2024/06/07 20:11:31 | stdout | [mc-image-helper] 15:11:31.145 ERROR : 'install-curseforge' command failed. Version is 1.38.15
2024/06/07 20:11:28 | stdout | [init] Running as uid=1026 gid=100 with /data as 'drwxr-xr-x 4 1026 100 4096 Jun  7 15:11 /data'
2024/06/07 20:03:33 | stdout | [init] ERROR failed to auto-install CurseForge modpack
2024/06/07 20:03:32 | stdout | at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
2024/06/07 20:03:32 | stdout | at picocli.CommandLine.execute(CommandLine.java:2174)
2024/06/07 20:03:32 | stdout | at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
2024/06/07 20:03:32 | stdout | at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
2024/06/07 20:03:32 | stdout | at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
2024/06/07 20:03:32 | stdout | at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
2024/06/07 20:03:32 | stdout | at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
2024/06/07 20:03:32 | stdout | at picocli.CommandLine.access$1500(CommandLine.java:148)
2024/06/07 20:03:32 | stdout | at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
2024/06/07 20:03:32 | stdout | at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:29)
2024/06/07 20:03:32 | stdout | at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:213)
2024/06/07 20:03:32 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:175)
2024/06/07 20:03:32 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:213)
2024/06/07 20:03:32 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.lambda$install$3(CurseForgeInstaller.java:176)
2024/06/07 20:03:32 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.installByRetrievingModpackZip(CurseForgeInstaller.java:255)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.Mono.block(Mono.java:1712)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
2024/06/07 20:03:32 | stdout | Suppressed: java.lang.Exception: #block terminated with an error
2024/06/07 20:03:32 | stdout | at java.base/java.lang.Thread.run(Unknown Source)
2024/06/07 20:03:32 | stdout | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024/06/07 20:03:32 | stdout | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024/06/07 20:03:32 | stdout | at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2024/06/07 20:03:32 | stdout | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2024/06/07 20:03:32 | stdout | at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
2024/06/07 20:03:32 | stdout | at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
2024/06/07 20:03:32 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
2024/06/07 20:03:32 | stdout | at me.itzg.helpers.curseforge.CurseForgeApiClient.lambda$searchMod$2(CurseForgeApiClient.java:123)
2024/06/07 20:03:32 | stdout | me.itzg.helpers.errors.GenericException: No mods found with slug=mcjw
2024/06/07 20:03:32 | stdout | [mc-image-helper] 15:03:32.686 ERROR : 'install-curseforge' command failed. Version is 1.38.15
2024/06/07 20:03:30 | stdout | [init] Running as uid=1026 gid=100 with /data as 'drwxr-xr-x 3 1026 100 4096 Jun  7 14:46 /data'
2024/06/07 20:03:30 | stdout | [init] Changing ownership of /data to 1026 ...
2024/06/07 19:55:36 | stdout | [init] ERROR failed to auto-install CurseForge modpack
2024/06/07 19:55:36 | stdout | at me.itzg.helpers.McImageHelper.main(McImageHelper.java:159)
2024/06/07 19:55:36 | stdout | at picocli.CommandLine.execute(CommandLine.java:2174)
2024/06/07 19:55:36 | stdout | at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
2024/06/07 19:55:36 | stdout | at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
2024/06/07 19:55:36 | stdout | at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
2024/06/07 19:55:36 | stdout | at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
2024/06/07 19:55:36 | stdout | at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
2024/06/07 19:55:36 | stdout | at picocli.CommandLine.access$1500(CommandLine.java:148)
2024/06/07 19:55:36 | stdout | at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
2024/06/07 19:55:36 | stdout | at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:29)
2024/06/07 19:55:36 | stdout | at me.itzg.helpers.curseforge.InstallCurseForgeCommand.call(InstallCurseForgeCommand.java:213)
2024/06/07 19:55:36 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:175)
2024/06/07 19:55:36 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.install(CurseForgeInstaller.java:213)
2024/06/07 19:55:36 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.lambda$install$3(CurseForgeInstaller.java:176)
2024/06/07 19:55:36 | stdout | at me.itzg.helpers.curseforge.CurseForgeInstaller.installByRetrievingModpackZip(CurseForgeInstaller.java:255)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.Mono.block(Mono.java:1712)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
2024/06/07 19:55:36 | stdout | Suppressed: java.lang.Exception: #block terminated with an error
2024/06/07 19:55:36 | stdout | at java.base/java.lang.Thread.run(Unknown Source)
2024/06/07 19:55:36 | stdout | at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024/06/07 19:55:36 | stdout | at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024/06/07 19:55:36 | stdout | at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
2024/06/07 19:55:36 | stdout | at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2024/06/07 19:55:36 | stdout | at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
2024/06/07 19:55:36 | stdout | at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:158)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onNext(FluxDoFinally.java:113)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:305)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:245)
2024/06/07 19:55:36 | stdout | at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:132)
2024/06/07 19:55:36 | stdout | at me.itzg.helpers.curseforge.CurseForgeApiClient.lambda$searchMod$2(CurseForgeApiClient.java:123)
**2024/06/07 19:55:36 | stdout | me.itzg.helpers.errors.GenericException: No mods found with slug=mcjw**
2024/06/07 19:55:36 | stdout | [mc-image-helper] 14:55:36.312 ERROR : 'install-curseforge' command failed. Version is 1.38.15
2024/06/07 19:55:34 | stdout | [init] Running as uid=1026 gid=100 with /data as 'drwxr-xr-x 2 1026 100 4096 Jun  7 14:47 /data'
2024/06/07 19:55:33 | stdout | [init] Changing gid of minecraft to 100
2024/06/07 19:55:33 | stdout | [init] Changing uid of minecraft to 1026

**Comment by itzg** [comment]
Their API is returning an empty list against that modpack. I'm guessing because it's marked experimental:

![image](https://github.com/itzg/docker-minecraft-server/assets/988985/c451c4e2-c6db-4125-b0c3-414ffae31e55)

**Comment by vaitamozhetnet** [comment]
i'll try to change modpack status, ty.
I tried normal forge with mods i installed manually and it all started working
