### ISSUE TITLE
Server crashes after prepping spawn area

### ISSUE THREAD

**Issue by LordoftheRaccoons** [itzg/docker-minecraft-server#288]
Everytime I try to start the server, after the server preps the spawn area the log spits this out.

[05:26:16] [Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)
[05:26:25] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.

Here's the crash report
[crash-2019-02-07_03.04.11-server.txt](https://github.com/itzg/dockerfiles/files/2839505/crash-2019-02-07_03.04.11-server.txt)

**Comment by LordoftheRaccoons** [comment]
I've looked into it some more, and people with similar issues are reccomending I get better hardware. I don't think this is the issue as I never reached 100% CPU or RAM utilization.

**Comment by itzg** [comment]
It could be something other than CPU getting saturated. For example I’m wondering if your system memory usage is going into swap in which case the whole system will dramatically drop as the OS churns memory pages to disk. If you hadn’t already, try disabling swap to see if that helps. You’ll need to Google for your particular system but `sudo swapoff -a` is typically the command.

**Comment by robinbraemer** [comment]
This error may be due to heavy events in the world such as 100000 exploding TNT or some redstone clock making lags.
Think about if there could be something in your world that is issuing this lags.

**Comment by LordoftheRaccoons** [comment]
This is on a brand new vanilla world, survival mode, just walking around.
Maybe world gen has some effect, but even after the chuncks are loaded it
still lags to hell and back. I'm running on a Synology NAS with only 1GB of
ram, but mem swap is off. As for the issue itself, this is really more of a
duct tape solution than a "fix" but switching the server to a spigot server
helped performance enough for it to be playable.

**Comment by itzg** [comment]
@LordoftheRaccoons what model of Synology NAS are you running? I see a lot of the models have processors that simply may not run Minecraft very well, which is totally fair since a NAS is a storage appliance first and foremost.

**Comment by michaelgeisler** [comment]
I'm having the same issue my server has 8 cores and I assigned 10 gb to the docker container and to java but recently the game is getting unplayable. It started to use 80% of the cpu in the docker container (meanwhile the actual usage was around 8%)

**Comment by robinbraemer** [comment]
@michaelgeisler Are you running a vanilla minecraft server?
I recommend you always running [paper](https://github.com/PaperMC/Paper), regardless if you need plugins or not as [paper](https://papermc.io/) gives high performance boosts and major fixes.

@itzg maybe you should consider updating the docker image to at least java 10 as of starting at this version java improved docker container integration and really uses the allocated memory and cpu of the container.

**Comment by itzg** [comment]
@robinbraemer in general, upgrading to Java 10/11 does seem like a good goal eventually; however, the container awareness added in Java 10 won't help much since the starting and max heap sizes are already explicitly passed to the JVM.

Going above Java 8 will be non-trivial since Alpine is not readily supported for newer versions of Java, so I'll have to switch some package installs, etc in the docker build.

**Comment by jwalton** [comment]
I was running into the same problem on my Synology DS1512+.  Maybe the problem has something to so with Atom processors?

**Comment by itzg** [comment]
As a data point, I have been running a vanilla 1.14.1 server for 12 days straight with up to 4 users on an Ubuntu machine with an i5-4250U . FYI, even though I set the heap limit to 1 GB, `top` is showing a "VIRT" memory usage of 2.5 GB and "RES" of 1.2 GB.
