### ISSUE TITLE
Accept yes/no for boolean environment variables

### ISSUE THREAD

**Issue by kdkasad** [itzg/docker-minecraft-server#2892]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

I would like to add "yes" and "no" as equivalents for "true" and "false" respectively when handling boolean environment variables.

Reasons:
1. It feels more natural: Enable autopause? Yes. Execute directly? No.
2. Ansible supports using yes/no variables, so anyone deploying this Docker container using Ansible (e.g. users of [Ansible NAS](https://ansible-nas.io)) might accidentally use yes/no and be confused why it isn't working.

I would be happy to implement this myself and open a PR. It should just require changing 2 lines of code.

**Comment by itzg** [comment]
Great idea and a PR would be good. You mean just adding to the isTrue and isFalse functions, right?

**Comment by kdkasad** [comment]
> Great idea and a PR would be good. You mean just adding to the isTrue and isFalse functions, right?

Yes, exactly. I'll have a PR in a few minutes.
