### ISSUE TITLE
Request for keep the original name of plugin file via SPIGET_RESOURCES

### ISSUE THREAD

**Issue by bestcb2333** [itzg/docker-minecraft-server#2923]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

The plugins automatically downloaded via the SPIGET_RESOURCES environment, are renamed to their number code in the plugins/ folder. Such as "12345.jar", "55555.jar". I think it's a good idea to keep the original name of the plugin, the number code is hard to read and distinguish for me.

**Comment by itzg** [comment]
It's a fair request. Already being tracked in #1686

You could also see if Modrinth provides the plugins you're needing.
