### ISSUE TITLE
Request for Java 18 Image

### ISSUE THREAD

**Issue by FlyHummingbird** [itzg/docker-minecraft-server#2926]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Hi. is it possible to add Java 18?
I need it for the modpack BetterMC 4, it only works with 18, i tried nearly every different TAG and it
always failed when I tried to start the server.
I am a Docker/Container Noob, maybe there is a way to do it manually, but i dont know how, if possible.

**Comment by itzg** [comment]
Java 18 specifically? Not 21 or 17? 18 has been unsupported since 2022 so there must be some pretty badly behaving code in one of those mods to require 18 specifically.

Can you provide the documentation stating that requirement or container config using the java21 image tag and the logs showing the failure?

**Comment by rhullah** [comment]
Agreed.  I was finding that BetterMC 4 is Minecraft version 1.20/1.20.1, which should use Java 17.  Which you can target that with an image tag of: `itzg/minecraft-server:java17`

Speaking around this @itzg, would it be possible in the image's startup process to know the Minecraft version and the Java version (which it should know both) and then log a warning if they don't align to what the recommendation is?

**Comment by itzg** [comment]
> Speaking around this @itzg, would it be possible in the image's startup process to know the Minecraft version and the Java version (which it should know both) and then log a warning if they don't align to what the recommendation is?

That would be annoyingly specific to Forge and possibly varies by mods installed -- I did the same for Java 8 Forge check for a while but gradually removed that code. Pretty much everything works with the newest Java version except for various Forge versions/mods that have improperly used internal APIs.

**Comment by rhullah** [comment]
Yeah, I was worried that was the case but didn't have that history myself.  I thought maybe a baseline Vanilla mapping could be a baseline, but it's why I mentioned the log as a warning, or even an info log, just to say "hey your combo may not be right, but could be based on your Server Type".

**Comment by itzg** [comment]
Ha, I just removed the last of it in #2711

**Comment by FlyHummingbird** [comment]
This is the Official README of BMC4:
YOU NEED JAVA 18 TO PLAY 1.20.1 MODPACKS. THIS CAN BE INSTALLED HERE https://adoptium.net/temurin/releases/?version=18 (install and run the 64bit .msi file)
If your server still doesn't launch with Java 18, uninstall other Java versions! This can be done by going to Programs and Features, then typing the letter "j" to search for versions of Java.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ONLY USE THESE FILES TO RUN THE SERVER:
Windows = start.ps1
Linux = start.sh
(DO NOT USE THE .jar TO RUN THE SERVER!)
Note that the file extensions (the .sh and the .ps1) will not show if you haven't enabled them. Instead, you can look for "Windows Powershell" to the right of the file named "start"

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Below is a list of commonly asked questions. If you have a question not answered in this document, please ask the question in our Discord: https://lunapixel.studio/discord

	Q: How do I start the server?
A: Right click the Start.ps1 file and Open with Powershell. 
	Q: How do I join my server?
A: 1) Install the modpack using a modded launcher (Curseforge, GDLauncher, ATLauncher, etc)	2) go to the Multiplayer tab in the main menu	3) click Direct Connect and type localhost
	Q: How do others join my server?
A: They will connect using your Public IP Address, which can be found by typing "my ip address" into Google. If people are unable to join with this IP, find a portforwarding guide online.
	Q: How do I allocate more RAM?
A: 1) Open the variables.txt text file	2) On line 8, you can add Java arguments inbetween the quotation marks. -Xmx8g will set maximum RAM usage to 8 gigabytes. 
	Q: Should I be worried about errors in the console?
A: Unless there is something that is not working as expected, don't mind any errors. 99% of them mean nothing.
	Q: Why is my server so laggy?
A: There are a few things you can do to for server lag:
 1) Follow this guide for optimal Java args. Please note that these can cause instability or worsened performance for some people: https://github.com/brucethemoose/Minecraft-Performance-Flags-Benchmarks
 2) If lag persists, do the following command ingame:
/spark profiler --interval 100
 3) Check the Spark Profiler website link that shows up in chat/console and check if your server is using all of the memory. You can allocate more memory accordingly.
 4) On the Spark Profiler website, you can also check what processes are using the most resources. Our Discord community can help you further if necessary.
	Q: How do I make my server public?
A: 1) To make your server available to the public, you have to go into the Server's Config folder > Navigate to BHMenu Folder and edit the bhmenu-public_server_list.properties file
2) Set it to True to enable your server to be viewed publicly on the Server Browser
3) To get your server registered on the Server Browser you need to post your server on https://minecraft.multiplayerservers.net/ or click the "Add Server" button on the Server Browser tab in the Multiplayer Menu.
Servers hosted using Bisect get placed higher on the server list. Make sure it's posted under the correct modpack or it will not show up in the ingame server browser. 
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IMPORTANT FOR WINDOWS 11 22H2 USERS!:
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	Q: When I open Powershell, it closes immediately! (This can also solve other issues!)
A: This is likely an issue with Powershell itself. Here is an alternative method of opening the start.ps1:
1) Press the Windows key, type Powershell and run as Administrator
2) Run the following: set-executionpolicy remotesigned
3) Agree by typing A
4) Run the start.ps1 again by Right click the Start.ps1 file and Open with Powershell.
5) Now it should work (If it does not work, restart your PC and try running again)

Windows 11 users can also try doing Step 1-5 of the alternative method of opening the start.ps1 (which can be found above) and then running the following command: Unblock-file -Path InsertFilePathHere

After running this command, the start script should work again. If not, use the guides below.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

IF YOU DO NOT WANT TO FOLLOW THE ABOVE FIX THEN YOUR ONLY OPTION IS MANUAL INSTALLATION:

New Windows 11 22H2 Update causes the PowerShell not to work. I suggest these Videos for Manual Installation:
FORGE 1.19.2: https://www.youtube.com/watch?v=3HD0ibIpO-A
FABRIC: https://www.youtube.com/watch?v=b2W1Xb7nLKo
Make sure to Install the Server in our ServerPacks so it can use the correct files.
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

LASTLY, IF YOU DO NOT WANT TO FACE THESE ISSUES WE RECOMMENED BISECT HOSTING:
Approx. $10 - $25 a month depending on what plan you choose. You can also get 25% off with Code LunaPixel.

Go to https://www.bisecthosting.com/LunaPixel and order a plan which fits you. We suggest 1GB per player but nothing lower than 4GB as the server needs at least 3GB to run.



And these are my Logs:

[bmc4.log](https://github.com/user-attachments/files/15977619/bmc4.log)

**Comment by itzg** [comment]
Wow, I was hoping for just a link and not the whole README 😄 .

Apparently I forgot there was an example and you hadn't looked there yet, but this BMC4 example worked fine with java17 image tag:

https://github.com/itzg/docker-minecraft-server/blob/master/examples/bmc4/docker-compose.yml

**Comment by itzg** [comment]
From your logs I'm not sure why you thought it was a Java version issue. The failure is

```
2024-06-25 21:41:51 Mod File: /data/mods/YungsMenuTweaks-1.20.1-Forge-1.0.2.jar
2024-06-25 21:41:51 Failure message: YUNG's Menu Tweaks (yungsmenutweaks) has failed to load correctly
2024-06-25 21:41:51 java.util.ServiceConfigurationError: com.yungnickyoung.minecraft.yungsmenutweaks.services.IPlatformHelper: com.yungnickyoung.minecraft.yungsmenutweaks.services.ForgePlatformHelper Unable to get public no-arg constructor
2024-06-25 21:41:51 Mod Version: 1.20.1-Forge-1.0.2
2024-06-25 21:41:51 Mod Issue URL: https://github.com/yungnickyoung/YUNGs-Menu-Tweaks/issues
2024-06-25 21:41:51 Exception message: java.lang.RuntimeException: Attempted to load class net/minecraftforge/client/event/ScreenEvent for invalid dist DEDICATED_SERVER
```

which you'll see if a client mod excluded in the example.

**Comment by FlyHummingbird** [comment]
Yeah i thought thats the java Version, because i have a running bmc4 Server in a VM, Updated the modpack to v28, nothing worked after Update, read the readme and updated to that Version, after that it worked fine. Now i tried to make a Container, because i dont want a VM running, running on my Homeserver, for Just a MC server. After Testing every different Versions of ur Server Tags i figured IT would BE the Same Problem. i am gonna try IT Out with the exlcuding File when i am done with my Work tonight. I will Update later If that fixed the Problem. Thank you. P.s.: Sorry for typos, different language :)

**Comment by FlyHummingbird** [comment]
Excluding the file fixed it, than you very much for the help.

**Comment by txj-xyz** [comment]
Where do you fix it at?

**Comment by itzg** [comment]
@txj-xyz ,  https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#exclude-client-mods
