### ISSUE TITLE
Automatic Update of Server-Icon on Container Restart

### ISSUE THREAD

**Issue by Akorian** [itzg/docker-minecraft-server#2942]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

After setting the server-icon via a Docker (Compose) argument, the icon remains persistent. Even if a new server-icon is provided, the existing icon will not be replaced until the current one is manually removed and the server is restarted. This behavior is not intuitive and can lead to confusion.

New Behavior:
When the server-icon is updated through Docker, the old icon should be automatically replaced with the new one upon the container's restart.

**Comment by Akorian** [comment]
Sounds about right for me. 
You could go more complicated but I don't see the need for that.
Also the file is expected to be small.

**Comment by itzg** [comment]
@Akorian I just re-read the line that I linked and the docs

https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#server-icon

Set `OVERRIDE_ICON` to "true" and it will do what you were wanting.
