### ISSUE TITLE
ERROR failed to auto-install CurseForge modpack

### ISSUE THREAD

**Issue by quasarea** [itzg/docker-minecraft-server#2947]
### Describe the problem

Using latest image sha256:065a277923c5a1ad29eef530100841f1d612a74be0dad3f2da6c26daaaeff176 2024-07-01 20:19:35

Using example config for ATM9 from https://github.com/itzg/docker-minecraft-server/blob/master/examples/atm9/docker-compose.yml

Using .env file next to docker-compose.yml where I have
```
CF_API_KEY=34dc2616-...
```
and calling ` docker compose up -d`

Generates new container and in its logs:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-x--- 2 1000 1000 4096 Jul  4 14:56 /data'
[mc-image-helper] 15:27:46.706 ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com is forbidden or rate-limit has been exceeded. Ensure CF_API_KEY is set to a valid API key from https://console.curseforge.com/ or allow rate-limit to reset.
[init] ERROR failed to auto-install CurseForge modpack
```
In container env:
![NVIDIA_Overlay_uklcW7R4KL](https://github.com/itzg/docker-minecraft-server/assets/10334982/f1434285-3b24-466a-ba17-38c8c2775c69)

Not sure what is wrong

**Comment by quasarea** [comment]
Same result with:
```
docker run --name mc-e9e -e EULA=TRUE --env-file=.env -e TYPE=AUTO_CURSEFORGE -e CF_SLUG=enigmatica9expert -e CF_FILE_ID=5356768 -e CF_API_KEY=34dc2616-*** -p 25565:25565 itzg/minecraft-server:java17
```
output:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Jun 27 18:47 /data'
[mc-image-helper] 16:01:33.374 ERROR : Invalid parameter provided for 'install-curseforge' command: Access to https://api.curseforge.com is forbidden or rate-limit has been exceeded. Ensure CF_API_KEY is set to a valid API key from https://console.curseforge.com/ or allow rate-limit to reset.
[init] ERROR failed to auto-install CurseForge modpack 
```

**Comment by itzg** [comment]
If your CF API key actually starts with "34dc2616" then that's not correct. There's usually a few dollar signs since they always need to be escaped.
