### ISSUE TITLE
Forge crash on launch

### ISSUE THREAD

**Issue by MegaZur** [itzg/docker-minecraft-server#2981]
### Describe the problem

I have a Synology DS720+ with DSM version 7.2.1-69057 Update 5.

I want to create my container with forge version 1.16.5. When I launch the container it crashes after a while. I haven't put any mods in the folder.

I've tried launching the container automatically without specifying a version, which works very well, and I can even add mods without worry.

I have the impression that it's the VERSION tag that's causing the problem, but I don't know how.

Translated with DeepL.com (free version)

### Container definition

services:
  mc:
    image: itzg/minecraft-server
    ports:
    # expose the Minecraft server port outside of container
    - "25565:25565"
    environment:
      # REQUIRED for all types
      EULA: "TRUE"
      # Set server type (vs the default of vanilla)
      TYPE: FORGE
      VERSION: 1.16.5
      FORGE_VERSION: 36.2.34
      DEBUG: "true"
    volumes:
    # use a named, managed volume for data volume
    - /volume1/docker/mc_forge/data:/data
    # attach local host directory "mods" in same directory as this compose file
    # all mods in this directory get copied into /data/mods at startup
    - /volume1/docker/mc_forge/mods:/mods:ro

volumes:
  # declared the named volume, but use default/local storage engine
  mc_forge: {}

### Container logs

<html><body>

<h2>forge-mc-1</h2>

date | stream | content
-- | -- | --
2024/07/11 12:50:55 | stdout | 2024-07-11T10:50:55.516Z	INFO	mc-server-runner	Done
2024/07/11 12:50:55 | stdout | 2024-07-11T10:50:55.516Z 	WARN	mc-server-runner	 Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error. 	{"exitCode": 1}
2024/07/11 12:50:55 | stderr | at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
2024/07/11 12:50:55 | stderr | at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
2024/07/11 12:50:55 | stderr | at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.Launcher.<init>(Launcher.java:55)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.Environment.computePropertyIfAbsent(Environment.java:62)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:47)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.api.TypesafeMap.computeIfAbsent(TypesafeMap.java:52)
2024/07/11 12:50:55 | stderr | at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.Launcher.lambda$new$6(Launcher.java:55)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.SecureJarHandler.<clinit>(SecureJarHandler.java:45)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.api.LamdbaExceptionUtils.uncheck(LamdbaExceptionUtils.java:95)
2024/07/11 12:50:55 | stderr | at cpw.mods.modlauncher.SecureJarHandler.lambda$static$1(SecureJarHandler.java:45)
2024/07/11 12:50:55 | stderr | Exception in thread "main" java.lang.IllegalAccessError: class cpw.mods.modlauncher.SecureJarHandler (in unnamed module @0x58372a00) cannot access class sun.security.util.ManifestEntryVerifier (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x58372a00
2024/07/11 12:50:55 | stdout | [10:50:55] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 21.0.3 by Eclipse Adoptium
2024/07/11 12:50:55 | stdout | [10:50:55] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.34, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
2024/07/11 12:50:55 | stdout | 2024-07-11 10:50:55,091 main WARN Advanced terminal features are not available in this environment
2024/07/11 12:50:54 | stdout | [Log4jPatcher] [WARN]  Unable to find noLookups:Z field in org/apache/logging/log4j/core/pattern/MessagePatternConverter
2024/07/11 12:50:54 | stdout | [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/pattern/MessagePatternConverter
2024/07/11 12:50:53 | stdout | [Log4jPatcher] [INFO] Transforming org/apache/logging/log4j/core/lookup/JndiLookup
2024/07/11 12:50:53 | stderr | + exec mc-server-runner --stop-duration 60s java -Xmx1G -Xms1G -javaagent:/image/Log4jPatcher.jar -Dlog4j2.formatMsgNoLookups=true -jar forge-1.16.5-36.2.34.jar
2024/07/11 12:50:53 | stderr | + return 1
2024/07/11 12:50:53 | stderr | + case "${1,,}" in
2024/07/11 12:50:53 | stderr | + isTrue false
2024/07/11 12:50:53 | stderr | + return 1
2024/07/11 12:50:53 | stderr | + case "${1,,}" in
2024/07/11 12:50:53 | stderr | + isTrue false
2024/07/11 12:50:53 | stderr | + return 1
2024/07/11 12:50:53 | stderr | + case "${1,,}" in
2024/07/11 12:50:53 | stderr | + isTrue false
2024/07/11 12:50:53 | stderr | + finalArgs+=("$@" $EXTRA_ARGS)
2024/07/11 12:50:53 | stderr | + finalArgs+=(-jar "$SERVER")
2024/07/11 12:50:53 | stderr | + [[ -n '' ]]
2024/07/11 12:50:53 | stderr | + finalArgs=($JVM_XX_OPTS $JVM_OPTS $expandedDOpts)
2024/07/11 12:50:53 | stdout | [init] 2024-07-11 10:50:53+00:00 Starting the Minecraft server...
2024/07/11 12:50:53 | stderr | + shopt -u -o xtrace
2024/07/11 12:50:53 | stderr | + oldState='set -o xtrace'
2024/07/11 12:50:53 | stderr | ++ shopt -po xtrace
2024/07/11 12:50:53 | stderr | + local oldState
2024/07/11 12:50:53 | stderr | + log 'Starting the Minecraft server...'
2024/07/11 12:50:53 | stderr | + '[' -f /data/bootstrap.txt ']'
2024/07/11 12:50:53 | stderr | + [[ forge-1.16.5-36.2.34.jar =~ run.sh ]]
2024/07/11 12:50:53 | stderr | + [[ FORGE == \C\U\R\S\E\F\O\R\G\E ]]
2024/07/11 12:50:53 | stderr | + [[ FORGE == \C\U\R\S\E\F\O\R\G\E ]]
2024/07/11 12:50:53 | stderr | + return 1
2024/07/11 12:50:53 | stderr | + case "${1,,}" in
2024/07/11 12:50:53 | stderr | + isTrue ''
2024/07/11 12:50:53 | stderr | + [[ -n '' ]]
2024/07/11 12:50:53 | stderr | + return 1
2024/07/11 12:50:53 | stderr | + case "${1,,}" in
2024/07/11 12:50:53 | stderr | + isTrue false
2024/07/11 12:50:53 | stderr | + mcServerRunnerArgs=(--stop-duration "${STOP_DURATION:-60}s")
2024/07/11 12:50:53 | stderr | + rm -f /data/.mc-health.env
2024/07/11 12:50:53 | stderr | + return 1
2024/07/11 12:50:52 | stderr | + mc-image-helper compare-versions 1.16.5 lt 1.7
2024/07/11 12:50:52 | stderr | + versionLessThan 1.7
2024/07/11 12:50:52 | stderr | + return 1
2024/07/11 12:50:51 | stderr | + mc-image-helper compare-versions 1.16.5 lt b1.8
2024/07/11 12:50:51 | stderr | + versionLessThan b1.8
2024/07/11 12:50:51 | stderr | + JVM_OPTS='-Xmx1G -Xms1G -javaagent:/image/Log4jPatcher.jar -Dlog4j2.formatMsgNoLookups=true '
2024/07/11 12:50:51 | stderr | + [[ -n 1G ]]
2024/07/11 12:50:51 | stderr | + JVM_OPTS='-Xms1G -javaagent:/image/Log4jPatcher.jar -Dlog4j2.formatMsgNoLookups=true '
2024/07/11 12:50:51 | stderr | + [[ -n 1G ]]
2024/07/11 12:50:51 | stderr | + shopt -u -o xtrace
2024/07/11 12:50:51 | stderr | + oldState='set -o xtrace'
2024/07/11 12:50:51 | stderr | ++ shopt -po xtrace
2024/07/11 12:50:51 | stderr | + local oldState
2024/07/11 12:50:51 | stderr | + log 'Setting initial memory to 1G and max to 1G'
2024/07/11 12:50:51 | stderr | + [[ -n 1G ]]
2024/07/11 12:50:51 | stderr | + return 1
2024/07/11 12:50:51 | stderr | + case "${1,,}" in
2024/07/11 12:50:51 | stderr | + isTrue ''
2024/07/11 12:50:51 | stderr | + return 1
2024/07/11 12:50:51 | stderr | + case "${1,,}" in
2024/07/11 12:50:51 | stderr | + isTrue ''
2024/07/11 12:50:51 | stderr | + return 1
2024/07/11 12:50:51 | stderr | + case "${1,,}" in
2024/07/11 12:50:51 | stderr | + isTrue ''
2024/07/11 12:50:51 | stderr | + return 1
2024/07/11 12:50:51 | stderr | + case "${1,,}" in
2024/07/11 12:50:51 | stderr | + isTrue ''
2024/07/11 12:50:51 | stderr | + '[' -n '' ']'
2024/07/11 12:50:51 | stderr | + expandedDOpts=
2024/07/11 12:50:51 | stdout | [init] 2024-07-11 10:50:51+00:00 Setting initial memory to 1G and max to 1G
2024/07/11 12:50:51 | stderr | + [[ '' = false ]]
2024/07/11 12:50:51 | stderr | + return 1
2024/07/11 12:50:49 | stderr | + mc-image-helper compare-versions 1.16.5 lt 1.14
2024/07/11 12:50:49 | stderr | + versionLessThan 1.14
2024/07/11 12:50:49 | stderr | + return 1
2024/07/11 12:50:49 | stderr | + case "${1,,}" in
2024/07/11 12:50:49 | stderr | + isTrue false
2024/07/11 12:50:49 | stderr | + JVM_OPTS='-javaagent:/image/Log4jPatcher.jar -Dlog4j2.formatMsgNoLookups=true '
2024/07/11 12:50:49 | stderr | + return 1
2024/07/11 12:50:49 | stderr | + case "${1,,}" in
2024/07/11 12:50:49 | stderr | + isTrue false
2024/07/11 12:50:49 | stderr | + return 0
2024/07/11 12:50:48 | stderr | + mc-image-helper compare-versions 1.16.5 lt 1.18.1
2024/07/11 12:50:48 | stderr | + versionLessThan 1.18.1
2024/07/11 12:50:48 | stderr | + return 1
2024/07/11 12:50:47 | stderr | + mc-image-helper compare-versions 1.16.5 lt 1.7
2024/07/11 12:50:47 | stderr | + versionLessThan 1.7
2024/07/11 12:50:47 | stderr | + JVM_OPTS='-Dlog4j2.formatMsgNoLookups=true '
2024/07/11 12:50:47 | stderr | + true
2024/07/11 12:50:47 | stderr | + useFallbackJvmFlag=true
2024/07/11 12:50:47 | stderr | + return 0
2024/07/11 12:50:46 | stderr | + mc-image-helper compare-versions 1.16.5 lt 1.18.1
2024/07/11 12:50:46 | stderr | + versionLessThan 1.18.1
2024/07/11 12:50:46 | stderr | + return 1
2024/07/11 12:50:46 | stderr | + [[ FORGE == \P\U\R\P\U\R ]]
2024/07/11 12:50:46 | stderr | + for t in "${@}"
2024/07/11 12:50:46 | stderr | + isType PURPUR
2024/07/11 12:50:46 | stderr | + return 1
2024/07/11 12:50:46 | stderr | + [[ FORGE == \P\U\R\P\U\R ]]
2024/07/11 12:50:46 | stderr | + for t in "${@}"
2024/07/11 12:50:46 | stderr | + isType PURPUR
2024/07/11 12:50:46 | stderr | + return 1
2024/07/11 12:50:46 | stderr | + [[ FORGE == \V\A\N\I\L\L\A ]]
2024/07/11 12:50:46 | stderr | + for f in "${@}"
2024/07/11 12:50:46 | stderr | + isFamily VANILLA
2024/07/11 12:50:46 | stderr | + return 1
2024/07/11 12:50:46 | stderr | + [[ FORGE == \V\A\N\I\L\L\A ]]
2024/07/11 12:50:46 | stderr | + for f in "${@}"
2024/07/11 12:50:46 | stderr | + isFamily VANILLA
2024/07/11 12:50:46 | stderr | + return 1
2024/07/11 12:50:45 | stderr | + mc-image-helper compare-versions 1.16.5 lt 1.7
2024/07/11 12:50:45 | stderr | + versionLessThan 1.7
2024/07/11 12:50:45 | stderr | + SERVER_DIR=/data
2024/07/11 12:50:45 | stderr | + [[ -n '' ]]
2024/07/11 12:50:45 | stderr | + useFallbackJvmFlag=false
2024/07/11 12:50:45 | stderr | + canUseRollingLogs=true
2024/07/11 12:50:45 | stderr | + '[' -n '' ']'
2024/07/11 12:50:45 | stderr | + exec /start-finalExec
2024/07/11 12:50:45 | stderr | + [[ -v WHITELIST ]]
2024/07/11 12:50:45 | stderr | + [[ -v WHITELIST_FILE ]]
2024/07/11 12:50:45 | stderr | + [[ -v OPS ]]
2024/07/11 12:50:45 | stderr | + [[ -v OPS_FILE ]]
2024/07/11 12:50:45 | stderr | + sharedArgs+=(--output-directory=/data)
2024/07/11 12:50:45 | stderr | + [[ -n '' ]]
2024/07/11 12:50:45 | stderr | + sharedArgs=(--version="$VERSION")
2024/07/11 12:50:45 | stderr | + [[ -v OVERRIDE_WHITELIST ]]
2024/07/11 12:50:45 | stderr | + [[ -v APPEND_WHITELIST ]]
2024/07/11 12:50:45 | stderr | + [[ -v OVERRIDE_OPS ]]
2024/07/11 12:50:45 | stderr | + [[ -v APPEND_OPS ]]
2024/07/11 12:50:45 | stderr | + exec /start-setupEnvVariables
2024/07/11 12:50:45 | stderr | + return 1
2024/07/11 12:50:45 | stderr | + case "${1,,}" in
2024/07/11 12:50:45 | stderr | + isTrue false
2024/07/11 12:50:45 | stderr | + return 1
2024/07/11 12:50:45 | stderr | + case "${1,,}" in
2024/07/11 12:50:45 | stderr | + isTrue ''
2024/07/11 12:50:45 | stdout | [mc-image-helper] 10:50:45.172 INFO  : Created/updated 4 properties in /data/server.properties
2024/07/11 12:50:45 | stderr | [mc-image-helper] 10:50:45.172 DEBUG : Setting property rcon.port to new value '25575'
2024/07/11 12:50:45 | stderr | [mc-image-helper] 10:50:45.171 DEBUG : Setting property rcon.password to new value '***'
2024/07/11 12:50:45 | stderr | [mc-image-helper] 10:50:45.171 DEBUG : Setting property enable-rcon to new value 'true'
2024/07/11 12:50:45 | stderr | [mc-image-helper] 10:50:45.169 DEBUG : Setting property white-list to new value 'false'
2024/07/11 12:50:43 | stderr | + mc-image-helper set-properties --definitions /image/property-definitions.json --escape-unicode /data/server.properties
2024/07/11 12:50:42 | stderr | + exec /start-setupServerProperties
2024/07/11 12:50:42 | stdout | [init] 2024-07-11 10:50:42+00:00 Disabling whitelist functionality
2024/07/11 12:50:42 | stdout | [init] 2024-07-11 10:50:42+00:00 Creating server properties in /data/server.properties
2024/07/11 12:50:42 | stderr | + '[' -d /config ']'
2024/07/11 12:50:42 | stderr | + : /data/config
2024/07/11 12:50:42 | stderr | + : /config
2024/07/11 12:50:42 | stderr | [mc-image-helper] 10:50:42.302 DEBUG : ensuring destinationDirectory=/data/mods
2024/07/11 12:50:42 | stderr | [mc-image-helper] 10:50:42.293 DEBUG : Configured with SyncAndInterpolate(skipNewerInDestination=true, replaceEnv=ReplaceEnvOptions(prefix=CFG_, excludes=[], excludePaths=[], suffixes=[yml, yaml, txt, cfg, conf, properties, hjson, json, tml, toml]), src=/mods, dest=/data/mods)
2024/07/11 12:50:41 | stderr | + mc-image-helper sync-and-interpolate --skip-newer-in-destination --replace-env-file-suffixes=yml,yaml,txt,cfg,conf,properties,hjson,json,tml,toml --replace-env-excludes= --replace-env-exclude-paths= --replace-env-prefix=CFG_ /mods /data/mods
2024/07/11 12:50:41 | stdout | [init] 2024-07-11 10:50:41+00:00 Copying any mods from /mods to /data/mods
2024/07/11 12:50:41 | stderr | + shopt -u -o xtrace
2024/07/11 12:50:41 | stderr | + oldState='set -o xtrace'
2024/07/11 12:50:41 | stderr | ++ shopt -po xtrace
2024/07/11 12:50:41 | stderr | + local oldState
2024/07/11 12:50:41 | stderr | + log 'Copying any mods from /mods to /data/mods'
2024/07/11 12:50:41 | stderr | + '[' -d /mods ']'
2024/07/11 12:50:41 | stderr | + return 0
2024/07/11 12:50:41 | stderr | + case "$FAMILY" in
2024/07/11 12:50:41 | stderr | + usesMods
2024/07/11 12:50:41 | stderr | + : /data/mods
2024/07/11 12:50:41 | stderr | + : /mods
2024/07/11 12:50:41 | stderr | + return 1
2024/07/11 12:50:41 | stderr | + case "$FAMILY" in
2024/07/11 12:50:41 | stderr | + usesPlugins
2024/07/11 12:50:41 | stderr | + : /data/plugins
2024/07/11 12:50:41 | stderr | + : /plugins
2024/07/11 12:50:41 | stderr | + subcommand=sync-and-interpolate
2024/07/11 12:50:41 | stderr | + return 0
2024/07/11 12:50:41 | stderr | + case "${1,,}" in
2024/07/11 12:50:41 | stderr | + isTrue true
2024/07/11 12:50:41 | stderr | + updateArg=--skip-newer-in-destination
2024/07/11 12:50:41 | stderr | + return 0
2024/07/11 12:50:41 | stderr | + case "${1,,}" in
2024/07/11 12:50:41 | stderr | + isTrue true
2024/07/11 12:50:41 | stderr | + exec /start-setupMounts
2024/07/11 12:50:41 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + mc-image-helper curseforge-files --default-category mc-mods --mod-loader FORGE
2024/07/11 12:50:39 | stderr | + args+=(--mod-loader "$TYPE")
2024/07/11 12:50:39 | stderr | + case "${TYPE,,}" in
2024/07/11 12:50:39 | stderr | + args+=(--default-category mc-mods)
2024/07/11 12:50:39 | stderr | + return 1
2024/07/11 12:50:39 | stderr | + case "$FAMILY" in
2024/07/11 12:50:39 | stderr | + usesPlugins
2024/07/11 12:50:39 | stderr | + return 0
2024/07/11 12:50:39 | stderr | + case "$FAMILY" in
2024/07/11 12:50:39 | stderr | + usesMods
2024/07/11 12:50:39 | stderr | + args=()
2024/07/11 12:50:39 | stderr | + handleCurseForgeFiles
2024/07/11 12:50:39 | stderr | + return 0
2024/07/11 12:50:39 | stderr | + case "$FAMILY" in
2024/07/11 12:50:39 | stderr | + usesMods
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -v MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES ]]
2024/07/11 12:50:39 | stderr | + : none
2024/07/11 12:50:39 | stderr | + : release
2024/07/11 12:50:39 | stderr | + : ''
2024/07/11 12:50:39 | stderr | + handleModrinthProjects
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + : ''
2024/07/11 12:50:39 | stderr | + : ''
2024/07/11 12:50:39 | stderr | + : ''
2024/07/11 12:50:39 | stderr | + handleGenericPacks
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + return 1
2024/07/11 12:50:39 | stderr | + case "$FAMILY" in
2024/07/11 12:50:39 | stderr | + usesPlugins
2024/07/11 12:50:39 | stderr | + outDir=/data/mods
2024/07/11 12:50:39 | stderr | + return 0
2024/07/11 12:50:39 | stderr | + case "$FAMILY" in
2024/07/11 12:50:39 | stderr | + usesMods
2024/07/11 12:50:39 | stderr | + return 1
2024/07/11 12:50:39 | stderr | + case "$FAMILY" in
2024/07/11 12:50:39 | stderr | + usesPlugins
2024/07/11 12:50:39 | stderr | + return 1
2024/07/11 12:50:39 | stderr | + case "$FAMILY" in
2024/07/11 12:50:39 | stderr | + usesPlugins
2024/07/11 12:50:39 | stderr | + return 0
2024/07/11 12:50:39 | stderr | + case "$FAMILY" in
2024/07/11 12:50:39 | stderr | + usesMods
2024/07/11 12:50:39 | stderr | + handleListings
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + handleModpackZip
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + handlePackwiz
2024/07/11 12:50:39 | stderr | + return 1
2024/07/11 12:50:39 | stderr | + case "${1,,}" in
2024/07/11 12:50:39 | stderr | + isTrue false
2024/07/11 12:50:39 | stderr | + CURSE_URL_BASE=https://minecraft.curseforge.com/projects
2024/07/11 12:50:39 | stderr | + exec /start-setupModpack
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + return 1
2024/07/11 12:50:39 | stderr | + case "${1,,}" in
2024/07/11 12:50:39 | stderr | + isTrue false
2024/07/11 12:50:39 | stderr | + out_dir=/data/world/datapacks
2024/07/11 12:50:39 | stderr | + exec /start-setupDatapack
2024/07/11 12:50:39 | stderr | + [[ -n '' ]]
2024/07/11 12:50:39 | stderr | + worldDest=/data/world
2024/07/11 12:50:39 | stderr | + '[' FORGE = CURSEFORGE ']'
2024/07/11 12:50:39 | stderr | + [[ world =~ ^/.*$ ]]
2024/07/11 12:50:39 | stderr | + exec /start-setupWorld
2024/07/11 12:50:39 | stderr | + FAMILY=FORGE
2024/07/11 12:50:39 | stderr | + export FAMILY=FORGE
2024/07/11 12:50:39 | stderr | + set +a
2024/07/11 12:50:39 | stderr | ++ TYPE=FORGE
2024/07/11 12:50:39 | stderr | ++ VERSION=1.16.5
2024/07/11 12:50:39 | stderr | ++ FAMILY=FORGE
2024/07/11 12:50:39 | stderr | ++ SERVER=forge-1.16.5-36.2.34.jar
2024/07/11 12:50:39 | stderr | + source /data/.run-forge.env
2024/07/11 12:50:39 | stderr | + set -a
2024/07/11 12:50:39 | stderr | [mc-image-helper] 10:50:39.570 DEBUG : Writing TYPE="FORGE" to results file
2024/07/11 12:50:39 | stderr | [mc-image-helper] 10:50:39.570 DEBUG : Writing VERSION="1.16.5" to results file
2024/07/11 12:50:39 | stderr | [mc-image-helper] 10:50:39.570 DEBUG : Writing FAMILY="FORGE" to results file
2024/07/11 12:50:39 | stderr | [mc-image-helper] 10:50:39.569 DEBUG : Writing SERVER="forge-1.16.5-36.2.34.jar" to results file
2024/07/11 12:50:39 | stderr | [mc-image-helper] 10:50:39.568 DEBUG : Populating results file /data/.run-forge.env
2024/07/11 12:50:39 | stderr | [mc-image-helper] 10:50:39.517 DEBUG : Deleting Forge installer log at /data/forge-installer-1.16.5-36.2.34.jar.log
2024/07/11 12:50:39 | stderr | [mc-image-helper] 10:50:39.517 DEBUG : Discovered entry file: /data/forge-1.16.5-36.2.34.jar
2024/07/11 12:49:57 | stdout | [mc-image-helper] 10:49:57.134 INFO  : Running Forge 36.2.34 installer for Minecraft 1.16.5. This might take a while...
2024/07/11 12:49:57 | stderr | [mc-image-helper] 10:49:57.132 DEBUG : Download of https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.34/forge-1.16.5-36.2.34-installer.jar took 808ms at 9939 KB/s
2024/07/11 12:49:56 | stdout | [mc-image-helper] 10:49:56.315 INFO  : Downloading Forge installer 36.2.34 for Minecraft 1.16.5
2024/07/11 12:49:56 | stderr | [mc-image-helper] 10:49:56.376 DEBUG : FILE FETCH: uri=https://maven.minecraftforge.net/net/minecraftforge/forge/1.16.5-36.2.34/forge-1.16.5-36.2.34-installer.jar headers=[user-agent: itzg/mc-image-helper/1.39.3 (cmd=install-forge), x-fetch-session: bd02024d-3cda-4891-8b22-28a568eb8437, accept: application/java-archive, host: maven.minecraftforge.net]
2024/07/11 12:49:56 | stderr | [mc-image-helper] 10:49:56.315 DEBUG : Resolved installer version=VersionPair(minecraft=1.16.5, forge=36.2.34)
2024/07/11 12:49:55 | stderr | [mc-image-helper] 10:49:55.964 DEBUG : JSON FETCH: uri=https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json headers=[user-agent: itzg/mc-image-helper/1.39.3 (cmd=install-forge), x-fetch-session: bd02024d-3cda-4891-8b22-28a568eb8437, accept: application/json, host: files.minecraftforge.net]
2024/07/11 12:49:55 | stderr | [mc-image-helper] 10:49:55.788 DEBUG : JSON FETCH: uri=https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json headers=[user-agent: itzg/mc-image-helper/1.39.3 (cmd=install-forge), x-fetch-session: bd02024d-3cda-4891-8b22-28a568eb8437, accept: application/json, host: files.minecraftforge.net]
2024/07/11 12:49:50 | stderr | + mc-image-helper install-forge --output-directory=/data --results-file=/data/.run-forge.env --minecraft-version=1.16.5 --forge-version=36.2.34 --force-reinstall=false
2024/07/11 12:49:50 | stderr | + [[ -n '' ]]
2024/07/11 12:49:50 | stderr | + exec /start-deployForge
2024/07/11 12:49:50 | stderr | + case "${TYPE^^}" in
2024/07/11 12:49:50 | stdout | [init] 2024-07-11 10:49:50+00:00 Resolving type given FORGE
2024/07/11 12:49:50 | stderr | + shopt -u -o xtrace
2024/07/11 12:49:50 | stderr | + oldState='set -o xtrace'
2024/07/11 12:49:50 | stderr | ++ shopt -po xtrace
2024/07/11 12:49:50 | stderr | + local oldState
2024/07/11 12:49:50 | stderr | + log 'Resolving type given FORGE'
2024/07/11 12:49:50 | stderr | + [[ -n '' ]]
2024/07/11 12:49:50 | stderr | + case "${TYPE^^}" in
2024/07/11 12:49:50 | stderr | + : ''
2024/07/11 12:49:50 | stderr | + [[ -n '' ]]
2024/07/11 12:49:50 | stderr | + [[ -n '' ]]
2024/07/11 12:49:50 | stderr | + [[ -n '' ]]
2024/07/11 12:49:50 | stderr | + [[ -n '' ]]
2024/07/11 12:49:50 | stderr | + [[ -n '' ]]
2024/07/11 12:49:50 | stderr | + return 1
2024/07/11 12:49:50 | stderr | + case "${1,,}" in
2024/07/11 12:49:50 | stderr | + isTrue false
2024/07/11 12:49:50 | stderr | + return 1
2024/07/11 12:49:50 | stderr | + case "${1,,}" in
2024/07/11 12:49:50 | stderr | + isTrue false
2024/07/11 12:49:50 | stderr | + DECLARED_VERSION=1.16.5
2024/07/11 12:49:50 | stderr | + export DECLARED_VERSION=1.16.5
2024/07/11 12:49:50 | stderr | + DECLARED_TYPE=FORGE
2024/07/11 12:49:50 | stderr | + export DECLARED_TYPE=FORGE
2024/07/11 12:49:50 | stderr | + cd /data
2024/07/11 12:49:50 | stderr | + which java
2024/07/11 12:49:50 | stderr | + fixJavaPath
2024/07/11 12:49:50 | stderr | + [[ -n '' ]]
2024/07/11 12:49:50 | stderr | + return 1
2024/07/11 12:49:50 | stderr | + case "${1,,}" in
2024/07/11 12:49:50 | stderr | + isTrue false
2024/07/11 12:49:50 | stderr | + return 1
2024/07/11 12:49:50 | stderr | + case "${1,,}" in
2024/07/11 12:49:50 | stderr | + isTrue false
2024/07/11 12:49:50 | stderr | + set +x
2024/07/11 12:49:50 | stderr | + return 0
2024/07/11 12:49:50 | stderr | + case "${1,,}" in
2024/07/11 12:49:50 | stderr | + isTrue true
2024/07/11 12:49:50 | stderr | + return 1
2024/07/11 12:49:50 | stderr | + case "${1,,}" in
2024/07/11 12:49:50 | stderr | + isTrue false
2024/07/11 12:49:50 | stderr | + '[' '!' -e /data/eula.txt ']'
2024/07/11 12:49:50 | stdout | [init] 2024-07-11 10:49:50+00:00 Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 1 1000 1000 358 Jul 11 10:49 /data'
2024/07/11 12:49:50 | stderr | + shopt -u -o xtrace
2024/07/11 12:49:50 | stderr | + oldState='set -o xtrace'
2024/07/11 12:49:50 | stderr | ++ shopt -po xtrace
2024/07/11 12:49:50 | stderr | + local oldState
2024/07/11 12:49:50 | stderr | + log 'Running as uid=1000 gid=1000 with /data as '\''drwxr-xr-x 1 1000 1000 358 Jul 11 10:49 /data'\'''
2024/07/11 12:49:50 | stderr | ++ ls -lnd /data
2024/07/11 12:49:50 | stderr | ++ id -g
2024/07/11 12:49:50 | stderr | ++ id -u
2024/07/11 12:49:50 | stderr | + HOME=/data
2024/07/11 12:49:50 | stderr | + export HOME=/data

</body>
</html>

**Comment by itzg** [comment]
From that error message it seems like an incompatible Java version. 

https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/#forge-versions
