### ISSUE TITLE
Java Err while creating Container

### ISSUE THREAD

**Issue by LeRoid-hub** [itzg/docker-minecraft-server#3011]
### Describe the problem

I get an Error.
I know its after "Starting Minecraft server" but maybe somebody can help me.

### Container definition

docker run -d -it -e MEMORY=4G -p 25565:25565 -e EULA=TRUE -v /home/tomistkacke:/data itzg/minecraft-server:java17

### Container logs

[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Jul 22 17:54 /data'

[init] Resolving type given VANILLA

[init] Resolved version given LATEST into 1.21

[mc-image-helper] 18:07:20.232 INFO  : Created/updated 1 property in /data/server.properties

[init] Setting initial memory to 4G and max to 4G

[init] Starting the Minecraft server...

Error: LinkageError occurred while loading main class net.minecraft.bundler.Main

	java.lang.UnsupportedClassVersionError: net/minecraft/bundler/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Comment by rhullah** [comment]
Since you're not specifying a Minecraft version it's defaulting to latest which requires [Java 21](https://docker-minecraft-server.readthedocs.io/en/latest/versions/java/#class-file-version-650). Just didn't specify a tag on the image and it should work.

**Comment by LeRoid-hub** [comment]
i tried Java17 after it failed without a Tag. 
The Error message is the same

**Comment by rhullah** [comment]
Make sure you have pulled the latest image.

**Comment by LeRoid-hub** [comment]
I repulled the image and i can finally play some minecraft. 
Thank you guys for your help :)
