### ISSUE TITLE
Add the option to run /save-all before server shutdown and after server shutdown announcement

### ISSUE THREAD

**Issue by joeyak** [itzg/docker-minecraft-server#3019]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

Add an option to save the world before server shutdown. I ran into a situation where someone lost some items because the server restarted and they put iron in a chest, but after the restart, the chest didn't have the iron and the player didn't have it in their inventory. This is because the server saves at a different interval than entities.

**Comment by itzg** [comment]
When the container stops **normally** then a graceful stop of the server is initiated. Your container must have been terminated abnormally. Watch the logs during a start and you'll see the progression of normal saves and shutdown.
