### ISSUE TITLE
Request: add custom port ranges for plugins which rely on webservers for Trunas Scale users.

### ISSUE THREAD

**Issue by false-fox** [itzg/docker-minecraft-server#3050]
### Enhancement Type

A completely new feature

### Describe the enhancement

I'm in a bit of a pickle right now. I'm using Trunas Scale on my main computer and i'm running a minecraft server with docker-minecraft server. I want to add a plugin like bluemap or dynmap, which are popular plugins that host a webserver on a random port (8100 and 8123 respectively) providing a map overview of the world.

Unfortunately, Trunas Scale provides no methods to open custom ports on the docker container, and configuration is completely limited to what the app developers include in their configuration. i have no way to open ports 8100 or 8123 on HTTPS to free it from the docker container, meaning any web-based plugins are unusable for all Trunas Scale users. 

The enhancement i'm requesting is an option in the app configuration to open a single or a range of HTTP/HTTPS ports to allow web-server based plugins to work on Trunas. thank you.

**Comment by itzg** [comment]
Arbitrary port mappings can be added to any container. The image only declares ports to expose as advice to container creation. I'm not sure who maintains the TrueNAS "application", but you'll need to contact them to allow for additional ports.

**Comment by false-fox** [comment]
> Arbitrary port mappings can be added to any container. The image only declares ports to expose as advice to container creation. I'm not sure who maintains the TrueNAS "application", but you'll need to contact them to allow for additional ports.

It seems like trunas maintains it themselves, i'll make an issue on their repository. not sure why this is so locked down in the first place. thank you :)
