### ISSUE TITLE
Remove Potential Inaccuracies From Variables Docs

### ISSUE THREAD

**Issue by lnorton89** [itzg/docker-minecraft-server#3113]
### Enhancement Type

Improve an existing feature

### Describe the enhancement

> The variables listed on this page are manually documented and may be out-of-date or inaccurate.
 All other documentation pages are actively maintained, so please use the search box above to find the desired topic.

What is the reasoning behind this? Seems like whatever build system is used for the docs could build a table based on the codebase (or an upstream codebase). Maybe I'm missing something, would love to contribute if needed.

**Comment by itzg** [comment]
#2137 is the placeholder for the custom tool that would be needed

**Comment by lnorton89** [comment]
I will do some research, thank you for providing the placeholder.

Closed due to duplicate #2137
