### ISSUE TITLE
disable healthcheck

### ISSUE THREAD

**Issue by T4ss** [itzg/docker-minecraft-server#3121]
### Describe the problem

how can i deactivate the healthcheck in my docker

or how do I prevent my servers from being stopped with "Stopping with rcon-cli"

### Container definition

```
Paste run command or compose file here
```

### Container logs

```
Paste logs here
```

**Comment by itzg** [comment]
Please don't open issues for discussions/questions. Also be sure to read the docs before posting a question that is answered there. 

As for "Stopping with rcon-cli" that is normal output when the container is being stopped. You'll need to investigate what is stopping the container.
