### ISSUE TITLE
Error in /start-deploy-FTBA when setting up new docker on Raspberry Pi5

### ISSUE THREAD

**Issue by KroneBonn** [itzg/docker-minecraft-server#3123]
### Describe the problem

I have tried to setup a container with this image today on a new Raspberry Pi 5, but am left with this error:
`/start-deployFTBA: line 48: =/arm: No such file or directory`
I have tried several combinations of modpacks from FTB and java version but ultimately run in the same error.
As I am new to docker it may be my fault, but looking into the GitHub commits it appears that the line throwing the error is rather new and the curl-call was handled differently before. I am not an expert in shell skripting, but this might be the problem. Would be happy for help.

### Container definition

```
docker run -d --name mc-ftb -e EULA=TRUE   -e TYPE=FTBA -e FTB_MODPACK_ID=119  -p 25565:25565 -v /home/samuel/Docker/Minecraft/FTB_DW_21/  itzg/minecraft-server:java17
```

but also with different modpack/java version:

```
docker run -d --name mc-ftb -e EULA=TRUE   -e TYPE=FTBA -e FTB_MODPACK_ID=20   -p 25565:25565 -v /home/samuel/Docker/Minecraft/FTB_IE_S/   itzg/minecraft-server:java8
```

### Container logs

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Oct 24 12:20 /data'

[init] Downloading FTB installer

[init] Downloading ARM installer

/start-deployFTBA: line 48: =/arm: No such file or directory
```

**Comment by itzg** [comment]
Yes your suspicion is mostly likely correct about that line probably being a new issue. I'll work on fixing that.

**Comment by itzg** [comment]
Or @IronMine if you can get to it before me. 

I'm guess it's a regression from #3108

**Comment by IronMine** [comment]
> Or @IronMine if you can get to it before me. 
> 
> I'm guess it's a regression from #3108

I am on it !

**Comment by KroneBonn** [comment]
Thanks for the speedy replies! Very much appreciated!

**Comment by IronMine** [comment]
> Thanks for the speedy replies! Very much appreciated!

i made a mistake i am sorry ! it's normal to be fast

**Comment by itzg** [comment]
Fix will be in this build https://github.com/itzg/docker-minecraft-server/actions/runs/11532283059
