### ISSUE TITLE
Crash Loop - Multiple possibilities

### ISSUE THREAD

**Issue by HostileGForce** [itzg/docker-minecraft-server#3141]
### Describe the problem

Server is running in TrueNAS Scale ElectricEel-24.10.0.1
Image itzg/minecraft-server:2024.10.2-java21

[RAW Crash Logs on GitHub](https://github.com/HostileGForce/bins/tree/main/mc-crashlogs-240908)

[crash-2024-11-08_08.58.36-server.txt](https://github.com/user-attachments/files/17682921/crash-2024-11-08_08.58.36-server.txt)
[crash-2024-11-08_08.59.37-server.txt](https://github.com/user-attachments/files/17682922/crash-2024-11-08_08.59.37-server.txt)
[2024-11-08-1.log](https://github.com/user-attachments/files/17682928/2024-11-08-1.log)
[debug-1.log](https://github.com/user-attachments/files/17682929/debug-1.log)
[truenas config](https://github.com/user-attachments/assets/23be5646-2dd0-43c4-ae6d-86fd6c711beb.png)

### Container definition

[
    {
        "Id": "19f3a6643e810ebfaa3d45c576c8d7b679bd76d4e7933e36882dff58e82d117c",
        "Created": "2024-11-08T19:20:51.208627213Z",
        "Path": "/start",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 53625,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2024-11-08T19:25:22.265391059Z",
            "FinishedAt": "2024-11-08T19:25:22.194682816Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2024-11-08T11:26:03.172865335-08:00",
                        "End": "2024-11-08T11:26:03.244788846-08:00",
                        "ExitCode": 1,
                        "Output": "failed to ping localhost:25565 : EOF"
                    },
                    {
                        "Start": "2024-11-08T11:26:08.245695842-08:00",
                        "End": "2024-11-08T11:26:08.329230089-08:00",
                        "ExitCode": 1,
                        "Output": "failed to ping localhost:25565 : EOF"
                    },
                    {
                        "Start": "2024-11-08T11:26:13.330269362-08:00",
                        "End": "2024-11-08T11:26:13.411572333-08:00",
                        "ExitCode": 1,
                        "Output": "failed to ping localhost:25565 : EOF"
                    },
                    {
                        "Start": "2024-11-08T11:26:18.41275459-08:00",
                        "End": "2024-11-08T11:26:18.477167637-08:00",
                        "ExitCode": 1,
                        "Output": "failed to ping localhost:25565 : EOF"
                    },
                    {
                        "Start": "2024-11-08T11:26:23.47962209-08:00",
                        "End": "2024-11-08T11:26:23.556467847-08:00",
                        "ExitCode": 0,
                        "Output": "localhost:25565 : version=1.21.1 online=0 max=20 motd='Peebis Moved'\n"
                    }
                ]
            }
        },
        "Image": "sha256:4a8bf7fb4043f07247e3bcf87d73c188f8836d5ba6c1af8b37d14e4d22e50620",
        "ResolvConfPath": "/mnt/.ix-apps/docker/containers/19f3a6643e810ebfaa3d45c576c8d7b679bd76d4e7933e36882dff58e82d117c/resolv.conf",
        "HostnamePath": "/mnt/.ix-apps/docker/containers/19f3a6643e810ebfaa3d45c576c8d7b679bd76d4e7933e36882dff58e82d117c/hostname",
        "HostsPath": "/mnt/.ix-apps/docker/containers/19f3a6643e810ebfaa3d45c576c8d7b679bd76d4e7933e36882dff58e82d117c/hosts",
        "LogPath": "/mnt/.ix-apps/docker/containers/19f3a6643e810ebfaa3d45c576c8d7b679bd76d4e7933e36882dff58e82d117c/19f3a6643e810ebfaa3d45c576c8d7b679bd76d4e7933e36882dff58e82d117c-json.log",
        "Name": "/ix-dw21-minecraft-1",
        "RestartCount": 2,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "ix-dw21_default",
            "PortBindings": {
                "25565/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "25565"
                    }
                ],
                "25575/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "25575"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": [
                "CHOWN",
                "DAC_OVERRIDE",
                "FOWNER",
                "SETGID",
                "SETUID"
            ],
            "CapDrop": [
                "ALL"
            ],
            "CgroupnsMode": "private",
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [
                "no-new-privileges"
            ],
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 9646899200,
            "NanoCpus": 12000000000,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 19293798400,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "bind",
                    "Source": "/mnt/HDD/MC/DW21 1",
                    "Target": "/data",
                    "BindOptions": {
                        "Propagation": "rprivate"
                    }
                },
                {
                    "Type": "volume",
                    "Target": "/tmp",
                    "VolumeOptions": {}
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/mnt/.ix-apps/docker/overlay2/fa2509733f9f5f5435bd3a725e489874b4ef424a0ea0649a9328e28b4d0fbc28-init/diff:/mnt/.ix-apps/docker/overlay2/41860b1a67e542968e3cee0bc110eb92c763b47dd4539dd8a48fb8f458d2ddf8/diff:/mnt/.ix-apps/docker/overlay2/5bee40c1eff4e0c166a371406b16c8512dfb0cbf17b62880b05ae22889c7a144/diff:/mnt/.ix-apps/docker/overlay2/2e3595cede769350edc4b1db69c1bd008c973c4e65d87ec6daa25dfeb37641cd/diff:/mnt/.ix-apps/docker/overlay2/eafd2155a9f7d77157b6c6bdd0e0d325e2eb7e4cbbb187afbf912c05ff38fe88/diff:/mnt/.ix-apps/docker/overlay2/1959133a4dc1c23c20454ac9f23e1ac6e942503c43e4843fbdcf4516f828474a/diff:/mnt/.ix-apps/docker/overlay2/909b4c1f673d2c3f42e71515bc4af90087b77255e864c2754e01550384f0542c/diff:/mnt/.ix-apps/docker/overlay2/d41ab3a08b2ddec667d77cc732a35ec5fee771c4b679e3a213a449cf4dfbe014/diff:/mnt/.ix-apps/docker/overlay2/2e006fdac20b61d1558cf056b5a90f037e963acdb48a26df474c8239060fb266/diff:/mnt/.ix-apps/docker/overlay2/4a01fb62e61151a90ccce93ff6e5b286b6cfdf0b7f22f7fa98eb220affd08125/diff:/mnt/.ix-apps/docker/overlay2/a3d9e477417657e356e1498aa854864d6e9243a627c1698bc911b491cb832f28/diff:/mnt/.ix-apps/docker/overlay2/a58ecc5d92cbfbd8230884ae870852eaeabc530a8c17c945329cf552e699f093/diff:/mnt/.ix-apps/docker/overlay2/b8bccd5cf454563b50c48e89d3ae40e8253bcab7cac8f162139965e97d38db47/diff:/mnt/.ix-apps/docker/overlay2/ee84f705829b05321362592060440850811090a34e160cf95672e17afd275799/diff:/mnt/.ix-apps/docker/overlay2/d1ea48ee3bf91398afdfdddb844faa50696cc29bc2375c99d07b7ff8924c4379/diff:/mnt/.ix-apps/docker/overlay2/5556d848c153e62d9984b3048b51da71729e5bd2a423ed7b3e3b6cf59987d685/diff:/mnt/.ix-apps/docker/overlay2/797ae21e01473f79cf3b6e7e313ce1b0dc251e80bb6230242dcaa64241dafac8/diff:/mnt/.ix-apps/docker/overlay2/54baa00e6e23875e6d305e0615719966f8e026ad8b466250c73ebaee2df46406/diff:/mnt/.ix-apps/docker/overlay2/2ad16648bb4c31739c7fd2fa8f49146509e762ca044d45e3286f9acc59c8d0af/diff:/mnt/.ix-apps/docker/overlay2/30da8edddc3f88d4e976ce753981fac7bf61294f42d53708b4ed648383c42f49/diff:/mnt/.ix-apps/docker/overlay2/865da55904f17c92e3151a3528dc2701761ce13554858f91eda00d9ee431f01d/diff:/mnt/.ix-apps/docker/overlay2/e9631280c3e22e74a192d795f32f96efebdb032898dc5bd0ce4b878230c720d5/diff:/mnt/.ix-apps/docker/overlay2/2611f79bd05f2cdbebfe2e6fa4afe4e63fa7a8a9104a4ab411897472207a7216/diff:/mnt/.ix-apps/docker/overlay2/29d3f5e5ba647d7c03c5f3028268a737fabdeae1f2fd8543945b5aade6616680/diff",
                "MergedDir": "/mnt/.ix-apps/docker/overlay2/fa2509733f9f5f5435bd3a725e489874b4ef424a0ea0649a9328e28b4d0fbc28/merged",
                "UpperDir": "/mnt/.ix-apps/docker/overlay2/fa2509733f9f5f5435bd3a725e489874b4ef424a0ea0649a9328e28b4d0fbc28/diff",
                "WorkDir": "/mnt/.ix-apps/docker/overlay2/fa2509733f9f5f5435bd3a725e489874b4ef424a0ea0649a9328e28b4d0fbc28/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/HDD/MC/DW21 1",
                "Destination": "/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "52b94259302d49399f886e437c4202955c95069a1b4b8184b0aa56015e2e9da0",
                "Source": "/mnt/.ix-apps/docker/volumes/52b94259302d49399f886e437c4202955c95069a1b4b8184b0aa56015e2e9da0/_data",
                "Destination": "/tmp",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "19f3a6643e81",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "25565/tcp": {},
                "25575/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "SPAWN_PROTECTION=16",
                "ANNOUNCE_PLAYER_ACHIEVMENTS=TRUE",
                "GID=568",
                "SERVER_PORT=25565",
                "DIFFICULTY=hard",
                "RCON_PASSWORD=RCONAdminPassword4$",
                "MODE=survival",
                "MOTD=Peebis Moved",
                "MAX_TICK_TIME=60000",
                "FTB_MODPACK_ID=126",
                "MAX_PLAYERS=20",
                "INIT_MEMORY=4G",
                "MAX_WORLD_SIZE=10000",
                "SERVER_NAME=dw21",
                "ONLINE_MODE=TRUE",
                "PUID=568",
                "RCON_PORT=25575",
                "LEVEL_TYPE=minecraft:default",
                "ALLOW_NETHER=TRUE",
                "ENABLE_COMMAND_BLOCK=FALSE",
                "USER_ID=568",
                "FORCE_GAMEMODE=FALSE",
                "VERSION=1.21.1",
                "MAX_MEMORY=8G",
                "SPAWN_ANIMALS=TRUE",
                "SPAWN_NPCS=TRUE",
                "PGID=568",
                "GENERATE_STRUCTURES=TRUE",
                "GUI=FALSE",
                "EULA=TRUE",
                "PVP=TRUE",
                "SEED=BoyMilk",
                "MAX_BUILD_HEIGHT=256",
                "ENABLE_RCON=TRUE",
                "UID=568",
                "ALLOW_FLIGHT=TRUE",
                "VIEW_DISTANCE=20",
                "HARDCORE=FALSE",
                "GROUP_ID=568",
                "TYPE=FTBA",
                "TZ=America/Los_Angeles",
                "SPAWN_MONSTERS=TRUE",
                "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "JAVA_HOME=/opt/java/openjdk",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "JAVA_VERSION=jdk-21.0.4+7"
            ],
            "Cmd": null,
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "mc-health"
                ],
                "Interval": 10000000000,
                "Timeout": 5000000000,
                "StartPeriod": 120000000000,
                "Retries": 30
            },
            "Image": "itzg/minecraft-server:2024.10.2-java21",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "/data",
            "Entrypoint": [
                "/start"
            ],
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "5942d500f8a8d788a50c2f55d58ea053e6a54d69f376df68c57c9185d32e24dd",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:4a8bf7fb4043f07247e3bcf87d73c188f8836d5ba6c1af8b37d14e4d22e50620",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "ix-dw21",
                "com.docker.compose.project.config_files": "/mnt/.ix-apps/app_configs/dw21/versions/1.11.22/templates/rendered/docker-compose.yaml",
                "com.docker.compose.project.working_dir": "/mnt/.ix-apps/app_configs/dw21/versions/1.11.22/templates/rendered",
                "com.docker.compose.service": "minecraft",
                "com.docker.compose.version": "2.29.1",
                "org.opencontainers.image.authors": "Geoff Bourne <itzgeoff@gmail.com>",
                "org.opencontainers.image.created": "2024-10-18T19:46:58.152Z",
                "org.opencontainers.image.description": "Docker image that provides a Minecraft Server that will automatically download selected version at startup",
                "org.opencontainers.image.licenses": "Apache-2.0",
                "org.opencontainers.image.ref.name": "ubuntu",
                "org.opencontainers.image.revision": "a9140fb84aaf156de4d45762c36bfe15cf52efa4",
                "org.opencontainers.image.source": "https://github.com/itzg/docker-minecraft-server",
                "org.opencontainers.image.title": "docker-minecraft-server",
                "org.opencontainers.image.url": "https://github.com/itzg/docker-minecraft-server",
                "org.opencontainers.image.version": "2024.10.2"
            },
            "StopSignal": "SIGTERM"
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "64113a0db8dc7e643fba2a95c02eb6cec1ed5bf2b4c2ad879d744a604740468a",
            "SandboxKey": "/var/run/docker/netns/64113a0db8dc",
            "Ports": {
                "25565/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "25565"
                    }
                ],
                "25575/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "25575"
                    }
                ]
            },
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "ix-dw21_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "ix-dw21-minecraft-1",
                        "minecraft"
                    ],
                    "MacAddress": "02:42:ac:10:01:02",
                    "DriverOpts": null,
                    "NetworkID": "4ddf67af648a43434a7d36834b894106ad109ed031464c7bbfcbe74651e852ab",
                    "EndpointID": "ef895807d8a679e63cdd8edd4aa5340c13df2267ea6f1c15a5f9d32948f1af24",
                    "Gateway": "172.16.1.1",
                    "IPAddress": "172.16.1.2",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "DNSNames": [
                        "ix-dw21-minecraft-1",
                        "minecraft",
                        "19f3a6643e81"
                    ]
                }
            }
        }
    }
]

### Container logs

line limit issue with truenas shell

**Comment by itzg** [comment]
I haven't had a chance to look at logs yet (since I'm viewing from my phone) but I see that you're using FTBA type. That is almost completely managed by their installer so there's not really anything I can change or much help I can provide with that. 

Even more so since you're getting crash logs hopefully they can provide support for that modpack.

**Comment by HostileGForce** [comment]
Ill go and harass them instead lol
thanks!

**Comment by HostileGForce** [comment]
NVM, it was an incompatible mod that the pack owners fixed. thanks for the kind reply regardless!
