### ISSUE TITLE
Forge installs failing with 403 forbidden on promotions_slim.json retrieval

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#3160]
Forge seems to be disallowing automated access to the crucial, first-step of Forge installation process

```
curl -fsSL https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
curl: (56) The requested URL returned error: 403
```

**Comment by Lumysia** [comment]
me too.

**Comment by Lumysia** [comment]
maybe [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr) will help?

**Comment by itzg** [comment]
Phew, good. 

Thanks for sharing the FlareSolverr project...however I'd have to host that somewhere.

**Comment by itzg** [comment]
I'll continue working on an option to lookup and download Forge installer via maven (and the Creeperhost repo). The downside to that option will be the lack of latest vs recommended delineation.
