### ISSUE TITLE
AccessDeniedException for session.lock When Using Old World Folder in Minecraft Server Version 1.21.4

### ISSUE THREAD

**Issue by FredLiuuuu** [itzg/docker-minecraft-server#3175]
### Describe the problem

After upgrading to version 1.21.4 of the Minecraft server, I encountered an AccessDeniedException error related to the session.lock file in the world folder. The server fails to start with the following error message:

```
java.nio.file.AccessDeniedException: ./world/session.lock
[03:32:02] [ServerMain/ERROR]: Failed to start the minecraft server
```

Reproduction Steps:
	1.	I had a working world folder from version 1.21.3.
	2.	I updated my server to version 1.21.4.
	3.	I copied the existing world folder from the 1.21.3 server into the data directory of the new server.
	4.	Upon starting the server, the above error occurs, and the server fails to load.

Additional Observations:
	•	If I run the 1.21.4 server with a fresh world folder (without copying the old one), the server starts and runs fine.
	•	The world folder from version 1.21.3 works perfectly in single-player mode without any issues.

Steps Taken:
	•	I ensured file permissions for the world folder are correct (drwxr-xr-x) and owned by the same user running the server.
	•	I confirmed the session.lock file exists and is accessible by the server.
	•	The issue persists even after multiple attempts to restart the server.

Environment Details:
	•	Minecraft server version: 1.21.4
	•	Type: Vanilla
	•	Memory settings: Initial 1G, Max 1G
	•	OS/Environment: Dockerized environment running as uid=1000 gid=1000
	•	The issue occurs after the [init] Starting the Minecraft server log.

Request:
Could you investigate this issue and confirm if there is a compatibility problem between the world folder from 1.21.3 and 1.21.4? If this is a bug, I would appreciate any guidance on resolving it or a patch.

### Container definition

```
docker run -d \
  -p 25565:25565 \
  -v /docker/Server_Sean:/data \
  -e PATH=/opt/java/openjdk/bin:/usr \
  -e JAVA_HOME=/opt/java/openjdk \
  -e LANG=en_US.UTF-8 \
  -e LANGUAGE=en_US:en \
  -e LC_ALL=en_US.UTF-8 \
  -e JAVA_VERSION=jdk-21.0.5+11 \
  -e TYPE=VANILLA \
  -e VERSION=LATEST \
  -e EULA=True \
  -e UID=1000 \
  -e GID=1000 \
  --name itzg-minecraft-server-Sean \
  itzg/minecraft-server:latest
```

### Container logs

```
<head></head>
2024/12/04 14:32:02 | stdout | 2024-12-04T03:32:02.916Z INFO mc-server-runner Done
-- | -- | --
2024/12/04 14:32:02 | stdout | at java.base/java.lang.Thread.run(Unknown Source) [?:?]
2024/12/04 14:32:02 | stdout | at net.minecraft.bundler.Main.lambda$run$0(Main.java:54) ~[?:?]
2024/12/04 14:32:02 | stdout | at net.minecraft.server.Main.main(SourceFile:139) ~[server-1.21.4.jar:?]
2024/12/04 14:32:02 | stdout | at evg.d(SourceFile:353) ~[server-1.21.4.jar:?]
2024/12/04 14:32:02 | stdout | at evg$c.<init>(SourceFile:374) ~[server-1.21.4.jar:?]
2024/12/04 14:32:02 | stdout | at ayf.a(SourceFile:34) ~[server-1.21.4.jar:?]
2024/12/04 14:32:02 | stdout | at java.base/java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]
2024/12/04 14:32:02 | stdout | at java.base/java.nio.channels.FileChannel.open(Unknown Source) ~[?:?]
2024/12/04 14:32:02 | stdout | at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source) ~[?:?]
2024/12/04 14:32:02 | stdout | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
2024/12/04 14:32:02 | stdout | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) ~[?:?]
2024/12/04 14:32:02 | stdout | at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) ~[?:?]
2024/12/04 14:32:02 | stdout | java.nio.file.AccessDeniedException: ./world/session.lock
2024/12/04 14:32:02 | stdout | [03:32:02] [ServerMain/ERROR]: Failed to start the minecraft server
2024/12/04 14:32:02 | stdout | [03:32:02] [ServerMain/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
2024/12/04 14:31:52 | stdout | Starting net.minecraft.server.Main
2024/12/04 14:31:52 | stdout | [init] Starting the Minecraft server...
2024/12/04 14:31:52 | stdout | [0;39m[init] Setting initial memory to 1G and max to 1G
2024/12/04 14:31:52 | stdout | [39m[mc-image-helper] 03:31:52.314 INFO  : Created/updated 1 property in /data/server.properties
2024/12/04 14:31:50 | stdout | [init] Resolved version given LATEST into 1.21.4
2024/12/04 14:31:47 | stdout | [init] Resolving type given VANILLA
2024/12/04 14:31:47 | stdout | [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 1 1000 1000 374 Dec  4 03:30 /data'


```

**Comment by itzg** [comment]
You introduced a problem at step 3. When copying the files you need to ensure they are correctly owned and appropriate permissions. 

There's no need to copy files around on an upgrade. Just recreate the container the VERSION changed and remount the same data directory. Or if using the default version of "latest", just restart the container.

**Comment by FredLiuuuu** [comment]
Thanks, I change the permissions of the folder, and it works again.
