### ISSUE TITLE
Auto pause example compose file is linked in docs but no longer exists / has moved

### ISSUE THREAD

**Issue by ASOwnerYT** [itzg/docker-minecraft-server#3187]
### Describe the problem

The [auto pause wiki page](https://docker-minecraft-server.readthedocs.io/en/latest/misc/autopause-autostop/autopause/) links to [this](https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-autopause.yml) as the example compose file, but the link no longer exists and shows 404 page not found error. The documentation should link to [this](https://github.com/itzg/docker-minecraft-server/blob/master/examples/autopause/compose.yml) instead.

**Comment by itzg** [comment]
Thanks for reporting this.
