### ISSUE TITLE
Forge java configuration mismatch issue. "UseG1GC  ParallelGCThreads"

### ISSUE THREAD

**Issue by kingofkya** [itzg/docker-minecraft-server#321]
When trying to start a fresh forge server i get a java config issue. Is there any work around? I tried to play with JVM_DD_OPTS and JVM_OPTS= but I wasn't able to change anything. Other mod packs and vanilla work just fine.

`flag -XX:+UseG1GC can not be combined with -XX:ParallelGCThreads=0`

The following variables are set: (nothing special)
MCPort:	25565
TYPE:FORGE
 EULA:	TRUE
 Data: /mnt/user/appdata/minecrafttravis/data/
 MAX_MEMORY:	4
 INIT_MEMORY:       2
 

Docker Logs:
_______________________________________________________________________________
`
Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 1 1000 1000 282 May 16 23:59 /data'
Checking version information.

Checking type information.
Checking Forge version information.

server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 2 and max to 4
Starting the Minecraft server...
Error occurred during initialization of VM

The flag -XX:+UseG1GC can not be combined with -XX:ParallelGCThreads=0
2019/05/17 00:00:05 Done
`

**Comment by itzg** [comment]
The only thing I’m wondering about is that the memory settings without units might cause problems. I’ll investigate some more.

**Comment by itzg** [comment]
Without the units mine fails to start, but with a more relevant error message:

```
Checking for JSON files.
Copying any mods over...
Setting initial memory to 2 and max to 4
Starting the Minecraft server...
Error occurred during initialization of VM
Too small initial heap
2019/05/17 20:14:14 Done
```

Leaving off the `INIT_MEMORY` and `MAX_MEMORY` it starts fine though

```
> docker run -it --rm -e EULA=TRUE -e TYPE=FORGE itzg/minecraft-server
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 May 17 20:12 /data'
Checking version information.
Checking type information.
Checking Forge version information.
Downloading 1.12.2-14.23.5.2768-1.14.1

  ...several download logs...

docker run -it --rm -e EULA=TRUE -e TYPE=FORGE itzg/minecraft-server
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 May 17 20:12 /data'
Checking version information.
Checking type information.
Checking Forge version information.
Downloading 1.12.2-14.23.5.2768-1.14.1
```

**Comment by kingofkya** [comment]
Interesting, that were getting different results. So more info my host OS is Unraid, running on a 64bit Xeon e3 v1 if that helps at all.

I created a new one with:
TYPE:FORGE
EULA:	TRUE
Data: /mnt/user/appdata/minecrafttest/data/


Hears some better logs from this attempt with ram not set note that the /data folder is brand new nothing in it.

`usermod: no changes
Changing ownership of /data to 1000 ...
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 1 1000 1000 22 May 17 15:21 /data'
Checking version information.

Checking type information.
Checking Forge version information.

Downloading 1.12.2-14.23.5.2768-1.14.1
...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768-1.14.1/forge-1.12.2-14.23.5.2768-1.14.1-installer.jar
curl: (22) The requested URL returned error: 404 Not Found

...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2768/forge-1.12.2-14.23.5.2768-installer.jar
Installing Forge 1.12.2-14.23.5.2768 using /tmp/forge-1.12.2-14.23.5.2768-installer.jar
Setting up logger: /data/forge-1.12.2-14.23.5.2768-installer.jar.log
java.net.preferIPv4Stack=true
Installing server to current directory
MESSAGE: Data kindly mirrored by Forge at http://MinecraftForge.net/
MESSAGE: Considering minecraft server jar
MESSAGE: Downloading minecraft server version 1.12.2

ETag: 71728ed3fbd0acd1394bf3ade2649a5c
MD5: 71728ed3fbd0acd1394bf3ade2649a5c
MESSAGE: Considering library net.minecraftforge:forge:1.12.2-14.23.5.2768: Not Downloading {Wrong Side}
MESSAGE: Considering library net.minecraft:launchwrapper:1.12
MESSAGE: Downloading library net.minecraft:launchwrapper:1.12
MESSAGE: Trying unpacked library net.minecraft:launchwrapper:1.12
MESSAGE: Trying unpacked library net.minecraft:launchwrapper:1.12
MESSAGE: Considering library org.ow2.asm:asm-all:5.2
MESSAGE: Downloading library org.ow2.asm:asm-all:5.2
MESSAGE: Trying unpacked library org.ow2.asm:asm-all:5.2
MESSAGE: Considering library org.jline:jline:3.5.1
MESSAGE: Downloading library org.jline:jline:3.5.1
MESSAGE: Trying unpacked library org.jline:jline:3.5.1
MESSAGE: Considering library net.java.dev.jna:jna:4.4.0
MESSAGE: Downloading library net.java.dev.jna:jna:4.4.0
MESSAGE: Considering library net.java.dev.jna:jna:4.4.0
MESSAGE: Downloading library net.java.dev.jna:jna:4.4.0
MESSAGE: Trying unpacked library net.java.dev.jna:jna:4.4.0
MESSAGE: Considering library com.typesafe.akka:akka-actor_2.11:2.3.3
MESSAGE: Downloading library com.typesafe.akka:akka-actor_2.11:2.3.3
MESSAGE: Unpacking packed file akka-actor_2.11-2.3.3.jar.pack.xz
Signed
Checksum Length: 140942

Total Length: 2606968
Temp File: /tmp/art6739036659537550064.pack
Signed
Checksum Length: 140942

Total Length: 2606968
Temp File: /tmp/art6739036659537550064.pack
MESSAGE: Successfully unpacked packed file akka-actor_2.11-2.3.3.jar.pack.xz
Checking "/data/./libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library com.typesafe:config:1.2.1
MESSAGE: Downloading library com.typesafe:config:1.2.1
MESSAGE: Unpacking packed file config-1.2.1.jar.pack.xz
Signed
Checksum Length: 12246

Total Length: 111476
Temp File: /tmp/art7840990770397459512.pack
MESSAGE: Successfully unpacked packed file config-1.2.1.jar.pack.xz
Checking "/data/./libraries/com/typesafe/config/1.2.1/config-1.2.1.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-actors-migration_2.11:1.1.0
MESSAGE: Downloading library org.scala-lang:scala-actors-migration_2.11:1.1.0
MESSAGE: Unpacking packed file scala-actors-migration_2.11-1.1.0.jar.pack.xz
Signed
Checksum Length: 3311

Total Length: 52481
Temp File: /tmp/art5332915732419616961.pack
MESSAGE: Successfully unpacked packed file scala-actors-migration_2.11-1.1.0.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-compiler:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-compiler:2.11.1
MESSAGE: Successfully unpacked packed file config-1.2.1.jar.pack.xz
Checking "/data/./libraries/com/typesafe/config/1.2.1/config-1.2.1.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-actors-migration_2.11:1.1.0
MESSAGE: Downloading library org.scala-lang:scala-actors-migration_2.11:1.1.0
MESSAGE: Unpacking packed file scala-actors-migration_2.11-1.1.0.jar.pack.xz
Signed
Checksum Length: 3311

Total Length: 52481
Temp File: /tmp/art5332915732419616961.pack
MESSAGE: Successfully unpacked packed file scala-actors-migration_2.11-1.1.0.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-compiler:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-compiler:2.11.1
MESSAGE: Unpacking packed file scala-compiler-2.11.1.jar.pack.xz
Signed
Checksum Length: 942120

Total Length: 9183051
Temp File: /tmp/art1353131200233370164.pack
MESSAGE: Successfully unpacked packed file scala-compiler-2.11.1.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang.plugins:scala-continuations-library_2.11:1.0.2
MESSAGE: Downloading library org.scala-lang.plugins:scala-continuations-library_2.11:1.0.2
MESSAGE: Unpacking packed file scala-continuations-library_2.11-1.0.2.jar.pack.xz
Signed
Checksum Length: 2416

Total Length: 18871
Temp File: /tmp/art247996518190541156.pack
MESSAGE: Successfully unpacked packed file scala-continuations-library_2.11-1.0.2.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang.plugins:scala-continuations-plugin_2.11.1:1.0.2
MESSAGE: Downloading library org.scala-lang.plugins:scala-continuations-plugin_2.11.1:1.0.2
MESSAGE: Unpacking packed file scala-continuations-plugin_2.11.1-1.0.2.jar.pack.xz
Signed
Checksum Length: 16815

Total Length: 139418
Temp File: /tmp/art926461137234455964.pack
MESSAGE: Successfully unpacked packed file scala-continuations-plugin_2.11.1-1.0.2.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-library:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-library:2.11.1
MESSAGE: Successfully unpacked packed file scala-continuations-plugin_2.11.1-1.0.2.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-library:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-library:2.11.1
MESSAGE: Unpacking packed file scala-library-2.11.1.jar.pack.xz
MESSAGE: Unpacking packed file scala-library-2.11.1.jar.pack.xz
Signed
Checksum Length: 341368

Total Length: 5984083
Temp File: /tmp/art5192718239025156371.pack
MESSAGE: Successfully unpacked packed file scala-library-2.11.1.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-parser-combinators_2.11:1.0.1
MESSAGE: Downloading library org.scala-lang:scala-parser-combinators_2.11:1.0.1
MESSAGE: Unpacking packed file scala-parser-combinators_2.11-1.0.1.jar.pack.xz
Signed
Checksum Length: 37614

Total Length: 273457
Temp File: /tmp/art2776384456034571313.pack
MESSAGE: Successfully unpacked packed file scala-parser-combinators_2.11-1.0.1.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-reflect:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-reflect:2.11.1
MESSAGE: Successfully unpacked packed file scala-parser-combinators_2.11-1.0.1.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-reflect:2.11.1
MESSAGE: Downloading library org.scala-lang:scala-reflect:2.11.1
MESSAGE: Unpacking packed file scala-reflect-2.11.1.jar.pack.xz
Signed
Checksum Length: 291610

Total Length: 3217021
Temp File: /tmp/art449189937609157320.pack
MESSAGE: Successfully unpacked packed file scala-reflect-2.11.1.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-swing_2.11:1.0.1
MESSAGE: Downloading library org.scala-lang:scala-swing_2.11:1.0.1
MESSAGE: Unpacking packed file scala-swing_2.11-1.0.1.jar.pack.xz
Signed
Checksum Length: 39019

Total Length: 888907
Temp File: /tmp/art9221363722309440266.pack
MESSAGE: Successfully unpacked packed file scala-swing_2.11-1.0.1.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-xml_2.11:1.0.2
MESSAGE: Downloading library org.scala-lang:scala-xml_2.11:1.0.2
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library org.scala-lang:scala-xml_2.11:1.0.2
MESSAGE: Downloading library org.scala-lang:scala-xml_2.11:1.0.2
MESSAGE: Unpacking packed file scala-xml_2.11-1.0.2.jar.pack.xz
Signed
Checksum Length: 35380

Total Length: 739509
Temp File: /tmp/art8920474907817033541.pack
MESSAGE: Successfully unpacked packed file scala-xml_2.11-1.0.2.jar.pack.xz
Checking "/data/./libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar" internal checksums
checksums.sha1 validated successfully
Jar contents validated successfully
MESSAGE: Considering library lzma:lzma:0.0.1
MESSAGE: Downloading library lzma:lzma:0.0.1
MESSAGE: Trying unpacked library lzma:lzma:0.0.1
MESSAGE: Considering library net.sf.jopt-simple:jopt-simple:5.0.3
MESSAGE: Downloading library net.sf.jopt-simple:jopt-simple:5.0.3
MESSAGE: Trying unpacked library net.sf.jopt-simple:jopt-simple:5.0.3
MESSAGE: Trying unpacked library lzma:lzma:0.0.1
MESSAGE: Considering library net.sf.jopt-simple:jopt-simple:5.0.3
MESSAGE: Downloading library net.sf.jopt-simple:jopt-simple:5.0.3
MESSAGE: Trying unpacked library net.sf.jopt-simple:jopt-simple:5.0.3
MESSAGE: Considering library java3d:vecmath:1.5.2
MESSAGE: Downloading library java3d:vecmath:1.5.2
MESSAGE: Trying unpacked library java3d:vecmath:1.5.2
MESSAGE: Considering library net.sf.trove4j:trove4j:3.0.3
MESSAGE: Downloading library net.sf.trove4j:trove4j:3.0.3
MESSAGE: Trying unpacked library net.sf.trove4j:trove4j:3.0.3
MESSAGE: Considering library org.apache.maven:maven-artifact:3.5.3
MESSAGE: Downloading library org.apache.maven:maven-artifact:3.5.3
MESSAGE: Trying unpacked library org.apache.maven:maven-artifact:3.5.3
Extracting: /forge-1.12.2-14.23.5.2768-universal.jar
To: /data/./forge-1.12.2-14.23.5.2768-universal.jar
The server installed successfully, you should now be able to run the file forge-1.12.2-14.23.5.2768-universal.jar
You can delete this installer file now if you wish
Finding installed server jar...
Using server forge-1.12.2-14.23.5.2768-universal.jar
Creating server.properties in /data/server.properties
Setting server-name to 'Dedicated Server' in /data/server.properties
Setting server-port to '25565' in /data/server.properties
Setting motd to 'A Forge Minecraft Server powered by Docker' in /data/server.properties
Skip setting allow-nether
Skip setting announce-player-achievements
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Skip setting view-distance
Skip setting hardcore
Skip setting snooper-enabled
Skip setting max-build-height
Skip setting force-gamemode
Skip setting max-tick-time
Skip setting enable-query
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'minecraft' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Skip setting max-players
Skip setting max-world-size
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'true' in /data/server.properties
Skip setting allow-flight
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
MESSAGE: Considering library org.apache.maven:maven-artifact:3.5.3
MESSAGE: Downloading library org.apache.maven:maven-artifact:3.5.3
MESSAGE: Trying unpacked library org.apache.maven:maven-artifact:3.5.3
Extracting: /forge-1.12.2-14.23.5.2768-universal.jar
To: /data/./forge-1.12.2-14.23.5.2768-universal.jar
The server installed successfully, you should now be able to run the file forge-1.12.2-14.23.5.2768-universal.jar
You can delete this installer file now if you wish
Finding installed server jar...
Using server forge-1.12.2-14.23.5.2768-universal.jar
Creating server.properties in /data/server.properties
Setting server-name to 'Dedicated Server' in /data/server.properties
Setting server-port to '25565' in /data/server.properties
Setting motd to 'A Forge Minecraft Server powered by Docker' in /data/server.properties
Skip setting allow-nether
Skip setting announce-player-achievements
Skip setting enable-command-block
Skip setting spawn-animals
Skip setting spawn-monsters
Skip setting spawn-npcs
Skip setting generate-structures
Skip setting view-distance
Skip setting hardcore
Skip setting snooper-enabled
Skip setting max-build-height
Skip setting force-gamemode
Skip setting max-tick-time
Skip setting enable-query
Skip setting query.port
Setting enable-rcon to 'true' in /data/server.properties
Setting rcon.password to 'minecraft' in /data/server.properties
Setting rcon.port to '25575' in /data/server.properties
Skip setting max-players
Skip setting max-world-size
Setting level-name to 'world' in /data/server.properties
Skip setting level-seed
Setting pvp to 'true' in /data/server.properties
Skip setting generator-settings
Setting online-mode to 'true' in /data/server.properties
Skip setting allow-flight
Setting level-type to 'DEFAULT' in /data/server.properties
Setting difficulty to '1' in /data/server.properties
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 1G
Starting the Minecraft server...
Error occurred during initialization of VM

The flag -XX:+UseG1GC can not be combined with -XX:ParallelGCThreads=0
2019/05/17 15:23:03 Done`

**Comment by kingofkya** [comment]
Hears the exact command it runs if that helps:

```
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Minecraft-Forge-Travis' --net='bridge' --cpuset-cpus='4,5,6' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -e 'TYPE'='FORGE' -e 'EULA'='TRUE' -v '/mnt/user/appdata/minecrafttest/data':'/data':'rw' 'itzg/minecraft-server' 

```

**Comment by itzg** [comment]
It's really strange that `ParallelGCThreads` is getting referenced in your container. That setting is not referenced anywhere in the repository:

https://github.com/itzg/dockerfiles/search?q=ParallelGCThreads&unscoped_q=ParallelGCThreads

The `JVM_XX_OPTS` is what conveys the G1GC setting

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/Dockerfile#L74

From the command-line you showed that Unraid uses, I can't guess where the extra JVM setting is coming from. It doesn't seem to be Forge re-launching java since that exact same version works fine for me.

**Comment by kingofkya** [comment]
OK i think i figured out whats triggering it when manual running the docker command from terminal i can remove some of the commands, and removing this fixes it  --cpuset-cpus='4,5,6' see if you can replicate.

I am still kinda lost as to where that ParallelGCThreads is getting referenced too because i did the same thing and searched the repo and didn't see it.

**Comment by kingofkya** [comment]
This also fixes it fyi. --cpuset-cpus='0,1,2,3,4,5,6,7' on my 8 core system.

**Comment by Deathhorn** [comment]
@kingofkya where do u set this parameter?

**Comment by Mondei1** [comment]
Just jumping in here. I have the same problem here but with PaperSpigot (Spigot too). 

My command line is this: `docker run -dit -e TYPE=PAPER -e VERSION=1.13.2 -e EULA=TRUE -e ONLINE_MODE=FALSE -v /srv/minecraft/templates/lobby:/data -p 1001:25565 --name mc.lobby_1 itzg/minecraft-server --noconsole --cpuset-cpus='0,1,2,3,4,5'`

If I leave this `--cpuset-cpus` away, it doesn't change the result. My servers distro is Debian 10. The funny thing is when I test this at my own PC (Pop!_OS 19.04) everything runs well. The logs are the same, so no reason to attach them.
