### ISSUE TITLE
pid file

### ISSUE THREAD

**Issue by sergey-koshelev** [itzg/docker-minecraft-server#325]
**[minecraft-server] Feature request: pid file**

Minecraft server doesn't provide his pid in file so it is difficult to monitor it execution by Monit
It would be great if in start script you could add this command:
_**echo $$ > /data/mcserver.pid**_  before **exec start-configuration**

**Comment by itzg** [comment]
That is certainly easy to add; however, I'm not sure if it'll do what is needed by monit since the PID namespace is isolated within containers. For example, launching into bash gives a PID 1 :

```
$ docker run -it --rm --entrypoint bash itzg/minecraft-server
bash-4.4# echo $$
1
```

From host, that same process is actually PID 3057:

```
root       733     1  0 20:51 ?        00:00:00   /usr/bin/containerd
root      3039   733  0 20:55 ?        00:00:00     containerd-shim -namespace m
root      3057  3039  0 20:55 pts/0    00:00:00       bash
```

If you're needing the minecraft server to auto-restart on failure, then Docker can already manage that with https://docs.docker.com/compose/compose-file/#restart

Let me know if you still want me to add the statement into the startup script.

**Comment by sergey-koshelev** [comment]
You are certainly right. If you run from the command line using just docker command - you will get PID address space local to the container. But there is the way to make container use host PID space. I'm using this docker-compose file:

version: '3.5'
services:
  minecraft:
    image: minecraft-server:latest
    environment:
      - EULA=TRUE
      - VERSION=LATEST
      - INIT_MEMORY=2G
      - MAX_MEMORY=4G
      - WHITELIST=truted,user,list
      - OPS=trusted
      - ENABLE_RCON=true.
      - RCON_PASSWORD=difficult_password
    volumes:
      - /home/minecraft/data:/data
    container_name: mcserver
    **pid: "host"**
    ports:
      - 25565:25565
      - 25575:25575
    tty: true
    stdin_open: true

**pid: "hosts"** command makes container PID space the same as host PID space. So all things are
working. I'm not sure is it possible to check inside the container  wich PID namespace is using,
but something like this for example:

if [  "x${CREATE_PID_FILE}" != "x"  ] ; then
    echo $$ > /data/mcserver.pid
fi
And pass CREATE_PID_FILE as the environment variable. 

I didn't find a better solution. I've played a lot with Unit file for systemctl without much success.
Also, I do not want to create a separate script for Monit to check systemctl output as it moves
status of the minecraft server to different group (Programs instead of Processes).

**Comment by sergey-koshelev** [comment]
Also found in docker parameters documentation, so it is possible to share PID space when you run contaioner with docker run command:


PID settings (--pid)
--pid=""  : Set the PID (Process) Namespace mode for the container,
             'container:<name|id>': joins another container's PID namespace
             'host': use the host's PID namespace inside the container
By default, all containers have the PID namespace enabled.

PID namespace provides separation of processes. The PID Namespace removes the view of the system processes, and allows process ids to be reused including pid 1.

In certain cases you want your container to share the host’s process namespace, basically allowing processes within the container to see all of the processes on the system. For example, you could build a container with debugging tools like strace or gdb, but want to use these tools when debugging processes within the container.

**Comment by itzg** [comment]
Ah yes. I’ll just have it write the pid unconditionally since it doesn’t hurt to have the file even if nothing looks at it.
