### ISSUE TITLE
Cannot build image based on minecraft-server

### ISSUE THREAD

**Issue by fangedhex** [itzg/docker-minecraft-server#331]
Hello,

I'm currently making some scripts on my CI to autobuild my modpack with a custom launcher but the server part is not working.

When my CI server is running the FROM command in my Dockerfile
`FROM itzg/minecraft-server:latest`
I get that error : 
`Status: Downloaded newer image for itzg/minecraft-server:latest
\# Executing 3 build triggers
 ---> Running in 3827247d5f43
Removing intermediate container 3827247d5f43
COPY failed: stat /var/lib/docker/tmp/docker-builder148438726/Dockerfile: no such file or directory`

`Docker version 18.09.6, build 481bc77`

I don't know how to fix this but my other Dockerfile scripts are running without a problem.

**Comment by itzg** [comment]
@Silthus , since you added the ONBUILD support for a similar use case, do you have any ideas or recommendations?

**Comment by Silthus** [comment]
Do you have a Dockerfile in your project? And is it accessible from the build environment?

In a build trigger the image tries to copy the Dockerfile into the container: https://github.com/itzg/dockerfiles/blob/98cec98dd9228865691c520aa66478d7d040dbf0/minecraft-server/Dockerfile#L55

Can you post you build script and more details about the setup?

**Comment by fangedhex** [comment]
I've made a workaround on my git repository because I have this problem only with your image.

Here is the tree when I was trying to use your image : https://lab.sylvainviste.com/minecraft/launcher/tree/e69b9626cae97e38bf98334cdf52a77c3ee396a6

Maybe it doesn't work well with Gitlab CI and their runner ? It's the first time I see that, all my other private projects use the same CI system. If you want me to do some more testing on a dummy repository on my gitlab, I can do that if needed.

**Comment by Silthus** [comment]
The problem is that there is no explicit Dockerfile in your repo. You have
a client and a server Dockerfile but for this to you work you will need a
Dockerfile.

Or we need to change the on build trigger to fake copy all `*Dockerfile*`
files.

Sylvain VISTE <notifications@github.com> schrieb am So. 9. Juni 2019 um
10:46:

**Comment by itzg** [comment]
I like the idea of wildcard copying the `*Dockerfile*`'s during the ONBUILD. @Silthus remind me what the reason is for those with your buildtools tool...maybe that `ONBUILD RUN` needs a conditional in front of it to make sure it doesn't fail on missing `Dockerfile`.

**Comment by Silthus** [comment]
The COPY command needs at least one of the provided files or it will fail.

Since I used it in the on build step we can't make sure a plugins.yml file
exists. That's why it copies a dummy Dockerfile (which I thought always
exists :)).

Geoff Bourne <notifications@github.com> schrieb am So. 9. Juni 2019 um
16:10:

**Comment by itzg** [comment]
@fangedhex and @Silthus I pushed an update that uses the wildcard in the `ONBUILD COPY` and then conditionally invokes ToF buildtools in the `ONBUILD RUN`.

Can you see if this update works for each of you?

**Comment by itzg** [comment]
@Silthus yeah I'm now thinking it would have been more robust for you to maintain a derivative/`FROM` image that includes the ToF buildtools and `ONBUILD` steps since we apparently assumed too much with the current strategy. I'd be glad to include very obvious linkage in the README of this image to a ToF image if you want to go that route.

**Comment by itzg** [comment]
...even this change https://github.com/itzg/dockerfiles/commit/da1a3a47cd02d26669575d60dfadefcf75509236 would fail if one chose to name their dockerfiles like `prod.dfile`.

**Comment by Silthus** [comment]
It would be great if your image would be hosted on its own repository. Then I could fork it and maintain a separate image more easily.

**Comment by fangedhex** [comment]
I will try out your fix. One question : I try to understand why you need to use the "child" Dockerfile, can you explain ?

**Comment by itzg** [comment]
@Silthus agreed on the repo cleanliness; however, I'm thinking you wouldn't even need a fork, just a derivative `Dockerfile` with the ToF related parts such as:

```
FROM itzg/minecraft-server

ADD https://git.faldoria.de/tof/server/build-tools/-/jobs/artifacts/buildtools-${TOF_BUILDTOOLS_VER}/raw/target/ToF-BuildTools.jar?job=release-artifact /tmp/tof-buildtools/BuildTools.jar

ONBUILD ARG BUILDTOOLS_OUTPUT=/plugins
ONBUILD COPY *Dockerfile* *plugins.yml /tmp/tof-buildtools/
ONBUILD RUN \
  [ -d /tmp/tof-buildtools ] && \
  [ $(find /tmp/tof-buildtools -type f -name plugins.yml | wc -l) -gt 0 ] && \
  java -jar /tmp/tof-buildtools/BuildTools.jar \
    --config "/tmp/tof-buildtools/plugins.yml" \
    --configs "plugins.yml" \
    --dir "/tmp/tof-buildtools/" \
    --output ${BUILDTOOLS_OUTPUT} && \
  chown -R minecraft:minecraft ${BUILDTOOLS_OUTPUT} && \
  rm -fR /tmp/tof-buildtools/ || \
  true
```

**Comment by itzg** [comment]
@fangedhex if I remember correctly that was to ensure the `ONBUILD COPY` wouldn't fail when no `plugins.yml` file(s) were present.

**Comment by Silthus** [comment]
You can go ahead and remove the on build code if you want.

I will create a derived image like you said.

Geoff Bourne <notifications@github.com> schrieb am Mo. 10. Juni 2019 um
16:04:

**Comment by itzg** [comment]
Sorry for the delay on this @fangedhex . The latest image on Docker Hub now delegates ToF buildtools to be augmented by a derivative image.
