### ISSUE TITLE
How to automate with Git and CI/CD?

### ISSUE THREAD

**Issue by DarrylSSY** [itzg/docker-minecraft-server#343]
Hello, so I am trying to implement the following flow to my server.

1. Commit plugin configurations to a repository to the staging branch (since I have many plugins with configs, I decided to put all plugins in one repository instead of one per repository.
2. CI/CD to ensure that server does not crash with latest plugin configurations
3. If tests passes, redeploy staging server with latest plugin configuration changes.
4. Once everything is okay, I will merge the latest staging server to the master server which wil then redeploy production server with the latest changes.

How would I be able to go around doing so with this docker image?

**Comment by itzg** [comment]
I actually have a similar challenge in doing complete CI/CD of the image itself. I'd like to have my CI run a container with each `TYPE` and confirm baseline config works, but haven't yet found a way.

So...I'm now realizing I could enhance my server runner (https://github.com/itzg/mc-server-runner) to watch for a configurable output string, such as "[13:56:24] [Server thread/INFO]: Done" and auto-stop the container at that point.

**Comment by iamtpage** [comment]
1. Trigger webhook on commit to staging branch to kickoff pipeline of your choice (concourse/jenkins/drone/gitlab/etc)
2. Pipeline runs and does the following:
- Checks out staging branch at current commit
- Checks out plugin repo at latest commit
- Organize file structure as the docker container expects
- Run docker container 
- Monitor docker logs from container (can grep for `[Server thread/INFO]: Done`)
- Decide if docker container is healthy (using previous grep command or docker healthcheck)
3. Depending on results of step 2, either
- Fail the build
- Pass the build

Then you just monitor the pipeline status or integrate it with your git repository, and either fix issues that resulted of the pipeline run, or merge the branch into master.
