### ISSUE TITLE
minecraft-server - curseforge redirects in manifest.json broken

### ISSUE THREAD

**Issue by Avil** [itzg/docker-minecraft-server#347]
Just noting that https://github.com/itzg/dockerfiles/commit/df9909a8e4c499f5d6b9c0bc327a7bba6ea52a9a did not fix my use case. Tagging @lfshr in case your commit intended to fix this issue. My use case is that I use a third-party modpack hosted on Twitch/CurseForge. 

**Design Behavior**
The Docker startup scripts should parse each mod in manifest.json, download each respective mod's .jar from CurseForge to `./data/FeedTheBeast/mods/`, and then the user-provided ServerStart.sh should (presumably) load these mods as it starts Forge.

**Current Behavior**
The Docker startup script constructs a URL based on the manifest.json values that CurseForge redirects to an HTML page. The startup script assumes that this is the target .jar and saves this HTML page as a .jar. The Forge launcher is unable to open the .jar (because it is not a .jar) and skips processing it during mod loading with an error and stack trace. (The server will ultimately start fine, but obviously without any mods.)

**Research**
[start-finalSetup02Modpack](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/start-finalSetup02Modpack) uses this line of code based on the present manifest.json to attempt to download each referenced mod: `url="${CURSE_URL_BASE}/${p}/files/${f}/download"`

This yields, for example, a URL such as: `https://minecraft.curseforge.com/projects/223094/files/2482481/download`

It appears that this once led directly to a file download. However, post-Twitch CurseForge - **how helpful!** - redirects to a URL with a new category and friendly project name: `https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks` and the actual target file is: `https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks/download/2482481/file`

I found nothing in the CurseForge API documentation that allows for identifying these two new variables from a project number, nor was I able to find anything informative from packet capture on the Twitch client due to encryption (because the client must be resolving these somehow). So... perhaps following the redirect and appending the target file is all that's needed?

**Comment by iamtpage** [comment]
This can be fixed by doing the following:

Example MC mod used: `Placebo`
Placebo Curseforge Project ID: `283644`
Placebo File ID (version Placebo-1.12.2-1.6.0.jar): `2694382`

```
root@tyr:/tmp/test# PROJECT_ID="283644"
root@tyr:/tmp/test# FILE_ID="2694382"
root@tyr:/tmp/test# REDIRECT_URL=$(curl -Ls -o /dev/null -w %{url_effective} https://minecraft.curseforge.com/projects/$PROJECT_ID)
root@tyr:/tmp/test# curl -sSL "$REDIRECT_URL/download/$FILE_ID/file" -o "./$FILE_ID.jar"
root@tyr:/tmp/test# file "$FILE_ID.jar"
2694382.jar: Java archive data (JAR)
```

**Comment by iamtpage** [comment]
I'll work on a PR soon if no one else picks this up
