### ISSUE TITLE
Unable to change Memory for Minecraft server

### ISSUE THREAD

**Issue by joopjuh** [itzg/docker-minecraft-server#349]
Hi,

I'm trying to increase the Memory from 1G to 4G but it is not accepting the change.
In the log i can see that it is setting the Memory to 4G but then it fails due to an invalid initial heap size.
I'm i doing something wrong?
Thanks.

usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    8 1000     1000          4096 Jul 19 10:01 /data'
Checking version information.
Cecking type information.
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 4G and max to 4G
Invalid initial heap size: -Xms4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
2019/07/19 10:09:31 Done

**Comment by itzg** [comment]
Are you sure your system has more than 4GB of free RAM available?

**Comment by joopjuh** [comment]
I have 8gb available ram in the system and i’m not running anything special that consumes the ram. Even with 2G i get the same error.

**Comment by itzg** [comment]
Are you running Docker on a Linux system or via Docker for Desktop on Windows/Mac?

**Comment by joopjuh** [comment]
I’m running it on a Qnap running docker.

**Comment by itzg** [comment]
From further research on that error I'm finding that the error indicates Java is running in 32-bit mode; however, I'm confused since the image is built for 64-bit. I did a `docker pull itzg/minecraft-server` and confirmed for me it is running 64-bit:

```
> docker run --rm --entrypoint java itzg/minecraft-server -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

Can you try the same, noting the `--entrypoint` override? Not sure how feasible that is with Qnap.

**Comment by weep** [comment]
I'm getting the same issue but only with some versions of mod packs. All The Mods 3 Remix 1.3.0 works fine but not 1.3.4 or 1.4.0. Might be something in the server startup perhaps?
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```
```
TYPE | CURSEFORGE
CF_SERVER_MOD | https://www.curseforge.com/minecraft/modpacks/all-the-mods-3-remix/download/2749172
```

**Comment by itzg** [comment]
Ah, possibly similar to https://github.com/itzg/docker-minecraft-server/issues/357

I already have logic to build a consistent startup script for the modpacks, so I think I'll engage that logic regardless of a bundled startup script since there is not an enforced strategy for JVM settings in those.

**Comment by joopjuh** [comment]
> Can you try the same, noting the `--entrypoint` override? Not sure how feasible that is with Qnap.

Still figuring out how to execute that on QNAP. Please bare with me.
Note that the QNAP i have is running arm32
This is the CPU AnnapurnaLabs Alpine AL-314 32-bit ARM® Cortex-A15 quad-core 1.7GHz processor
Does that help in understanding the issue better?

**Comment by itzg** [comment]
@joopjuh I'm surprised the QNAP even allows for 8GB of physical RAM since usage above 2GB or 4GB gets really dicey on 32-bit systems:

https://en.wikipedia.org/wiki/2_GB_limit
https://en.wikipedia.org/wiki/RAM_limit#32-bit_x86_RAM_limit

**Comment by alexeast99** [comment]
I know I'm late to the party, but I'm new to docker and this image in particular. Can someone please tell me how to set the RAM that the docker image uses? Or any configuration files in general? Thanks! :-)

**Comment by itzg** [comment]
@alexeast99 the env var to use is `MEMORY` 

https://github.com/itzg/docker-minecraft-server#memory-limit

**Comment by alexeast99** [comment]
Thank you!
