### ISSUE TITLE
Error SSL certificate

### ISSUE THREAD

**Issue by flipkill1985** [itzg/docker-minecraft-server#353]
Hello,

i get this Error all the time what can i do?

Best Jan

usermod: no changes
--
  | Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000            22 Jul 21 23:34 /data'
  | Checking version information.
  | curl: (60) SSL certificate problem: self signed certificate in certificate chain
  | More details here: https://curl.haxx.se/docs/sslcerts.html
  |  
  | curl failed to verify the legitimacy of the server and therefore could not
  | establish a secure connection to it. To learn more about this situation and
  | how to fix it, please visit the web page mentioned above.
  | Checking type information.
  | Downloading minecraft_server..jar ...
  | curl: (60) SSL certificate problem: self signed certificate in certificate chain
  | More details here: https://curl.haxx.se/docs/sslcerts.html
  |  
  | curl failed to verify the legitimacy of the server and therefore could not
  | establish a secure connection to it. To learn more about this situation and
  | how to fix it, please visit the web page mentioned above.
  | ERROR failed to obtain version manifest URL (60)

**Comment by itzg** [comment]
Can you provide the `docker run` that you’re using? I might to have the image accept an option to download things insecurely but want to double check things.

**Comment by flipkill1985** [comment]
Hello,

it was a DNS Bug in Kubernetes i Fixed DNS now all wors fine.

best Jan
