### ISSUE TITLE
docker-compose and dns 

### ISSUE THREAD

**Issue by sljdhl** [itzg/docker-minecraft-server#355]
`version: '3'
//Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
//  ports:
//     - "25565:25565"
    expose:
      - "25565"
    volumes:
      - "/home/docker/minecraft/mc:/data"
    environment:
      EULA: "TRUE"
//   CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "testing"
      RCON_PORT: 28016
    restart: unless-stopped
    networks:
      - proxy-net
      - default
    labels:
      - "traefik.docker.network=proxy-net"
      - "traefik.enable=true"
      - "traefik.frontend.auth.basic"
      - "traefik.basic.frontend.rule=Host:minecraft.domain.com"
      - "traefik.basic.port=25565"
      - "traefik.basic.protocol=http"
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  mc:
  rcon:

networks:
  proxy-net:
    external: true`

This is my docker-compose.yaml and i can connect to it within my own network, but not with the hostname. How do I expose it and make it possible to connect to it through my domain?

**Comment by itzg** [comment]
I’m not very familiar with traefik, but what I can already tell won’t work is trying to proxy Minecraft connections as HTTP. Minecraft has its own proprietary TCP protocol. You’ll need to at least configure traefik in a simple TCP load balancing mode...or better yet, I recommend using this ingress router I implemented and use for my home kubernetes deployment:

https://github.com/itzg/mc-router

**Comment by sljdhl** [comment]
> I’m not very familiar with traefik, but what I can already tell won’t work is trying to proxy Minecraft connections as HTTP. Minecraft has its own proprietary TCP protocol. You’ll need to at least configure traefik in a simple TCP load balancing mode...or better yet, I recommend using this ingress router I implemented and use for my home kubernetes deployment:
> 
> https://github.com/itzg/mc-router

Should I integrate the mc-router within my existing minecraft container or should it be a new on its own? Do you have any docker-compose examples for it?

**Comment by itzg** [comment]
You’ll deploy it as a separate/sidecar container. Good question about a docker compose example. I’ll gather one up and include that here.

**Comment by itzg** [comment]
@sljdhl I have added a Docker Compose example to the mc-router README at

https://github.com/itzg/mc-router#docker-compose-usage
