### ISSUE TITLE
SSL error when containers try and download images from https

### ISSUE THREAD

**Issue by rwarren** [itzg/docker-minecraft-server#356]
Trying to download from https with curl/wget/whatever results in this (as an example):

```
Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
mc2     | Error loading shared library libssl.so.1.1: Exec format error (needed by /usr/lib/libcurl.so.4)
```

Not having the `paper_server.jar` file prevents the container from starting.

The exact path to me getting here was:

1. Try and update my papermc image by deleting the `paper_server.jar` file
    * This triggers the container to download a new jar file
    * I only figured this out by looking at the `start-deployPaper` script [here](https://github.com/itzg/docker-minecraft-server/blob/master/start-deployPaper) (could use some docs here, unless I'm blind?)
2. Server failed to start, and I can't event connect, with repeated errors as above

For anyone else with the same issue, I'll log my recovery efforts here...

I haven't even figured out how to fix this yet. I step into the container with:

```
docker run -it --rm --entrypoint sh <my_container_id>
```

but can't download the file (due to the same ssl error):

```
$ docker run -it --rm --entrypoint sh 7dba51cec456
/data # wget https://papermc.io/api/v1/paper/1.14.4/latest/download
Error loading shared library libssl.so.1.1: Exec format error (needed by /usr/bin/wget)
Segmentation fault (core dumped)
```

I've also tried `docker cp` to get a file I downloaded on my host into the root, but it hasn't worked for me yet (probably because of my stupidity"). I'm trying this for my `mc2` image as follows

```
docker cp paper_server.jar mc2:/paper_server.jar
```

but, though it seems to work, it doesn't put the file into the root of the container.

**Comment by rwarren** [comment]
From a recovery logging perspective I've now recovered (but the reported ssl issue still exists).

The paper_server.jar file is actually in `/data` (of course), not in the container root. Copying a file there with `docker cp` got my server up and running again. I also fixed permissions for good measure. Log below for the record of it (only one of my mc servers was broken due to the upgrade attempt):

```
$ cd /var
$ sudo find . -name paper_server.jar
./lib/docker/volumes/mc_data/_data/paper_server.jar
$ docker cp ~/paper_server.jar mc2:/data/paper_server.jar
$ sudo find . -name paper_server.jar
./lib/docker/volumes/mc_data/_data/paper_server.jar
./lib/docker/volumes/mc2_data/_data/paper_server.jar
$ sudo find . -name paper_server.jar | sudo xargs ls -al
-rw-r--r-- 1 root root    43156927 Jul 26 03:57 ./lib/docker/volumes/mc2_data/_data/paper_server.jar
-rw-rw-r-- 1 russ lpadmin 43450986 Dec 16  2018 ./lib/docker/volumes/mc_data/_data/paper_server.jar
$ sudo chown russ:lpadmin /var/lib/docker/volumes/mc2_data/_data/paper_server.jar
$ sudo chmod 664 /var/lib/docker/volumes/mc2_data/_data/paper_server.jar
```

Hopefully that helps someone else out in the same situation.

**Comment by itzg** [comment]
@rwarren I am not able to re-create the original "libssl" issue:

Ensuring latest image:
```
$ docker pull itzg/minecraft-server
Using default tag: latest
latest: Pulling from itzg/minecraft-server
Digest: sha256:409b139ab5f60b9c435dfddd59d3a82747112696a989ccebbe8abb9096a8e621
Status: Image is up to date for itzg/minecraft-server:latest
docker.io/itzg/minecraft-server:latest

and running with `TYPE=PAPER`:
```
docker run -it --rm -e EULA=TRUE -e TYPE=PAPER itzg/minecraft-server
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Jul 27 17:41 /data'
Checking version information.
Checking type information.
Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
Creating server.properties in /data/server.properties
.
.
.
```

and trying `wget` specifically
```
$ docker run -it --rm --entrypoint bash itzg/minecraft-server
bash-4.4# wget https://papermc.io/api/v1/paper/1.14.4/latest/download
--2019-07-27 16:39:11--  https://papermc.io/api/v1/paper/1.14.4/latest/download
Resolving papermc.io... 104.25.249.102, 104.25.250.102, 2606:4700:20::6819:fa66, ...
Connecting to papermc.io|104.25.249.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 43156927 (41M) [application/java-archive]
Saving to: 'download'

download                                 100%[==================================================================================>]  41.16M  12.5MB/s    in 3.8s    

2019-07-27 16:39:16 (10.7 MB/s) - 'download' saved [43156927/43156927]
```

Can you double check you have pulled the latest image referencing `itzg/minecraft-server` in your `docker run` (rather than a container ID)?

**Comment by rwarren** [comment]
Weird: I just tried creating an additional server and got the same thing.

```
$ docker pull itzg/minecraft-server
Using default tag: latest
latest: Pulling from itzg/minecraft-server
Digest: sha256:a5bcc6bf3cef4a441f64e4c33003910ed1196262fb839df77a27d69f3d9eb11a
Status: Image is up to date for itzg/minecraft-server:latest
docker.io/itzg/minecraft-server:latest
```

Trying to start that server results in repeated failures per below (I'm using docker-compose here):

```
<snip>
mc3     | usermod: no changes
mc3     | Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Dec  6 20:31 /data'
mc3     | Checking version information.
mc3     | Checking type information.
mc3     | Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
mc3     | Error loading shared library libssl.so.1.1: Exec format error (needed by /usr/lib/libcurl.so.4)
mc3     | /start-deployPaper: line 12:    17 Segmentation fault      (core dumped) curl -fsSL -o $SERVER "$downloadUrl"
mc3     | ERROR: failed to download from https://papermc.io/api/v1/paper/1.14.4/latest/download (status=0)
mc3     | usermod: no changes
mc3     | Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Dec  6 20:31 /data'
mc3     | Checking version information.
mc3     | Checking type information.
mc3     | Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
mc3     | Error loading shared library libssl.so.1.1: Exec format error (needed by /usr/lib/libcurl.so.4)
mc3     | /start-deployPaper: line 12:    17 Segmentation fault      (core dumped) curl -fsSL -o $SERVER "$downloadUrl"
mc3     | ERROR: failed to download from https://papermc.io/api/v1/paper/1.14.4/latest/download (status=0)
mc3     | usermod: no changes
mc3     | Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Dec  6 20:31 /data'
mc3     | Checking version information.
mc3     | Checking type information.
mc3     | Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
mc3     | Error loading shared library libssl.so.1.1: Exec format error (needed by /usr/lib/libcurl.so.4)
mc3     | /start-deployPaper: line 12:    17 Segmentation fault      (core dumped) curl -fsSL -o $SERVER "$downloadUrl"
mc3     | ERROR: failed to download from https://papermc.io/api/v1/paper/1.14.4/latest/download (status=0)
<snip>
```

I ended up using my own pre-determined recovery process up above to copy the paper_server and got it working. Phew! :)

**Comment by itzg** [comment]
It seems like such a strange way for it to fail. The main benefit of containers is that they run identical everywhere...but yours isn’t. What host platform are you using for running Docker? I’m wondering if it’s a kernel difference contributing to the segfault.

**Comment by rwarren** [comment]
Time for another upgrade, and hit the problems again.  Sorry I missed your question earlier.

I'm using docker-compose with this (I just changed `VERSION` from 1.14.4 to 1.15.2):

```
  mc3:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.15.2"
      MEMORY: 2G
      SEED: -84392960
    volumes:
      - mc3_data:/data
      - mc3_plugins:/plugins
    container_name: mc3
    tty: true
    stdin_open: true
    restart: always
    #command: "--noconsole"
    command: "/bin/bash"
```

Then I deleted `/data/paper_server.jar`, hoping for a clean upgrade.  It is now in a perpetual reboot cycle:

```
mc3     | usermod: no changes
mc3     | Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx   10 1000     1000          4096 Mar  8 16:16 /data'
mc3     | Checking version information.
mc3     | Checking type information.
mc3     | Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
mc3     | Error loading shared library libssl.so.1.1: Exec format error (needed by /usr/lib/libcurl.so.4)
mc3     | /start-deployPaper: line 12:    22 Segmentation fault      (core dumped) curl -fsSL -o $SERVER "$downloadUrl"
mc3     | ERROR: failed to download from https://papermc.io/api/v1/paper/1.14.4/latest/download (status=0)
mc3     | usermod: no changes
mc3     | Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx   10 1000     1000          4096 Mar  8 16:17 /data'
mc3     | Checking version information.
mc3     | Checking type information.
mc3     | Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
mc3     | Error loading shared library libssl.so.1.1: Exec format error (needed by /usr/lib/libcurl.so.4)
mc3     | /start-deployPaper: line 12:    18 Segmentation fault      (core dumped) curl -fsSL -o $SERVER "$downloadUrl"
mc3     | ERROR: failed to download from https://papermc.io/api/v1/paper/1.14.4/latest/download (status=0)
mc3     | usermod: no changes
mc3     | Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx   10 1000     1000          4096 Mar  8 16:17 /data'
mc3     | Checking version information.
mc3     | Checking type information.
mc3     | Downloading Paper 1.14.4 from https://papermc.io/api/v1/paper/1.14.4/latest/download ...
mc3     | Error loading shared library libssl.so.1.1: Exec format error (needed by /usr/lib/libcurl.so.4)
mc3     | /start-deployPaper: line 12:    18 Segmentation fault      (core dumped) curl -fsSL -o $SERVER "$downloadUrl"
mc3     | ERROR: failed to download from https://papermc.io/api/v1/paper/1.14.4/latest/download (status=0)
```

Aside from the `libssl` issue, almost more curious is that the version is still on 1.14.4 for some reason I don't understand.   It is definitely the correct container, so I'm not sure where that version is getting picked up from.  Is it cached in the container somewhere?

**Comment by itzg** [comment]
I am still unable to recreate the various issues you are seeing. I should have clarified that I was curious about the CPU architecture of your docker host? "Exec format error" can sometimes indicate the container is running on ARM or 32-bit x86 instead of the expected 64-bit x86. 

Please provide the output of `docker version` to answer that. For comparison my `docker version` provided https://gist.github.com/itzg/8541af75ca9fb4b68d8bef14d726c390#gistcomment-3204900

Then, let's make sure you are running the latest/correct image. Please do a `docker-compose pull` or `docker pull itzg/minecraft-server`, then provide the output of:

```
docker image inspect -f '{{.Id}}'  itzg/minecraft-server
```

At this point, try again to see if pulling that image helped. FYI the image sha right now is `sha256:b0da038f46a0c815220511d162a3d957ed1ccf332d20ac1e26ec962866de07fe`.

For comparison, here is the compose file I used for testing (derived from yours):

https://gist.github.com/itzg/8541af75ca9fb4b68d8bef14d726c390#file-docker-compose-yml

and the output I got is:

https://gist.github.com/itzg/8541af75ca9fb4b68d8bef14d726c390#gistcomment-3204898
