### ISSUE TITLE
JVM heap larger than specified in MAX_MEMORY

### ISSUE THREAD

**Issue by DJDANNY123** [itzg/docker-minecraft-server#357]
```
`Checking version information.
Checking type information.
Looking for Feed-The-Beast / CurseForge server modpack.
detected FTB, changing properties path to /data/FeedTheBeast/LITV-Serverpack-1.12/server.properties
server.properties already created, skipping
Checking for JSON files.
Copying any mods over...
Setting initial memory to 1G and max to 2G
Running FTB /data/FeedTheBeast/LITV-Serverpack-1.12/LaunchServer.sh in /data/FeedTheBeast/LITV-Serverpack-1.12 ...
Invalid maximum heap size: -Xmx4G
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.` 
```

Above is my docker logs, running itzg/minecraft-server:multiarch with -e MAX_MEMORY=2G.

This appears to be valid through the line: Setting initial memory to 1G and max to 2G
However it then shows it is setting the max heap size to  -Xmx4G

**Comment by itzg** [comment]
I'll have to investigate that specific modpack. Unfortunately there's no standard to the launch scripts, so they are free to do their own memory setting arguments. This might be my final motivation to skip the use of the bundled launch scripts entirely...

**Comment by itzg** [comment]
I was going back through old issues and thought I would mention that I implemented the feature I mentioned above. Adding `-e USE_MODPACK_START_SCRIPT=false` will have the advantage that the container `MEMORY` setting will directly get used.
