### ISSUE TITLE
Server using SWAP memory while there is enough host memory available

### ISSUE THREAD

**Issue by grasmanek94** [itzg/docker-minecraft-server#376]
Command:
```
docker pull itzg/minecraft-server
docker stop mc
docker rm mc
docker run -d -it --restart always \
    -e EULA=TRUE -e VERSION=1.14 \
    -e MAX_MEMORY=32G -e MAX_RAM=32G \
    -e MIN_MEMORY=8G -e MIN_RAM=8G \
    -e PERMGEN_SIZE=4G -p 25565:25565 \
    -v /home/minecraft/data:/data \
    --name mc \
    itzg/minecraft-server
```

`free --giga -h` output:
```
              total        used        free      shared  buff/cache   available
Mem:           515G         10G        1.9G         28M        503G        502G
Swap:          5.8G        5.4G        401M
```

` smem -s swap -t -n -k` output:
```
  PID User     Command                         Swap      USS      PSS      RSS
(...)
36671 1000     mc-server-runner --stop-dur     3.4M   920.0K   920.0K   924.0K
36074 0        /usr/bin/docker-proxy -prot     4.4M   212.0K   422.0K     2.1M
36088 0        /usr/bin/docker-proxy -prot    10.3M   212.0K   422.0K     2.1M
36461 0        /usr/local/libexec/ipsec/pl    12.6M     8.9M     9.2M     9.7M
 1238 0        /usr/bin/dockerd -H fd:// -    13.7M    65.4M    65.5M    68.3M
 1225 0        /usr/bin/containerd            20.0M    54.9M    54.9M    56.6M
36776 1000     java -XX:+UseG1GC -Xms1G -X     5.0G     8.4G     8.4G     8.4G
-------------------------------------------------------------------------------
  131 11                                       5.1G     9.2G     9.3G     9.9G
```

The minecraft server is allowed to use 32GB of memory. It uses 9.2GB of memory and 5.1GB of swap. Total: 14.3GB. Consuming 99% of host SWAP memory when there's 502GB of RAM available is not acceptable. SWAP is meant only for writing to memory mapped files (doesn't require much space) and recovery actions/purposes on servers with plenty of RAM (when a process goes 'rogue' and leaks memory like a madman). Other docker containers don't exhibit this issue.

This issue has been described (KB000736) by docker and should be fixed with the mentioned steps:

https://success.docker.com/article/node-using-swap-memory-instead-of-host-memory

If this is intended/desired behavior I would like to request help with preventing the use of SWAP by the minecraft docker container(s): Are there parameters to disable this behavior?

**Comment by itzg** [comment]
The article you provided is exactly what I was going to suggest, but those are **host** settings. Since your host has a whole lot of RAM, I would suggest disabling swap as described in that article regardless of the issues you're seeing with Docker.

Until you asked about this, I didn't think that was tune-able per container; however, I did find this documentation that might help

https://docs.docker.com/config/containers/#limit-a-containers-access-to-memory

The host-level `sysctl` settings will likely fix your issue; however, I am curious if the settings in the docs there help on their own. Can you let me know since I don't have a way to sufficiently exercise the scenario?

**Comment by grasmanek94** [comment]
My fault, sorry! I thought that `node` in that context meant the docker container. I did read up on docker language use and realized they indeed talk about the host OS. I'll try applying these settings then. We don't have cgroup support enabled so won't be able to test per-container restraints. If docker will keep using up swap space like a madman that might be the last resort :)

**Comment by grasmanek94** [comment]
Following the instructions didn't really fix the issue, only delay it. I chose to completely disable swap.
