### ISSUE TITLE
Wiki on Docker Hub not up to date

### ISSUE THREAD

**Issue by docquantum** [itzg/docker-minecraft-server#380]
Wiki on Docker Hub is not up to date. It needs to be updated with the one from this repo.

**Comment by itzg** [comment]
Thanks for pointing this out. I have been (incorrectly) assuming that the Docker Hub builds were bringing over the README on each build; however, I suspect it it truncating the latest README. I might need to add a "See more docs" link at the very top...

**Comment by itzg** [comment]
...yep, it's being truncated. I have added a banner-link to direct users over to the full README:

![image](https://user-images.githubusercontent.com/988985/63640024-e1dc9300-c660-11e9-8cfa-5b5ba4120ef9.png)
