### ISSUE TITLE
Unable to execute

### ISSUE THREAD

**Issue by Neevok** [itzg/docker-minecraft-server#383]
Hi,

I have a Raspbian GNU/Linux 10 (buster) running on my Raspberry Pi 4 with 4 GB RAM.
It runs Docker version 19.03.1, build 74b1e89

Executing "sudo docker run -d -it -e EULA=TRUE -p 25565:25565 -v /mnt/minecraft:/data --name mc itzg/minecraft-server" pulls the most recent version. All fine.
Mountpoint has been created before.
Trying to start it doesn't seem to work. "sudo docker logs mc" unveils a "standard_init_linux.go:211: exec user process caused "exec format error""

What can I do? I'm not that much experienced with docker etc at all.
Any help is appreciated.

**Comment by itzg** [comment]
Unfortunately I don't yet have a solution in place for non-amd64 builds of the image. Docker Hub supports multi-architecture base images, but I haven't yet figured out how to setup this image's Hub build to leverage those.

Stay turned since I would really like to solve this given that Raspberry Pi 4 and arm64 systems are now better suited for running the Minecraft server.

**Comment by itzg** [comment]
...clicked too soon. In the meantime, you could try cloning this repo onto your RaspberryPi and performing a docker build, such as:

```
docker build -t mc-rpi4 .
```

Then replace `itzg/minecraft-server` with `mc-rpi4` and it should actually work.

**Comment by Neevok** [comment]
Stupid me, but will this also work with the bedrock version?
Regards, Peter

**Comment by Neevok** [comment]
Okay, tried it with bedrock, and that failed building the docker image following the scheme above

**Comment by itzg** [comment]
Glad to hear the build approach worked. Unfortunately bedrock won’t work since they don’t use java but rather prebuild a native (x86) binary.

**Comment by KonradLinkowski** [comment]
@itzg  I tried running `docker build -t mc-rpi4 --build-arg ARCH=armv7 .` it and I got
```
Step 14/32 : RUN easy-add --var os=${TARGETOS} --var arch=${TARGETARCH}${TARGETVARIANT}   --var version=1.2.0 --var app=restify --file {{.app}}   --from https://github.com/itzg/{{.app}}/releases/download/{{.version}}/{{.app}}_{{.version}}_{{.os}}_{{.arch}}.tar.gz
 ---> Running in fe9ebf1c9bcc
/usr/bin/easy-add: line 1: syntax error: unexpected "("
The command '/bin/sh -c easy-add --var os=${TARGETOS} --var arch=${TARGETARCH}${TARGETVARIANT}   --var version=1.2.0 --var app=restify --file {{.app}}   --from https://github.com/itzg/{{.app}}/releases/download/{{.version}}/{{.app}}_{{.version}}_{{.os}}_{{.arch}}.tar.gz' returned a non-zero code: 2
```

**Comment by itzg** [comment]
@KonradLinkowski this issue has been closed. Why are you building the image when I already provide a multiarch tagged image for armv7 support?

**Comment by KonradLinkowski** [comment]
I'm getting `standard_init_linux.go:211: exec user process caused "exec format error"`  in docker logs when trying to run `docker run -d -p 25565:25565 --name mc -e EULA=TRUE itzg/minecraft-server` so I thought that this is the answer

**Comment by itzg** [comment]
No problem at all and glad that image works for you. Building non-x86 architectures is surprisingly hard, so have had to setup a specific branch and build setup for it.
