### ISSUE TITLE
Increase RAM used by vanilla minecraft server?

### ISSUE THREAD

**Issue by danydacosta** [itzg/docker-minecraft-server#384]
Hey!

First, wonderful work on that image, thank you. Second, I have read the doc and I'm unable to find how to customize the amount of RAM used by the server. I can see by default it uses 1GB, how to increase to 2GB? Also, is it possible to change that setting without having to re-run the container?

Thank you in advance,

Dany

**Comment by itzg** [comment]
Thanks!

Unfortunately the documentation limit on Docker Hub chops off the section you needed. The full README has this section which should help:

https://github.com/itzg/docker-minecraft-server#memory-limit

Unfortunately you will need to restart the container for the java process to get re-invoked with the increased memory limit; however, any attached volume will persist just fine across the container restart.

**Comment by chr0n0phage** [comment]
I realize this is closed and old but i'm having real trouble with getting this to work.

I'm trying to run this server with the following: 

`sudo docker run -d -p 25565:25565 MEMORY=6G --name mc3 -e MEMORY=6G EULA=TRUE itzg/minecraft-server`

However I just receive this:

`docker: invalid reference format: repository name must be lowercase.`

I'm not sure what i'm doing wrong. If I remove the MEMORY variable I can run the image just fine.
