### ISSUE TITLE
Friend can't connect to my server and I can't connect to his

### ISSUE THREAD

**Issue by Woolooloo** [itzg/docker-minecraft-server#385]
My friend told me he set a server up using this code and got it to work with him in the game, but when he sent me the IP with the port I was unable to connect. So I tried setting it up and got it to work as well with my own server, then he tried connecting to me and it wouldn't work. Is this an issue with us being too far apart or what (I'm in NY and they're in VA).

**Comment by itzg** [comment]
On the router connected to your internet provider, have you setup port forwarding of TCP 25565? If not, you’ll need forward that to the local IP address of the computer where you’re running Docker.

**Comment by Woolooloo** [comment]
That worked, thanks
