### ISSUE TITLE
Paper Server: Permission Denied while replacing config variables.

### ISSUE THREAD

**Issue by AtzManuel** [itzg/docker-minecraft-server#391]
Replacing env variables in configs that match the prefix SMGR...
Replacing SMGR_SERVERNAME with staylords ...
sed: can't create temp file '/data/plugins/Hub/config.ymlXXXXXX': Permission den                                                                                                                                                             ied
sed: can't create temp file '/data/plugins/Citizens/config.ymlXXXXXX': Permissio                                                                                                                                                             n denied
sed: can't create temp file '/data/plugins/Citizens/lang/messages_en.propertiesX                                                                                                                                                             XXXXX': Permission denied
sed: can't create temp file '/data/plugins/Citizens/saves.ymlXXXXXX': Permission                                                                                                                                                              denied
sed: can't create temp file '/data/plugins/bStats/config.ymlXXXXXX': Permission                                                                                                                                                              denied
sed: can't create temp file '/data/plugins/Framework/config.ymlXXXXXX': Permissi                                                                                                                                                             on denied
sed: can't create temp file '/data/plugins/Framework/lang.ymlXXXXXX': Permission                                                                                                                                                              denied

I don't understand how to solve this issue.

**Comment by itzg** [comment]
It sounds like the directory ownership of those subdirectories of `/data/plugins` differs from the user running within the container? Can you provide the "Running as" log line that appears at the very start of the container startup? Also, if you are mounting the `/data` volume from a host directory, please double check if those particular directories differ in ownership with `ls -l` vs the top level host directory attached.

**Comment by AtzManuel** [comment]
The uID is 1000 and also the g something(gid if I'm not wrong).
I'm mounting the /data volume. I'll double check ownerships

**Comment by AtzManuel** [comment]
Fixed the plugins folder and subfolders were owned by root. Fixed with chmod 1000:1000 plugins/*
(1000 is the user ID and 1000 is group ID).
Thanks for the help. Keep the project up!

**Comment by AtzManuel** [comment]
The problem now is that I need to be replaced on every new container. Not just the first time. Is there a way?

**Comment by itzg** [comment]
Glad to hear you got it resolved. I'm not sure how it initially got in that state, but It should remain fixed going forward since your container is running as uid=1000 and it'll leave the files owned as is.

**Comment by AtzManuel** [comment]
Yes I mean it doesn't change the config file inside the container. It change it in the host directory
