### ISSUE TITLE
My friend cannot connect to my Galacticraft server

### ISSUE THREAD

**Issue by Elensky3** [itzg/docker-minecraft-server#393]
In walked him through everything exactly as i did it, here's the error

29.09 20:32:08 [Disconnect] User [minecraft/NetHandlerPlayServer]: MattMosley has disconnected, reason: Server Mod rejections:
29.09 20:32:08 [Server] INFO BlankPlanet: Requires version 1.12.2-0.3 but mod is not found on client.
29.09 20:32:08 [Server] INFO Extra Planets: Requires version 1.12.2-0.5.8 but mod is not found on client.
29.09 20:32:08 [Server] INFO Galacticraft Core: Requires version 4.0.2.237 but mod is not found on client.
29.09 20:32:08 [Server] INFO Galacticraft Planets: Requires version 4.0.2.237 but mod is not found on client.
29.09 20:32:08 [Server] INFO MJRLegendsLib: Requires version 1.12.2-1.1.9 but mod is not found on client.
29.09 20:32:08 [Server] INFO More Planets: Requires version 2.0.21 but mod is not found on client.
29.09 20:32:08 [Server] INFO MorePlanetsExtras: Requires version 1.12.2-1.0 but mod is not found on client.
29.09 20:32:08 [Server] INFO The One Probe: Requires version 1.4.28 but mod is not found on client.

**Comment by itzg** [comment]
From the `disconnected, reason: Server Mod rejections` and `but mod is not found on client` messages It sounds like he isn't hasn't installed the mods in the client or isn't running the client profile where the mods were installed. 

Unless he is already doing it this way, I definitely recommend using Technic Launcher or Twitch's CurseForge launcher to simplify the client-side installation.

**Comment by Elensky3** [comment]
Thank you, i'm having him try it now. I'm new to running a server and modding in general so any feedback helps!

**Comment by thomasdpage** [comment]
Hi, I'm new to building Minecraft servers (my son _really_ wants me to build him one so he can use mods) and this sounds similar to an issue I'm having.  

The container with Forge option deploys fine (I'm running Docker on an EC2 instance in AWS) but when I log in I can't see anything related to Forge in the GUI - do I need to anything on the client side for Forge to work?

**Comment by itzg** [comment]
@thomasdpage, it's kinda awkward, but forge mods need to be installed on both the server and client. The good news is that the same mod files that you would have installed on the server side can be simply placed into the `mods` as described in articles like this https://www.instructables.com/id/How-to-Install-Mods-for-Minecraft-Forge/

The other direction to solve this, which I just recently discovered, is creating a custom profile/pack in the Twitch 

https://stickypiston.co/account/knowledgebase/123/Creating-a-Custom-Mod-Pack-on-the-Twitch-Launcher.html

I haven't documented it yet, but there's a `GENERIC_PACK` environment variable that can reference the URL or path to a zip file that will get applied to the `/data` of the minecraft server container. I'll work on documenting that variable and also test out this theory with the Twitch custom modpacks.

**Comment by itzg** [comment]
...well, the exported profile from Twitch doesn't actually contain the mod files, but I did find another menu item that reveals the client-side configured directory which does. This option

![image](https://user-images.githubusercontent.com/988985/68538388-02032080-0339-11ea-9940-0969e26f6671.png)

reveals a usual `mods` directory

![image](https://user-images.githubusercontent.com/988985/68538394-1d6e2b80-0339-11ea-9e27-d9fc82bc9429.png)

**Comment by thomasdpage** [comment]
Great - thanks.  I'll give this a try.
