### ISSUE TITLE
Change Server motd and image

### ISSUE THREAD

**Issue by MrPresidentWhite** [itzg/docker-minecraft-server#396]
Like the title say: 

How can i change the motd message of the minecraft server and how can i change the server logo?

**Comment by itzg** [comment]
You can configure the MOTD on first-startup using the config in

https://github.com/itzg/docker-minecraft-server#message-of-the-day

however, changing it later requires manually modifying `server.properties` (until I enhance that process)

You can have it download and convert a server icon using the config in

https://github.com/itzg/docker-minecraft-server#server-icon

however, if there is already a `server-icon.png` file in the data directory it will skip that process. To change it later, you could manually place the new file there or delete the existing one and let the next container startup re-process it.

**Comment by MrPresidentWhite** [comment]
Thank you.
