### ISSUE TITLE
Server verification issue

### ISSUE THREAD

**Issue by Navino16** [itzg/docker-minecraft-server#406]
Hello,

I experiment some issue with creating a curseforge server.
`minecraft3       | usermod: no changes
minecraft3       | Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    3 1000     1000          4096 Oct 26 16:39 /data'
minecraft3       | Checking version information.
minecraft3       | Checking type information.
minecraft3       | Looking for Feed-The-Beast / CurseForge server modpack.
minecraft3       | Unpacking FTB server modpack /data/Sky-of-Diamonds-1.6.0-Server.zip ...
minecraft3       | ..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
minecraft3       | Please make sure you are using the server version of the FTB modpack!`

The merge request #241 seem to cause issue when server pack  doesn't contain "ServerStart.sh" file.

The file contained in Sky-of-diamonds mod pack is named "StartServer.sh"

So if you can do anything for this it will be awesome (having a less strict check for example) !

Thanks.

**Comment by itzg** [comment]
Ideally the maintainers of the Sky of Diamonds pack would rename that start script to `ServerStart.sh`; however, it's not technically a bug since there's no enforced rules about CurseForge modpacks...unfortunately for scripts like this container's. If it helps, when reporting that, point them to https://github.com/AllTheMods/Server-Scripts where the "standard" entry script is named `ServerStart.sh`.

Let me know if they push back on that issue and I can look into making the script searching logic allow for either name and/or a configurable override.

**Comment by Navino16** [comment]
For reference : https://www.curseforge.com/minecraft/modpacks/awakening/issues/1011

**Comment by nrgbistro** [comment]
I also had this issue with ATM3R. I'm not familiar with how this container actually performs the startup, but couldn't this be avoided by checking for both `ServerStart.sh` and `StartServer.sh` (as well as all lowercase versions)?

**Comment by itzg** [comment]
I have finally added an option to avoid the use of the start scripts provided by modpacks and tested with ATM3 specifically

https://github.com/itzg/docker-minecraft-server#buggy-start-scripts

**Comment by nrgbistro** [comment]
Sounds good. Just to confirm, does that mean the new default is to use the modpack's startup script?

**Comment by itzg** [comment]
Yes, the new default basically retains the old behavior of using the modpack's startup script.

**Comment by nrgbistro** [comment]
Awesome thanks for the fix!
