### ISSUE TITLE
Unable to update mod pack

### ISSUE THREAD

**Issue by haudankaivajasi** [itzg/docker-minecraft-server#407]
Hi,
I came across a problem regarding updating my mod files. I followed the instructions given:  stopped 
the docker, removed it and tried to create it again with the command:

    docker run -d -v /share/CACHEDEV1_DATA/Container/container_files/Minecraft:/data \
    -e TYPE=FTB \
    -e FTB_SERVER_MOD=https://www.feed-the-beast.com/projects/ftb-revelation/files/2778975 \
    -e MEMORY=4G \
    -p 25565:25565 \
    -e EULA=TRUE \
    --restart=always \
    --name mc \
    itzg/minecraft-server

The mod link is for the newest version. For some reason it won't download the file. I also tried to download the file and place the file in `/data` and also replaced the mod line in the command to 
`-e FTB_SERVER_MOD=FTBRevelationServer_3.2.0.zip \` but still it wouldn't install the newest version. Also `-e FORCE_REDOWNLOAD=true` didn't do anything for me.

I updated the docker image but it had no effect to this.
Am I doing something completely wrong or why isn't my mods updating?

**Comment by wlp7s0** [comment]
Hello,
According to startup script - re-download will occur only if there is no hidden file with the name.
I think you need to remove all files with dot in the beginning in '/share/CACHEDEV1_DATA/Container/container_files/Minecraft' directory before docker run.

**Comment by haudankaivajasi** [comment]
I just checked the situation and there does not seem to be any hidden files in that location.

**Comment by wlp7s0** [comment]
Oh, my bad. FTB uses different logic.
[Here](https://github.com/itzg/docker-minecraft-server/blob/master/start-deployFTB) is the startup script.
You need to 
`mv /share/CACHEDEV1_DATA/Container/container_files/Minecraft/FeedTheBeast/ServerStart.sh /tmp/ || 
mv /share/CACHEDEV1_DATA/Container/container_files/Minecraft/FeedTheBeast/ServerStartLinux.sh /tmp/ || 
mv /share/CACHEDEV1_DATA/Container/container_files/Minecraft/FeedTheBeast/LaunchServer.sh /tmp/ `
and restart docker.

Script looks for those files in /data/FeedTheBeast directory. If one of them is found - no need to re-download. If none of them are present - it uses provided url to download.

**Comment by haudankaivajasi** [comment]
Ok, I did what you said but for some reason it didn't download the whole file so I downloaded it manually and renamed accordingly. Now it finds it and extracts the contents like it should but in the process of starting the server, it crashes and it seems to now always unpack the stuff, try to start and crash when ever I try to start the server

**Comment by haudankaivajasi** [comment]
Ok, I resolved the updating by stopping the server, deleting the container, deleting everything except 
`backups`, `world`, `server.properties`, `whitelist.json` in Minecraft-folder, downloaded the newest mod-pack manually, put it in the right location and ran:

    docker run -d -v /share/CACHEDEV1_DATA/Container/container_files/Minecraft:/data \
    -e TYPE=FTB \
    -e FTB_SERVER_MOD=FTBRevelationServer_3.2.0.zip \
    -e MEMORY=4G \
    -p 25565:25565 \
    -e EULA=TRUE \
    --restart=always \
    --name mc \
    itzg/minecraft-server

Now it seems to be running ok. Thanks for the help though! And strange that the method in the readme didn't work :o
