### ISSUE TITLE
Install of CurseForge modpack silently terminates

### ISSUE THREAD

**Issue by hannah98** [itzg/docker-minecraft-server#413]
> I didn't find any obvious exit points that would cause the quiet container termination, so I thought I would try recreating your scenario. Can you provide the `manifest.json` that you're using?

_Originally posted by @itzg in https://github.com/itzg/docker-minecraft-server/issues/404#issuecomment-545915612_

---

@obsessionwithfire do you mind opening a new issue? Yours is definitely in the general realm of FTB/CurseForge challenges, but seems to be different since the startup logic is quietly failing at the point:

```
Looking for Feed-The-Beast / CurseForge server modpack.
```

I probably have some missing error checking around there.

_Originally posted by @itzg in https://github.com/itzg/docker-minecraft-server/issues/392#issuecomment-545444716_

---

I have done some debugging and [this is the line](https://github.com/itzg/docker-minecraft-server/blob/581d5fde1d504b99d84be8612f1e11a501f19fe2/start-finalSetup02Modpack#L81) where it is silently failing:

```
curl -Ls -o /dev/null -w %{url_effective} $MANIFEST
```

My MANIFEST variable is equal to ```/data/FeedTheBeast/manifest.json``` but when I run that curl command inside your image/container, it exits with an error code 3.

To reproduce, run this command at the shell inside your container:
```
curl -Ls -o /dev/null -w %{url_effective} /data/FeedTheBeast/manifest.json
echo $?
```

My output is:

```
/data/FeedTheBeast/manifest.json
3
```

And it is failing at that point because ```set -e``` [is turned on](https://github.com/itzg/docker-minecraft-server/blob/581d5fde1d504b99d84be8612f1e11a501f19fe2/start-finalSetup02Modpack#L3) in the script.

I thought about submitting a pull request to fix but I wasn't sure how you would want to handle it.  I've seen you reference this in a couple of other tickets (listed above) so I thought I'd submit an issue with the research.

**Comment by itzg** [comment]
Great research @hannah98 . A PR would be fantastic. As you might have seen, there's logic nearby that makes use of the `isURL` utility function and I could see a solution using that to conditionally skip the downloading of the manifest.json.
