### ISSUE TITLE
installing forge didn't go proxy

### ISSUE THREAD

**Issue by Diluka** [itzg/docker-minecraft-server#415]
I set `PROXY` env which I have tested working. But it not using proxy to download forge libs.

**Comment by wlp7s0** [comment]
Can you provide more data? As I understand from your description: you have no issue installing and building docker image using proxy. But after you start the image, forge tries to download and install libs and in this case it doesn't use proxy.

**Comment by itzg** [comment]
@Diluka ah, apparently the environment variables should be `HTTPS_PROXY` and `HTTP_PROXY`. I'll update [the README section](https://github.com/itzg/docker-minecraft-server#http-proxy) to fix that.

**Comment by itzg** [comment]
I need to revisit this since I now see there's code that is supposed to set those variables

https://github.com/itzg/docker-minecraft-server/blob/1c9bbee3b3096ae8ce954ba9f3eb569d6e8e37e6/start-configuration#L38-L43

however, I am now wondering if the code needs to set the uppercase versions of those variables also.

**Comment by itzg** [comment]
...also re-reading your description I realized you said "download forge libs". It sounds like then the startup script parts that use `curl` are correctly using the proxy setting, but the forge installer itself is not. You probably need to report an issue against forge.

**Comment by wlp7s0** [comment]
This code works fine. But it works only upon docker build. After the image is build - executing run command without http_proxy environment variable will not trigger the container to use proxy.

**Comment by itzg** [comment]
@wlp7s0 , correct at `docker run` one must set the `PROXY` appropriately at which point the startup script will set `http_proxy` and `https_proxy` with that value. The proxy setting is not involved during build time and that happens on Docker Hub in the case of this image.

**Comment by wlp7s0** [comment]
I'm not sure I did understand your comment. 
I think that the author of the issue uses PROXY variable while building the image and it works, but he omits this environment variable upon docker run. 
At least that is how I understand this.

**Comment by itzg** [comment]
OK, let's wait for @Diluka to clarify. It is rare that people need to build this image since I already provide it on Docker Hub.

**Comment by Diluka** [comment]
sorry about the slow response

it's nothing about the image building

set PROXY is working for curl but not forge installer

EL PYS CONGROO

________________________________
发件人: Geoff Bourne <notifications@github.com>
发送时间: 星期二, 十一月 26, 2019 11:01 下午
收件人: itzg/docker-minecraft-server
抄送: Diluka; Mention
主题: Re: [itzg/docker-minecraft-server] installing forge didn't go proxy (#415)


OK, let's wait for @Diluka<https://github.com/Diluka> to clarify. It is rare that people need to build this image since I already provide it on Docker Hub.

―

**Comment by itzg** [comment]
Cleaning up some old issues...if you're still experiencing this then I suggest reporting an issue with Forge since all the known proxy environment variables are getting configured.

**Comment by Diluka** [comment]
https://github.com/itzg/docker-minecraft-server/blob/master/start-deployForge#L87

see https://stackoverflow.com/questions/120797/how-do-i-set-the-proxy-to-be-used-by-the-jvm

java should set proxy in command @itzg

**Comment by itzg** [comment]
Thanks @Diluka for finding that.
