### ISSUE TITLE
ERROR failed to obtain version manifest URL (6)  

### ISSUE THREAD

**Issue by Pw4r0w** [itzg/docker-minecraft-server#416]
Hello

I'm quiet a noob with docker, but I try to create a docker on my qnap with container and I have an issue after the creation of it :
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Nov 26 12:38 /data'                                              
Checking version information.                                                                                                                            
curl: (6) Could not resolve host: launchermeta.mojang.com                                                                                                
Checking type information.                                                                                                                               
Downloading minecraft_server..jar ...                                                                                                                    
curl: (6) Could not resolve host: launchermeta.mojang.com                                                                                                
ERROR failed to obtain version manifest URL (6)           

I don't know what to do, even when try to manually add a manually minecraft jar it does not work. 
I've already had a minecraft server running on Docker and it worked but now it doesn't work anymore.

**Comment by itzg** [comment]
It sounds like a Docker-DNS configuration issue on the qnap, but without any experience with that environment I can't offer any suggestions.

**Comment by Pw4r0w** [comment]
I've already thought about the DNS issues, but obviously, I've been able to create other dockers (KSP for example, downloaded, updated & now running fine) I also have a ARK Docker server running and it works perfectly

**Comment by itzg** [comment]
To help troubleshoot, can you deploy a container with the image `curlimages/curl` and the command line `https://launchermeta.mojang.com/mc/game/version_manifest.json`? That should exercise the equivalent logic but take the minecraft-server image out of the picture.

**Comment by wlp7s0** [comment]
That is strange. By default docker uses /etc/resolv.conf file of the host OS. As described [here](https://docs.docker.com/v17.09/engine/userguide/networking/default_network/configure-dns/). This page contains an example how to rewrite docker's DNS. You can try to start build process with this flag and force it to use specific DNS.

Anyhow, it looks like this is not an issue of this repository.

**Comment by Pw4r0w** [comment]
@itzg  ![image](https://user-images.githubusercontent.com/5208263/69650974-ac847e80-106f-11ea-9292-2080f83793c2.png)
This is what I get when I try to create a container with curlimages/curl and the requested command line. I could copy paste the whole console result but it's kind of huge.

**Comment by itzg** [comment]
Thanks @Pw4r0w , that helped to narrow things down. I'm wondering if this nsswitch.conf configuration is interfering in your particular environment

https://github.com/itzg/docker-minecraft-server/blob/master/Dockerfile#L32

Removing that setting isn't ideal either since it caused `localhost` not to resolve on some people's systems. As a compromise, I can make that be a `docker run` option and at least see if disabling that works for your environment.

**Comment by itzg** [comment]
@Pw4r0w this is a stab in the dark, but the latest image pushed to Docker Hub now includes the ability to set `SKIP_NSSWITCH_CONF=TRUE` to disable the creation of `/etc/nsswitch.conf`. Can you give that option a try when you get a chance and see if that helps?

**Comment by Pw4r0w** [comment]
OK, I think I put the finger on something.

I tried to create the minecraft server again with my custom settings that have worked before on all my dockers. Same issue. So I tried it again with full default config even network default. And then it worked. I think that when I tried to launch the server on a bridged interface it does not work.
![image](https://user-images.githubusercontent.com/5208263/69699922-784da400-10e9-11ea-8db8-f11f83985f23.png)

But when it's on NAT > working fine. 
![image](https://user-images.githubusercontent.com/5208263/69700215-31ac7980-10ea-11ea-9103-8e5e291bd47b.png)

I've also tried another docker with my custom bridget settings > working fine too (but outdated)
Is there something wrong with my settings?

**Comment by clmcavaney** [comment]
G'day,

> @Pw4r0w this is a stab in the dark, but the latest image pushed to Docker Hub now includes the ability to set `SKIP_NSSWITCH_CONF=TRUE` to disable the creation of `/etc/nsswitch.conf`. Can you give that option a try when you get a chance and see if that helps?

I tried this, but it was also unable to resolve DNS:

```
$ docker run -d -it -e EULA=TRUE -e SKIP_NSSWITCH_CONF=TRUE -p 25565:25565 --name mc itzg/minecraft-server
46781d085b83fd89332d12a585ad498016b6326d419fd80940cf1222f5397742
$ docker logs mc
usermod: no changes
Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Dec  3 07:20 /data'
Checking version information.
curl: (6) Could not resolve host: launchermeta.mojang.com
Checking type information.
Downloading minecraft_server..jar ...
curl: (6) Could not resolve host: launchermeta.mojang.com
ERROR failed to obtain version manifest URL (6)
```

I'm relatively new to Docker, so not able to diagnose any further inside the container.  Is there a basic shell included to interact with the container and run a simple host or dig command?

Regards,
Christopher

**Comment by clmcavaney** [comment]
Couldn't help myself - kept looking into this.
Turned out that I hadn't allowed the Docker subnet access to my forwarding name server.
So, including the /16 subnet that Docker uses sorted things:
```
allow-recursion { ... ; 172.17/16; }
```

**Comment by itzg** [comment]
@clmcavaney so glad to hear your scenario got resolved. To answer your question: yes, `bash` is included in the image so you can always insert `--entrypoint bash` to interact within the container. (I do that a lot when enhancing things on it :) )

**Comment by roomboot** [comment]
I had the exact same issue. Using the Host network instead of bridged network solved the problem for me.

Any idea why and how to get the server to run on the bridged network?

**Comment by itzg** [comment]
@roomboot I'm guessing most users, myself included, are successfully using the default bridge networking, so there’s no advise I can provide relative to this repo.

As @wlp7s0 mentioned the DNS issues described here do not seem to be a bug or issue with this repo specifically.  I’m going to close this issue and recommend that anyone having DNS issues should work with the respective Docker distribution provider, such as QNAP in this case.  

The Discord server could also be a good place to share findings and crowd source solutions.

**Comment by fabiosanchez27** [comment]
Sorry to bother by adding a comment into this closed issue but I am running in the same problem.

I even did the troubleshooting like described here:

> To help troubleshoot, can you deploy a container with the image curlimages/curl and the command line https://launchermeta.mojang.com/mc/game/version_manifest.json? That should exercise the equivalent logic but take the minecraft-server image out of the picture.

Unfortunatelly neither the minecraft docker nor the curl docker can resolve the name:
minecraft:
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Mar  9 00:07 /data'                                                                  
curl: (6) Could not resolve host: launchermeta.mojang.com   

curl:
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
curl: (6) Could not resolve host: launchermeta.mojang.com

I will try the nat setting next.

Again sorry for bothering :D.
