### ISSUE TITLE
BuildTools out of date

### ISSUE THREAD

**Issue by nikhiljha** [itzg/docker-minecraft-server#417]
I get this warning when starting a Spigot server.

```
*** Server will start in 20 seconds ***,
*** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***,
*** Error, this build is outdated ***
```

Works fine on 1.15.1, it's just complaining about BuildTools being out of date.

**Comment by itzg** [comment]
Sorry for the delay in responding. For what it's worth, I am seeing the same message even with a completely fresh container. Apparently https://getbukkit.org/ 's downloads are just out of date enough to trigger the error. I wonder if there's a command line option the container script could pass to disable the check...

**Comment by nikhiljha** [comment]
Is `getbukkit.org` an official source? I remember the original bukkit builds just being available on `bukkit.org` and Spigot builds being available on `spigotmc.org`.

You can always grab Spigot's latest BuildTools (which can also build Bukkit) from https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar - which is an official source.

**Comment by itzg** [comment]
getbukkit is “semi official” :) in that it provides a robust way to download a few flavors. Yes, as you found the image supports building from source; however, that takes much longer than the 20 second update check delay :)

**Comment by vlldk** [comment]
Is there possibly another way to get the pre-built images? The current latest, force-redownloaded version gives an error telling me that the server is 77 versions behind which seems like quite a bit... 
![image](https://user-images.githubusercontent.com/25381970/79671526-4634ff80-81ba-11ea-8355-db6433927ddc.png)
Otherwise I'll just built it myself

**Comment by itzg** [comment]
I do not know of another download provider, especially since bukkit had to discontinue direct downloads due DCMA takedown: https://bukkit.gamepedia.com/FAQ#Where_can_I_get_it.3F

Just to clarify, the option `-e BUILD_FROM_SOURCE=true` will enable you to build your own at first startup.

**Comment by nikhiljha** [comment]
I "solved" this by switching to Paper, which seems to not have that issue. Paper is generally fully compatible with CB/Spigot plugins, so you should give it a shot if you haven't already.

**Comment by itzg** [comment]
I only play vanilla, so I can barely keep up with what's going on the world bukkit, spigot, paper, magma, ... :)

**Comment by itzg** [comment]
FWIW, I just pushed an image update that sets a flag on Spigot to skip the 20 second delay after update check.

**Comment by vlldk** [comment]
Thanks for your feedback, I'll try out the different options to find what fit my needs best 😄
