### ISSUE TITLE
Use higher Java version

### ISSUE THREAD

**Issue by quiquelhappy** [itzg/docker-minecraft-server#419]
Hello!
My server is being halted on startup because a plugin is triggering a java bug that was fixed months ago, could you please upgrade the jvm version to  Oracle Java/OpenJ9(JVM8)?

The plugin in question is "quickshop", quite popular and essential to most survival economy servers.

Here you have the [error ](https://cdn.discordapp.com/attachments/471882812270706719/661552731323891717/Terminus_VKWynTk7tA.png)showing up in the logs

___

Other than that, this is working like a charm! I reported this issue to the plugin author  @Ghost-chu on discord too.

**Comment by itzg** [comment]
Can you give it a try with the image tag  itzg/minecraft-server:adopt11? I’m considering switching the mainline to be based on that and would appreciate you testing it out especially in this scenario.

**Comment by Ghost-chu** [comment]
here is snapshot reported by @quiquelhappy 
![Terminus_VKWynTk7tA](https://user-images.githubusercontent.com/30802565/71623267-4d89ca80-2c16-11ea-8f6e-eba95b60fac0.png)

we have bstats to allow view jvms can running quickshop: 
https://bstats.org/plugin/bukkit/QuickShop-Reremake

**Comment by itzg** [comment]
There’s almost 300 users there on 1.8.0_212, but I wonder if it’s something about the alpine variant used in this image.

**Comment by quiquelhappy** [comment]
Hello!
With :adopt11 the server is starting up with the plugin and running fine:
![alt text](https://i.imgur.com/pXQP91u.png "new image pull")
![alt text](https://imgur.com/UIiijbp "server startup")

**This image (:adopt11) is working perfectly**, let me know if I can do any further testing for you!

**Comment by Ghost-chu** [comment]
I have received same report with same version number.
So i think it maybe JDBC driver issue, because the plugin is reading data from Database.

**Comment by quiquelhappy** [comment]
@Ghost-chu the plugin should be reading the local shops.db file, I'm not using a MySQL server for that file right now, if you need me for any further testing let me know.

**Comment by Ghost-chu** [comment]
> @Ghost-chu the plugin should be reading the local shops.db file, I'm not using a MySQL server for that file right now, if you need me for any further testing let me know.

JDBC is a driver for Database in Java.
It both support SQLite and MySQL

**Comment by quiquelhappy** [comment]
@itzg please, close this issue or post something when it's safe to use standard release again (without adopt 11)

**Comment by itzg** [comment]
Thanks! I'll close this (if I remember :) ) when I switch mainline to adopt11.

**Comment by Lartza** [comment]
Forge does NOT support anything other than Java 8 nor does it support the OpenJ9 JVM, only HotSpot. Unsure about Fabric. It should run fine on 8u232 though instead of the 212 in the current image.

**Comment by itzg** [comment]
Thanks @Lartza, I thought there was a reason I was holding off on upgrading the mainline beyond 8. Unfortunately the alpine variant of openjdk tops out at 8u212 :(, so we'll have to stick with the alternate tags, like adopt11, for versions beyond that.

**Comment by wlp7s0** [comment]
@itzg this is exactly why I asked you to add 
`adoptopenjdk/openjdk8:alpine-jre
adoptopenjdk/openjdk8:alpine-slim
adoptopenjdk/openjdk8:alpine-jre-nightly`
those branches in a first place. I'm using Forge as @Lartza and it supports only native java. 
In my experience - those are great alternatives. Also, to have openjdk10 would be nice
`adoptopenjdk/openjdk10:alpine-slim`
tested this version with FORGE 14.23 version.

**Comment by MarcDoughty** [comment]
I've had great luck running Minecraft Server on OpenJDK 13, and with ZGC (which is no longer experimental in Java 13) instead of G1GC.

I'm guessing your code will run really well under 'adoptopenjdk:13-jre-hotspot-bionic' as the base image. I might try to get my feet wet with Docker doing this.

**Comment by itzg** [comment]
@MarcDoughty at the risk of spoiling some of the fun, I could get that prepped in a branch like the adoptopenjdk 11 branch:

https://github.com/itzg/docker-minecraft-server/blob/adopt11/Dockerfile#L1

You could take it from there with some confirmation of a switch from G1GC to ZGC.

**Comment by itzg** [comment]
... @MarcDoughty I prepared the branch here https://github.com/itzg/docker-minecraft-server/blob/adopt13/Dockerfile#L1

**Comment by MarcDoughty** [comment]
Oooh, very cool. I started playing on my own over here: https://github.com/MarcDoughty/docker-minecraft-server/

I'm new to this, so I might be making a mess for a while until I get a grip on things.

So far in my fork, the conversion to Bionic, JDK13, and ZGC are working, but I only played vanilla for a few minutes, so it hasn't *really* been tested.

I can contribute back to that once I figure things out (both with Docker and with git).

**Comment by itzg** [comment]
FYI, I'm trying to keep the mainline branches to be based on Alpine since it definitely trims down the overall image size. As I mentioned over in https://github.com/itzg/docker-minecraft-server/issues/443#issuecomment-594008079 the `multiarch` branch is already based on Debian, so you'll probably find that is more familiar "apt territory".

**Comment by magneticflux-** [comment]
Is there a build for the `adopt13` branch? It seems like the CircleCI build failed.

**Comment by itzg** [comment]
Sorry for the confusion @magneticflux- , I should really clean up the CircleCI build. The actual image builds are done in Docker Hub and I have added an automated build for the `adopt13` branch and image tag. So `itzg/minecraft-server:adopt13` is now available for use.
