### ISSUE TITLE
does this support nas servers?

### ISSUE THREAD

**Issue by bigdog0044** [itzg/docker-minecraft-server#421]
I have been trying to setup a minecraft server using my nas. But the EULA does not seem to be updating even tho I copy and pasted in the excact command from your website. I just wanted to know if this image is supported on nas?

**Comment by itzg** [comment]
I don’t have access to a NAS myself, but have worked with others that have been able to get the server to work on one. To see if I can spot anything can you provide info about what NAS system you’re using and any screenshots or snippets of how you’re attempting to run the server?

**Comment by bigdog0044** [comment]
the nas server I am using is the TerraMaster F5-22 5bay cloud storage. The code I am trying to run is 

docker run -d -it -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server

but when I run it in the container it gives the following error 
![image](https://user-images.githubusercontent.com/33731701/71980466-fd16fc00-3217-11ea-81fa-1b9ad9100bb8.png)

after seeing this error. I try running: docker run -e EULA=TRUE but still it gives the same error.

**Comment by itzg** [comment]
Strange, that all seems correct. To confirm there's not a stale instance, can you try running it in the foreground by removing the `-d` as in:

```
docker run -it -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
```

**Comment by bigdog0044** [comment]
ok I have just done that and it still provides the same error message

**Comment by itzg** [comment]
Even more strange. Can you now do a `docker pull itzg/minecraft-server`, re-run the foreground version of the command and provide the logs from the start of the container run?

**Comment by bigdog0044** [comment]
Is that using the docker app for windows 10?

**Comment by itzg** [comment]
You'll run the docker pull in the same command line area where you are invoking docker run.

**Comment by bigdog0044** [comment]
ok sorry for the long reply, unfortually the docker on my nas server does not have a command line, instead I have re-downloaded the image and tried running the command
docker run -it -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server
but I still get the same error

**Comment by itzg** [comment]
Ah, ok, but now I'm confused. Does the NAS let you input that `docker run` command-line exactly or does it have a UI to enter the equivalent fields? (I am not able to easily find the user guide for their products with regard to Docker usage.)

**Comment by bigdog0044** [comment]
no there is no UI or command line place to input that. The only way to install images is through a section called the registary 
![image](https://user-images.githubusercontent.com/33731701/72055557-f2657100-32c2-11ea-9389-db1278b96b58.png)

The image above is the only thing my nas server docker has

**Comment by itzg** [comment]
That helps to see that. Thank you for your patience working with me on this. Can you now post a screenshot of the “Container” tab for the Minecraft server before you start it?

**Comment by bigdog0044** [comment]
![image](https://user-images.githubusercontent.com/33731701/72076315-3f5e3d00-32ed-11ea-834c-1e7e00c04e59.png)
sorry for the late reply

**Comment by itzg** [comment]
Thanks. Can you provide what the "Edit" and "Details" buttons at the top there show?

**Comment by bigdog0044** [comment]
The edit button allows you to edit the container (image shown below) 
![image](https://user-images.githubusercontent.com/33731701/72090760-93295000-3306-11ea-8039-16b1fb4392e2.png)
The details button shows you how much resources the container uses, what port the server runs on etc (image is shown below)
![image](https://user-images.githubusercontent.com/33731701/72090860-c4a21b80-3306-11ea-8930-6e45187c7ba2.png)

**Comment by itzg** [comment]
Thanks! I see there's two things you need to add to the container configuration:
1. In the `Environment` tab, you'll add the `EULA` variable with a "TRUE" value
2. In the `Port Settings` tab, you'll add an entry with local port 25565, network port probably also 25565, and type set as "TCP"

**Comment by bigdog0044** [comment]
It worked, server is now up and running. Thank you so much for helping me on this issue, I hope you have a very nice day.
