### ISSUE TITLE
-e UID=0 not respected

### ISSUE THREAD

**Issue by sheepa** [itzg/docker-minecraft-server#425]
Setting -e UID=0 will still not run the server as root. I understand the reasons not to run a server as root but if explicitly asked for it should.

**Comment by itzg** [comment]
I totally understand and that should work, so I’ll look into this.

**Comment by itzg** [comment]
Thanks for reporting this...the existing logic was definitely broken. The updated image should be available shortly.

**Comment by sheepa** [comment]
Thanks for the quick fix!
