### ISSUE TITLE
Updated to 1.15.2 health check fails

### ISSUE THREAD

**Issue by bagobones** [itzg/docker-minecraft-server#426]
Not sure if it is from rebuilding the container or updating to 1.15.2 but the built in health check seems to be be failing.. looks like mcstatus is failing to install or load.

**Comment by itzg** [comment]
Ah, I had switched from using mcstatus to mc-monitor for health checks since mcstatus was the only reason python was being pulled into the image.

If you have declared a healthcheck separate from the Dockerfile one
https://github.com/itzg/docker-minecraft-server/blob/master/Dockerfile#L20
then you'll need to update that.

Regardless, I just realized I should put a shim in pace that allows for old-style calls to mcstatus.

**Comment by itzg** [comment]
Can you pull the latest image and see if that resolves the issue for you? It now includes an mcstatus shim in /usr/local/bin.

**Comment by itzg** [comment]
Sorry, I had a bug in the previous image that caused it to just echo the shimmed command. Please pull the image again if you had before.

**Comment by vinnie357** [comment]
was pulling it from helm https://github.com/helm/charts/tree/master/stable/minecraft, had to change:
livenessProbe:
  command:
    - mcstatus
    - localhost:25565
    ~~- status~~ **- ping**
readinessProbe:
  command:
    - mcstatus
    - localhost:25565
   ~~- status~~ **- ping**
or else I just kept hitting the "else" in your updated mcstatus.
`else
  echo "ERROR can only shim the 'ping' command"
  exit 1`
thanks!

**Comment by bagobones** [comment]
After pulling the latest it shows healthy now.. not sure if it is doing a proper check but at least it doesn't constantly appear to be failing.

**Comment by itzg** [comment]
Thanks, both, for the feedback. I’ll adjust the shim to allow for any value for the second argument since there’s not much point in it being picky.

**Comment by roncanepa** [comment]
Hello.  Could you please update the documentation as far as mcstatus change?  I spent way too much time and even submitted an issue over there where when thought I was having problems.

https://github.com/Dinnerbone/mcstatus/issues/78

**Comment by roncanepa** [comment]
I would also suggest adding some additional output to when the shim calls mcstatus stating that it's being passed through to another utility.

**Comment by itzg** [comment]
@roncanepa I'm so sorry for that. I had forgotten I had an mcstatus reference in the README, so I have
- updated https://github.com/itzg/docker-minecraft-server#healthcheck
- added a deprecation warning in the mcstatus shim

**Comment by roncanepa** [comment]
Perfect!  Thank you.
