### ISSUE TITLE
/start-minecraftFinalSetup: line 34: python: command not found

### ISSUE THREAD

**Issue by Prof-Bloodstone** [itzg/docker-minecraft-server#427]
Python was not only used for mcstatus, but also for parsing json files and checking if they are valid :)
If you don't want to have it in image, jq should be smaller.

```
mc-server | server.properties already created, skipping
mc-server | Checking for JSON files.
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | /start-minecraftFinalSetup: line 34: python: command not found
mc-server | Copying any mods over...
mc-server | Copying any Bukkit plugins over...
```

**Comment by itzg** [comment]
I'm so embarrassed since I think you and I discussed the replacement before of those steps. I'll put python back for the moment and work on the jq replacement.

**Comment by itzg** [comment]
...ah, I missed this during testing since I used a fresh container without any json files there. A new image is now available which puts back python for now. I'll close this issue and we can use the older issue https://github.com/itzg/docker-minecraft-server/issues/323 for tracking python removal progress.

**Comment by Prof-Bloodstone** [comment]
> I'm so embarrassed since I think you and I discussed the replacement before of those steps. I'll put python back for the moment and work on the jq replacement.

I don't think we did discuss it, i barely touched this repo. But I was quite active on the mc backup repo (I believe there's still my 1 PR hanging, didn't have time to work on it further). :)

**Comment by itzg** [comment]
That's what it was...knew we discussed something, somewhere :)
