### ISSUE TITLE
Minecraft Forge 1.12.2 server mods wont work

### ISSUE THREAD

**Issue by LochlainPotato** [itzg/docker-minecraft-server#429]
I'm trying to start a server for me and my friends, I went through all the network stuff and my friends can join flawlessly but the mods don't seem to work. I try to start forge none server in server files to see if it needs to run first but when i do that it says: Potentially Dangerous alternative prefix 'MINECRAFT' followed by the mod name. It also says that some of the mods arent signed or dont have a version annotation. All of the mods worked perfectly in single player. Then it crashes that window. IDK what to do.[https://i.stack.imgur.com/Ym1ec.png](url)
 [https://i.stack.imgur.com/pRi3i.png](url)

**Comment by itzg** [comment]
Can you provide the docker run command-line you're using?

**Comment by LochlainPotato** [comment]
How do i find that and what is it?

**Comment by LochlainPotato** [comment]
> Can you provide the docker run command-line you're using?
How do i find that and what is it?

**Comment by itzg** [comment]
Sorry, I should have generalized the question. Can you provide information about what environment variables and volume mappings you used when creating the image?
