### ISSUE TITLE
Spigot server does not autoupdate

### ISSUE THREAD

**Issue by Nimrod-666** [itzg/docker-minecraft-server#431]
Hi, i'm using the image to host a spigot server and it's currently on version 1.15.1. The newest version offered by spigot is 1.15.2 and after reading the docs i thaught the container has an autoupdate function by restarting it? My version is not updating, but maybe i understood something wrong?

Here's my compose file:

`version: '3.7'

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - mc:/data
    environment:
      - EULA=TRUE
      - TYPE=SPIGOT
      - ENABLE_RCON=true
      - CONSOLE=FALSE
      - VERSION=LATEST
      - RCON_PASSWORD=${rconpw}
      - RCON_PORT=28016
      - MEMORY=6G
      - VIEW_DISTANCE=20
      - MOTD="Sandros Minecraft Server"
      - REPLACE_ENV_VARIABLES=TRUE
      - ENV_VARIABLE_PREFIX="CFG_"
      - CFG_DB_HOST="http://localhost:3306"
      - CFG_DB_NAME="minecraft"
      - CFG_DB_PASSWORD=${dbpw}
      - SERVER_NAME="Sandros Server"
    restart: always
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    volumes:
      - rcon:/opt/rcon-web-admin/db

volumes:
  mc:
  rcon:
`

**Comment by itzg** [comment]
Your understanding is correct and your compose file looks correct, especially the `VERSION=LATEST`. I'll have to investigate that part of the startup scripts to see why it might not work as we're expecting. In the meantime, can you provide the initial logs from when you restarted the container to (try to) pick up the update?

**Comment by itzg** [comment]
...I found the issue. Since the jar file's name doesn't mention the version it isn't properly allowing for `VERSION=LATEST` style auto-updates:

https://github.com/itzg/docker-minecraft-server/blob/cae1a2097366d003ea2d1940e59270ac4e8c4159/start-deployBukkitSpigot#L67-L76

I'll work on a fix for that.

**Comment by itzg** [comment]
If you `docker-compose pull` or `docker pull itzg/minecraft-server` the latest image, this should be fixed. Let me know though if it doesn't (or causes more issues).

**Comment by sandroLuk** [comment]
That worked great! Thank you! Great work with the images!

**Comment by lookapanda** [comment]
Hi, this doesn't work for me. It's not building from source nor updating the server (it says it's 95 versions behind) and I also get a "Error, this build is outdated" console log.

**Comment by itzg** [comment]
@lookapanda it would be better to open a new issue, either way please provide the docker run command line you’re using or docker compose. Also provide container logs. Also make sure you have pulled the latest image.
