### ISSUE TITLE
Reload command not working

### ISSUE THREAD

**Issue by WaterKnight1998** [itzg/docker-minecraft-server#432]
Hi,

After I added plugins to plugins folder or modified whitelist, I tried to reload. However reload command or whitelist reload is not working.

> 
> reload
> §cPlease note that this command is not supported and may cause issues when using some plugins.
> §cIf you encounter any issues please use the /stop command to restart your server.
> §aReload complete.

I need to stop server and start it again. Is there any fix?

**Comment by itzg** [comment]
I'm afraid this is beyond the control of the docker image itself, so I can't offer any help. I agree that from the command's output it sounds like you need to stop and restart the container to load plugin changes.
