### ISSUE TITLE
rcon does not connect to minecraft server

### ISSUE THREAD

**Issue by vjunjoced** [itzg/docker-minecraft-server#436]
I am trying to run the server on my pc but the rcon does not connect to the minecraft. The minecraft server is running perfectly.

![image](https://user-images.githubusercontent.com/16103960/74496376-444c7880-4eb9-11ea-8166-f96e5239224e.png)

![image](https://user-images.githubusercontent.com/16103960/74496511-a1482e80-4eb9-11ea-9c25-b03a56de2d23.png)
![image](https://user-images.githubusercontent.com/16103960/74496538-b58c2b80-4eb9-11ea-80b5-bf62306a26d9.png)
![image](https://user-images.githubusercontent.com/16103960/74496548-bd4bd000-4eb9-11ea-9b04-6e00817e7d03.png)

**Comment by vjunjoced** [comment]
I have run it directly on my cloud server and it has worked.

**Comment by itzg** [comment]
That’s strange it didn’t work on your PC; config looked right to me. In any case, glad it worked in the final setup.
