### ISSUE TITLE
Can't use any ports; "connection refused"

### ISSUE THREAD

**Issue by JohnEridium** [itzg/docker-minecraft-server#437]
Hey there,

despite several fresh installs, i am unable to set another port for a server, other than 25565. Portscans also reveal that, even though specified otherwise in the initial docker run command, only port 25565 is open.

The command i used is:

docker run -d -p 25566:25565 -e EULA=TRUE -e DIFFICULTY=normal -e LEVEL_TYPE=flat -e ALLOW_NETHER=true -e SPAWN_ANIMLAS=true -e SPAWN_MONSTERS=true -e SPAWN_NPCS=true -e MODE=creative -e 'MOTD=Try out builds and show them to others' -e VERSION=1.15.2 --name ShowOff itzg/minecraft-server

so that the port to the outs should be 25566, yet the port that actually opens is 25565. Minecraft also throws an error saying

"io.netty.AbstractChannel$AnnotatedConnectException: Connection refused: "

I am more or less directly attached to the machine (docker is running in a proxmox vm and connected via a switch).

Furthermore, as of writing this, not even the standard port is working.  command is:

 docker run -d -it -e EULA=TRUE -p 25565:25565 --name test itzg/minecraft-server

OS is fresh install of Ubuntu 18.04.04.

can anyone help me? i am at a total loss here...

**Comment by JohnEridium** [comment]
i correct: default port works

`... -p 25566:25565` does not....

**Comment by itzg** [comment]
When you say

> Minecraft also throws an error saying
> "io.netty.AbstractChannel$AnnotatedConnectException: Connection refused: "

Is that coming from the Minecraft server container logs or the client? If it is the server, can you provide a few more lines of logs around it to help me identify the context?

Since I'm curious if the default docker network on your system is using host mode, can you also provide the output from

```
docker container inspect ShowOff -f '{{ json .NetworkSettings }}'
```

**Comment by JohnEridium** [comment]
hey,
thanks for your fast reply!

for some reason, proxmox has two places where you need to deactivate the hypervisor firewall (Hardware --> network devices --> firewall and firewall --> options --> firewall) and i only deactivated one of them.
it all works now

thouh my output of the command you provided:

`{"Bridge":"","SandboxID":"740f3cd25303e11c3a7fe33752d848309c76886854010b457ad9ed94ae90c4c9","HairpinMode":false,"LinkLocalIPv6Address":"","LinkLocalIPv6PrefixLen":0,"Ports":{},"SandboxKey":"/var/run/docker/netns/740f3cd25303","SecondaryIPAddresses":null,"SecondaryIPv6Addresses":null,"EndpointID":"","Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","MacAddress":"","Networks":{"bridge":{"IPAMConfig":null,"Links":null,"Aliases":null,"NetworkID":"4911e841cc8731b0976b09c872e515fc95cf2b03a8bf1fb7d5bd10171931e797","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"","DriverOpts":null}}}`

thanks again ^^
