### ISSUE TITLE
extract world data from container

### ISSUE THREAD

**Issue by JohnEridium** [itzg/docker-minecraft-server#438]
Hey there,

is there a way to extract the world data from one container to move it to another container on a different machine?
I can't seem to find a "world" folder or something like this

thanks in advance :D

**Comment by wlp7s0** [comment]
Hello, can you provide a docker run command that you use to start a container? minecraft's data directory is stored under /data inside a docker container. 
1. If you didn't mount this directory on 'docker run' than your data is inside docker's fs layer. To copy it - run the container with custom entry point - bash and mounted directory from host's system. Copy the world to the mounted directory and you are ready to move it.
2. If you did mount it, the world should be inside the directory that you mount to docker's /data directory.

**Comment by itzg** [comment]
Thanks @wlp7s0 for reminding me of this issue and asking what I would have :)

**Comment by itzg** [comment]
Thanks @wlp7s0 for reminding me of this issue and asking what I would have :)

**Comment by JohnEridium** [comment]
hey there, thanks for the reply (sorry i was busy this week)

so in Order to attach a volume that saves the world data of a container, you can just create a volume and mount it in /data inside the container in order to make the world data persistent, even if the container is removed with docker rm?
I'm still fairly new to docker and have messed with volumes in any way yet

**Comment by JohnEridium** [comment]
Nice!
works like a charm

sorry for the late reply
