### ISSUE TITLE
Specifying a value for -e MEMORY seems to crash the container.

### ISSUE THREAD

**Issue by Arocho17** [itzg/docker-minecraft-server#439]
Not sure why this is ocurring, but whenever I try and set a value for the MEMORY variable the server will not start. I am using a forge server, 14.23.5.2847 and Minecraft version 1.12.2.  Here is my line:
docker run -p 25565 -e VERSION=1.12.2 -e TYPE=FORGE -e FORGEVERSION=14.23.5.2847 -e EULA=TRUE -e MEMORY=3G -v "/Users/Joey/Server/1.12":/data --name server itzg/minecraft-server

The server starts fine without the memory variable.

When running docker inspect server I see "failed to ping localhost:25565 : could not connect to Minecraft server: dial tcp 127.0.0.1:25565: connect: connection refused"

Not entirely sure if its something I'm doing wrong if if it should be an issue.

Thanks for any help you can provide!

**Comment by itzg** [comment]
To sanity check, do you have 3 GB of memory available on the Docker host? Otherwise, can you provide the container logs from one of the failures?

**Comment by Arocho17** [comment]
I do, and after further testing, it seems to work fine when setting INIT_MEMORY: 1G and MAX_MEMORY: 3G in a docker-compose file as well. Container logs are filled with errors from multiple mods starting up. I provided the logs and the result of docker inspect.

[Container Logs.txt](https://github.com/itzg/docker-minecraft-server/files/4241853/Container.Logs.txt)
[Docker Inpsect Info.txt](https://github.com/itzg/docker-minecraft-server/files/4241854/Docker.Inpsect.Info.txt)

**Comment by Arocho17** [comment]
Also, not sure if worth mentioning but this is running on a Macbook

**Comment by itzg** [comment]
Since you’re running on a Mac you will need to double check the amount of memory allocated to the Docker Desktop VM. I think the default is 2GB.

**Comment by Arocho17** [comment]
Ah, silly me. Forgot to even look there first. Raising the amount fixed it of course.

Thank you!

**Comment by itzg** [comment]
Aha, yep I have to reconfigure the Docker Desktop VM on ever re-install.
