### ISSUE TITLE
Can't get JVM_OPTS to work

### ISSUE THREAD

**Issue by GodsVictory** [itzg/docker-minecraft-server#441]
Am I calling it correctly?

`JVM_OPTS="-Xms10G -Xmx10G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:G1MixedGCLiveThresholdPercent=35 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Dusing.aikars.flags=mcflags.emc.gs"`

**Comment by wlp7s0** [comment]
[https://github.com/itzg/docker-minecraft-server#jvm-options](https://github.com/itzg/docker-minecraft-server#jvm-options)
Nope, you should try 'JVM_XX_OPTS'
