### ISSUE TITLE
Log prefix

### ISSUE THREAD

**Issue by scriptcoded** [itzg/docker-minecraft-server#442]
I'm building a Minecraft server management platform, and I've decided to use your Docker image as a base for running the actual servers.

One thing that's a bit cumbersome right now is differentiating between the logs from the wrapper, and the actual Minecraft server. Would it be a fair idea to prefix the logs with something like `[wrapper]` and `[minecraft]`? That would make it way easier to separate logs correctly. It would also make the output more readable IMO.

I could create a PR for a suggested implementation if it's something that sounds interesting.

Also, great work with this! At first I was using my own image, but this just makes everything 20 times easier!

**Comment by itzg** [comment]
That sounds like a great use case!

I'm definitely open to a PR. Since specifically this logging transfer would be annoying to intercept

https://github.com/itzg/mc-server-runner/blob/master/main.go#L75

I prefer your suggestion of prepending the wrapper's logs with something like `[wrapper]` or `[mc-server-runner]`.

**Comment by scriptcoded** [comment]
Would you prefer having it implemented in the runner instead of the shell scripts in this repo? I added a crude implementation for my own personal usage. It instead replaces the `echo` call and also pipes the output of `mc-server-runner` to `sed`. That effectively shifts the responsibility of labeling the logs to the log aggregator, in this case the actual docker image.

**Comment by itzg** [comment]
Ah, that could work. Can you submit a PR for that then and I'll see how that looks? If we decide to go with an mc-server-runner change, then I can make that change pretty easily too.

**Comment by scriptcoded** [comment]
Now implemented in #444

**Comment by itzg** [comment]
Keep me posted on your management platform. I developed a now-defunct one a long time ago https://github.com/moorkop/mccy-engine , so am always interested in these types of solutions.

**Comment by itzg** [comment]
And apparently a "long time ago" was only 3 years, but that feels like forever in Docker-evolution-time. :)

**Comment by scriptcoded** [comment]
Will do! I'll warn you though. To start of it will only be a personal project. I'm also doing it partially to learn Go, so only the server wrapper will use it. The actual web server will be implemented in Node.js until I feel that I'm confident enough with Go. So it'll be a mess ;)

I'll have a look at your project as well. Perhaps there's some good takeaways.

**Comment by itzg** [comment]
> I'll have a look at your project as well. Perhaps there's some good takeaways.

Go for it!
