### ISSUE TITLE
Motd skips backslashes

### ISSUE THREAD

**Issue by P4sca1** [itzg/docker-minecraft-server#446]
Trying to use back slashes in the motd as explained [here](https://nodecraft.com/support/games/minecraft/including-colours-in-your-motd) to display colors does not work.

**Log:**
`[init] Setting motd to '\u00A7aN\u00A7bO\u00A74D\u00A7eE\u00A77CRAFT \u00A70Official' in /data/server.properties`.

**Actual content of `server.properties`:**
`motd=u00A7aNu00A7bOu00A74Du00A7eEu00A77CRAFT u00A70Official`

**Comment by P4sca1** [comment]
Guess it is something with the usage of `sed`: https://github.com/itzg/docker-minecraft-server/blob/1e334ca7d5c91c30ea505e4a44c34faecb1c607b/start-finalSetup04ServerProperties#L16
But I am too unexperienced with `sed` to dig deeper into this.

**Comment by itzg** [comment]
I think you’re right that the sed operation is chewing them up. I’ll also investigate this a little bit later, but for now try using double backslashes and see if that works.

**Comment by P4sca1** [comment]
Using double backslashes works as a temporary workaround.

**Comment by P4sca1** [comment]
@itzg Which solution do you prefer?
1. Leave a note in the README that you have to use \\ when you want to use \ in server.properties (especially when configuring motd).
2. Automatically replace single backslashes with double backslashes before issuing the sed command, which might be a minor breaking change, but allows a more natural configuration of the server.

**Comment by itzg** [comment]
Sorry for the delay following up on this. I went ahead and created a PR for you check for me.
