### ISSUE TITLE
Link full documentation on docker hub

### ISSUE THREAD

**Issue by hajduzs** [itzg/docker-minecraft-server#448]
Hello!

I've came across this issue myself:
https://github.com/itzg/docker-minecraft-server/issues/384

I just thought it would be nice to clarify where to find the full documentation, for example at the beginning of the Docker Hub overview section. (For those who aren't fully familiar with this chopping "feature" of the platform) 

Ps: Anyway, thank you for this nice image! Thanks to this, I could easily set up a server for my dorm mates for the time of the covid-19 isolation :)

**Comment by itzg** [comment]
I have the "Click for extended docs" link, but maybe doing that as an image didn't make it obvious it was clickable

![image](https://user-images.githubusercontent.com/988985/76768960-c6a2b380-6769-11ea-893d-6e9805b72b15.png)

Perhaps I could add a regular, textual link below it for clarity.

**Comment by hajduzs** [comment]
Oh I see, it is right before my eyes..
Sorry for being such a dummy, it can be hard to clarify these things to everyone. 
Maybe I could suggest to keep only the essential doc parts on docker hub, and add a paragraph/link to github at the very end.
Thanks for the quick reply, and keep up the great work! :)
