### ISSUE TITLE
Abnormal CPU usage on 1.15.2

### ISSUE THREAD

**Issue by vityafx** [itzg/docker-minecraft-server#456]
Hi! Recently my fat vds has started to feel sick and unresponsive and I decided to look at what was it with it so wrong. According to docker stats, my Minecraft server now consumes 1300% of CPU, I barely even can connect or run `top` utility - so bad it is! It started happening quite recently, I think I noticed it a few days ago, but I am not sure how long it has it been. Can we fix this, please? The output of the `docker-compose logs -f` is usual and has nothing extraordinary except these lines:

```
minecraft | [21:24:58] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2202ms or 44 ticks behind
minecraft | [21:25:16] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2612ms or 52 ticks behind
```

**Comment by itzg** [comment]
1.15 in general seems to have degraded performance compared to previous versions; however, it's strange it got worse for your after it had been running for some amount of time. What `TYPE` are you using or just the default vanilla?

**Comment by vityafx** [comment]
> 1.15 in general seems to have degraded performance compared to previous versions; however, it's strange it got worse for your after it had been running for some amount of time. What `TYPE` are you using or just the default vanilla?

If it is an environment variable, then I don't have it specified at all, so must be vanilla:

```
version: "2"

services:
  minecraft-server:
    ports:
      - "25565:25565"

    environment:
      - EULA=TRUE
      - ONLINE_MODE=FALSE
      - WHITELIST=aa,bb
      - MAX_PLAYERS=2
      - ALLOW_NETHER=true
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - ENABLE_COMMAND_BLOCK=true
      - GENERATE_STRUCTURES=true
      - MOTD=Minecraft Server

    image: itzg/minecraft-server:adopt13

    container_name: minecraft

    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./data:/data
```

**Comment by vityafx** [comment]
I was running it on a custom VM, not from google cloud or amazon or digital ocean droplet, it is just a VDS with KVM: 4 core some xeon of 2800 mhz, 8gb ram, SSD 130gb.

**Comment by itzg** [comment]
Strange, that should be plenty of horsepower. One thing you could try is using the JVM 11 variant of the image, which is `itzg/minecraft-server:adopt11`. I'm having to stick with JVM 8 on the mainline since Forge and others don't play nice with newer Java versions.

**Comment by vityafx** [comment]
I've already tried that recently. The server finally started but the CPU usage is less scary: not 1200% but 100% instead. Not very cool anyway, I think. And this - when no one is on the server. When I finally launch the game and join the server, I have to wait like for 2 minutes to render the world.

**Comment by aK0nshin** [comment]
Hello, I'm trying to deploy container to the Google Cloud Kubernetes Engine with your k8s deployment example manifest and got same issue.

```
...
[23:18:39] [Server-Worker-1/INFO]: Preparing spawn area: 87%
[23:18:40] [Server-Worker-1/INFO]: Preparing spawn area: 88%
[23:18:40] [Server-Worker-1/INFO]: Preparing spawn area: 90%
[23:18:41] [Server-Worker-1/INFO]: Preparing spawn area: 91%
[23:18:41] [Netty Epoll Server IO #1/INFO]: Disconnecting Player (server is still starting): Server is still starting! Please wait before reconnecting.
[23:18:41] [Server-Worker-1/INFO]: Preparing spawn area: 92%
[23:18:42] [Server-Worker-1/INFO]: Preparing spawn area: 93%
[23:18:42] [Server-Worker-1/INFO]: Preparing spawn area: 95%
[23:18:43] [Server-Worker-1/INFO]: Preparing spawn area: 95%
[23:18:43] [Server-Worker-1/INFO]: Preparing spawn area: 98%
[23:18:44] [Server thread/INFO]: Time elapsed: 51944 ms
[23:18:44] [Server thread/INFO]: Done (119.171s)! For help, type "help"
[23:18:44] [Server thread/INFO]: Starting remote control listener
[23:18:44] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
[23:18:45] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:18:45] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:23:47] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 3218ms or 64 ticks behind
```
Tried `itzg/minecraft-server` and `itzg/minecraft-server:adopt11` images.
My machine is `e2-standard-2` as you suggests.
I also add `resources` section to deployment becouse my pods get evicted other way:
```
resources:
          requests:
            memory: "6208268Ki"
            cpu: "1930m"
          limits:
            memory: "6208268Ki"
            cpu: "1930m"
```
My env:
```
env:
        - name: GUI
          value: "false"
        - name: MEMORY
          value: "6G"
        - name: VERSION
          value: "1.15.2"
        - name: TYPE
          value: "FORGE"
        - name: FORGEVERSION
          value: "31.1.0"
        - name: EULA
          value: "true"
```

**Comment by itzg** [comment]
@aK0nshin , can you open a new issue for your scenario?

**Comment by vityafx** [comment]
So, I've just moved to DigitalOcean from my old provider. It runs fine it seems. If not, I'll re-open this issue. Thank you for your fast response!
