### ISSUE TITLE
Image doesn't run with 2 cpu cores

### ISSUE THREAD

**Issue by Zerrox0** [itzg/docker-minecraft-server#458]
I just pulled the latest version of the image and tried to start a server, but it seems to fail based on some java arguments. An older version of the image that's running on another Docker host is working fine.

This is the log:

> [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx   12 1000     1000          4096 Mar 23 02:07 /data'
[init] Checking version information.
[init] Checking type information.
[init] Checking Forge version information.
[init] server.properties already created, skipping
[init] log4j2.xml already created, skipping
[init] Checking for JSON files.
[init] Copying any mods over...
[init] Setting initial memory to 2G and max to 2G
[init] Starting the Minecraft server...
Error occurred during initialization of VM
The flag -XX:+UseG1GC can not be combined with -XX:ParallelGCThreads=0
2020/03/23 02:07:45 Done

**Comment by ZeroxTV** [comment]
I've been trying to work around it some more, but I don't seem to be able to fix it. Maybe it's my docker host, and not the image? Can anyone confirm this?

If that's the case I'm really sorry for this unnecessary issue

**Comment by ZeroxTV** [comment]
The error was on my side, I'm sorry. It has nothing to do with the latest image

I was running the container in a docker instance inside a proxmox container and the container only had 2 cpu cores assigned. I was looking at #321 and a solution mentioning cpu cores, so I tried out increasing the core count for the container. This seems to have fixed it.

Still weird, that it doesn't work with 2 cpu cores, might be worth further investigating

**Comment by ZeroxTV** [comment]
Set the core count back down to see if my claim was right, but since the last restart it seems to be working every time with any core count. Seems a bit inconsistent, but it might still be due to my system setup.

**Comment by itzg** [comment]
I have run this on various multi-core systems. The issue your in description is simply because the JVM doesn't allow mixing the G1GC garbage collector with the parallel GC option since they are from two different GC implementations. If you need further assistance please provide a snippet showing how the container is being started. Specifically I was curious if `JVM_XX_OPTS` was getting reconfigured correctly from the default value of "-XX:+UseG1GC"

**Comment by ZeroxTV** [comment]
I start the container with this docker run command:

> docker run -d \
	--name mc \\
	--restart unless-stopped \\
	-v /root/mc:/data \\
	-p 25567:25565 \\
	-e ONLINE_MODE=TRUE \\
	-e MEMORY=2G \\
	-e EULA=TRUE \\
	itzg/minecraft-server

Like I mentioned, strangely enough, it is working completely fine since the last restart and I have not changed anything about the way I start the container.

**Comment by itzg** [comment]
I just heard of someone else with a similar problem and I was wondering if the solution here also works for you:

https://github.com/itzg/docker-minecraft-server/issues/466#issuecomment-605677829
