### ISSUE TITLE
Set the time for the container docker 

### ISSUE THREAD

**Issue by Bloopps** [itzg/docker-minecraft-server#463]
Hi,
I have a time difference in my container logs, I can't figure out how to set the time for my time zone how can I do it?
Thanks for your work.

**Comment by itzg** [comment]
If it's a timezone mismatch, then there are solutions like

https://forums.docker.com/t/synchronize-timezone-from-host-to-container/39116

If you're seeing this with Docker Desktop, this is/was an issue I kept seeing with the VM's clock drifting from the host clock `https://github.com/docker/for-win/issues/5593`

**Comment by pauldadin** [comment]
It's resolved, I hadn't set my docker server time correctly.  
🤦‍♂

**Comment by Bloopps** [comment]
It's resolved, I hadn't set my docker server time correctly.
🤦‍♂
