### ISSUE TITLE
template pre-baked dockerimage

### ISSUE THREAD

**Issue by breuerfelix** [itzg/docker-minecraft-server#464]
hey guys,

i am really familiar with docker but not with minecraft servers.

Yet, my little brothers want a server so i have to see what i can do...  
I managed to set one up with permissions and stuff like that some months ago but now after updating to minecraft 1.15 it doesnt work anymore.

Also a fresh installation without plugins hangs at "loading plugins..."

i was wondering if someone did a dockerimage with the basic plugins everybody should use (like permissions) pre configured and just ready to go.

Maybe just set some env vars like seed and OPS or mount a permissions file

I found myself struggling hard on configuring the server to work, so this might help me alot !

cheers,

felix

**Comment by itzg** [comment]
I personally just use vanilla servers, but @Silthus this sounds like something you might have solved for...maybe?

Otherwise @breuerfelix I would recommend jumping on the Discord channel (https://discord.gg/DXfKpjB), if you haven't already and pose the question there.

**Comment by Silthus** [comment]
@itzg is right. I did something like this about a year ago for my old Minecraft server. However I never created a public „pre-built“ image that can be reused.

**Comment by itzg** [comment]
@breuerfelix I was thinking about this some more and I have already wanted to do some Dockerfile cleanup like not pre-declaring all of these volumes (and not force them on every container created)

https://github.com/itzg/docker-minecraft-server/blob/6f67f76eefe3e7c260e204e3e64c63910fa4929e/Dockerfile#L61

If I were to at least remove `/mods` from there, you could craft a Dockerfile that was based from itzg/minecraft-server and then `ADD`/`COPY` the desired plugins into `/mods` to stage them for container startup.

**Comment by wlp7s0** [comment]
@itzg  I'm confused. Though I just used FORGE and vanila servers, to use mods and custom config I use `./data/mods` and `./data/config` directory. 
Checking the startup [script](https://github.com/itzg/docker-minecraft-server/blob/master/start-minecraftFinalSetup) I can see that the script just duplicates `/mods` and `/data/mods` on startup. I don't understand why it is there? one can reach mods via `/data/mods` that is mounted as a volume. 

And the advantage of `/data/mods` usage is that you can just restart the container without rebuilding it to activate\deactivate mods\config.

**Comment by itzg** [comment]
@wlp7s0 yes, it certainly looks confusing at first since you're right, the `/data/mods` (and `/data/plugins`) directories are the ones used at runtime. The `/mods` feature allows you to stage your favorite set of mods into a docker volume and then spin up any number of containers based on that set. That realization is what made me think this feature could actually help in @breuerfelix , but instead of a pre-staged docker volume, it would be a pre-built image.

**Comment by breuerfelix** [comment]
yes thats exactly what i am looking for !

just some pre baked /plugins and /mods that i can spin up a container with that works with some basic functionality out of the box ! i guess that would help so many people :D cause if you come into this MC world... you are overwhelmed with all these different server types and plugins / mods stuff like that :)

**Comment by itzg** [comment]
I pushed a new image that removes the forced creation of `/mods` and `/config` volumes. That improves the feasibility of creating derivative images to pre-`ADD` into those paths.
