### ISSUE TITLE
Cannot execute /fml confirm while attched

### ISSUE THREAD

**Issue by Razva** [itzg/docker-minecraft-server#465]
I've started the container using `-it`. I can see the startup procedure but I get stuck at this:

```
Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.
```

This occurs because of a bad mod that I've removed and now I need to confirm all items/entities removal.

How could I start the server using `-Dfml.queryResult=confirm` or execute `/fml confirm`?

**Comment by itzg** [comment]
You can add that option using `-e JVM_DD_OPTS=fml.queryResult:confirm`, which interestingly was an example that someone contributed to the section

https://github.com/itzg/docker-minecraft-server#jvm-options
