### ISSUE TITLE
Duplicate fml flags in ServerStart.sh

### ISSUE THREAD

**Issue by dunksten** [itzg/docker-minecraft-server#468]
Hi. While investigating how to update a CurseForge pack I discovered a weird behaviour.

The ProjectOzone3 pack has no own ServerStart.sh, so the image is creating one. In this file a flag named "-Dfml.queryResult=confirm" is inserted into the command. 

What I discovered is that every time the container restarts, this flag is appended which leads to a lot of duplicate flags. In my old file probably more than 100 duplicate "-Dfml.queryResult=confirm" flags.

**Comment by itzg** [comment]
Good catch. I'll look into fixing that.
