### ISSUE TITLE
Updating Curseforge Modpack not possible

### ISSUE THREAD

**Issue by dunksten** [itzg/docker-minecraft-server#469]
Hi,
from the README file updating a pack should be as simple as putting the new file in the /data directory and recreating the container. 

Well, it seems not as easy as that. Updating the environment variable does nothing, the pack starts normally as is into the old version.

I had a look into the DeployFTB.sh file and discovered that the new .zip is only unpacked when no ServerStart.sh file is present in the FeedTheBeast directory.

I don't know if I'm doing something wrong or if updating is not intended at all, but only deleting ServerStart.sh will lead to unpacking of the new .zip.

Well, this normally leads to another issue of conflicting mod versions which crashed the pack at startup.
Every time the pack is updated, "mods", "config" and "scripts" folder have to be deleted first.

That solves the issue and the pack is updated.

**Comment by itzg** [comment]
Yeah, I'm afraid upgrading of a modpack is not directly supported by the startup scripts; however, along the lines of your solution deleting the entire `/data/FeedTheBeast` directory will ensure both the unpacking logic is triggered and conflicting mods are avoided. The downside is that configuration data within the mods area will get lost, but I believe each modpack tends to provide its own reasonable defaults.

**Comment by mankalan** [comment]
HI,
Since the last update of the docker image, it is imposible to create a server with FTB or Courseforge zips. 
It gives this error
 `,[init] Running FTB /data/FeedTheBeast/ServerStart.sh in /data/FeedTheBeast ...
,2020/03/31 23:09:40 Failed to start: fork/exec /data/FeedTheBeast/ServerStart.sh: permission denied
,[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsrwx    6 1000     1000          4096 Mar 31 23:09 /data'`

**Comment by itzg** [comment]
@mankalan I'll get a fix out for that, but it is caused by the host volume attached to the container having the `noexec` flag enabled on it. On Linux that'll be a setting in the fstab file.

**Comment by itzg** [comment]
@mankalan the permission denied issue should be fixed now if you pull the latest image

**Comment by mankalan** [comment]
@itzg thanks!!.
