### ISSUE TITLE
Docker Status (Unhealthy)

### ISSUE THREAD

**Issue by DaFr0n** [itzg/docker-minecraft-server#471]
Hi all

Iam having a issue regarding Docker health status, Server is running Forge. There does not appear to be any sever issues apart from the status

Failure count 39
failed to ping localhost:25565 : could not connect to Minecraft server: dial tcp [::1]:25565: connect: connection refused

**Portainer Stack:**

---
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft
    network_mode: host
    environment:
      - PUID=100
      - PGID=1000
      - EULA=TRUE
      - VERSION=LATEST
      - MEMORY=2G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - TYPE=FORGE
      #- FORGEVERSION=14.23.5.2838
      - FORGE_INSTALLER=forge-1.12.2-14.23.5.2838-installer.jar
    ports:
      - 25565:25565
    volumes:
      - /srv/dev-disk-by-label-SSD120GB/SSD120GB/Appdata/Minecraft:/data
    restart: unless-stopped

Thanks in advance

**Comment by wlp7s0** [comment]
Hello @DaFr0n ,
As you are using `network_mode: host`, docker container does not listen on localhost, but on server's external IP address. As for now - Docker health status is checking only localhost. Will create a pull request to fix the issue.

**Comment by itzg** [comment]
Good catch @wlp7s0 . @DaFr0n are you sure host network mode was necessary. It is very rare I have found that mode was required.

I'm not familiar with Portainer, so perhaps that is an odd constraint it creates. In which case, you can disable healthchecks entirely in compose using:

```
healthcheck:
  disable: true
```

from https://docs.docker.com/compose/compose-file/#healthcheck

**Comment by DaFr0n** [comment]
> Good catch @wlp7s0 . @DaFr0n are you sure host network mode was necessary. It is very rare I have found that mode was required.
> 
> I'm not familiar with Portainer, so perhaps that is an odd constraint it creates. In which case, you can disable healthchecks entirely in compose using:
> 
> ```
> healthcheck:
>   disable: true
> ```
> 
> from https://docs.docker.com/compose/compose-file/#healthcheck


Hi itzg
Apologies i am new to Docker and not to familiar with the network differences. I believe Portainer set this up automatically as a 'Host' network.

If i change to Minecraft_Default network it gives the below error:
**** FAILED TO BIND TO PORT!
The state engine was in incorrect state POSTINITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded
The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address not available

If i change to 'Bridge' mode network the following error is given:
**** FAILED TO BIND TO PORT!
[16:34:51] [Server thread/INFO]: The state engine was in incorrect state POSTINITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded
The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address not available

**Comment by DaFr0n** [comment]
> Hello @DaFr0n ,
> As you are using `network_mode: host`, docker container does not listen on localhost, but on server's external IP address. As for now - Docker health status is checking only localhost. Will create a pull request to fix the issue.

Hello @wlp7s0 
I used the above Docker Stack and it automatically sets it up as 'Host'. I have tried numerous other networks as mentioned to itzg, however they all throw errors & the server does not start.

Apologies for my lack of experience with these things, slowly learning :)

**Comment by itzg** [comment]
I guess Portainer is trying to be too helpful :). Bridge mode is what I would have expected. Make sure you stopped any other Minecraft containers before trying the switch or maybe allow time for Portainer to deallocate the port 25565. 

Otherwise, disabling the health check is a reasonable solution for now.

**Comment by DaFr0n** [comment]
@itzg Just the one container running so i will switch to 'Bridge' and give it 5 minutes of trying to start.
If no joy i will add health check to the stack.


Thanks for your help

**Comment by DaFr0n** [comment]
@itzg tried leaving it for a while to see if the port was de-allocated, no joy.
I will try and disable the health check though i cannot get this to work in using Portainer stack (v2) it just throws "unsupported config"

**Comment by DaFr0n** [comment]
@itzg Good news all sorted.
Looks like i created the error myself, I have changed over to Bridge mode and its now Healthy.

I had set a server ip in the server.properties file (serverip=) this must have been causing issues, removed the ip leaving it blank resolved the issue.

Thank you both again.
