### ISSUE TITLE
Could not resolve host: launchermeta.mojang.com

### ISSUE THREAD

**Issue by debuamundi** [itzg/docker-minecraft-server#472]
Hi!
My Minecraft Server container is not starting. It fails with the error "Could not resolve host: launchermeta.mojang.com ERROR failed to obtain version manifest URL (6)"

My Docker host is a newly installed Ubuntu 18.04 LTS Server. I have pulled the 1.15.2 version with adopt13 tag (same error with latest). I'm using UFW on my docker host. Because of Docker is bypassing ufw rules I have added "iptables": false to my /etc/docker/daemon.json. UFW is configured to deny all incoming traffic except from IP's that are explicit allowed to port 25565 and allows all outgoing traffic.
When I remove this daemon.json entry it works. But my server would be open for everyone on the internet.
I have also tried to force the Minecraft container to use 8.8.8.8 as DNS. But it fails with the same error.
What am I doing wrong here? Maybe I need some incoming UFW rule for the DNS request? But launchermeta.mojang.com can be resolved from the Docker host with nslookup.

Please help!
Thank you!

**Comment by itzg** [comment]
It sounds like some of the config changes are definitely influencing the problem. FYI, ufw is basically a (user friendly) wrapper around iptables and Docker heavily uses iptables to implement very precise handling of port forwarding rules. So I would highly recommend avoiding that `iptables: false` option in the daemon config.

**Comment by wlp7s0** [comment]
@debuamundi docker uses DOCKER-USER chain to filter the connections to the container. 
https://docs.docker.com/network/iptables/
In your case you need to work with iptables directly to achieve your goal.
After the container is started, you need to add a restriction to the chain and use a strict allow rules.
```
ALLOW_IP='5.6.33.44' # This IP address will be allowed to connect
ALLOW_IP2='66.55.44.111'
PORT='4326' # external port docker is using to forward the connection
iptables -A DOCKER-USER -s ${ALLOW_IP} -p tcp --dport ${PORT} -j ACCEPT
iptables -A DOCKER-USER -s ${ALLOW_IP2} -p tcp --dport ${PORT} -j ACCEPT
iptables -A DOCKER-USER -j REJECT
```
I had encountered some issue with docker + systemd + ufw.

Systemd tries to start all daemons simultaneously on host startup, but both docker and ufw add it's own iptables chain to the build-in kernel chains (INPUT,FORWARD etc). And sometimes docker adds it's chains before ufw. In this case ufw firewall filter rules will be executed first and docker rules will make no difference. You will find a bunch of open issues about this, debating on what service should filter the connections and how. But in my case - I just add the dependency on docker systemd service to start after ufw. Or you can just restart docker after server is booted and ufw is started. 

So, for DOCKER-USER filter rules to work, make sure that it is located on the top of the iptables chain:
```
iptables -nvL FORWARD
```

**Comment by debuamundi** [comment]
@wlp7s0 thank you very much! I have removed `iptables: false` from daemon.json and restarted the docker service. The container is starting now and ufw works for my home network but not for connections from the internet. So I will focus on the iptables.
