### ISSUE TITLE
Docker is dead

### ISSUE THREAD

**Issue by rogue-agent** [itzg/docker-minecraft-server#475]
Hey,
sysadmin from Abyss. Running multiple of these in docker just kills docker and ps.

**Comment by NickCody** [comment]
@rogue-agent what exactly is happening? Do you have an error you can share? If you start multiple instances, its possible you're not binding to separate ports on the host? -p <host_port>:<container_port> so you'll need:

container #1: -p 25565:25565
container #2: -p 2556**6**:25565
container #3: -p 2556**7**:25565

Three separate ports on the host. Not sure if this is your issue.

**Comment by honzapatCZ** [comment]
This might happen if you run out of ram, linux kernel will start killing of processes, in the process it can kill anything.

**Comment by itzg** [comment]
I'm suspecting the same as @honzapatCZ .
