### ISSUE TITLE
Log Prefix might broke console colors

### ISSUE THREAD

**Issue by Sylensky** [itzg/docker-minecraft-server#476]
Hi,

i am using your docker images to run couple paper servers and i noticed that something happened during my container recreation. During my backup process i pulled the latest images of the minecraft-server and the bungeecord. All settings remained the same except the image has changed. Now there are Prefixes in the Console log showing which thread is working on a particular thing. Things that were previously stated in colors are now stated as the actual color code. For example: A red label gets prefixed with "§4" and the color dissapeared.
For a better representation i have the log here below.

[16:27:04] [luckperms-scheduler-worker-5/INFO]: §7§l[§b§lL§3§lP§7§l] §3LOG §3§l>
[16:27:04] [luckperms-scheduler-worker-5/INFO]: §7§l[§b§lL§3§lP§7§l] §3LOG §3§l>

Plugins and server version stayed the same and i made no changes to them.
I am using CentOS-76-64 minimal and the containers are attached in a tmux session.
Do you have any idea what could cause this?

**Comment by itzg** [comment]
Sorry for the delay. My only guess is that the log4j config change here https://github.com/itzg/docker-minecraft-server/commit/fc6129261b784e5a114eb8a023f2953a3f1cb6b1 influenced the color code processing.

@TimoMeijer, looking at one of the Paper patch files for log4j.xml, https://github.com/PaperMC/Paper/blob/master/Spigot-Server-Patches/0172-Handle-plugin-prefixes-using-Log4J-configuration.patch, I'm wondering if the `%minecraftFormatting{%msg}` needed to be used to process-away the color codes.

One solution could be to provide an option like `SKIP_LOGGING_CONFIG` that leaves the builtin log4j to be used; however, log files will enumerate without bound.

**Comment by TimoMeijer** [comment]
Hmm, that patch does not match the log4j2.xml packaged by default with Minecraft, as `%highlightError` and `%minecraftFormatting` do not occur there. Paper must have a different file somewhere.

I'll investigate if I can find that logging file they use, depending on what it contains we can decide what a proper solution is for the Paper environment.

**Comment by TimoMeijer** [comment]
Spigot has a different log4j2.xml, which Paper patches with its additional configuration.
It does have some cleanup, it keeps 1000 log-files, and rolls over daily or on startup. This is a bit under 3 years of logs, which is a bit more than the 7 days we now use.

I suggest we add 2 additional log-files, one for Spigot and one for Paper, with the same cleanup policy we use for vanilla.
@itzg if you agree, I'd be happy to submit a PR when I get some spare time to set it up!

**Comment by itzg** [comment]
Sounds great @TimoMeijer and thanks for investigating that.

**Comment by itzg** [comment]
For now I pushed 56c2f0b4661142ae992e0e24035d0d80c08e0276 which has a conditional on `TYPE != SPIGOT` since it also seems to cause the CPU to peg and startup gets stuck at "loading libraries" : https://github.com/itzg/docker-minecraft-server/issues/482

@TimoMeijer feel free to undo that conditional as you put the real Spigot log4j fix in there.

**Comment by Sylensky** [comment]
Sorry for my very late reply and thanks for investigating that issue.

**Comment by itzg** [comment]
@Sylensky did that latest image fix the color/chat code logging for you?

**Comment by Sylensky** [comment]
@itzg i haven't tested yet since they are more or less in production. I will make a new pull and test them the following days.

**Comment by Sylensky** [comment]
@itzg I pulled the latest image and it works now as intended. Thanks.

**Comment by Sylensky** [comment]
Sorry i have to reopen that issue. I pulled the latest image and it seem to appear that some prefixes work and some are still greyed out. 
Also i am not sure but with the latest image the container always wants to download the latest paper version of the server instead of using the one that is currently in.

**Comment by itzg** [comment]
Thanks for the update. Yesterday I was already thinking some logic disappeared in that area. I’ll look into this.

**Comment by itzg** [comment]
Found the issue, I broke it in 56c2f0b4661142ae992e0e24035d0d80c08e0276 . The latest pushed image now includes the proper logic to exclude the logging config for TYPE=PAPER.

As for the re-download observation, I wasn't able to recreate that. Can you provide some logs from when it does that?

**Comment by Sylensky** [comment]
I just removed the freshly download jar and let the container start again. And it is downloading the specific jar again but adds "-latest" to it. 

[init] Resolved version given 1.15.1 into 1.15.1
[init] Resolving type given PAPER
[init] Downloading Paper 1.15.1 (build latest) from https://papermc.io/api/v1/paper/1.15.1/latest/download ...
[init] server.properties already created, skipping
[init] log4j2.xml already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 10G and max to 10G
[init] Starting the Minecraft server...

But the old jar still remains in it and isn't being used.

For the log prefixes i will comment later on when i can pull all images again.

**Comment by itzg** [comment]
The inclusion of `-latest` is a new behavior and expected. That allows for picking off specific, previous build of the paper installer.

**Comment by Sylensky** [comment]
Oh. When did this change? i thought it would be a bug since it never used behave like that.

**Comment by itzg** [comment]
It was very recent https://github.com/itzg/docker-minecraft-server/pull/503

**Comment by Sylensky** [comment]
thanks alot. Maybe i should look into it more often.

**Comment by Sylensky** [comment]
Freshly pulled the latest images and all works as intended. Thanks again.
