### ISSUE TITLE
Docker log not working

### ISSUE THREAD

**Issue by Sander0542** [itzg/docker-minecraft-server#478]
## Information

When I access the log of the docker container it is not showing the console output anymore. Before I could see all the server logs there, but now it only shows the setup. I am running this docker on unRAID.

## Server Specs

- OS: unRAID 6.8.3
- CPU: AMD Ryzen 5 3600
- RAM: 32 GB DDR4
- SSD: Intel 660p

## Screenshot

![image](https://user-images.githubusercontent.com/11409610/78278896-006c0c00-7517-11ea-8477-e2dfd203c9b8.png)

**Comment by itzg** [comment]
Can you provide the `docker run` or equivalent to show how this container is configured?

**Comment by Sander0542** [comment]
This is what unRAID does for the run

`docker run -d --name='minecraft' --net='bridge' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'TYPE'='SPIGOT' -e 'VERSION'='1.15.2' -e 'EULA'='True' -p '25565:25565/tcp' -p '8123:8123/tcp' -v '/mnt/user/appdata/minecraft/':'/data':'rw' 'itzg/minecraft-server'`

Port 8123 is for the Dynmap

**Comment by itzg** [comment]
I was able to recreate the same problem; however, it seems to be a bug in Spigot since it seems to be stuck in a CPU busy state. Using the Java 13 image label fixed it though: `itzg/minecraft-server:adopt13`

**Comment by itzg** [comment]
I'm also not sure why https://getbukkit.org/ seems to be provided an outdated version of Spigot 1.15.2. Maybe the Java 8 bug will go away once getbukkit updates their copy.

**Comment by Sander0542** [comment]
I tried the adpot13 tag. It works, thanks!

![image](https://user-images.githubusercontent.com/11409610/78382543-54d6c080-75d7-11ea-91e5-19822ebdc4d7.png)
