### ISSUE TITLE
Error: Invalid or corrupt jarfile spigot_server-1.8.jar

### ISSUE THREAD

**Issue by mootras** [itzg/docker-minecraft-server#479]
On ubuntu I did:
`docker run -d -p 25565:25565 --name mc -e TYPE=SPIGOT -e VERSION=1.8 -e EULA=TRUE`

In interactive mode I see:

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    7 1000     1000          4096 Apr  3 01:28 /data'
[init] Resolved version given 1.8 into 1.8
[init] Resolving type given SPIGOT
[init] server.properties already created, skipping
[init] log4j2.xml already created, skipping
[init] Checking for JSON files.
[init] Copying any mods over...
[init] Copying any Bukkit plugins over...
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
**Error: Invalid or corrupt jarfile spigot_server-1.8.jar
2020/04/03 01:29:05 Done**

**Comment by itzg** [comment]
You seem to be running a new image, but my output showed more detail:

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Apr  3 19:53 /data'
[init] Resolved version given 1.8 into 1.8
[init] Resolving type given SPIGOT
[init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.8.jar ...

ERROR: failed to download from https://cdn.getbukkit.org/spigot/spigot-1.8.jar
       Visit https://getbukkit.org/download/spigot to lookup the
       exact version, such as 1.4.6-R0.4-SNAPSHOT or 1.8-R0.1-SNAPSHOT-LATEST
```

For 1.8, the example in the error message is actually from https://getbukkit.org/get/WAH0jXqYA2s3Gzzg3toWHG1R3lHNCNZY
