### ISSUE TITLE
[Suggestion] Unraid compatibility 

### ISSUE THREAD

**Issue by Jadiction** [itzg/docker-minecraft-server#481]
I'm unsure what it takes for Unraid to recognize a docker as "proper", but for some reason, Unraid doesn't see the docker well.

It shows no image, constantly shows an update (even when freshly ran), and has no options to edit parameters that other dockers provide.

![image](https://user-images.githubusercontent.com/8557785/78463905-663bcd80-76a8-11ea-93fc-0834a8938d87.png)
 
Here you can see the no options for editing:
![image](https://user-images.githubusercontent.com/8557785/78463942-d0ed0900-76a8-11ea-877e-b29722c5da7f.png)

Here is what other dockers show:
![image](https://user-images.githubusercontent.com/8557785/78463930-bdda3900-76a8-11ea-931b-518281cf875c.png)

When updating you see that a configuration was not found:
![image](https://user-images.githubusercontent.com/8557785/78463952-fc6ff380-76a8-11ea-8057-064c4c6f6987.png)

**Comment by itzg** [comment]
I went searching for Unraid documentation on this issue and have so far only found general reports of the same issue, such as

https://forums.unraid.net/topic/77869-docker-containers-always-update-ready/

**Comment by eihns** [comment]
unraid is widley used to run dockers. So a integration would be awesome.

I guess you need to add a template for unraid to "their appstore".

https://forums.unraid.net/topic/38582-plug-in-community-applications/

https://forums.unraid.net/topic/87144-ca-application-policies-notes/

https://github.com/Squidly271/Community-Applications-Moderators

If you have time for it, it would be really nice, there is currently no really working minecraft container, so that would be great.

(its still usable without integration, but not that nice... :P)

**Comment by itzg** [comment]
Thanks @eihns that lead me to find this specific comment from Squid (who apparently is the gatekeeper for the "community" applications). I might need you and/or other unraid users to be my proxy with submitting the "template xml" mentioned

https://forums.unraid.net/topic/57181-docker-faq/#comment-566084

I can create an empty github repo and invite you as a collaborator, if that helps.

**Comment by eihns** [comment]
Im not sure if that is allowed. 

> Publishing to CA
> 
> - Create a GitHub repository and upload the XML(s)
> - Drop myself (squid)  a PM asking for it to be published with a link to the github repo.
> - I'm going to odds on reply first and then insist you create a <Support> thread.  Just create it anywhere (as you won't be able to create in the docker Containers) and a moderator will move it.  Update the XML with the support link.  I will also insist on Categories being set.  
> - I do a quick check on the xml(s) and then add it to CA.  If there are no major problems, within 2 hours all users of CA will have access to it under normal circumstances.
> - Time permitting after its available to all users of CA, I will update the Repositories thread
> 
>  
> 
> Note:  After you have a repository added, I do not need to know about any new xml's being added.  CA (and more to the point the  appfeed) will handle all changes to the xml's automatically every 2 hours.
> 

If you want i could post it for you, but i guess it would be better if you create a account there, its a friendly community... besides the account on the forum, the rest you can handle automatic via github, it seems...

**Comment by itzg** [comment]
Since I don’t have unraid, mainly I was concerned about creating and/or verifying the xml the instructions say to provide.

**Comment by eihns** [comment]
Its very easy. In the end it has to look like this, ?!
```
  {
    "name":  "linuxserver's Repository",
    "url":  "https://github.com/linuxserver/docker-templates",
    "forum":  "http://lime-technology.com/forum/index.php?topic=42092.0",
    "web":  "https://www.linuxserver.io/"
  },

--->

<?xml version="1.0" encoding="UTF-8"?>
<Container version="2">
  <TemplateURL>https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/airsonic.xml</TemplateURL>
  <Beta>False</Beta>
  <Category>MediaApp:Music MediaServer:Music Status:Stable</Category>
  <Date>2017/12/30</Date>
  <Changes>
  [center][img width='300px' src='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_small.png'][/center]

  [center][font size=4] Change Log[/font][/center]
  </Changes>
  <Name>airsonic</Name>
  <Support>https://forums.unraid.net/topic/62456-support-linuxserverio-airsonic/</Support>
  <Description>Airsonic is a free, web-based media streamer, providing ubiqutious access to your music. Use it to share your music with friends, or to listen to your own music while at work. You can stream to multiple players simultaneously, for instance to one player in your kitchen and another in your living room.&#xD;
&#xD;
[br][br][b][u][span style='color: #E80000;']Configuration[/span][/u][/b][br]&#xD;
  [b]/music[/b] - Location of music.[br]&#xD;
  [b]/media[/b] - Location of other media.[br]&#xD;
  [b]/podcasts[/b] - Location of podcasts.[br]&#xD;
  [b]/playlists[/b] - Location for playlists storage.[br]&#xD;
  [b]CONTEXT_PATH[/b] for setting url-base in reverse proxy setups[br]&#xD;
  [b]JAVA_OPTS[/b] for setting Java options, default is 256MB starting RAM and Max RAM of 512MB[br]&#xD;
[br][b]Default user/pass is: admin/admin[/b]</Description>
  <Project>https://airsonic.github.io/</Project>
  <Overview>Airsonic is a free, web-based media streamer, providing ubiqutious access to your music. Use it to share your music with friends, or to listen to your own music while at work. You can stream to multiple players simultaneously, for instance to one player in your kitchen and another in your living room.</Overview>
  <Repository>linuxserver/airsonic</Repository>
  <Registry>https://hub.docker.com/r/linuxserver/airsonic/</Registry>
  <Network>bridge</Network>
  <BindTime>true</BindTime>
  <Privileged>false</Privileged>
  <WebUI>http://[IP]:[PORT:4040]/airsonic</WebUI>
  <Icon>https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/airsonic-logo.png</Icon>
  <Networking>
    <Mode>bridge</Mode>
    <Publish>
      <Port>
        <HostPort>4040</HostPort>
        <ContainerPort>4040</ContainerPort>
        <Protocol>tcp</Protocol>
      </Port>
    </Publish>
  </Networking>
  <Data>
    <Volume>
      <HostDir></HostDir>
      <ContainerDir>/music</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
    <Volume>
      <HostDir></HostDir>
      <ContainerDir>/playlists</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
    <Volume>
      <HostDir></HostDir>
      <ContainerDir>/podcasts</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
    <Volume>
      <HostDir></HostDir>
      <ContainerDir>/media</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
    <Volume>
      <HostDir></HostDir>
      <ContainerDir>/config</ContainerDir>
      <Mode>rw</Mode>
    </Volume>
  </Data>
  <Environment>
    <Variable>
      <Value>99</Value>
      <Name>PUID</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value>100</Value>
      <Name>PGID</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value>airsonic</Value>
      <Name>CONTEXT_PATH</Name>
      <Mode/>
    </Variable>
    <Variable>
      <Value>-Xms256m -Xmx512m</Value>
      <Name>JAVA_OPTS</Name>
      <Mode/>
    </Variable>
  </Environment>
  <Config Name="User ID" Target="PUID" Default="99" Mode="" Description="Set to Desired User ID" Type="Variable" Display="always" Required="true" Mask="false">99</Config>
  <Config Name="Group ID" Target="PGID" Default="100" Mode="" Description="Set to Desired Group ID" Type="Variable" Display="always" Required="true" Mask="false">100</Config>
  <Config Name="Music" Target="/music" Default="" Mode="rw" Description="Container Path: /music" Type="Path" Display="always" Required="true" Mask="false"/>
  <Config Name="Playlists" Target="/playlists" Default="" Mode="rw" Description="Container Path: /playlists" Type="Path" Display="always" Required="true" Mask="false"/>
  <Config Name="Podcasts" Target="/podcasts" Default="" Mode="rw" Description="Container Path: /podcasts" Type="Path" Display="always" Required="true" Mask="false"/>
  <Config Name="Media" Target="/media" Default="" Mode="rw" Description="Container Path: /media" Type="Path" Display="always" Required="true" Mask="false"/>
  <Config Name="CONTEXT_PATH" Target="CONTEXT_PATH" Default="airsonic" Mode="" Description="Container Variable: CONTEXT_PATH" Type="Variable" Display="always" Required="false" Mask="false">airsonic</Config>
  <Config Name="JAVA_OPTS" Target="JAVA_OPTS" Default="-Xms256m -Xmx512m" Mode="" Description="Container Variable: JAVA_OPTS" Type="Variable" Display="always" Required="false" Mask="false">-Xms256m -Xmx512m</Config>
  <Config Name="Port" Target="4040" Default="4040" Mode="tcp" Description="Container Port: 4040" Type="Port" Display="always" Required="true" Mask="false">4040</Config>
  <Config Name="AppData Config Path" Target="/config" Default="/mnt/cache/appdata/airsonic" Mode="rw" Description="Container Path: /config" Type="Path" Display="advanced-hide" Required="true" Mask="false">/mnt/cache/appdata/airsonic</Config>
<DonateText>Donations</DonateText>
<DonateLink>https://www.linuxserver.io/donate</DonateLink>
<DonateImg>https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/donate.png</DonateImg>
<BaseImage>lsiobase/ubuntu</BaseImage>
 </Container>
```

**Comment by eihns** [comment]
I also found this https://github.com/selfhosters/unRAID-CA-templates

**Comment by Jadiction** [comment]
I'm happy this is getting somewhere. I'm here if you need any testing.
I'd go as far as to screen share on Discord and test the docker in front of you if that helps.

**Comment by eihns** [comment]
Yes, please keep us updated on this. We help where we can. :)

**Comment by itzg** [comment]
@eihns thanks, that repo looks like a more doable to me

**Comment by Jadiction** [comment]
Any news on this? I'd love to see this happen. I don't often update this docker and with this addition, I think I would much more because it'd be as simple as Unraid showing there's an update and I can effortlessly click an update button.

I'm definitely still willing to help test this anyway I can.

**Comment by eihns** [comment]
As far as i know there is no difference in updates. If something changes you have to manually edit your docker anyways.

Real benefit is only for new users.

**Comment by Jadiction** [comment]
Updates are different with compatibility.
1. You'll always know when your app is up to date (and keep it up to date)
2. It's easier to update. Rather than having to open the terminal, run `docker stop <docker>`, `docker rm <docker>` and then copy/paste whichever ideal settings to `docker run`, you literally just click "apply update" and it does all that for you. 

Plus, yeah, installing would be easier without having to `docker run`.

**Comment by itzg** [comment]
I don’t understand why Unraid doesn’t do image update handling without all this extra, proprietary metadata. I can slightly understand variable descriptions (however it duplicates all the work put into the README), but everything else is available via the standard OCI image format and registry API.

Since I have no idea about the platform or file format, can I minimize my maintenance burden and just list one or two critical variables like EULA and TYPE?

**Comment by eihns** [comment]
> Updates are different with compatibility.
> 
> 1. You'll always know when your app is up to date (and keep it up to date)
> 2. It's easier to update. Rather than having to open the terminal, run `docker stop <docker>`, `docker rm <docker>` and then copy/paste whichever ideal settings to `docker run`, you literally just click "apply update" and it does all that for you.
> 
> Plus, yeah, installing would be easier without having to `docker run`.

Thats just wrong. You can normal update via CA auto update without a special unraid template. It makes no difference from update standpoint. 

"I don’t understand why Unraid doesn’t do image update handling without all this extra, proprietary metadata. I can slightly understand variable descriptions (however it duplicates all the work put into the README), but everything else is available via the standard OCI image format and registry API.

Since I have no idea about the platform or file format, can I minimize my maintenance burden and just list one or two critical variables like EULA and TYPE?"

At the end its about the nice to use GUI for new users. They INSTANT see whats needed to run the docker and can fill in the neccessary stuff without knowing anything about linux or docker or anything... 

I would really suggest you add all NEEDED like

-e EULA=TRUE -e ENABLE_AUTOPAUSE=TRUE -e VERSION=20w19a -e INIT_MEMORY=1G -e MAX_MEMORY=4G

**Comment by eihns** [comment]
Also, if you want, you could just install unraid in 5 min to a usb stick (theres a  free version) and just boot it on some random machine up, then oyu understand why we love it... xD

**Comment by itzg** [comment]
@eihns thanks, that's a great suggestion since it would solve my concerns about submitting something blind.

**Comment by Jadiction** [comment]
>You can normal update (and even) via CA auto update without a special unraid template.

You saw this, right? This happens when you try to update normally.
![image](https://user-images.githubusercontent.com/8557785/87255301-33e00000-c44f-11ea-873a-eb1fcf67636f.png)
As for CA, I don't have any plugins that mess with my docker updates (yes, I know CA Auto Update is available). So if it's not installed by default, I doubt many people have it, which is the main point of this.

**Comment by eihns** [comment]
You didnt "installed" this docker via community plugin.

**Comment by Jadiction** [comment]
> You didnt "installed" this docker via community plugin.

How did I not? I installed it just like anybody else would install it, through the docker command. Even running your command and it still doesn't allow updates, so you're mistaken with thinking that it can be updated.
![image](https://user-images.githubusercontent.com/8557785/87728189-221c9680-c788-11ea-89d9-ae2b689eb9ff.png)

**Comment by eihns** [comment]
yeah thats "wrong".

The error messages even indicates it...

<img width="1762" alt="minecraft1" src="https://user-images.githubusercontent.com/43281991/87816898-549dc080-c868-11ea-8532-27746077eee8.png">
<img width="1737" alt="minecraft2" src="https://user-images.githubusercontent.com/43281991/87816903-55ceed80-c868-11ea-99f0-a685e979b6ec.png">

**Comment by Jadiction** [comment]
It runs the same command as above... even look at your copy/paste of your console messages, lol.

Running the command rather than installing via Apps just allows for a faster way to define variables.

**Comment by eihns** [comment]
?????
You want a solution or just make stress? just try it yourself and it works. wtf are we even talking about

**Comment by jahanson** [comment]
I can help out with this, I'd like to see this on the CA store. Let me know what you need to do as far as submitting, testing, or maintaining something on the Unraid side.

**Comment by itzg** [comment]
@jahanson thank you so much for any and all help you can provide. I started working on a tool that will extract and itemize all of the environment variables that the image uses. If I can finish that tool and provide the variables list, then it would be fantastic if you ran with the Unraid specific bits.

**Comment by jahanson** [comment]
Awesome, looking forward to getting this ball rolling.

**Comment by jahanson** [comment]
Ok, the image is officially on the CA store for Unraid. These are the basic settings so far, but if any others are needed there is an "Extra parameters" field to put in the raw commandline "extras" like -e VERSION=1.7.9
![image](https://user-images.githubusercontent.com/1548511/92733251-163ef200-f33d-11ea-8d59-1a6a46621109.png)
In order to list it I had to list a folder on github with the XML in it. We can host it here, but it's currently at https://github.com/jahanson/unraid-docker-templates

**Comment by jahanson** [comment]
Also, is there an Icon that I should post for this? 
![image](https://user-images.githubusercontent.com/1548511/92733940-b85eda00-f33d-11ea-8a1c-e17cfddaf380.png)

**Comment by itzg** [comment]
That's fantastic @jahanson! You're very welcome to continue maintaining the Unraid file there. A brief section/paragraph in the README here can link over to your repo to maintain the traceability. 

As for the icon, I know I'm not too picky as long as the one chosen doesn't violate any license.

**Comment by eihns** [comment]
Nice, thanks, i found somethings i would consider changing (just a suggestion, highlighted is the important part i think):

1.   
<Name>itzg Minecraft **Server**</Name>

2.
<HostDir>/mnt/user/Minecraft/minecraft1</HostDir>

should be

<HostDir>/mnt/user/**appdata**/minecraft-server</HostDir>

3. 
<Config Name="Accept EULA" Target="EULA" Default="" Mode="" Description="**Set to** TRUE to accept EULA" Type="Variable" Display="always" Required="true" Mask="false"></Config>

Im not sure where to add the text which stands under the NAME (like the description) i would add there a link to https://github.com/itzg/docker-minecraft-server/blob/master/README.md with the tip that there are all extra parameters

**Comment by jahanson** [comment]
Thanks @eihns all good suggestions. I just sent a PM to request a support thread on the Unraid forums for any template support.

**Comment by EndreEndi** [comment]
Hi, I suggest to make a Discord Support server for this Repo, i for example i need with my unRAID docker, and i prefer to speak on an LIVE chat rather an "email like" one :)
And would be a good idea if you want to make polls for features or things like that if you will want to consider adding them :)

**Comment by itzg** [comment]
@EndreEndi are you asking me or @jahanson ? This docker image has a Discord server and I can add a channel for Unraid specific discussion, if needed.

**Comment by jahanson** [comment]
I see the confusion here, I just realized there was a Discord for your repo. It says chat, but I'm generally inclined to look for the Discord icon or the text "Join our Discord". I just joined it if you have any questions about the Unraid bits... as Veriwind

**Comment by itzg** [comment]
Good point. I think I will change the badge to "Join our Discord" or somehow make that more prominent.

**Comment by EndreEndi** [comment]
Thank you Guys, i didn't know if there's a discord server for the repo.

**Comment by arejaytee** [comment]
@jahanson This is no longer on the CA store, what's required to get it back on there?

**Comment by jahanson** [comment]
> @jahanson This is no longer on the CA store, what's required to get it back on there?

It's right here

![2021-07-02_08-55](https://user-images.githubusercontent.com/1548511/124285222-40b4a280-db3d-11eb-9a5e-cd44077a167f.png)

**Comment by arejaytee** [comment]
Appreciated, I was looking for itgz! DoH!
