### ISSUE TITLE
[Feature Request] Switch to Aikar's Flags

### ISSUE THREAD

**Issue by AugusDogus** [itzg/docker-minecraft-server#483]
For increased performance, using Aikar's flags is recommended. 
https://aikar.co/2018/07/02/tuning-the-jvm-g1gc-garbage-collector-flags-for-minecraft/

**Comment by itzg** [comment]
I’ll do some brief double checking with those and think about how to incorporate with user provided JVM options. Maybe if JVM_XX_OPTS isn’t set then it can use the Aikar flags.

**Comment by itzg** [comment]
This is now available in the latest image. I left it as an opt-in feature since, like the EULA, I would prefer that users of this image acknowledge they are using (and ideally donate to) Aikar's research.

https://github.com/itzg/docker-minecraft-server#enable-aikars-flags
