### ISSUE TITLE
Named volume "mc_java_forge:/data:rw" is used in service "minecraft_java_forge" but no declaration was found in the volumes section.

### ISSUE THREAD

**Issue by survivalbloke** [itzg/docker-minecraft-server#485]
I wish there were more documentation on the compose file.  I don't entirely understand what I would want to/need to change for my personal deployment.
Here is my compose:
`##--MINECRAFT JAVA FORGE--#########################################################
  minecraft_java_forge:
    image: itzg/minecraft-server
    ports:
      - 19500:25565
    volumes:
      - mc_java_forge:/data
    environment:
      - EULA=TRUE
      - ENABLE_RCON=true
      - RCON_PASSWORD=7uSsvCyeAdds
      - RCON_PORT=28016
      # enable env variable replacement
      - REPLACE_ENV_VARIABLES=TRUE
      # define an optional prefix for your env variables you want to replace
      - ENV_VARIABLE_PREFIX=CFG_
      # and here are the actual variables
      - CFG_DB_HOST=http://localhost:3306"
      - CFG_DB_NAME=minecraft
      - CFG_DB_PASSWORD=ug23u3bg39o-ogADSs
      - TYPE=FORGE
    restart: unless-stopped
  rcon:
    image: itzg/rcon
    ports:
      - 4326:4326
      - 4327:4327
    volumes:
      - rcon:/opt/rcon-web-admin/db`

When I run docker-compose up -d, I get `ERROR: Named volume "mc_java_forge:/data:rw" is used in service "minecraft_java_forge" but no declaration was found in the volumes section.`

Questions while I'm at it.  I understand the first 4 lines of environment settings, however I don't understand the rest.  Not sure why it is needed to replace the prefix with _CFG?  Also, in env settings, it specifies RCON port= 28016 but further down under the rcon: section, it lists different ports.

**Comment by itzg** [comment]
Sorry, this issue fell off my radar.

You picked off a fairly advanced example that definitely contained more variables than normally need to be set. I added a cleaner example that is more generally useful:

https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-forge.yml

In your particular case, your compose file was missing the volume declaration such as

https://github.com/itzg/docker-minecraft-server/blob/master/examples/docker-compose-forge.yml#L21-L23
