### ISSUE TITLE
/data working directory

### ISSUE THREAD

**Issue by rienafairefr** [itzg/docker-minecraft-server#492]
In the dockerfile, WORKDIR is set as /data, but in many places you use hardcoded /data/xxx paths, and in other places not (e.g. writing `eula.txt`). This bit me (in a derived image) when I got a "permission denied" because of EULA writing, not realising that the process I had started started somewhere else than /data. Might be good to either use /data/xxx paths everywhere or assume the working directory of the process is /data everywhere ?

**Comment by itzg** [comment]
`/data` is a very important assumption of all of the startup scripts. The `WORKDIR` is declared as a convenience and was not intended to ever be altered without being very sure about what you're doing. Can you clarify what you attempted that broke thing?

**Comment by rienafairefr** [comment]
I didn't really alter WORKDIR, didn't alter your image, just added stuff to it, starting `/start` differently inside, and in doing so, the `/start` process started with another working directory than `/data`. It's in [this repo](https://github.com/rienafairefr/minecraft-on-demand) if you're curious (which is starting the minecraft server under `supervisord`).

**Comment by itzg** [comment]
Gotcha. Very interesting solution you have there. 

So, you solved the issue here correct

https://github.com/rienafairefr/minecraft-on-demand/blob/master/src/supervisord.conf

I would prefer to avoid using relative directories throughout the startup scripts, so I’m not sure what else to do here.

**Comment by rienafairefr** [comment]
The error in my case first happend on the EULA validation, [here](https://github.com/itzg/docker-minecraft-server/blob/1c2a0c506ce06b1ed5c9e785aaadb46bbd050829/start-configuration#L22), where the scripts writes eula.txt with `> eula.txt`, which assumes the working directory is /data, so I guess a `> /data/eula.txt` would have avoided the issue. Probably other examples in the scripts, I didn't look everywhere

**Comment by itzg** [comment]
Ok, now I see what you mean. I’ll look through the scripts and see where I can be more consistent.

**Comment by VoronkoM** [comment]
Hi all,

Having the same problem I think. The minecraft server folder is not created in the 
`\\QNAP\Container\container-station-data\lib\docker\volumes\******\_data`
And upon booting the container I get message:

>[init] Please accept the Minecraft EULA at                                                                                                                   
>[init]   https://account.mojang.com/documents/minecraft_eula                                                                                                 
>[init] by adding the following immediately after 'docker run':                                                                                               
>[init]   -e EULA=TRUE    

The solution from @rienafairefr does not work as his is compiled for x86 I believe and I have ARM.

> _by "doesnt work" i mean that if I download his docker it wont run and I cant understand what he changed in the code :)_

Can someone explain what should I edit in the code and where exactly for it to create the directory or set the EULA=TRUE, please? :)

**Comment by itzg** [comment]
@VoronkoM I'm guessing your scenario is quite different than the original issue where a derived image was being built. You shouldn't need to edit any code but rather make sure you have set the environment variable `EULA` to "TRUE".

**Comment by VoronkoM** [comment]
> @VoronkoM I'm guessing your scenario is quite different than the original issue where a derived image was being built. You shouldn't need to edit any code but rather make sure you have set the environment variable `EULA` to "TRUE".

Then I might have completely misunderstood the described issue...
I understand the point of setting the variable to true but I can not find it anywhere. Its not in the container settings, there is no eula.txt file in the *docker volume*\_data (actually its completely empty) and the suggestion in the error to set the variable right after "docker run" is also not entirely clear to me. How do I access the command of running the container and add the "-e EULA=TRUE" to it? Any help in explaining how it should be run would be highly appreciated :)
Any suggestions?

**Comment by itzg** [comment]
@VoronkoM I haven't used QNAP, so from the docs https://www.qnap.com/en/how-to/tutorial/article/how-to-use-container-station I'm guessing you need to go into the "Advanced settings" on the "Create container" page to set
- environment variables
- volume mappings
- port mappings

**Comment by VoronkoM** [comment]
@itzg The list of variables available in the create container page is the same as listed in the configuration json files:
`"Env":["PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","LANG=en_US.UTF-8","LANGUAGE=en_US:en","LC_ALL=en_US.UTF-8","JAVA_VERSION=jdk-13.0.2+8","JAVA_HOME=/opt/java/openjdk","UID=1000","GID=1000","JVM_XX_OPTS=-XX:+UseG1GC","MEMORY=1G","TYPE=VANILLA","VERSION=LATEST","FORGEVERSION=RECOMMENDED","SPONGEBRANCH=STABLE","SPONGEVERSION=","FABRICVERSION=LATEST","LEVEL=world","PVP=true","DIFFICULTY=easy","ENABLE_RCON=true","RCON_PORT=25575","RCON_PASSWORD=minecraft","RESOURCE_PACK=","RESOURCE_PACK_SHA1=","LEVEL_TYPE=DEFAULT","GENERATOR_SETTINGS=","WORLD=","MODPACK=","MODS=","SERVER_PORT=25565","ONLINE_MODE=TRUE","CONSOLE=true","SERVER_NAME=Dedicated Server","REPLACE_ENV_VARIABLES=FALSE","ENV_VARIABLE_PREFIX=CFG_"]`
So there are no variables referring to EULA :(
Im completely lost at this point to why none of the files are created and where to set true to EULA.

**Comment by itzg** [comment]
That's a poor design on QNAP's part then. Does it not provide freeform fields to provide additional environment variables? Can you provide a screenshot of the variable configuration page?

**Comment by rienafairefr** [comment]
![image](https://user-images.githubusercontent.com/758517/79268619-5d62ad00-7e9b-11ea-9048-c244f186df73.png)
@VoronkoM  In this screen ("create container", then "advanced setttings"), you should add a EULA variable, with a value TRUE

**Comment by VoronkoM** [comment]
@itzg @rienafairefr 
Indeed, it is possible to add another environment var BUT only if there are no empty fields for any other vars. So first I had to fill "null" for things like `"RESOURCE_PACK="`, then it let me create an extra variable for EULA. After removing 'nulls' and launching it worked!
Thanks everyone!

**Comment by itzg** [comment]
Ah, that's good to know actually, because I have been considering removing all the pre-defined, but empty environment variables in the Dockerfile to help container managers like that. Seeing a concrete example confirms that was a good plan.

**Comment by itzg** [comment]
@VoronkoM FYI, the latest image now removes those empty environment variables, so I'm hoping that now simplifies the QNAP advanced settings area.
