### ISSUE TITLE
minecraft-server:raspberrypi server version out of date

### ISSUE THREAD

**Issue by yllekz** [itzg/docker-minecraft-server#494]
I successfully deployed minecraft-server:raspberrypi, but the official Minecraft client (1.15.2, latest release) refuses to connect due to it with the error stating: "Client out of date!".

If I check running processes, one of the CMD lines is referencing version 20w16a. Is this something that needs to be updated? I noticed this particular image has not been updated in 2 years

**Comment by yllekz** [comment]
My bad, apparently 20w16a is indeed the latest version, but Microsoft has not released the equivalent client version yet.

**Comment by itzg** [comment]
Please also try with the `armv7` since I made several improvements there and the `raspberrypi` tag is deprecated.
