### ISSUE TITLE
Running multiple Curseforge containers simultaneously 

### ISSUE THREAD

**Issue by jcoker85** [itzg/docker-minecraft-server#496]
Hi itzg,

Thanks for this fantastic container. Question for you - when running multiple containers, each with a Curseforge modpack (specifically Engineer's Life and Sevtech Ages together in my case), there is a problem connecting to each container when both are up. The issue is that when connecting to each container from the Minecraft client, you receive a message stating it requires additional mods, which turn out to be the mods installed on the other running container. 

A few specifics:

- The client and each container mod folders are OK and do not have these extra mods listed.
- If you only have one container running at a time there is no issue. 
- I forwarded 25565 to 25564 in the docker run command and changed the ports in the server.properties file for one of the containers. 
- The client did connect and attempt to login before displaying the message. 

I have some theories on why this may have occurred but will wait for your insight first. I searched the documentation and issues here, perhaps this just isn't supported, but I couldn't find anything specifically addressing this topic.

Thanks!

**Comment by itzg** [comment]
You will need to bind two separate host-side ports (the left side of the port mapping), rather than changing the container port in server.properties.

For example, let's say Engineer's life will get port 25565 and Sevtech will get port 25566, the docker run for each would be like

```
docker run .... -p 25565:25565 --name engineers_life ....

docker run .... -p 25566:25565 --name sevtech ....
```

Then in the Minecraft client you'll connect with something like "localhost" and "localhost:25566" for each server instance. (Change `localhost` to the hostname where Docker is running.)

**Comment by jcoker85** [comment]
> I forwarded 25565 to 25564 in the docker run command and changed the ports in the server.properties file for one of the containers.

I tried what you suggested, but I believe my issue was also changing the port in server.properties when I should have left it alone. Let me check and will get back to you.

Thank you for the quick reply!

**Comment by jcoker85** [comment]
Thanks again - it was both the port change in server.properties and our lack of using the port in the client connection explicitly for the server with the changed port.

Closing as this was user error. 😄
