### ISSUE TITLE
[Sugestion] Add Magma Foundation as a server type

### ISSUE THREAD

**Issue by Panderine** [itzg/docker-minecraft-server#497]
I know I can pull my own server jar but It wold be great to have magma as an easy option as well. https://magmafoundation.org/

**Comment by itzg** [comment]
That looks feasible and thanks for making me aware of this new server type. Forge + Bukkit/Spigot + Paper really does it all.

**Comment by Fireant456** [comment]
Any luck finding time to look into this enhancement? I am attempting to run Magma as a Custom Jar but I end up just hanging the container and this is the point in the logs that hangs. 
```
[16:44:52] [main/INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[16:44:57] [main/INFO]: 2 patches loaded!
[16:44:57] [main/INFO]: CoreProtect [Changes Material to Magma's getBlockMaterial that has modded block materials ] loaded
[16:44:57] [main/INFO]: dynmap [Remaps BukkitVersionHelperCB and BukkitVersionHelperGeneric to support Magma version] loaded
[16:44:58] [Server thread/INFO]: Searching /data/./mods for mods```

**Comment by kingdevnl** [comment]
Hi, I'm one of the authors of magma.
It should run fine under docker (Iv'e been running it under docker for quite a while)
What docker image to you use?

**Comment by kingdevnl** [comment]
O and here is a link to always fetch the last jar of Magma

https://api.magmafoundation.org/api/resources/Magma/1.12.2/stable/latest/download

**Comment by Fireant456** [comment]
It seems if I use the CUSTOM_JAR environment variable it works fine, just seems the minecraft server console is not outputting as you would expect. not a huge deal but nice to have that output for logging and debug purposes.

**Comment by Fireant456** [comment]
It appears trying to add FTB Ultimate breaks in docker as well as on plain Magma on Windows.

**Comment by Panderine** [comment]
It works with custom jar. Problem is that the 1.12.2 technical mods I'm using are not so happy with Magma. Maybe you have one of those mods. I'm having issues with opencomputer's for example. Also with some spigot plugins like skinrestorer :(

**Comment by itzg** [comment]
Thanks @kingdevnl, that API approach will be very good to use for this image.

**Comment by itzg** [comment]
The latest image now supports `-e TYPE=MAGMA`:

https://github.com/itzg/docker-minecraft-server#running-a-magma-server

**Comment by Fireant456** [comment]
Ya I got it to boot with Magma normally, I am having the issue with getting FTB Ultimate to work on Magma in this container. On Windows it works fine.

https://mclo.gs/jteLOva
http://paste.fyi/NcZbIXLnw

**Comment by Fireant456** [comment]
Got it working! was a weird permission bug, thanks for your help :)

**Comment by Fireant456** [comment]
@itzg will the `CF_SERVER_MOD` env variable work as will with `TYPE=MAGMA`?

**Comment by itzg** [comment]
It won't as-is and not sure if they can naturally be mixed since CurseForge modpacks provide their own Forge server jar. For now you could manually transplant the mods from a modpack into `/data/mods` or attach via `/mods`.

**Comment by Fireant456** [comment]
@itzg maybe you can continue helping me on #525 to find a solution, there are a couple of things I am unsure if I am configuring correctly and might be causing my issue.
