### ISSUE TITLE
[Server thread/WARN]: Forge Mod Loader detected missing registry entries.

### ISSUE THREAD

**Issue by eihns** [itzg/docker-minecraft-server#500]
Hey,
thanks for that great docker.

I had run a local minecraft server (via start LAN) and now i want to place it as server.

Used same MC and forge version ofc.

But the problem is this:
[14:17:04] [Server thread/WARN]: Forge Mod Loader detected missing registry entries.

There are 5 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:entities:
cfm:mirror
Missing minecraft:soundevents:
rftools:elevator_loop
rftools:elevator_stop
rftools:elevator_start
rftools:scan

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

The server wont start without an anser.

Ofc i tried sending it via 

> root@Unraid-Server:# docker exec -i MineCraftModded rcon-cli
> 2020/04/19 14:07:50 Failed to connect to RCON serverdial tcp 127.0.0.1:25575: connect: connection refused
> root@Unraid-Server:# docker exec -i MineCraftModded rcon-cli
> 2020/04/19 14:07:53 Failed to connect to RCON serverdial tcp 127.0.0.1:25575: connect: connection refused
> root@Unraid-Server:# docker exec -i MineCraftModded rcon-cli
> 2020/04/19 14:09:54 Failed to connect to RCON serverdial tcp 127.0.0.1:25575: connect: connection refused
> root@Unraid-Server:# docker exec -i MineCraftModded /fml confirm

But, i guess, since the server isnt startet properly, i cant connect to the rcon? Right?

So how i can give the confirm command to it? I also dont know a way to add "-Dfml.queryResult=confirm" to the minecraft start, bc i guess -e wont do that?

attach only seem to give me the log, but i cant enter commands... :(

Thanks for any help!

**Comment by itzg** [comment]
Just to confirm, you placed all the same mods you were using via the client into the container's `/data/mods` directory? But yes, it seems to fail to connect rcon since it didn't fully start up.

**Comment by eihns** [comment]
yes, ofc, i just removed optifine, since its a client only mod.

**Comment by eihns** [comment]
Okay, i found solution, many thanks.

https://github.com/itzg/docker-minecraft-server/issues/465

didnt found it initialy via search...
