### ISSUE TITLE
Connection issues using router IP

### ISSUE THREAD

**Issue by leonkrischer** [itzg/docker-minecraft-server#502]
Hello,
I'm running a vanilla minecraft server on my personal NAS at home and I'm getting a quite annoying issue for which I can't find any solution. I'm currently running Rockstor, and installed the container using the rocks-on feature of the distro. 
Installation was easy and quick. However: I'm only able to access my MC server from the local network. I set up NAT forwarding and even opened ports in my routers firewall, but I keep getting a "timed out" error when trying to connect using my routers IP. Connecting with the local IP of the MC server works just fine.  
Iptables and Ifconfig shows up the servers activity, and it doesn't seem like anything is wrong there. I looked through the internet for a solution but couldn't find one. Maybe you will give me one?
Thanks a lot

**Comment by itzg** [comment]
It sounds like a problem I had using the router provided by my internet provider. I finally discovered the NAT on their router didn't support [hairpin routing](https://en.wikipedia.org/wiki/Hairpinning). When removing the ISP's router and using my original router I was able to access my server by both its LAN IP address and my public IP address.

**Comment by leonkrischer** [comment]
Don't think that's the issue. I already hosted a MC server on another machine under Ubuntu without having any issues using the routers ip to connect to the server inside the local network. 
I also have a VPN running on my NAS which is accessible with devices logged in the local network but using the server ip to connect. (the VPN isn't installed in a Docker container).

**Comment by itzg** [comment]
I am going to close this since I'm afraid this issue is beyond the scope of this container/repo.
