### ISSUE TITLE
exec user process caused "exec format error"

### ISSUE THREAD

**Issue by tmonfiletto** [itzg/docker-minecraft-server#505]
used your docker compose example on my Raspberry Pi4 running Ubuntu 19.10.01 Arm64
The log file just repeats over and over

standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"

How can I help you troubleshoot?
Docker version 19.03.8,
Linux dockerhost 5.3.0-1014-raspi2 #16-Ubuntu SMP Tue Nov 26 11:18:23 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

**Comment by itzg** [comment]
Which example was it? I might need to fix it. The image tag that works on raspberrypi is `itzg/minecraft-server:armv7`

**Comment by tmonfiletto** [comment]
I guess that was my bad, I changed it to :multiarch and it started, Next question, what can connect to this? I tried both my ipad and windows 10 machine on port 25565 and it says it can't find it.

**Comment by itzg** [comment]
Java edition clients will be able to connect. IPad and the Windows 10 editions of Minecraft only connect to Bedrock server (https://github.com/itzg/docker-minecraft-bedrock-server) and unfortunately Mojang only provides an x86 binary for that.

**Comment by tmonfiletto** [comment]
Oh dang, Well thanks anyway! I don't have a persistent x86 machine at home, I guess thats why I never set it up!
