### ISSUE TITLE
Container not detecting /stop

### ISSUE THREAD

**Issue by xorinzor** [itzg/docker-minecraft-server#507]
When I run `/stop` from my forge server the container will keep running (the server itself will stop completely).
I have to use the `docker attach` command and press CTRL + C in order to get the container to stop.

I'm using UnRaid with the `--restart unless-stopped` run parameter, which right now doesn't work since the container never stops unless I manually trigger it. 

Not sure if this would happen with crashes either since I haven't had any, but apparently the current entrypoint script isn't aware of when the executable has exited.

**Comment by itzg** [comment]
> When I run /stop from my forge server

Can you clarify how you run this? From the Minecraft client? Via a docker attach?

If you have stdin and tty enabled you could have used `docker attach` and the `stop` command there. You can also use the included `rcon-cli` to send a stop command:

https://github.com/itzg/docker-minecraft-server#interacting-with-the-server

**Comment by xorinzor** [comment]
Yes as an OP from within the game, idea being if I made a quick config change while playing (for example: discovering a recipe that doesn't quite work, etc.) that I can quickly restart the server that way.

But once the server is stopped, it will show the following log output:
```
[13:03:21] [Server thread/INFO]: Saving worlds
[13:03:21] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[13:03:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[13:03:22] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
```

And then does nothing, until I do `docker attach` and press CTRL + C, after which the docker container will automatically restart.

**Comment by itzg** [comment]
I am unable to recreate the issue, so it appears to be something influenced by Unraid.

I created a fresh server using:
```
docker run -it --rm -e EULA=TRUE -e TYPE=FORGE -e OPS=itzg -p 25565:25565 itzg/minecraft-server
```

Connected with a fresh Forge client installation and issued the `/stop` command. Server logs showed:

```
[16:11:12] [Server thread/INFO]: §7§o[itzg: Stopping the server]§r
[16:11:12] [Server thread/INFO]: Stopping server
[16:11:12] [Server thread/INFO]: Saving players
[16:11:12] [Server thread/INFO]: itzg lost connection: Server closed
[16:11:12] [Server thread/INFO]: §eitzg left the game§r
[16:11:12] [Server thread/INFO]: Saving worlds
[16:11:12] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[16:11:13] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[16:11:13] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
2020-04-25T16:11:14.161Z        INFO    mc-server-runner        Done
```

**Comment by xorinzor** [comment]
The log line `INFO    mc-server-runner        Done` has never appeared in the containers log file from what I can tell.

Before this docker container, I used a different one, which didn't use a wrapper (and thus whenever the container got stopped, it would force-shutdown the server, which is why I switched). But whenever I'd run `/stop` on that container, it would stop the container too, and automatically restart it. Therefor I have a feeling it might be related to the wrapper.

Unfortunately my Go skills are slim to none, I can roughly make out what the wrapper is doing, but that's about it. Is it looking for an exit code, or some kind of signal? Is this something I could check for / debug?

**Comment by itzg** [comment]
Yeah, I'm really confused about why your container is not stopping all the way since all the wrapper is doing at that point is waiting for the child process to end at

https://github.com/itzg/mc-server-runner/blob/7675731c4e9c9a98b9ffdfff1e2c4020c8f3df46/main.go#L126

which is https://golang.org/pkg/os/exec/#Cmd.Wait

With that the context is cancelled and the wrapper handles that and exits here
https://github.com/itzg/mc-server-runner/blob/7675731c4e9c9a98b9ffdfff1e2c4020c8f3df46/main.go#L154-L156

which is what you see in my logs.

**Comment by itzg** [comment]
...when it gets into that state, can you `docker exec` into the container and do a `ps -ef`. I'm curious to see the state the java process at that point.

**Comment by xorinzor** [comment]
So I had a power outage here causing my Unraid server to restart, after which I tried what you asked.

This is the output:
 ```
    1 minecraf  0:00 mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms1G -Xmx1G -Dlog4j.configurationFile=/data/log4j2.xml -jar forge-1.15.2-31.1.47.jar
   45 minecraf 12:13 java -XX:+UseG1GC -Xms1G -Xmx1G -Dlog4j.configurationFile=/data/log4j2.xml -jar forge-1.15.2-31.1.47.jar
  390 root      0:00 sh
  396 root      0:00 ps -ef
```

Oddly enough, after a minute or so my terminal session got closed and the `mc-server-runner Done` log line appeared. Not sure what changed, I had the exact same situation before, and after 10 minutes nothing had happened until I used the CTRL+C trick.

I guess it's solved for now, albeit a complete mystery to me what would've caused it.
Thanks for your help

**Comment by xorinzor** [comment]
Just happened again (and is still happening).

Managed to dump some information from the Java server as well, unfortunately it doesn't really tell me much what's going on.

https://pastebin.com/7QMf1bs0

The fact however that you managed to run a clean server without reproducing the problem makes me think it might actually be the server, or a mod causing this issue. It wouldn't really make sense for it to be the docker container or the wrapper at this stage in debugging.

**Comment by itzg** [comment]
Good thinking! It did make a lot more sense that a particular mod would interfere and would explain why a clean forge server stopped fine for me.
