### ISSUE TITLE
Could not create the Java Virtual Machine

### ISSUE THREAD

**Issue by GreedHub** [itzg/docker-minecraft-server#508]
Hi, I'm having a memory asignation issue when running the server:

Just to be clear, server has more than 60GB of free RAM

```
[init] Setting initial memory to 16G  and max to 16G 

[init] Starting the Minecraft server...

Invalid initial heap size: -Xms16G 

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.

2020-04-25T21:43:28.855Z	INFO	mc-server-runner	Done

```

Run command:

`docker run -d -v /mnt/data_drive_1/srv/minecraft/spigot_latest/:/data --restart=always -e VERSION=1.15.2 -e MEMORY=16G  -e DIFFICULTY=hard -e ONLINE_MODE=FALSE -e TYPE=SPIGOT -p 25566:25565 -e EULA=TRUE --name spigot_latest itzg/minecraft-server
`

Output of `docker run --entrypoint java itzg/minecraft-server -version` :

```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

It worked before, but now I'm upgrading the server with a fresh install and having this issue.

Thnx in advance!

**Comment by itzg** [comment]
Can you see if there's a certain memory setting where it seems to break? Like 16G, 8G?

**Comment by GreedHub** [comment]
Same with 8G and 4G:

```
[init] Setting initial memory to 8G  and max to 8G 

[init] Starting the Minecraft server...

Invalid initial heap size: -Xms8G 

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.
```

```
[init] Setting initial memory to 4G  and max to 4G 

[init] Starting the Minecraft server...

Invalid initial heap size: -Xms4G 

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.
```

Seems to be working with `openj9` tag

**Comment by GreedHub** [comment]
It also works without the memory envirorment variable

**Comment by itzg** [comment]
Quite strange. Can you add a `-e DEBUG_EXEC=true` and provide that output? Maybe the startup script is coming up with an incompatible set of arguments.

**Comment by Fireant456** [comment]
I get the same thing, Tried bumping up to 4G from 1G
```
[init] Setting initial memory to 2G and max to 4G
[init] Starting the Minecraft server...
+ exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms2G -Xmx4G -Dlog4j.configurationFile=/data/log4j2.xml -jar paper_server-1.12.2-latest.jar
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000006c0000000, 2147483648, 0) failed; error='Out of memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
# Can not save log file, dump to screen..
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   The process is running with CompressedOops enabled, and the Java Heap may be blocking the growth of the native heap
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2773), pid=24, tid=0x00007f1ff9029b10
#
# JRE version:  (8.0_212-b04) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.12.0
# Distribution: Custom build (Sat May  4 17:33:35 UTC 2019)
# Core dump written. Default location: /data/core or core.24```

**Comment by Fireant456** [comment]
This started happening around the last update or two. had a handful of servers that I am running with different memory settings and they all work as set before the update but changing them causes them not to boot.

**Comment by itzg** [comment]
@Fireant456 can you pull the latest image and add `-e DEBUG_MEMORY=TRUE`. With that please provide the output from the logs that looks like the following:

```
[init] Memory usage and availability (in MB)
Linux 8f0f4552edf0 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 Linux
             total       used       free     shared    buffers     cached
Mem:         12783       5321       7462          5        608       3172
-/+ buffers/cache:       1540      11243
Swap:         4096          0       4096
[init] Starting the Minecraft server...
+ exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms1G -Xmx1G -Dlog4j.configurationFile=/data/log4j2.xml -jar paper_server-1.12.2-latest.jar
```

**Comment by Fireant456** [comment]
I tried that and the Debug showed that all the memory was being used.

shut down all my servers in the network and started them back up one by one and they seem to be leaving some ram leftover. once there was the available ram, I was able to create more or up the amount on existing containers.

**Comment by itzg** [comment]
@GreedHub can you try the same, adding `-e DEBUG_MEMORY=TRUE` to the container and seeing what that reports?

**Comment by GreedHub** [comment]
Sorry fo the delay, busy week

With `-e DEBUG_MEMORY=TRUE` seems to be working

With `-e DEBUG_EXEC=true`

```
2020-04-29T14:07:29.653Z	INFO	mc-server-runner	Done

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsrwx    7 1000     1000          4096 Apr 29 14:07 /data'

[init] Resolved version given 1.12.2 into 1.12.2

[init] Resolving type given FORGE

[init] Checking Forge version information.

[init] server.properties already created, skipping

[init] log4j2.xml already created, skipping

[init] Checking for JSON files.

[init] Setting initial memory to 4G  and max to 4G 

[init] Starting the Minecraft server...

+ exec mc-server-runner --stop-duration 60s java -XX:+UseG1GC -Xms4G  -Xmx4G  -Dlog4j.configurationFile=/data/log4j2.xml -jar forge-1.12.2-14.23.5.2825-universal.jar

Invalid initial heap size: -Xms4G 

Error: Could not create the Java Virtual Machine.

Error: A fatal exception has occurred. Program will exit.

2020-04-29T14:07:33.906Z	INFO	mc-server-runner	Done
```

**Comment by itzg** [comment]
@GreedHub hmm, `-e DEBUG_MEMORY=TRUE` shouldn't actually "fix" anything, but glad to hear it now works. Whenever you do encounter the problem again, you can re-open this issue and provide the output of the "Memory usage and availability" section of the startup logs.

**Comment by GreedHub** [comment]
I know `-e DEBUG_MEMORY=TRUE` should not fix anything, but its pretty weird, and it does somehow... If I create the container without it it keeps failing, but if I use it, the container works... I dont know if this shoud be closed

**Comment by jltml** [comment]
@itzg Hi! Sorry for commenting on an old issue — I'm having this exact same problem (on a Raspberry Pi 4 w/ 8gb of RAM) and I can't at all figure out what the issue is. Everything works up to `MAX_MEMORY: "2G"` (or slightly more if I set the value in `M`). When I run `docker stats mc`, it shows `LIMIT: 7.691GiB`, so presumably the issue is with the JVM. I'm pretty new to this, so I could very well be messing something up that's obvious. And I know it's probably outside your prevue anyway, since it's the JVM, but I just thought I'd ask anyway.

This is the error message with `DEBUG_MEMORY: "TRUE"`:
```
mc                  | [init] Setting initial memory to 1000m and max to 3000m
mc                  | [init] Memory usage and availability (in MB)
mc                  | Linux 018ba993f918 5.4.83-v7l+ #1379 SMP Mon Dec 14 13:11:54 GMT 2020 armv7l armv7l armv7l GNU/Linux
mc                  |               total        used        free      shared  buff/cache   available
mc                  | Mem:           7875         162        6291           8        1422        7479
mc                  | Swap:            99           0          99
mc                  | [init] Starting the Minecraft server...
mc                  | Error occurred during initialization of VM
mc                  | Could not reserve enough space for 3072000KB object heap
mc                  | 2021-03-11T21:08:48.800Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
mc                  | 2021-03-11T21:08:48.800Z	INFO	mc-server-runner	Done
```

And just to be safe, here's my `docker-compose.yml` (the version that works):
```yaml
minecraft-server:
  image: itzg/minecraft-server:multiarch-latest

  ports:
    - "25565:25565"

  environment:
    EULA: "TRUE"
    # MEMORY: "4G"
    INIT_MEMORY: "1G"
    MAX_MEMORY: "2G"
    DEBUG_MEMORY: "TRUE"

  tty: true
  stdin_open: true
  restart: always
  container_name: mc
  privileged: true
```

Regardless of all of this, thanks so much for the incredible image!

**Comment by itzg** [comment]
@jltml for future reference please open a new issue.

As for your scenario, I know Raspbian by default is a 32-bit OS, so you might be bumping into

https://en.wikipedia.org/wiki/2_GB_limit

**Comment by jltml** [comment]
@itzg Oh, sorry about that! I'm quite new to GitHub etc & I'm still figuring things out — I'll create new ones going forward.

And ah, that would make sense… I don't know how I was unaware of that! I'll try again with the 64-bit OS. Thanks so much!
