### ISSUE TITLE
unable to edit files

### ISSUE THREAD

**Issue by Frownwarrior** [itzg/docker-minecraft-server#509]
Hey First of all your guide is awesome. Thanky you very much for it. 
Now I'm running a MC Server in Docker on my OMV5. It works so far fine. 
My problem is, that when I connect to my MC folder via Windows explorer to edit my server files it allways gives me an error, that I have no rights (login and connected as admin) 
Is there a way how I can edit my server files? 
I want to change the RAM usage, enable flight and setting OPS.

Specially the RAM settings. I gave my docker installation 16G but the Java Server properties are still on there default 2G. 

Hier my Stack:

---
version: "2"
services:
  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraftFTB 
    network_mode: host
    environment:
      - PUID=998
      - PGID=100
      - EULA=TRUE
      - VERSION=SNAPSHOT
      - MEMORY=16G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - TYPE=CURSEFORGE
      - CF_SERVER_MOD=https://media.forgecdn.net/files/2731/545/FTBInfinityServer_3.1.0.zip
      - OPS=username,
    ports:
      - 25565:25565
    volumes:
      - /srv/dev-disk...Minecraft:/data
    restart: unless-stopped

**Comment by itzg** [comment]
Can you provide the first few lines of the container output, mainly the first one that looks like

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Apr 27 12:51 /data'
```

Otherwise, it sounds like this option would be better for the ongoing changes you would like the container to use:

https://github.com/itzg/docker-minecraft-server#server-configuration

**Comment by Frownwarrior** [comment]
Thanky you for your fast replay.

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwsr-x    6 1000     1000          4096 Apr 28 07:59 /data',
[init] Resolved version given SNAPSHOT into 20w17a,
[init] Resolving type given CURSEFORGE,
[init] Looking for Feed-The-Beast / CurseForge server modpack.,
~/FeedTheBeast ~,
/usr/bin/wget,
--2020-04-28 08:19:11--  https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/minecraft_server.1.7.10.jar,
Resolving s3.amazonaws.com... xxxxxx
Connecting to s3.amazonaws.com|xxxxx|:xxxx... connected.,
Length: 9605030 (9.2M) [application/octet-stream],
Saving to: 'minecraft_server.1.7.10.jar',
[init] Setting initial memory to 16G and max to 16G,
[init] Running FTB /data/FeedTheBeast/ServerStart.sh in /data/FeedTheBeast ...,
Starting server,
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=256M; support was removed in 8.0

```
It looks like the amount of RAM is set and still I dknpt see any useage over >2.5GB
I checked the OPS.JSON and my username is in it but in the ops.json file in the feedthebeast folder it is empty and i can not edit it. 

Everything works so good, but to be unable to enable flights and manage the server rigth as op in the game is getting annoying ^^'


(ps. sorry for my english, I use google translater for better understanding the subject)

**Comment by itzg** [comment]
Thanks for the information. I just noticed the PUID and PGID variables are not correct. They should be UID and GID:

https://github.com/itzg/docker-minecraft-server/blob/master/README.md#running-as-alternate-usergroup-id

I’m hoping that makes it work better.

**Comment by Frownwarrior** [comment]
What variables should they have ?
And am I'm writing the OPS usename right ? do I have to wirte some <> or "" first ?
> 
> PUID | 998
> -- | --
> PGID | 100
> EULA | TRUE
> VERSION | SNAPSHOT
> MEMORY | 16G
> ANNOUNCE_PLAYER_ACHIEVEMENTS | true
> TYPE | CURSEFORGE
> CF_SERVER_MOD | https://media.forgecdn.net/files/2731/545/FTBInfinityServer_3.1.0.zip
> OVERRIDE_SERVER_PROPERTIES | true
> ALLOW_FLIGHT | TRUE
> OPS | Frownwarrior,
> ENABLE_RCON | true
> RCON_PASSWORD | xxxx
> PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin
> LANG | C.UTF-8
> JAVA_HOME | /usr/lib/jvm/java-1.8-openjdk/jre
> JAVA_VERSION | 8u212
> JAVA_ALPINE_VERSION | 8.212.04-r0
> UID | 1000
> GID | 1000
> JVM_XX_OPTS | -XX:+UseG1GC
> FORGEVERSION | RECOMMENDED
> SPONGEBRANCH | STABLE
> SPONGEVERSION |  
> FABRICVERSION | LATEST
> LEVEL | world
> PVP | true
> DIFFICULTY | easy
> RCON_PORT | 25575
> LEVEL_TYPE | DEFAULT
> SERVER_PORT | 25565
> ONLINE_MODE | TRUE
> SERVER_NAME | Dedicated Server
> REPLACE_ENV_VARIABLES | FALSE
> ENV_VARIABLE_PREFIX | CFG_
> 
>

**Comment by itzg** [comment]
Here are the changes I would recommend:

Variable | Value | Notes
-- | -- | --
~PUID~ | ~998~ | Replace with UID
~PGID~ | ~100~ | Replace with PGID
OPS | Frownwarrior | Remove trailing comma
UID |  998 | Using previous value from PUID
GID | 100 | Using previous value from PGID
