### ISSUE TITLE
Unable to access configuration files through windows

### ISSUE THREAD

**Issue by tigger29900** [itzg/docker-minecraft-server#513]
Hi,

I have been trying to edit my configuration file/backup my world file and for some reason i am unable to find the files in the associated directories. Confirmed that i can restart the container without issue and it is looking at the correct world file but it does not seem to have mounted

Any way to find and backup the files?

P.S setup was so easy!

**Comment by itzg** [comment]
Can you provide the `docker run` you’re using and I’ll see if I can help locate that directory for you. 

Glad to hear it was easy to setup at least :)

**Comment by tigger29900** [comment]
{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "ArgsEscaped": true,
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": [],
        "Domainname": "",
        "Entrypoint": [
            "/start"
        ],
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin",
            "LANG=C.UTF-8",
            "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
            "JAVA_VERSION=8u212",
            "JAVA_ALPINE_VERSION=8.212.04-r0",
            "UID=1000",
            "GID=1000",
            "JVM_XX_OPTS=-XX:+UseG1GC",
            "MEMORY=1G",
            "TYPE=VANILLA",
            "VERSION=LATEST",
            "FORGEVERSION=RECOMMENDED",
            "SPONGEBRANCH=STABLE",
            "FABRICVERSION=LATEST",
            "LEVEL=world",
            "PVP=true",
            "DIFFICULTY=easy",
            "ENABLE_RCON=true",
            "RCON_PORT=25575",
            "RCON_PASSWORD=minecraft",
            "LEVEL_TYPE=DEFAULT",
            "SERVER_PORT=25565",
            "ONLINE_MODE=TRUE",
            "CONSOLE=true",
            "SERVER_NAME=Sean's Server",
            "REPLACE_ENV_VARIABLES=FALSE",
            "ENV_VARIABLE_PREFIX=CFG_",
            "EULA=TRUE",
            "SPONGEVERSION=",
            "RESOURCE_PACK=",
            "RESOURCE_PACK_SHA1=",
            "GENERATOR_SETTINGS=",
            "WORLD=",
            "MODPACK=",
            "MODS="
        ],
        "ExposedPorts": {
            "25565/tcp": {},
            "25565/udp": {},
            "25575/tcp": {}
        },
        "Healthcheck": {
            "StartPeriod": 60000000000,
            "Test": [
                "CMD-SHELL",
                "mc-monitor status --host localhost --port $SERVER_PORT"
            ]
        },
        "Hostname": "500c25ebff03",
        "Image": "itzg/minecraft-server:latest",
        "Labels": {
            "maintainer": "itzg"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": true,
        "User": "",
        "Volumes": {
            "/config": {},
            "/data": {},
            "/mods": {}
        },
        "WorkingDir": "/data"
    },
    "Created": "2020-03-16T23:03:33.336342515Z",
    "Driver": "overlay2",
    "ExecIDs": [
        "c3de7f96e8dd48f5e7069dac3ea1a9e788cbf3d45aa61a4d590dd28407b24e02"
    ],
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/3e9f70581e6bb5d265bab133aab3436b1fdca20f2aeaf93bed1283f9df8a65d4-init/diff:/var/lib/docker/overlay2/da6b017a57a9655b231a2160a292e1c366f3c515e105391d2d2df747296cef5f/diff:/var/lib/docker/overlay2/d261d5f5af447ba6531fbf04bca0e35595c937b34ff3a2e9f0dde168a1bc4fde/diff:/var/lib/docker/overlay2/e52b5537229f90c4fdcfb6961ad2e4449e400c26bc41a331130eb897cd05af1b/diff:/var/lib/docker/overlay2/93ffafb352db059a9443f4590ccd166dbdd316e32b5e11236225ca4cc9cab9b3/diff:/var/lib/docker/overlay2/cbbbf2e731024602cf8cdcabadfe088d49c04b1e01f7563f46e79399513eef69/diff:/var/lib/docker/overlay2/2e47eb5be99ade7d54ba570a32d82dde4b78b34145ed05e2ee8cd39bde0fbf62/diff:/var/lib/docker/overlay2/d303b5ab441f5e6ef523775ff6193fc65a10b5b3a2a5423b99ddbcb10e5a58f7/diff:/var/lib/docker/overlay2/17f9d2da356222684bcfd8d87b771ef73d2eda182f7ffc5fe423aa5e60a01f37/diff:/var/lib/docker/overlay2/325bb49b5cce13da1f2168f3f892d413bab56cd386299a3330a794e790c367d3/diff:/var/lib/docker/overlay2/ae8a2245e1a4aad93908b65e86080fdded93995fd875cad7fafa7a6f13db1f94/diff:/var/lib/docker/overlay2/4028b0ada234b02c6479cdaba9fcc8593418fb1e30878743f4fb06b097ee60bc/diff:/var/lib/docker/overlay2/3157a87c0d15daed96c3ba9fcb2573577431b41c80bce38f34ab243ed5d946bd/diff:/var/lib/docker/overlay2/adffaf851cf984453734234a7193cb3fd5cf154c8a7fe944bf46655c1a0a00e7/diff:/var/lib/docker/overlay2/f6427e560841ebc66ec3f1374ec08353df3d5fe14cbb55cdcd148fcfa8678c88/diff:/var/lib/docker/overlay2/ae160377fff06c8e02dea6cb075ae3d047dc55be15e4547d3399f9727fb79444/diff:/var/lib/docker/overlay2/3c74c754396c6eca933756f5a9f9fe744110b474cd2be385ef056b57e66b0ef4/diff",
            "MergedDir": "/var/lib/docker/overlay2/3e9f70581e6bb5d265bab133aab3436b1fdca20f2aeaf93bed1283f9df8a65d4/merged",
            "UpperDir": "/var/lib/docker/overlay2/3e9f70581e6bb5d265bab133aab3436b1fdca20f2aeaf93bed1283f9df8a65d4/diff",
            "WorkDir": "/var/lib/docker/overlay2/3e9f70581e6bb5d265bab133aab3436b1fdca20f2aeaf93bed1283f9df8a65d4/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "/mnt/nfs-1/minecraft/data:/data",
            "/mnt/nfs-1/minecraft/mods:/mods",
            "/mnt/nfs-1/minecraft/config:/config"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "Devices": [],
        "DiskQuota": 0,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "IpcMode": "shareable",
        "Isolation": "",
        "KernelMemory": 0,
        "Links": null,
        "LogConfig": {
            "Config": {
                "max-file": "2",
                "max-size": "25m"
            },
            "Type": "json-file"
        },
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": false,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": 0,
        "PortBindings": {
            "25565/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "25565"
                }
            ],
            "25565/udp": [
                {
                    "HostIp": "",
                    "HostPort": "25565"
                }
            ]
        },
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "unless-stopped"
        },
        "Runtime": "runc",
        "SecurityOpt": null,
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/a8aed700499055eddc6c257c74cd797030acb95234dbc020c396c0b84ef629a0/hostname",
    "HostsPath": "/var/lib/docker/containers/a8aed700499055eddc6c257c74cd797030acb95234dbc020c396c0b84ef629a0/hosts",
    "Id": "a8aed700499055eddc6c257c74cd797030acb95234dbc020c396c0b84ef629a0",
    "Image": "sha256:0eb4de0187bdfeaa34426fff68baeb8ae309fdbc013e2b87b517836b4ec29784",
    "LogPath": "/var/lib/docker/containers/a8aed700499055eddc6c257c74cd797030acb95234dbc020c396c0b84ef629a0/a8aed700499055eddc6c257c74cd797030acb95234dbc020c396c0b84ef629a0-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/config",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/nfs-1/minecraft/config",
            "Type": "bind"
        },
        {
            "Destination": "/data",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/nfs-1/minecraft/data",
            "Type": "bind"
        },
        {
            "Destination": "/mods",
            "Mode": "",
            "Propagation": "rprivate",
            "RW": true,
            "Source": "/mnt/nfs-1/minecraft/mods",
            "Type": "bind"
        }
    ],
    "Name": "/Minecraft",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "de0c2494f17ca48d551224a5b15170402713aa829a9f6267ca711639d254dda2",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.8",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:08",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "de0c2494f17ca48d551224a5b15170402713aa829a9f6267ca711639d254dda2",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "172.17.0.8",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:11:00:08",
                "NetworkID": "30dc0dc27b1df91e43eec0168a46438e667c08f1d583c3ea4cd3cb8a5d76711b"
            }
        },
        "Ports": {
            "25565/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "25565"
                }
            ],
            "25565/udp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "25565"
                }
            ],
            "25575/tcp": null
        },
        "SandboxID": "7b8d0fa2a374d5174b0d4abc6c039d7a15f623a98b2c19c5d91667f193d302fc",
        "SandboxKey": "/var/run/docker/netns/7b8d0fa2a374",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/start",
    "Platform": "linux",
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/a8aed700499055eddc6c257c74cd797030acb95234dbc020c396c0b84ef629a0/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "2020-04-29T01:25:26.673493346Z",
        "Health": {
            "FailingStreak": 0,
            "Log": [
                {
                    "End": "2020-05-02T12:07:33.832287858Z",
                    "ExitCode": 0,
                    "Output": "localhost:25565 : version=1.15.2 online=0 max=20 motd='A Vanilla Minecraft Server powered by Docker'",
                    "Start": "2020-05-02T12:07:33.761128822Z"
                },
                {
                    "End": "2020-05-02T12:08:04.03570901Z",
                    "ExitCode": 0,
                    "Output": "localhost:25565 : version=1.15.2 online=0 max=20 motd='A Vanilla Minecraft Server powered by Docker'",
                    "Start": "2020-05-02T12:08:03.877836281Z"
                },
                {
                    "End": "2020-05-02T12:08:34.136812776Z",
                    "ExitCode": 0,
                    "Output": "localhost:25565 : version=1.15.2 online=0 max=20 motd='A Vanilla Minecraft Server powered by Docker'",
                    "Start": "2020-05-02T12:08:34.069498093Z"
                },
                {
                    "End": "2020-05-02T12:09:04.281620934Z",
                    "ExitCode": 0,
                    "Output": "localhost:25565 : version=1.15.2 online=0 max=20 motd='A Vanilla Minecraft Server powered by Docker'",
                    "Start": "2020-05-02T12:09:04.220147623Z"
                },
                {
                    "End": "2020-05-02T12:09:34.375688918Z",
                    "ExitCode": 0,
                    "Output": "localhost:25565 : version=1.15.2 online=0 max=20 motd='A Vanilla Minecraft Server powered by Docker'",
                    "Start": "2020-05-02T12:09:34.313253293Z"
                }
            ],
            "Status": "healthy"
        },
        "OOMKilled": false,
        "Paused": false,
        "Pid": 3389,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2020-04-29T02:17:05.977617949Z",
        "Status": "running"
    }
}

**Comment by tigger29900** [comment]
i think i pulled what you were looking for :-) sorry using portainer to manage my docker images

**Comment by itzg** [comment]
That info helped. Looking at the volume mappings, `/data` is mounted from `/mnt/nfs-1/minecraft/data` on your portainer system. You'll need to ask portainer people how to get to a specific path on the system, but I'm guessing it's via NFS from the path.

**Comment by tigger29900** [comment]
Yeah I was worried, I have them maps to the right folders but for some
reason it’s not showing up

No worries worth a try!
