### ISSUE TITLE
There is insufficient memory for the Java Runtime Environment (Docker swarm)

### ISSUE THREAD

**Issue by ImuustMINE** [itzg/docker-minecraft-server#514]
I just connected a new machine to my docker swarm network and tried to start 10 minecraft servers:

`docker service create --replicas 10 -e EULA=TRUE --name mc_test itzg/minecraft-server`

Unfortunately only 5 replicas are able to start.
The other 5 instances showed following error in the log:

```
 ...
 [init] Setting initial memory to 1G and max to 1G
 [init] Starting the Minecraft server...
 OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000c0000000, 1073741824, 0) failed; error='Out of memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1073741824 bytes for committing reserved memory.
```
But as I can see on my node I have plenty of memory left only 6 GB of 32 GB are in use.

Are there some parameters I have add to the command or do I have to configure my node with specific settings?

Best 
ImuustMINE :)

**Comment by wlp7s0** [comment]
Hello @ImuustMINE,
From the information above it is hard to determine what is the problem. But it looks like one of your node doesn't have enough memory. Swarm will distribute the tasks between all the nodes in the swarm. Please try to constraint the task to a specific node with 32GB of RAM

**Comment by ImuustMINE** [comment]
@wlp7s0 I only have one node installed with 32 GB of RAM. So I should have definitely enough RAM available.

**Comment by itzg** [comment]
Add `-e DEBUG_MEMORY=true` to have the startup log include an output of the memory statistics prior to JVM launch.

**Comment by ImuustMINE** [comment]
```
 [init] Memory usage and availability (in MB)
 Linux 6f6ed2bdd6b4 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 Linux
              total       used       free     shared    buffers     cached
 Mem:          3850       3663        187         52          5        589
 -/+ buffers/cache:       3067        783
 Swap:            0          0          0
```

**Comment by itzg** [comment]
The JVM is correct to fail then. The output there shows the node only has 187MB of free memory. That report is saying the node only has 3850 MB total memory or about 4 GB, so I'm not sure where the 32 GB fits into the picture.

**Comment by ImuustMINE** [comment]
Thanks for your help! The debug info helped me to resolve the issue. Docker swarm tried to start an instance of the Minecraft server on my manager node (4 GB of RAM) and not on my worker node (32 GB of RAM). 
As I am new to swarm I didn't know that swarm also tries to deploy images on manager nodes.

With using tags I am now able to deploy the Minecraft servers only on my worker node:
`docker service create --replicas 1 --constraint node.labels.type==worker1 -e EULA=TRUE --name mc_test itzg/minecraft-server`
