### ISSUE TITLE
minecraft-ftb-revelations on kubernetes fails

### ISSUE THREAD

**Issue by Dipluz** [itzg/docker-minecraft-server#517]
Hi,

I keep getting these errors even though I deploy the pod with the environmental variables needed to deploy FTB.

Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 4 1000 1000 4096 May  1 22:50 /data'
Checking version information.
Checking type information.
Looking for Feed-The-Beast / CurseForge server modpack.
Unpacking FTB server modpack /data/2818181.zip ...
/start-deployFTB: line 74: unzip: command not found
Please make sure you are using the server version of the FTB modpack!

My environmental variables are the following:
VERSION = 1.12.2
TYPE = FTB
MEMORY=  6G
FTB_SERVER_MOD = https://www.curseforge.com/minecraft/modpacks/ftb-revelation/files/2818181/
EULA = TRUE

**Comment by Dipluz** [comment]
I am sorry I found the problem as mentioned in other issues is that curse forge has the url redirect. I found a alternative place to grab the jar file and it now boots up. I forgot also to say tnx for the great job on this image. :)

**Comment by itzg** [comment]
Glad you got it figured out
