### ISSUE TITLE
Can't use RCON

### ISSUE THREAD

**Issue by BartekDe** [itzg/docker-minecraft-server#518]
Hi
I'm trying to execute commands using RCON on my server, but it doesn't seem to work or even start at all. My server works fine.
When I run
`docker exec mc-enigmatica rcon-cli op myname`
it returns
`Failed to connect to RCON serverdial tcp 127.0.0.1:25575: connect: connection refused`

I tried exposing RCON ports to the outside and connect using some other tools like mcrcon, but it gives the same message.

My start script:
```
docker run -d \
-v /root/minecraft:/data \
-v /root/minecraft/mod:/modpacks \
-e TYPE=CURSEFORGE \
-e CF_SERVER_MOD=/modpacks/Enigmatica2Server-1.74b.zip \
-p 25565:25565 \
-p 25575:25575 \
-e EULA=TRUE \
-e ENABLE_RCON=true \
-e RCON_PASSWORD=testing \
-e ONLINE_MODE=FALSE \
-e 'MOTD=My server' \
-e MEMORY=3500M \
--name mc-enigmatica itzg/minecraft-server
```

I am using not an up to date modpack version and the RCON was working on other modpack (Valhelsia2), but hopefully that isn't the issue with version, because I don't want to change it.

**Comment by wizel10** [comment]
Same issue here.

**Comment by incomingstick** [comment]
I am experiencing this issue too. Interstingly, I pulled the latest image 6 days ago, and it had been working out of the box. I tried using RCON again today, and it no longer seems to work.

Here is my image run command:
```
docker run -d \
--restart unless-stopped \
-v /etc/localtime:/etc/localtime:ro \
-v /home/user/minecraft_server/data/:/data/ \
-it \
-e EULA=TRUE \
-p 25565:25565 \
--name mc-server itzg/minecraft-server
```

**Comment by itzg** [comment]
I haven't tried yet with the modpack but @incomingstick I wasn't able to recreate your scenario with a vanilla server:

```
> docker exec mc rcon-cli op itzg
Made itzg a server operator
```

Can you all locate the server log line that looks like:
```
[17:56:09] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:25575
```

**Comment by incomingstick** [comment]
@itzg I was just a config issue for me it seems. This is my first time running a Minecraft server, and it was more an experiment to learn Docker than anything. I actually realized my issue was that an RCON password was set. Providing that password during the `docker exec` command granted me access again.

That said, and correct me if I am wrong, I did make the following observations:

- The docker image defaults to an empty password (I could be misremembering this?)
- Once a password has been set for RCON, you _must_ provide that password in plaintext via the `--password` flag
- If you change the password to be empty again RCON **will not start**

Are these observations true? Am I misunderstanding something?

**Comment by itzg** [comment]
I need to document it better, but the default password is actually "minecraft", defined at

https://github.com/itzg/docker-minecraft-server/blob/de866a322ffc55e93c27d055efe4937d58bc19ba/Dockerfile#L71

The cool thing about `docker exec` is that it will borrow the env vars (including `-e`'s) from the container. You can `docker exec CONTAINER env` to confirm that.

So, `RCON_PASSWORD` should be picked up by an exec of rcon-cli as long as you made sure to change it via a `-e`. (If you change that after initial container creation, you'll also need to set `-e OVERRIDE_SERVER_PROPERTIES=true` to keep the properties in sync with env vars.)

FYI, rcon-cli is programmed to pick up config from `RCON_*` env vars:

https://github.com/itzg/rcon-cli/blob/ef0727479c9ccf37ffdef2ed929e0e51402c97da/cmd/root.go#L96-L97

**Comment by antoinetielbeke** [comment]
> Providing that password during the `docker exec` command granted me access again.

How did you pass the password during the docker exec? can you show the full command? I still get Failed to connect to RCON serverdial tcp 127.0.0.1:25575: connect: connection refused

**Comment by itzg** [comment]
@antoinetielbeke , you can pass the password with `--password` ([docs here](https://github.com/itzg/rcon-cli#usage)); however, with a connection refused it sounds like rcon may have not been enabled.

You could confirm the final rcon settings used by using

```
docker exec $CONTAINER grep rcon server.properties
```

**Comment by jshank** [comment]
I think this is because the most recent image starts the rcon server up on port 28016
`minecraft    | [10:14:21] [RCON Listener #1/INFO]: RCON running on 0.0.0.0:28016`

It looks like all of the rest of your containers try to find it at the old port of 25575

**Comment by itzg** [comment]
Eww, I need to fix that example since the default is still 25575

https://github.com/itzg/docker-minecraft-server/blob/f2c9d2f905a65e988f706fb05ef853583417f0e5/Dockerfile#L72

In fact, that example compose file is not only misleading, it's overly complicated...so I'll get that cleaned up. Sorry for the confusion caused by that.

**Comment by icanotc** [comment]
on the newest image here, rcon still wont connect, but only with a modpack tho, it works fine without a modpack

**Comment by dustinblack** [comment]
Same here. Cannot use rcon on a server with a modpack.

**Comment by itzg** [comment]
@dustinblack what modpack are you using that prevents rcon? It would be interesting to see what kind of pattern there is with the ones that cause this issue.

**Comment by QuByte-Zer0** [comment]
SkyFactory 4.2.2 seems to have the same issue as well.

**Comment by dustinblack** [comment]
@itzg For ours, it's a HUGE custom list of nearly 180 mods, so I'm not sure that helps much :-/

**Comment by timothypangburn** [comment]
After working on this a bit it seems the **RCON_PASS** is not being written to the server.properties file if you have multiple mod packs installed. 

I am running a server with SevTech and can see this happening.  

Full disclosure I am testing this Fedora 32 and podman so there might be issues here due to not using docker.

**Comment by james-d-elliott** [comment]
The env var is RCON_PASSWORD, not RCON_PASS. Additionally if OVERRIDE_SERVER_PROPERTIES is not set to 1 or TRUE it will not overwrite the file if it still exists. Thus if you start your docker container without specifying it, the password will be the default of "minecraft" and if you change the env var it will fail.

@timothypangburn @dustinblack a few things that may help diagnose this:

1. Make a backup of your server.properties file.
2. Set `-e OVERRIDE_SERVER_PROPERTIES=TRUE`.
3. Check if that fixes it.

I have a feeling what's occurring is your server.properties doesn't have the same value as env (which rcon-cli uses).

@itzg might be worth having sed replace the rcon lines. Something like:
```bash
cat server.properties | sed "s/rcon.port=.*/rcon.port=${RCON_PORT}/g" | sed "s/rcon.password=.*/rcon.password=${RCON_PASSWORD}/g" > server.properties
```

**Comment by timothypangburn** [comment]
@james-d-elliott thanks for the help.  Yup it is **RCON_PASSWORD**, that what I get for coping and pasting too fast.

I will give your solution a try later today if I can pry family off the server now that I opened it up to them.  :)

**Comment by james-d-elliott** [comment]
@timothypangburn any luck?

**Comment by izio38** [comment]
Same issue with `Infinity` modpack. Here is a link.. But the mod list is pretty huge which might be not that useful.

https://atlauncher.com/pack/Infinity

Anyway, may I help you with a verbose log or something ?

**Comment by itzg** [comment]
@izio38 yeah, a complete log posted on gist, etc might be helpful. It might also be good to open an issue with the modpack authors to shift the effort to them to see which mod is breaking rcon.

**Comment by timothypangburn** [comment]
@james-d-elliott  Sorry for the delay. I finally tested this and while it did work for a Valhelsia modpack it did not work for the SevTech modpack.  Something in SevTech modpack is blocking writing to the correct variable in the server.properties file. 

Modifying the **RCON_PASSWORD** in the server.properties file is a fine workaround for me as this is a lightly used server for family.  

Thanks again for everyone's suggestions and help

**Comment by kevinkjt2000** [comment]
I noticed multiple server.properties files today. One was at `data/server.properties` and had all the correct values based on environment variables. The other was at `data/FeedTheBeast/server.properties` and looked like Minecraft defaults, including rcon-cli being disabled. So I peeked around the startup scripts:

`data/server.properties` https://github.com/itzg/docker-minecraft-server/blob/f613228619c6a3d2e4a3ad39c595f966cc1e7c31/start-configuration#L58
`data/FeedTheBeast` https://github.com/itzg/docker-minecraft-server/blob/f613228619c6a3d2e4a3ad39c595f966cc1e7c31/start-deployCF#L8

These paths are different! What does one do to fix this? Should `data/FeedTheBeast` be changed to `data`? Are there other implications? Should `data` be changed to `data/FeedTheBeast` only if a ftb or curse pack is being loaded? I'm asking a lot of questions because I'm very unfamiliar with the codebase until today.

**Comment by itzg** [comment]
Good find @kevinkjt2000 . At first I thought maybe that got lost in a refactoring of [this final step](https://github.com/itzg/docker-minecraft-server/blob/ca9f883352c10779a52b7fceca36aa25e46a0ce9/start-minecraftFinalSetup#L183-L191); however, looking back through history it didn't seem to ever do that.

I'm thinking of adding a variable to ensure it is a purposeful choice of copying over `server.properties` since some modpacks might rely on the pack-provided settings. How about `CF_COPY_SERVER_PROPERTIES` ?

**Comment by kevinkjt2000** [comment]
Sounds okay to me. What about the already existing Boolean that forces the overwrite of server.properties?

**Comment by kevinkjt2000** [comment]
Another solution could be to extract modpackt directly to the data/ folder (instead of to data/FeedTheBeast/)? I will admit that I have 0 experience with custom mudpack startup scripts, so it's hard for me to make definitive suggestions on how to tackle this.

**Comment by itzg** [comment]
> Sounds okay to me. What about the already existing Boolean that forces the overwrite of server.properties?

Good idea. That's what I'll go with.

> Another solution could be to extract modpack directly to the data/ folder (instead of to data/FeedTheBeast/)? I will admit that I have 0 experience with custom mudpack startup scripts, so it's hard for me to make definitive suggestions on how to tackle this.

I can't remember why I extracted to the subdirectory in the first place, but now it's probably risky to change in case users have scripting around that path. Otherwise, it does make more sense now to have done that.

**Comment by itzg** [comment]
...and just as I was starting to make changes, I noticed that the properties file is directly setup in the subdir with

https://github.com/itzg/docker-minecraft-server/blob/9a7a532f7b1d4cd362dcf46bcaade928d9476a2b/start-finalSetupServerProperties#L173-L176

So, setting `-e OVERRIDE_SERVER_PROPERTIES=TRUE` might actually be the thing that fixes the original problem. Otherwise, it leaves the modpack copy as-is since modpacks are processed before properties. Finally, documented the sequence [here](https://github.com/itzg/docker-minecraft-server/blob/master/docs/start-script-flow.drawio.png).

**Comment by kevinkjt2000** [comment]
Another idea: `FTB_BASE_DIR` could also be made to be configurable with a default of `/data/FeedTheBeast`. I'm currently using my own version of this docker where I manually changed that variable from `/data/FeedTheBeast` to `/data`. Seems to be working well enough.

**Comment by itzg** [comment]
Oops, let's reopen this for now

**Comment by itzg** [comment]
@kevinkjt2000 , in the latest image that base directory can be configured via `CF_BASE_DIR` or `FTB_BASE_DIR`. Added a README section:

https://github.com/itzg/docker-minecraft-server#modpack-data-directory

**Comment by Benjinz** [comment]
Just thought id add to this and say I had the same issue with a CurseForge modpack but manually adding the RCON password(minecraft) to the server.properties file fixed it :) doesn't look like there's any need to set an env to overwrite that file.

**Comment by ElpersonPL** [comment]
Cannot use RCON here either.

**Comment by Sean-FFC** [comment]
For what it is worth, I ran this for the first time tonight trying to do a FABRIC mod server. I'm also unable to connect even though I've specified a password and everything looks right in the server.properties.

**Comment by BartekDe** [comment]
I can't provide feedback as of now, because I don't use this image anymore.
When I created the issue I thought you can access server's CLI only by RCON, but turned out I didn't need to use RCON to do it.

**Comment by taeraeyttaejae** [comment]
> I need to document it better, but the default password is actually "minecraft", defined at
> 
> https://github.com/itzg/docker-minecraft-server/blob/de866a322ffc55e93c27d055efe4937d58bc19ba/Dockerfile#L71
> 
> The cool thing about `docker exec` is that it will borrow the env vars (including `-e`'s) from the container. You can `docker exec CONTAINER env` to confirm that.
> 
> So, `RCON_PASSWORD` should be picked up by an exec of rcon-cli as long as you made sure to change it via a `-e`. (If you change that after initial container creation, you'll also need to set `-e OVERRIDE_SERVER_PROPERTIES=true` to keep the properties in sync with env vars.)
> 
> FYI, rcon-cli is programmed to pick up config from `RCON_*` env vars:
> 
> https://github.com/itzg/rcon-cli/blob/ef0727479c9ccf37ffdef2ed929e0e51402c97da/cmd/root.go#L96-L97

If using docker-composer to start 2 vanilla servers, I think dockerfile has precedence over compose .yml -file, as when i am trying to set 2nd. server RCON settings, they seem to be reseted to default values thus I cannot connect to 2nd server(or this is my best guess at this point).

Any remedy for this, using docker-compose?

**Comment by itzg** [comment]
@taeraeyttaejae can you open up a new issue and include your compose file there?
