### ISSUE TITLE
[Discussion] armv7 + Forge + Minecraft v1.12.2 + Mods on a Pi4

### ISSUE THREAD

**Issue by paladizm** [itzg/docker-minecraft-server#523]
Hello!

First off thanks for this awesome docker container! I wanted to run an older version of Forge and Minecraft so I could use some older mods and was running into a whole host of problems and wanted to post here on how I got around them (also to see if there is a better way :D). Just to describe my setup a bit I am running [Portainer ](https://www.portainer.io/)on the Pi4 4GB with the volumes mounted on an SSD. 

**Problem 1:** unzip and Java 8 not available in the armv7 branch. 

The reason Java 8 is needed is the version of Forge for 1.12.2 of Minecraft does not support anything higher than that, and throws obscure errors. This one took me a bit to get around, but I ended up making a new image (custom Dockerfile) in portainer and installing OpenJDK 8 and unzip after your image. Like so, 
```
FROM itzg/minecraft-server:armv7

RUN apt-get update && apt-get install -y unzip openjdk-8-jdk openjdk-8-jre && apt-get clean
```

After I set up my new container I had to update the java paths in the ENV vars like so (PATH, JAVA_HOME, JAVA_VERSION), 
![image](https://user-images.githubusercontent.com/756057/81464326-933f3c80-918e-11ea-999e-e36eb5f95dba.png)

once I did that Java 8 was the default Java running. 

**Problem 2:** Java not going above 1GB of ram and the version of openjdk installed does not support -XX:+UseG1GC

This was remedied by overriding another ENV var and passing +AlwaysPreTouch in the Java opts
![image](https://user-images.githubusercontent.com/756057/81464388-545db680-918f-11ea-9de8-1fe129ba6840.png)

Once those were up and running Forge was starting to run! Below was my forge settings,
![image](https://user-images.githubusercontent.com/756057/81464399-7eaf7400-918f-11ea-8a52-592b97e9acff.png)
![image](https://user-images.githubusercontent.com/756057/81464415-9ab31580-918f-11ea-8301-5e98c630a38d.png)

Then it was as easy as making a mod folder on my volume and SCPing mods to the folder and installing. The Pi4 is running great so far! I have had multiple folks on the server with very limited issues. Great for a casual playthrough with mods! Anyway thought I would post this here I know it is not an issue so I apologize, but I thought my journey would help some folks! 

Thanks again!

**Comment by itzg** [comment]
Interesting discovery. I thought I was stuck with Java 11 from AdoptOpenJDK since all the "openjdk" docker images seemed to only supply a "Zero VM" which ran only in interpreted mode. On RaspberryPi 3 B+ that was practically unusable since I could give up after numerous hours for the server to start.

So...I started up just an `ubuntu:20.04` image and apt installed openjdk-8 and indeed it is the correct kind of JIT JVM.

I'm going to do some further experiments to improve the base image of the armv7 tag.

**Comment by itzg** [comment]
@paladizm the armv7 branch and the latest `itzg/minecraft-server:armv7` tag is now based on ubuntu and leveraging your approach now supplies Java 8. It's the regular JVM which runs decently on RaspberryPI 3 B+.

**Comment by paladizm** [comment]
Hey @itzg! 

Thanks! I will close this issue, and folks can find it in the archive. Glad that I could help this awesome project a bit!!
