### ISSUE TITLE
Semver tags on Docker Hub

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#526]
Would it be possible to start tagging the images on docker hub with semver or equivalent. Our dependency tracking is having a hard time/generating lots of noise with the frequency of openj9 releases for example, and the dated releases don't seem to cover our requirements.

Possibly v1.0.0-openj9 or similar would work well?
Renovate could do all of this for you, and handle dependencies https://docs.renovatebot.com

**Comment by itzg** [comment]
I can definitely manage semver's on the master/latest branch; however, I have created bit of challenge for myself with six branches for all the variants. On top of that, I have Docker Hub configured to autobuild when the base image is updated; however, looking through Renovate docs I see what you mean, it should be able to replace that aspect.

I like the convention you proposed and just need to think through how to build upon https://github.com/itzg/docker-minecraft-server/blob/master/docker-versions-create.sh and Renovate to get the workflow streamlined.

**Comment by ChipWolf** [comment]
Check out how @dockhippie does it https://github.com/dockhippie/minecraft-vanilla

**Comment by itzg** [comment]
Interesting. Looks like some of the magic is done with Drone -- so I have another tool to learn :) however, I also see [a lot of tediousness across the variants](https://github.com/dockhippie/minecraft-vanilla/commit/f40d5ccad5e45e46c217a5fca696668ae6b11c05). I'll pick and choose some solutions from all of this.

**Comment by ChipWolf** [comment]
Yeah, a combo of Drone and Renovatebot could be pretty powerful, you could automate most if not all of that substitution

**Comment by itzg** [comment]
With f93c42a23f51bca75c619e390e5cd7af97eb5975 I am now able to reliably tag the mainline along with the variant-branches. Since it is a manual step, feel free to ping me if you notice I go too many commits without cutting a new tag.
