### ISSUE TITLE
Update installed spigot

### ISSUE THREAD

**Issue by bryan-lunt** [itzg/docker-minecraft-server#528]
The server logs tell us that the version of spigot contained in the image is out of date.
Could it be updated and a new one pushed to docker hub?

Thanks a lot!
This image is great!

```
*** Error, this build is outdated ***
*** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
*** Server will start in 20 seconds ***
Loading libraries, please wait...
[21:44:55] [Server thread/INFO]: Starting minecraft server version 1.15.2
[21:44:56] [Server thread/INFO]: Loading properties
[21:44:57] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-800b93f-8160e29 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```

**Comment by itzg** [comment]
We're at the mercy of how quickly https://getbukkit.org/ provides new builds or you can add [`-e BUILD_FROM_SOURCE=true`](https://github.com/itzg/docker-minecraft-server#running-a-bukkitspigot-server) to build an up to date copy...however, it takes a long time to build.

**Comment by bryan-lunt** [comment]
Thanks!
