### ISSUE TITLE
Thank you for this image

### ISSUE THREAD

**Issue by tomlarkworthy** [itzg/docker-minecraft-server#533]
Hey, just wanted to say thank you so much for making this.

I wrapped it up for a GCP deployment https://futurice.com/blog/friends-and-family-minecraft-server-terraform-recipe and many people are using it. I use it at home and my daughters are so happy. Your work is bringing happiness to the world so thank you very much.

**Comment by itzg** [comment]
That’s so great to hear and thank you so much. Great article too.
