### ISSUE TITLE
[FEATURE] Auto pause / stop if no player online

### ISSUE THREAD

**Issue by eihns** [itzg/docker-minecraft-server#535]
Hey, 
i dont think you want to implement it. But i think it would be very usefull. I couldnt find a mod for it, only some scripts like https://github.com/gekigek99/minecraft-vanilla-server-hibernation but that cant really be included (as far as i know) into your docker (by me).

Maybe you could consider adding this functionallity, this would save alot of resources, maybe instead of stopping the instance it would be just "frozen" and "unfrozen" (https://www.ostechnix.com/suspend-process-resume-later-linux/ ?)

Problem is i want to use chunk loading, but i dont want to chunkload when no players are online, so the server run infinite, i couldnt find another solution... i really wonder why no one had made a plugin or something like this for it (maybe not possible inside minecraft - only from outside?)

**Comment by itzg** [comment]
You’re in luck. There’s actually a PR in progress to add this for all server types 


https://github.com/itzg/docker-minecraft-server/pull/531

**Comment by itzg** [comment]
...if you could help review and test that PR, that would be fantastic.

**Comment by eihns** [comment]
CRAZY, perfect. Is it meant to be added as a argument "-e ENABLE_AUTOPAUSE=TRUE"?

because it didnt explizity tell to add as argument
