### ISSUE TITLE
Readme references old version of paper

### ISSUE THREAD

**Issue by agilekevin** [itzg/docker-minecraft-server#537]
The readme says:

> Enable PaperSpigot server mode by adding a -e TYPE=PAPER -e VERSION=1.9.4 to your command-line.

1.9.4 is very old, and specifying is unnecessary.  Later on covers using a specific version, rather than the latest.

(just checking I understand these flags, I'll submit a PR for this)

**Comment by itzg** [comment]
Yes, that is simply an example and a very old example. So a PR to update or simply removing that would be great.

**Comment by agilekevin** [comment]
PR ready, let me know if it goes too far:
https://github.com/itzg/docker-minecraft-server/pull/541

**Comment by agilekevin** [comment]
This is off-topic, but I just wanted to say thanks for putting this image together.  I used it to host a birthday party for my daughter and 20 friends, with some fun mods I wrote with PaperMC.  Without the heavy lifting done here, it would have been much more difficult.

Thanks again.

**Comment by itzg** [comment]
That’s so cool and thanks for the help.
