### ISSUE TITLE
OpenJDK Client VM warning: G1 GC is disabled in this release

### ISSUE THREAD

**Issue by reemplazable** [itzg/docker-minecraft-server#538]
Arm32 image is really slow. I was trying to run with the Aikars flags but it seems the main thing is using the G1 GC but unfortunately it is not available in the java version installed. :-(

**Comment by itzg** [comment]
Yeah arm32 is not a very good platform for Minecraft servers

**Comment by barrerajl** [comment]
I disagree, rpi4 works good with minecraft servers (small number of users of course) and a good GC. Just gonna make it work with a newer ubuntu and a newer jdk. Gonna fork the project and see if I can :-)

**Comment by itzg** [comment]
You're welcome to contribute back to this repo if you find a JDK combination that works more effectively. In any case, be sure to work from the `multiarch` branch since that is where the armv7 along with arm64/aarch64 is built.

**Comment by itzg** [comment]
...btw, I wanted to clarify that it's running the server on my RaspberryPi 3 B+ that has been disappointing for me. Even when I'm the only player I get "player moved too fast" and block breaking lag.

**Comment by itzg** [comment]
...and one more follow-up. Aikar flags are not intended to improve CPU performance; in fact, in the intro it states:

> These flags help keep your server running CONSISTENT without any large garbage collection spikes. CPU may be slightly higher, but your server will be overall more reliable and stable TPS.

**Comment by itzg** [comment]
### Note to self:

Tried AdoptOpenJDK distribution of JDK 8 and armv7's image shows the Zero VM is used, which lacks JIT compilation and is very, very slow. That is a regression from the openjdk-8 bundled with Ubuntu 18.04.

Using:
```
FROM ubuntu:18.04

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
    curl \
    gnupg2 \
    software-properties-common \
    && apt-get clean

RUN curl -fsSL https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add - && \
  add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/

ARG JAVA_RELEASE=8

RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive \
  apt-get install -y \
    adoptopenjdk-${JAVA_RELEASE}-hotspot \
    imagemagick \
    gosu \
    wget \
    jq \
    dos2unix \
    mysql-client \
    tzdata \
    rsync \
    nano \
    && apt-get clean
```

reports:
```
OpenJDK Zero VM warning: G1 GC is disabled in this release.
```

**Comment by reemplazable** [comment]
Ok, looking into the matter. RPI4 with ubuntu64 bits and using as a base adoptopenjdk based on debian images they can be multiarch because they support armv7l and aarch64. So It won't be the fastest but the image can use jdk11 or better con G1 GB or even try ZGC... with jdk13/14
So for amd64 images you can use low footprint alpine and for multiarch you can use adoptopenjdk:debian and upgrade the jre versions :+1: 

Thanks!

Maybe doing a PR? (What do you think?)

**Comment by itzg** [comment]
Forge is apparently only compatible with Java 8, which is why I’m stuck using that as the mainline java version for both the alpine/latest and Ubuntu/multiarch. 

I can introduce `multiarch-11` variant for Java 11. It takes more than a PR since I need to get update and build strategies in place.
