### ISSUE TITLE
Can not run docker latest image

### ISSUE THREAD

**Issue by Migarve55** [itzg/docker-minecraft-server#542]
When I try to run the image I always get the same error: 

`/bin/bash: /start: Permission denied`

This is the command I used:

`sudo docker run itzg/minecraft-server`

I tried several different types of server (vanilla, spigot, etc) and it does not make a differente, it never manages to start the server. Maybe there is an issue with the start script permissions.

**Comment by itzg** [comment]
Someone on the Discord channel reported the exact same issue and they resolved it by clearing out the images and pruning the build cache. I'm guessing they used `docker system prune`.

**Comment by max7patek** [comment]
I'm also having this issue. I'm on a fresh install of Ubuntu 20 and a fresh install of docker with nothing to prune. 

I'm also getting an rcon error when running the docker-compose.yml:

```
minecraft_1  | /bin/bash: /start: Permission denied
rcon_1       | fs.js:114
rcon_1       |     throw err;
rcon_1       |     ^
rcon_1       | 
rcon_1       | Error: EACCES: permission denied, open '/opt/rcon-web-admin-0.14/src/main.js'
rcon_1       |     at Object.openSync (fs.js:443:3)
rcon_1       |     at Object.readFileSync (fs.js:343:35)
rcon_1       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:20)
rcon_1       |     at Module.load (internal/modules/cjs/loader.js:653:32)
rcon_1       |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
rcon_1       |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
rcon_1       |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
rcon_1       |     at startup (internal/bootstrap/node.js:283:19)
rcon_1       |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
docker-minecraft-server_rcon_1 exited with code 1
docker-minecraft-server_minecraft_1 exited with code 126
```
Not sure if they're related. I tried cloning the repo, chmoding +x  on `start`, and running docker compose from that directory, but no difference (probably because its still pulling from dockerhub).

**Comment by max7patek** [comment]
Update: After trying some other docker apps, I think the issue is [this](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1879690), discovered [here](https://forum.snapcraft.io/t/docker-fails-with-permission-denied-inside-containers/17602/22). I'll try switching to apt docker.
