### ISSUE TITLE
Java process is running with Flag "-Dfml.queryResult=confirm" ~50 times

### ISSUE THREAD

**Issue by Mohl** [itzg/docker-minecraft-server#543]
I sshed into the container out of curiosity when I stumbled upon this. Apparently, with my setup the aforementioned flag is added 47 times to the java process.

I use the openj9 tagged image and added several flags myself using the JVM_XX_OPTS env variable:
` -Xmns5G -Xmnx10G  -Xgc:concurrentScavenge -Xgc:dnssExpectedTimeRatioMaximum=3  -Xgc:scvNoAdaptiveTenure -Xdisableexplicitgc  -Xjit:disableGuardedStaticFinalFieldFolding` (Sidenote: the last flag VASTLY improves performance, especially with large modpacks like FTB or MC Eternal - see https://github.com/eclipse/openj9/issues/8353 ).

The JAVA_TOOL_OPTIONS Env Variable was set by the image: `-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle`

This apparently has no negative consequence to the container or minecraft - it's running flawless. I just thought I should no leave this unmentioned...

**Comment by itzg** [comment]
I added a fix for this a few months ago, so can you double check that you have pulled the latest image. I’ll double check the fix didn’t disappear too.

**Comment by Mohl** [comment]
I just set up the image today, and `docker images`reports the image was created 4 days ago:
```
docker images | grep openj9
itzg/minecraft-server               openj9              1a7dba01713d        4 days ago          457MB
```
Java version reports `jdk8u252-b09_openj9-0.20.0` - released April 20, 2020.

**Comment by itzg** [comment]
Yeah, the fix is still present for the "queryResult" issue reported before:

https://github.com/itzg/docker-minecraft-server/blob/8440e571183efe488c91bd661f98d4af72e4b737/start-deployFTB#L112-L113

Can you provide the "docker run" or compose file you're using to launch your container?
