### ISSUE TITLE
itzg/docker-minecraft-server stops with "ERROR failed to obtain version manifest URL"

### ISSUE THREAD

**Issue by McBschire** [itzg/docker-minecraft-server#544]
Moin,

maybe someone can give me an impulse to find a way to solve my issue.

I installed the docker image in my QNAP container station. First I decided to use NAT but then my son asked for access for his friend over the internet, so I changed to bridged mode with fixed IP address (installed the image again).

The bridged version worked good, but then I stopped the image and started it again. After that the image started and stopped after a few seconds. The log shows the following:

...
Checking version information.
curl: (6) Could not resolve host: launchermeta.mojang.com
Checking type information.
Downloading minecraft_server..jar ...
curl: (6) Could not resolve host: launchermeta.mojang.com
ERROR failed to obtain version manifest URL (6)

Obviously the network connection did not work.

Step 1: I tried to install the image again with the same fixed IP. The result was, that this time the image starts and stops even the first time with the ERROR.
Step 2: Then I installed the image with another IP address and this time the image worked again. But after starting and stopping the image I got the same error. So I tried Step 1 again with the same address. Did not work. Step 2 with another address did work the first time and after starting and stopping it fails.

I assume, that the reason for the stop of the image is because of missing network connectivity. As the image stops I do not have the chance to look at the network configuration after the reboot of the image.

Of course I would take the solution directly, but if not: Is there a way where I can change something to prevent the stop of the image? Then I could look from CLI, which part of the network is not working.

Thank you for any hint
Jim

Environment at 24.05.2020
- QNAP TVS-463 - 4.4.2.1270
- Container Station 2.0.1189
- iztg/minecraft-server - latest

**Comment by itzg** [comment]
Hmm, I'm not familiar with QNAP, so I can't help much with any specifics for your scenario. For the last part, you can simply start the container with bash to inspect networking using:

```
docker run -it --rm --entrypoint bash itzg/minecraft-server
```

It sounds like either the DNS configuration from your host/network is not getting picked up by Docker or a firewall type configuration is blocking the DNS query response.

To further help your debugging, at that point in the startup scripts it is doing a

```
curl -fsSL https://launchermeta.mojang.com/mc/game/version_manifest.json
```

**Comment by McBschire** [comment]
Moin, 

thank you for your fast response. I try to investigate into this the next days.

Jim

**Comment by McBschire** [comment]
Moin,

I've created a container with /bin/bash as entrypoint now with an unexpected result.
I can start and stop this container as often as I like: The network is up and running and the curl command works. 

So I thought after starting the /start script, it will not work again. But: I can start and stop the minecraft server and/or the container as often as I like, the error is gone.

So I tried again to setup a container with /start as default entrypoint. And this one behaves like at the beginning: It works first and after stopping and starting the container it will not come up again.

If someone reads this: At the moment I do have four itzg/minecraft-server:latest images installed in containers. They have different IDs and (host)names, but the image name is the same. If I understood docker command right, with docker run it starts a new container/image. To debug my error I do need to start an existing (broken) container with a different entrypoint (bash). I though docker start should do that, but I could not find a parameter till now, which uses the ID or the name instead of the image-name. I will read more and am sure, that there should be a command like this, but of course hints for docker-Beginners are very welcome.

Jim

**Comment by itzg** [comment]
If QNAP provides the docker software, then I would suggest contacting them since it sounds like their platform or your network environment is not behaving consistently.

To your question, the entry point (and really most parameters) can only be defined when the container is created. Docker’s `run` is basically a shortcut for `create` and `start`.

**Comment by PatPetereit** [comment]
I have the same problem with the newest image. No other container shows this behaviour, already tried bridge and host mode. Both show the same problems. When i exec a simple ping or curl from the shell i get the excpected results. 

Running in Debian10 (OpenmediaVault). Anything i can do to help troubleshoot?

**Comment by PatPetereit** [comment]
Update: It was a permission problem with the GUIDS. Fixed it an everything is fine now. It is not a network problem, i guess he just coudnt store the file. Sorry to bother you with this :)

**Comment by McBschire** [comment]
Moin, 

till now I did not find a way to start one of the failing containers in the way, to reach the shell to debug into the issue.

As I am able to start the containers with bash as entrypoint (with an working network environment) I am currently starting the processes afterwards manually. 

Therefore I will close the issue here without a solution. Thank you for your hints and the support.

Jim

**Comment by M4TY** [comment]
> Update: It was a permission problem with the GUIDS. Fixed it an everything is fine now. It is not a network problem, i guess he just coudnt store the file. Sorry to bother you with this :)

Hello. Sorry for writing into a closed issue, but how do you do that? 😄 I am currently struggling with the same issue. Thanks in advance.

**Comment by Mistic92** [comment]
Hi, I had the same issue. When I changed entrypoint to `/bin/bash` and then used `/start` from terminal it start normally.
