### ISSUE TITLE
Unable to access jarfile forge-1.15.2-31.1.74.jar

### ISSUE THREAD

**Issue by Alejano** [itzg/docker-minecraft-server#547]
[root@localhost Servidor]# docker run -d -v /myHost/data -e TZ=America/Mexico_City -e TYPE=FORGE -e FORGEVERSION=31.1.74 -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server
9cff120c6569a0a42cd0b1649a7ea6189fde1e6cd61bf3c8cc4652ef11fc06b3
[root@localhost Servidor]# docker logs -f mc
[init] Changing ownership of /autopause to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    4 1000     1000           236 May 28 20:15 /data'
[init] Resolved version given LATEST into 1.15.2
[init] Resolving type given FORGE
[init] Checking Forge version information.
[init] server.properties already created, skipping
[init] log4j2.xml already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 1G and max to 1G
[init] Starting the Minecraft server...
Error: Unable to access jarfile forge-1.15.2-31.1.74.jar
2020-05-28T20:25:35.385-0500	INFO	mc-server-runner	Done
[root@localhost Servidor]# 

I don't know why it doesn't work, I already provided the jarfile in my / Data, but it still doesn't recognize it, it says it doesn't exist

**Comment by Alejano** [comment]
I had to use this: "1.15.2-latest": "31.2.5", I think it is important to specify the versions to use, since some do not work

: C

**Comment by itzg** [comment]
With `TYPE=FORGE` it will download the forge installer for you and install the resulting forge jar. By providing the jar yourself, it sounds like it might have confused the startup logic. You may want to try `TYPE=CUSTOM`.
