### ISSUE TITLE
Overriding max memory doesn't affect anything.

### ISSUE THREAD

**Issue by ShawnRG** [itzg/docker-minecraft-server#548]
Hi,
I've tried adding the `MEMORY`, `INIT_MEMORY` and `MAX_MEMORY` env variables to my docker run but in the logs I still get the following log:

> [init] Setting initial memory to 1G and max to 1G

Am I doing something wrong?

**Comment by itzg** [comment]
That's indeed the correct variables and the correct log entry to observe. Can you provide the full docker run command-line you're using?

**Comment by ShawnRG** [comment]
Also the _opping_ doesn't work.
Here is the code command I used:
```
docker run -d -v ~/server:/data -v ~/modpacks:/modpacks -e TYPE=CURSEFORGE -e /
CF_SERVER_MOD=/modpacks/Enigmatica4Server.zip -p 25565:25565 -e EULA=TRUE --name mc /
itzg/minecraft-server -e MEMORY=8G -e OPS=ShawnRoss,Dipfly -e INIT_MEMORY=3G -e MAX_MEMORY=8G
```

**Comment by itzg** [comment]
Oh, I should have asked for your `docker run` initially. You need to make sure all container arguments like `-e` go **before** the image name.

**Comment by ShawnRG** [comment]
I see, makes sense.
Let me quickly verify.

**Comment by ShawnRG** [comment]
I also had issues connecting to the server with RCON

**Comment by itzg** [comment]
How are you trying rcon and what is it doing?
