### ISSUE TITLE
Reloading ResourceManager takes 5 minutes

### ISSUE THREAD

**Issue by rosierazorex** [itzg/docker-minecraft-server#552]
I'm not sure where to ask this or if it's even a problem.

I'm running a paper server on a Raspberry Pi 4. This step, "Reloading ResourceManager: Default, bukkit", takes 4:30 minutes to complete when starting the server. The rest of the startup process only takes 30 seconds. Is this expected?

During this step the RPi uses less CPU power than when the server is running with 2 players connected, and it runs smoothly at that point. 

I'm using the armv7 image. 

Is this an issue at all or is it just expected RPi performance?

**Comment by itzg** [comment]
Some of that is just the nature of running on rpi and that step is slower on every platform; however, try out the `multiarch` image tag. Its code started from the armv7 branch, has a few more improvements, and also supports 64-bit ARM.
