### ISSUE TITLE
java command line params error

### ISSUE THREAD

**Issue by Diluka** [itzg/docker-minecraft-server#560]
compose 
```
      JVM_DD_OPTS: "-Dfml.queryResult=confirm"
      JVM_XX_OPTS: "-XX:+AggressiveOpts"
```

real command `java -XX:+AggressiveOpts -Xms1g -Xmx4g -Dlog4j.configurationFile=/data/log4j2.xml -D-Dfml.queryResult=confirm -jar forge-1.15.2-31.2.21.jar nogui`

`-D-Dfml.queryResult=confirm` shall be `-Dfml.queryResult=confirm`

**Comment by Diluka** [comment]
my bad

**Comment by Diluka** [comment]
@itzg JVM_DD_OPTS don't need -D bug why JVM_XX_OPTS needs -XX?

**Comment by itzg** [comment]
Yes, in hindsight that’s an unfortunate confusion due to the similarity in names. The XX one long pre-dated the other and simply existed since the JVM requires those options before -D and others.

**Comment by itzg** [comment]
...also the intent for XX one is to convey any of the low level JVM options like `-agent` and others so it can’t do the auto-prefixing like the DD one.
