### ISSUE TITLE
Catserver is not in the TYPE list

### ISSUE THREAD

**Issue by ooohawk** [itzg/docker-minecraft-server#561]
Code i ran

> docker run -d -v /cat:/data -e VERSION=1.12.2 -e TYPE=CATSERVER -e MEMORY=12G -e OPS=Lemon2ee -e MAX_PLAYERS=5 -p 25565:25565 -e EULA=TRUE --name cat itzg/minecraft-server

Expected:The server should be installed and running with catserver

What i actually got: 

> [init] Changing ownership of /autopause to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1000          4096 Jun 23 14:12 /data'
[init] Resolved version given 1.12.2 into 1.12.2
[init] Resolving type given CATSERVER
[init] Invalid type: 'CATSERVER'
[init] Must be: VANILLA, FORGE, BUKKIT, SPIGOT, PAPER, FTB, CURSEFORGE, SPONGEVANILLA

**Comment by itzg** [comment]
Double check you have `docker pull`ed the latest image or use the tagged version `itzg/minecraft-server:1.3.0`

...however, I do need to add CATSERVER and a couple other new ones to the log message there.

**Comment by ooohawk** [comment]
pulled the image again and problem solved. THX
