### ISSUE TITLE
Failed to download Paper 1.16 ????

### ISSUE THREAD

**Issue by Elrondo46** [itzg/docker-minecraft-server#563]
I'm sure you have to solve this:

`[init] Resolved version given LATEST into 1.16
[init] Resolving type given PAPER
[init] Downloading Paper 1.16 (build latest) from https://papermc.io/api/v1/paper/1.16/latest/download ...
curl: (22) The requested URL returned error: 404 
[init] ERROR: failed to download from https://papermc.io/api/v1/paper/1.16/latest/download (status=0)
`

**Comment by peace-blaster** [comment]
I don't think paper 1.16 is out yet. It appears to be trying to fetch from `https://papermc.io/api/v1/paper/1.16/<VERSION>/download` regardless of version, even though the latest is `https://papermc.io/api/v1/paper/1.15.2/370/download`. I just put in a ticket with the same issue.

**Comment by itzg** [comment]
Yeah, I need to look again at what it’ll take to cap Paper (and friends, like Spigot) at 1.15.2 until they’re caught up.

**Comment by ronthecookie** [comment]
@itzg Paper's Jenkins instance seems to have an [API](https://papermc.io/ci/api/json) however I don't know about the others
.

**Comment by peace-blaster** [comment]
I just temporarily switched my servers back over to vanilla until this is resolved. If you have your `/data` folder mounted on the host OS, you can just recreate the container on top of it again and it seems to work, unless you need some sort of paper-specific functionality I'm unaware of.

According to their dev 'Z750', they don't have an ETA on paper 1.16, so it'll probably be a minute.

**Comment by ronthecookie** [comment]
@peace-blaster You can just set the `VERSION=1.15.2` env variable until it's fixed. (or until paper has a 1.16 build)

**Comment by ronthecookie** [comment]
Paper 1.16.1 is out now so someone should probably rename this issue to reflect fixing it for future versions. (@itzg ?)

**Comment by itzg** [comment]
It sounds like the issue can be simply closed. BTW, I’m not sure what there is to fix for future versions.

**Comment by ronthecookie** [comment]
Well like you said before, we need a way to cap paper/spigot/etc at a specific version until they update

**Comment by Arunscape** [comment]
recently ran into this as well. I noticed in the logs, it knows of previous versions.
Maybe it can fall back to the latest version available?

```
[init] ERROR: 1.16.2 is not (yet) published by PaperMC
[init]        Set VERSION to one of the following:
[init]        1.16.1, 1.15.2, 1.15.1, 1.15, 1.14.4, 1.14.3, 1.14.2, 1.14.1, 1.14, 1.13.2, 1.13.1, 1.13-pre7, 1.13, 1.12.2, 1.12.1, 1.12, 1.11.2, 1.10.2, 1.9.4, 1.8.8
```

**Comment by itzg** [comment]
> edit: yeah this would be trivial (for paper at least)

Yes, it would be trivial (and PRs are welcome BTW); however, I was hesitant to have the meaning of `VERSION=LATEST` differ from the primary semantic of "latest mainline/official version" to "if paper, then LATEST is actually the latest version available for Paper".

If I can get some thumbs up/down votes on that conditional behavior, then I'm good with adding the logic.

**Comment by itzg** [comment]
...meanwhile, please reach out to the PaperMC people and see if there's help that can be contributed to get 1.16.2 released sooner.

**Comment by james-d-elliott** [comment]
1.16.2 RC4 is a available via [this URL](https://cdn.discordapp.com/attachments/742779128868241550/745101276278161478/1.16.2-r4.jar). I believe they have not released it yet since stability and world corruption is still a major issue even between 1.16.1 and 1.16.2 (exists in vanilla and spigot too).

**Comment by itzg** [comment]
FYI PaperMC 1.16.2 is now available; however, I'm still working on enhancing the "pick latest PaperMC version" logic for the next case like this.

**Comment by itzg** [comment]
Latest image now improves the logic to fallback to latest available PaperMC version when `VERSION=LATEST` is used.

**Comment by yllekz** [comment]
FYI, I just tried using VERSION=LATEST and it tried to grab Paper 1.16.3 which doesn't appear to exist yet. I know you said you included fallback logic but it didn't seem to kick in for me. I had to plunk in 1.16.2 to get it to work

**Comment by itzg** [comment]
Hmm, now's my chance to test and re-fix that logic.

**Comment by itzg** [comment]
Paper 1.16.3 is now available so I'll have to try to reproduce the issue differently.

```
[02:41:52 INFO]: This server is running Paper version git-Paper-191 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
```

@yllekz BTW are you sure you have pulled the latest image? I reviewed the latest changes and it looks like it should handle it correctly.

**Comment by yllekz** [comment]
Yeah it looks like in the time that I made the comment and today, Paper 1.16.3 came out. I might have to wait till another version variance to re-test, but yeah yesterday I was just getting "failed to download" over and over. I am 95% certain I had the latest image but you never know. I'll test again next time this comes up.
