### ISSUE TITLE
Minecraft Spigot v1.16.1 not working under podman on CentOS 8.2

### ISSUE THREAD

**Issue by bavrogar** [itzg/docker-minecraft-server#565]
Hello,

OS: CentOS 8.2
SELinux: Enforcing
Software: Podman
Rootless: Yes

When running
`podman run -d -v /virt/podman/container-data/minecraft:/data:z  -e TYPE=SPIGOT -p 25565:25565 -e EULA=TRUE -e VERSION=1.16.1 --name minecraft itzg/minecraft-server`

I got the following error:

`ERRO[0000] exit status 1                                
ERRO[0000] Unit 95655dbca3e6bc601b17f0fbd34ef2234cc4b0d248e36862acc525a0a44a788b.service not found. 
95655dbca3e6bc601b17f0fbd34ef2234cc4b0d248e36862acc525a0a44a788b`

Podman reports that the container is not running. Disabling SELinux or running under root is not the solution. The same problem exists with Minecraft 1.15.2, but then the container runs.

Could you please help me out?

**Comment by itzg** [comment]
It will be a while before Spigot supports 1.16. Until then, one workaround is to explicitly set  `VERSION` to `1.15.2`. I might also add some logic to cap the version at 1.15.2 for non-vanilla types.

**Comment by JulienTant** [comment]
Spigot has been released @bavrogar ;)

**Comment by itzg** [comment]
Yay, that was much quicker than I expected.

**Comment by itzg** [comment]
...confirmed `docker run -ti --rm -e EULA=TRUE -e TYPE=SPIGOT itzg/minecraft-server` started and reported:

```
[19:13:07] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-758abbe-2b00831 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
```

**Comment by bavrogar** [comment]
Hey itzg,
Thanks for the reaction. We got Spigot running on 1.16.1 now. The error I listed still exists and also exists with 1.15.2. Could you please have a look at it?

**Comment by itzg** [comment]
It sounds like you need to report an issue with podman. That error doesn’t appear to make any specific mention of this image.
