### ISSUE TITLE
[RPi/armv7] Server lagging and crashing with recent updates

### ISSUE THREAD

**Issue by yllekz** [itzg/docker-minecraft-server#567]
Hello, I've noticed lately that my server running off of my Raspberry Pi 4B (armv7 image) has been effectively unusable for the past few versions. I'm not quite sure what suddenly is the problem, but worlds are very laggy, and chunks are slow to load, with server crashes occasionally happening.

My console is littered with messages from the java output stating things like " Can't keep up! Is the server overloaded? Running 15655ms or 313 ticks behind" or "[Server Watchdog/FATAL]: A single server tick took 60.00 seconds (should be max 0.05)"

Was just wondering if others are experiencing this as well with the armv7 branch.

**Comment by itzg** [comment]
Please double check using the `multiarch` tag since I have deprecated the armv7 branch/tag and consolidated into `multiarch`. With that said, starting with 1.15 the minecraft server seems to be considerably more resource intensive in general :(

**Comment by yllekz** [comment]
Thanks, I switched over to the multiarch tag but the same issues remain. Ugh yeah I'm wondering if the recent updates need more resources, because my poor Pi server crashes me out after a few minutes of connecting.

**Comment by itzg** [comment]
Yeah, I had to give up using my RaspberryPi 3 B+ :( Luckily I also have an Intel NUC running Ubuntu, so that has worked out well.

**Comment by yllekz** [comment]
Just an FYI, there is an open [bug filed with Mojang](https://bugs.mojang.com/browse/MC-191659) about apparent server performance issues with 1.16.
