### ISSUE TITLE
Unclear how to make autopause and knockd work

### ISSUE THREAD

**Issue by FreezyExp** [itzg/docker-minecraft-server#569]
Instead of stating what does not work, maybe give a hint of what does work.

An example docker-compose could be added to get us on the right path.

**Comment by itzg** [comment]
That's a good point. I have updated the docs, marked the feature experimental, and added an example compose file.

**Comment by FreezyExp** [comment]
Awesome! I will experiment with this then :P

**Comment by FreezyExp** [comment]
In the docker-compose-autopause.yml
I see no special networking settings, is it due to the docker-compose version or something?

Sorry for my ignorance, I'm ok-ish with docker, but far from well-versed in it.

**Comment by FreezyExp** [comment]
Ah I see, I specified
user: 888:888 
and set up the folder privileges accordingly, but then knockd fails inside the container.
This lets the server run with the proper file access, but for some reason cannot start the knockd daemon.

I guess altering the user externally is possible by changing the hardcoded 1000 to some default env variable.

It seems AUTOPAUSE comes up without errors now, experimentation underway :D

This seems to work:

`version: '3.3'

services:
  mc:  
    image: itzg/minecraft-server
    ports:
    - 25565:25565
    environment:
      EULA: "TRUE"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "example"
      RCON_PORT: "28016"
      SEED: "1234567890"
      MAX_MEMORY: 1G
      WHITELIST: "true"
      SNOOPER_ENABLED: "false"
      SPAWN_PROTECTION: "16"
      OPS: "ExampleUser"
      MODE: "spectator"
	  # add gamerules?
      ENABLE_AUTOPAUSE: "TRUE"	  
    volumes:
    - /srv/minecraft/game:/data
    tty: true
    stdin_open: true
    restart: always
    networks:
      - mc_bridge
      - mc_service
    
    
  mc-rcon:
    image: itzg/rcon
    ports:
    - 4326:4326
    - 4327:4327
    environment:
      RWA_USERNAME: SomeRconUser
      RWA_PASSWORD: "anotherpassword"      
      RWA_RCON_HOST: mc
      RWA_RCON_PORT: 28016
      RWA_RCON_PASSWORD: "example"
    volumes:
    - /srv/minecraft/rcon:/opt/rcon-web-admin/db
    restart: always
    networks:
      - mc_service

  mc-backups:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "6h"             
      INITIAL_DELAY: "1m"      
      PRUNE_BACKUPS_DAYS: "3"
      RCON_PORT: "28016"
      RCON_PASSWORD: "example"
      EXCLUDES: "*.jar,cache,logs"
      BACKUP_METHOD: "tar"
      RCON_HOST: "mc"
    volumes:
    - /srv/minecraft/game:/data:ro
    - /srv/minecraft/backups:/backups
    restart: always
    networks:
      - mc_service
      
networks:
  mc_bridge:
    driver: bridge
  mc_service:
`
