### ISSUE TITLE
Container export doesn't save world

### ISSUE THREAD

**Issue by raikoug** [itzg/docker-minecraft-server#570]
Hello, I was trying to export container and importing in another machine.

* run commands:
```docker run -d -e EULA=TRUE -e TZ=Europe/Rome -p 25565:25565 --name mc itzg/minecraft-server```

* export command:
```docker export -o minecraft_2020_06_28_01_04.tar mc```

* I then scp the file to another machine (save OS, same docker version)
```docker import minecraft_2020_06_28_01_04.tar minecraft_bacup:1.0```
* Run command
```docker run -d --restart unless-stopped -e EULA=TRUE -e TZ=Europe/Rome -p 25565:25565 --name mc minecraft_bacup:1.0 /start```
(With command as last argument either ways it would work from start)

First error: ```type cannot be "" ``` while reading the TYPE value.
Ok, I override this with: ```-e TYPE=VANILLA```

Second error: java memory value error... Ok, I override this too with: ```-e MEMORY=2G```

Now the run commands is:
```docker run -d --restart unless-stopped -e EULA=TRUE -e TZ=Europe/Rome -e TYPE=VANILLA -e MEMORY=2G -p 25565:25565 --name mc minecraft_bacup:1.0 /start```

It runs! I connect and... this is not my world. Or my spawn is somewhere totally different from before?

I still have the original server and would like to know of a safe way to export this, because even beeing familiar with docker and haveing done this before with other containers (without any issue) I really can't understand.

This is the docker inspect of Imported Backup Image:
```
[
    {
        "Id": "sha256:53835f3d130e43a8ba81ab6c4bf4961fd7659a7118b4c30b41353bbc632e97a3",
        "RepoTags": [
            "minecraft_bacup:1.0"
        ],
        "RepoDigests": [],
        "Parent": "",
        "Comment": "Imported from -",
        "Created": "2020-06-28T10:56:30.421321746Z",
        "Container": "",
        "ContainerConfig": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "DockerVersion": "19.03.12",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": null,
            "Cmd": null,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 294076806,
        "VirtualSize": 294076806,
        "GraphDriver": {
            "Data": {
                "MergedDir": "/var/lib/docker/overlay2/f3460ebd26e8664863ccc7a2febd019e6700358a21d979fab92979022956528d/merged",
                "UpperDir": "/var/lib/docker/overlay2/f3460ebd26e8664863ccc7a2febd019e6700358a21d979fab92979022956528d/diff",
                "WorkDir": "/var/lib/docker/overlay2/f3460ebd26e8664863ccc7a2febd019e6700358a21d979fab92979022956528d/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:876c289ea6080fe331c8b2e8feb052b842a8935860594039490b60f9191b8dfc"
            ]
        },
        "Metadata": {
            "LastTagTime": "2020-06-28T12:56:30.427913204+02:00"
        }
    }
]
```

Comparing it to the original one, the differences are huges, and this never happened before to me. 

Am I doing something wrong or is this a issue with Minecraft server docker?

Thanks and sorry to bother. Your work is AWESOME.

**Comment by itzg** [comment]
`docker export` does not include volumes and `/data`, which is where all of the minecraft content is maintained, is a volume:

![image](https://user-images.githubusercontent.com/988985/85950949-81278200-b925-11ea-9184-375ea97a2470.png)

Volume attachment of `/data` to a host directory would have been the easiest way to transport the content from one host to another; however, since you're using the auto-volume creation you can instead use [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp/) to copy the `/data` directory out of the old container, move that directory to the new host and [attach that directory as the data volume](https://github.com/itzg/docker-minecraft-server#attaching-data-directory-to-host-filesystem).

**Comment by raikoug** [comment]
I'm used to create whatever I want inside a container, export and import somewhere else and find the new things I created.

Is `/data ` somehow different?

I will use external volume from now on to let me move this thing easily.

Thanks for the answer!

**Comment by james-d-elliott** [comment]
You can also find all your docker volumes under /var/lib/docker/volumes.

**Comment by itzg** [comment]
@raikoug again, `/data` is only "different" because it is declared as a volume:

https://github.com/itzg/docker-minecraft-server/blob/bbe930e55203f80a0cdf4791ce3a8f4ac04c6cd9/Dockerfile#L64
