### ISSUE TITLE
Spigot

### ISSUE THREAD

**Issue by JacoVanR** [itzg/docker-minecraft-server#572]
Hello there! 
We are making a server for my old school and im wondering how i can install spigot??

Thanks!

Jaco.

**Comment by itzg** [comment]
There's a section for running Spigot type servers:

https://github.com/itzg/docker-minecraft-server#running-a-bukkitspigot-server

Let me know if you have any follow up questions or join the discussion over at Discord

https://discord.gg/DXfKpjB
