### ISSUE TITLE
Feature Request - Option to force overwrite /plugins

### ISSUE THREAD

**Issue by Trikolon** [itzg/docker-minecraft-server#576]
I've added a bind mount to `/plugins` to be able to put my plugin binaries and configuration files under version control.
There are situations where a  server plugin updates a config in the volume, updating its last modified timestamp. Then it's no longer possible to update the file via `/plugins` bind mount without manually changing the timestamp.

Could you add an option which disables the last-modified check for the rsync command so data can always be overwritten?

**Comment by itzg** [comment]
The latest image now includes an option to set `PLUGINS_SYNC_UPDATE=false`, which will avoid the `--update` in rsync:

https://github.com/itzg/docker-minecraft-server#deploying-plugins-from-attached-volume

**Comment by Trikolon** [comment]
Awesome! Thanks for implementhing this so quickly. I'll give it a try and provide feedback soon.

**Comment by Trikolon** [comment]
I've just tested this and also deployed it to production. All working! Thank you.
