### ISSUE TITLE
REPLACE_ENV_VARIABLES does not replace variables in /plugins

### ISSUE THREAD

**Issue by Trikolon** [itzg/docker-minecraft-server#577]
When I add variables to configs I mount in `/plugins` it doesn't replace them before copying the files to the server config directory. This means I have to start the server twice for it to apply the variables.
Would it be possible to do the replace step after copying the files or even provide an option to only replace vars for files copied from `/plugins`?

**Comment by itzg** [comment]
The latest image now does `/plugin` processing before env var replacements.

**Comment by Trikolon** [comment]
I can confirm this works now. Thank you!
