### ISSUE TITLE
FTBA version.json not found

### ISSUE THREAD

**Issue by cclloyd** [itzg/docker-minecraft-server#578]
Deployed using the itzg/minecraft helm chart.  

Relevant parts of my yaml to deploy:

    image: itzg/minecraft-server
    imageTag: multiarch
    extraEnv:
      FTB_MODPACK_ID:
        value: 35
      FTB_MODPACK_VERSION_ID:
        value: 37

The container shows the following logs:

    [init] Running as uid=1746400001 gid=0 with /data as 'drwxrwxrwx 2 1746400001 1746400001 4096 Jul  5 06:19 /data'
    [init] Resolved version given 1.12.2 into 1.12.2
    [init] Resolving type given FTBA
    [init] FTB modpack ID map[value:35], version ID map[value:37] is ready to go
    jq: error: Could not open file version.json: No such file or directory

At that point the container crashes and goes into CrashLoopBackOff.  

Without the version included, it says 

    [init] Resolving type given FTBA
    jq: error (at :0): Cannot iterate over null (null)
    [init] ERROR unable to resolve latest modpack version ID for modpack map[value:35]

**Comment by itzg** [comment]
Currently the chart issue you reported is breaking this

https://github.com/itzg/minecraft-server-charts/issues/8

**Comment by itzg** [comment]
@cclloyd since this is now fixed in the chart, please change your values yaml to

```yaml
minecraftServer:
  type: FTBA
imageTag: multiarch
extraEnv:
  FTB_MODPACK_ID: 35
  FTB_MODPACK_VERSION_ID: 37
```

**Comment by cclloyd** [comment]
Fixed.  Works with those values.
