### ISSUE TITLE
Will running start-deployForge from within docker exec -it <name> /bin/bash/ setup Forge?

### ISSUE THREAD

**Issue by Dartellum** [itzg/docker-minecraft-server#582]
I deployed a server locally for the family. My wife has put a lot of time into her seventh home (she loves building them). When I deployed, I just deployed as plain vanilla. I would like to add Forge to the server. I have added to the clients already and the mods I have enabled are working but some require the server to have Forge as well. I would like to keep the existing world and add Forge to the server. I could copy|backup the Forge server files to my mounted data folder (could also backup the world there?), rebuild the container with TYPE=FORGE, and copy the existing world files back over?

Would running start-deployForge work? Or, can I change one of the files to point to the Forge file?  I am hopeful I can without.

**Comment by itzg** [comment]
Re-creating the container, pointing the `/data` volume at the same directory, and setting TYPE=FORGE will simply take care of it. (You'll just end up with an extra vanilla server jar sitting there.) As you mentioned, backing up the data directory before doing all that will be good just in case something goes wrong.

**Comment by itzg** [comment]
...as for running that script directly, it expects to be invoked in sequence with the others, so it wouldn't have done quite what you wanted.

**Comment by Dartellum** [comment]
Okay, rebuilt the thing, after copying my world off to another location. I changed the name of the folder in my data folder and set LEVEL equal to that new name. Loaded right up at the spot I was in. Well, I had to put the mods on the server that are on my client. So, I need to stay mindful of that now. My son has mods the length of football field (he has played since the beginning). :)

**Comment by itzg** [comment]
Ah yes, I tend to play vanilla servers, so I forget how many mods are out there until I try a [Feed the Beast](https://www.feed-the-beast.com/) modpack.

Good to close the issue?

**Comment by Dartellum** [comment]
Yes, I will close this issue. :)
