### ISSUE TITLE
OPS and WHITELIST variables don't work with FTB

### ISSUE THREAD

**Issue by jcgruenhage** [itzg/docker-minecraft-server#584]
FTB looks for these files in another location, so it breaks.

**Comment by itzg** [comment]
Sorry for the delay. This fix is now pushed to Docker Hub. Let me know if it still doesn't seem to work.

**Comment by champ8644** [comment]
For some reason, I would like to play Minecraft server on Forge before 1.17, which need to use itzg/minecraft-server:java8-multiarch version. I know this is resolved on latest version, but this issue still presented on that version, so my question is what could I do to be able to whitelist on java8-multiarch version?
