### ISSUE TITLE
[init] Unable to compute URL for 1.7.10--1.7.10

### ISSUE THREAD

**Issue by AtomJon** [itzg/docker-minecraft-server#587]
When i use the command:
<CODE>
sudo docker run -it -d -v /home/john_doe/mc_server/ThaumiCraft/ -p 25565:25565 --name mc -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.7.10 itzg/minecraft-server
</CODE>
and attach, i only get this:
`
curl: (6) Could not resolve host: files.minecraftforge.net
cat: can't open '/tmp/forge.json': No such file or directory
/start-deployForge: line 24: [: =: unary operator expected
[init] Downloading 1.7.10--1.7.10
[init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10--1.7.10/forge-1.7.10--1.7.10-installer.jar
curl: (6) Could not resolve host: files.minecraftforge.net
[init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-/forge-1.7.10--installer.jar
curl: (6) Could not resolve host: files.minecraftforge.net
[init] Unable to compute URL for 1.7.10--1.7.10
`

and the docker closes.

When i try to specify the url:
`
sudo docker run -it -d -v /home/doe_john/mc_server/ThaumiCraft/ -p 25565:25565 --name mc -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.7.10 -e FORGE_INSTALLER_URL=https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-installer.jar itzg/minecraft-server
`
Then it can't resolve the host:
`
[init] Downloading https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-installer.jar ...
curl: (6) Could not resolve host: files.minecraftforge.net
[init] Failed to download from given location https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.4.1558-1.7.10/forge-1.7.10-10.13.4.1558-1.7.10-installer.jar
`

Im using ssh to acces an CentOS x86_64.
Please send help

**Comment by itzg** [comment]
I'm afraid you have some kind of DNS issue with your Docker system since it can't resolve the forge website. I can't help with that since DNS always works fine for me. Perhaps search for "docker dns centos firewall" solutions.

**Comment by AtomJon** [comment]
Ok, thanks. I'l look into that

**Comment by AtomJon** [comment]
And it worked. Thanks for your time and effort, have a great day
