### ISSUE TITLE
pi 3 install

### ISSUE THREAD

**Issue by thelostinthought** [itzg/docker-minecraft-server#589]
I'm trying to do a quick basic install on a pi 3b+. nothing fancy no mods.
I tried 
"$docker run -d -it -e EULA=TRUE -p 25565:25565 --name mc itzg/minecraft-server"
 "$docker container ls" returned no containers running.
 "$docker logs mc" returns 
'standard_init_linux.go:211: exec user process caused "exec format error"'

I'm not sure what to do next, but this feels like a readme error or something deeper in the code.  I seen some closed issues with this in the past talking about multi arch support, but they made it sound like this was fixed.

**Comment by SuNNjek** [comment]
You need to pull the multiarch image: `itzg/minecraft-server:multiarch`

**Comment by thelostinthought** [comment]
thank you. that worked.
