### ISSUE TITLE
Can't see console.

### ISSUE THREAD

**Issue by japietru2004** [itzg/docker-minecraft-server#593]
Is there option to enable console to be visible for eye - server console. other then bash of docker

**Comment by japietru2004** [comment]
I mean is there option to have server console in docker management.

**Comment by itzg** [comment]
I'm still not quite sure what you mean. If you mean the Minecraft server console, then this should help

https://github.com/itzg/docker-minecraft-server#interacting-with-the-server

**Comment by japietru2004** [comment]
I wasn't knowing how to attach server console, And can I attach console on my servers that are already running? Without rcon access enabled

**Comment by itzg** [comment]
Again, if you look at

https://github.com/itzg/docker-minecraft-server#interacting-with-the-server

you are left with the option of using `docker attach`; however, I would recommend leaving rcon enabled since it is a much easier way to access the minecraft server console.

**Comment by japietru2004** [comment]
servers seam to crash when I use -it as start parametr

**Comment by japietru2004** [comment]
cockpit server template from image - I have settings copied for easier management 
![obraz](https://user-images.githubusercontent.com/51274570/88287200-44fffb00-ccf2-11ea-83fb-661f04eaec74.png)

**Comment by itzg** [comment]
I'm not familiar with cockpit, so can you translate the name of that field. The `-it` argument is passed to the `docker run` and not as an argument to the container itself. 

Why don't you want to use rcon? It is much simpler.

**Comment by itzg** [comment]
I found an English screenshot. That's the wrong field for that setting and you already checked the correct one. Do you know how to do an "attach" with Cockpit? I am not able to support third party management software that I have not used.

**Comment by japietru2004** [comment]
vockpit visualixates docker data, it is somehow customizable, and I not sure how to attach  it tells something is not enable. I remember it starts with "T".

**Comment by itzg** [comment]
Maybe "TTY"? There didn't seem to be an checkbox for that in Cockpit. Does it have a way to "exec" a command in a container?

**Comment by japietru2004** [comment]
![obraz](https://user-images.githubusercontent.com/51274570/88380155-4db10980-cda4-11ea-8483-b272b3cd26cc.png)

**Comment by itzg** [comment]
I think you need to contact Cockpit for support since the problems are not specific to this repo. You need to have them explain how to create a container with the equivalent of `-i -t` and they need to confirm how to do `docker attach` to that.

**Comment by japietru2004** [comment]
I will try, if they have any support for cockpit, it is community handled

**Comment by itzg** [comment]
Well, I'm the only one providing support of this repo, so they will easily outnumber me :) .

**Comment by japietru2004** [comment]
I will try, if they have any support for cockpit, it is community handled
