### ISSUE TITLE
Way to pass java arguments ?

### ISSUE THREAD

**Issue by v0idp** [itzg/docker-minecraft-server#594]
I would like to pass some of java arguments to the java command when the server starts. is there a environment variable which allows me to do so ?

**Comment by itzg** [comment]
JVM options

https://github.com/itzg/docker-minecraft-server#jvm-options

and any other arguments passed after the image name are passed along to the java invocation.

**Comment by v0idp** [comment]
thank you!

**Comment by featherfurl** [comment]
Would it be possible to provide some syntax examples in the documentation? I've tried several variations on copying JVM options from my non-dockerized server start script and none of them seem to work.

**Comment by itzg** [comment]
@featherfurl please open a new issue with more specifics, but first refer to the section I linked above.
