### ISSUE TITLE
More startup script naming options

### ISSUE THREAD

**Issue by nrgbistro** [itzg/docker-minecraft-server#595]
I appreciate the addition of the `USE_MODPACK_START_SCRIPT=false`, but it does not seem to solve the issue I've been having. When trying to update my ATM5 server, I get `Please make sure you are using the server version of the FTB modpack!`. After changing the startup script's name from `startserver.sh` to `ServerStart.sh`, the error goes away and the pack installs and starts correctly. Would it be possible to add more names to the startup script of the container? It looks like it could be added here: 
```
entryScriptExpr="
  -name ServerStart.sh
  -o -name ServerStartLinux.sh
  -o -name LaunchServer.sh
  -o -name server-start.sh
  "
```
(in `start-deployFTB`)

**Comment by itzg** [comment]
Yes, that could easily be added there. You're welcome to create a PR for that too.
