### ISSUE TITLE
Installed Docker version on windows using data host path, added mods, mods seem to load, but no mods show

### ISSUE THREAD

**Issue by dmitrye** [itzg/docker-minecraft-server#604]
I've setup Docker instance using the following startup commands:

`docker run -d -p 25565:25565 -e EULA=TRUE -e MODE=creative -e TYPE=FORGE -v d:/minecraft/data:/data --name testmc itzg/minecraft-server`

The h:/minecdaft/data folder contains a /mods folder with zip files of the mods. I've tried different mods etc. IT SEEMS like they are being loaded because when I monitor the logs of the container I can see custom files being loaded (different files based on the type and size of the mods). What I'm not seeing is the mods activated when I connect to the server from my MC Java App. Does the client also need to be modified? I could not find anything in the documentation here that would indicate any additional changes.

FYI - I've tried different run configurations w/o FORGE type and W/O MODE and the same results.

TIA

**Comment by itzg** [comment]
Yes, forge mods have to be loaded both on the client and server.
