### ISSUE TITLE
Current Version 1.7.0 Java edition via docker connection issue to Mojang Auth Servers for locally hosted Minecraft servers on any local client

### ISSUE THREAD

**Issue by finndo77** [itzg/docker-minecraft-server#605]
Ok, so long/short description of the situation, if you only care about the issue, skip to the next paragraph.

I moved to a new house about 30 miles away and decided to update my minecraft docker images as I haven't in 5+ weeks, before I bring everything up, and since then everything has been bad. initially I had a new router, but removed that and setup my original config from the old house as there is an issue with the current firmware on the new one that prevents reaching externally available services from an internal device (even when using the external IP), but that is a different story.  I tried a lot of network troubleshooting until I discovered that my Plex server was working fine.

What happens is that your servers ping fine and report the correct number of active users in the official minecraft launcher, but when you try to connect, it fails on the encryption part (I tried using oracle java on the linux clients, but the launcher requires openjdk apparently, so I tested in Windows 10 machine that had oracle JRE installed and same issue).  The error message is "Authentication servers are Down. Please try again later."

I can connect to publicly hosted java instances elsewhere, but not internally hosted.  I will not be able to test if someone externally can connect until about 10 hours from now, at the earliest.

The launcher logs in fine.

I can load or create single player worlds without issue.

The logs show "connecting to server (gives IP address)" and nothing else.

the failing image I am using is: c8662545ce13 324MB
currently I have rolled back to a 5 week old working version, image: 2cc47309f5c9 302MB

**Comment by itzg** [comment]
That's a strange issue to be caused by the container itself. Some security vulnerabilities were reported recently (maybe within last 5 weeks?), so perhaps package upgrades have somehow altered your behavior...however, latest image works for many users including myself. 

In any case, thanks for providing an image ID that works for you since that'll help me narrow down possible diffs.

**Comment by finndo77** [comment]
I know, the container was the last thing I checked (obviously, since that made it work), because I could not find anything online about it being an issue.  And I know a lot of people use this image.  A LOT.

I have 3 containers built from the same image, all with the issue, I tried with and without Optifiine, I have no mods and just set a url for a resource pack in server.properties on them after this issue started.

I use this command line in a bash script to deploy the containers (modified by instance name and I adjust the port number for each container)

`docker run -d -e INIT_MEMORY=1G -e MAX_MEMORY=4G -e ICON=/mnt/Adata-512GB-M2/minecraft/girls-world/icon.png -e WHITELIST=player1,player2,player3 -e EULA=TRUE -p 25570:25565 -v /mnt/Adata-512GB-M2/minecraft/girls-world:/data -v /etc/timezone:/etc/timezone:ro --name mc-girls-world itzg/minecraft-server`

I think 4Gigs of RAM is a bit of overkill for a server that has 4 max players, but I intended on opening it up to my daughters' classmates once they were comfortable with playing (we all just started the end of May with playing minecraft)

if you need anything, the environment is pretty static, and I have a backup run every 15 minutes of the game data, I can put the tar up somewhere if you want to deploy the image to a container using exactly what I used, that could possibly eliminate a weird networking issue I haven't identified.

**Comment by itzg** [comment]
I realized I can't narrow down the image with the short ID. Can you provide the output of `docker image inspect` given the image that does work?

**Comment by finndo77** [comment]
bad image: c8662545ce135bf3630215f4f643cf105996807dbcc5dbeb7d77a5cf905a8f90
good image: 2cc47309f5c9149af41049ae58990acdd55478af9a73a4d8c924a27335b4ae75

**Comment by itzg** [comment]
I'm sorry, I should have clarified I wanted the output of `docker image inspect 2cc47309f5c9` since it provides the sha256 and a few other helpful details.

**Comment by finndo77** [comment]
np, I thought about posting the whole output :)  I redirected the output to a file...

pm with a link to dropbox incoming

**Comment by finndo77** [comment]
well maybe I don't have a backup of the bad image... looks like my backup cleanup script has been failing to purge the old backups and the drive filled up, you will never guess when...  2 hours before i shut the server down and moved it to the new house, so my last successful backup is from before I updated the image.  I can deploy a new world from the image that is not working and back it up though (makes about a 350MB tar file on a clean world) if you are unable to reproduce the issue locally.

**Comment by itzg** [comment]
Both outputs you provided will let me narrow down the range of commits, so that's fine to not have the bad image.

**Comment by finndo77** [comment]
ok, let me know if you need the world, thanks for looking into this, hope it is not a rabbit hole.

**Comment by itzg** [comment]
FYI, using the image info you provided here is the list of commits that happened in between

https://github.com/itzg/docker-minecraft-server/compare/c4c3613874011129ff1c54e989660c92abac0de9...4fe55b5a28e6928992df41a9912a0984fc6d8c6d

however, I'm guessing it was this one where I was fixing security vulnerabilities due to older packages

https://github.com/itzg/docker-minecraft-server/commit/3b2b98b9fe72d46e5a264a139f5de254baca1ee8

To confirm that theory can you try these two images (before and after that change):

```
itzg/minecraft-server@sha256:24f407f9bf6203dbda06ae43bb98c9e70d6fc467fe6f613e42c4af80942984e7
itzg/minecraft-server@sha256:497682ad1a78afa3e0056959ef6c5c4449e376a0abe74c01fba8cffb3a24ce5c
```

**Comment by finndo77** [comment]
sorry for the delay, I'm still unpacking

this one started up and I was able to connect and log in
docker run -d -e INIT_MEMORY=1G -e MAX_MEMORY=2G -e WHITELIST=BGFuryk -e
EULA=TRUE -p 25550:25565 -v /mnt/Adata-512GB-M2/minecraft/test:/data -v
/etc/timezone:/etc/timezone:ro --name mc-test itzg/minecraft-server@sha256
:24f407f9bf6203dbda06ae43bb98c9e70d6fc467fe6f613e42c4af80942984e7

this one started up and I was able to connect and log in
docker run -d -e INIT_MEMORY=1G -e MAX_MEMORY=2G -e WHITELIST=BGFuryk -e
EULA=TRUE -p 25551:25565 -v /mnt/Adata-512GB-M2/minecraft/test2:/data -v
/etc/timezone:/etc/timezone:ro --name mc-test2 itzg/minecraft-server@sha256
:497682ad1a78afa3e0056959ef6c5c4449e376a0abe74c01fba8cffb3a24ce5c

Because of this I tested the latest (same one already on my machine) and it
also ran and i was also able to log in on it.
docker run -d -e INIT_MEMORY=1G -e MAX_MEMORY=2G -e
ICON=/mnt/Adata-512GB-M2/minecraft/first-world/icon.png -e
WHITELIST=BGFuryk,FrozenMermaid,HotWheelsGirl,r3d3k3r -e EULA=TRUE -p
25560:25565 -v /mnt/Adata-512GB-M2/minecraft/first-world:/data -v
/etc/timezone:/etc/timezone:ro --name mc-first-world
itzg/minecraft-server:latest
11ec655b4b6702f564a457c0bdeada3e3b37ab3887180d2d2681cfc47c25efe9

Nothing has changed on my end this time, do you think it is something to do
with the Mojang auth servers because I moved into a new house and upgraded
the imagers before logging in the first time?  Or did the "latest" change
and docker pulled an updated version?

Joel Perry
Comptia A+
Comptia Network+
MCPS - Microsoft Certified Professional
MCNPS - Microsoft Certified Network Professional
MCTS - Microsoft Certified Technical Specialist
IBM eServer Certified Specialist - AIX
VCP - VMware Certified Professional
AWS - Developerwbcgyagsgjvzhagsv
ywgwhwhwhhwwgwgc
Splunk Certified

----------------------------------------------------------
1984
At the Winter USENIX/UniForum meeting, AT&T describes its support policy
for Unix:
"No advertising, no support, no bug fixes, payment in advance."

----------------------------------------------------------

**Comment by itzg** [comment]
I was actually thinking of suggesting to try the very latest image since I was hopeful a package update that broke your setup would get updated again to fix it. 

So, I guess it's a mystery whether it's the packages or the auth servers. Either way I'm glad to hear you're moved and back to a fully operational Minecraft server :)

**Comment by finndo77** [comment]
Thank you, there was much screaming and wailing and gnashing of teeth in
the house!

I have read about the security lock from the auth servers previously, I
guess they make a 2 way auth token when you connect to a server and if
something changes from one end it blocks you, but the only info I could
find about it said to log on to account.mojang.com from the new location
and it resets the auth token on their side to your current location.  This
did not work for me though.

Now I need to setup a Proxy/PAC filter for my girls' laptops to use since
Mojang blocks my current VPN from the auth servers too. (at least it was,
maybe I'll get connected to different servers from here and get lucky.

Again, I really appreciate your assistance, if it was on my side I don't
understand how reverting images makes the new image work, unless that is
what it needed to update the auth tokens... (which still doesn't make
sense, but I can at least understand why it worked)  if it was on Mojang's
side I can understand what happened, but I'm not sure exactly how to
resolve it next time without trying 50 different things again.  :)

Joel Perry
Comptia A+
Comptia Network+
MCPS - Microsoft Certified Professional
MCNPS - Microsoft Certified Network Professional
MCTS - Microsoft Certified Technical Specialist
IBM eServer Certified Specialist - AIX
VCP - VMware Certified Professional
AWS - Developer
Splunk Certified

----------------------------------------------------------
1984
At the Winter USENIX/UniForum meeting, AT&T describes its support policy
for Unix:
"No advertising, no support, no bug fixes, payment in advance."

----------------------------------------------------------

**Comment by finndo77** [comment]
Please close this issue, I have had no further similar issues.
