### ISSUE TITLE
Internal Exception: io.netty.channel.unix.Error Connection reset by peer

### ISSUE THREAD

**Issue by mrtntome** [itzg/docker-minecraft-server#606]
When non-local players connect to the server, they get kicked after a while.
The get the error message:

Internal Exception: io.netty.channel.unix.Error Connection reset by peer

Searched over the internet for answers, can't find a consistent answer.

**Comment by itzg** [comment]
I haven't noticed that one either. Let's see if anyone else comes across this and can post advice.

**Comment by JosephCW** [comment]
Am currently running into this issue. Running docker on openSUSE, default java.

**Comment by itzg** [comment]
Now that I see this again, it's probably something to report upstream at https://bugs.mojang.com/projects/MC/summary

**Comment by Braydon64** [comment]
Same exact issue for my new Java server I created on 1.16.4. I can connect just fine when on the same LAN as the server but anywhere else & it just disconnects after about 30 seconds. I also run a Bedrock Edition server on a different VM on the same device & it works flawlessly.

**Comment by phynias** [comment]
anyone get figure this out? recently started using this and having the same problem.

**Comment by JosephCW** [comment]
> anyone get figure this out? recently started using this and having the same problem.

The 'solution' for me was to use the internal IP address of the server and not the external IP. I also found that none of my players had this issue and that it seemed to happen to any computer within my own network (all accounts coming from the same external IP connecting to the same external IP)

**Comment by ItsZelix** [comment]
Same, I have a modded 1.16.5 server(IceAndFire), and I'm on a different network rn, and each time I try connecting, it kicks me after about 30 secs. Anyone know a fix?

**Comment by SPREEKDOS** [comment]
> Same, I have a modded 1.16.5 server(IceAndFire), and I'm on a different network rn, and each time I try connecting, it kicks me after about 30 secs. Anyone know a fix?

I installed openssl from the terminal and it got fixed for me.

**Comment by TaraJura** [comment]
A lot of comments but no one answered :/ do you fix it already guys ?

**Comment by itzg** [comment]
Intermittent networking issues are not influenced by this image and beyond its control to fix. Please search issues/forums for the server type you are using.

**Comment by AlloyGamer** [comment]
so I restarted my computer and it fixed the problem

**Comment by arrow501** [comment]
I got the same exception when players tried connecting from an external network. Turns out my ISP was either blocking or rate limiting incoming traffic on default minecraft port (25565). Forwarding port 80-> 25565 seems to fix the issue.
But my players need to specify a port when connecting by
ip.ip.ip.ip:80
This is far from ideal, but works

**Comment by mperf** [comment]
I can confirm that the problem was solved by changing the default port to another. Thanks @arrow501
