### ISSUE TITLE
Can't locate latest paper build

### ISSUE THREAD

**Issue by DillFrescott** [itzg/docker-minecraft-server#607]
'[init] Resolved version given LATEST into 1.16.2

[init] Resolving type given PAPER

[init] Downloading Paper 1.16.2 (build latest) from https://papermc.io/api/v1/paper/1.16.2/latest/download ...

curl: (22) The requested URL returned error: 404

[init] ERROR: failed to download from https://papermc.io/api/v1/paper/1.16.2/latest/download (status=0)'

**Comment by DillFrescott** [comment]
The link leads to an api 404 error through the browser as well. I guess the link needs to be updated

**Comment by james-d-elliott** [comment]
There is no 1.16.2 paper build that has been officially published. You can use the second URL if you want to however I highly advise reading the first link in it's entirety and backup of all worlds before using it. 

https://github.com/PaperMC/Paper/pull/4123

https://cdn.discordapp.com/attachments/555469074080202765/743313314167390208/1.16.2-r2.jar

**Comment by itzg** [comment]
I'll improve the error message there and have it provide the list of published versions that the papermc API is providing.

**Comment by itzg** [comment]
Latest image now clarifies the failure and offers a solution:

```
[init] Downloading Paper 1.16.2 (build latest) from https://papermc.io/api/v1/paper/1.16.2/latest/download ...
[init] ERROR: 1.16.2 is not (yet) published by PaperMC
[init]        Set VERSION to one of the following:
[init]        1.16.1, 1.15.2, 1.15.1, 1.15, 1.14.4, 1.14.3, 1.14.2, 1.14.1, 1.14, 1.13.2, 1.13.1, 1.13-pre7, 1.13, 1.12.2, 1.12.1, 1.12, 1.11.2, 1.10.2, 1.9.4, 1.8.8
```

**Comment by DillFrescott** [comment]
Ok. Thanks guys!
