### ISSUE TITLE
Error with CurseForge/Forge: unzip: short read

### ISSUE THREAD

**Issue by dcramer** [itzg/docker-minecraft-server#608]
Hit this using a standard CF setup, as well as another GENERIC_MODPACK setup I found as an example here. I've confirmed various permissions and everything seems fine.

Using image build 1.8.0.

```
[init] Resolved version given 1.12.2 into 1.12.2
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] Unpacking FTB server modpack /modpacks/RLCraft Server Pack 1.12.2 - Beta v2.8.2.zip ...
unzip: short read
.
[init] Please make sure you are using the server version of the FTB modpack!
```

Relevant config:

```
      VERSION: "1.12.2"
      INIT_MEMORY: "1G"
      MAX_MEMORY: "6G"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "/modpacks/RLCraft Server Pack 1.12.2 - Beta v2.8.2.zip"
```

**Comment by dcramer** [comment]
Example using Forge with GENERIC_PACK:

```
MESSAGE: Considering library org.apache.maven:maven-artifact:3.5.3
MESSAGE: Downloading library org.apache.maven:maven-artifact:3.5.3
MESSAGE: Trying unpacked library org.apache.maven:maven-artifact:3.5.3
Extracting: /forge-1.12.2-14.23.5.2838-universal.jar
To:          /data/./forge-1.12.2-14.23.5.2838-universal.jar
The server installed successfully, you should now be able to run the file forge-1.12.2-14.23.5.2838-universal.jar
You can delete this installer file now if you wish
[init] Finding installed server jar...
[init] Using server forge-1.12.2-14.23.5.2838-universal.jar
unzip: short read
```

**Comment by dcramer** [comment]
Looks like the core issue is if you have spaces in the name. Maybe just missing quotes around the commands.

**Comment by itzg** [comment]
Yes, it looks like it probably the spaces in the filename you provided. Even Chrome doesn't like spaces in filenames and downloaded the file as "RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip" on my Windows system.

I'll work on quoting the filename/paths in the CF_SERVER_MOD area.

**Comment by dcramer** [comment]
In case anyone else stumbles upon this, I ended up having to use the GENERIC_MODPACK approach. I dont know if thats actually needed, but the detection for CF looks for things not available in the server pack for RLCraft.

Here's the relevant config I ended up with to get it running:

```
      INIT_MEMORY: "1G"
      MAX_MEMORY: "6G"
      VERSION: "1.12.2"
      TYPE: "FORGE"
      FORGEVERSION: "14.23.5.2838"
      GENERIC_PACK: "/modpacks/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip"
```

**Comment by itzg** [comment]
I added a feature recently for modpacks with broken or missing start scripts. It can be activated by using

```
    USE_MODPACK_START_SCRIPT: "false"
```

**Comment by itzg** [comment]
Oh yeah, I've been down this rabbit hole before. That version of RLCraft server zip is all kinds of broken. It's also missing a forge installer. I'll fix the spaces-in-filename handling, but glad to hear the GENERIC_PACK solution works for modpacks like this.

**Comment by dcramer** [comment]
Yeah once I figured out the spaces issue the error messages made it super obvious, and I found the GENERIC_MODPACK via another closed issue here.

**Comment by itzg** [comment]
Latest image now handles spaces in the `CF_SERVER_MOD` filename.
