### ISSUE TITLE
server unable to locate jar after hard restart

### ISSUE THREAD

**Issue by FrankMormino** [itzg/docker-minecraft-server#609]
Weird issue - server running fine for months then last week after power outage container tried to start back up and kept saying cannot locate install forge server jar

I stopped container and removed it as I have mapped volumes so a new docker run should bring it back up with no issues.
However, I am seeing issue with unable to locate ``minecraft_server.1.12.2.jar``
logs - 
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx. 13 1000 1000 4096 Aug 12 17:11 /data'
[init] Resolved version given LATEST into 1.16.2
[init] Resolving type given FTBA
[init] FTB modpack ID 35, version ID 37 is ready to go
[init] ERROR unable to locate the installed forge server jar
minecraft_server.1.12.2.jar

```

docker run command
`docker run -d -p 25566:25565 -e TYPE=FTBA -e FTB_MODPACK_ID=35 -e EULA=TRUE -e MEMORY=10G -v /opt/minecraft/newrev:/data --name newrev itzg/minecraft-server:multiarch`

ls of /data directory

drwxrwxrwx.  3        27 Jul 12 18:32 astralsorcery
drwxrwxrwx.  2      4096 Aug  9 00:15 backups
-rwxrwxrwx.  1         2 Aug  8 22:15 banned-ips.json
-rwxrwxrwx.  1         2 Aug  8 22:15 banned-players.json
-rwxrwxrwx.  1     16310 Aug  8 22:15 crafttweaker.log
-rwxrwxrwx.  1      1007 Aug  8 22:13 downloader.log
-rwxrwxrwx.  1         0 Jul 12 18:30 downloader.log.lck
-rwxrwxrwx.  1        65 Jul 12 18:30 eula.txt
-rwxrwxrwx.  1   9073324 Jul 12 18:30 ftb-installer
drwxrwxrwx.  3        20 Jul 12 18:32 journeymap
drwxrwxrwx.  4        40 Jul 12 18:32 local
-rwxrwxrwx.  1      1367 Jul 12 18:31 log4j2.xml
drwxrwxrwx.  3      4096 Aug 11 20:34 logs
**-rwxrwxrwx.  1  30222121 Jul 12 18:31 minecraft_server.1.12.2.jar**
-rwxrwxrwx.  1       272 Aug  8 22:15 ops.json
-rwxrwxrwx.  1        15 Jul 12 18:31 options.txt
drwxrwxrwx.  2         6 Jul 12 18:31 patchouli_books
-rwxrwxrwx.  1         2 Aug  8 22:12 pregenData.json
drwxrwxrwx.  2        85 Aug  8 22:13 scripts
-rwxrwxrwx.  1      4992 Aug  8 22:13 server-icon.png
-rwxrwxrwx.  1      1170 Aug  8 22:15 server.properties
drwxrwxrwx.  2         6 Jul 12 18:32 snapshots-server
-rwxrwxrwx.  1      1613 Aug  8 22:17 usercache.json
-rwxrwxrwx.  1       834 Jul 29 23:50 usernamecache.json
-rwxrwxrwx.  1    549319 Aug  8 22:13 version.json
-rwxrwxrwx.  1         2 Jul 12 18:32 whitelist.json
drwxrwxrwx.  2        23 Aug  8 22:12 woot
drwxrwxrwx. 23      4096 Aug 12 13:04 world

Also using latest multiarch tag from 9 days ago
`itzg/minecraft-server            multiarch              a458b9a1adef        9 days ago          488MB`

**Comment by itzg** [comment]
It's actually looking for a forge jar since that is actually what gets launched and wraps up the official server jar. If you remove the hidden file `.ftb-installed` from that directory then it'll force it to re-download the FTBA installer and install the forge jar.

**Comment by FrankMormino** [comment]
Let me try that and get back to you shortly. Thanks for expedited feedback!

**Comment by FrankMormino** [comment]
Your fix worked perfectly - thank you!
