### ISSUE TITLE
Autopause doesn't work together with UID

### ISSUE THREAD

**Issue by Mask** [itzg/docker-minecraft-server#611]
I was having trouble getting autopause to work. I kept getting
```
[Autopause loop] Failed to start knockd daemon.
[Autopause loop] Possible cause: docker's host network mode.
[Autopause loop] Recreate without host mode or disable autopause functionality.
[Autopause loop] Stopping server.
```
it turns out the problem was the `sudo` in `autopause-daemon.sh`- I had set UID in the environment preventing the sudo from working.

Not sure the best way to fix this, maybe at least add a sanity check to `start-autopause` ?

**Comment by Tailslide** [comment]
No matter what I try I get it failing with ```sudo: you do not exist in the passwd database```

**Comment by itzg** [comment]
cc @Oekn5w

**Comment by Oekn5w** [comment]
@Mask This error is not in the current image; I've since updated the images (latest and multiarch separately, a few months ago) to have a selectable interface for the deamon. Additionally a non-default UID was working when I tested it last weekend. Please repull your image and re-check.

**Comment by Mask** [comment]
Ok I figured it out. I was settings UID and GID to already existing values, e.g. setting GID to 100 (group `users`).

This won't work since only `minecraft` is added to sudoers. 

Closing this since it is clearly a corner case.
