### ISSUE TITLE
Unable to find FTBA ID's

### ISSUE THREAD

**Issue by pamendoz** [itzg/docker-minecraft-server#612]
Now that the NeptuneFTB services are commisioned, I am unable to find the ID's for the FTB packs.

**Comment by pamendoz** [comment]
I actually found that there is a REST API that can do this thing:

https://api.modpacks.ch/public/modpack/search/5?term=direwolf

Querying this URL returns the ID's of the modpacks based on a term (in this example, direwolf).

This query in particular returns the following:

`{
    "packs": [
        14,
        24,
        31
    ],
    "total": 3,
    "limit": 5,
    "refreshed": 1598219293
}`

**Comment by pamendoz** [comment]
This should be documented for future users.

Also amazing work on this Docker image, regarding the latest server types.

**Comment by itzg** [comment]
Excellent find! I'll re-open this issue to track the documentation change.

**Comment by Logically2ed** [comment]
Don't know if this is what you're looking for but if you go to the FTB/modpack (https://www.feed-the-beast.com/modpack) website each mod has the ID preceding it.

**Comment by itzg** [comment]
Yay, teamwork! I'm pretty sure the modpack ID didn't used to be displayed on the main FTB site, so this solution seems to be perfect. Randomly tested one with FTB_MODPACK_ID=11 for FTB Lite 3.

**Comment by littlediobolic** [comment]
I may be crazy, but I think the FTB site took down the ID's for their modpacks? I cannot for the life of me find them. Here is a picture for reference:

![image](https://user-images.githubusercontent.com/1341157/103359864-accb2680-4a86-11eb-8fe9-0ecfc51fdaa7.png)

Clicking on the modpack doesn't give any relevant info either.

The API @pamendoz mentioned still seems to be functioning though.

**Comment by itzg** [comment]
@littlediobolic you'll need to drill into each particular modpack to see its ID, such as

https://feed-the-beast.com/modpack/ftb_revelation

to see

![image](https://user-images.githubusercontent.com/988985/103366434-3d563680-4a88-11eb-9a71-90f0bf7632d7.png)

**Comment by littlediobolic** [comment]
Whoops!

Researching at work and guess a firewall policy is blocking that specific element from loading. Did it from my phone and its there....

Sorry to bother!

**Comment by MusikPolice** [comment]
It looks like that text element that shows the ID is no longer present. I was able to find an id by inspecting the page with debug tools though. For the Direwolf20 1.16 pack, the ID appears to be 79. 
![image](https://user-images.githubusercontent.com/1799952/141227191-9f2cfbeb-ac66-4279-9486-fd6764aa423c.png)

**Comment by mcfadyeni** [comment]
Still looks like the only way to find the IDs are via inspecting using DevTools; should this be added to the documentation?

**Comment by janderson676** [comment]
I was able to find the id in the inspect but noticed that If you hover over the pack name with the cursor a tooltip shows up with the id
![image](https://user-images.githubusercontent.com/45110192/155819221-7ac1d112-0eee-4a25-88e5-c6af69eb1e61.png)

**Comment by itzg** [comment]
Great find @janderson676 ! I'll reopen this and get the docs updated.
