### ISSUE TITLE
Raspberry pi Minecraft crashes

### ISSUE THREAD

**Issue by larskhansen** [itzg/docker-minecraft-server#613]
Hello,

I've just started playing with this Docker image, so sorry if the issue has already been handled.

I have a "regular" Intel 64bit based Linux machine with Docker. There is no issues here with the Docker image, it just runs perfectly.

But I also have a Raspberry Pi, and this one just does not want to start the image :-/

I'm running it through Docker Swarm with one replica, so there shouldn't be any difference compared to a regular docker.

I'm running the following setup: `docker service create --name minecraft --hostname minecraft --mode replicated -p 25565:25565 --replicas 1 --replicas-max-per-node 1 --mount type=bind,source=/mnt/minecraft,destination=/data -e EULA=TRUE -e UID=1026 -e GID=1023 -e TZ=Europe/Copenhagen itzg/minecraft-server:1.8.0-multiarch`

First it starts of with this log file: `chmod: changing permissions of '/data': Operation not permitted`

Then it moves on preparing the server, identical to how my Intel based server does.

But then it throws this error: 
```
[14:35:51] [Worker-Main-7/INFO]: Preparing spawn area: 2%
2020/08/23 14:35:52 Stopping with rcon-cli
[14:35:52] [Worker-Main-9/INFO]: Preparing spawn area: 2%
[14:35:52] [Worker-Main-9/INFO]: Preparing spawn area: 2%
2020-08-23T14:35:52.822+0200	ERROR	mc-server-runner	ERROR Failed to stop using rcon-cli	{"error": "exit status 1"}
2020-08-23T14:35:52.850+0200	INFO	mc-server-runner	Sending 'stop' to Minecraft server...
2020-08-23T14:35:52.851+0200	INFO	mc-server-runner	Waiting for completion...
```

The docker swarm restarts the service with a new container. The new container also fails and so it repeats itself.

Regards, Lars Hansen

**Comment by itzg** [comment]
I'm wondering if the health check timed out since it seemed to get a stop initiated externally. You can fine tune the health check parameters with docker or use [the convenience environment variable to disable that](https://github.com/itzg/docker-minecraft-server#healthcheck).

Try disabling the health check and see if that allows for the container to startup all the way and stay running.

**Comment by larskhansen** [comment]
It could build with the disable_health_check set to true. But I'm not able to play on the server... I'll look in to it later when I have more time.

Thanks for the tip about health_check.
