### ISSUE TITLE
/mods and /config volumes created even if not needed

### ISSUE THREAD

**Issue by bagobones** [itzg/docker-minecraft-server#616]
The docs indicate at a minimum you need /data mounted, which I have and it works. However, I have noticed that every time I setup this docker it spawns volumes for /mods and /config. Other dockers with optional volumes do not appear to do this, I am not sure what the difference is.

This doesn't seem to hurt anything other than generating some random numbered volumes that appear when browsing your docker volumes.

**Comment by itzg** [comment]
Can you double check you have pulled the latest image since I thought that was fixed 5 months ago.

**Comment by bagobones** [comment]
Looks like after manual deletion of the volumes and pulling the latest they are not recreated..
