### ISSUE TITLE
Error : Can't keep up! Is the server overloaded?

### ISSUE THREAD

**Issue by srgtang** [itzg/docker-minecraft-server#618]
My Nas information

CPU : Intel J1900
RAM: DDR3L 4GB

![1](https://user-images.githubusercontent.com/70360116/91519554-eb60a100-e92d-11ea-8107-5ba70e6c723d.png)

Referring to what is written on github, I built a server in docker through putty as follows.

_**docker run -d \
-v /volume1/docker/minecraft-server:/data \
-d -p 25565:25565 \
--name mc \
-e EULA=TRUE \
-e MEMORY=4G \
itzg/minecraft-server**_

The RAM was allocated 3 GB out of 4 GB, but the following error occurred.
It's not a fatal error to play on the server, but there is a bug that blocks are not crushed immediately and disappears after a while.
So, looking at the docker log, I got the following error, how can I fix it?

 Can't keep up! Is the server overloaded? Running 2022ms or 40 ticks behind

**Comment by itzg** [comment]
I can't provide much support for the server performance itself. What I can suggest though is looking at the per core utilization. That processor type  has a fairly low clock frequency, so I'm suspecting you'll find a core or two is maxed out. 

![image](https://user-images.githubusercontent.com/988985/91560171-fd771b00-e8fe-11ea-8d06-4aa3ba89a71c.jpeg)

**Comment by smithpet001** [comment]
I'm having the same problem with my J3455 which has 4 cores at 1.5 GHz and 8GB RAM. Runs fine, but throws errors. Good enough for me! Maybe one block every 15 minutes or so lags when being broken.

**Comment by itzg** [comment]
I have experienced similar with my RaspberryPi 3 where it'll report that message, but does run fine generally other than a laggy block break or two, as @smithpet001  mentioned.

BTW, if you use `top -1` it'll show the individual cores and again, I'm guessing one of those is maxed out...which is unfortunately typical depending on the CPU class:

```
top - 18:51:17 up 12 days,  5:56,  1 user,  load average: 0.58, 0.84, 0.89
Tasks: 223 total,   1 running, 221 sleeping,   0 stopped,   1 zombie
%Cpu0  : 12.0 us,  3.4 sy,  0.0 ni, 82.5 id,  1.7 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu1  : 11.6 us,  3.8 sy,  0.0 ni, 83.9 id,  0.3 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu2  : 10.7 us,  3.8 sy,  0.0 ni, 83.8 id,  1.4 wa,  0.0 hi,  0.3 si,  0.0 st
%Cpu3  : 11.3 us,  3.4 sy,  0.0 ni, 83.9 id,  1.0 wa,  0.0 hi,  0.3 si,  0.0 st
MiB Mem :  15909.7 total,   4360.6 free,   4648.6 used,   6900.5 buff/cache
MiB Swap:   4096.0 total,   4096.0 free,      0.0 used.  11534.2 avail Mem
```

**Comment by srgtang** [comment]
Thanks you.
