### ISSUE TITLE
Configs inside subdirectories are not copied when hosted in /config

### ISSUE THREAD

**Issue by bbf** [itzg/docker-minecraft-server#620]
Hello,

I noticed that some of my configs when placed in folders inside /config where not being copied to /data/config. Any mod that uses a folder for organization can't have it's config overridden because of:
https://github.com/itzg/docker-minecraft-server/blob/6cfc7e45efdea0b5b03ecaebb017b66d9a42ac2b/start-minecraftFinalSetup#L63

Perhaps changing to -f || -d would be enough? I didn't submit a PR because I don't know if there's a reason why this was implemented like this. Let me know if there's isn't and you would like the PR.

Cheers

**Comment by itzg** [comment]
Yeah, I see what you mean. In fact, looking at that code now I don't like the for-loop going on there and am thinking it should just use rsync like the mods bit above there.

**Comment by itzg** [comment]
...oh and a PR would be great

**Comment by Silthus** [comment]
This will be fixed by #689

**Comment by itzg** [comment]
Latest images now include the change from #689
