### ISSUE TITLE
FTB Sky Factory 3 can't connect to server

### ISSUE THREAD

**Issue by DannyP314** [itzg/docker-minecraft-server#622]
Sorry for any ignorance or lack of information here, I'm brand new to Docker and Ubuntu Server which is where i'm trying to set this container up. I'm also sorry if there's a better place to seek this sort of help. I can successfully run the docker command and start the container but once it is started the status I am getting is (Uptime) (unhealthy) and the minecraft launcher can't find the server on a local machine. It's able to see a different vanilla server when that is set up but not the FTB Modded server.

**Comment by itzg** [comment]
This is a good place to ask such things. The Discord server is good place to ask too.

What `docker run` command line or compose file are you using to launch the FTB Sky Factory 3 server?

**Comment by DannyP314** [comment]
perfect, thanks for getting back as well! this is the docker run line that has the server up currently. it's been up for three hours and still reports unhealthy

docker run -d --name mc-ftb -e EULA=TRUE -e TYPE=FTBA -e FTB_MODPACK_ID=25 -p 25565:25565 itzg/minecraft-server:multiarch  

CONTAINER ID        IMAGE                             COMMAND             CREATED             STATUS                   PORTS                                 NAMES
059c3c5dd887        itzg/minecraft-server:multiarch   "/start"            3 hours ago         Up 3 hours (unhealthy)   0.0.0.0:25565->25565/tcp, 25575/tcp   mc-ftb

**Comment by itzg** [comment]
That looks right. I'll give it a try too.

**Comment by itzg** [comment]
I keep forgetting the FTB modpacks need a lot of memory. I added `-e MEMORY=4G` and that has fixed it for me at least. That's assuming you have sufficient memory available on your host.

**Comment by DannyP314** [comment]
okay great, I'll give that a shot and see if it helps!

**Comment by DannyP314** [comment]
that did it, thank you for your help!

**Comment by itzg** [comment]
Excellent!
