### ISSUE TITLE
Server is crashing when player join

### ISSUE THREAD

**Issue by ArcadeFighter** [itzg/docker-minecraft-server#625]
Hello, i have issue with only 1 server, i made a compose with 8 servers (mixed version and different Java) and only one server is crashing when i join, it throw a core dump and after that it will be restarted and over and over. And i don't see any issue, server was running ok before i switch to Docker.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000000a786, pid=43, tid=0x00007fc620a7db10
#
# JRE version: OpenJDK Runtime Environment (8.0_252-b09) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.252-b09 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 3.16.0
# Distribution: Custom build (Thu Aug 13 12:46:32 UTC 2020)
# Problematic frame:
# C  0x000000000000a786
#
# Core dump written. Default location: /data/core or core.43
#
# An error report file with more information is saved as:
# /data/hs_err_pid43.log
#
# If you would like to submit a bug report, please include
# instructions on how to reproduce the bug and visit:
#   https://icedtea.classpath.org/bugzilla
#
```

This is on the bottom of messages.

**Comment by itzg** [comment]
Can you provide the snippet for that one that fails? It might worth trying one of the other image tags like `adopt11`, `adopt13`, or `multiarch`

**Comment by ArcadeFighter** [comment]
i was trying without snippet and tried `latest` (server version 1.12 custom paper fork). no success

**Comment by itzg** [comment]
You probably need to report an issue with the provider of that custom server. However, trying the other java versions could solve it.

**Comment by ArcadeFighter** [comment]
I found that one plugin dropping server, so issue is solved, thank you for your help.
