### ISSUE TITLE
New pack updating feature doesn't seem to remove config folder

### ISSUE THREAD

**Issue by the-vindex** [itzg/docker-minecraft-server#626]
Just did it as code review, didn't actually try to run the script on production yet:
https://github.com/itzg/docker-minecraft-server/blob/48ccdf128f18061603eb48ce21ee1e59358e941d/start-deployCF#L31

Also nowhere in that diff config is metioned, so I assume it's not deleted.
- Some more stupid mods actually MAY store some data in config
- IIRC some mod like worldedit did something like that in the past
- that I would have to check

**Comment by itzg** [comment]
I think I was initially nervous about deleting user configs from that directory, but now I do remember some modpacks pre-configure things there.
