### ISSUE TITLE
Changing the default RCON password breaks AutoPause's auto save

### ISSUE THREAD

**Issue by wolfen351** [itzg/docker-minecraft-server#627]
Just what the title says - if I change the RCON server's password, then when the autopause pauses, it fails to authenticate and then cannot quicksave the game before pausing it. 

I guess this will possibly cause lost data if the container is shut down while sleeping?

As a workaround, just reset the password and it saves again.

**Comment by wolfen351** [comment]
Just to be clear - the password is set and shown in plaintext in the server.properties file.

**Comment by itzg** [comment]
Are you changing the password with `RCON_PASSWORD` env var or setting it directly in server.properties?

**Comment by wolfen351** [comment]
Setting it directly in server.properties, then spinning up a new container pointing at that data directory

**Comment by itzg** [comment]
The bundled rcon-cli currently assumes the environment variable `RCON_PASSWORD` is set with the password. If you want to avoid keeping both values in sync, you can set `-e OVERRIDE_SERVER_PROPERTIES=true` to have the environment variables update `server.properties`.
