### ISSUE TITLE
MC server in a continual reboot after installing in docker

### ISSUE THREAD

**Issue by Radiance76** [itzg/docker-minecraft-server#628]
Hi,

When I issue the following command 
docker run -d -p 25565:25565 --name mc itzg/minecraft-server

The mc server just starts and then shuts down. if I add the string --restart always, then it will go in a continual loop.
It is as though the server starts and then reads the Eula and then exits cause is cannot apply the core files to run the server like the server properties file, world, nether and other supporting folders.

**Comment by itzg** [comment]
You were close to figuring it out. The EULA must be acknowledged with `-e EULA=TRUE`:

https://github.com/itzg/docker-minecraft-server#eula-support
