### ISSUE TITLE
Spigot download link error temporary

### ISSUE THREAD

**Issue by minakmostoles** [itzg/docker-minecraft-server#629]
Info logs:
sminecraft            | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Sep 13 12:54 /data'
sminecraft            | [init] Resolved version given LATEST into 1.16.3
sminecraft            | [init] Resolving type given SPIGOT
sminecraft            | [init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.16.3.jar ...
sminecraft            |
sminecraft            | ERROR: failed to download from https://cdn.getbukkit.org/spigot/spigot-1.16.3.jar
sminecraft            |        Visit https://getbukkit.org/download/spigot to lookup the
sminecraft            |        exact version, such as 1.4.6-R0.4-SNAPSHOT or 1.8-R0.1-SNAPSHOT-LATEST
sminecraft            |

The problem trying to download a version not yet available.
It would be good if in case of error download the previous version. i see you take the vainilla-version  the oficial  server
https://launchermeta.mojang.com/mc/game/version_manifest.json but in this moment the oficial version is 1.16.3 and the last version de spigot is 1.16.2. 
At the moment I fix the version manually witch VERSION: "1.16.2"

Thank you.

**Comment by minakmostoles** [comment]
The problem is fixed until the next minecraft update. 👍 Spigot 1.16.3 is available now.

**Comment by itzg** [comment]
As you noticed, I wasn't able to address this yet, but at least now I have a bit more time until 1.16.4 breaks things again :)
