### ISSUE TITLE
Magma unable to locate correct version

### ISSUE THREAD

**Issue by DocTiK3r** [itzg/docker-minecraft-server#630]
I have tried using VERSION=1.12.2, VERSION=vade7751 but all appear to try and download version 1.16.3 which one is not available and 2 is not the version specified. Any ideas? Thank you

2020-09-13 18:26:16 | stdout | [init]  Check https://magmafoundation.org/ for available versions
2020-09-13 18:26:16 | stdout | [init] ERROR unable to download version 1.16.3 of Magma
2020-09-13 18:26:16 | stdout | curl: (22) The requested URL returned error: 500
2020-09-13 18:26:16 | stdout | [init] Resolving type given MAGMA
2020-09-13 18:26:16 | stdout | [init] Resolved version given vade7751 into 1.16.3

Is there any way to set up a custom URL for Magma type?

Apologies for the log being upside down

I read post #558 but doesn't seem like the issue is solved or maybe I am doing something wrong

**Comment by itzg** [comment]
Hmm, I see what you mean. Setting `VERSION=1.12.2` is required, but their API endpoint is returning a 500 which indicates an error on their end. Hopefully, they fix that soon. If not, looks like I'd have to switch to their github releases area.

**Comment by DocTiK3r** [comment]
Thank you. I guess is just a waiting game now

**Comment by DocTiK3r** [comment]
Is there an option to download Magma manually and point the server to use that launcher? 
Thank you

**Comment by itzg** [comment]
I haven't tried it myself with Magma, but the `TYPE=CUSTOM` approach probably works:

https://github.com/itzg/docker-minecraft-server#running-with-a-custom-server-jar

**Comment by DocTiK3r** [comment]
Got it working using the TYPE=CUSTOM method. Thank you!

For the 1.12.2 latest magma use this link for those interested.
CUSTOM_SERVER= https://github.com/magmafoundation/Magma/releases/download/v3a65e28/Magma-3a65e28-server.jar
