### ISSUE TITLE
(Question) How to support the author?

### ISSUE THREAD

**Issue by quiquelhappy** [itzg/docker-minecraft-server#633]
Hello!
I'm creating a hosting service with this Docker image and I'm showing every user creating a container with this image the author information, I would LOVE to support itzg. @itzg Have you considered creating an open collective, buymeacoffee or using GitHub sponsors?

Thank you!
By the way, the service in question is purecore.io, using [this repo](https://github.com/purecoreio/machine-supervisor), it's not finished yet but the basics are already working!

**Comment by itzg** [comment]
That's so great to hear. Actually, I do have a Buy Me a Coffee link on my README: https://www.buymeacoffee.com/itzg

I'll be sure to check the locations you provided. Thanks!

**Comment by quiquelhappy** [comment]
Thanks!
