### ISSUE TITLE
Auto-updating of servers should be non-fatal

### ISSUE THREAD

**Issue by ubergeek77** [itzg/docker-minecraft-server#634]
I have a server that keeps failing to download Paper for whatever reason. This prevents the server from starting at all, despite me having a perfectly good Paper .jar on a persistent volume with the rest of the game data.

I have no idea why it's failing to download Paper (despite me being able to download it manually just fine), but diagnosing that is not the point of this issue. The network issue appears to be on my end, but this could also theoretically happen if any of the upstream server download URLs experience outages. I don't believe that service should be denied to the server due to a failed update download (and it definitely shouldn't `exit 3` like it currently does!).

I am still unable to start my server, and I'm currently working at commenting out parts of the scripts in order to allow it to run again.

I would like to request the following features in light of this issue:

- Auto-updating should be done optionally, configured via an environment variable (an opposite counterpart to `FORCE_REDOWNLOAD`)
- Provided a .jar is already available on a persistent volume, the start of the Minecraft server should always take priority over an update, and a failed download should never fatally exit.
- To build on that second point, automatic updates should be detached from the Minecraft server start process; the Minecraft server should start *first* (if able), then a detached download process downloads an updated .jar in the background with a different name, ready for the next container restart.

These changes would avoid any downtime issues in the event of download issues, while still allowing automatic updates in a non-disruptive way.

**Comment by itzg** [comment]
Good point, that re-download logic should be optional, but apparently the change in https://github.com/itzg/docker-minecraft-server/commit/5e75410e7c4244c20fc71bbc3b6a1f9367069c18 was too broad.

For the moment you can use the tag before that change at `itzg/minecraft-server:1.7.0`.

**Comment by itzg** [comment]
It turns out there were a couple of bugs in there, so the latest image now changes the logic to use `FORCE_REDOWNLOAD` properly and does the curl re-download logic correctly.

**Comment by schoentoon** [comment]
As this does seem related. Right now papermc.io seems quite broken, as a result the image doesn't start at all despite me still having a functional paper.jar already present at the same mountpoint it would usually download to. In case of curl failures it should fallback to using this instead imo.

Relevant log
```mc_1  | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    1 1000     1000           556 Sep 21 12:37 /data'
mc_1  | [init] Resolved version given 1.16.3 into 1.16.3
mc_1  | [init] Resolving type given PAPER
mc_1  | [init] Downloading Paper 1.16.3 (build latest) from https://papermc.io/api/v1/paper/1.16.3/latest/download ...
mc_1  | [init] ERROR: failed to contact PaperMC at https://papermc.io/api/v1/paper/1.16.3/latest/download
mc_1  | [init]        curl: (56) OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
mctest_mc_1 exited with code 3
```

**Comment by itzg** [comment]
@schoentoon I did change it already for Paper. Can you double check you have pulled the latest image? If so, adding `DEBUG: "true"` to the environment variables and providing those debug logs will help me a bunch.

**Comment by schoentoon** [comment]
With the current latest image it does indeed seem to be a non issue. Except that I would expect it to be non-fatal using FORCE_DOWNLOAD as well if there's already a valid jar present. I will probably use this flag so it'll automatically update to the latest paper build upon every start, but I wouldn't like this potentially failing due to some network issue somewhere down the line or alike.
