### ISSUE TITLE
Eula issue

### ISSUE THREAD

**Issue by kylewschmitt** [itzg/docker-minecraft-server#635]
Using QNAP and Container Station, im not able to get the Eula to accept when launching. Set command to docker run -d -p 25565:25565 --name mc -e EULA=TRUE itzg/minecraft-server as per your instructions. Container station issue?

![image](https://user-images.githubusercontent.com/71448220/93482711-02ac0200-f8ce-11ea-81fc-71b2b7792969.png)

**Comment by itzg** [comment]
You can set environment variables in that "Advanced Settings" section.

**Comment by kylewschmitt** [comment]
Worked like a charm! Thanks for entertaining my stupidity. I tried doing this after it was initially created and it wouldn't let me adjust the parameters. Thanks again!
