### ISSUE TITLE
Where is the EULA?

### ISSUE THREAD

**Issue by garethsnaim** [itzg/docker-minecraft-server#638]
Hi, really sorry I have googled this to death with no resolution. I won't lie, I hate dockers, its just so confusing for the average person but would really like to get this going.

I am using OMV, with portainer installed, and trying to deploy from there. I put in an environmental parameter of EULA TRUE but this is ignored so the server wont start telling me to agree to it and to goto the text. What text? How do I access this text? 

Also and perhaps its because of portainer I don't know, I can use the docker just once. If I then try to adjust the image, and start the docker again, it says its all running great but I cannot ever access the gui with an err-connection refused. The only way to deal is to delete it entirely and start again. I have 6 other dockers running without this issue.

Any help would be appreciated my kid is at me all the time about it.

**Comment by garethsnaim** [comment]
Ok feel a bit dim I found the file manager and adjusted the eula but this led to another issue. It told me there was the latest server to down load which I did but when it try to start the server it just says ‘server starting’ with a little spinner and that’s it it does not start

**Comment by itzg** [comment]
Since we're being honest, I am unable to support Portainer nor running Docker on media or NAS servers. These solutions have good intentions to simplify Docker, but instead apparently make it much more complex.

On regular Linux with regular Docker, I can start a container and confirm the EULA quite easily:

```
docker run -it -d --name mc -e EULA=TRUE -p 25565:25565 itzg/minecraft-server
```

and output the eula file:
```
docker exec mc cat /data/eula.txt
# Generated via Docker on Sat Sep 26 14:37:35 UTC 2020
eula=true
```

I would recommend reporting an issue with Portainer since this is apparently a usability issue on their part.

**Comment by garethsnaim** [comment]
Hi I think I agree with you! I am not a programmer, but the levels of complexity in getting these apparently easy dockers going is immense. 

I think I am going to attempt to install a limux VM and run it from there. FWIW I got it going in the end server is running, but I cannot access the prefs files to increase ram/change ports etc because its contained in the docker and as I dont have a PHD in computing, I cannot fathom how to get to it.

Spent the last 2 hours trying to convince the docker to store the data in a share I created in OMV, but its having none of it.

**Comment by itzg** [comment]
I think you'll find your docker experience to much more pleasant with a good ol' linux VM. I recommend using Docker's convenience script for installing:

https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script

([they have the same for CentOS](https://docs.docker.com/engine/install/centos/#install-using-the-convenience-script) if not using Ubuntu)

From there you should be able to follow along directly with [the README](https://github.com/itzg/docker-minecraft-server/blob/master/README.md).

**Comment by garethsnaim** [comment]
Well, on balance I think I'll try and keep it simple. I have an dell server here doing nothing, I'll install linux on and just install mc on it rather than any more terrifying docker experiences.

Do you thin ubuntu server would be best for this?

**Comment by itzg** [comment]
I highly recommend Ubuntu. It has served me well (no pun intended) for many years now.

**Comment by garethsnaim** [comment]
Well I tried to install using the instructions after getting to this command

./MCMA2_Linux_x86_64 -setpass [YOURPASSWORD] -configonly

I get

[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: An exception was thrown by the type initializer for System.Console ---> System.TypeInitializationException: An exception was thrown by the type initializer for System.ConsoleDriver ---> System.Exception: Magic number is wrong: 542


I give up, I have to accept my limitations, and practically a whole day trying to make this work obviously means I am way out of my depth.

Back to windows for me.

**Comment by itzg** [comment]
I'm not familiar with that command you show there. In any case, I totally understand when fighting the software totally sucks all the fun out of it.

**Comment by eoware** [comment]
Just connect directly to the docker server and start the container as in the instructions. Portainer is just a front end -- it doesn't change how docker works. Once you start the container, it'll show up in Portainer and you can manage it as usual.
