### ISSUE TITLE
Running on Rasperry Pi 3 crash

### ISSUE THREAD

**Issue by hannesa2** [itzg/docker-minecraft-server#639]
First of all, I want to say thank you for this Docker image.

I tried to start it on my Rasperian with 
`docker run -d -p 25565:25565 --name mc -e EULA=TRUE itzg/minecraft-server`

But `docker ps` shows me no running image !

Having a deeper look with `docker logs -f mc`

> standard_init_linux.go:178: exec user process caused "exec format error"
> standard_init_linux.go:178: exec user process caused "exec format error"

Any idea how to get rid of it ? 
Do I have to compile Docker image for arm architecture ? Does this works ?

**Comment by hannesa2** [comment]
At least I found a way to start on Rasperian with with 
`docker run -d -p 25565:25565 --name minecraft -e EULA=TRUE itzg/minecraft-server:raspberrypi`

but now it has issue with the memory 
![image](https://user-images.githubusercontent.com/3314607/94361305-84acdf80-00b3-11eb-85ac-6f2439cb9278.png)

Btw, this image is 2 years old

**Comment by hannesa2** [comment]
Switching to `multiarch` with command
`docker run -d -e VERSION=1.16.3 -v /home/pi/mincraftData:/data -p 25565:25565 --name minecraft -e EULA=TRUE itzg/minecraft-server:multiarch`

runs into
<img width="927" alt="image" src="https://user-images.githubusercontent.com/3314607/94362038-d7d56100-00b8-11eb-9b96-89924daa0131.png">

**Comment by itzg** [comment]
Oops, I thought I had deleted off the `raspberrypi` tag since the `multiarch` covers that platform. It's deleted now.

As for the final error you encountered, I also haven't been able to run very well on my RaspberryPi 3. I have to lower the `MEMORY` to about 750m.
