### ISSUE TITLE
Running the container in Kubernetes

### ISSUE THREAD

**Issue by Sonlis** [itzg/docker-minecraft-server#642]
Hello there,

I am trying to run the container into a kubernetes pod, however get stuck at accepting the eula. I cannot use the option of "docker run -e eula=true" as kubernetes deploys the pod from a docker image. I tried to change a tiny bit your docker image:

Dockerfile
`FROM itzg/minecraft-server
RUM rm /data/eula.txt
RUN echo "eula=true" > /data/eula.txt`

However it tells me that /data/eula.txt does not exist. 
Do you have a way of accepting the eula before the pod is started ?

Thank you very much for your work !

EDIT: when I say before the pod is started, I mean in the docker image.

**Comment by itzg** [comment]
You'll be pleased to find out that the image does not need to be modified. From the example deployment you'll see that `-e` environment variables need to be translated into the `env` section of the container:

https://github.com/itzg/docker-minecraft-server/blob/master/examples/k8s/using-statefulset.yml#L22-L24

**Comment by Sonlis** [comment]
Oh wow that's more than I asked, thank you very much !
