### ISSUE TITLE
Mods: lucky-blocks - Missing License Information in file Mod File: /data/mods/luckyblock-1.16.1-1.jar

### ISSUE THREAD

**Issue by chuenniger** [itzg/docker-minecraft-server#643]
Hi,

I've installed the luck-blocks module ( https://www.luckyblockmod.com/docs/#/add-ons?id=installing ). 

But when I start the container I get an error: `Missing License Information in file Mod File: /data/mods/luckyblock-1.16.1-1.jar`

Setup: 
* MineCraft: 1.16.3

**Comment by itzg** [comment]
This sounds like an issue to report with the lucky block authors.
