### ISSUE TITLE
Autopause with Spigot, and automatic restarting

### ISSUE THREAD

**Issue by mhbates** [itzg/docker-minecraft-server#650]
How do we get Autopause working properly with Spigot? My server shut down due to Spigot's watch dog thinking it wasn't responding. I'm guessing we just increase the timeout-time in the spigot.yml to some very large number?

On a related note, Spigot actually tries to restart the server, but it can't find the start.sh script, which I imagine is due to the Docker implementation. It looks like the start script (and "start-autopause", which might be the right one in this case) is actually one level up. Can we just point the spigot.yml to this script (i.e. "restart-script: ../start-autopause"), or is it more complicated than that?

**Comment by itzg** [comment]
If Spigot has a watchdog similar to the `max-tick-time` setting described here

https://github.com/itzg/docker-minecraft-server#autopause-experimental

then yes, that needs to be increased or disabled.

That's really strange Spigot would go looking for any particular script, such as `start.sh`. What do they expect to happen when running on Windows? I don't know much about running Spigot, so can only give a vague suggestion to avoid their restart logic and instead "stop" the server and leverage Docker's auto-restart capability.

**Comment by mhbates** [comment]
Setting the max-tick-time to a very large value fixed it. Thank you.
