### ISSUE TITLE
Minecraft server crash with autopause enabled

### ISSUE THREAD

**Issue by wolfen351** [itzg/docker-minecraft-server#651]
I had an interesting situation - minecraft process crashed with an out of memory exception, but the autopause was still happy to accept connections. This leads to the health check passing and the container not restarting, but the minecraft process is also dead, so unplayable.

I would like:
a) The health check to fail in this situation
b) The minecraft process to auto restart on crash (maybe ?)

**Comment by tekook** [comment]
Mine crashes every day with autopause enabled. If the server idles for too long, the server tick checker consideres the server as crashed as soon as a new player connects.

**Comment by TheCatMan2000** [comment]
I'm having the same issue. Here's what my log looks like:

```
...
[08:43:48] [Server thread/INFO]: TheCatMan2000 joined the game
[Autopause loop] Client connected - waiting for disconnect
[08:43:57] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2051ms or 41 ticks behind
[08:44:21] [Server thread/INFO]: TheCatMan2000 lost connection: Disconnected
[08:44:21] [Server thread/INFO]: TheCatMan2000 left the game
[Autopause loop] All clients disconnected - stopping in 3600 seconds
[Autopause loop] No client reconnected - stopping
[09:44:31] [RCON Listener #1/INFO]: Thread RCON Client /127.0.0.1 started
[09:44:31] [Server thread/INFO]: [Rcon: Saved the game]
[09:44:31] [RCON Client /127.0.0.1 #2/INFO]: Thread RCON Client /127.0.0.1 shutting down
[2021-03-13T09:44:31+0000] [Autopause] Pausing Java process
[16:57:53] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 26001940ms or 520038 ticks behind
[16:57:53] [Server Watchdog/FATAL]: A single server tick took 26001.94 seconds (should be max 0.05)
[16:57:53] [Server Watchdog/FATAL]: Considering it to be crashed, server will forcibly shutdown.
[Autopause loop] Client connected - waiting for disconnect
Crash report:
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 3/13/21, 4:57 PM
Description: Watching Server
...
```

**Comment by itzg** [comment]
> I would like:
> a) The health check to fail in this situation

If the main process exits (due to a crash) the whole container exits. I'm not sure why that didn't happen in your case. From there, [the health check probably got skipped](https://github.com/itzg/docker-minecraft-server/blob/4cb12f6cae66340eafd4a7f19f92136f37a77919/health.sh#L8-L10) since the process was in a bad state.

> b) The minecraft process to auto restart on crash (maybe ?)

[Docker itself already has a feature for that](https://docs.docker.com/engine/reference/run/#restart-policies---restart).

**Comment by itzg** [comment]
@Oekn5w , any thoughts/suggestions?

**Comment by Oekn5w** [comment]
@tekook [From Readme](https://github.com/itzg/docker-minecraft-server#autopause):

> From the server's point of view, the pausing causes a single tick to take as long as the process is stopped, so the server watchdog might intervene after the process is continued, possibly forcing a container restart. To prevent this, ensure that the max-tick-time in the server.properties file is set correctly. Non-vanilla versions might have their own configuration file, you might have to disable their watchdogs separately (e.g. PAPER Servers).

@wolfen351 are you sure this is autopause related? How's your setup, can you provide any log files?

**Comment by wolfen351** [comment]
This is so long ago, I don't have any more info other than what has been provided here. It also hasn't happened again, so I think it is safe to close this one with a _shrug computers, huh_
