### ISSUE TITLE
Container Running But Server Stops

### ISSUE THREAD

**Issue by algertc** [itzg/docker-minecraft-server#657]
After running for about 10 minutes, the server will randomly stop working. Nothing is in the logs and the container says it is running and healthy. When I open Minecraft the server shows up as offline both from the internet and locally. Maybe it is just disconnecting somehow? A restart of the container fixes the problem for the next 10 minutes. 

Running: spigot 1.16 with essentials and nothing else

**Comment by itzg** [comment]
Can you provide the docker run command or compose file you use to create the container?

**Comment by algertc** [comment]
I have confirmed this to be an issue with docker's networking configuration, not your image. Sorry about that!
