### ISSUE TITLE
improvement: consistent false/true flags across settings

### ISSUE THREAD

**Issue by Silthus** [itzg/docker-minecraft-server#661]
Currently most of the settings in the docker image use different ways to parse the true/false flags. Depending on the setting you need to try around with different versions of true and false, e.g. `FALSE`, `false`, `"FALSE"`, `"false"`, and the same for true.

To reduce configuration errors and friction when setting up the image, all variables should be able to parse as true or false regardless of their writing.

**Comment by itzg** [comment]
Agreed. I have been gradually switching to the utility methods in `start-utils`, but would be good to just make a sweep through all the scripts and unify on that.
