### ISSUE TITLE
High CPU IOWait causing server freezes

### ISSUE THREAD

**Issue by volitle** [itzg/docker-minecraft-server#665]
I've spent quite awhile troubleshooting these intermittent freezes I've been seeing. They are happening almost exactly every 35min on the dot, where I'm getting this error in the docker logs:
[Server thread/WARN]: Can't keep up! Is the server overloaded? Running 28415ms or 568 ticks behind

When I first started using the server it was bad enough that it would kick everyone since the delay was >30sec, but after installing fabric, phosphor, and lithium it's now low enough that it's just causing massive rubberbanding. I thought it might have been my raid controller (PERC 710p Mini), but it's completely up to date. I also checked the SMART data on the 4 600gb 15k drives I have in a raid 10, and none of them are throwing errors and have the latest firmware. With a lot of digging and the help of Chronograf, I was able to produce these images showing the spikes as well as process "java" causing massive IOWait, but I wasn't actually to figure out what within the container was causing it.

![2020-11-11 16_48_16-Chronograf and 27 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/7141832/98870742-c1555000-2441-11eb-9e40-cb05bfb736aa.png)
![2020-11-11 16_35_05-Chronograf and 26 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/7141832/98870744-c31f1380-2441-11eb-88b7-4e5489f07846.png)
![2020-11-11 16_35_33-admin@localhost__sys_kernel](https://user-images.githubusercontent.com/7141832/98870746-c31f1380-2441-11eb-9f85-dc7a4b3dd3d5.png)

Might it have something to do with garbage collection? I'm allocating 16gb to the container, have the Aikar flags enabled, and set 8 threads to the GC with UseG1GC, but it was doing it before I had those flags set. Whatever it's doing, it's also grinding all of my other containers to a halt for the duration of the spike (usually 20-30sec).

**Comment by itzg** [comment]
It's best if you report performance issues with respective upstream, Mojang, Bukkit, etc since the containerization had very little impact on the performance characteristics. 

What I can suggest though is using the JMX monitoring option

https://github.com/itzg/docker-minecraft-server#enable-remote-jmx-for-profiling

and attach jconsole or JDK Mission Control see a bunch of detail about what the JVM is during those spikes.

**Comment by mpriem** [comment]
I have a similar issue, but mine occurs daily at 9AM with no users attached. Java process simply goes bananas. Also throughout the day CPU usage is slowly increasing for no apparent reason; again in most cases without anyone connected to the server.
To mitigate I have a small crontab running every 3 hours to kick the box when no one is playing.

```
Players=`docker exec servername rcon-cli list | head -c 17 | tail -c 1`
if [ $Players == "0" ]
then
  docker stop servername
  sleep 2m
  docker start servername
fi
```

**Comment by itzg** [comment]
I'm going to close this issue. @mpriem please refer to the comment above yours.

**Comment by mpriem** [comment]
No worries. Just wanted to chime in on the issue. I understand this is most likely not related to containerizing minecraft server code. Thanks for your work. I really love this repo.
