### ISSUE TITLE
CurseForge ServerPack not recognized as "Server Version of FTB modpack!"

### ISSUE THREAD

**Issue by Stephen-Hilton** [itzg/docker-minecraft-server#666]
As a prefix:  i'm not new to Minecraft on Docker(awesome work, BTW), but I AM new to Minecraft CurseForge.   I'm trying to setup a CurseForge server for my son and friend, and have burnt 3 hours researching and trying and retrying.  Hoping for a quick point to what i'm doing wrong...  not sure if this is an issue, or a lack of documentation / knowledge on my part.

I've downloaded locally the server pack for Lapito's Galacticraft:
[https://www.curseforge.com/minecraft/modpacks/lapitos-galacticraft/files/2655131](https://www.curseforge.com/minecraft/modpacks/lapitos-galacticraft/files/2655131)

I'm unfamiliar whether the "ModPack" works as a "ServerPack" now, the way i've read Forge does - i've also tried the latest ModPack:
[https://www.curseforge.com/minecraft/modpacks/lapitos-galacticraft/files/3060645](https://www.curseforge.com/minecraft/modpacks/lapitos-galacticraft/files/3060645)

I should also mention the modpack above has 327,167 Downloads (as of now), so it doesn't look like an obscure mod (although most of those are certainly modpacks, not serverpacks)

here is my run command:
```
## Minecraft-Galacticraft
docker run -d --name minecraft-galacticraft \
 -p 55559:25565 \
 --restart unless-stopped \
 --net famhil-net \
 -e EULA=TRUE \
 -e VERSION=1.12.2 \
 -e SERVER_PORT=25565 \
 -e RCON_PORT=25566 \
 -e MEMORY=4G \
 -e TYPE=CURSEFORGE \
 -e CF_SERVER_MOD=/modpacks/LGM2.0-ServerPack.zip \
 -v /opt/docker/volumes/minecraft-galacticraft:/data \
 -v /opt/docker/volumes/modpacks:/modpacks \
 itzg/minecraft-server  --noconsole
```

All iterations / scenarios i've tried lead to the same error (looping):

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    3 1000     1000          4096 Nov 14 22:12 /data'
[init] Resolved version given 1.12.2 into 1.12.2
[init] Resolving type given CURSEFORGE
[init] Looking for Feed-The-Beast / CurseForge server modpack.
[init] Unpacking FTB server modpack /modpacks/LGM2.0-ServerPack.zip ...
...........................................................................................................
[init] Please make sure you are using the server version of the FTB modpack!
```

as you can see from above, i'm using LGM2.0- --> ServerPack <-- .zip

I've tried different flavors of FBT / GENERIC types, both the ModPack and ServerPack, re-downloaded (in case of corruption), but all to no avail so far.   Again, completely possible i'm doing something wrong, but i can't find clear instructions for my level of understanding.  I also don't know how to determine whether the ServerPack is well formed.

Thanks for any pointers you can provide!

**Comment by itzg** [comment]
It certainly wasn't you, that modpack seems to be quite a strange one. In fact, it looks like they're improperly including the official minecraft server jar. FYI I only play vanilla, so I don't get much exposure to all these different modpacks and their quirks.

After trying a few things, much like you, this seemed to be the compose file that finally worked where `LGM2.0-ServerPack.zip` is in a `modpacks` subdir next to the compose file.

```yaml
version: '3'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.12.2
      GENERIC_PACK: "/modpacks/LGM2.0-ServerPack.zip"
    volumes:
      - ./modpacks:/modpacks:ro
      - ./data:/data
    ports:
      - 25565:25565
```

**Comment by Stephen-Hilton** [comment]
Good to know i'm not completely insane :)   thanks for the quick response!

This did indeed work for me - appreciate the attention, happy weekend!
