### ISSUE TITLE
REMOVE_OLD_MODS does not delete /data/plugins on paper servers

### ISSUE THREAD

**Issue by aspro-at** [itzg/docker-minecraft-server#667]
If REMOVE_OLD_MODS is set to 'true', the content of the folder /data/mods is deleted for all servers but spigot servers. This is done in start-finalSetupModpack lines 10 to 17. Are there any objections to include paper servers in the condition of the relevant if clause?

The relevant passage should be

# Remove old mods/plugins
if [ "$REMOVE_OLD_MODS" = "TRUE" ]; then
  if [ "$TYPE" = "SPIGOT" ] || [ "$TYPE" = $PAPER ]; then
    rm -rf /data/plugins/*
  else
    rm -rf /data/mods/*
  fi
fi

p.s.: Great work! Thank you!

**Comment by itzg** [comment]
Sorry for the delay. Yes, that modification makes sense to me. You're very welcome to PR that or I can make the change.

**Comment by Silthus** [comment]
This is fixed by the new addition of #688 which closed #662

**Comment by aspro-at** [comment]
I can confirm that cleaning /data/plugins now works for me with paper servers.
But there seems to be another (unrelated) problem. If the directory /data/plugins is not present, the attempted to clean it fails and the server does not start up:

> [init] Removing old mods in /data/plugins...
> find: /data/plugins: No such file or directory

**Comment by aspro-at** [comment]
Created PR #697

**Comment by itzg** [comment]
@aspro-at image with your final fix is now published. Can you verify and close the issue?

**Comment by aspro-at** [comment]
It work's!
Thank you!
