### ISSUE TITLE
curl: (6) Could not resolve host: papermc.io

### ISSUE THREAD

**Issue by Zahlenspiel** [itzg/docker-minecraft-server#668]
There's an extra slash there. Failed to contact PaperMC while downloading Paper (build latest).

https://papermc.io/api/v1/paper//latest/download

**Comment by Sciroccogti** [comment]
Maybe you should try this? `https://papermc.io/api/v1/paper/1.16.4/latest/download`

**Comment by itzg** [comment]
Sounds like your docker/host setup has DNS issues since it was reported as an unresolvable host issue.

As a result, the version lookup failed and left the blank spot in the URL and looks like a double slash.

**Comment by Zahlenspiel** [comment]
Looks like the version is missing in the url. I'll check it asap

**Comment by Zahlenspiel** [comment]
Well, any other service I run in docker works fine. I'll look into it.

**Comment by itzg** [comment]
Understood but images can vary by base distro and therefore interact differently with your network's DNS. For example the mainline image here uses Alpine. Perhaps give the `itzg/minecraft-server:multiarch` tag a try since it is based on Debian.

**Comment by Zahlenspiel** [comment]
@itzg got it. My DNS is probably fine. To get docker working with UFW I added "DOCKER_OPTS="--iptables=false"" in /etc/default/docker - and by removing it I get the container to work 👍

**Comment by itzg** [comment]
That should be safe to remove since UFW is just a nicer front end to iptables

https://wiki.ubuntu.com/UncomplicatedFirewall#Introduction

...and docker does all its port forwarding magic with iptables.

**Comment by itzg** [comment]
Can this issue be closed?

**Comment by Zahlenspiel** [comment]
Well we could argue about docker and ufw since docker bypass rules set with ufw. But this issue can be closed 👍
