### ISSUE TITLE
multiarch startup error: ${ftbInstallMarker}: ambiguous redirect

### ISSUE THREAD

**Issue by kevinoconnor7** [itzg/docker-minecraft-server#671]
Relevant portion of the logs:

```
=================  FORGE INSTALL ENDS  =================


Pack install Finished.


/start-deployFTBA: line 53: ${ftbInstallMarker}: ambiguous redirect
```

Seems to have been introduced in f97b3bf82e2b116910c3f3e1d25d05bb8130d1ad as I encountered this error immediately after docker recreated the container with the updated image pushed ~30 min ago.

**Comment by kevinoconnor7** [comment]
I reverted that commit locally, but since the last run had `ftbInstallMarker` undefined, the startup script deleted the server and attempted to reinstall it.

So then with the commit reverted, the server failed to come up with: `ERROR unable to locate the installed forge server jar`. I had to also delete the marker file and let the server be reinstalled.

**Comment by kevinoconnor7** [comment]
oof unfortunately the script had also wiped out a bunch of metadata (namely the `config` directory). I would suggest pulling that image since it's going to cause data loss for some folks.

I would highly recommend the [unofficial bash strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/) as a way to catch these sort of errors. A reference to an undefined variable would've been a hard error.

**Comment by itzg** [comment]
I have reverted the commit and new images are building.

**Comment by itzg** [comment]
Strange I already had `set -e`, but maybe [this issue](https://github.com/itzg/docker-minecraft-server/issues/645#issuecomment-734018718) still happened since curl downloaded a partial file. I'm just going to leave the scripts alone for now since [the original motivation got resolved externallly](https://github.com/itzg/docker-minecraft-server/issues/645#issuecomment-734068630).

**Comment by kevinoconnor7** [comment]
Thanks Geoff!

For completeness: `set -e` causes bash to abort after the first non-zero return code. `set -u` would have been helpful here since the variable `ftbInstallMarker` was undeclared. I think it was a mistake in your commit that the variable was deleted.
