### ISSUE TITLE
Paper to require java 11 with 1.17 release (currently shows warning)

### ISSUE THREAD

**Issue by gerome1812** [itzg/docker-minecraft-server#676]
On using java 8, paper prints [this message](https://github.com/PaperMC/Paper/commit/eb89fd5deabcaf7ab044f8f7953dde5c6e5c1ce1#diff-b5cbd2b4a65e247504b29d64f8593aec6cdddfd7f7029ed07c8ac170a23daccfR52-R66) telling you you need to install java 11 for paper to work 1.17.

**Comment by itzg** [comment]
Very interesting. For now, you can change your image to the tagged one `itzg/minecraft-server:adopt11`; however, it sounds like I'll need to consider making that the mainline/latest since Forge is the only remaining reason I default to Java 8.

**Comment by gerome1812** [comment]
I wasn't very clear in my first comment, but they made a post here with more details: [papermc.io/java11](https://papermc.io/java11).

**Comment by xorinzor** [comment]
I'm actually running into the issue while setting up a server too. Where plugins actually fail to load because they've been compiled with a higher version then is used in the docker container.

Can confirm that using `itzg/minecraft-server:adopt11` fixed this issue for me.

**Comment by Davie3** [comment]
The adopt11 image tag work great in the meantime. The arm images will also need to be updated to java 11: itzg/minecraft-server:armv7 and itzg/minecraft-server:arm64.

**Comment by itzg** [comment]
Yep, please use `itzg/minecraft-server:adopt11` in the meantime; however, I'm very soon going to switch master/latest to Java 11 and have already introduced a `java8` tag. I will also be bumping `multiarch` (where ARM is now supported) to Java 11.

**Comment by itzg** [comment]
As of this revision https://github.com/itzg/docker-minecraft-server/commit/96aa1054dc3d620688f7082a8887a6b10967d931 the master-branch/latest-tag and multiarch is now based on Java 11.
