### ISSUE TITLE
Java 15 support

### ISSUE THREAD

**Issue by CDFN** [itzg/docker-minecraft-server#678]
Hey it'd be great if we could use java 15 with this image. Latest supported java version by `minecraft-server` is 14.

**Comment by itzg** [comment]
Java 15 is already supported in the `itzg/minecraft-server:multiarch-latest` image; however, that reminds me I need to check back if an Alpine Java 15 is now avaialble.

**Comment by itzg** [comment]
...note to self, yes, `adoptopenjdk/openjdk15:alpine-jre` is now available at https://hub.docker.com/r/adoptopenjdk/openjdk15
