### ISSUE TITLE
Unable to use GENERIC_PACK and MODS with url parameters

### ISSUE THREAD

**Issue by qnten** [itzg/docker-minecraft-server#684]
I am using urls with very long parameters ([like this one](https://storage.googleapis.com/q-mc-data/configs.zip?X-Goog-Signature=5168f4e5aa83747d59fcea199ea987d28c229b39cb18fb920dc9cb8a1388564ee9c3eea479c64c6da1c23748952399304ß50296f7d6046653e6fbb4624aa6e4042c2ed48dd48b16d8468be1bd6863053cd94a56ea1da17657e84d48dd83e8fde10c561b6867c104008fa935bc8c29f659f482a54ba2ab00aae7dcbe0ae2b189ed9feea5aec6d6cc148acdee3d31332ce6589212855856e745ba61d7843151f9f500b024b15b6ca212b05d0ac037184a02b1bbd65457b79da8530129d9fcbf6d37c2f6cff65d932c9879b17be8483403e0e2222ae727c9)) to download worlds etc. When trying to download a generic pack, curl fails with `curl: (23) Failed writing body (0 != 1377)`. I think this is because the script tries to download the file to the basename of the url in this line:
https://github.com/itzg/docker-minecraft-server/blob/0f7bd5f4fd58cced5b879a54cc6019aac5557d73/start-finalSetupModpack#L144
Unfortunately `baseline` doesn't remove url parameters which results in a filename that is too long. 

I'm not sure what the best approach for a fix is. Should the parameters be stripped or should the generic pack be downloaded to a fixed filepath like the world file?

**Comment by itzg** [comment]
Oh yeah, that approach is not robust at all for URLs with any query parameters. I'll explore a little bit because I think there might be a way of addressing that as a curl argument.

**Comment by qnten** [comment]
Thank you! I just noticed that this also happens when using the `MODS` var to download jars. Error message is `Must be HTTP or HTTPS and a JAR file`

**Comment by itzg** [comment]
The latest should now fix this. Can you pull the latest image and try again with the generic pack URL?

**Comment by itzg** [comment]
> Thank you! I just noticed that this also happens when using the `MODS` var to download jars. Error message is `Must be HTTP or HTTPS and a JAR file`

What is an example of a `MODS` value that didn't work? That bit of code a little bit different, so it'll need to be addressed differently.

**Comment by qnten** [comment]
When setting the MODS value to a [url with parameters](https://storage.googleapis.com/mc-plugins/PluginsFile.jar?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Signature=04e81cf16f1350627257e61b300935151412399eed3f17cc10d17105118032363de0b46cbfde6eaf146ee6ee3d5b8bfc1bd100a2bda0029fad12a75bc9b5a85c2f85b833cf30b739b1e430d9bb48d8787d2783490273809229c04a72344e361a912ee3c68cb4d3ff0f805d97a85767983cdf0f48825296b70af6d94aa37dcbdcfa2ea67a9755de6956684b60ff7e13afb0ad77b54679c62c9fcc37b4493528b0633069c67e84355f55a191917556aa6b1230b51cccb70c32d138ada51d7f9c671d41f616a1a353ec4664ecbbeab5780dff2787d591c6ce5cd206d565707006180a3) the script fails with `[init] ERROR Invalid URL given in MODS` and `[init]       Must be HTTP or HTTPS and a JAR file`.

**Comment by itzg** [comment]
Latest image should now also fix `MODS` handling of URLs with query parameters.

**Comment by qnten** [comment]
Yes this issue seems to be fixed. Thank you very much!
