### ISSUE TITLE
printf is not supported by find during GENERIC_PACK download

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#685]
When using the newest docker image containing this fix, the world download fails:
```
[init] Resolved version given LATEST into 1.16.4
[init] Resolving type given PAPER
[init] Downloading PaperMC 1.16.4 (build 323) ...
[init] Unzipping world
find: unrecognized: -printf
BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.
```

I think the `-printf` flag isn't supported in alpine (https://github.com/google/cadvisor/issues/1556).

_Originally posted by @qnten in https://github.com/itzg/docker-minecraft-server/issues/683#issuecomment-743777122_

**Comment by itzg** [comment]
@qnten the latest image should now fix this

**Comment by qnten** [comment]
Yes it works, thank you!

**Comment by Nicholaiii** [comment]
I have this issue using the java8 image

**Comment by itzg** [comment]
@Nicholaiii, please provide the output of `docker image inspect --format "{{json .Config.Labels}}" itzg/minecraft-server:java8`

**Comment by Nicholaiii** [comment]
> 
> 
> @Nicholaiii, please provide the output of `docker image inspect --format "{{json .Config.Labels}}" itzg/minecraft-server:java8`

I will get to that later, but I got it confirmed working on the debian based java8-multiarch image,
