### ISSUE TITLE
How to automaticly restart any MC Server

### ISSUE THREAD

**Issue by Chaoschaot232** [itzg/docker-minecraft-server#692]
Due to the problems which are coming through JAVA it is at a certain point required to restart your MC-Server that it runs
smoothly again - as long as other players didn't done any shit to cause lags where simple reboots take no effect.

By now, the restart is done over Portainer Interface but is there any possibility to do this automaticly incl. any kind of color
formated message to announce the server restart?

Would be nice to know how this could be done :)

**Comment by itzg** [comment]
I would recommend looking for Bukkit/Paper server plugins that provide such commands. That combined with a container's restart policy will probably address your request.
