### ISSUE TITLE
Paper edit start parameter

### ISSUE THREAD

**Issue by BatUnt** [itzg/docker-minecraft-server#693]
hi i need advice on how to add a line to the boot parameter i need it around the plugin

**Comment by itzg** [comment]
What kind of parameter?

**Comment by BatUnt** [comment]
-javaagent:slimeworldmanager-classmodifier-<version>.jar

**Comment by BatUnt** [comment]
it is an interesting plugin that can store the world in a database etc ...

**Comment by BatUnt** [comment]
![image](https://user-images.githubusercontent.com/63431281/102714155-0ab07f00-42cd-11eb-82ea-79dea4bf1673.png)

**Comment by BatUnt** [comment]
![image](https://user-images.githubusercontent.com/63431281/102714168-18660480-42cd-11eb-80c2-816a57965c77.png)

**Comment by BatUnt** [comment]
okey i ran this here is a solution to the problem
![image](https://user-images.githubusercontent.com/63431281/102714782-477e7500-42d1-11eb-80c0-3889e2163264.png) good

![image](https://user-images.githubusercontent.com/63431281/102714784-4d745600-42d1-11eb-8b88-470bb31b399e.png)
bead
