### ISSUE TITLE
Docker Minecraft Forge

### ISSUE THREAD

**Issue by MCLover101** [itzg/docker-minecraft-server#694]
So, I was running a Forge Docker Server, and my son was wondering why the mods I installed were working for him, even though he didn't even have forge or any mods in his mods folder.  What I'm curious about is, why did every single tutorial that I found say that you need Forge on the Server, and Forge on the launcher...  Any Answers?

**Comment by itzg** [comment]
Agreed, I always thought forge mods had to be installed both in the server and client. What's an example of one that seems to be working server-only? 

FYI the bukkit/spigot/paper server types only need plugins on the server side.

**Comment by MCLover101** [comment]
My son wanted WorldEdit on the server, so we went searching.  Every single video we found said both the server and launcher need Forge and WorldEdit for it to work.  We thought it might have something to do with being opped on the server, as on most servers (Like Hypixel) you aren't opped.  He even tried completely removing the WorldEdit mod from his mods folder, and it still worked.  Any idea's as to if the OP thing is correct?

**Comment by itzg** [comment]
I tried this myself and I also found that a vanilla client profile was able to connect fine. I'm guessing without the client-side use of forge and the mod then some features will not be available, such as [selection lines](https://worldedit.enginehub.org/en/latest/usage/regions/selections/#want-to-see-selection-lines).

Can we close this issue now?

**Comment by MCLover101** [comment]
Yes

**Comment by MCLover101** [comment]
Yes, but one more thing.  If I were to download MrCrayfish's Furniture Mod, would the same thing apply? (Meaning, would some items be missing if I used the Vanilla Client)

**Comment by itzg** [comment]
I'm sorry, I really don't know much about mods. I play vanilla Minecraft myself and provide the container image as a general purpose way for people to run modded servers, etc. 

Feel free to join the Discord server to ask if others have more information about the various mods.

**Comment by MCLover101** [comment]
Ok
