### ISSUE TITLE
[reopened] How to automaticly restart any MC Server

### ISSUE THREAD

**Issue by Chaoschaot232** [itzg/docker-minecraft-server#695]
1) Do not close direclty issiues/qeustions as long as they are not compleatly disscussed, thanks.

2) Your answere in #692 is not realistic and possible because you assume a Bukkut/Paper server and what is with Forge?
It is definitly at you end to provide support for this since every MC-Player knows that at a certain amount of time any modded MC-Server, specialy Forge ones, in urgant need of a reboot. This, like stated before, can't be done with an administrative mod, as mods/plugins/... only working when teh server runs but after stopping the server, the container also dies and not even ```restart= alwas``` can solve this problem.

This means that this litte request is smth. which only you can implement in your project, tbh.

Oh, my server is a Forge server, because bukkit/spigot isn't worth to play on as Forge offers much more mods and fun, tbh.

**Comment by itzg** [comment]
> This means that this litte request is smth. which only you can implement in your project, tbh.

This is not a "little request" and I have no further information to provide about how a container repo can provide such functionality. The last line of the startup script exec's the Minecraft Java process and has no further interaction with the process.

The container bundles rcon-cli, so you're welcome to automate whatever commands you want to issue via your own script.

**Comment by Chaoschaot232** [comment]
What about an included cron for this which can be configured as ENV for the container?

Cron support should be given in it so that the hole conatiner doesn't needs to be restarted instead of just extending the container setup with smth. like `-e CRON="* 12 * * *"` (should be the correct value für cron) and when it applies simpley reboot the server but do not kill the entiere container and get lost of the tracing the log (I use docker-compose logs -f <mc-instancename-here> or at last without a specific name to monitor them all together).

Would be surprised if this shouldn't be possible 🤔

**Comment by itzg** [comment]
It's not proper to run multiple processes in a container since a container = a process ...however, you could run cron on your host (or a sidecar container) and have that docker exec into the Minecraft container to run the rcon commands to post a message then issue a stop command. With the container set to auto restart it would then start itself after being stopped.

**Comment by itzg** [comment]
BTW, I know it looks like I'm avoiding the original request but instead I am a strong believe in [single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle). In this case, the `itzg/minecraft-server` image is responsible for setting up the server files and running the server. From there, it's a building block in larger solutions where other containers/processes/cronjobs can be integrated to do more things. For example, scheduled backups are supplied by [a separate image](https://github.com/itzg/docker-mc-backup).
