### ISSUE TITLE
Enviroment variables are not replaced on files copied through the config mount

### ISSUE THREAD

**Issue by Misterio77** [itzg/docker-minecraft-server#700]
Hey!

I've been trying to get some variables replaced on config files on a paper server, but it seems that the step that copies from `/config` mount [only occurs at the last setup step](https://github.com/itzg/docker-minecraft-server/blob/master/start-minecraftFinalSetup#L63), which is right after the [one that replaces env vars](https://github.com/itzg/docker-minecraft-server/blob/master/start-finalSetupEnvVariables).

I don't think this is intended? I thought of two different solutions:

1.  Move Env vars step to [start-minecraftFinalSetup](https://github.com/itzg/docker-minecraft-server/blob/master/start-minecraftFinalSetup)
2. Move the copy step to its own file, and make that run before finalSetupEnvVariables

I think the latter is a bit cleaner, so i'll try and write a PR for it, if that's okay?

**Comment by itzg** [comment]
Yes, option 2 makes sense and a PR would be great.
