### ISSUE TITLE
World resets after system restart, data still present

### ISSUE THREAD

**Issue by YU2Lhr7U** [itzg/docker-minecraft-server#702]
After restarting my system (Fedora 33) my world has reset, the world files are still present in the directory they should be.

The container was created with 
```
docker run -d --network host -v /mnt/minecraft/:/data --name mc -e EULA=TRUE itzg/minecraft-server
```

Sorry if this has been solved previously (or is some fundamental feature of Docker I don't yet understand), my problem might be related to #27, I'm not sure though.

Thanks in advance.

**Comment by itzg** [comment]
I'm not sure what happened since your volume attachment should have been durable. My only guess is that the container didn't get to gracefully stop and issue the stop command to the Minecraft server.

**Comment by YU2Lhr7U** [comment]
It turns out I'm an idiot anddidn't have the drive mounted...

Thanks  you for your time 😅
