### ISSUE TITLE
Spigot remote debug

### ISSUE THREAD

**Issue by hannesa2** [itzg/docker-minecraft-server#705]
I want to debug my Spigot plugin on a server (I don't found an other way how to debug it. if there an other way, please let me know) and for this I've to change start [params](https://www.spigotmc.org/wiki/intellij-debug-your-plugin/?__cf_chl_jschl_tk__=84982c1d539d52ff48295c14f03b06f013a1e089-1609065258-0-AUwv23zU40m2woTIUSdDjzmfpI1v6vINAf6KqgyIGjoMtF-csYtYkXLPPX6o7bPutla_EUTb_yOB7Jib2OQsJRLFW2rEgL8pv9P3iQ2PNCvvoTFP6mEmwDc2keCGE6RD5MYgZfSQ4IALTeL-p0XYGPs0KN6Qrhswgcbfh8IXIfkNWJSBNdJi_brAjlpFhxlRAjCti-XU6zrs8rBEe5F-Qx7IwrWeUmEcpDybt9GWSftIl02jjToOxTXTDq1R2eDvwzvcKEryLYaZ7TxYOt8u0-5hZcuqwbFsac3IyA-3Y8AelU-cpvxm1DDf4tqoLEiSfSC6ZrKpAX0YaisYcPGppLhDmy1ibznMVqeNojZNNTIy) but how can I do this with docker start params ?

Sorry for the basic questions

<img width="810" alt="image" src="https://user-images.githubusercontent.com/3314607/103274359-c6566a80-49c1-11eb-8137-accdad05c848.png">

**Comment by itzg** [comment]
Yes, those are the usual remote debug parameters I use for Java debugging. To pass those to this particular image, you'll use the `JVM_OPTS` variable and also expose the remote debugging port, such as with:

```
docker run -it --rm -e EULA=TRUE -e JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -p 5505:5005 -p 25565:25565 itzg/minecraft-server
```
