### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by SvobodaGaming** [itzg/docker-minecraft-server#709]
Hello! I have a Spigot 1.12.2 Server. After some time, the server stops with an error:

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x000000000000a786, pid=47, tid=0x00007fadec4ffb10

 JRE version: OpenJDK Runtime Environment (8.0_252-b09) (build 1.8.0_212-b04)
 Java VM: OpenJDK 64-Bit Server VM (25.252-b09 mixed mode linux-amd64 compressed oops)
 Derivative: IcedTea 3.16.0
 Distribution: Custom build (Thu Aug 13 12:46:32 UTC 2020)
 Problematic frame:
 C  0x000000000000a786

 Core dump written. Default location: /data/core or core.47

 An error report file with more information is saved as:
/data/hs_err_pid47.log

 If you would like to submit a bug report, please include
 instructions on how to reproduce the bug and visit:
  https://icedtea.classpath.org/bugzilla

2021-01-01T13:23:18.472+0300	WARN	mc-server-runner	sub-process failed	{"exitCode": -1}
2021-01-01T13:23:18.473+0300	INFO	mc-server-runner	Done

**Comment by itzg** [comment]
You probably need to report this one with the Spigot issue tracker; however, you could also try some of the other image tags to see if a different Java version helps, such as `adopt11` or `multiarch-latest`.

**Comment by SvobodaGaming** [comment]
Thanks! I changed image from itzg/minecraft-server:latest to itzg/minecraft-server:multiarch and it's work!
