### ISSUE TITLE
Not able to run 2 servers on seperate ports

### ISSUE THREAD

**Issue by Janilom** [itzg/docker-minecraft-server#714]
I am trying to run a Vanilla server on port 25565 as well as a Curseforge modpack on port 22595.
Both servers setup normally in Docker however whether I open the Modded client instance or the Vanilla client instance, the only server that shows up is whichever is setup first via Docker. I attempted using a direct local connection to each server as well as with a reverse proxy but still no luck.

**Comment by itzg** [comment]
How did you declare the port mappings for each container? Did you make sure to include the port when filling in the direct connection in the client, such a "localhost:25595"?

**Comment by Janilom** [comment]
I would like to use my reverse proxy for both to make it easier for my kids and their friends to connect. 

I set the reverse proxy to: 
vanilla.myurl.com > 192.168.1.15:22565
mods.myurl.com > 192.168.1.15:22595

These are my 2 compose files:

version: "2"
services:
  minecraft_sevtech_server:
    image: itzg/minecraft-server:latest
    container_name: mc_enigmatica_6
    restart: unless-stopped
    ports:
      - 25595:25565
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles
      - EULA=TRUE
      - TYPE=CURSEFORGE
      - VERSION=1.16.4
      - SERVER_NAME=Enigmatica 6 Server
      - CF_SERVER_MOD=Enigmatica6Server-0.3.2.zip
      - MEMORY=6G
      - DIFFICULTY=NORMAL
      - ONLINE_MODE=TRUE
      - OPS=Janilom
    volumes:
      - /srv/dev-disk-by-label-systemdata/Minecraft/enigmatica_6:/data

---

version: "2"
services:
  mc_Vanilla:
    image: itzg/minecraft-server:latest
    container_name: mc_vanilla
    restart: unless-stopped
    ports:
      - 25565:25565
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles
      - EULA=TRUE
      - MEMORY=5G
      - VERSION=LATEST
      - ONLINE_MODE=TRUE
      - DIFFICULTY=normal
      - SERVER_NAME=Vanilla MC Server
      - MOTD=Whats up my Dudes!! Have fun building!
      - OVERRIDE_SERVER_PROPERTIES=TRUE
      - ALLOW_NETHER=TRUE
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=TRUE
      - ENABLE_COMMAND_BLOCK=TRUE
      - GENERATE_STRUCTURES=TRUE
      - HARDCORE=FALSE
      - PVP=TRUE
      - SNOOPER_ENABLED=FALSE
      - SPAWN_ANIMALS=TRUE
      - SPAWN_MONSTERS=TRUE
      - SPAWN_NPCS=TRUE
      - MODE=survival
      - ALLOW_FLIGHT=TRUE
      - OPS=Janilom
    volumes:
      - /srv/dev-disk-by-label-systemdata/Minecraft/vanilla:/data

**Comment by itzg** [comment]
What reverse proxy are you using? It sounds like a problem at that layer since your compose files and port mappings look correct.

**Comment by Janilom** [comment]
Its a docker instance of nginx proxy manager. Strange thing is even if I try connecting to the servers via IP:PORT it still just shows the 1 server that I started first. I can try connecting but it then fails because its not the correct server/client version.

**Comment by itzg** [comment]
I'm pretty sure you can't use nginx as a reverse proxy for Minecraft's proprietary protocol. (nginx's reverse proxy support is meant for HTTP or HTTPS).

The determination of backend server instance by hostname has to be selected from the "server address" field of the handshake message:

https://wiki.vg/Protocol#Handshake

You will need to use [mc-router](https://github.com/itzg/mc-router), [bungeecord](https://www.spigotmc.org/wiki/bungeecord/), or a variant thereof.

**Comment by itzg** [comment]
...forgot to mention, I also provide an image for bungeecord and variants: https://github.com/itzg/docker-bungeecord

**Comment by Janilom** [comment]
Ah I see now what my mistake is with Nginx. I never realized there was such a thing like bungeecord. I’ll check out the image and see if I can figure it out. Time to learn something new. I greatly appreciate your help and these images as they have provided my kids and I loads of family game time!

**Comment by itzg** [comment]
FWIW, I developed and use mc-router for exactly the scenario you're attempting; however, I agree with trying bungeecord since it'll supply even more features that your kids will probably eventually request.

I wrote some of the original features to simplify my daughter's requests for Forge customizations :) , so I'm always glad to hear of more successful family docker-minecrafting experiences.

**Comment by Janilom** [comment]
This is a small server hardware wise. I think I am going to try mc-router first to get things up and running. Then I can test out bungeecord separately to figure it all out. For mc-router can I use my existing compose files ?

**Comment by itzg** [comment]
> Is there a way to open the two servers within mc-router to the internet?

Yes, I have my minecraft servers deployed behind mc-router with only mc-router exposed to the internet. Given the example compose file in the repo:

https://github.com/itzg/mc-router/blob/master/docs/docker-compose.yml

It's important to note that the two minecraft servers don't even need their ports published since the `router` service can access their container ports over the docker network created amongst them. What's left then is to

1. Configure your internet-facing router hardware to port forward TCP port 25565 to your docker host, where port 25565 on your host is published by mc-router
2. Setup your DNS hostnames to point to your public IP address

**Comment by baer95** [comment]
just fyi: nginx does also support tcp/udp loadbalancing :)
https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/

**Comment by Janilom** [comment]
My solution was to use your image for Bungeecord. I now have both servers working and have a central hub as well to add more mini games and such for the kids to play. You made this Dad cool again ! I appreciate your work!

**Comment by itzg** [comment]
That's great news @Janilom :)

**Comment by nerdfoundrygaming** [comment]
@Janilom would you be willing to share the docker compose setup for that? Asking for a friend ;)

**Comment by Janilom** [comment]
> 
> 
> @Janilom would you be willing to share the docker compose setup for that? Asking for a friend ;)

version: '2'

services:
  bungeecord:
    image: itzg/bungeecord
    container_name: mc_bungeecord
    ports:
      - 25565:25577
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles
      - TYPE=WATERFALL
      - WATERFALL_VERSION=latest
      - WATERFALL_BUILD_ID=latest
      - MEMORY=512m
      - MAX_MEMORY=1G
      - DB_USER=minecraft
      - DB_HOST=MCdb
      - DB_PORT=3365
      - DB_NAME=db
      - DB_PASSWORD=password
    volumes:
      - /local/config.yml:/server/config.yml
      - /local/plugins:/plugins
      
  MCdb:
    image: mysql:latest
    container_name: mc_database
    restart: always
    ports:
      - 3365:3306
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=minecraft
    volumes:
      - /local/db:/var/lib/mysql
      
  lobby:
    image: itzg/minecraft-server:latest
    container_name: mc_lobby
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles
      - EULA=TRUE
      - MEMORY=512m
      - MAX_MEMORY=2G
      - TYPE=PAPER
      - VERSION=LATEST
      - ONLINE_MODE=FALSE
      - DIFFICULTY=normal
      - OVERRIDE_SERVER_PROPERTIES=TRUE
      - ALLOW_NETHER=FALSE
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=FALSE
      - ENABLE_COMMAND_BLOCK=FALSE
      - GENERATE_STRUCTURES=FALSE
      - HARDCORE=FALSE
      - PVP=FALSE
      - SNOOPER_ENABLED=FALSE
      - SPAWN_ANIMALS=FALSE
      - SPAWN_MONSTERS=FALSE
      - SPAWN_NPCS=TRUE
      - MODE=adventure
      - ALLOW_FLIGHT=FALSE
      - OPS=Me
      - DB_USER=minecraft
      - DB_HOST=MCdb
      - DB_PORT=3365
      - DB_NAME=db
      - DB_PASSWORD=password
    volumes:
      - /local/lobby:/data

  survival:
    image: itzg/minecraft-server:latest
    container_name: mc_vanilla_survival
    ports:
      - 8123:8123 #this is to allow dynmap to work with my reverse proxy
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles
      - EULA=TRUE
      - MEMORY=1G
      - MAX_MEMORY=3G
      - TYPE=PAPER
      - VERSION=LATEST
      - ONLINE_MODE=FALSE
      - DIFFICULTY=normal
      - OVERRIDE_SERVER_PROPERTIES=TRUE
      - ALLOW_NETHER=TRUE
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=TRUE
      - ENABLE_COMMAND_BLOCK=TRUE
      - GENERATE_STRUCTURES=TRUE
      - HARDCORE=FALSE
      - PVP=TRUE
      - SNOOPER_ENABLED=FALSE
      - SPAWN_ANIMALS=TRUE
      - SPAWN_MONSTERS=TRUE
      - SPAWN_NPCS=TRUE
      - MODE=survival
      - ALLOW_FLIGHT=TRUE
      - OPS=Me
      - DB_USER=minecraft
      - DB_HOST=MCdb
      - DB_PORT=3365
      - DB_NAME=db
      - DB_PASSWORD=password
    volumes:
      - /local/vanilla:/data

**Comment by nerdfoundrygaming** [comment]
I found my issue was trying to use bungeecord with forge on 1.16.4.... just simply doesn't seem to be a good combo 😔On Jan 16, 2021 11:54 PM, Janilom <notifications@github.com> wrote:

@Janilom would you be willing to share the docker compose setup for that? Asking for a friend ;)

version: '2'
services:
bungeecord:
image: itzg/bungeecord
container_name: mc_bungeecord
ports:
- 25565:25577
environment:
- PUID=1000
- PGID=100
- TZ=America/Los_Angeles
- TYPE=WATERFALL
- WATERFALL_VERSION=latest
- WATERFALL_BUILD_ID=latest
- MEMORY=512m
- MAX_MEMORY=1G
- DB_USER=minecraft
- DB_HOST=MCdb
- DB_PORT=3365
- DB_NAME=db
- DB_PASSWORD=password
volumes:
- /local/config.yml:/server/config.yml
- /local/plugins:/plugins
MCdb:
image: mysql:latest
container_name: mc_database
restart: always
ports:
- 3365:3306
environment:
- PUID=1000
- PGID=100
- TZ=America/Los_Angeles
- MYSQL_ROOT_PASSWORD=password
- MYSQL_PASSWORD=password
- MYSQL_DATABASE=db
- MYSQL_USER=minecraft
volumes:
- /local/db:/var/lib/mysql
lobby:
image: itzg/minecraft-server:latest
container_name: mc_lobby
restart: unless-stopped
environment:
- PUID=1000
- PGID=100
- TZ=America/Los_Angeles
- EULA=TRUE
- MEMORY=512m
- MAX_MEMORY=2G
- TYPE=PAPER
- VERSION=LATEST
- ONLINE_MODE=FALSE
- DIFFICULTY=normal
- OVERRIDE_SERVER_PROPERTIES=TRUE
- ALLOW_NETHER=FALSE
- ANNOUNCE_PLAYER_ACHIEVEMENTS=FALSE
- ENABLE_COMMAND_BLOCK=FALSE
- GENERATE_STRUCTURES=FALSE
- HARDCORE=FALSE
- PVP=FALSE
- SNOOPER_ENABLED=FALSE
- SPAWN_ANIMALS=FALSE
- SPAWN_MONSTERS=FALSE
- SPAWN_NPCS=TRUE
- MODE=adventure
- ALLOW_FLIGHT=FALSE
- OPS=Me
- DB_USER=minecraft
- DB_HOST=MCdb
- DB_PORT=3365
- DB_NAME=db
- DB_PASSWORD=password
volumes:
- /local/lobby:/data
survival:
image: itzg/minecraft-server:latest
container_name: mc_vanilla_survival
ports:
- 8123:8123 #this is to allow dynmap to work with my reverse proxy
restart: unless-stopped
environment:
- PUID=1000
- PGID=100
- TZ=America/Los_Angeles
- EULA=TRUE
- MEMORY=1G
- MAX_MEMORY=3G
- TYPE=PAPER
- VERSION=LATEST
- ONLINE_MODE=FALSE
- DIFFICULTY=normal
- OVERRIDE_SERVER_PROPERTIES=TRUE
- ALLOW_NETHER=TRUE
- ANNOUNCE_PLAYER_ACHIEVEMENTS=TRUE
- ENABLE_COMMAND_BLOCK=TRUE
- GENERATE_STRUCTURES=TRUE
- HARDCORE=FALSE
- PVP=TRUE
- SNOOPER_ENABLED=FALSE
- SPAWN_ANIMALS=TRUE
- SPAWN_MONSTERS=TRUE
- SPAWN_NPCS=TRUE
- MODE=survival
- ALLOW_FLIGHT=TRUE
- OPS=Me
- DB_USER=minecraft
- DB_HOST=MCdb
- DB_PORT=3365
- DB_NAME=db
- DB_PASSWORD=password
volumes:
- /local/vanilla:/data

**Comment by voruti** [comment]
> ```
> MCdb:
> image: mysql:latest
> container_name: mc_database
> restart: always
> ports:
> - 3365:3306
> ```

Just as a hint: You do **not** need to publish the port of the database. The Minecraft server can reach the database over Docker's internal network.

**Comment by itzg** [comment]
Good point @voruti !

...and that helped me notice that this issue can be closed 😃
