### ISSUE TITLE
PAPERBUILD environment variable ignored

### ISSUE THREAD

**Issue by Dubhar** [itzg/docker-minecraft-server#715]
After switching to PaperMC V2 API (Commit: 08a4bde6c1a004918f15ae825f0c72adbcde9462) the environment variable PAPERBUILD is not used anymore.
Will this feature be restored/implemented again?
If not please remove "PAPERBUILD" from Readme.md to avoid confusion.

**Comment by itzg** [comment]
Good point. I'll fix this either way.

**Comment by itzg** [comment]
The latest image now includes the fix for this

**Comment by Dubhar** [comment]
Works with image tag _latest_ on amd64.
Thanks alot!
