### ISSUE TITLE
Setup for forgeserver does not work

### ISSUE THREAD

**Issue by Chaoschaot232** [itzg/docker-minecraft-server#716]
Hey,

when I use
```
environment:
  - TYPE=FORGE
  - FORGEVERSION=14.23.5.2854
```
your image /latest and multiarch), tries to download `1.16.4-14.23.5.2854-1.16.4 which is definitly not wanted.
I followed the instructions here on this repro and I assume that they are maybe out of date or that maybe smth. goes wrong behind the scene.

Could you pls take a look into this while I am trying to get my FTB Rev 3.4 server running again but as a forge server or at last a custom server?

Would be nice :) 

Regards

**Comment by Chaoschaot232** [comment]
Took a look into https://github.com/itzg/docker-minecraft-server/blob/master/start-deployForge#L40 and found out that there is a 2nd variable needed which isn't mentioned in the part for the stated type of what I want to deploy. Maybe adding this as hint would be nice ;)

**Comment by itzg** [comment]
It has to try two forms of the forge filename since they used to have a weird naming with 1.12 (I think) and older. There's no harm in what it is doing and rather is necessary to be robust for a wide range of versions. 

What 2nd variable are you referring to?

**Comment by Chaoschaot232** [comment]
Um, 1.12 has at last 3 Stages. 1.12, 1.12.1 and 1.12.2 so and yes, there naming is a bit weired but I can understand it, tbh.

The 2nd variable is `VERSSION=` ... I totaly forgott about this var as it isn't mentioned in the docu directly at the part for forge, where you should only give `FORGEVERSION=` (or Installer) so it confused me, and you software, that it couldn't found a 1.16.4 forge version, with the given "14.x" forge version number ^^

I assumed that the code behind knows that it counts to 1.12.2 and do "the magic" self then, but it didn't.
After adding the 2nd variable it worked even if not the universal file was installed but this is on forges end ;)

**Comment by itzg** [comment]
I'm confused now. I don't see a `VERSSION` (with two S's), just `VERSION` (with one S) in that file. That refers to the main variable used throughout the types

https://github.com/itzg/docker-minecraft-server#versions

I still don't see what is the remaining problem since this iteration here is trying out the two naming conventions and uses the one that succeeds:

https://github.com/itzg/docker-minecraft-server/blob/2fb01b4adfcd279e914ed6a5b1c5bac70994ec11/start-deployForge#L58-L63

Are you finding that the container fails to start with the environment variables shown?

**Comment by itzg** [comment]
where those two version naming variables are declared further up

https://github.com/itzg/docker-minecraft-server/blob/2fb01b4adfcd279e914ed6a5b1c5bac70994ec11/start-deployForge#L39-L40

**Comment by Chaoschaot232** [comment]
Oh, a typo in my response ^^ - Yes, I refered to the env `VERSION=` which is used to define the version which you want to play on.
But looking at the Doc I have read that you use the evns `TPYE=FORGE` and `FORGEVERSION=14.23.5.2854` (this is the recomamnded 1.12.2 file) to specify on which forgeversion you'll play but it ended up in using the version above and 1.16.4 which is totaly false ^^

The problem is that you did not mention to add the `VERSION=` env at this point so I was confused about it, because it didn't wokre like described in the docs, tbh.

**Comment by itzg** [comment]
I see what you mean and I can clarify that in the docs.

**Comment by Chaoschaot232** [comment]
This would be nice 👍

**Comment by itzg** [comment]
[That section](https://github.com/itzg/docker-minecraft-server#running-a-forge-server) has now been updated. Does that look good?

**Comment by Chaoschaot232** [comment]
Know it is  fine, but could you please edit the forgeversion in your codeblock example? Because 1.12.2 and forge 10.x will not work together so maybe replace forgeversion with smth. like `14.23.5.2854` then all should be fine ;)

**Comment by itzg** [comment]
Good catch! That's fixed now.
