### ISSUE TITLE
Expand the openj9 builds to more recent versions (11, 14, 15 etc.)?

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#721]
Are you planning to expand the openj9 builds to more recent versions (11, 14, 15 etc.)? The images are available (for Java 11 for example: https://hub.docker.com/r/adoptopenjdk/openjdk11-openj9).

_Originally posted by @C0Nd3Mnd in https://github.com/itzg/docker-minecraft-server/issues/360#issuecomment-758135039_

**Comment by C0Nd3Mnd** [comment]
> @C0Nd3Mnd I could...but it becomes overwhelming to support all the permutations of JVM provider, Java version, and base OS version. I'd be open to adding one combination of those, like the Java 11 openj9 example you provided. Would that one be sufficient?
> 
> 
> 
> I just realized I should probably close out this issue, but I'll spin off the openj9 + java version item to a new issue.

Supporting Java 11 (or whatever the latest LTS version is, currently 11) is sufficient for me, yeah. Does Docker Hub track which tag is downloaded how often? If so, you could remove tags/branches that are rarely used (I'd imagine `openj9-nightly` isn't used that often, although I could be wrong).

**Comment by C0Nd3Mnd** [comment]
As PaperMC states in [their documentation](https://paper.readthedocs.io/en/latest/server/getting-started.html#requirements), "LTS versions of Java are best supported".

In [this forum post](https://papermc.io/forums/t/java-11-mc-1-17-and-paper/5615) they state that the latest 2 LTS versions of Java will be supported:

> Going forward in general Paper will support the last 2 LTS releases of Java. LTS releases happen every 3 years - the next one will be Java 17 in September 2021. Java 11 is the current LTS release of Java.

So at least for PaperMC servers, offering Java 11 and Java 8 images with OpenJ9 (and later 17 and 11 instead of 11 and 8) makes the most sense.

**Comment by itzg** [comment]
Cool, I'll add an openj9-11 image tag today/tomorrow.

**Comment by itzg** [comment]
- Branch added: https://github.com/itzg/docker-minecraft-server/tree/openj9-11
- `itzg/minecraft-server:openj9-11` published to Docker Hub

**Comment by C0Nd3Mnd** [comment]
Just tested it and it seems to work just fine. Thanks for the quick implementation!

**Comment by Panderine** [comment]
I know this is closed and seems it was already discussed, but I usually have the best performance with openj9 15 using ZGC, specially on the memory footprint department.   
Would you be able to add at least that one is it's not too much trouble?

**Comment by itzg** [comment]
> I know this is closed and seems it was already discussed, but I usually have the best performance with openj9 15 using ZGC, specially on the memory footprint department.
> Would you be able to add at least that one if it's not too much trouble (Alpine openj9 15 amd64)?

@Panderine  I am trying to reduce permutations of images, but I don't mind creating one like a `java15-openj9` if that works. Please open a new issue requesting that one or the one you would prefer.

**Comment by Panderine** [comment]
> @Panderine I am trying to reduce permutations of images, but I don't mind creating one like a `java15-openj9` if that works. 

YOU ARE THE MAN! :D danke schön!
