### ISSUE TITLE
player whitelist docker-compose.yml unintuitive

### ISSUE THREAD

**Issue by Meeuwisse** [itzg/docker-minecraft-server#726]
Friends are loving this so it was time to put a proper configuration in place. While testing I found the following unintuitive - not sure if I'm doing something wrong, etc. Just $0.02.

Whitelist section in README.md does not mention you need to set ENFORCE_WHITELIST: "TRUE"

Letting docker-compose up recreate a container does not change server.properties if it already exists - thus still not enforcing the whitelist, for example.

Changing WHITELIST: playerA,... and 'up' again will add new players listed to whitelist.json, but not remove old ones.

**Comment by itzg** [comment]
The way the minecraft server itself handles the whitelist files and properties is strange to begin with. The [enforce-whitelist](https://minecraft.gamepedia.com/Server.properties#enforce-whitelist) property seems to only apply when you use the `/whitelist reload` command while the server is running. The property [white-list](https://minecraft.gamepedia.com/Server.properties#white-list) is the one that applies more to this container configuration. It gets auto-set to true when the `WHITELIST` env var is used...however, I see now that should be mentioned in the README.

As the additive nature of the whitelist players, it's the default side effect of using the "whitelist.txt" approach in the startup scripts to handoff `whitelist.json` creation to the server itself.

Being able to remove players totally makes sense, but to avoid breaking the behavior for others, I can introduce a variable `OVERRIDE_WHITELIST` to have it wipe out the `whitelist.json` each startup to ensure it'll match up with `WHITELIST`. Would that work for you?

**Comment by Meeuwisse** [comment]
I was just experimenting to make sure it was working as intended. I've added a comment to my configuration reminding myself to remove the `whitelist.json` before updating the allowed players. I think what you suggest would be a nice addition!

**Comment by itzg** [comment]
The latest image now includes `OVERRIDE_WHITELIST ` option

**Comment by Meeuwisse** [comment]
Gave it a spin, works like a charm! Thanks
