### ISSUE TITLE
multiarch-latest broken networking

### ISSUE THREAD

**Issue by eljohnson92** [itzg/docker-minecraft-server#727]
Trying to run with multiarch-latest I think there is a networking issue in the docker image. I tested curl with multiarch and multiarch-latest and it looks like it only works in multiarch. I think this is affecting installs.
mutliarch-latest:
```
docker run --rm  --entrypoint=/bin/bash -it itzg/minecraft-server:multiarch-latest
root@421c7323a269:/data# curl google.com
curl: (28) Timeout was reached
```
multiarch:
```
docker run --rm  --entrypoint=/bin/bash -it itzg/minecraft-server:multiarch
root@a07d27ca01a3:/data# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```
I tried to boil the problem down to it's simplest, let me know if I'm missing something here

**Comment by itzg** [comment]
I tried on two different hosts, but was unable to recreate the issue.

On a Linux Ubuntu 20.04 host:
```
geoff@nuc:~$ docker pull itzg/minecraft-server:multiarch-latest
multiarch-latest: Pulling from itzg/minecraft-server
Digest: sha256:f23c90e94a50f73259c079428adeee23130712371a019a7071ee2af0db01f805
Status: Image is up to date for itzg/minecraft-server:multiarch-latest
docker.io/itzg/minecraft-server:multiarch-latest
geoff@nuc:~$ docker run -it --rm --entrypoint bash itzg/minecraft-server:multiarch-latest
root@0a024a586292:/data# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

On a Docker Desktop Windows WSL 2 host:
```
geoff@nuc:~$ docker pull itzg/minecraft-server:multiarch-latest
multiarch-latest: Pulling from itzg/minecraft-server
Digest: sha256:f23c90e94a50f73259c079428adeee23130712371a019a7071ee2af0db01f805
Status: Image is up to date for itzg/minecraft-server:multiarch-latest
docker.io/itzg/minecraft-server:multiarch-latest
geoff@nuc:~$ docker run -it --rm --entrypoint bash itzg/minecraft-server:multiarch-latest
root@0a024a586292:/data# curl google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```

**Comment by eljohnson92** [comment]
I was running this off of my raspberry pi, so this must be an issue with my environment, I'll continue debugging on my end.

**Comment by dvoelkel** [comment]
I have the same effect here. Raspi4, itzg/minecraft-server:multiarch-latest, installed via portainer.

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Feb  7  2021 /data'
curl: (28) Resolving timed out after 1225470232819 milliseconds

What can I do to get the container run?

**Comment by itzg** [comment]
From #755 it sounds like adding `privileged: true` will likely fix it.

**Comment by eljohnson92** [comment]
I believe this is related to this bug  https://github.com/moby/moby/issues/40734#issuecomment-614259072 haven't tried any of the solutions yet though

**Comment by dvoelkel** [comment]
@itzg Setting the privilege did the trick :) thanks for that. :) 
Now trying to fix "curl: (6) Could not resolve host: launchermeta.mojang.com"
