### ISSUE TITLE
executable file not found in $PATH

### ISSUE THREAD

**Issue by SvobodaGaming** [itzg/docker-minecraft-server#732]
Hello! I have a Spigot 1.12.2 Server. I am try to set multiarch-latest. After start, the server stops with an error:

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 11 1000 1000 4096 Jan 20 10:29 /data'
[init] Resolved version given 1.12.2 into 1.12.2
[init] Resolving type given SPIGOT,[init] Downloading Spigot from https://cdn.getbukkit.org/spigot/spigot-1.12.2.jar ...
[init] Copying plugins over...
[init] Copying any configs from /config to /data/config
[init] server.properties already created, skipping
[init] Checking for JSON files.
[init] Setting initial memory to 3G and max to 3G
[init] Starting the Minecraft server...
2021-01-22T09:46:11.493+0300	ERROR	mc-server-runner	Failed to start	{"error": "exec: \"java\": executable file not found in $PATH"}
2021-01-22T09:46:11.504+0300	ERROR	mc-server-runner	command failed abnormally	{"error": "exec: not started"}
2021-01-22T09:46:11.504+0300	INFO	mc-server-runner	Done

**Comment by itzg** [comment]
Can you provide the command line or compose file that you used to create the container?

**Comment by SvobodaGaming** [comment]
A previous value of `$PATH` was carried over into the new container setup, thus causing the error message above. I'm sorry for being so stupid, tyvm.
