### ISSUE TITLE
World/Level resets

### ISSUE THREAD

**Issue by jdc181091** [itzg/docker-minecraft-server#733]
My World/Level resets after changing Environment variables.
Can anybody help?

**Comment by itzg** [comment]
Please provide the `docker run` command-line or compose file you're using to create the container.

**Comment by jdc181091** [comment]
I'm using Docker in Plesk. Is there any chance  to fix this problem?

**Comment by itzg** [comment]
Yes, it can be fixed but I need a few more clues about how you're attempting so far. A screenshot perhaps?

Are you using a persistent volume for the `/data` mount:

https://github.com/itzg/docker-minecraft-server#attaching-data-directory-to-host-filesystem

**Comment by jdc181091** [comment]
Here my properties 

![mc-server_problem](https://user-images.githubusercontent.com/77899406/105613154-21ad2a00-5dc1-11eb-9601-b3df090c95d8.PNG)

**Comment by itzg** [comment]
Configure a specific volume mapping at

![image](https://user-images.githubusercontent.com/988985/105613178-b34b7600-5d86-11eb-8c99-15d01def5d81.png)

I have never used Plesk's docker support, but I'm guessing a valid path to directory you want to use needs to go in the "Host" field.

**Comment by jdc181091** [comment]
can u give me an example please?

**Comment by itzg** [comment]
An example of a valid path? Examples would be `/home/YourUsername/minecraft-data` on Linux or `C:\Users\YourUsername\minecraft-data` on Windows.

**Comment by itzg** [comment]
Some quick googling I found

https://support.plesk.com/hc/en-us/articles/115001973253-How-to-map-volumes-in-Docker-on-Plesk-server-

https://docs.plesk.com/en-US/onyx/administrator-guide/plesk-administration/using-docker.75823/#o77134

**Comment by jdc181091** [comment]
i change the "Host" to a specific folder on the server an it works! :)
much much thanks for your fast help.

my last question: is it normal that this specific folder has no date in it?

**Comment by itzg** [comment]
Excellent!
