### ISSUE TITLE
Latest FTBA for Direwolf20 1.16 ERROR unable to locate installed forge jar

### ISSUE THREAD

**Issue by DarksideVT** [itzg/docker-minecraft-server#734]
`gamenightMinecraft    | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 7 1000 1000 15 Jan 26 20:24 /data'
gamenightMinecraft    | [init] Resolved version given LATEST into 1.16.5
gamenightMinecraft    | [init] Resolving type given FTBA
gamenightMinecraft    | [init] FTB modpack ID 79, version ID 220 is ready to go
gamenightMinecraft    | [init] ERROR unable to locate the installed forge server jar
gamenightMinecraft    | forge-1.16.4-35.1.36.jar  forge-1.16.5.jar  minecraft_server.1.16.4.jar`

Since the latest Forge version is different is there some issue?

[docker-compose.txt](https://github.com/itzg/docker-minecraft-server/files/5875913/docker-compose.txt)

I've got an almost identical instance on another IP that runs with no issue.

**Comment by DarksideVT** [comment]
Tried removing .ftb-installed like fix #609. Issue still persists.

**Comment by DarksideVT** [comment]
ran same docker-compose on another PC and worked fine. Is there an issue with running two instances of this with different IP?

**Comment by itzg** [comment]
Using your compose file settings it also worked fine for me. Can you try a couple of things:

1. `docker-compose pull` just to make sure you have the latest image. Try again if there was an update.
2. Add `DEBUG: "true"` to the `environment` and provide the additional output from that during startup

**Comment by DarksideVT** [comment]
Latest release seemed to fix it. Sorry I wasn't able to get anything for you. I'll close this. Thanks for the help @itzg I'll remeber the Debug var next time.

**Comment by itzg** [comment]
> I'll remeber the Debug var next time.

In fairness I really need to add that to the README.
