### ISSUE TITLE
Silcrow (Double S) does not parse correctly when setting text colors

### ISSUE THREAD

**Issue by Bulbousonions13** [itzg/docker-minecraft-server#736]
Hi,

Let me start by saying your image(s) are fantastic. Good job.

Issue: When setting the colors of Scoreboard player names using the Silcrow in an eclipse modding environment based in Windows for MC 1.11.2 - everything works fine on both Client and Server - no issues. When the mod is deployed as a volume mounted in the container using your image, the silcrows - § - do not parse correctly and lead to some null pointers. Is this something you have any experience with? Does the base Linux image use different character encoding or something?

Thanks!

**Comment by itzg** [comment]
It sounds similar to an issue that I fixed with https://github.com/itzg/docker-minecraft-server/commit/3de2bf88df93a0ef8ef41830dafb22ca6b45962e ; however, can you tell me more specifics about where you're attempting to use those?
