### ISSUE TITLE
java8 tag is not, in fact java 8

### ISSUE THREAD

**Issue by jaredallard** [itzg/docker-minecraft-server#753]
How to reproduce:

```
$ docker pull itzg/minecraft-server:java8
$ docker run --rm --entrypoint java itzg/minecraft-server:java8 -version
```

Output:

```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

Expected: Java 8 :D

**Comment by itzg** [comment]
Strange, I must have messed something up git-wise along the way. Fixing now...

**Comment by jaredallard** [comment]
Thank you! Also, would you consider using Github Sponsors? I've used your work for a really long time now and it saved me the pain of doing it myself (especially helm charts...). :)

**Comment by itzg** [comment]
> Also, would you consider using Github Sponsors?

Thanks for reminding me to look again into that. My quick solution for now has been https://www.buymeacoffee.com/itzg

**Comment by itzg** [comment]
Published image is now fixed and now correctly reports:

```
> docker run --rm --entrypoint java itzg/minecraft-server:java8 -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

Sorry for that silly mistake...and thanks for the coffees!

**Comment by jaredallard** [comment]
> Published image is now fixed and now correctly reports:
> 
> ```
> > docker run --rm --entrypoint java itzg/minecraft-server:java8 -version
> openjdk version "1.8.0_212"
> OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
> OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
> ```
> 
> Sorry for that silly mistake...and thanks for the coffees!

Thanks for the quick fix! Confirmed :)
