### ISSUE TITLE
AutoPause does not work in a docker on Synology NAS

### ISSUE THREAD

**Issue by VeanD99** [itzg/docker-minecraft-server#754]
Hi there,

I am using the minecraft-server for docker on my Synology NAS. It runs perfect but I just cant get the Auto Pause function to work. The container simply does not recognizes the extra environment. It is not possible to run any commands in this version of docker but it is possible to add environment settings. Those work except for the ENABLE_AUTOPAUSE. When I add this element, the server just starts up as normal but without this feature. Is there someone who recognizes this problem and knows how to solve it?

Kindes Regards.

**Comment by itzg** [comment]
I don't have experience with Synology and it seems to add an extra complication to Docker IMHO. So let's see if someone else has experience getting autopause running on Synology.

**Comment by UpsettingBoy** [comment]
I currently have an instance running on a Synology NAS with auto-pause activated. No problem whatsoever besides it sometimes crash because of this feature (it is expected tho)

**Comment by VeanD99** [comment]
Ahh okay! Is it maybe possible for you to share your environment settings? Because my server doesn't recognize the environment setting at all, no mention of an AutoPause proces.

**Comment by UpsettingBoy** [comment]
Which server type are you using?

**Comment by VeanD99** [comment]
I use Spigot

**Comment by UpsettingBoy** [comment]
This works for my with Paper. Set this env. variables:

- MAX_TICK_TIME = -1
- WATCHDOG = -1

I don't know if this will work for you. Search how to disable Spigot watchdog.

**Comment by VeanD99** [comment]
I found out what the issue is! As standard, the provided Image Synology downloads runs Java8. When I used Java15 in combination with PAPER, the environment settings of AutoPause were already loaded. I am not sure if it would be different with Spigot but I think the Java version solved the problem.
Thanks for the help!
