### ISSUE TITLE
Vanilla to Spigot world conversion

### ISSUE THREAD

**Issue by F0Xde** [itzg/docker-minecraft-server#757]
Currently the `DIM1` and `DIM-1` directories are [manually moved](https://github.com/itzg/docker-minecraft-server/blob/8312233a9393832d62d6638e1e6b516abbe33ff5/start-finalSetupWorld#L56) to `world_the_end` and `world_nether`, which does not work when these directories already exists, as `mv` fails in this case.
Now as it turns out Spigot is already able to move the directories itself when encountering them, so really I think these lines could just be completely removed, if there's no other requirement for them to stay.

**Comment by itzg** [comment]
Interesting. Yeah, if Spigot that itself then I agree it would be best to simply remove those.
