### ISSUE TITLE
Can't connect to server from outside network.

### ISSUE THREAD

**Issue by CleavisX** [itzg/docker-minecraft-server#764]
Hello! I am able to connect to my minecraft server from its IP locally (192.168.xx.xx) but I can't connect using the IP I find on myip.com.

I have port forwarded minecraft's ports with the static IP of the container, but I still can't connect. Does the docker container have its own public IP that it uses? or does it just use the network public IP like a minecraft server I run on my pc does?

**Comment by itzg** [comment]
Can we just use #761 for discussion? It's tough to jump between two issues to discuss inter-related things.
