### ISSUE TITLE
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by nygage** [itzg/docker-minecraft-server#766]
Hello, i'm triying to run the image under a Terramaster NAS and i'm getting this error. I've triyed with solutions mentioned in #466 but nothings seems to happen. 

Here is the log: https://0paste.com/183196

What can be? 
Thanks!

**Comment by itzg** [comment]
The logs further up apply to your scenario:
```
mc    | [init] **********************************************************************
mc    | [init] WARNING: The image tag itzg/minecraft-server:java8 is recommended
mc    | [init]          since some mods require Java 8
mc    | [init] **********************************************************************
```

**Comment by RikGeboers** [comment]
had the same exception but with running multiarch for FTBA modapack id 35
[pastebin log](https://0paste.com/193839)

**Comment by itzg** [comment]
@RikGeboers similarly there is now an `itzg/minecraft-server:java8-multiarch` image.

**Comment by nygage** [comment]
> @RikGeboers similarly there is now an `itzg/minecraft-server:java8-multiarch` image.

It worked for me, thanks! I'll wait until @RikGeboers feedback

**Comment by RikGeboers** [comment]
Worked perfectly! You can close it
