### ISSUE TITLE
cannot connect : invalid session

### ISSUE THREAD

**Issue by jolypas** [itzg/docker-minecraft-server#769]
hello

I tried online_mode = false & true but I cannot connect on local server / local lan using TLauncher 

[12:02:12] [Server thread/INFO]: com.mojang.authlib.GameProfile@405ff961[id=<null>,name=xxxxxx,properties={},legacy=false] (/192.168.2.96:12220) lost connection: Disconnected

on launcher part I get
"Invalid session"

**Comment by jolypas** [comment]
I found the issue

    environment:
      - PUID=998
      - PGID=100
      - EULA=TRUE
      - VERSION=SNAPSHOT
      - MEMORY=2G
      - ANNOUNCE_PLAYER_ACHIEVEMENTS=true
      - ONLINE_MODE=FALSE

ONLINE_MODE is not transmitted to sever.properties. I corrected manualy the file into the docker data repository and it works.

**Comment by itzg** [comment]
It might have already created the server.properties on first startup and then after that it will avoid modifying the file unless OVERRIDE_SERVER_PROPERTIES is set:

https://github.com/itzg/docker-minecraft-server#server-configuration
