### ISSUE TITLE
FTB Minecraft Server - A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by bmduke1997** [itzg/docker-minecraft-server#770]
When trying to create an FTB Minecraft server using the examples/docker-compose-ftba.yaml as an example I created the attached docker-compose file. When running docker-compose up I get the following [output](https://0paste.com/188107).

I am running docker on an Ubuntu 20.04.2.

[docker-compose.txt](https://github.com/itzg/docker-minecraft-server/files/5978446/docker-compose.txt)

**Comment by itzg** [comment]
Sorry, I need to update that example with the "new" Java 8 image `itzg/minecraft-server:java8-multiarch`

**Comment by itzg** [comment]
Examples have been updated.

**Comment by bmduke1997** [comment]
Sorry, it took me so long to respond, that fixed it right up!
