### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Paul42812** [itzg/docker-minecraft-server#771]
I set up itzg/minecraft-server for my fabric server and everything seemed to be working. But If I try to connect i get:
`io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused:`
But in the Server preview it looks normal

**Comment by itzg** [comment]
Can provide more info about the container setup?

**Comment by Paul42812** [comment]
I'm using compose:
```
survival:
  image: itzg/minecraft-server:latest

  ports:
    - "25599:25565"
    - "25589:25575"

  environment:
    FORCE_REDOWNLOAD: "TRUE" 
    EULA: "TRUE"
    TYPE: FABRIC
    VERSION: "1.16.5"
    
    
    OVERRIDE_SERVER_PROPERTIES: "TRUE"
  
  volumes:
    - /home/paulj/dockermc/survival:/data
  
  tty: true
  stdin_open: true
  restart: always```

**Comment by Paul42812** [comment]
Linux manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
Docker version 20.10.3, build 48d30b5b32
docker-compose version 1.28.2, build unknown
![picture](https://user-images.githubusercontent.com/66885609/108330816-5947a000-71ce-11eb-864f-b3189bcb05c9.png)

**Comment by itzg** [comment]
What host/connection string are you using in the client? Since you're using a non-standard port then that will be important.

**Comment by Paul42812** [comment]
0:25599

**Comment by Paul42812** [comment]
Sorry for the incident it works fine with localhost:25599
