### ISSUE TITLE
Unable to run Enigmatica 6 Server

### ISSUE THREAD

**Issue by AndreiPurcaru** [itzg/docker-minecraft-server#772]
I have tried different docker-compose files and every time it gets stuck with its last lines being 
```
Running FTB /data/FeedTheBeast/mods/ServerStart.sh in /data/FeedTheBeast/mods ...
minecraft_e6 | no main manifest attribute, in forge-1.16.5-geckolib-3.0.7.jar
minecraft_e6 | 2021-02-18T15:53:34.815Z INFO    mc-server-runner        Done
 ```

A weird thing I have noticed is that for some reason the server and properties files are placed inside the /mods folder. I have tried to run the docker-compose with ` DEBUG: "true" ` but I am not getting any significant output. I have also tried the env ` USE_MODPACK_START_SCRIPT: "false" `.

My `docker-compose.yml` looks like this now:
```
version: '3'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft_e6
    ports:
      - "25567:25565"
    volumes:
      - "./data:/data"
      - "./modpacks:/modpacks:ro"
    environment:
      EULA: "TRUE"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/Enigmatica6Server-0.3.13.zip
#      USE_MODPACK_START_SCRIPT: "false"
      CONSOLE: "false"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "Str0ngA5St33l"
      RCON_PORT: 28016
      INIT_MEMORY: 1G
      MAX_MEMORY: 6G
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: 600
      DEBUG: "true"
    restart: unless-stopped
  rcon:
    image: itzg/rcon
    container_name: rcon_e6
    ports:
      - "4340:4326"
      - "4341:4327"
    volumes:
      - "rcon:/opt/rcon-web-admin/db"

volumes:
  rcon:
```

**Comment by itzg** [comment]
It sounds like there's something broken in that modpack since the container is not responsible for how the modpacks startup script does it's downloading. Perhaps see if the modpack has a way to discuss issues.

**Comment by itzg** [comment]
With `USE_MODPACK_START_SCRIPT: "false"` I enhanced the modpack handling to lookup the installer URL from the modpack's config file. Re-pull the image and see if that works for you now.

**Comment by zachcheatham** [comment]
I also ran into this issue with GreedyCraft from CurseForge and after disabling the pack's start script, I still couldn't launch. I found that the launch script is picking up multiple forge-*.jar files due to the geckolib mod who's file name is like forge-1.12.2-geckolib-3.0.0-beta.7.jar in the /mods/ directory. I solved the issue by renaming that mod's jar to something that didn't start with "forge-"

Here is some of the debug output around where the script locates forge before I renamed the jar:
```
+ export 'SERVER=/data/FeedTheBeast/mods/forge-1.12.2-geckolib-3.0.0-beta.7.jar
/data/FeedTheBeast/forge-1.12.2-14.23.5.2855.jar'
+ SERVER='/data/FeedTheBeast/mods/forge-1.12.2-geckolib-3.0.0-beta.7.jar
/data/FeedTheBeast/forge-1.12.2-14.23.5.2855.jar'
+ [[ -z /data/FeedTheBeast/mods/forge-1.12.2-geckolib-3.0.0-beta.7.jar
/data/FeedTheBeast/forge-1.12.2-14.23.5.2855.jar ]]
+ [[ ! -f /data/FeedTheBeast/mods/forge-1.12.2-geckolib-3.0.0-beta.7.jar
/data/FeedTheBeast/forge-1.12.2-14.23.5.2855.jar ]]
```

**Comment by itzg** [comment]
@zachcheatham make sure to re-pull the image you are using. The debug output looks like it doesn't include the latest fix.
