### ISSUE TITLE
FTBA 

### ISSUE THREAD

**Issue by jsProj** [itzg/docker-minecraft-server#773]
I find that running: `sudo docker run --privileged --name ftb -e EULA=TRUE -e TYPE=FTBA -e FTB_MODPACK_ID=60 -e MEMORY=4G -p 25565:25565 -v /home/pi/ftb_data:/data itzg/minecraft-server:multiarch` gives me the error of:

```
[init] Changing ownership of /data to 1000 ...
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Feb 21 07:34 /data'
[init] Resolved version given LATEST into 1.16.5
[init] Resolving type given FTBA
[init] Downloading FTB installer
[init] Installing modpack ID 60, version ID 198
/start-deployFTBA: line 40: /data/ftb-installer: cannot execute binary file: Exec format error
```

I was wondering if anyone has got a workaround-fix to this, it seems to be that the install file of whats downloaded from ftb is in the wrong format, (i presume not for arm)

**Comment by itzg** [comment]
Yeah, their launcher only works for x86. I should probably figure out how to log a more informative error when using ARM with FTBA.

**Comment by jsProj** [comment]
Well I'm screwed then, fml

**Comment by itzg** [comment]
FWIW I'm afraid any FTB modpack would run poorly on RPI hardware anyway. Speaking of which, I didn't know any of the models had > 4GB of RAM. 

In any case, if you want to experiment you can always download the modpacks manually use TYPE=CURSEFORGE.

**Comment by jsProj** [comment]
What would be the full command line to get the tech world to mod pack from Chris forge using that

**Comment by itzg** [comment]
Here is the section for that

https://github.com/itzg/docker-minecraft-server#running-a-server-with-a-curseforge-modpack

and make sure to download the server files modpack

https://www.curseforge.com/minecraft/modpacks/tech-world/files/2260221

**Comment by chrisfowles** [comment]
> FWIW I'm afraid any FTB modpack would run poorly on RPI hardware anyway

Worth noting that ARM is not limited to RPI hardware - many cloud offerings have cheaper ARM servers than x86 now.

**Comment by itzg** [comment]
Good point @chrisfowles , that's why I qualified that with "RPI hardware"
