### ISSUE TITLE
Setting a property in server.properties fails if the line does not exist already

### ISSUE THREAD

**Issue by the-vindex** [itzg/docker-minecraft-server#776]
Situation:
- server.properties coming delivered by modpack
- OVERRIDE_SERVER_PROPERTIES enabled
- rcon.password is not present in server.properties from the modpack

Failure:
- rcon.password is not created and hence not set
- impact - RCON is not started, backups are not running because they cannot connect to RCON

I blame following function: https://github.com/itzg/docker-minecraft-server/blob/e46af9d54c014adb94d6dd2293ef162732f0f251/start-finalSetupServerProperties#L6
- it does not check for the situation when the line doesn't exist

**Comment by itzg** [comment]
Yep, I see what you mean. This line specifically will only swap out if it's there (commented out or not):

https://github.com/itzg/docker-minecraft-server/blob/e46af9d54c014adb94d6dd2293ef162732f0f251/start-finalSetupServerProperties#L16

**Comment by itzg** [comment]
The latest image should now fix this, so re-pull that and give it a try.
