### ISSUE TITLE
Legacy FTB fix broken

### ISSUE THREAD

**Issue by jsProj** [itzg/docker-minecraft-server#777]
The location where it grabs legacyjavafixer.jar is gone... anyone know where i can get an alternative?, also @itzg is it possible you could update the FTB curseforge type, maybe with a working location

```
[init] Installing legacy java fixer to /data/FeedTheBeast/mods/legacyjavafixer.jar
curl: (6) Could not resolve host: ftb.forgecdn.net
```

run script

```
sudo docker run --privileged --rm -v /home/pi/modpacks:/modpacks -v /home/pi/tw2_data:/data -e TYPE=CURSEFORGE -e CF_SERVER_MOD=/modpacks/TechWorld2-1.1.6-1.6.4Server.zip -e FTB_LEGACYJAVAFIXER=true -p 25565:25565 -e EULA=TRUE --name tw2 itzg/minecraft-server:java8-multiarch
```

**Comment by jsProj** [comment]
Even visiting ftb.forgecdn.net comes up with unresolved in my browser...

**Comment by jsProj** [comment]
Downloading the mod externally, and see what I can do with it.

**Comment by jsProj** [comment]
no luck, leaves players unable to connect

**Comment by itzg** [comment]
Is there a copy of the jar available for manual download? If so, maybe I could just bundle it within the image of the license allows.

**Comment by jsProj** [comment]
Possibly, but the ones I've downloaded error out the server, disallow loving and connecting to it

**Comment by itzg** [comment]
I'm not sure how to fix this then. Is there a particular modpack that consistently causes the issue?

**Comment by jsProj** [comment]
I'm trying tech world 2, but I could test with another modpack later

**Comment by Silversurfer79** [comment]
Hi, Any movment on this yet? 
Same issue here, been wanting to add mods for my daughter.
Tried: RLCraft and SkyFactory 4, same for both.

![image](https://user-images.githubusercontent.com/58236890/118344988-30128380-b521-11eb-9c74-8b4585a412d2.png)

**Comment by gurustave** [comment]
https://files.minecraftforge.net/maven/net/minecraftforge/lex/legacyjavafixer/1.0/legacyjavafixer-1.0.jar

**Comment by itzg** [comment]
A PR would be great 😉

**Comment by gurustave** [comment]
> A PR would be great wink

Will do in a couple minutes, at least for updating the URL. Just wanted to get the link out there last night as it was late for me when I found it. 

> Is there a copy of the jar available for manual download? If so, maybe I could just bundle it within the image of the license allows.

The repo says the source is under the MIT License.
https://github.com/MinecraftForge/LegacyJavaFixer
