### ISSUE TITLE
Support Flag --cpuset-cpus

### ISSUE THREAD

**Issue by yogi7777** [itzg/docker-minecraft-server#778]
Hi,

I can't start the container with the flag --cpuset-cpus=8 or eq.

`SEVERE: cpuset-cpus is not a recognized option`

can you add support for this flag? 
I have many Minecraft Server on the root server and i have performance issues. java can't handle multi cpu's.

thanks

**Comment by itzg** [comment]
That argument is not in my scope to support. Make sure you're passing it before the image name in the `docker run` command line

https://docs.docker.com/config/containers/resource_constraints/#cpu

**Comment by yogi7777** [comment]
> That argument is not in my scope to support. Make sure you're passing it before the image name in the `docker run` command line
> 
> https://docs.docker.com/config/containers/resource_constraints/#cpu

oooh this works :) i added in the top of my stackfile cpuset: "8" 
thanks for your help :)
