### ISSUE TITLE
Removing old PaperMC versions step takes over 15 mins on Synology NAS

### ISSUE THREAD

**Issue by Andrew-H2O** [itzg/docker-minecraft-server#779]
Don't know why, but when starting up the "removing old PaperMC versions" step in the startup takes over 15 minutes to complete.  Once past this everything works just fine, but it means that restarts for plugin updates (for example) can be a bit tedious.

Relevant log snip with timestamps: 

> 2021-02-23 13:30:57	stdout	[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    1 1000     1000           578 Feb 22 23:41 /data' 
> 2021-02-23 13:30:59	stdout	[init] Resolved version given LATEST into 1.16.5 
> 2021-02-23 13:31:03	stdout	[init] Resolving type given PAPER
> 2021-02-23 13:31:03	stdout	[init] Removing old PaperMC versions ... 
> 2021-02-23 13:44:27	stdout	./paper-1.16.5-484.jar 
> 2021-02-23 13:44:27	stdout	[init] Downloading PaperMC 1.16.5 (build 487) ... 
> 2021-02-23 13:44:30	stdout	[init] server.properties already created, skipping

**Comment by itzg** [comment]
Can you make sure you have pulled the latest image since I fixed that kind of issue recently 959bf73485b2a5964d7241e8bfafeff55d374864

**Comment by Andrew-H2O** [comment]
Yes, I'd seen that change, and I can confirm that the image I'm using is more recent than that - the log snippet I posted was after using Portainer to recreate the container pulling the latest image in the process.

**Comment by itzg** [comment]
Hmm, perhaps limiting the find's depth doesn't really prevent it from making the traversal. I might just change that to a plain old file glob.

**Comment by Andrew-H2O** [comment]
I'll be happy to test it for you...

**Comment by itzg** [comment]
Please re-pull the latest image and see if that speeds up that step.

**Comment by Andrew-H2O** [comment]
That seems to have done the trick.  

From clicking 'Start Container', it now seems to take about **45 seconds** total for it to initialize.  
I can also confirm that it removes older versions of the paper-*.jar file as expected.
