### ISSUE TITLE
Fix build for mohist server?

### ISSUE THREAD

**Issue by flololan** [itzg/docker-minecraft-server#781]
Hi,

We would like to have a 1.16.x server with Forge+Paper/Bukkit. The only server that does this more or less seems to be mohist but as it is still in developement there are reuglarily builds who introduce new bugs. Could we get an environment variable to specify a specific build for mohist so that if we find a build that fits our need, we can keep it? Because the "VERSION"-variable only sets if I want the latest 1.12 or 1.16 build...

Thanks in advance

**Comment by itzg** [comment]
Yes, it looks like that would be doable to allow a specific build to be specified rather than looking up the latest.

**Comment by flololan** [comment]
That would be awesome!

**Comment by itzg** [comment]
The latest image now includes an option for `MOHIST_BUILD`:

https://github.com/itzg/docker-minecraft-server#running-a-mohist-server
