### ISSUE TITLE
READ ME update request

### ISSUE THREAD

**Issue by finndo77** [itzg/docker-minecraft-server#782]
hello again, I ran in to an issue with setting the "SEED" environment variable. if the SEED ID is negative, you need o put the number in double quotes for it to be read (the string is ignored without quotes).

Related, the MOTD note about quoting, you can put double quotes around the message, you don't need to single quote the variable and entire string.  Probably a note at the top regarding quoting would cover it all, or more thoroughly a note on each variable that "could" have any non alpha numeric characters.

existing examples
-e SEED=1785852800490497919
-e 'MOTD=My Server'

functioning examples (note the negative sign in the seed#)
-e MOTD="My Server"
-e SEED="-1785852800490497919"

note: everything works, just a READ ME update request to avoid any user issues.

**Comment by itzg** [comment]
Great suggestion! The docs are updated.
