### ISSUE TITLE
Crash/stall with latest image

### ISSUE THREAD

**Issue by mhbates** [itzg/docker-minecraft-server#783]
Hi there. Watchtower grabbed the latest image for me this morning and the container is no longer starting up properly. Error is below. Rolling back to 2021.5.1 fixes it.

>  A fatal error has been detected by the Java Runtime Environment:
> 
>   SIGSEGV (0xb) at pc=0x00007f1d77c6801c, pid=93, tid=135
> 
>  JRE version: OpenJDK Runtime Environment AdoptOpenJDK (11.0.10+9) (build 11.0.10+9)
>  Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK (11.0.10+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
>  Problematic frame:
>  C  [libc.so.6+0xe801c]
> [error occurred during error reporting (printing problematic frame), id 0xb, SIGSEGV (0xb) at pc=0x00007f1d77c01980]
> 
>  Core dump will be written. Default location: /data/core
> 
>  An error report file with more information is saved as:
>  /data/hs_err_pid93.log
> 
>  If you would like to submit a bug report, please visit:
>    https://github.com/AdoptOpenJDK/openjdk-support/issues
>  The crash happened outside the Java Virtual Machine in native code.
>  See problematic frame for where to report the bug.

**Comment by itzg** [comment]
I'm afraid it might be beyond my control to fix that. You may need to submit a bug report to AdoptOpenJDK as the crash log reports. For myself and others, the latest image is starting up and running fine, so it's unfortunately a unique interaction on your particular system, kernel, file state, etc.

Are you using the multiarch variants of image tags? I ask because libc.so is not normally involved with the Alpine variants.

**Comment by mhbates** [comment]
I've been using the latest tag, or rather no tag specified at all which I assume is latest. Perhaps the wrong version was pushed to latest?

**Comment by itzg** [comment]
From my pull, latest image is what I expected and correctly using alpine. Again, I'm afraid it's something unique to your environment and not sure how/what.

**Comment by mhbates** [comment]
Thanks. For reference, I'm on Debian 10 Buster.

One other thing I noticed is that after stopping the container, I still see a lot of I/O activity for a few more minutes, according to iotop. Specifically:

`[kworker/u8:0+flush-8:16]`

Anyway, I did a quick search and it looks like someone already created an issue on AdoptOpenJDK: https://github.com/AdoptOpenJDK/openjdk-support/issues/263

**Comment by nmills3** [comment]
just for the record, i'm getting the same issue here. i'm using latest spigot and docker is running on unraid

**Comment by nmills3** [comment]
Not sure if this helps, but a temporary fix that's working for me, if you switch over to the java8 image it seems to be working. not perfect but a good patch while you wait

**Comment by eugeneindigo** [comment]
I had the same issue today. On 25th when I booted up my server with latest tag it ran fine. But when I had booted up my server today again with latest tag it has crashed with SIGSEGV errors. Rolling back to tag 2021.5.1-adopt11 worked for me, it is working for now.

**Comment by itzg** [comment]
Hmm, is wonder what the pattern is...I'll also check over any differences in the image layers that might give some clues.

**Comment by nmills3** [comment]
i'm not sure if this helps or not. When i'm running the latest 1.16 spigot the issue happens. but using the exact same docker image but with the latest snapshot build it's working fine

**Comment by Cubxity** [comment]
This happens do to a recent update in alpine's image. See [AdoptOpenJDK/openjdk-docker #520](https://github.com/AdoptOpenJDK/openjdk-docker/issues/520), [Cubxity/docker-minecraft-server #1](https://github.com/Cubxity/docker-minecraft-server/issues/1).

**Comment by Andrei-Paul** [comment]
Just here to +1 it, container hosted on poseidon/typhoon+flatcar-stable. Tag latest crashed as described, tag 2021.5.1 worked.

**Comment by itzg** [comment]
Also be sure to +1 the issue that @Cubxity linked, since that's the root cause.

**Comment by n00b42** [comment]
Having the same problem while running PaperMC, actually server starts fine for me as long as I do not use specific plugins.
e.g. enabling WorldGuard kills the server as soons as the first player trys to connect.

**Comment by n00b42** [comment]
They reverted to an older version a few days ago (and are investigating the issue).
Therefore a rebuild image with their reverted version might already fix it for now.

**Comment by itzg** [comment]
Thanks @n00b42 ! I am subscribed to the issue, but they didn't mention the image was re-published there. In any case, `itzg/minecraft-server:latest` is now rebuilt and reports an Alpine release of 3.12.4.

**Comment by n00b42** [comment]
At least the problem I had is gone with the republished image (for now).
Will have to retest when they move to the newer version again.

@itzg They mentioned a Merge(Request) about going back. And if I read correctly their images are nightlies (at least for alpine etc). Therefore, I assumed that the latest update of the image might include that MR. So it was only semi-mentioned in the issue ;)

Thanks.

**Comment by yllekz** [comment]
Also running into crashing issues here. Server runs for about 5-10 minutes then falls over. It's also running my Pi up to 100% CPU and RAM consumption. Going to +1 the issue linked above.
