### ISSUE TITLE
Possible conflict with Alpine 3.13 and OpenJDK

### ISSUE THREAD

**Issue by benab** [itzg/docker-minecraft-server#791]
Hello. First, I have to say that this Minecraft Docker is so handy and well documented! Thanks for the time you put in!

I recently had trouble running a Paper server with the floodgate-bukkit plugin in the _latest_ Java version (Java 11, Alpine) of docker-minecraft-server.

I opened a ticket in the [Floodgate](https://github.com/GeyserMC/Floodgate) repo and it seems that it could be an upstream issue with the Docker container as opposed to the Floodgate plugin itself. 

I was eventually able to get the plugin to work without crashing when I switched to the _multiarch_ (Ubuntu) image.

It was suggested that I open a ticket on this repo to see if there are potential issues with the container. Hopefully this isn't a duplicate issue.

Here's a link to the ticket I've opened on the Floodgate repo: [https://github.com/GeyserMC/Floodgate/issues/120](https://github.com/GeyserMC/Floodgate/issues/120)

Cheers!

**Comment by benab** [comment]
In fact, just after posting this ticket, I see another that may be related, but am not sure: [https://github.com/itzg/docker-minecraft-server/issues/783](https://github.com/itzg/docker-minecraft-server/issues/783)

**Comment by itzg** [comment]
Yes that’s a related issue and the root cause is further upstream 

https://github.com/AdoptOpenJDK/openjdk-docker/issues/520

**Comment by benab** [comment]
Okay. Thanks much for verifying.
