### ISSUE TITLE
Can't install MAGMA Server

### ISSUE THREAD

**Issue by Johann-vln** [itzg/docker-minecraft-server#792]
When i run the Magma Server with this Command ("docker run -d -v /home/lib/leipziginblocks/magma_server:/data -e TZ=Europe/Berlin -e TYPE=MAGMA -p 25565:25565 -p 25575:25575 -e EULA=TRUE -e MEMORY=6G -e ENABLE_RCON=true -e RCON_PASSWORD=Password --name mc-server itzg/minecraft-server:java8
e1109db65d8eea04e8e6214bcd76bd3cfc08baef9a4e0aaa37f64c2984c80d77") it gave me this error

[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x   12 1000     1000          4096 Mar  4 09:10 /data'
[init] Resolved version given LATEST into 1.16.5
[init] Resolving type given MAGMA
curl: (22) The requested URL returned error: 500
[init] ERROR unable to download version 1.16.5 of Magma
[init]       Check https://magmafoundation.org/ for available versions

Why?
How can i solve it

**Comment by itzg** [comment]
If the Magma URL is returning a 500 status code then that's a problem on their end. Please report an issue with Magma. 

FYI https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

**Comment by itzg** [comment]
Their API server is still broken by confirming with curl:

```
> curl -v https://api.magmafoundation.org/api/resources/Magma/1.16.5/stable/latest/download
*   Trying 185.173.26.97:443...
* TCP_NODELAY set
* Connected to api.magmafoundation.org (185.173.26.97) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api.magmafoundation.org
*  start date: Jan 13 14:10:48 2021 GMT
*  expire date: Apr 13 14:10:48 2021 GMT
*  subjectAltName: host "api.magmafoundation.org" matched cert's "api.magmafoundation.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55d44fac2670)
> GET /api/resources/Magma/1.16.5/stable/latest/download HTTP/2
> Host: api.magmafoundation.org
> user-agent: curl/7.68.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 500
< server: nginx/1.17.8
< date: Sat, 06 Mar 2021 02:49:09 GMT
< content-type: text/html; charset=utf-8
< content-length: 14
< x-powered-by: Express
< access-control-allow-origin: *
< etag: W/"e-I1dfNaUh6cJh0nSsTLKcLwWyYaw"
< vary: Accept-Encoding
< strict-transport-security: max-age=15724800; includeSubDomains
<
* Connection #0 to host api.magmafoundation.org left intact
Internal Error
```

**Comment by itzg** [comment]
Their API docs page also fails with 500:

![image](https://user-images.githubusercontent.com/988985/110192577-90d06200-7df4-11eb-92aa-796e9f613c58.png)

**Comment by kingdevnl** [comment]
Hey i'm one of the magma devs I will have a look what's wrong with the API

Our own website uses the API aswell and dousn't seem to have any issues

**Comment by itzg** [comment]
> Hey i'm one of the magma devs I will have a look what's wrong with the API

Thanks. FWIW I just tried the `curl` above and I'm still getting a 500.

**Comment by kingdevnl** [comment]
Our api has changed last week. The image has to be updated

**Comment by itzg** [comment]
@patchint You're already using java8 variant, so `docker-compose pull` will grab the latest.
