### ISSUE TITLE
Unable to join the Minecraft Server

### ISSUE THREAD

**Issue by sd016808** [itzg/docker-minecraft-server#807]
Hi,
   I use the raspberry pi 4 and the Portainer to hold the server with the tag:armv7.
   When I try to join the server, the log shows some error message as below:

[10:47:56] [Worker-Main-4/INFO]: Loaded 7 recipes
,[10:47:57] [Worker-Main-4/INFO]: Loaded 927 advancements
,[10:48:01] [Server thread/INFO]: Starting minecraft server version 1.16.5
,[10:48:01] [Server thread/INFO]: Loading properties
,[10:48:01] [Server thread/INFO]: Default game type: SURVIVAL
,[10:48:01] [Server thread/INFO]: Generating keypair
,[10:48:02] [Server thread/INFO]: Starting Minecraft server on *:25565
,[10:48:02] [Server thread/INFO]: Using default channel type
,[10:48:04] [Server thread/INFO]: Preparing level "world"
,[10:48:04] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:08] [Server thread/INFO]: Preparing spawn area: 0%
,[10:48:09] [Server thread/INFO]: Preparing spawn area: 5%
,[10:48:09] [Server thread/INFO]: Preparing spawn area: 63%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:28] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:29] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:29] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:30] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:30] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:31] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:31] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:32] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:32] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:33] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:33] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:34] [Worker-Main-6/INFO]: Preparing spawn area: 83%
,[10:48:34] [Worker-Main-8/INFO]: Preparing spawn area: 83%
,[10:48:35] [Worker-Main-7/INFO]: Preparing spawn area: 83%
,[10:48:35] [Worker-Main-8/INFO]: Preparing spawn area: 84%
,[10:48:36] [Worker-Main-8/INFO]: Preparing spawn area: 85%
,[10:48:36] [Worker-Main-7/INFO]: Preparing spawn area: 86%
,[10:48:37] [Worker-Main-7/INFO]: Preparing spawn area: 86%
,[10:48:37] [Server thread/INFO]: Preparing spawn area: 87%
,[10:48:38] [Server thread/INFO]: Preparing spawn area: 88%
,[10:48:38] [Server thread/INFO]: Preparing spawn area: 89%
,[10:48:39] [Worker-Main-8/INFO]: Preparing spawn area: 89%
,[10:48:39] [Worker-Main-6/INFO]: Preparing spawn area: 90%
,[10:48:40] [Worker-Main-6/INFO]: Preparing spawn area: 91%
,[10:48:40] [Worker-Main-7/INFO]: Preparing spawn area: 92%
,[10:48:41] [Worker-Main-6/INFO]: Preparing spawn area: 92%
,[10:48:41] [Worker-Main-6/INFO]: Preparing spawn area: 93%
,[10:48:42] [Worker-Main-7/INFO]: Preparing spawn area: 94%
,[10:48:42] [Worker-Main-8/INFO]: Preparing spawn area: 94%
,[10:48:43] [Worker-Main-6/INFO]: Preparing spawn area: 96%
,[10:48:43] [Worker-Main-7/INFO]: Preparing spawn area: 97%
,[10:48:44] [Worker-Main-8/INFO]: Preparing spawn area: 98%
,[10:48:44] [Worker-Main-8/INFO]: Preparing spawn area: 99%
,[10:48:44] [Server thread/INFO]: Time elapsed: 40249 ms
,[10:48:44] [Server thread/INFO]: Done (40.469s)! For help, type "help"
,[10:48:44] [Server thread/INFO]: Starting remote control listener
,[10:48:44] [Server thread/INFO]: Thread RCON Listener started
,[10:48:44] [Server thread/INFO]: RCON running on 0.0.0.0:25575
,[10:49:06] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started
,[10:49:06] [RCON Client /192.168.50.163 #2/INFO]: Thread RCON Client /192.168.50.163 shutting down
,[10:49:13] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started
,[10:49:13] [RCON Client /192.168.50.163 #3/INFO]: Thread RCON Client /192.168.50.163 shutting down
,

The inspect file is as follows:
{
    "AppArmorProfile": "",
    "Args": [],
    "Config": {
        "AttachStderr": false,
        "AttachStdin": false,
        "AttachStdout": false,
        "Cmd": null,
        "Domainname": "",
        "Entrypoint": [
            "/start"
        ],
        "Env": [
            "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "LANG=en_US.UTF-8",
            "LANGUAGE=en_US:en",
            "LC_ALL=en_US.UTF-8",
            "JAVA_VERSION=jdk-11.0.10+9",
            "JAVA_HOME=/opt/java/openjdk",
            "UID=1000",
            "GID=1000",
            "MEMORY=2G",
            "TYPE=VANILLA",
            "VERSION=LATEST",
            "ENABLE_RCON=true",
            "RCON_PORT=25575",
            "RCON_PASSWORD=minecraft",
            "SERVER_PORT=25565",
            "ONLINE_MODE=TRUE",
            "SERVER_NAME=33 Minecraft Server",
            "ENABLE_AUTOPAUSE=false",
            "AUTOPAUSE_TIMEOUT_EST=3600",
            "AUTOPAUSE_TIMEOUT_KN=120",
            "AUTOPAUSE_TIMEOUT_INIT=600",
            "AUTOPAUSE_PERIOD=10",
            "AUTOPAUSE_KNOCK_INTERFACE=eth0",
            "EULA=TRUE",
            "VERSION=LATEST",
            "FORGEVERSION=RECOMMENDED",
            "SPONGEBRANCH=STABLE",
            "SPONGEVERSION=",
            "FABRICVERSION=LATEST",
            "LEVEL=world",
            "PVP=true",
            "DIFFICULTY=easy",
            "LEVEL_TYPE=DEFAULT",
            "REPLACE_ENV_VARIABLES=FALSE",
            "ENV_VARIABLE_PREFIX=CFG_"
        ],
        "ExposedPorts": {
            "25565/tcp": {},
            "25575/tcp": {}
        },
        "Healthcheck": {
            "StartPeriod": 60000000000,
            "Test": [
                "CMD-SHELL",
                "/health.sh"
            ]
        },
        "Hostname": "056a42038eac",
        "Image": "itzg/minecraft-server:armv7",
        "Labels": {
            "maintainer": "itzg",
            "org.opencontainers.image.authors": "Geoff Bourne <itzgeoff@gmail.com>",
            "org.opencontainers.image.documentation": "https://github.com/itzg/docker-minecraft-server",
            "org.opencontainers.image.revision": "44769b6001ef54bad89ace246d73efce6e88867e",
            "org.opencontainers.image.source": "https://github.com/itzg/docker-minecraft-server",
            "org.opencontainers.image.version": "multiarch"
        },
        "OnBuild": null,
        "OpenStdin": false,
        "StdinOnce": false,
        "Tty": true,
        "User": "",
        "Volumes": {
            "/data": {}
        },
        "WorkingDir": "/data"
    },
    "Created": "2021-03-18T10:47:35.974505367Z",
    "Driver": "overlay2",
    "ExecIDs": null,
    "GraphDriver": {
        "Data": {
            "LowerDir": "/var/lib/docker/overlay2/b0b22086e1560f52e73ce63afb61ff34ae5853c04fcc78768c90b0022f28889a-init/diff:/var/lib/docker/overlay2/c2573dbc21a772ee323c6c3d80ca9983efa3fa04d2ca7073a60c2ac272e994a5/diff:/var/lib/docker/overlay2/2d2eecdb738531e6e6eac4adf53791ae358c8be11d5c64d617907ae1258d3066/diff:/var/lib/docker/overlay2/a3d79e8b050fa1d749f29f19af98a68376b970aeafd852fcb0cd0e5bd04c36ab/diff:/var/lib/docker/overlay2/081a16112081c7071d183293f5540910e0f0ef39da6a3468f4ef2562fb0fa164/diff:/var/lib/docker/overlay2/2b1fde1614e4ba9ff11414b4feeb4e72eb55675052aa0792ce409a455599467d/diff:/var/lib/docker/overlay2/fffb2088ec87995829942725a68848b7b61cdf8e6ee5976aa20dec2e640b2278/diff:/var/lib/docker/overlay2/2784bc0030b98c36d4654e07f2d87cadfbe6dfef3849332c01fb9344ec9c299e/diff:/var/lib/docker/overlay2/bcc5f6afc58fb3b6ba7037eedf274dad3a9bfd345541610d8d5266ac61fec550/diff:/var/lib/docker/overlay2/f09e6f43369ea75814d20a77201ed0308228bbeed779637fed29e9e1857bd207/diff:/var/lib/docker/overlay2/947ed3109b894c7a6c1e3cd3e66ac5e504d99fbddb1c6ca0417b1091a991ec39/diff:/var/lib/docker/overlay2/15ed1cff73c5a2d5d3c0bf0a03fed19257f29bdef492d4d3ff5fb8c1c1cfbf67/diff:/var/lib/docker/overlay2/89e666205b1aafd24ce46930a3f39e8a7e2de1f370476889f62fdf57c88107e7/diff:/var/lib/docker/overlay2/6ad925c661bd7ae612998a23785815a08f62b08f261a6e0fb794917706392b42/diff:/var/lib/docker/overlay2/c15f6d613ae1000b0af2d001efb6b7e429524b2c6739ca1c40987b0b10f21331/diff:/var/lib/docker/overlay2/fb050bc5a9986e52cf4e3d57f5c24818c71551ed82c083e3fa4e974f43112e75/diff:/var/lib/docker/overlay2/d2637a6878f586cf39ebd24990b9baecbc996a4371e5b0c2da14ba8793f84402/diff:/var/lib/docker/overlay2/e6d6146c0f02a9613686d8983bca7bfcb074b72c3c0af696ee7964ab3e1c5bcd/diff:/var/lib/docker/overlay2/5e09d8fcae218ee121f28f8ae9aedf3ba156576d3231a794b9623d208fab1b8e/diff",
            "MergedDir": "/var/lib/docker/overlay2/b0b22086e1560f52e73ce63afb61ff34ae5853c04fcc78768c90b0022f28889a/merged",
            "UpperDir": "/var/lib/docker/overlay2/b0b22086e1560f52e73ce63afb61ff34ae5853c04fcc78768c90b0022f28889a/diff",
            "WorkDir": "/var/lib/docker/overlay2/b0b22086e1560f52e73ce63afb61ff34ae5853c04fcc78768c90b0022f28889a/work"
        },
        "Name": "overlay2"
    },
    "HostConfig": {
        "AutoRemove": false,
        "Binds": [
            "279ceb0535f64fdf9084955412e4b492cb11e23f60aff56f802cd5a8468ce123:/data"
        ],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceWriteIOps": null,
        "BlkioWeight": 0,
        "BlkioWeightDevice": null,
        "CapAdd": [
            "AUDIT_WRITE",
            "CHOWN",
            "DAC_OVERRIDE",
            "FOWNER",
            "FSETID",
            "KILL",
            "MKNOD",
            "NET_BIND_SERVICE",
            "NET_RAW",
            "SETFCAP",
            "SETGID",
            "SETPCAP",
            "SETUID",
            "SYS_CHROOT"
        ],
        "CapDrop": [
            "AUDIT_CONTROL",
            "BLOCK_SUSPEND",
            "DAC_READ_SEARCH",
            "IPC_LOCK",
            "IPC_OWNER",
            "LEASE",
            "LINUX_IMMUTABLE",
            "MAC_ADMIN",
            "MAC_OVERRIDE",
            "NET_ADMIN",
            "NET_BROADCAST",
            "SYSLOG",
            "SYS_ADMIN",
            "SYS_BOOT",
            "SYS_MODULE",
            "SYS_NICE",
            "SYS_PACCT",
            "SYS_PTRACE",
            "SYS_RAWIO",
            "SYS_RESOURCE",
            "SYS_TIME",
            "SYS_TTY_CONFIG",
            "WAKE_ALARM"
        ],
        "Cgroup": "",
        "CgroupParent": "",
        "CgroupnsMode": "host",
        "ConsoleSize": [
            0,
            0
        ],
        "ContainerIDFile": "",
        "CpuCount": 0,
        "CpuPercent": 0,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpuShares": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "Devices": [],
        "Dns": [],
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": [],
        "GroupAdd": null,
        "IOMaximumBandwidth": 0,
        "IOMaximumIOps": 0,
        "Init": false,
        "IpcMode": "private",
        "Isolation": "",
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "Links": null,
        "LogConfig": {
            "Config": {},
            "Type": "json-file"
        },
        "MaskedPaths": [
            "/proc/asound",
            "/proc/acpi",
            "/proc/kcore",
            "/proc/keys",
            "/proc/latency_stats",
            "/proc/timer_list",
            "/proc/timer_stats",
            "/proc/sched_debug",
            "/proc/scsi",
            "/sys/firmware"
        ],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "NanoCpus": 0,
        "NetworkMode": "bridge",
        "OomKillDisable": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "PidsLimit": null,
        "PortBindings": {
            "25575/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "25575"
                }
            ]
        },
        "Privileged": true,
        "PublishAllPorts": false,
        "ReadonlyPaths": [
            "/proc/bus",
            "/proc/fs",
            "/proc/irq",
            "/proc/sys",
            "/proc/sysrq-trigger"
        ],
        "ReadonlyRootfs": false,
        "RestartPolicy": {
            "MaximumRetryCount": 0,
            "Name": "always"
        },
        "Runtime": "runc",
        "SecurityOpt": [
            "label=disable"
        ],
        "ShmSize": 67108864,
        "UTSMode": "",
        "Ulimits": null,
        "UsernsMode": "",
        "VolumeDriver": "",
        "VolumesFrom": null
    },
    "HostnamePath": "/var/lib/docker/containers/bd1bd3c72a1d999f55f34b54709e25bf50e3de1d58e030a1a37121d73b6bb720/hostname",
    "HostsPath": "/var/lib/docker/containers/bd1bd3c72a1d999f55f34b54709e25bf50e3de1d58e030a1a37121d73b6bb720/hosts",
    "Id": "bd1bd3c72a1d999f55f34b54709e25bf50e3de1d58e030a1a37121d73b6bb720",
    "Image": "sha256:88b701db61ed353cf8f4f6739d86419c1d736f36dfd31c87e01d6d3c0c861975",
    "LogPath": "/var/lib/docker/containers/bd1bd3c72a1d999f55f34b54709e25bf50e3de1d58e030a1a37121d73b6bb720/bd1bd3c72a1d999f55f34b54709e25bf50e3de1d58e030a1a37121d73b6bb720-json.log",
    "MountLabel": "",
    "Mounts": [
        {
            "Destination": "/data",
            "Driver": "local",
            "Mode": "z",
            "Name": "279ceb0535f64fdf9084955412e4b492cb11e23f60aff56f802cd5a8468ce123",
            "Propagation": "",
            "RW": true,
            "Source": "/var/lib/docker/volumes/279ceb0535f64fdf9084955412e4b492cb11e23f60aff56f802cd5a8468ce123/_data",
            "Type": "volume"
        }
    ],
    "Name": "/minecraft33",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "26d4baaf7a799824986212bcf3e099206e9d7b74f4967fe16117bd0c3a414e6d",
        "Gateway": "172.17.0.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.4",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:04",
        "Networks": {
            "bridge": {
                "Aliases": null,
                "DriverOpts": null,
                "EndpointID": "26d4baaf7a799824986212bcf3e099206e9d7b74f4967fe16117bd0c3a414e6d",
                "Gateway": "172.17.0.1",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "IPAMConfig": {},
                "IPAddress": "172.17.0.4",
                "IPPrefixLen": 16,
                "IPv6Gateway": "",
                "Links": null,
                "MacAddress": "02:42:ac:11:00:04",
                "NetworkID": "d37222552dfabacdf6d930d5d1d59e25d345223e83eafc387dfb6fcef2ff52f8"
            }
        },
        "Ports": {
            "25565/tcp": null,
            "25575/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "25575"
                }
            ]
        },
        "SandboxID": "796de7346fdb5447b221d6e5ffaf553956d63470235f2ec6ec75ed3c39790560",
        "SandboxKey": "/var/run/docker/netns/796de7346fdb",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "Path": "/start",
    "Platform": "linux",
    "Portainer": {
        "ResourceControl": {
            "Id": 17,
            "ResourceId": "bd1bd3c72a1d999f55f34b54709e25bf50e3de1d58e030a1a37121d73b6bb720",
            "SubResourceIds": [],
            "Type": 1,
            "UserAccesses": [],
            "TeamAccesses": [],
            "Public": false,
            "AdministratorsOnly": true,
            "System": false
        }
    },
    "ProcessLabel": "",
    "ResolvConfPath": "/var/lib/docker/containers/bd1bd3c72a1d999f55f34b54709e25bf50e3de1d58e030a1a37121d73b6bb720/resolv.conf",
    "RestartCount": 0,
    "State": {
        "Dead": false,
        "Error": "",
        "ExitCode": 0,
        "FinishedAt": "0001-01-01T00:00:00Z",
        "Health": {
            "FailingStreak": 12,
            "Log": [
                {
                    "End": "2021-03-18T18:52:10.695932444+08:00",
                    "ExitCode": 127,
                    "Output": "/bin/sh: 1: /health.sh: not found\n",
                    "Start": "2021-03-18T18:52:10.498239583+08:00"
                },
                {
                    "End": "2021-03-18T18:52:40.922436542+08:00",
                    "ExitCode": 127,
                    "Output": "/bin/sh: 1: /health.sh: not found\n",
                    "Start": "2021-03-18T18:52:40.711680003+08:00"
                },
                {
                    "End": "2021-03-18T18:53:11.194624784+08:00",
                    "ExitCode": 127,
                    "Output": "/bin/sh: 1: /health.sh: not found\n",
                    "Start": "2021-03-18T18:53:10.939613838+08:00"
                },
                {
                    "End": "2021-03-18T18:53:41.444758289+08:00",
                    "ExitCode": 127,
                    "Output": "/bin/sh: 1: /health.sh: not found\n",
                    "Start": "2021-03-18T18:53:41.209389994+08:00"
                },
                {
                    "End": "2021-03-18T18:54:11.69369694+08:00",
                    "ExitCode": 127,
                    "Output": "/bin/sh: 1: /health.sh: not found\n",
                    "Start": "2021-03-18T18:54:11.459873076+08:00"
                }
            ],
            "Status": "unhealthy"
        },
        "OOMKilled": false,
        "Paused": false,
        "Pid": 16190,
        "Restarting": false,
        "Running": true,
        "StartedAt": "2021-03-18T10:47:38.011839838Z",
        "Status": "running"
    }
}

It seems the server auto-closes the connection, I have checked the Minecraft version of the client is the same as the server (1.16.5).

How can I solve this problem?
Thanks!

**Comment by itzg** [comment]
I really need to delete that image tag since it's old. Try the `multiarch` tag and see if that acts better.

**Comment by sd016808** [comment]
Actually, I have tested the multiarch tag. The output log get the almost the same result.

[12:59:22] [Worker-Main-5/INFO]: Preparing spawn area: 28%,
[12:59:22] [Worker-Main-4/INFO]: Preparing spawn area: 28%,
[12:59:23] [Worker-Main-4/INFO]: Preparing spawn area: 28%,
[12:59:23] [Worker-Main-5/INFO]: Preparing spawn area: 36%,
[12:59:24] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:24] [Worker-Main-5/INFO]: Preparing spawn area: 36%,
[12:59:25] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:25] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:26] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:26] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:27] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:27] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:28] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:28] [Worker-Main-4/INFO]: Preparing spawn area: 36%,
[12:59:29] [Worker-Main-5/INFO]: Preparing spawn area: 44%,
[12:59:30] [Worker-Main-5/INFO]: Preparing spawn area: 44%,
[12:59:32] [Worker-Main-5/INFO]: Preparing spawn area: 44%,
[12:59:32] [Worker-Main-5/INFO]: Preparing spawn area: 44%,
[12:59:32] [Worker-Main-5/INFO]: Preparing spawn area: 44%,
[12:59:32] [Worker-Main-5/INFO]: Preparing spawn area: 44%,
[12:59:32] [Worker-Main-6/INFO]: Preparing spawn area: 48%,
[12:59:32] [Worker-Main-4/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-5/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-5/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-4/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-4/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-4/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-4/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-4/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-4/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-5/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-5/INFO]: Preparing spawn area: 49%,
[12:59:38] [Worker-Main-5/INFO]: Preparing spawn area: 49%,
[12:59:39] [Worker-Main-4/INFO]: Preparing spawn area: 59%,
[12:59:39] [Worker-Main-5/INFO]: Preparing spawn area: 59%,
[12:59:39] [Worker-Main-6/INFO]: Preparing spawn area: 61%,
[12:59:40] [Worker-Main-5/INFO]: Preparing spawn area: 61%,
[12:59:40] [Worker-Main-6/INFO]: Preparing spawn area: 62%,
[12:59:41] [Worker-Main-6/INFO]: Preparing spawn area: 64%,
[12:59:41] [Worker-Main-6/INFO]: Preparing spawn area: 64%,
[12:59:42] [Worker-Main-5/INFO]: Preparing spawn area: 65%,
[12:59:42] [Worker-Main-5/INFO]: Preparing spawn area: 66%,
[12:59:43] [Worker-Main-4/INFO]: Preparing spawn area: 68%,
[12:59:43] [Worker-Main-6/INFO]: Preparing spawn area: 68%,
[12:59:46] [Worker-Main-6/INFO]: Preparing spawn area: 68%,
[12:59:46] [Worker-Main-6/INFO]: Preparing spawn area: 68%,
[12:59:46] [Worker-Main-5/INFO]: Preparing spawn area: 68%,
[12:59:46] [Worker-Main-6/INFO]: Preparing spawn area: 68%,
[12:59:46] [Worker-Main-5/INFO]: Preparing spawn area: 68%,
[12:59:53] [Worker-Main-4/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-4/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-4/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-5/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-5/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-5/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-5/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-5/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-5/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-4/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-4/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-4/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-4/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-4/INFO]: Preparing spawn area: 73%,
[12:59:53] [Worker-Main-5/INFO]: Preparing spawn area: 81%,
[12:59:54] [Worker-Main-5/INFO]: Preparing spawn area: 85%,
[12:59:54] [Worker-Main-4/INFO]: Preparing spawn area: 85%,
[12:59:55] [Worker-Main-5/INFO]: Preparing spawn area: 87%,
[12:59:55] [Worker-Main-6/INFO]: Preparing spawn area: 88%,
[12:59:56] [Worker-Main-5/INFO]: Preparing spawn area: 89%,
[12:59:56] [Worker-Main-6/INFO]: Preparing spawn area: 90%,
[12:59:57] [Worker-Main-6/INFO]: Preparing spawn area: 91%,
[12:59:57] [Worker-Main-5/INFO]: Preparing spawn area: 93%,
[12:59:58] [Worker-Main-6/INFO]: Preparing spawn area: 94%,
[12:59:58] [Worker-Main-6/INFO]: Preparing spawn area: 94%,
[12:59:59] [Worker-Main-5/INFO]: Preparing spawn area: 96%,
[12:59:59] [Worker-Main-6/INFO]: Preparing spawn area: 97%,
[13:00:00] [Worker-Main-4/INFO]: Preparing spawn area: 98%,
[13:00:00] [Server thread/INFO]: Time elapsed: 83980 ms,
[13:00:00] [Server thread/INFO]: Done (119.663s)! For help, type "help",
[13:00:00] [Server thread/INFO]: Starting remote control listener,
[13:00:00] [Server thread/INFO]: Thread RCON Listener started,
[13:00:00] [Server thread/INFO]: RCON running on 0.0.0.0:25575,
[13:00:01] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started,
[13:00:01] [RCON Client /192.168.50.163 #2/INFO]: Thread RCON Client /192.168.50.163 shutting down,
[13:00:05] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 4949ms or 98 ticks behind,
[13:00:19] [RCON Client /192.168.50.163 #3/INFO]: Thread RCON Client /192.168.50.163 shutting down,
[13:00:19] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started,
[13:00:23] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started,
[13:00:23] [RCON Client /192.168.50.163 #4/INFO]: Thread RCON Client /192.168.50.163 shutting down,
[13:00:23] [RCON Client /192.168.50.163 #5/INFO]: Thread RCON Client /192.168.50.163 shutting down,
[13:00:23] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started,
[13:00:31] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 10623ms or 212 ticks behind,
[13:00:31] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started,
[13:00:31] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started,
[13:00:31] [RCON Client /192.168.50.163 #6/INFO]: Thread RCON Client /192.168.50.163 shutting down,
[13:00:31] [RCON Client /192.168.50.163 #7/INFO]: Thread RCON Client /192.168.50.163 shutting down,
[13:00:31] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started,
[13:00:31] [RCON Client /192.168.50.163 #8/INFO]: Thread RCON Client /192.168.50.163 shutting down,
[13:00:32] [RCON Listener #1/INFO]: Thread RCON Client /192.168.50.163 started,
[13:00:32] [RCON Client /192.168.50.163 #9/INFO]: Thread RCON Client /192.168.50.163 shutting down,

**Comment by sd016808** [comment]
Sorry, I found the problem. It's my fault. I change the PORT CONFIGURATION 
From 
0.0.0.0:25575  25575/tcp
To
0.0.0.0:25565 25565/tcp
in Portainer. 

Then, everything works fine!  Thanks!

![image](https://user-images.githubusercontent.com/9477727/111635952-fd0a8700-8832-11eb-816b-d551e8be1a64.png)
