### ISSUE TITLE
Use Spiget to automatically download a given list of plugins

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#808]
[Spiget](https://spiget.org/) is an API for Spigot which can be used to gather resources programmatically.
This could be implemented in some way to automatically gather a given list of plugins which further reduces the amount of state you need to manage.

**Comment by itzg** [comment]
Awesome. Just making a note that this seems to be the specific endpoint of interest

https://spiget.org/documentation/#!/resources/get_resources_resource_download

**Comment by itzg** [comment]
It's ready to test out

https://github.com/itzg/docker-minecraft-server#auto-downloading-spigotmcbukkitpapermc-plugins

**Comment by michaelnguyenm** [comment]
I tried this new option out and it does work, at least for the resources hosted by Spigot. Maybe there should be a comment in the README about resources that are hosted externally as those return a 404 for the Spiget API and that the user will either have to use the MOD/MODPACK env variables or copy the files to the plugins folder? It took me only a brief second to figure out that was the issue though.

For example, I was trying to use 1997 which is protolib:
https://www.spigotmc.org/resources/protocollib.1997/
But the download button shows that it's an external file so Spiget can't retrieve it.

**Comment by ChipWolf** [comment]
I believe the API has some kind of redirect for externally hosted files, might be worth adding some handling for that if it's possible

**Comment by itzg** [comment]
> I believe the API has some kind of redirect for externally hosted files, might be worth adding some handling for that if it's possible

Can you elaborate? It's already using curl's `-L` to follow redirects, which is needed to resolve the first hop to `https://apple.api.spiget.org/v2/resources/{resource}/download`

**Comment by michaelnguyenm** [comment]
When I looked at the documentation for `/resources/{resource}/download` it didn't appear to me that there's an option to get a redirect. As a result something like [`/resources/1997/download`](https://apple.api.spiget.org/v2/resources/1997/download) just returns `{"error": "file not found"}` with no redirect there or anything to help resolve this.

However, using `/resources/{resource}`, it's possible to get more information about the URL that users on spigotmc.org use to get the externally hosted resource. [`/resources/1997`](https://api.spiget.org/v2/resources/1997) has a `file.url` property with the path, `resources/protocollib.1997/download?version=383725`, which might help with getting those files? Not too sure on this end.

**Comment by ChipWolf** [comment]
`https://www.spigotmc.org/resources/protocollib.1997/download?version=383725`
@itzg

**Comment by itzg** [comment]
> `https://www.spigotmc.org/resources/protocollib.1997/download?version=383725`

Ah, I was trying to line up with the APIs `/resources`. 

...however, when I curl that it seems to be disallowing non-humans since it comes back with a 503:

```
curl -v 'https://www.spigotmc.org/resources/protocollib.1997/download?version=383725'

< HTTP/2 503 
< date: Tue, 30 Mar 2021 02:34:39 GMT
< content-type: text/html; charset=UTF-8
< x-frame-options: SAMEORIGIN
< set-cookie: __cfduid=ddd67f9e08720f609db3a01a6fdb5c66b1617071679; expires=Thu, 29-Apr-21 02:34:39 GMT; path=/; domain=.spigotmc.org; HttpOnly; SameSite=Lax; Secure
< cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< expires: Thu, 01 Jan 1970 00:00:01 GMT
< cf-request-id: 092294be7000002f010896e000000001
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"max_age":604800,"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=7MqqbMsOq%2FQAelTyx4bT%2FbMNDhXrdJzNKNDKUnk%2Bmg7Mg7p74FmZ%2F%2FedYpnVEMznHl7zrBZdwAnAijzqCVO9du7L1%2BqUmNyW6zarmpv91btR"}]}
< nel: {"max_age":604800,"report_to":"cf-nel"}
< server: cloudflare
< cf-ray: 637df0aa4cd82f01-DFW
< alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
< 
<!DOCTYPE HTML>
<html lang="en-US">

...and landing page HTML
```

**Comment by ChipWolf** [comment]
Oh yeah, that's Cloudflare kicking you back. There are [ways around that](https://github.com/SpiGetOrg/spiget-puppeteer-client), but they're mostly ugly and [questionable](https://github.com/VeNoMouS/cloudscraper).

I don't think solving that issue is in scope for this project, it may need some collaboration between SpigotMC (@md-5) & SpiGet (@InventivetalentDev)

I think we effectively need a package manager for Bukkit plugins to have a proper solution, but that's obviously easier said than done. Until then, this solution works perfectly for assets hosted on Spigot!

**Comment by InventivetalentDev** [comment]
I can look into following the external download URLs to the actual source (away from the spigotmc.org domain behind CF) so that it's more accessible for clients of spiget.  
One thing I've been meaning to do is supporting github releases to download resources from, but supporting any other custom download pages would get pretty messy.

**Comment by itzg** [comment]
> I can look into following the external download URLs to the actual source (away from the spigotmc.org domain behind CF) so that it's more accessible for clients of spiget.
> One thing I've been meaning to do is supporting github releases to download resources from, but supporting any other custom download pages would get pretty messy.

Thanks @InventivetalentDev and thanks for an awesome API to work with. Feel free to ping me with an issue if I need to adjust to any API changes.

Otherwise, looks like I'm good to close out this first round.

**Comment by InventivetalentDev** [comment]
@itzg @ChipWolf the resolved direct links to external downloads are now available as `file.externalUrl` for any new resource updates :)

**Comment by Nordiii** [comment]
Does this work with a paper server and on multiarch?
Want to run this in a docker container on my pi, but sadly the plugins wont download and the console does not say anything about trying to download any plugins.

My docker-compose looks like this:
```
version: "3"

services:
  mc:
    image: itzg/minecraft-server:multiarch-latest
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "4G"
      SPIGET_RESOURCES: 4657,45288,7939,59773,44462,28140
      DEBUG: "TRUE"
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft:/data

```
