### ISSUE TITLE
Spiget not yet available on multiarch

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#821]
Does this work with a paper server and on multiarch?
Want to run this in a docker container on my pi, but sadly the plugins wont download and the console does not say anything about trying to download any plugins.

My docker-compose looks like this:
```
version: "3"

services:
  mc:
    image: itzg/minecraft-server:multiarch-latest
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "4G"
      SPIGET_RESOURCES: 4657,45288,7939,59773,44462,28140
      DEBUG: "TRUE"
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft:/data

```

_Originally posted by @Nordiii in https://github.com/itzg/docker-minecraft-server/issues/808#issuecomment-811992736_

**Comment by itzg** [comment]
@Nordiii , I'm sorry, I forgot to get this feature merged to other branches / image tags. I'll take care of that and then it will work for Paper with all image tags.

**Comment by itzg** [comment]
@Nordiii the spiget feature is now merged to all of the image tags, so it should now work in `itzg/minecraft-server:multiarch-latest`

**Comment by Nordiii** [comment]
Works great for me on multiarch, thanks a lot for the quick update!
