### ISSUE TITLE
Support spiget's file.externalUrl field

### ISSUE THREAD

**Issue by itzg** [itzg/docker-minecraft-server#822]
@itzg @ChipWolf the resolved direct links to external downloads are now available as `file.externalUrl` for any new resource updates :)

_Originally posted by @InventivetalentDev in https://github.com/itzg/docker-minecraft-server/issues/808#issuecomment-811307615_

**Comment by itzg** [comment]
@InventivetalentDev I came up with a couple of questions while starting to think of implementation:

1. Do you know of any new resource updates yet that now have `file.externalUrl` populated?
2. Would it be possible for the `/resources/{resource}/download` to abstract that alternative location even if it's just a 302 over to that?

**Comment by InventivetalentDev** [comment]
@itzg 
1.
``` 
17700 9651 10693 22981 20957 17599 18494 2124 12038 5341 274 42076 42228 43487 47894 49976 51398 54612 58905 64116 64982 65417 65706 67351 69929 70895 71234 74642 75409 75839 75870 75891 75975 76474 77456 77943 78445 79466 81115 81215 81914 82678 83111 83813 83917 84859 85151 85250 85733 86539 86901 87489 87955 89075 89308 89346 89568 89775 90079 90192 90252 90283 90161 90387 90628 90682 90714 90720 90746 90763 90767 90772 90780 90800 90806 90829 90834 87196
```
2. I'll have to think about that. Technically clients are supposed to check the `external` field of a resource before attempting to download, but I'm a bit worried about changing that endpoint being able to redirect outside of spiget. I think having that single route for downloads would be good though.

**Comment by itzg** [comment]
Thanks and I'm good with whatever is feasible or not for (2). 

If keeping the assumption

> clients are supposed to check the external field of a resource before attempting to download

then I'd recommend adding that to [the download API docs](https://spiget.org/documentation/#!/resources/get_resources_resource_download).

**Comment by InventivetalentDev** [comment]
[Changed the download route](https://github.com/SpiGetOrg/api.spiget.org/commit/20dd109e100976996c2aaa8d3b780247635ac19c) to redirect to external stuff & added some notes to the [docs](https://rest.wiki/?https://raw.githubusercontent.com/SpiGetOrg/Documentation/master/swagger.yml#operations-resources-get_resources__resource__download)

**Comment by itzg** [comment]
Tested with `-e SPIGET_RESOURCES=1997,17700`
