### ISSUE TITLE
Spiget downloads outdated files.

### ISSUE THREAD

**Issue by kevintran-git** [itzg/docker-minecraft-server#824]
On testing I see that spiget is downloading an outdated version of a plugin.

On the start-spiget file, I see
```
getResourceFromSpiget() {
  resource=${1?}

  log "Downloading resource ${resource} ..."

  tmpfile="/tmp/${resource}.zip"
  url="https://api.spiget.org/v2/resources/${resource}/download"
  if ! curl -o "${tmpfile}" -fsSL -H "User-Agent: itzg/minecraft-server" "${extraCurlArgs[@]}" "${url}"; then

```

and if you replace the url with `https://api.spiget.org/v2/resources/${resource}/versions/latest/download` 
it should download the latest version.

**Comment by itzg** [comment]
That's an odd default behavior. Can you provide an example plugin ID where you saw that and I'll open an issue with them?

**Comment by kevintran-git** [comment]
I was trying to download https://api.spiget.org/v2/resources/60383/download , however I have contacted their developers and it does not seem to be a problem on their end. This link will download version 3.5.4, while https://api.spiget.org/v2/resources/60383/versions/latest/download reliably downloads the latest version (3.12.1) even as it was updated today.

**Comment by itzg** [comment]
> I have contacted their developers

Do you mean you contact the Spiget API developers or AngelChest developers?

**Comment by itzg** [comment]
FYI I just now tried `curl -fsSL -o 60383.jar https://api.spiget.org/v2/resources/60383/download` and looking at the `plugin.yml` within that jar it is `3.12.1`. It's not the newest, `3.12.2` but then it was only updated 13 minutes ago

![image](https://user-images.githubusercontent.com/988985/114110376-fc4a9b00-989c-11eb-8b0a-f39268627816.png)

I don't have enough confirmation yet to report an issue at [Spiget's repo](https://github.com/SpiGetOrg/api.spiget.org/issues). If you continue to see problems with their primary `/download` URL then please report an issue there and link it here.

**Comment by kevintran-git** [comment]
> > I have contacted their developers
> 
> Do you mean you contacted the Spiget API developers or AngelChest developers?

AngelChest developers, they say they update their latest versions on Spigot and I don't know what else they can do on their end

**Comment by itzg** [comment]
> AngelChest developers, they say they update their latest versions on Spigot and I don't know what else they can do on their end

Agreed, it's not an AngelChest issue and it's not issue with this Docker image. If anything, it's an issue in the Spiget API service -- **note** that Spiget with an "e" and not Spigot with an "o":

```
itzg/minecraft-server image -> Spiget API -> SpigotMC website -> AngelChest
                               ^^^^^^^^^^
                               Problem seems to be here from your testing
```

**Comment by kevintran-git** [comment]
Yeah, I tried today and it appears to be functioning correctly. If you have not changed anything it is probably on Spiget API's end.

Another thing, would it be possible to use `SPIGET_RESOURCES` with other distributions of server jars? I'm currently using Paper, and `SPIGET_RESOURCES` works, however I think that the image would not  download resources if I had Purpur (which should run as a drop-in replacement of Spigot/Paper) as it is a fork.

**Comment by itzg** [comment]
The latest image now supports Spiget with Purpur (and Tuinity and Airplane).
