### ISSUE TITLE
Support Spiget resource versions

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#825]
I'm thinking the format `RESOURCE_ID:VERSION_ID` will work without much change to the existing feature.
The version ID should assume latest _(filtering by the Minecraft version?)_ if not specified.

```
-e SPIGET_RESOURCES=9089:367353,34315,28140:388301
```

Another good feature would be printing a summary of plugins/versions on start & if the specified version is not up-to-date.
I would perhaps consider adding another feature to check the hash of the existing plugins to verify if they're already downloaded (#978?)

**Comment by itzg** [comment]
Phew, that's at least four enhancements you noted there 😃 All good stuff and contributions are welcome.

**Comment by DanielRamp** [comment]
the first enhancement (downloading a specified version of a plugin) seems quite doable, I think.
We might just use the API Endpoint "Resource Version Download" instead of "Resource Download"

The only thing about this enhancment which would be difficult for me is how to get the ``:version`` from input: https://github.com/itzg/docker-minecraft-server/blob/37b81aa0be2c7429979796b83263ed637d68e712/start-spiget#L62

**Comment by itzg** [comment]
> The only thing about this enhancment which would be difficult for me is how to get the `:version` from input:

@DanielRamp what I did was borrow a technique [from here](https://linuxhandbook.com/bash-split-string/), so the same could be done in `getResourceFromSpiget` to split the individual resource string by colon.

**Comment by ChipWolf** [comment]
For the anti-IFS side of the table:
```bash
SPIGET_RESOURCES=9089:367353,34315,28140:388301
res=${SPIGET_RESOURCES//[^,][0-9]}
for n in $(seq 1 ${#res}); do
  for i in $(echo $TEST | cut -d, -f$n); do
    echo "plugin $(echo $i | cut -d: -f1) version $(echo $i | cut -d: -f2)"
  done
done
```

**Comment by itzg** [comment]
```
res=${SPIGET_RESOURCES//[^,]}
```
produces `,,`

and fixing the character class inversion
```
res=${SPIGET_RESOURCES//[,]}
```
produces `9089:3673533431528140:388301`

Maybe you meant
```
res=${SPIGET_RESOURCES//,/ }
```

but `${#res}` is `30` since it didn't get parsed as an array of 3 elements.

So...the counter-proposal seems to be error prone. It also uses several sub-shells and sub-processes, which I like to minimize.

**Comment by ChipWolf** [comment]
@itzg we'll have to re-open this one manually if that PR is merged

**Comment by itzg** [comment]
> @itzg we'll have to re-open this one manually if that PR is merged

Because of the `fixes #825` phrasing? Github is not reporting that as an auto-close phrase so far. But yeah, you or I can re-open this issue if github auto-closes.

**Comment by ChipWolf** [comment]
> 
> 
> > @itzg we'll have to re-open this one manually if that PR is merged
> 
> Because of the `fixes #825` phrasing? Github is not reporting that as an auto-close phrase so far. But yeah, you or I can re-open this issue if github auto-closes.

`DanielRamp linked a pull request that will close this issue 2 days ago `

**Comment by DanielRamp** [comment]
I just can't get the [double string splitting](https://github.com/itzg/docker-minecraft-server/blob/b46e57c24e28ea9eab1c02aeceb1bc6dcbdf2d95/start-spiget#L119-L129) working.
Maybe someone could help, so the first part of this issue could be solved.

```
[init] Getting plugins via Spiget
[init] Downloading resource 9089 ...
/start-spiget: line 93: $2: cannot assign in this way
```
with ``SPIGET_RESOURCES=9089:367353,34315,28140:388301``

**Comment by itzg** [comment]
@DanielRamp is that comment supposed to go in the PR or are you saying there's something broken in the main branches?

**Comment by DanielRamp** [comment]
It's about the pr..

**Comment by itzg** [comment]
This feature is blocked ultimately by SpigotMC's redirection of version specific resources via CloudFlare browser detection. For example, version 367353 of 9089 (EssentialsX), is ultimately directed to the URL `https://www.spigotmc.org/resources/9089/download?version=367353`; however, there are normally various cookies in the request that CloudFlare validates to allow access.

**Comment by ChipWolf** [comment]
> 
> 
> This feature is blocked ultimately by SpigotMC's redirection of version specific resources via CloudFlare browser detection. For example, version 367353 of 9089 (EssentialsX), is ultimately directed to the URL `https://www.spigotmc.org/resources/9089/download?version=367353`; however, there are normally various cookies in the request that CloudFlare validates to allow access.

@InventivetalentDev

**Comment by itzg** [comment]
Got great clarification from @InventivetalentDev on the PR, but I'm afraid still that this feature can't be implemented until SpigotMC happens to change file access. I don't see them changing that any time soon since bandwidth is expensive.
