### ISSUE TITLE
/stop command bricks the server

### ISSUE THREAD

**Issue by shaunmoini** [itzg/docker-minecraft-server#828]
I can't start the server back up after using the /stop command. Container still running but server is inaccessible.

**Comment by itzg** [comment]
I have never heard of this happening before. Please provide more details like logs and how you created container. 

In any case, I'm not sure how this is an issue with the docker image and should be reported to Mojang.

**Comment by shaunmoini** [comment]
Seems all I had to do was physically restart the machine hosting the container. ¯\_(ツ)_/¯
