### ISSUE TITLE
EXEC_DIRECTLY doesn't work with java15-openj9

### ISSUE THREAD

**Issue by frambinni** [itzg/docker-minecraft-server#830]
The `EXEC_DIRECTLY: "true"` in docker-compose doesn't add the color to the console when using the `java15-openj9` tag. It does work with the `multiarch-latest` tag though.

**Comment by itzg** [comment]
Can you provide the compose file that didn't work?

**Comment by frambinni** [comment]
```yaml
version: '3.8'
services:
  mc:
    image: itzg/minecraft-server:java15-openj9
    environment:
      EULA: "true"
      TYPE: PAPER
      VERSION: 1.16.5
      PAPERBUILD: 590
      # "CONSOLE: false" needed for Paper versions before 1.14
      CONSOLE: "false"
      # If "EXEC_DIRECTLY: true"; "docker stop" will not stop the server gracefully!
      # Use "docker exec <container> rcon-cli stop" instead.
      EXEC_DIRECTLY: "true"
      MEMORY: 2G
      TZ: "America/Edmonton"
    ports:
      - 25565:25565
      - 8192:8192
    volumes:
      - ./data:/data
    tty: true
    stdin_open: true
    restart: always
volumes:
  data:

**Comment by itzg** [comment]
Only the WARN logs are colored (yellow), so I was only to catch one example using your compose file:

![image](https://user-images.githubusercontent.com/988985/114439859-1206db80-9b8f-11eb-96c0-61d6bb8e32db.png)

Double check you have pulled the latest copy of that image using `docker-compose pull`.

**Comment by frambinni** [comment]
Oh right, I forgot to pull the latest image! Sorry, I was 😴 lol

I can confirm that after pulling the latest image of `itzg/minecraft-server:java15-openj9` the console displays colors accordingly.
