### ISSUE TITLE
Container won't start on multiarch : curl timeout

### ISSUE THREAD

**Issue by ChRiiS** [itzg/docker-minecraft-server#836]
Hi,
I'm on a Raspberry 4 on a fresh raspbian install and i tried to run the image with :  
`docker run -d -it --name mc -p 25565:25565 -e EULA=TRUE itzg/minecraft-server:multiarch`
Everything went fine :
```Unable to find image 'itzg/minecraft-server:multiarch' locally
multiarch: Pulling from itzg/minecraft-server
2b310eb62794: Pull complete
051c3059c680: Pull complete
0927a80501a3: Pull complete
d8525cbef9c7: Pull complete
093cdfa5d472: Pull complete
696575d13d5b: Pull complete
0e0f8f0d9900: Pull complete
6b5fa31bbe8c: Pull complete
8df47876637a: Pull complete
06b546aed1d4: Pull complete
15b7bb91fec0: Pull complete
eb2f250bb152: Pull complete
5e92129f88ec: Pull complete
d78356d0a139: Pull complete
a13c1dd79ab6: Pull complete
477a2a993e4e: Pull complete
8a1820e6a07c: Pull complete
0e20cb8cbec6: Pull complete
ee613d82a9ad: Pull complete
5a01c5ebb2c6: Pull complete
a65c2688e93a: Pull complete
cf02dac40ee8: Pull complete
436507de4616: Pull complete
7f54c93bb55c: Pull complete
Digest: sha256:b3f3db84c9dfc550bbba77415c11281bd22b4b86f641647494ef5a1a2e62a122
Status: Downloaded newer image for itzg/minecraft-server:multiarch
d9bcc962275855a97b1a50ac379c532f6ae829343e20c0c1132fbbd16f282566
```
But the container won't start... I have no output, i can't find the container
The only thing i could see is that curl time out : 
```
docker logs -f mc
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Apr 18  2021 /data'
curl: (28) Timeout was reached
```
Did i missed something ?

**Comment by itzg** [comment]
Seems to be duplicate of https://github.com/itzg/docker-minecraft-server/issues/755

**Comment by ChRiiS** [comment]
Yeah it's seems to be the same thing, didn't find it sorry.
But i can't update (ou downgrade) libseccomp on this Raspberry unfortunatly, i tried to take a look at the link you gave https://docs.docker.com/engine/security/seccomp/ but i don't really find there what should i do now.. 
I'll keep trying to understand, thank you !

**Comment by itzg** [comment]
It's quite strange the issue exists with the baseline distro and that package update is awkward too.
