### ISSUE TITLE
A problem installing the server was detected, server install cannot continue

### ISSUE THREAD

**Issue by SkyBlade1978** [itzg/docker-minecraft-server#837]
Hi,

Thanks for creating this, however I am having an issue in trying to get it to work with forge-1.10.2-12.18.3.2185-installer.jar

I tried both letting it download the installer and providing it, however when it tries to install it creates a log saying;

Installing server to current directory
A problem installing the server was detected, server install cannot continue

It creates the eula.txt file, the libraries directory (empty) and the mods folder (also empty).

I use the command;

docker run -d -v mcvol:/data -e TYPE=FORGE -p 25565:25565 -e EULA=TRUE -e VERSION=1.10.2 -e FORGE_INSTALLER=forge-1.10.2-12.18.3.2185-installer.jar --name mc itzg/minecraft-server:java8

I already created the volume mcvol

**Comment by itzg** [comment]
Those logs come from the Forge installer itself, so it seems to be beyond my control.

Even tried downloading `http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2185/forge-1.10.2-12.18.3.2185-installer.jar` outside of Docker and got the same failure:

```
curl -O -fsSL http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.10.2-12.18.3.2185/forge-1.10.2-12.18.3.2185-installer.jar
java -jar forge-1.10.2-12.18.3.2185-installer.jar --installServer
Setting up logger: /Users/geoff.bourne/Downloads/forge-1.10.2-12.18.3.2185-installer.jar.log
Installing server to current directory
A problem installing the server was detected, server install cannot continue
```

**Comment by SkyBlade1978** [comment]
Thanks for the reply.

I am wondering, is there a way of bypassing the install, as what I am trying to achieve is to move an existing, working installation complete with world and mods inside of the docker container, perhaps I can drop the existing files into the volume?

**Comment by SkyBlade1978** [comment]
Weirdly, I just cleaned the volume and tried again (letting it download the installer) and it worked, I don't see what is different from yesterday, maybe a maven repo was down..
