### ISSUE TITLE
Please use the server modpack.

### ISSUE THREAD

**Issue by Trqhxrd** [itzg/docker-minecraft-server#838]
Hey itzg! 
I tried to create an RL-Craft Server with this docker image.
I set "CF_SERVER_MOD" to https://media.forgecdn.net/files/2935/323/RLCraft+Server+Pack+1.12.2+-+Beta+v2.8.2.zip but it said, "Please be sure to use the server pack." What do i do? 
[The Log file](https://github.com/itzg/docker-minecraft-server/files/6345893/_mc-rlcraft_logs.txt)

**Comment by itzg** [comment]
That modpack seems to be "broken" for servers. There's no server start script such as https://github.com/AllTheMods/Server-Scripts/blob/master/ServerStart.sh

**Comment by ichbestimmtnicht** [comment]
I have the same issure with the latest (4.4.0) LinW Modpack
Clientfiles: https://www.curseforge.com/minecraft/modpacks/life-in-new-woods
Serverfiles https://mod-com.eu/linw/
and it works locally with `java -Xmx10G -Xms1G -jar linw.jar -nogui`

**Comment by itzg** [comment]
@ichbestimmtnicht please open an enhancement request. The current startup scripts has no idea about invoking some that specific.

**Comment by itzg** [comment]
@Trqhxrd please report an issue with RLCraft. I just now re-read their instructions and this statement is wrong

![image](https://user-images.githubusercontent.com/988985/116791831-86dc7f80-aa82-11eb-8be6-17c5af6bd48f.png)

There is no forge server jar nor installer included in the server modpack zip file.

**Comment by itzg** [comment]
...as a workaround, you can always use `-e TYPE=FORGE -e VERSION=1.12.2` and prepare the RLCraft content in the attached `/data` path.

**Comment by Trqhxrd** [comment]
> ...as a workaround, you can always use `-e TYPE=FORGE -e VERSION=1.12.2` and prepare the RLCraft content in the attached `/data` path.

Thank you! I think I will do that!
