### ISSUE TITLE
Pterodactyl Support?

### ISSUE THREAD

**Issue by red0fireus** [itzg/docker-minecraft-server#839]
I haven't seen anything mentioned yet about Pterodactyl. 

I was wondering if you could use this with a Pterodactyl panel? If so, how would I go about defining that in the configuration.

Thank you!

**Comment by red0fireus** [comment]
I have tried: itzg/minecraft-server:java11

Error: Error response from daemon: manifest for itzg/minecraft-server:java11 not found: manifest unknown: manifest unknown

**Comment by red0fireus** [comment]
I wanted to set it up with purpur

**Comment by itzg** [comment]
> I have tried: itzg/minecraft-server:java11
> 
> 
> 
> Error: Error response from daemon: manifest for itzg/minecraft-server:java11 not found: manifest unknown: manifest unknown

Yeah, that tag doesn't exist. Just use `latest` or `multiarch` if you want Java 11. 

> I wanted to set it up with purpur 
> 
> This seemed to sorta work but I'm unsure of how I would accept the eula. itzg/minecraft-server:multiarch 
> 
>  
> 
> This doesn't seem to work in the pterodactyl panel.. (-e eula=true)

I have never heard of pterodactyl other than the dinosaur. `-e` refers to setting environment variables on the container. You may need to contact that software vendor for help with Docker configuration.

**Comment by red0fireus** [comment]
Here is the panel: https://github.com/pterodactyl/panel

But thank you. I will look in to it with the people over there for support.
