### ISSUE TITLE
server-port environment not working.

### ISSUE THREAD

**Issue by Focusz** [itzg/docker-minecraft-server#841]
Hi bro, i'm used this docker for rancher docker and papermc 1.16.5.
And server-port environment to 25444, it's not working. Can you help me?

{
"id": "1s60",
"type": "service",
"links": {
"self": "…/v2-beta/projects/1a5/services/1s60",
"account": "…/v2-beta/projects/1a5/services/1s60/account",
"consumedbyservices": "…/v2-beta/projects/1a5/services/1s60/consumedbyservices",
"consumedservices": "…/v2-beta/projects/1a5/services/1s60/consumedservices",
"instances": "…/v2-beta/projects/1a5/services/1s60/instances",
"networkDrivers": "…/v2-beta/projects/1a5/services/1s60/networkdrivers",
"serviceExposeMaps": "…/v2-beta/projects/1a5/services/1s60/serviceexposemaps",
"serviceLogs": "…/v2-beta/projects/1a5/services/1s60/servicelogs",
"stack": "…/v2-beta/projects/1a5/services/1s60/stack",
"storageDrivers": "…/v2-beta/projects/1a5/services/1s60/storagedrivers",
"containerStats": "…/v2-beta/projects/1a5/services/1s60/containerstats"
},
"actions": {
"upgrade": "…/v2-beta/projects/1a5/services/1s60/?action=upgrade",
"restart": "…/v2-beta/projects/1a5/services/1s60/?action=restart",
"update": "…/v2-beta/projects/1a5/services/1s60/?action=update",
"remove": "…/v2-beta/projects/1a5/services/1s60/?action=remove",
"deactivate": "…/v2-beta/projects/1a5/services/1s60/?action=deactivate",
"removeservicelink": "…/v2-beta/projects/1a5/services/1s60/?action=removeservicelink",
"addservicelink": "…/v2-beta/projects/1a5/services/1s60/?action=addservicelink",
"setservicelinks": "…/v2-beta/projects/1a5/services/1s60/?action=setservicelinks"
},
"baseType": "service",
"name": "Minecraft",
"state": "active",
"accountId": "1a5",
"assignServiceIpAddress": false,
"createIndex": 18,
"created": "2021-04-21T22:27:01Z",
"createdTS": 1619044021000,
"currentScale": 1,
"description": "Survival",
"externalId": null,
"fqdn": null,
"healthState": "healthy",
"instanceIds": [ 2 items
"1i349",
"1i350"
],
"kind": "service",
"launchConfig": {
"type": "launchConfig",
"blkioWeight": null,
"capAdd": [ ],
"capDrop": [ ],
"cgroupParent": null,
"count": null,
"cpuCount": null,
"cpuPercent": null,
"cpuPeriod": null,
"cpuQuota": null,
"cpuRealtimePeriod": null,
"cpuRealtimeRuntime": null,
"cpuSet": null,
"cpuSetMems": null,
"cpuShares": null,
"dataVolumes": [
"/minecraft-data/Survival:/data"
],
"dataVolumesFrom": [ ],
"description": null,
"devices": [ ],
"diskQuota": null,
"dns": [ ],
"dnsSearch": [ ],
"domainName": null,
"environment": {
"DIFFICULTY": "normal",
"EULA": "true",
"GENERATOR_SETTINGS": "",
"LEVEL_TYPE": "DEFAULT",
"MODE": "survival",
"MOTD": "A Minecraft server powered by Docker",
"OPS": "",
"PVP": "false",
"SEED": "",
"VERSION": "LATEST",
"WHITELIST": "",
"WORLD": "",
"PAPER_DOWNLOAD_URL": "https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/606/downloads/paper-1.16.5-606.jar",
"TYPE": "PAPER",
"SERVER_PORT": "20010"
},
"healthCheck": null,
"healthInterval": null,
"healthRetries": null,
"healthTimeout": null,
"hostname": null,
"imageUuid": "docker:itzg/minecraft-server",
"instanceTriggeredStop": "stop",
"ioMaximumBandwidth": null,
"ioMaximumIOps": null,
"ip": null,
"ip6": null,
"ipcMode": null,
"isolation": null,
"kernelMemory": null,
"kind": "container",
"labels": {
"io.rancher.sidekicks": "MinecraftData",
"io.rancher.container.pull_image": "always"
},
"logConfig": {
"type": "logConfig",
"config": { },
"driver": null
},
"memory": null,
"memoryMb": null,
"memoryReservation": null,
"memorySwap": null,
"memorySwappiness": null,
"milliCpuReservation": null,
"networkContainerId": null,
"networkMode": "host",
"oomScoreAdj": null,
"pidMode": null,
"pidsLimit": null,
"ports": [ ],
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"requestedIpAddress": null,
"runInit": false,
"secrets": [ ],
"shmSize": null,
"startOnCreate": true,
"stdinOpen": true,
"stopSignal": null,
"stopTimeout": null,
"system": false,
"tty": true,
"user": null,
"userdata": null,
"usernsMode": null,
"uts": null,
"version": "0021f45b-1ff2-4456-b934-3dc814326bbd",
"volumeDriver": null,
"workingDir": null,
"dataVolumesFromLaunchConfigs": [
"MinecraftData"
],
"networkLaunchConfig": null,
"vcpu": 1,
"drainTimeoutMs": 0
},
"lbConfig": null,
"linkedServices": null,
"metadata": {
"io.rancher.service.hash": "16fff32e85e3896356172e572b0659186975c017"
},
"publicEndpoints": [ ],
"removed": null,
"retainIp": null,
"scale": 1,
"scalePolicy": null,
"secondaryLaunchConfigs": [
{
"type": "secondaryLaunchConfig",
"dataVolumes": [
"/minecraft-data:/data/data"
],
"entryPoint": [
"/bin/true"
],
"imageUuid": "docker:busybox",
"instanceTriggeredStop": "stop",
"kind": "container",
"labels": {
"io.rancher.container.start_once": "true",
"io.rancher.service.hash": "9ed64fe08107549f05f5ec54a5d3d838a1ae0bb5"
},
"logConfig": {
"type": "logConfig"
},
"name": "MinecraftData",
"networkMode": "none",
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"runInit": false,
"startOnCreate": true,
"stdinOpen": false,
"system": false,
"tty": false,
"vcpu": 1,
"version": "0"
}
],
"selectorContainer": null,
"selectorLink": null,
"stackId": "1st34",
"startOnCreate": false,
"system": false,
"transitioning": "no",
"transitioningMessage": null,
"transitioningProgress": null,
"upgrade": {
"type": "serviceUpgrade",
"inServiceStrategy": {
"type": "inServiceUpgradeStrategy",
"batchSize": 1,
"intervalMillis": 2000,
"launchConfig": {
"type": "launchConfig",
"blkioWeight": null,
"capAdd": [ ],
"capDrop": [ ],
"cgroupParent": null,
"count": null,
"cpuCount": null,
"cpuPercent": null,
"cpuPeriod": null,
"cpuQuota": null,
"cpuRealtimePeriod": null,
"cpuRealtimeRuntime": null,
"cpuSet": null,
"cpuSetMems": null,
"cpuShares": null,
"dataVolumes": [
"/minecraft-data/Survival:/data"
],
"dataVolumesFrom": [ ],
"description": null,
"devices": [ ],
"diskQuota": null,
"dns": [ ],
"dnsSearch": [ ],
"domainName": null,
"environment": {
"DIFFICULTY": "normal",
"EULA": "true",
"GENERATOR_SETTINGS": "",
"LEVEL_TYPE": "DEFAULT",
"MODE": "survival",
"MOTD": "A Minecraft server powered by Docker",
"OPS": "",
"PVP": "false",
"SEED": "",
"VERSION": "LATEST",
"WHITELIST": "",
"WORLD": "",
"PAPER_DOWNLOAD_URL": "https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/606/downloads/paper-1.16.5-606.jar",
"TYPE": "PAPER",
"SERVER_PORT": "20010"
},
"healthCheck": null,
"healthInterval": null,
"healthRetries": null,
"healthTimeout": null,
"hostname": null,
"imageUuid": "docker:itzg/minecraft-server",
"instanceTriggeredStop": "stop",
"ioMaximumBandwidth": null,
"ioMaximumIOps": null,
"ip": null,
"ip6": null,
"ipcMode": null,
"isolation": null,
"kernelMemory": null,
"kind": "container",
"labels": {
"io.rancher.sidekicks": "MinecraftData",
"io.rancher.container.pull_image": "always"
},
"logConfig": {
"type": "logConfig",
"config": { },
"driver": null
},
"memory": null,
"memoryMb": null,
"memoryReservation": null,
"memorySwap": null,
"memorySwappiness": null,
"milliCpuReservation": null,
"networkContainerId": null,
"networkMode": "host",
"oomScoreAdj": null,
"pidMode": null,
"pidsLimit": null,
"ports": [
"20010:20010/tcp"
],
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"requestedIpAddress": null,
"runInit": false,
"secrets": [ ],
"shmSize": null,
"startOnCreate": true,
"stdinOpen": true,
"stopSignal": null,
"stopTimeout": null,
"system": false,
"tty": true,
"user": null,
"userdata": null,
"usernsMode": null,
"uts": null,
"version": "45ab773b-d09c-4928-8ad6-69d5dcb19c4c",
"volumeDriver": null,
"workingDir": null,
"dataVolumesFromLaunchConfigs": [
"MinecraftData"
],
"networkLaunchConfig": null,
"vcpu": 1,
"drainTimeoutMs": 0
},
"previousLaunchConfig": {
"type": "launchConfig",
"blkioWeight": null,
"capAdd": [ ],
"capDrop": [ ],
"cgroupParent": null,
"count": null,
"cpuCount": null,
"cpuPercent": null,
"cpuPeriod": null,
"cpuQuota": null,
"cpuRealtimePeriod": null,
"cpuRealtimeRuntime": null,
"cpuSet": null,
"cpuSetMems": null,
"cpuShares": null,
"dataVolumes": [
"/minecraft-data/Survival:/data"
],
"dataVolumesFrom": [ ],
"description": null,
"devices": [ ],
"diskQuota": null,
"dns": [ ],
"dnsSearch": [ ],
"domainName": null,
"environment": {
"DIFFICULTY": "normal",
"EULA": "true",
"GENERATOR_SETTINGS": "",
"LEVEL_TYPE": "DEFAULT",
"MODE": "survival",
"MOTD": "A Minecraft server powered by Docker",
"OPS": "",
"PVP": "false",
"SEED": "",
"VERSION": "LATEST",
"WHITELIST": "",
"WORLD": "",
"PAPER_DOWNLOAD_URL": "https://papermc.io/api/v2/projects/paper/versions/1.16.5/builds/606/downloads/paper-1.16.5-606.jar",
"TYPE": "PAPER",
"SERVER_PORT": "20010"
},
"healthCheck": null,
"healthInterval": null,
"healthRetries": null,
"healthTimeout": null,
"hostname": null,
"imageUuid": "docker:itzg/minecraft-server",
"instanceTriggeredStop": "stop",
"ioMaximumBandwidth": null,
"ioMaximumIOps": null,
"ip": null,
"ip6": null,
"ipcMode": null,
"isolation": null,
"kernelMemory": null,
"kind": "container",
"labels": {
"io.rancher.sidekicks": "MinecraftData",
"io.rancher.container.pull_image": "always"
},
"logConfig": {
"type": "logConfig",
"config": { },
"driver": null
},
"memory": null,
"memoryMb": null,
"memoryReservation": null,
"memorySwap": null,
"memorySwappiness": null,
"milliCpuReservation": null,
"networkContainerId": null,
"networkMode": "host",
"oomScoreAdj": null,
"pidMode": null,
"pidsLimit": null,
"ports": [ ],
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"requestedIpAddress": null,
"runInit": false,
"secrets": [ ],
"shmSize": null,
"startOnCreate": true,
"stdinOpen": true,
"stopSignal": null,
"stopTimeout": null,
"system": false,
"tty": true,
"user": null,
"userdata": null,
"usernsMode": null,
"uts": null,
"version": "0021f45b-1ff2-4456-b934-3dc814326bbd",
"volumeDriver": null,
"workingDir": null,
"dataVolumesFromLaunchConfigs": [
"MinecraftData"
],
"networkLaunchConfig": null,
"vcpu": 1,
"drainTimeoutMs": 0
},
"previousSecondaryLaunchConfigs": [
{
"type": "secondaryLaunchConfig",
"dataVolumes": [
"/minecraft-data:/data/data"
],
"entryPoint": [
"/bin/true"
],
"imageUuid": "docker:busybox",
"instanceTriggeredStop": "stop",
"kind": "container",
"labels": {
"io.rancher.container.start_once": "true",
"io.rancher.service.hash": "9ed64fe08107549f05f5ec54a5d3d838a1ae0bb5"
},
"logConfig": {
"type": "logConfig"
},
"name": "MinecraftData",
"networkMode": "none",
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"runInit": false,
"startOnCreate": true,
"stdinOpen": false,
"system": false,
"tty": false,
"vcpu": 1,
"version": "0"
}
],
"secondaryLaunchConfigs": [
{
"type": "secondaryLaunchConfig",
"dataVolumes": [
"/minecraft-data:/data/data"
],
"entryPoint": [
"/bin/true"
],
"imageUuid": "docker:busybox",
"instanceTriggeredStop": "stop",
"kind": "container",
"labels": {
"io.rancher.container.start_once": "true",
"io.rancher.service.hash": "9ed64fe08107549f05f5ec54a5d3d838a1ae0bb5"
},
"logConfig": {
"type": "logConfig"
},
"name": "MinecraftData",
"networkMode": "none",
"privileged": false,
"publishAllPorts": false,
"readOnly": false,
"runInit": false,
"startOnCreate": true,
"stdinOpen": false,
"system": false,
"tty": false,
"vcpu": 1,
"version": "0"
}
],
"startFirst": false
},
"toServiceStrategy": null
},
"uuid": "34fbdbfd-a39f-403b-9b7a-0a055d30a762",
"vip": null
}

**Comment by itzg** [comment]
Why are you wanting to change `server-port`? Docker port mapping might be what you actually intended.

**Comment by Focusz** [comment]
Because I want to run multiple minecraft servers in oner. 
![image](https://user-images.githubusercontent.com/4957690/115635799-bb3f9580-a336-11eb-9422-49eaf4d02dec.png)

When I rebuild any server, it still defaults to 25565.
![image](https://user-images.githubusercontent.com/4957690/115635857-d6aaa080-a336-11eb-8e6d-99588afcf666.png)

**Comment by itzg** [comment]
> Because I want to run multiple minecraft servers in oner. 

What does "in oner" mean? 

In any case, unless Rancher changes something fundamental in Docker then containers have isolated network namespaces anyway. The server-port binding is within that namespace, so you can have any number of containers all listening on 25565.
