### ISSUE TITLE
Support downloads from FTP servers

### ISSUE THREAD

**Issue by RouNNdeL** [itzg/docker-minecraft-server#849]
Right now when using an ftp server url (e.g. `ftp://192.168.1.10/modpack.zip`) an error is thrown that the URL is not valid. However, `curl` supports downloads from an FTP server, so there shouldn't be a reason that an URL starting with `ftp` is not valid. I considered creating a PR, but don't want to change the `isURL` function as it might be used in some places that require HTTP. Maybe split into `isHttpUrl` and `isFtpUrl` ?

**Comment by itzg** [comment]
I'd have to look through the usages, but I'm guessing all checks of isURL precede a curl invocation. If you could check through that too a PR would be great.

**Comment by RouNNdeL** [comment]
Will do :)
