### ISSUE TITLE
REMOVE_OLD_MODS requires presence of 'mods' and 'plugins' under /data

### ISSUE THREAD

**Issue by Stealthii** [itzg/docker-minecraft-server#851]
When using the `REMOVE_OLD_MODS` flag to clean up old mods/plugins on startup, the server failed to load if either the 'mods' or 'plugins' directories don't exist under `/data/`:
```
Attaching to minecraft_lobby_1
lobby_1             | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Apr 28 13:04 /data'
lobby_1             | [init] Resolved version given LATEST into 1.16.5
lobby_1             | [init] Resolving type given AIRPLANE
lobby_1             | [init] Downloading Airplane from https://dl.airplane.gg/latest/Airplane-JDK11/launcher-airplane.jar ...
lobby_1             | find: /data/mods: No such file or directory
lobby_1             | find: /data/plugins: No such file or directory
minecraft_lobby_1 exited with code 1
```

This applies to all configured server types, not just Airplane (tested with Paper, Forge, etc.)

These directories don't exist at all on fresh server startup. Even if this option is disabled (to allow initial creation), it will still fail on Spigot-like instances where 'mods' isn't created.

**Comment by Stealthii** [comment]
Hang on - looks like this was fixed in b1bb3f3. Looking forward to release, many thanks!

**Comment by itzg** [comment]
Actually, I'm going to reopen since I thought the change you linked would proceed even if the base directories of the `find` were not present.

**Comment by itzg** [comment]
Pushed a version of `latest` tag that should fix this. I'll get it merged over to other tags after another PR is merged.
