### ISSUE TITLE
FORGE server java8 output debug log

### ISSUE THREAD

**Issue by gargamelonly** [itzg/docker-minecraft-server#854]
A couple of days ago the server started to output debug logs files in the log folder. 
I did not change any config or properties to enable it. 
How do I stop the debug log from being generated?

    image: itzg/minecraft-server:java8
      - TYPE=FORGE
      - VERSION=1.12.2
.forge-installed-1.12.2-14.23.5.2855

**Comment by itzg** [comment]
Did a quick Google search and I'm not finding any obvious answers that I could work into the image 

https://www.google.com/search?q=forge+enable+debug+logs

**Comment by gargamelonly** [comment]
Something related to this maybe?
[main/DEBUG] [FML]: Injecting tracing printstreams for STDOUT/STDERR.
