### ISSUE TITLE
[Enhancement Request] Custom Start Option

### ISSUE THREAD

**Issue by ichbestimmtnicht** [itzg/docker-minecraft-server#855]
Reason:
Some CurseForge Modpacks do not comply to the best practise to deliver a `ServerStart.sh` within their pack. (See [Issue 838](https://github.com/itzg/docker-minecraft-server/issues/838#issuecomment-823639463) for 2 examples)

Enhancement ideas:
- Providing an ENV option such as `CUSTOM_START_JAR="example.jar"` to name the `.jar` file to start the server with the other provided options such as MEM
- Providing an option to provide an `custom_start.sh` within for example the modpacks folder with the ENV option `CUSTOM_START_SCRIPT="/location/to/script/"`
- Providing an option to override the startup with for example ENV `CUSTOM_START_CMD="java -jar name.jar nogui"`

**Comment by UdoChudo** [comment]
it would be super nice :)
