### ISSUE TITLE
 Failed to verify username

### ISSUE THREAD

**Issue by fabricioo93** [itzg/docker-minecraft-server#860]
Good night, I would like to ask for help. I can't log into my own server. ONLINE_MODE is false, I still can't get in. Thanks!
![image](https://user-images.githubusercontent.com/66912509/117559082-a2362480-b058-11eb-9b54-40feec28a25c.png)

**Comment by TheLastBilly** [comment]
I had this exact same issue a few minutes ago, I solved it by recreating the minecraft data folder. You can also go into the settings for the server and change the online-mode variable to false

**Comment by itzg** [comment]
@fabricioo93 what exact error are you seeing? Please provide a screenshot, etc. Also provide the container logs around the time of attempted connection. 

Why did you want to disable online mode to fix a login issue? FYI there's a variable to allow for overriding server properties after the data directory has been setup.

**Comment by mv-stns** [comment]
> @fabricioo93 what exact error are you seeing? Please provide a screenshot, etc. Also provide the container logs around the time of attempted connection.
> 
> Why did you want to disable online mode to fix a login issue? FYI there's a variable to allow for overriding server properties after the data directory has been setup.

not working, trying to get a friend on my mc server.
