### ISSUE TITLE
Java 16 images required for 21w19a onwards

### ISSUE THREAD

**Issue by Stealthii** [itzg/docker-minecraft-server#864]
With Mojang's change to using Java 16 in snapshot 21w19a, images will need prepared with OpenJDK 16 in order to run instances under this and future versions.

As the game is compiled with Java 16, and has a class file version of 60, Java 15 and below will not execute these jars.

**Comment by itzg** [comment]
README has been updated and build is in progress

https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version

**Comment by itzg** [comment]
`itzg/minecraft-server:java16` is now available. I'm doing a quick test myself with that image and `VERSION=SNAPSHOT`.

**Comment by m4lfunction** [comment]
> `itzg/minecraft-server:java16` is now available. I'm doing a quick test myself with that image and `VERSION=SNAPSHOT`.

Just tested, seems to be working fine.

**Comment by Stealthii** [comment]
Can confirm this works as expected under type `FABRIC` and `VANILLA`. Happy to close this!

**Comment by Panderine** [comment]
Hi! It's me again the openj9 guy. Would you be so kind to add java16-openj9 version? I think you can remove java15-openj9. Thanks again for everything!!!
