### ISSUE TITLE
Automatic Minecraft server stopping

### ISSUE THREAD

**Issue by Twometer** [itzg/docker-minecraft-server#874]
First of all, thank you for this amazing project! I really love it.

I am currently developing an application that can automatically start and stop Minecraft servers based on player count. While the actual server is offline, it provides the Minecraft Ping (so that the server appears online in the server list), and once someone connects to the server, it automatically starts the server and redirects the traffic via firewall rules. After everyone has left and some time passed, it will gracefully shut down the server.

This would be really useful for small (private) servers that are only occasionally used by a few players, and where you don't want it to eat RAM while no one uses it.

Would you be interested in an integration with your docker container? Maybe it could be integrated into your `mc-server-runner`, where I could post a Pull Request; or one could implement it as a separate "proxy" layer after the runner.

I have started working on this tool using Go at https://github.com/Twometer/craftignite. It currently only implements the Ping Protocol, and does not automatically start and stop yet, but I wanted to wait for your reply on the integration beforehand🙂

**Comment by MaxiMii05** [comment]
There's already the AUTOPAUSE functionality built into the container. However, the container still reserves the allocated amount of RAM even when the server is stopped.
If it is possible to free up the memory when the server is stopped, I would highly appreciate this addition. Whether that is by using your project or by simply expanding the already existing autopause functionality is for someone else to decide.

**Comment by Twometer** [comment]
Very nice to see that there are other people interested in such an addition 😀. Yes, that's the idea behind this new project. An alternative to autopause, that does not only, well, pause, but completely shut down the server, so that it does not use any resources (RAM etc)

**Comment by itzg** [comment]
That sounds like a great concept. I would prefer to keep it as an adjacent solution since the benefit of Docker is that it enables small, purposeful building blocks. FWIW, I have very briefly considered shifting the auto-pause feature to be a derived image since it goes slightly beyond the mainline functionality. 

With all that said, I would really like to include a link to your project in the README when you're ready so that I can encourage the community to find great solutions.

**Comment by Twometer** [comment]
Okay, yes I understand that this project is beyond the scope of the core image. A derived image sounds like a good idea, so I've forked (some of) the repositories at https://github.com/craftignite and I'll start implementing the service there.

Also, including a link in the README would be really great for the project once it's finished, so thank you very much! 🙂 

I'll keep updates on the project posted here!
