### ISSUE TITLE
auto-updating premium plugins

### ISSUE THREAD

**Issue by General-Zimmer** [itzg/docker-minecraft-server#876]
(I wrote this after a long session of reading and tinkering with stuff, so my brain is completely fried)

I've recently began moving stuff to docker, some of it being Minecraft servers. My issue however, is I can't auto-update premium plugins with this image. I haven't taken a look at Spiget API yet, so I have no clue if there's a way to add log-in or authentication to allow premium plugins to be downloaded via a direct link. Is it possible?

**Comment by itzg** [comment]
I have never used a premium plugin, so I have no idea how those usually work. Do you login to their site and download a copy of the plugin? And then does it require a serial number or something to be configured?

What is an example of one? I suspect the answer is that it won't be possible to automate but really it depends on whether the provider has an API.

**Comment by General-Zimmer** [comment]
Not too many hours after I wrote this, I found out it wasn't possible.
