### ISSUE TITLE
[Feature Request] Somehow use this docker setup to just download and install the server instance with no docker container

### ISSUE THREAD

**Issue by Hi-ImKyle** [itzg/docker-minecraft-server#878]
I can understand if you don't follow what I mean with that title so I'll do my best to explain it.

I love this for creating Minecraft servers, it's great, it works flawlessly. But recently I've moved to a WebUI to handle my game server instances. It does the creating and installing stuff but also has a manual way of setting up servers.

My request or, just general asking how-to, is, is it possible to use this docker setup to just download and install all the Minecraft related things, like the server jar, the ftb mod pack and unpack etc, basically do everything but run the server and just dump everything the server needs to a folder somewhere. 

My idea is just a script that is either apart or a standalone to this, you pass the same arguments you would to specify a server type, the server mod pack if using one and it goes and gets everything you need to start the server, but then I can point my WebUI to its downloaded directory to manage it. To note, installation of Java wouldn't be required but obviously for those who are in the same boat as me might not have it installed so a quick check might be in order.

I'm sorry if this is a bit much of an ask, I do have to admit I was thinking of just doing it the lazy way and using this and moving everything myself but I don't want to make unnecessary containers for the sake of this... Do you get what I mean? Sorry~

**Comment by itzg** [comment]
I think this would be easy to add. Just to make sure I understand it would do everything right up until the point of running Java, but instead just exit? I'm assuming you'd have a host directory mounted to the container's `/data`  and then use the content of that prepared host directory?

**Comment by Hi-ImKyle** [comment]
Yes, do everything up until running the actual server, this leaves the server folder in like a ready to run state assuming Java is installed. Then I can tell my WebUI whats what for my personal use case.

**Comment by itzg** [comment]
I have added the option for `-e SETUP_ONLY=true` where just before exiting it'll output the java command-line it would have invoked, such as

```
SETUP_ONLY: java -Xms1G -Xmx1G -jar minecraft_server.1.16.5.jar
```

**Comment by Hi-ImKyle** [comment]
Sounds good. In order to test, do I need to wait for the image to be updated via docker hub? Only ever got images from there, not sure if I can pull from github and use the updated version. (Sorry, I know docker, just not well)

**Comment by itzg** [comment]
Sorry, I should have clarified that then image is already pushed to Docker Hub. Just do a pull to grab the latest.

**Comment by Hi-ImKyle** [comment]
The following command, `docker run -d -it -p 6969:25565 -v /disk1/dump/vanilla:/data -e EULA=TRUE -e SETUP_ONLY=TRUE itzg/minecraft-server` just runs the server normally. Doesn't seem to stop. Am I being silly and missing something?

**Comment by Hi-ImKyle** [comment]
Enjoy the coffees :)
