### ISSUE TITLE
Autopause: Not resuming when UID / GID set to nondefault values

### ISSUE THREAD

**Issue by Oekn5w** [itzg/docker-minecraft-server#882]
https://github.com/itzg/docker-minecraft-server/issues/555#issuecomment-844718608 : ~Bug confirmed~.

> I am not running as UID/GID 1000 .. if I manually run this with the correct user and group it resumes but not if I manually run the line above.

**Comment by Oekn5w** [comment]
@Tailslide not confirmed, error on my side. Do you have steps to reproduce the issue?

**Comment by Tailslide** [comment]
I don't have a clean reproduce for this unfortunately. Part of my difficulties may have been not being aware of the difference between UID, GID and PUID and PGUID on my Synology Docker.  May be worth starting from scratch and giving people a step by step on getting autopause working with non default UID.. I'm still not clear on what steps to take.  Does the minecraft user get set to some other UID somehow or is it supposed to work set at 1000 ?

I recreated my container with UID 1000 and chown'd my data files to 1000 and autopause works fine now.
I think now that I have it working I'll stick with the default UID 1000

**Comment by Oekn5w** [comment]
Hmm, I used the UID and GID environment variables, and the owner of the persistent data directory is set to these on container startup. This is on a "clean" Ubuntu docker(-compose) environment, idk what Synology does to docker. Both are 1000 by default, and the minecraft user and group id is set according to the variables.

**Comment by Oekn5w** [comment]
@Tailslide Which tag and compose file / docker command do you use?

**Comment by Tailslide** [comment]
Here is a script I was using when I was fighting with this.. user greg is 1026 and group users is 100
I've since moved to a compose file that uses the default UID of 1000.

```
docker stop mc
docker rm mc
sudo rm -rf /volume1/docker/minecraft/data/mods/*
cp /var/services/homes/greg/pugserver/mods/* /volume1/docker/minecraft/data/mods
chown greg /volume1/docker/minecraft/data/mods/*
chgrp users /volume1/docker/minecraft/data/mods/*
docker run -d -v /volume1/docker/minecraft/data:/data -e TYPE=FABRIC \
    --user 1026 -e UID=1026 -e GID=100 -p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server
```

**Comment by Tailslide** [comment]
Aha PGID and PUID are nothing to do with synology just a convention that some containers use to resolve these permissions issues by changing the ID of the user. Might work in this case for the minecraft user.

https://meta.discourse.org/t/choose-the-user-puid-and-pgid-inside-the-container/113309
