### ISSUE TITLE
How to force IPV4 insteadof IPV6

### ISSUE THREAD

**Issue by mistrjirka** [itzg/docker-minecraft-server#884]
Hi, I noticed that when using Minecraft server (forge), the default IP version is 6 instead of 4, this makes it really hard to port forward. If you have any idea how to force it back. I would be very glad. 
tcp6       0      0 :::25565                :::*                    Listening

**Comment by itzg** [comment]
netstat/lsof seem to report the docker proxy's bound port as tcp6/IPv6 but it's actually binding to both IPv6/IPv4. As a result, just do plain old IPv4 port forwarding and it will be fine. That's what I do on my home system.
