### ISSUE TITLE
The requested URL returned error: 522 

### ISSUE THREAD

**Issue by Dids** [itzg/docker-minecraft-server#893]
Using Paper and a few Spigot mods, installed with the env vars.
Everything worked great, until I just tried adding two new mods to the env var, and it now repeatedly errors on startup.

Removing the two new mods from the env var has no effect, so I'm now wondering if it's failing to update/check for updates to Paper itself?

Any idea what causes the following?

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx. 9 1000 1000 4096 May 25 06:30 /data'
[init] Resolved version given LATEST into 1.16.5
[init] Resolving type given PAPER
curl: (22) The requested URL returned error: 522 
curl: (22) The requested URL returned error: 522 
[init] WARN: using  since that's the latest provided by PaperMC
curl: (22) The requested URL returned error: 522 
curl: (22) The requested URL returned error: 522 
[init] WARN: using  since that's the latest provided by PaperMC
curl: (22) The requested URL returned error: 522 
curl: (22) The requested URL returned error: 522 
[init] WARN: using  since that's the latest provided by PaperMC
curl: (22) The requested URL returned error: 522 
curl: (22) The requested URL returned error: 522 
[init] WARN: using  since that's the latest provided by PaperMC
```

**Comment by Dids** [comment]
Update: turns out papermc.io is down at the moment, which is why this is happening.
This does make me wonder if this Docker image should still deal with this issue, and effectively skip the update checks if PaperMC is already installed, allowing the server to startup regardless?

**Comment by campfred** [comment]
I'd add as a second workaround option in the meantime that the `PAPER_DOWNLOAD_URL` environment variable enabled me to get back up and running.

In my case, I just pointed it at the link shown on [the PaperMC website's download page](https://papermc.io/downloads) for getting their latest version. I don't know if it is the latest _stable_ build that they put there though. But for the only container that I rebooted and got stuck in that situation, it wasn't much of a concern.

**Comment by itzg** [comment]
Thanks for the workaround idea @campfred 

I'll see if I can at least improve the error handling since the loop of messages is not good

```
curl: (22) The requested URL returned error: 522 
curl: (22) The requested URL returned error: 522 
[init] WARN: using  since that's the latest provided by PaperMC
curl: (22) The requested URL returned error: 522 
curl: (22) The requested URL returned error: 522 
```

**Comment by campfred** [comment]
You're welcome, @itzg!
I'll add that for the error messages, my logs were showing a 404 error instead, which is what threw me off because I couldn't believe that PaperMC would vanish from the face off heart on a pinch (even though it _is_ possible). So, if you're looking into reacting to specific error codes, you might want to take the 404 one in account too.
