### ISSUE TITLE
Auto restarting on update release

### ISSUE THREAD

**Issue by matthew-jones-uk** [itzg/docker-minecraft-server#899]
I understand that when a new version is detected it'll update to it on startup but is it possible to have the server stop itself (and perhaps restart) on detection of an update?

E.g. I have it set to use the latest snapshots with docker and when a new snapshot is released I have to manually stop and restart the container (which I might not be there to do). It would be nice if the container could stop itself (and so docker would automatically restart it) or the server itself is stopped and restarted (within the container) so that an update can be performed.

Thanks!

**Comment by itzg** [comment]
That's a reasonable request, but is outside the scope of this image. The last thing the container startup does is exec the Java process, so there's nothing lingering that could watch for upgrades. 

Instead, this is an opportunity for the community to develop a sidecar container or tool that watches for updates and restarts the container as normal.

Another approach could be enhancing https://github.com/itzg/mc-router to watch for upgrades and wait for no player connections to minimize disruption.
