### ISSUE TITLE
SevTech: Ages modpack is started with 4GB of ram

### ISSUE THREAD

**Issue by Luxed** [itzg/docker-minecraft-server#905]
It seems like the [SevTech: Ages 3.2.1](https://www.curseforge.com/minecraft/modpacks/sevtech-ages) modpack uses a `settings.sh` file instead of `settings-local.sh` file that was created.
It looks like this:
<details>
  <summary>settings.sh</summary>

```sh
# Don't edit these values unless you know what you are doing.
export INSTALL_JAR="forge-1.12.2-14.23.5.2854-installer.jar"
export SERVER_JAR="forge-1.12.2-14.23.5.2854.jar"

# You can edit these values if you wish.
export MIN_RAM="1024M"
export MAX_RAM="4096M"
export JAVA_PARAMETERS="-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Dfml.readTimeout=180"
```

</details>

This file is then sourced in `ServerStart.sh`.
There are a few ways that I saw to resolve this issue:

1. Modify the `ServerStart.sh` file to source the `settings-local.sh` file _after_ the `settings.sh` file, thus overwriting the variables it set beforehand.
2. Modify the `settings.sh` file the same way the `settings.cfg` file is modified to set the correct values.

I am able to make a PR for this but I have a few questions first:

- Is this an edge that should not even be taken care of?
- If this needs to be fixed, which solution should be chosen?

**Comment by itzg** [comment]
All modpacks seem to be edge cases unfortunately. 

Option 1 seems too brittle especially since there is no consistent/required structure modpack authors use for the start scripts. 

Option 2 sounds good.

**Comment by Luxed** [comment]
As said on the PR #907, I simply do not like the solution that was implemented and decided against merging it.
If anyone else needs this code merged, they are free to take it and make another PR!
