### ISSUE TITLE
minecraft server curl: (28) Connection time-out

### ISSUE THREAD

**Issue by mrprogremmer010** [itzg/docker-minecraft-server#909]
Hello my friend i saw your docker of the Minecraft server but i get this error curl: (28) Connection time-out please help me I am sad

**Comment by itzg** [comment]
Are you running on RaspberryPi?

**Comment by matteoscrugli** [comment]
Hi, I have the same error, I'm on RaspberryPi 4 and I run this command:
```
sudo docker run \
--name minecraft-server \
-d \
-p 25565:25565 \
-e EULA=TRUE \
-e PUID=1000 \
-e PGID=1000 \
--restart=always \
-v /var/lib/docker/volumes/minecraft/data:/data \
itzg/minecraft-server:latest
```
I have the same error with:
` sudo docker run -d -p 25565:25565 --name minecraft-server -e EULA=TRUE itzg/minecraft-server`
Log:
```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jun  8  2021 /data'
curl: (28) Timeout was reached
```
Thank you

**Comment by PaoloP74** [comment]
Same error running on NAS WD MyCloudEx2Ultra (linux armv7l - 4.14.22-armada-18.09.3).

**Comment by itzg** [comment]
Please follow the solution starting at this comment

https://github.com/itzg/docker-minecraft-server/issues/755#issuecomment-781615497

I need to add some more detail to the README

https://github.com/itzg/docker-minecraft-server#running-on-raspberrypi
