### ISSUE TITLE
Plugins installation

### ISSUE THREAD

**Issue by pelich** [itzg/docker-minecraft-server#911]
Hi, First of all I am sorry I have not post this in discussion tab but it seems is quiet dead. I am a father of 2 boys that love Minecraft and asked me for help.

I am not computer savvy but I have managed to install on my Synology docker and then I have successfully installed itzg Minecraft server. They are able to connect and play. The only thing they want me to add to the server is "Worldedit" plugin..
Can someone pls explain to me how to do it??? 

Thank you for your help!!!

Michal

**Comment by itzg** [comment]
Yeah, people don't seem to find the discussion area  wry often. I myself don't have experience with any of the NAS solutions but you could ask around in this server channel

https://discord.gg/7P4nHBbG

Here are the general instructions if it helps

https://github.com/itzg/docker-minecraft-server#working-with-mods-and-plugins

**Comment by JeroenAdam** [comment]
So I have the same issue, I abandoned the TYPE=CURSEFORGE parameter and went with this one: MODPACK=https://media.forgecdn.net/files/3502/99/worldedit-bukkit-7.2.7.jar

All seems fine, here a piece of the log output:
[init] Downloading mod/plugin pack
Archive:  /tmp/modpack.zip
   creating: /data/mods/META-INF/
  inflating: /data/mods/META-INF/MANIFEST.MF
   creating: /data/mods/com/
   creating: /data/mods/com/sk89q/
   creating: /data/mods/com/sk89q/bukkit/
   creating: /data/mods/com/sk89q/bukkit/util/
  inflating: /data/mods/com/sk89q/bukkit/util/ClassSourceValidator.class
  inflating: /data/mods/com/sk89q/bukkit/util/CommandInfo.class
  inflating: /data/mods/com/sk89q/bukkit/util/CommandInspector.class
  inflating: /data/mods/com/sk89q/bukkit/util/CommandRegistration.class
  inflating: /data/mods/com/sk89q/bukkit/util/CommandsManagerRegistration.class
  inflating: /data/mods/com/sk89q/bukkit/util/DynamicPluginCommand.class
  inflating: /data/mods/com/sk89q/bukkit/util/DynamicPluginCommandHelpTopic$Factory.class
  inflating: /data/mods/com/sk89q/bukkit/util/DynamicPluginCommandHelpTopic.class
  inflating: /data/mods/com/sk89q/bukkit/util/FallbackRegistrationListener.class
   creating: /data/mods/com/sk89q/wepif/
  inflating: /data/mods/com/sk89q/wepif/bPermissionsResolver.class
  inflating: /data/mods/com/sk89q/wepif/ConfigurationPermissionsResolver.class
  inflating: /data/mods/com/sk89q/wepif/DinnerPermsResolver.class
  inflating: /data/mods/com/sk89q/wepif/FlatFilePermissionsResolver.class
  inflating: /data/mods/com/sk89q/wepif/GroupManagerResolver.class
  inflating: /data/mods/com/sk89q/wepif/NijiPermissionsResolver.class
  inflating: /data/mods/com/sk89q/wepif/PermissionsExResolver.class
  inflating: /data/mods/com/sk89q/wepif/PermissionsProvider.class
  inflating: /data/mods/com/sk89q/wepif/PermissionsResolver.class
  inflating: /data/mods/com/sk89q/wepif/PermissionsResolverManager$MissingPluginException.class
  inflating: /data/mods/com/sk89q/wepif/PermissionsResolverManager$ServerListener.class
  inflating: /data/mods/com/sk89q/wepif/PermissionsResolverManager.class
  inflating: /data/mods/com/sk89q/wepif/PluginPermissionsResolver.class
  inflating: /data/mods/com/sk89q/wepif/VaultResolver.class
  inflating: /data/mods/com/sk89q/wepif/WEPIFRuntimeException.class
   creating: /data/mods/com/sk89q/worldedit/
   creating: /data/mods/com/sk89q/worldedit/bukkit/
   creating: /data/mods/com/sk89q/worldedit/bukkit/adapter/
  inflating: /data/mods/com/sk89q/worldedit/bukkit/adapter/AdapterLoadException.class
  inflating: /data/mods/com/sk89q/worldedit/bukkit/adapter/BukkitImplAdapter.class
  inflating: /data/mods/com/sk89q/worldedit/bukkit/adapter/BukkitImplLoader.class
  inflating: /data/mods/com/sk89q/worldedit/bukkit/adapter/Refraction.class
  inflating: /data/mods/com/sk89q/worldedit/bukkit/adapter/UnsupportedVersionEditException.class
  inflating: /data/mods/com/sk89q/worldedit/bukkit/BukkitAdapter$1.class
  inflating: /data/mods/com/sk89q/worldedit/bukkit/BukkitAdapter.class
  inflating: /data/mods/com/sk89q/worldedit/bukkit/BukkitBiomeRegistry.class

(many more of these)

The menu shows the existance of 3 mods.
Inside the container I do find the Worledit mod in the mods folder.

But I can't seem to use it, a chop on a block with the wooden axe doess not show the executed command, it just chops a block.
That's how it is supposed to work,.
Any thoughts?
