### ISSUE TITLE
1.17 Server requires Java 16 - Synology NAS

### ISSUE THREAD

**Issue by MrPinrel** [itzg/docker-minecraft-server#913]
We have been running your server using Docker on our Synology NAS, great work!

However, now that 1.17 is available, I get an error on start-up saying that the server needs classfile version 60 and our current version of Java only supports 52. I assume I need to get Java 16 running on my Synology NAS? Any ideas how to do that? The Synology Java app only supports Java 8 as far as I can tell.

Or can I use a different environment variable to get 1.17 running with Java 8?

thanks!

**Comment by DrFrankensteinUK** [comment]
Just coming to say having the same issues with 1.17 following to understand the fix/workaround

**Comment by itzg** [comment]
Make sure you have pulled the latest image. It was updated to Java 16 several weeks ago.

**Comment by DrFrankensteinUK** [comment]
I did a complete pull of images a few hours ago and tested using the JAVA15 version.. which version should we use?

**Comment by itzg** [comment]
Use the `latest` tag or `java16`. Java 15 is not supported by the 1.17 server.

**Comment by DrFrankensteinUK** [comment]
OK Gotcha... perfect I will get my userguide changed over on my site.

**Comment by MrPinrel** [comment]
I've been working on it and I'm close, but I still can't get it to work.  The native Synology support is only for Java8. I managed to get Java16 installed using rednoahs' java_installer package. now I can run the 1.17 minecraft server from the command line by typing the command 

java -jar minecraft_server.1.17.jar --nogui

However when I try to run the itz latest container on docker I still get 
![image](https://user-images.githubusercontent.com/85575790/121384856-a20a9c80-c916-11eb-90f4-706c58a33b25.png)

and then
![image](https://user-images.githubusercontent.com/85575790/121384953-b353a900-c916-11eb-8d4b-1800e3b16422.png)

It obviously is still trying to run it using the Java 8 files. I have been monkeying around with the JAVA and JAVA_HOME environment variables but I still can't get it to work.

Any ideas?

**Comment by itzg** [comment]
> The native Synology support is only for Java8. I managed to get Java16 installed using rednoahs' java_installer package. 

To be blunt, you're on the wrong path. The `itzg/minecraft-server` includes Java 16 itself, so it makes no difference if you even have Java installed on your Synology.

If you're running `java` from the Synology command-line then that's not an issue to report here against this Docker image.

**Comment by MrPinrel** [comment]
Appreciate the bluntness. I hadnt realized that Java16 was already included in the Docker image. 

I started from scratched, pulled the image with the latest tag again, created a new container, and I could see the env variables got set the right way this time. It is running!

thanks again
