### ISSUE TITLE
Problem MODPACK path

### ISSUE THREAD

**Issue by Nathan-Guillaume** [itzg/docker-minecraft-server#915]
Hello I have a problem when I want to recover my zip file in my windows folders, I use the function: classic of java to recover a path and I have this error :

"cp: can't stat 'C: \ lobby- default.zip ': no ​​such file or directory
[init] ERROR: failed to copy from C: \ lobby-default.zip "

Can you help me ? Thank you. 😉

**Comment by itzg** [comment]
You can't access host directory paths from within the container. Instead, attach that host directory as a volume for the container to access and then reference the files via the attached path.

**Comment by Nathan-Guillaume** [comment]
Can you tell me how I should place my files and which text to add in addition to the command to copy paste the plugin file in my C directory:

**Comment by itzg** [comment]
There's examples throughout [the README](https://github.com/itzg/docker-minecraft-server/blob/master/README.md) and in [the examples directory](https://github.com/itzg/docker-minecraft-server/tree/master/examples). But command-line it would be like `-v c:/some-path-on-your-host:/modpacks`

**Comment by Nathan-Guillaume** [comment]
But like that, I couldn't configure the settings from my java app

**Comment by itzg** [comment]
What command or compose file are you using so far to create your container?

**Comment by Nathan-Guillaume** [comment]
https://pastebin.com/TpGfytit

**Comment by itzg** [comment]
I'm not quite sure what HydroServer is, so I'm quite confused about the context. I also don't see where "C: \ lobby- default.zip" is getting referenced, so I don't know how to suggest a change in syntax. Perhaps read https://docs.docker.com/engine/reference/commandline/run/

**Comment by Nathan-Guillaume** [comment]
I just want to make a server balancing system, we can choose between two models if the first is the hub model or the second is the game model. for the two models you need different plugins, so I would like to have two templates that can still remain customizable from my code in java

**Comment by itzg** [comment]
> I just want to make a server balancing system, we can choose between two models if the first is the hub model or the second is the game model. for the two models you need different plugins, so I would like to have two templates that can still remain customizable from my code in java

That's completely different from your original issue description of

> Hello I have a problem when I want to recover my zip file in my windows folders, I use the function: classic of java to recover a path and I have this error

I guess I'll answer your new question: For varying plugins between models, use a different `MODPACK` for each.

**Comment by Nathan-Guillaume** [comment]
If I use what you told me above it is not possible to configure the ENVIRONMENTS of each image directly in the java code?
