### ISSUE TITLE
Add adopt8 container builds

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#920]
Perhaps this is already here & I'm missing it, but adoptopenjdk hotspot builds for Java 8 would be useful for forge 1.12.

Thanks

**Comment by itzg** [comment]
There's three Java 8 image tags and java8-multiarch is specifically adoptopenjdk

https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version

**Comment by ChipWolf** [comment]
Ah there we go, I was on the `java8` tag & it didn't look like Adopt. Will give it another go @itzg
