### ISSUE TITLE
Console Commands

### ISSUE THREAD

**Issue by ledfortr** [itzg/docker-minecraft-server#921]
Hi, I installed the latest docker onto unraid. Is there a way to run console commands?  How do you promote a user to admin?  Sorry, i'm a newb

**Comment by itzg** [comment]
I don't know anything about Unraid. Join the Discord server and ask in the NAS channel or post a question to Unraid.

**Comment by ledfortr** [comment]
Will do!

**Comment by phoenixsampras** [comment]
> I don't know anything about Unraid. Join the Discord server and ask in the NAS channel or post a question to Unraid.

Thanks for your reply.

What is the Discord link channel please?

**Comment by itzg** [comment]
@phoenixsampras its at the top of the README

**Comment by arejaytee** [comment]
For reference with Unraid you just need to add a new variable on the docker container configuration as per https://github.com/itzg/docker-minecraft-server#opadministrator-players 

To get the user id you first need to access Web GUI and grab the xuid: for your player, then add that to Value: option in your variable configuration.

![itzg-unraid-add-operator-variable](https://user-images.githubusercontent.com/6357327/124277114-091f1800-db88-11eb-9cf3-423ec4d5a08f.PNG)

**Comment by itzg** [comment]
Thanks @arejaytee for helping out.

FYI, you can/should enter regular usernames for OPS and others. The minecraft server itself will do the xuid conversion at startup.

I'm going to close out this issue, but @ledfortr feel free to chat more on Discord.
