### ISSUE TITLE
Any options for mob limits?

### ISSUE THREAD

**Issue by BloodBlight** [itzg/docker-minecraft-server#924]
As described here:
https://shockbyte.com/billing/knowledgebase/203/How-To-Change-The-Mob-Spawn-Rate-On-Your-Server.html

Are there any ways to limit the spawning of mobs?

Thanks!

**Comment by itzg** [comment]
The `bukkit.yml` file not directly managed by the image, so simply supply your own via the data and config mounts.

**Comment by BloodBlight** [comment]
I wasn't sure if it was a function of their loader, or something that could be added directly to vanilla.   If not, then this can just be closed.

Thanks!
