### ISSUE TITLE
Server can't keep up issue lately

### ISSUE THREAD

**Issue by Linightz** [itzg/docker-minecraft-server#927]
I've been experiencing significant lagging in the game lately, server-side log keeps generating this log "server can't keep up, is the server overloaded?".

It was good before, not long after we upgraded it to 1.17, this issue started happening and persists all the time. I've ruled out the hardware issue and the networking issue. In the game, the debug profiler pie graph shows nothing weird. I've also tried increasing the memory to >2G and adding some more JVM tunings, no help.

The lagging starts right after the server starts, without any player log in yet. I ran out of ideas, does anyone else have this issue lately?

**Comment by itzg** [comment]
Please report this issue to Mojang. The docker image/container has no influence over performance.

**Comment by artemave** [comment]
I am seeing the same issue. @Linightz have you got to the bottom of this by any chance?

**Comment by artemave** [comment]
Ok. Apparently vanilla mc server (default one) is not very performant. I switched to papermc (start container with `TYPE=PAPER`) and the problem has gone. Quite an impressive performance boost all around.
