### ISSUE TITLE
Unable to find java 16 install (ubuntu 20.04 headless)

### ISSUE THREAD

**Issue by cootshk** [itzg/docker-minecraft-server#928]
I was trying to upgrade my server to Minecraft 1.17. The server starts as usual, but then crashes and says " Mod 'Minecraft' (minecraft) requires version 16 or later of mod 'OpenJDK 64-Bit Server VM' (java), but a non-matching version is present: 8!". I apt-installed java 16, but I still get this error. The server is running fabric with no mods (I removed the mods to see if it would start). The server starts fine if I export it from my ubuntu headless vm onto a ds918 (and change the setting to version 1.16.5).

**Comment by cootshk** [comment]
logs:
![image](https://user-images.githubusercontent.com/83678457/122679093-5a013a80-d19e-11eb-9b83-96fa90c85c15.png)

**Comment by itzg** [comment]
The java you have apt-installed on your host is irrelevant. The pointer of Docker is that the image brings its own java.

Re-pull the latest image or use `itzg/minecraft-server:java16` to be sure you're doing things right:

https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version

**Comment by cootshk** [comment]
this worked, thank you!
