### ISSUE TITLE
aarch64 for Java16 openj9

### ISSUE THREAD

**Issue by Panderine** [itzg/docker-minecraft-server#930]
Would you be so kind to add aarch64 for Java16 openj9 to the container?

https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.1%2B9_openj9-0.26.0/OpenJDK16U-jre_aarch64_linux_openj9_16.0.1_9_openj9-0.26.0.tar.gz

Thanks!!

**Comment by itzg** [comment]
They need to publish the image for it before I can make use of it:

![image](https://user-images.githubusercontent.com/988985/122830952-c23f4180-d2ae-11eb-8dc3-ea2826c8dd3e.png)

from [here](https://hub.docker.com/layers/adoptopenjdk/library/adoptopenjdk/16-openj9/images/sha256-1df1ea39a6e0b3fad018ebffeb5af5731d5e9ecee27a3c17dd5fb2eb229c4fa7?context=explore)
