### ISSUE TITLE
Autopause does not work on synology

### ISSUE THREAD

**Issue by belleDESiRE** [itzg/docker-minecraft-server#935]
docker image, tag 'latest'
spigot 1.17, java 16
synology ds1019+ (64 bit)
eth0 interface available in container, docker mode bridged

max-tick-time set to -1
rcon enabled with password, both in server.properties as well as in docker env vars
outside rcon port not mapped to container
using non-default uid and gid
autopause enabled, default settings

I am seeing one log entry: "[init] Autopause functionality enabled"
After that no more logentries related to autopause and spigot is not stopped

Tried to run knockd in debug mode and I see output when connecting and disconnecting

Any ideas?

**Comment by itzg** [comment]
cc @Oekn5w

**Comment by galadril** [comment]
I'm having the same issue. Any fix for it?

**Comment by belleDESiRE** [comment]
could it be that it needs one of the cap-add flags on synology for this to work?

**Comment by recqup** [comment]
Hi, I think I have found the problem.

If you have the _UID_ variable set, the _autopause-daemon.sh_ script runs with user _minecraft_. On this script _knockd_ is called with _sudo_, which in this situation prompts the user for a password.
This prompt is not shown on the main terminal, and the autopause script just get stuck there.

Not sure if this is the right way, but I solved it adding a _NOPASSWD_ entry on the container's _/etc/sudoers_:

`minecraft ALL=(ALL) NOPASSWD: /usr/sbin/knockd`

**Comment by belleDESiRE** [comment]
indeed I have the uid (and gid) parameters set

**Comment by recqup** [comment]
Actually, there is currently a very similar line on _/etc/sudoers.d/sudoers-mc_:

`%minecraft ALL=(ALL) NOPASSWD:/usr/sbin/knockd`

Which gives the permission to the _minecraft_ _group_ instead of the _minecraft_ _user_

Surely this works on the normal case, but in my case, the user _minecraft_ does not belog to the group _minecraft_

```
root@itzg-minecraft-server:/# groups minecraft                                                                                                                                              
minecraft : users
```
```
root@itzg-minecraft-server:/# getent group minecraft                                                                                                                                        
minecraft:x:100:             
```                                                                                                                                                                    
```                                                                                                                                                                   
root@itzg-minecraft-server:/# id -u minecraft                                                                                                                                               
1035  
```
I have the variables set as: _UID=1035, GID=100_

Giving sudo permission to the _user minecraft_ works, but I'm not sure which is the proper solution.

**Comment by belleDESiRE** [comment]
Adding the minecraft user to the sudoers-mc file fixes this for me also

**Comment by davels** [comment]
When I set _GID=100_ for the container I see this in /etc/group
```
users:x:100:
minecraft:x:100:
```
I think this is what's causing the issue, since the minecraft user is a member group 100.
Changing sudoers-mc to to match by user instead group was the easiest solution for me.

**Comment by belleDESiRE** [comment]
bump

**Comment by Oekn5w** [comment]
Sounds good, I don't know why I went with the group matching in the first place.
However, is the minecraft user properly assigned to the minecraft group? Reading the two issues, this might not be the case, although I didn't look thoroughly into this just now.

**Comment by itzg** [comment]
@davels or @Oekn5w can you create a PR for that?
