### ISSUE TITLE
Use classpath option

### ISSUE THREAD

**Issue by zvwild** [itzg/docker-minecraft-server#943]
Hello, how can i use the -classpath option? Whenever i pass it to the server using JVM_OPTS, the server complains about the passing of a non existing 'j' option. This is probalby due to -jar getting appended to the end of the command. Is there a solution for this?

**Comment by itzg** [comment]
That worked fine for me:

```
docker run -it -e EULA=TRUE -e JVM_OPTS="-classpath somewhere/" -e DEBUG_EXEC=true itzg/minecraft-server
```

from debug output:
```
+ exec mc-server-runner --stop-duration 60s java -Xms1G -Xmx1G -classpath somewhere/ -jar minecraft_server.1.17.jar
```

**Comment by zvwild** [comment]
For the classpath option to work you need to give it the main class of your program, -jar and -classpath at the same do not work

**Comment by itzg** [comment]
Good point, they usually can't but so far Java 16 might be allowing it.

**Comment by itzg** [comment]
>  Whenever i pass it to the server using JVM_OPTS, the server complains about the passing of a non existing 'j' option

What you're encountering is different than the what used to happen when combining classpath and jar arguments. What exact `docker run` or compose file are you trying?

Also, I'm curious what why you're needing to add to the classpath. Maybe there's a different way to solve the original use case.

**Comment by zvwild** [comment]
Hello, i need the classpath option in order to load additional libraries (e.g mongodb and redis drivers) for my plugins. I've solved it now by editing the the start-minecraftFinalSetup. But of course, that isn't ideal. My suggestion would be to add kind of a "RUN_COMMAND" environment variable or something similar so that other people who have a similar problem won't have to create fat jars.

**Comment by itzg** [comment]
What does your modification look like? Also, what plugin(s) are you using? I'm wondering why they're not doing things like shading the client libraries in with their own plugin jar.

**Comment by zvwild** [comment]
The plugins are our custom-made ones, I didn't shade the libraries because I found this to be a more maintainable way if one library needs an update, otherwise I would have to recompile every plugin. The modification is just a swap of - jar with -cp and the main class that comes after the classpath declaration at the end of the file where the start command is executed.

**Comment by itzg** [comment]
While what you're asking is an easy change, I am not happy about adding it since the usability quickly gets challenging. Someone has to extract the `META-INF/MANIFEST.MF` to find the appropriate main class since it varies by server type, such as Paper's:

```
Manifest-Version: 1.0
Main-Class: io.papermc.paperclip.Paperclip
Multi-Release: true
Launcher-Agent-Class: io.papermc.paperclip.Agent
Premain-Class: io.papermc.paperclip.Agent
```

and even then launching with `-cp paper-1.17-75.jar io.papermc.paperclip.Paperclip` fails with

```
Unable to retrieve Instrumentation API to add Paper jar to classpath. If you're running paperclip without -jar then you also need to include the -javaagent:<paperclip_jar> JVM command line option.
```

Now I have to add the `-javaagent` arg. All of this is quite familiar to me since I have developed in Java for 25 years, but someone new to Docker/Java will be quickly overwhelmed.

I have never heard of a plugin/mod requiring `-classpath` customization since I'm guessing they all use `URLClassLoader` to dynamically load additional jars. Since this is your custom plugin, please investigate that approach. 

You're also welcome to build an image that extends from this one.

I'll leave this issue open to think about it some more.

**Comment by itzg** [comment]
Out of curiosity I also looked at Forge's manifest and the situation is even worse:

```
Manifest-Version: 1.0
Git-Branch: 1.16.x
ServerLaunchArgs: --gameDir . --launchTarget fmlserver --fml.forgeVers
 ion 36.1.0 --fml.mcpVersion 20210115.111550 --fml.mcVersion 1.16.5 --
 fml.forgeGroup net.minecraftforge
Class-Path: libraries/org/ow2/asm/asm/9.0/asm-9.0.jar libraries/org/ow
 2/asm/asm-commons/9.0/asm-commons-9.0.jar libraries/org/ow2/asm/asm-t
 ree/9.0/asm-tree-9.0.jar libraries/org/ow2/asm/asm-util/9.0/asm-util-
 9.0.jar libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar l
 ibraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar libraries/c
 pw/mods/grossjava9hacks/1.3.0/grossjava9hacks-1.3.0.jar libraries/net
 /minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar li
 braries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar librarie
 s/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar libraries/net/
 minecraftforge/coremods/4.0.6/coremods-4.0.6.jar libraries/net/minecr
 aftforge/unsafe/0.2.0/unsafe-0.2.0.jar libraries/com/electronwill/nig
 ht-config/core/3.6.3/core-3.6.3.jar libraries/com/electronwill/night-
 config/toml/3.6.3/toml-3.6.3.jar libraries/org/jline/jline/3.12.1/jli
 ne-3.12.1.jar libraries/org/apache/maven/maven-artifact/3.6.3/maven-a
 rtifact-3.6.3.jar libraries/net/jodah/typetools/0.8.3/typetools-0.8.3
 .jar libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.
 11.2.jar libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-c
 ore-2.11.2.jar libraries/net/minecrell/terminalconsoleappender/1.2.0/
 terminalconsoleappender-1.2.0.jar libraries/net/sf/jopt-simple/jopt-s
 imple/5.0.4/jopt-simple-5.0.4.jar libraries/org/spongepowered/mixin/0
 .8.2/mixin-0.8.2.jar libraries/net/minecraftforge/nashorn-core-compat
 /15.1.1.1/nashorn-core-compat-15.1.1.1.jar libraries/net/minecraft/se
 rver/1.16.5-20210115.111550/server-1.16.5-20210115.111550-extra.jar
Timestamp: 2021-03-15T22:14:26+0000
GitCommit: 5c488c90
Main-Class: net.minecraftforge.server.ServerMain
```

I'd have to add all of the jars in `Class-Path` to the `-cp` arg.

**Comment by zvwild** [comment]
You're right, adding such an option would certainly drive up complexity, its probably a better option for everyone to just modify the start script as i did for one's own purposes.
