### ISSUE TITLE
A problem installing the server was detected, server install cannot continue

### ISSUE THREAD

**Issue by codevski** [itzg/docker-minecraft-server#945]
![image](https://user-images.githubusercontent.com/1435321/124297971-0da2fb00-db9f-11eb-9ad0-ff1eaa815693.png)

Fresh install.
Image: itzg/minecraft-server:java8
Env:
- TYPE=FORGE
- VERSION=1.12.2
- FORGEVERSION=14.23.5.2838
- EULA=TRUE

If I try to wget direct version with the jar file in the folder I get the same error... Not sure what else to check logs don't say much

java.net.preferIPv4Stack=true
Installing server to current directory
A problem installing the server was detected, server install cannot continue

Manually adding installer file:
![image](https://user-images.githubusercontent.com/1435321/124299154-73dc4d80-dba0-11eb-8f9f-d26be82d4f42.png)

**Comment by itzg** [comment]
That message is coming from the forge installer, so I'm not sure what it means either.

**Comment by codevski** [comment]
Okay no problem, since its a Forge issue I will close this.
