### ISSUE TITLE
Doubled escapes in first entry in server.properties

### ISSUE THREAD

**Issue by oldium** [itzg/docker-minecraft-server#949]
The following `echo` command doubles backslashes, which is not necessary as in the case few lines up with `sed`:

https://github.com/itzg/docker-minecraft-server/blob/c090095e08d29f822ff45d98774bdf7abd6ecec0/start-finalSetupServerProperties#L22

This results in the following `server.properties` file with `SERVER_NAME` environment variable value `Old\u016Fv server`:

```
server-name=Old\\u016Fv server
```

**Comment by P4sca1** [comment]
> which is not necessary as in the case few lines up with `sed`

`sed` requires double backslashes. See https://github.com/itzg/docker-minecraft-server/issues/446

**Comment by oldium** [comment]
> > which is not necessary as in the case few lines up with `sed`
> 
> `sed` requires double backslashes. See #446
> 
> **Edit:**
> I think I misunderstood your sentence. You meant that it is required for `sed`, but not for `echo` right?

Yes, exactly 😀. `sed` needs it, `echo` does not.

> This results in incorrect double backslashes when the `server.properties` file gets created the first time (or the specific prop did not exist before).
> Restarting the server with the `OVERRIDE_SERVER_PROPERTIES=true` env var set will fix the issue.

Perfect, thanks for the hint. I am using named volumes, so I mounted the volume to another container and edited `server.properties` directly with Midnight Commander.

**Comment by P4sca1** [comment]
@oldium I created a pull request #954, which should fix this issue. Would be great, if you could review it.
