### ISSUE TITLE
titan 1.0

### ISSUE THREAD

**Issue by MartinBrugnara** [itzg/docker-minecraft-server#95]
Hi, 
are you planning to upgrade to titan 1.0?

**Comment by itzg** [comment]
Yes :) just need to make the time to do it. At the same time you're welcome to contribute a PR.

**Comment by MartinBrugnara** [comment]
I totally understand you, I will try if I find the time myself.
In the mean time, thank you for you great work!
-- Martin Brugnara

**Comment by itzg** [comment]
I had forgotten that I started on an upgrade here https://github.com/itzg/dockerfiles/tree/titan-1.0.0-upgrade/titan-gremlin

I'll have to see where I left off with that.
