### ISSUE TITLE
Loading wrong mc version

### ISSUE THREAD

**Issue by MashaGaming** [itzg/docker-minecraft-server#952]
VERSION env variable set to 1.17 yet container loads 1.17

`[init] Resolved version given 1.17 into 1.17`
`[15:21:55] [main/INFO]: Loading for game Minecraft 1.17.1`
`[15:21:55] [main/FATAL]: A critical error occurred`
`net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: voicechat requires {minecraft @ [1.17]}`

**Comment by joshschmille** [comment]
If you got around this, what was the solution?
