### ISSUE TITLE
-v :/DATA does not work after getting failed to download from https://cdn.getbukkit.org/spigot/spigot-1.17.1.jar

### ISSUE THREAD

**Issue by teknowill** [itzg/docker-minecraft-server#958]
tried -e SPIGOT_DOWNLOAD_URL=https://download.getbukkit.org/spigot/spigot-1.17.1.jar

this got it to update, but it ignores my existing world files and make a new one

also tried-e VERSION=1.17
, but it ignores my existing world files and make a new one as well

before in version 1.17 spigot
docker run -d -v /mnt/c/minecraft/data:/data \
-e TYPE=SPIGOT \
-e MEMORY=8G \
-p 25565:25565 -e EULA=TRUE --name mc itzg/minecraft-server

worked fine. 
but I cannot start this mc container as it fails to download latest,

with this
docker run -d -v /mnt/c/minecraft/data:/data -e SPIGOT_DOWNLOAD_URL=https://download.getbukkit.org/spigot/spigot-1.17.1.jar -e TYPE=SPIGOT -e MEMORY=8G -p 25565:25565 -e EULA=TRUE --name mc17 itzg/minecraft-server 

gets the newest minecraft spigot, it's mounts /mnt/c/minecraft/data:/data 
but the docker server won't use it, just makes a new world file else where within the container

suggestion, if it can't download latest:
just load the existing jar, don't kill the server
and/or let the user overwrite the jar file by keeping the run file name the same, regardless of version so one can just copy over the file in the data folder without breaking config, 

what's preventing it from using a /DATA folder with a new container id / name even though mounted?
I tried making a new folder and it mounts it but still it won't interact

**Comment by itzg** [comment]
I pushed a fix to the image that uses the new `https://download.getbukkit.org` URL base.

As for the rest of your issues, I can't offer any advice without seeing more log output, screenshots, and etc.

**Comment by itzg** [comment]
I'm going to close this issue since you opened #969 for your ongoing questions
