### ISSUE TITLE
download.getbukkit.org doesn't work for 1.15.2

### ISSUE THREAD

**Issue by halogod35** [itzg/docker-minecraft-server#962]
I pushed a fix to the image that uses the new `https://download.getbukkit.org` URL base.

As for the rest of your issues, I can't offer any advice without seeing more log output, screenshots, and etc.

_Originally posted by @itzg in https://github.com/itzg/docker-minecraft-server/issues/958#issuecomment-876418532_

I have to create a SPIGOT_DOWNLOAD_URL environment variable and set the address to https://cdn.getbukkit.org/spigot/spigot-1.15.2.jar with this latest image.

The error I get is 
`Downloading Spigot from https://download.getbukkit.org/spigot/spigot-1.15.2.jar ... 
curl: (22) The requested URL returned error: 404 Not Found`

**Comment by itzg** [comment]
Oh, now getbukkit is being really annoying 😕  I guess I need to change that back since they must have reverted something on their side.

**Comment by itzg** [comment]
...weirder still, it looks like they switched to "download." at 1.16.5

**Comment by itzg** [comment]
The latest image will now pick the download URL based upon the VERSION.
