### ISSUE TITLE
Error: Invalid or corrupt jarfile minecraft_server.1.17.1.jar

### ISSUE THREAD

**Issue by ghcrow** [itzg/docker-minecraft-server#965]
Unsure whether this is a me issue, or one with the image for the latest jar update - I manage everything through Portainer.

Vanilla server - runs fine in 1.17 - have tested with setting `VERSION` to 1.17 and it boots up OK. However when using `VERSION` of LATEST, I get the following error:

```
[init] Starting the Minecraft server...,
Error: Invalid or corrupt jarfile minecraft_server.1.17.1.jar,
2021-07-09T19:58:34.438Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1},
2021-07-09T19:58:34.439Z	INFO	mc-server-runner	Done
```

It will then be stuck in an infinite loop of the start up script re-running and entering into the same issue.

The container health check comes back as unhealthy. I have tried re-deploying the container too do that a new image is rebuilt and the same happens every time. As it works with 1.17, but not with 1.17.1, and I keep everything the same and just restarted the container to upgrade earlier, I can't see what it is that I would be missing. 

Any ideas / suggestions would be much appreciated!

**Comment by itzg** [comment]
Did you double check by creating a new container with a fresh data volume? 1.17.1 starts fine for me, so you simply have a corrupted file. Delete it and let the container re-download it.

**Comment by ghcrow** [comment]
Great thanks - my misunderstanding that redeploying the container and creating a new image wouldn't automatically create a new volume. Thanks for your help! Expected it would be a me issue, learn something new every day.

**Comment by ghcrow** [comment]
One final thing - the new volume obviously doesn't contain the data files of the old volume (world data etc.). Is this something I need to move across myself from old to new volume?

**Comment by itzg** [comment]
The suggestion of a new container+volume was just for sanity testing. I'd recommend keeping your existing data volume and just delete the corrupted `minecraft_server.1.17.1.jar` file.

**Comment by ghcrow** [comment]
Thanks! All sorted.
