### ISSUE TITLE
java.base bootstrap loader fail on modded

### ISSUE THREAD

**Issue by iiLeia** [itzg/docker-minecraft-server#966]
I have no issues when launching a vanilla server, however when I try launching one using Forge, Curseforge, or FTB, I recieve the same crash message:
![image](https://user-images.githubusercontent.com/83024773/125168158-fdc48180-e171-11eb-8c70-c4badaf75c20.png)

If anyone knows how to resolve the issue or where it comes from the help is greatly appreciated!
I have tried using both the itzg/minecraft-server:latest and itzg/minecraft-server:java16 since I saw some with similar but not identical issues, however have had the same outcome from both containers.

**Comment by itzg** [comment]
Right line of thought but go the other direction and try itzg/minecraft-server:java8 since latest is also Java 16.

**Comment by iiLeia** [comment]
Worked! Thanks!
