### ISSUE TITLE
[Paper]: /start-spiget: Resource '${$resource}' already downloaded: bad substitution

### ISSUE THREAD

**Issue by SILENCE-ETERNAL** [itzg/docker-minecraft-server#981]
When using Spiget to download plugins for a type=paper server, the docker instance exits on the following failure:

```
...
[init] Downloading PaperMC 1.17.1 (build 111) ...
[init] Getting plugins via Spiget
[init] Downloading resource 274 ...
/start-spiget: line 32: Resource '${$resource}' already downloaded: bad substitution
mc exited with code 1
```
My relevant docker-compose.yml lines:
```
environment:
 - TYPE=PAPER
 - SPIGET_RESOURCES=274,1331
```
If I go delete the files .1331 and .274 from the plugins/ directory, the container will start properly once, then the next restart will fail again. 

I'm wondering if this is related to the recent commit #974, as this only started happening today since I pulled the latest docker image (my last image was ~6 days old).

**Comment by itzg** [comment]
Yes, it looks like it's from that commit. I'll fix it shortly.

**Comment by itzg** [comment]
The latest image includes the fix for this.

**Comment by SILENCE-ETERNAL** [comment]
Perfect, that does it! Thanks for the quick fix!
