### ISSUE TITLE
Replace env vars in parallel

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-minecraft-server#983]
Currently, replacing env variables takes a *very* long time, presumably because it's checking all files for each variable rather than checking all files for all variables at once.
https://github.com/itzg/docker-minecraft-server/blob/75f5a430e48e85f24e8339aba8c00ecd70ba2366/start-finalSetupEnvVariables#L36

**Comment by ChipWolf** [comment]
Pixelmon mod generates thousands of jsons, I've excluded that dir with `REPLACE_ENV_VARIABLES_EXCLUDE_PATHS` for now

**Comment by ChipWolf** [comment]
This is still an issue occasionally, I think we could make this significantly faster by getting a list of files that contain the ${CFG_...} string first, then using that list for subsequent replacements.

**Comment by ChipWolf** [comment]
This is still an issue occasionally, I think we could make this significantly faster by gathering a list of files that contain the ${CFG_...} string first, then using that list for subsequent replacements @itzg

**Comment by itzg** [comment]
To address https://github.com/itzg/docker-minecraft-server/issues/987 I'm writing the solution in Java as a multi-purpose image-helper tool. My next step was going to be swapping out the in-place file interpolation, so that'll speed up this whole process.

**Comment by itzg** [comment]
> I've excluded that dir with `REPLACE_ENV_VARIABLES_EXCLUDE_PATHS` for now for a significant speed improvement

...however, the exclude paths is probably the more correct solution in most cases. Having done development for a looong time, I have found that doing things in parallel is not always the best answer. So set your expectations accordingly 😉

**Comment by itzg** [comment]
The latest image and variants now includes the feature changes. Feel free to re-open this issue if needed.

If you happen to be able to grab some before and after timings I would be curious what speedup (and hopefully not slowdown) was gained.
