### ISSUE TITLE
spigot image not downloadable

### ISSUE THREAD

**Issue by SamuelWhittle** [itzg/docker-minecraft-server#984]
When running the docker container based on your example spigot docker-compose, searches https://cdn.getbukkit.org/spigot/spigot-1.17.1.jar (as of this issue).

The issue I am having is that that weblink does not seem to point to an accessible spigot jar, if I go the website in chrome it says not publicly accessible, I also went to the bukkit website to confirm and the download like for 1.17.1 seemed to be the same as above but with "download" instead of "cdn".

Is this just a me thing?

**Comment by itzg** [comment]
Make sure to re-pull the latest image. That issue was fixed recently and now varies the download URL based on version. For example, it's now

```
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 4096 Jul 14 23:43 /data'
[init] Resolved version given LATEST into 1.17.1
[init] Resolving type given SPIGOT
[init] Downloading Spigot from https://download.getbukkit.org/spigot/spigot-1.17.1.jar ...
```

**Comment by SamuelWhittle** [comment]
Thank you sir I did not realize that I needed to remove and re-add the docker image I thought the docker compose up command automatically searched for that.

All is working!

**Comment by itzg** [comment]
Ah, if you're using docker compose then `docker-compose pull` will take of upgrading the image. Then the next `docker-compose up` will update the container with that image.
