### ISSUE TITLE
Unable to access jarfile forge-1.6.4-9.11.1.1345-universal.jar

### ISSUE THREAD

**Issue by clock-boy** [itzg/docker-minecraft-server#986]
I'm trying to run a 1.6.4 server and I'm using forge 9.11.1.1345 instead of 9.11.1.965 because I saw a post on how old installers don't work anymore but 9.11.1.1345 did. Whenever I start the server it gets past the connectivity check and repeats the message below until it stops due to crashes.

Starting server
Error: Unable to access jarfile forge-1.6.4-9.11.1.1345-universal.jar
Server will restart in ~10 seconds. No input needed...
Skipping internet connectivity check
Rebooting now!

**Comment by itzg** [comment]
Can you provide more details about how you created your container?

**Comment by carltibule** [comment]
Hello there,

I'm having the same issue, trying to install 1.17.1 with Forge Version 37.0.0. Here's the log: [https://pastebin.com/J5dfy7ae](url)
After that it will spit out a few lines then say: "Unable to access jarfile *forge*.jar. Looking at the folder where everything is it seems to have created libraries and mods folder, but the forge.jar (not even the vanilla minecraft jar) files are nowhere to be seen at the root. 

I've tried deleting the .forge-installed file as mentioned in one of the earlier issues of the same nature, and restarting the container, to no avail. I've also tried various things like not specifying the minecraft and forge version, going for 37.0.0.1, among other things but no luck.

**Comment by itzg** [comment]
@carltibule can you provide more details about how you created your container?

**Comment by carltibule** [comment]
For sure! I usually deploy mine using Docker Compose, on Portainer. Here's what my compose file looks like: [https://pastebin.com/smZ92kiZ](https://pastebin.com/smZ92kiZ)

It seems to work fine if it's just a vanilla installation though, only fails when it's forge.

**Comment by clock-boy** [comment]
I am using docker compose

**Comment by kaelfischer** [comment]
I believe I have a similar issue, but can open a new one if that's better.
Goal: mc version 1.17 with Forge.

Container creation:
``$ docker run -d -v <my favorite_path>/MC_1_17_1:/data -it -e EULA=TRUE -e OPS=<user1>,<user2>,<user3> -e WHITELIST=<user1>,<user2>,<user3> -e ALLOW_NETHER=true -e VERSION=1.17.1 -e TYPE=FORGE -e MEMORY=4G -p 25560:25565 --name MC_1_17_1 itzg/minecraft-server:java8``

Forge installer log finishes:
`` The server installed successfully
You can delete this installer file now if you wish``

Forge .jars seem to exist:
``$ find . -iname 'forge-*.jar'``
``./libraries/net/minecraftforge/forge/1.17.1-37.0.1/forge-1.17.1-37.0.1-universal.jar``
``./libraries/net/minecraftforge/forge/1.17.1-37.0.1/forge-1.17.1-37.0.1-server.jar``

Yet, the server log says: **Error: Unable to access jarfile *forge*.jar**

``$ docker logs -f MC_1_17_1 | tail``
``[init] Setting level-name to 'world' in /data/server.properties``
``[init] Setting online-mode to 'true' in /data/server.properties``
``[init] Updating ops``
``[init] Updating whitelist``
``[init] Checking for JSON files.``
``[init] Setting initial memory to 4G and max to 4G``
``[init] Starting the Minecraft server...``
``Error: Unable to access jarfile *forge*.jar``
``2021-07-23T22:27:22.393Z	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}``
``2021-07-23T22:27:22.393Z	INFO	mc-server-runner	Done``

**Comment by itzg** [comment]
Oh, they made a major change to their installer and are using Java jigsaw modules. Now it drops a `run.sh` that contains

```
java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.17.1-37.0.2/unix_args.txt
```

and `libraries/net/minecraftforge/forge/1.17.1-37.0.2/unix_args.txt` contains a bunch of critical arguments. 

This is going to take a fair bit of redesign in my startup script :(

**Comment by itzg** [comment]
...I spoke way too soon. The latest image now supports their run.sh mechanism.

Now, @clock-boy the 1.17 behavior is probably totally different from your original issue. Specifically I was needing to know what environment variables you set, but maybe it's basically TYPE=FORGE and VERSION=1.6.4?

**Comment by itzg** [comment]
@clock-boy this started up fine for me:

```
docker run -it -p 25565:25565 -e EULA=TRUE -e TYPE=FORGE -e VERSION=1.6.4 itzg/minecraft-server:java8
```

and it looks like it actually grabbed `9.11.1.1345` as the forge version.

**Comment by carltibule** [comment]
Just tested again, still having the same issue as before. The change has not been released yet I suppose?

**Comment by itzg** [comment]
> Just tested again, still having the same issue as before. The change has not been released yet I suppose?

The 1.17.1 fix is fully released -- make sure you have pulled the latest image. `docker-compose pull` in your case.

**Comment by carltibule** [comment]
> 
> The 1.17.1 fix is fully released -- make sure you have pulled the latest image. `docker-compose pull` in your case.

Forgot to provide an update but it's working for me now. Thank you!
