### ISSUE TITLE
Typo in current table of contents

### ISSUE THREAD

**Issue by Jafner** [itzg/docker-minecraft-server#988]
![image](https://user-images.githubusercontent.com/40403594/126879422-015dbcde-e97c-4fa7-ba64-aff5c3fe942a.png)
The "Running a server with a CurseForge modpack" header should have sub-headers of "Modpack data directory", "Buggy start scripts", and "Fixing 'unable to launch forgemodloader'"
Instead, it looks like some linebreaks are missing.

**Comment by itzg** [comment]
Good catch. I had some incorrect header levels under that section and the TOC generator didn't like that.
