### ISSUE TITLE
Please make sure you are using the server version of the FTB modpack error.

### ISSUE THREAD

**Issue by TahoeBennie** [itzg/docker-minecraft-server#992]
I am completely new to synology/docker and I have no idea what it is trying to tell me when it says to use the server version of the ftb modpack, the modpack I am trying to use is Stacia Expert
https://www.curseforge.com/minecraft/modpacks/stacia-expert/files/3393840
I don't know what to do for this error because it has gotten as far as knowing the modpack it is meant to be using, and that is the extent of my knowledge for this error. I would like to know how to fix this as I am just trying to run a modded server on my synology for my brother and I to play, but I cannot get past this.
Sorry if I do not seem like I know very much about this as I am completely new to everything remotely related to docker.
I have already browsed other issues of this same error but I have no idea how to import a script whilst trying to setup the running of the server for the first time, so it doesn't help me.

**Comment by itzg** [comment]
I don't think I have tried out that modpack myself, but a couple of things to double check:
- Make sure you grabbed the "server" file located in the "Additional Files" section 
![image](https://user-images.githubusercontent.com/988985/128052532-98e092b5-98d0-4a73-b993-ac2216d47b36.png)
- If you used the server file, then try using [the option described here](https://github.com/itzg/docker-minecraft-server#buggy-start-scripts)

**Comment by TahoeBennie** [comment]
I tried to use the server file in the additional files but I just worked around it with instead of grabbing the link for the modpack, I just use a regular forge server and add the necessary mods, thanks though.

**Comment by 19wolf** [comment]
I'm having this issue as well, with this mod- https://www.curseforge.com/minecraft/modpacks/medieval-minecraft-modpack/files/3406762

**Comment by Vistritium** [comment]
I have the same issue, should this issue be reopened?
