### ISSUE TITLE
GENERATOR_SETTINGS too much escaping

### ISSUE THREAD

**Issue by DanielRamp** [itzg/docker-minecraft-server#999]
The [environment variable ``GENERATOR_SETTINGS``](https://github.com/itzg/docker-minecraft-server#level-type-and-generator-settings) does not [function](https://github.com/itzg/docker-minecraft-server/blob/cbaef446ac4f3e7d559dbce98539e9449b92356c/start-finalSetupServerProperties#L84) properly.
(The [function ``setServerProp``](https://github.com/itzg/docker-minecraft-server/blob/327f21f1bbc8328ac35c89fffe4cabbafba14d31/start-finalSetupServerProperties#L8-L27) escapes `\` the colon `:` but that is not wanted in this scenario)

the running ``server.properties`` contains:
```
generator-settings=minecraft\:air;minecraft\:the_void
```
if used ``GENERATOR_SETTINGS=minecraft:air;minecraft:the_void``

**Comment by itzg** [comment]
Are you sure that's not getting modified after the Java server process has started? Java properties processing has more aggressive escaping, which is why I'm double checking. 

Please add DEBUG=true and provide that output to help confirm when the escaping is happening.

**Comment by smellypengu** [comment]
Having this issue too

**Comment by DanielRamp** [comment]
No I'm unfortunately not really sure where it's getting modified, but I could print out the env var and it was correct, but not the server.properties.

To be able to analyze it easy, I pasted most of the logs onto a gist [here](https://gist.github.com/DanielRamp/6f4aa2a0337e325709ecb8a1fe83e79d#file-1__readme-md).

Lastly I tried using `TYPE=SPIGOT` but same result (instead of paper).

_I hope that helps._

**Comment by itzg** [comment]
Yes, that helped. The debug logs show the file contained the value as given to the script

https://gist.github.com/DanielRamp/6f4aa2a0337e325709ecb8a1fe83e79d#file-2__docker-log-L95

The Minecraft server process itself is adding the escapes, so that's beyond my control.

**Comment by DanielRamp** [comment]
~~It looks like this is even a vanilla server bug:~~
https://gaming.stackexchange.com/questions/352909/what-do-i-put-in-the-generator-settings-area-in-server-properties/352936#352936

-> https://bugs.mojang.com/browse/MC-134900

-> https://bugs.mojang.com/browse/MC-182421

**UPDATE:**
No it isn't, since 1.13 it just needs to be json and not the "text" from the client.
I found [a cool generator site](https://misode.github.io/world/). (WARNING: Need to test if it works; I remove this warning then.)

_If I tested, I might do a pr to the docs here._

**Comment by DanielRamp** [comment]
The [generation site](https://misode.github.io/world/) could be used as an example but I saw that we need to trimm it as described here.

We might get something like this:
```json
{
  "generate_features": false,
  "bonus_chest": false,
  "seed": 0,
  "dimensions": {
    "minecraft:overworld": {
      "type": "minecraft:overworld",
      "generator": {
        "type": "minecraft:flat",
        "settings": {
          "biome": "minecraft:the_void",
          "layers": [
            {
              "block": "minecraft:bedrock",
              "height": 1
            },
            {
              "block": "minecraft:stone",
              "height": 10
            },
            {
              "block": "minecraft:dirt",
              "height": 1
            }
          ],
          "structures": {
            "structures": {}
          }
        }
      }
    }
  }
}
```

but we only need the json object `minecraft:overworld`, like this:
```json
{
  "biome": "minecraft:the_void",
  "layers": [
    {
      "block": "minecraft:bedrock",
      "height": 1
    },
    {
      "block": "minecraft:stone",
      "height": 10
    },
    {
      "block": "minecraft:dirt",
      "height": 1
    }
  ],
  "structures": {
    "structures": {}
  }
}
```

This can be archived by manually trim the file or with this jq command (if the file is named "world_settings.json"):
```bash
jq -c '.dimensions."minecraft:overworld".generator.settings' world_settings.json
```
which will even minify it to one line (nececary for the config file):
```json
{"biome":"minecraft:the_void","layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:stone","height":10},{"block":"minecraft:dirt","height":1}],"structures":{"structures":{}}}
```


_This might be nice to add to the docs/README or even add to the start scripts so that we can just add the downloaded "world_settings.json" file to the /config/ volume and it will trim it._
